### ISSUE TITLE
Icon Request: fa-mate (drink)

### ISSUE THREAD

**Issue by gentilmente** [FortAwesome/Font-Awesome#10075]
hi, argentinian people drink Mate. 
It´s like a tea, but we drink this all the time, it´s a national symbol like tango dance. 
Here are some examples http://www.canstockphoto.com/illustration/yerba-mate.html#file_view.php?id=32060393 
And Obama loves it :-) http://remezcla.com/wp-content/uploads/2016/03/obamate-1150x584.jpg
So the Pope, http://www.agenciafe.com/data/img_cont/img_imagenes/img_gr/108937.jpg.
thank you

**Comment by arielpont** [comment]
Im needing this icon!!! jeje

**Comment by lucas-labs** [comment]
Having this one in font awesome would be great. It's already an emoji btw: 🧉 (`U+1F9C9`)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Comment by csarven** [comment]
I'm not from Argentina, Uruguay, or the region. I looked this up because I thought it would be great to convey the concept of sharing, e.g., for the share button in an authoring application, such as https://git.dokie.li/ . We currently use the bullhorn but find mate would be a lot cooler and fun.

---

Looking at the emoji reactions to the original comment, there are many that would like to see this icon.

If possible, it may be more appropriate to reopen this issue given that an icon request template had the following checkbox:

>I've already [searched through existing issues](https://github.com/FortAwesome/Font-Awesome/issues), and to the best of my knowledge this request isn't a duplicate
