### ISSUE TITLE
Icon request: icon-washstart icon-washdone

### ISSUE THREAD

**Issue by mbugs** [FortAwesome/Font-Awesome#10087]
Hi, all.  Requesting two related icons:

![washstart](https://cloud.githubusercontent.com/assets/22939475/19526263/7ad99748-95e9-11e6-808a-a77831efc163.jpg)

![washdone](https://cloud.githubusercontent.com/assets/22939475/19526246/7511964e-95e9-11e6-9533-6e23782405a3.jpg)

Thanks!

**Comment by tagliala** [comment]
Ref: #5914, #1181

**Comment by mbugs** [comment]
Tagliala, thanks for contributing.  I am new to github, so pardon my ignorance.  You referenced two related icon threads.  Not sure what that means... Could you point me to an online resource that explains how the community works and give me the 5 cent guidelines for a newbie?  Thanks!

**Comment by tagliala** [comment]
A wash machine (requested in #5916) could be combined with actions like `fa-play` and `fa-check` (requested in #1181) to implement the above icons

**Comment by JooStrappin** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
