### ISSUE TITLE
Icon Request: fa-user-search

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#10119]
Need icon for search user.
Try "search user icon" in the google and you will get a lot for sample

**Comment by tagliala** [comment]
Ref: #1181, you will find a solution there

**Comment by megamaiku** [comment]
+1 Saw myself needing this. Thanks.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
