### ISSUE TITLE
Icon Request: fa-users-question

### ISSUE THREAD

**Issue by msivick** [FortAwesome/Font-Awesome#10139]
need an icon for when an item to be worked (like a ticket), has not been assigned to anyone available in the group.

Like this:

![users-unknown-grey](https://cloud.githubusercontent.com/assets/23127779/19820526/caa67058-9d27-11e6-8f19-87df56bcd891.png)

**Comment by tagliala** [comment]
you can use the stacking feature http://fontawesome.io/examples/#stacked or consider fontawesome actions

Slighty refers to: #1131

**Comment by msivick** [comment]
That caused too many bugs for our dev team and implementation.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
