### ISSUE TITLE
Icon Request: fa-2x1

### ISSUE THREAD

**Issue by 79137913** [FortAwesome/Font-Awesome#10147]
2x1

**Comment by tagliala** [comment]
Could you please clarify this request?

Take also a look at our [contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons)

**Comment by 79137913** [comment]
yes, an icon with "2x1" (take 2 pay 1)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
