### ISSUE TITLE
Icon Request: fa-tank or fa_reservoir

### ISSUE THREAD

**Issue by jaroph** [FortAwesome/Font-Awesome#10168]
Hi,

I would like to use a tank/reservoir icon for our website. I searched but could not find such.
Would you be so kind and include one in your icon collection?

Here is preview of wait I have in mind:
![tank-icon](https://cloud.githubusercontent.com/assets/23265636/20016152/a872361a-a2be-11e6-87f3-56f363fe8748.jpg)

Thank you, I really like your project, very cool icons and easy to use!

Kind regards,
Jaro

**Comment by xmuskrat** [comment]
+1

Maybe one empty, too.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
