### ISSUE TITLE
Icon request: icon-user-with-dollar

### ISSUE THREAD

**Issue by gcrome** [FortAwesome/Font-Awesome#10189]
Would be nice to have an icon to specify a client. Maybe a user with dollar sign..

**Comment by tagliala** [comment]
Ref: #1181 , there you will find a solution to generate that icon

by the way, we tend to provide international icons which could be used worldwide. The example you provided is not international because it depends on the currency

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
