### ISSUE TITLE
Icon Request: fa-All-Orders

### ISSUE THREAD

**Issue by newprogrammer** [FortAwesome/Font-Awesome#10195]
Hi All,
Currently I am using an Icon shown below which is an image, which I think is inappropriate.
![all](https://cloud.githubusercontent.com/assets/4718260/20180547/3314d2e6-a75b-11e6-9e1c-1bcaef0b239c.png)

Thanks

**Comment by tagliala** [comment]
What is the use case of this icon?

**Comment by newprogrammer** [comment]
@tagliala Thanks for ur consideration, well I have a small web-based supply chain mgmt where I have different phases like; fresh orders, pending orders, ready to ship orders, shipped orders and ALL Orders.
All Orders is the area where suppliers/clients can see Orders from all phases (which contain all open orders)
like u can see in the image below, currently I used [database icon], which I think is not suitable;
![image](https://cloud.githubusercontent.com/assets/4718260/20209437/b4f33980-a7f4-11e6-845d-ca2b16ad777a.png)

Before I used:
![](https://cloud.githubusercontent.com/assets/4718260/20180547/3314d2e6-a75b-11e6-9e1c-1bcaef0b239c.png)

It would be very nice if you can suggest me better icon/s or if a new icon could be created.

thanks

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
