### ISSUE TITLE
Icon Request: fa-globe-mars

### ISSUE THREAD

**Issue by aresastro** [FortAwesome/Font-Awesome#10200]
With all of the hype around the planet Mars and human missions coming in the near future, it may be time to consider having a Mars globe icon in FontAwesome, and perhaps the other planets at a later date. Here is one that I designed to match the existing fa-globe icon:

![mars](https://cloud.githubusercontent.com/assets/21272680/20207046/bb0136d0-a838-11e6-97ad-e5f66e1fbc64.png)

[mars.pdf](https://github.com/FortAwesome/Font-Awesome/files/585183/mars.pdf)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
