### ISSUE TITLE
Icon Request: icon-drawing (file)

### ISSUE THREAD

**Issue by Warrenrl** [FortAwesome/Font-Awesome#10237]
It would be nice if you could add a drawing icon for use with other file icons.  I use Autocad, if you could use the Autocad icon that would be even better.  Similar to having the PDF icon.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.]()

**Comment by tagliala** [comment]
@sensibleworld can you check the link here? I was not able to link to the correct icon

Is it https://fontawesome.com/icons/file-vector?f=sharp&s=solid ?

**Comment by sensibleworld** [comment]
Yup! I think this could also work: https://fontawesome.com/icons/file-pen?f=classic&s=solid
