### ISSUE TITLE
Icon Request: fa-pdu

### ISSUE THREAD

**Issue by m1rr0r1ng** [FortAwesome/Font-Awesome#10247]
• Power distribution unit (PDU)
• Application for power monitoring

![ic-pdu](https://cloud.githubusercontent.com/assets/15794399/20450837/3827c842-adb9-11e6-983c-5c1af64751d0.png)

**Comment by tagliala** [comment]
the above example is hard to fit at 14px/16px icon size

**Comment by m1rr0r1ng** [comment]
How about this example?

![ic-pdu-2](https://cloud.githubusercontent.com/assets/15794399/20491191/34936cd0-afd6-11e6-83ff-cff4663afd43.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
