### ISSUE TITLE
Icon Request: fa-fahrenheit, fa-celsius

### ISSUE THREAD

**Issue by PassTheMayo** [FortAwesome/Font-Awesome#10241]
Here's what I'm thinking about these icons:

fa-fahrenheit:
   A Fahrenheit superscript, like a degree symbol with a small F after it.

<strike>fa-fahrenheit-o:
    The fa-fahrenheit icon that is surrounded in a circle.</strike>

fa-celsius:
    A Celsius superscript, like a degree symbol with a small C after it.

<strike>fa-celsius-o:
    The fa-celsius icon that is surrounded in a circle.</strike>

<strike>fa-thermometer:
    A small icon of a thermometer like this: [click here](https://www.iconexperience.com/_img/o_collection_png/green_dark_grey/512x512/plain/thermometer.png)

fa-thermometer-o:
    The fa-thermometer icon that is surrounded in a circle.</strike>

Hope this gets added :D

**Comment by tagliala** [comment]
fa-thermometer is here

**Comment by tagliala** [comment]
I will remove the -o versions because they should be `-circle` and you could achieve that with plain css or stack. It will keep this request simpler

**Comment by tagliala** [comment]
Also, the symbols should be `°C` and `°F`

https://en.wikipedia.org/wiki/Celsius#Unicode_character

> Unicode provides the Celsius symbol at codepoint U+2103 ℃ DEGREE CELSIUS. However, this is a compatibility character provided for roundtrip compatibility with legacy encodings. The Unicode standard explicitly discourages the use of this character: "In normal use, it is better to represent degrees Celsius "°C" with a sequence of U+00B0 ° DEGREE SIGN + U+0043 C LATIN CAPITAL LETTER C, rather than U+2103 ℃ DEGREE CELSIUS. For searching, treat these two sequences as identical."[24]

Shown below is the degree Celsius character followed immediately by the two-component version:

℃ °C
When viewed on computers that properly support Unicode, the above line may be similar to the image in the line below (enlarged for clarity):

Unicode degree Centigrade comparison
The canonical decomposition is simply an ordinary degree sign and "C", so some browsers may simply display "°C" in its place due to Unicode normalization.

**Comment by GothShoot** [comment]
Hey guy's
Is implemented ?
