### ISSUE TITLE
icon-request : fa-tv, fa-ova, fa-movie, fa-special

### ISSUE THREAD

**Issue by Kikidy-cam** [FortAwesome/Font-Awesome#10257]
Requesting an icon for each of T.V., O.V.A., Movie & Special.
I would use the icon as a identifier of such, both in a table and in the upper right corner of a information box. 
The icons could I be the letters for its respective classification in a dark rectangle, like git-square or cc-visa, or they could be a TV, a clapperboard, but not sure for special and ova...

**Comment by tagliala** [comment]
since we already have fa-tv http://fontawesome.io/icon/television/

could you please clarify this request providing examples?

Also:
* It is hard to put the "movies/special" text inside a 14/16px icon
* "Movies/Special" depend on language. We are trying to keep icons international
* You can stack text and icon using the current `fa-tv` icon: http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/

**Comment by sensibleworld** [comment]
We now have a `clapperboard` icon, as well as `tv` and `tv-retro`. (Not to mention `film`)
