### ISSUE TITLE
Icon Request: fa-lisk-currency

### ISSUE THREAD

**Issue by punkr0ck** [FortAwesome/Font-Awesome#10252]
Lisk is an open-source blockchain platform for decentralized applications, written in JavaScript. They raised ~14,000 Bitcoins (~10,222,380 USD at today's BTC price) in their ICO phase earlier this year. They are at rank 23 on the [List of highest funded crowdfunding projects](https://en.wikipedia.org/wiki/List_of_highest_funded_crowdfunding_projects). Their currency symbol is:

# Ⱡ
Infos: https://no.wikipedia.org/wiki/%E2%B1%A0

As **Font Awesome** has other relevant currency symbols like Bitcoin already, I would like to see the currency symbol for Lisk, too.

Website: https://lisk.io

**Comment by MaxKK** [comment]
👍🏻

**Comment by densmirnov** [comment]
👍🏻

**Comment by redsn0w0** [comment]
👍🏻

**Comment by Lamaras** [comment]
👍🏻

**Comment by battyKit** [comment]
👍🏻

**Comment by metal494** [comment]
Thumbs UP!

**Comment by Gr33nDrag0n69** [comment]
As a user of both font-awasome and lisk, I totally approved the idea.

**Comment by karek314** [comment]
👍🏻

**Comment by tharude** [comment]
👍

**Comment by Magentobooker** [comment]
👍

**Comment by staticinstance** [comment]
👍

**Comment by vstet** [comment]
:thumbsup:

**Comment by pcdinh** [comment]
Good idea

**Comment by noparanoia** [comment]
good

**Comment by alepop** [comment]
We need this!

**Comment by ducktank1990** [comment]
Ⱡ

**Comment by TheBlaineMono** [comment]
👍

**Comment by shuhad97** [comment]
Yes Please!  👍

**Comment by shilch** [comment]
+1
What about the Lisk Icon?

**Comment by Desdeney** [comment]
why not :D

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
