### ISSUE TITLE
Icon Request: fa-kwh

### ISSUE THREAD

**Issue by m1rr0r1ng** [FortAwesome/Font-Awesome#10261]
• Icon for kWh usage
• Icon used in device management software

![icon175x175](https://cloud.githubusercontent.com/assets/15794399/20491452/0ee543f4-afd7-11e6-83e6-71491567b164.jpeg)

**Comment by tagliala** [comment]
I'm not convinced because we should add all unit of measurements to a tachimeter

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
