### ISSUE TITLE
Icon Request: fa-request

### ISSUE THREAD

**Issue by rathod24** [FortAwesome/Font-Awesome#10266]
Something which defines 'permission request'

**Comment by tagliala** [comment]
Please provide an example

**Comment by timmyrs** [comment]
I think if you stack an arrow up and a question mark you will have something like that.
See [this example](http://fontawesome.io/examples/#stacked) for help with stacking.

**Comment by rathod24** [comment]
@tagliala something like box and written 'Approve' on that, or something like round stamp with text 'Approve'

**Comment by tagliala** [comment]
@rathod24 icons should not contain text, because text is not international.

Also, "approve" is a very long word for a 14/16px icon size

I think that in your use case, [check-circle](http://fontawesome.io/icon/check-circle/) and [times-circle](http://fontawesome.io/icon/times-circle/) should do the job

**Comment by rathod24** [comment]
Ok thanks for suggestion.
