### ISSUE TITLE
Icon Request: fa-desktop-circle-plus

### ISSUE THREAD

**Issue by m1rr0r1ng** [FortAwesome/Font-Awesome#10260]
• Icon for adding a desktop computer/laptop
• Icon used in device management software

![computer_desktop_workstation_pc_game_play_station_server_processor_monitor_display_storage_system_data_node_add_create_insert_plus-512](https://cloud.githubusercontent.com/assets/15794399/20491390/d9179dda-afd6-11e6-83c4-70e23ba59ce0.png)

**Comment by tagliala** [comment]
Related to: #2361 #1181

**Comment by sidpagariya** [comment]
+1

**Comment by aethior** [comment]
Alternative name `computer-circle-plus`.

**Comment by tagliala** [comment]
**In a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/189/

**Heads-up!** Pro customers can also implement this icon with the [Icon Wizard](https://fontawesome.com/v6/docs/web/add-icons/icon-wizard#contentHeader)

![image](https://user-images.githubusercontent.com/556268/221378482-2e081d4b-4c3d-4ac4-87c6-ef6da18a6ff3.png)


Ref:
- https://fontawesome.com/v6/docs/web/style/power-transform
- https://fontawesome.com/docs/web/style/mask
- https://fontawesome.com/docs/web/style/layer
- https://fontawesome.com/v6/docs/web/add-icons/icon-wizard#contentHeader

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
