### ISSUE TITLE
Icon request: recover-corrupted-file

### ISSUE THREAD

**Issue by Bravodin** [FortAwesome/Font-Awesome#10280]
-A icon to recover corrupted files

tyvm ;)

**Comment by tagliala** [comment]
could you please provide an example?

**Comment by Bravodin** [comment]
I think something like that 
![download](https://cloud.githubusercontent.com/assets/3421781/20639956/5e43479e-b3b9-11e6-8b0e-786e4920055a.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
