### ISSUE TITLE
Icon Request: fa-shop-open

### ISSUE THREAD

**Issue by hubca** [FortAwesome/Font-Awesome#10295]
Currently there is no open shop sign to express that something is open for business or to help indicate opening times.

Something simple like this might be best:

[https://thumb1.shutterstock.com/display_pic_with_logo/176167/204495343/stock-vector-open-sign-icon-204495343.jpg](url)

**Comment by aethior** [comment]
Please, remember that icons should be international (without words in any language).

**Comment by tagliala** [comment]
@aethior is right, icon should not contain words because they are hard to render at 14/16px icon size and are not international

We are having issues with numbers, too: #4418

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
