### ISSUE TITLE
icon request: fa-autism

### ISSUE THREAD

**Issue by mcvanderkooij** [FortAwesome/Font-Awesome#10312]
For autism it is very common to use pieces of a puzzle. Something like: https://www.pitt.k12.nc.us/Page/1174   or 
http://www.clipartbest.com/clipart-4cb4LbrMi

This is an Accessibility Icon

**Comment by brunodOut** [comment]
> 
> 
> For autism it is very common to use pieces of a puzzle. Something like: https://www.pitt.k12.nc.us/Page/1174 or
> http://www.clipartbest.com/clipart-4cb4LbrMi
> 
> This is an Accessibility Icon

Despite the fact that people (mostly parents of autistic people and use it and in some places it's an "official" symbol, we don't like this symbol and several people feel offended by it (I include myself here). The puzzle piece gives an idea that we - the autistic - are "complicated", or that our condition is "complex" or a kind of "problem to be solved", and for that reason I would kindly request that you never add it. 

I'd recommend something based on the Neurodiversity Flag, actually used by autistic people as a symbol. 
[https://en.wikipedia.org/wiki/File:Neurodiversity_Symbol.svg](url)

There are some variations for the Autistic Pride Day, like this one:
[https://www.evero.com/wp-content/uploads/2019/06/2606745_0.jpg](url)

There could be one with a neurodiversity flag with the word Autism written in the same style, as neurodiversity encompasses some other neurotypes (i.e. ADHD, dyslexia, etc). 

I'm currently opening a new request for the neurodiversity flag because I kinda need it, but if someone could make a request for the others that would be great!!

**Comment by mcvanderkooij** [comment]
This was the first time I heard people being offended by the puzzle pieces. And with your explanation why I can understand why you feel that way. For myself I'm looking at the puzzle pieces as corresponding to the information flow in my brain which takes more effort to puzzle together into the correct picture.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it doesn't have enough definition. If there's an existing icon/symbol that would work here, we'd love it if someone would open a new request (using our new icon template format). Thanks!
