### ISSUE TITLE
Icon Add: fa-long-arrow-circle

### ISSUE THREAD

**Issue by aayusharyan** [FortAwesome/Font-Awesome#10316]
Long arrows of font awesome icons to be contained in a circle (like normal arrows).

**Comment by tagliala** [comment]
please also consider [stacked icons](http://fontawesome.io/examples/#stacked) or pure css approaches

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
