### ISSUE TITLE
Icon request: fa-wheelchair-yay

### ISSUE THREAD

**Issue by lupodellasleppa** [FortAwesome/Font-Awesome#10331]
Hello there, it's the same guy from the golf carts.

Since the golf cart tours seem to be a very easy way to make disabled people move around, I got this other icon I'd really be happy and honored to have as part of your awesome font. 

![whatsapp image 2016-12-07 at 19 39 37](https://cloud.githubusercontent.com/assets/23663689/20981414/eedb8704-bcb4-11e6-9462-d3553f34eec5.jpeg)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
