### ISSUE TITLE
Icon Request: fa-heromask

### ISSUE THREAD

**Issue by ravenswd** [FortAwesome/Font-Awesome#10358]
I would like to suggest inclusion of a superhero-type mask. There is already an icon for "superpowers." I would imagine this would be used for similar instances. It could also be used to indicate "costume" or "privacy." Or a more directed use of "comics." 

As a big fan of superheroes, I would use it for online events featuring those types of characters, like the Avengers. More specifically, I operate a site (and frequent others) which are dedicated to superheroes and would find something like that useful. 

Here's a general idea of the design:

![mask2](https://cloud.githubusercontent.com/assets/10733055/21142731/295512f8-c109-11e6-98dd-a75a837f3ee9.png)

Thanks for the consideration.

**Comment by ryankane** [comment]
This could also be considered a bandit's mask.

**Comment by caduvieira** [comment]
Refers #1562

**Comment by timdiggins** [comment]
I think this was addressed by #1562  and should be closed.

Here's the mask icon now in FA: https://fontawesome.com/v5.15/icons/mask?style=solid
<img width="142" alt="Screenshot_16_10_2021__08_58" src="https://user-images.githubusercontent.com/18395/137579492-dfe9c26f-6b15-4525-8f09-caa45dd2eb10.png">

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/mask?f=classic&s=solid)
