### ISSUE TITLE
Icon request: icon-vulnerability

### ISSUE THREAD

**Issue by misteranderson** [FortAwesome/Font-Awesome#10353]
Represent vulnerabilities on servers or other devices.

**Comment by tagliala** [comment]
any example?

**Comment by becks256** [comment]
I like this idea.  Maybe the existing server and device icons with an exclamation in the bottom corner contained in a circle? 
![fa-server-alert](https://cloud.githubusercontent.com/assets/22892728/21123645/e6570ada-c0a7-11e6-93de-118f4d4b520f.jpg)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
