### ISSUE TITLE
Icon Request: fa-room

### ISSUE THREAD

**Issue by vgjuvsland** [FortAwesome/Font-Awesome#10388]
An icon for a room on a floor

**Comment by tagliala** [comment]
please provide an example

**Comment by BasicSoft** [comment]
I suggest something like that
![room-icon](https://user-images.githubusercontent.com/25501553/38353429-b08f7260-38b6-11e8-81a7-765520a6aab1.png)

**Comment by tagliala** [comment]
@BasicSoft something more simple, to fit the 16px icon size?

**Comment by martindubenet** [comment]
Instead of a two dimensional view, i sugest a 3D view based on an open view of the (already existing) `fa-cube` where we wopuld just need to add a door-opening to re-inforce the architectural aspect of that 3 sides cube.

![fa-room_mockup](https://user-images.githubusercontent.com/4236385/63126624-4b341600-bf7e-11e9-970f-7fd066a39823.jpg)

**Comment by tagliala** [comment]
No feedback from the opener. Let's use #12064
