### ISSUE TITLE
Icon Request: fa-dash (fa-drk)

### ISSUE THREAD

**Issue by bkimminich** [FortAwesome/Font-Awesome#10450]
![image](https://cloud.githubusercontent.com/assets/3531020/21579601/7fc5f7dc-cfba-11e6-9df4-dc8b72cb8cda.png)

Another crypto currency: https://www.dash.org (formerly "Darkcoin")

**Comment by KVNHNF** [comment]
+1

**Comment by William2030** [comment]
+1

**Comment by KVNHNF** [comment]
no f*ck will ever be given waste of time....instead of waiting for something that won't happen, install icomoon library instead

**Comment by Spindler360** [comment]
Is there any news or results here? I don't want to use icomoon.io or simpleicons.org

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
