### ISSUE TITLE
Icon Request: icon-catering, 

### ISSUE THREAD

**Issue by mamush1234** [FortAwesome/Font-Awesome#10465]
I would very much appreciate it if you would consider adding a "Catering" as used on building sites. We plan to use it in place of a "home" icon to represent represent construction based training ...

**Comment by tagliala** [comment]
Could you please provide an example?

**Comment by mamush1234** [comment]
need catering  Category Icon.

**Comment by tagliala** [comment]
@mamush1234 please take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
