### ISSUE TITLE
Icon Request: fa-gjirafabizz

### ISSUE THREAD

**Issue by kukiboy** [FortAwesome/Font-Awesome#10505]
![logopikbiz](https://cloud.githubusercontent.com/assets/22072727/21838753/26f3c504-d7d4-11e6-8827-582560866dec.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request?

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by kukiboy** [comment]
Hi there!

Gjirafa.bizz is well known business in Kosovo and other parts needs to use Gjirafa.bizz logo on their web sites, flyers, e Magazine....etc.

You may be interested to visit Gjirafa.bizz web site follow the link:
https://gjirafa.biz

Font Awesome Community is growing community by adding this icon you will make happy web designers.

Thank you so much for paying attention.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
