### ISSUE TITLE
Icon Request: fa-christmas-nativity

### ISSUE THREAD

**Issue by GermanKiwi** [FortAwesome/Font-Awesome#10519]
Hi, as I understand it, Font Awesome 5 will include a religious icons set. I'd like to request an icon depicting a Christmas nativity scene, like the example below. Something basic that depicts Mary & Joseph, the manger, the star, and inside a basic stable that has a similar size to the existing Font Awesome house icon. It would be best if it isn't cluttered up with other figures (shepherds, wise men etc) as it would need to look clear in smaller sizes. The example below looks good even when it's very tiny.

![fa-christmas-nativity](https://cloud.githubusercontent.com/assets/1030242/21935079/49cf3174-d9ac-11e6-9934-4ccec354672a.png)

An icon like this would be popular to replace the standard house/home icon on church websites during the Christmas period.

**Comment by tagliala** [comment]
this is almost impossibile to render at 16px font size

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
