### ISSUE TITLE
Icon Request: fa-easter-crosses

### ISSUE THREAD

**Issue by GermanKiwi** [FortAwesome/Font-Awesome#10518]
Hi, as I understand it, Font Awesome 5 will include a religious icons set. I'd like to request an Easter crosses icon for inclusion in that set - something like this, depicting a hill with three crosses on it (ie. representing the scene of the crucifixion of Christ):

![fa-easter-crosses](https://cloud.githubusercontent.com/assets/1030242/21934900/8371d4be-d9ab-11e6-9d14-e52093832208.png)

The hill itself would be better depicted with a simple curved edge, rather than having the bumpy edge shown in the example above.

An icon like this would be popular for church websites during the Easter period.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
