### ISSUE TITLE
Icon Request: fa-lock-undo (reset password)

### ISSUE THREAD

**Issue by VisualBean** [FortAwesome/Font-Awesome#10516]
Ive been needing an icon representing this exactly for some time now, and found one over on the Noun Project website, but would be awesome if something similar could be included into font-awesome.

could also be used for change password.

The noun project one can be found [here](https://thenounproject.com/search/?q=reset&i=12330)

**Comment by ryankane** [comment]
Couldn't you just combine `fa-undo` with `fa-lock`?

```html
<span class="fa-passwd-reset fa-stack">
  <i class="fa fa-undo fa-stack-2x"></i>
  <i class="fa fa-lock fa-stack-1x"></i>
</span> <label>Reset Password:</label>
<input type="password" name="new-passwd" />
```

```css
.fa-passwd-reset > .fa-lock {
  font-size: 0.85rem;
}
```

![passwd-reset](https://cloud.githubusercontent.com/assets/1094151/21896657/2939ab9e-d8b5-11e6-9cba-57506d4d9893.png)

> [**➥ JSFiddle Demo**](https://jsfiddle.net/MrPolywhirl/zschxoam/)

**Comment by Roumed** [comment]
+1

**Comment by metju312** [comment]
+1

**Comment by karsumit94** [comment]
+1

**Comment by redlum94** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
