### ISSUE TITLE
Icon Request: fa-circle-onotch-thin

### ISSUE THREAD

**Issue by tasmanwebsolutions** [FortAwesome/Font-Awesome#10535]
Hello i am using 

`<i class="fa fa-circle-o-notch fa-5x fa-fw"></i>` 

I would like to make a request for a thin version of this icon above. Same thickness as this or thinner http://fontawesome.io/icon/circle-thin/

As in image the icon is quite thick

Thank you

![alt][1]

[1]: https://ibin.co/39Pam1v7L4L1.png

**Comment by tagliala** [comment]
Hi,

nope, unfortunately there is no way of doing that.

Feel free to change the title to `Icon Request: fa-circle-onotch-thin` (as in http://fontawesome.io/icon/circle-thin/)

**Comment by wolfgang1983** [comment]
@tagliala I have changed the title

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/circle-notch?f=classic&s=thin)
