### ISSUE TITLE
Buoy Misspelled - } .fa-life-bouy:before,

### ISSUE THREAD

**Issue by lukepolo** [FortAwesome/Font-Awesome#10541]
```
.fa-life-bouy:before,
```

**Comment by tagliala** [comment]
Hi, thanks for reporting this.

I know about this issue and there is also a deprecation note in icons.yml: https://github.com/FortAwesome/Font-Awesome/blob/master/src/icons.yml#L4434

Unfortunately we cannot remove the misspelled alias because it is a breaking change, we should wait for 6.0.0

Closing here
