### ISSUE TITLE
Icon Request: fa-calender-M / fa-calender-A / fa-calender-D / fa-calender-Q

### ISSUE THREAD

**Issue by SadeemHosain** [FortAwesome/Font-Awesome#10575]
Dear team,

can you please create a new icon where you use the same fa-calender-o icon and then inside it one of the letters A for annual , Q for Quarterly, M for Monthly , and D for Daily.

i need it for data publishing and updates.

Thank you :)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I should advise you to take a look at this blogpost: http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/

And there is also a request for weeks/months: #3609

I'm going to close this one because glyphs should not depend on language but "A", "Q", "M" and "D" will not work globally (e.g: "D" should be "G" in my language)
