### ISSUE TITLE
Icon Request: fa-shared-folder-closed

### ISSUE THREAD

**Issue by eashancode** [FortAwesome/Font-Awesome#10586]
![02](https://cloud.githubusercontent.com/assets/9126937/22420125/b7fd1564-e706-11e6-9df3-8511a0bb939d.png)

**Comment by CaldwellSmith** [comment]
Is there any progress on this icon?

Here were some ideas based on existing icons and ideas.

![V1](https://user-images.githubusercontent.com/13855937/62234469-985d9880-b37f-11e9-913a-c78a49b79d7c.png)
![V2](https://user-images.githubusercontent.com/13855937/62234470-98f62f00-b37f-11e9-8ce7-db8a867fae69.png)

**Comment by Rlcolli4** [comment]
I second the question about progress on this icon? I could really use this in an application

**Comment by tenderScript** [comment]
I third the question about progress on this icon? I could really use this in an application.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Comment by eashancode** [comment]
@sensibleworld, @tagliala Woah, hold on a sec, gotta dust off the floppy disk with my FontAwesome wish list!   Never mind that icon request from 2017, apparently carrier pigeons are faster for design requests these days. Thanks for getting back to me though!
