### ISSUE TITLE
Icon Request: fa-shared-folder-open

### ISSUE THREAD

**Issue by eashancode** [FortAwesome/Font-Awesome#10585]
![01](https://cloud.githubusercontent.com/assets/9126937/22420079/7d90db4a-e706-11e6-9fa9-bf392f117f48.png)

**Comment by jackniu81** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Comment by eashancode** [comment]
@sensibleworld @tagliala   Woah, hold on a sec, gotta dust off the floppy disk with my FontAwesome wish list! Never mind that icon request from 2017, apparently carrier pigeons are faster for design requests these days. Thanks for getting back to me though!

**Comment by sensibleworld** [comment]
Our icon requests have been a messy place for far too long! We're finally taking some action on them.

And I think the carrier pigeon got distracted as well 😂

**Comment by eashancode** [comment]
Sounds like those carrier pigeons need a performance review! 😂    
But seriously, this is fantastic news.  The icon request system is long overdue for an upgrade, and I'm excited to see what you have planned. (Thanks for taking charge, @sensibleworld !)
