### ISSUE TITLE
Icon Request: icon-push-button (Icon Request: icon-actions)

### ISSUE THREAD

**Issue by publicocean0** [FortAwesome/Font-Awesome#10584]
in the header of a table where we place actions .... we could place a icon "actions"

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide an example and set a proper title?

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by publicocean0** [comment]
this is a very common use case. 
You have a table with a list. In a column (usually last) you have different button for actions related to specific row in table (for example delete , view ,...) In the header ot this list instead to write "actions" i m putting a icon giving a general idea about "action on ".

**Comment by tagliala** [comment]
If you are request a hand / finger pushing a button, please rename this request as `Icon Request: icon-push-button`

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
