### ISSUE TITLE
 icon request: dog bite

### ISSUE THREAD

**Issue by labrsq** [FortAwesome/Font-Awesome#10597]
![image](https://cloud.githubusercontent.com/assets/25471296/22493315/4fe4f1b6-e7e4-11e6-902d-20d4299e7581.png)
or
![image](https://cloud.githubusercontent.com/assets/25471296/22493333/74bf0fa8-e7e4-11e6-97f7-599446ebd227.png)

**Comment by tagliala** [comment]
This icon will barely fit 16px icon size

**Comment by WayneRE** [comment]
A bit too detailed to be seen very small. Maybe just the dogs head and the bite section of the leg

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
