### ISSUE TITLE
Icon request: icon for flat size of Apartmen

### ISSUE THREAD

**Issue by kubis** [FortAwesome/Font-Awesome#10668]
On real estate web pages there is very important info - size of an apartment or house or ...

my suggestion is 

![size](https://cloud.githubusercontent.com/assets/765648/22979849/1548af9c-f398-11e6-9d66-6ce5321800e4.jpg)

it could be done from square-o with addition of two arrows.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.]()

**Comment by tagliala** [comment]
@sensibleworld did you want to link to https://fontawesome.com/icons/up-right-and-down-left-from-center?f=classic&s=solid ?
