### ISSUE TITLE
Icon Request: fa-saml

### ISSUE THREAD

**Issue by rpmansion** [FortAwesome/Font-Awesome#10672]
Please also include SAML icon for single sign on button icon.

![image](https://cloud.githubusercontent.com/assets/18090549/23014105/8e87a72a-f468-11e6-8aaa-cbca610978fb.png)

**Comment by tagliala** [comment]
Could you please provide more detail about this icon?

**Comment by robertpmansion** [comment]
We have an application that provides single sign-on using different authentication, one of them is SAML2. We provide the service provider for SAML and user add their Identity Provider in order to authenticate their account using SAML2 in our application.

I believe SAML commonly use in some university as their authentication. This is an open standard data format for exchanging authentication and authorization data between parties, in particular, between an identity provider and a service provider.

**Comment by tagliala** [comment]
Is there any official website? I'm not able to find that logo on google

**Comment by robertpmansion** [comment]
It seems it doesn't have.

**Comment by tagliala** [comment]
So this is not an official logo? Is it widely accepted in the community? (eg: javascript's unofficial logo)

**Comment by robertpmansion** [comment]
Probably, but that is the logo being used here: https://auth0.com/docs/protocols/saml/saml-idp-generic.

**Comment by tagliala** [comment]
Hi!

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
