### ISSUE TITLE
Icon request: music artist

### ISSUE THREAD

**Issue by meredithcollinz** [FortAwesome/Font-Awesome#10696]
Suggesting/requesting a music artist/ performer icon. I have a collaborative songwriting platform that it would be awesome for, but would be great for any music platform or app that offers services/resources/info for/on
<img width="146" alt="screen shot 2017-02-22 at 7 17 34 pm" src="https://cloud.githubusercontent.com/assets/8887145/23239352/ae74a986-f934-11e6-9194-7e531bebc9a0.png">
<img width="311" alt="screen shot 2017-02-22 at 7 17 19 pm" src="https://cloud.githubusercontent.com/assets/8887145/23239356/b2b9249a-f934-11e6-83b1-a19d0682c885.png">

 musicians.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
