### ISSUE TITLE
Icon Request: fa-industry-plus

### ISSUE THREAD

**Issue by luli-isa** [FortAwesome/Font-Awesome#10712]
Hi,
I would like to request an icon representing the action for add a new factory, like user-plus http://fontawesome.io/icon/user-plus/ 
but with industry logo http://fontawesome.io/icon/industry/

Thanks very much.

**Comment by tagliala** [comment]
Ref: #1181, you will find a solution there

**Comment by luli-isa** [comment]
Thanks, but if I must insert my icon on Vis.js library? How can I insert it? The library wants insert **unicode** for node with icon shape. 
http://visjs.org/docs/network/nodes.html

I can't use icon stacked http://fontawesome.io/3.2.1/examples/#stacked

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
