### ISSUE TITLE
How can I use FontAwesome font is Desktop?

### ISSUE THREAD

**Issue by cssExpert** [FortAwesome/Font-Awesome#1071]
When I'm trying t create an Icon in Photoshop using FontAwesome, its making the Alphabet or Character as a Border Block. Can't found this FontAwesome working for Desktop.

![icon](https://f.cloud.github.com/assets/2076513/501407/b7f614aa-bc97-11e2-95ee-f26a8243c83f.png)

**Comment by eladkarako** [comment]
check out http://umoji.eladkarako.com/ I've gathered only ones that does not look like squeres, (it is even say so in the description), it is not just on your pc, it is not 100% since you can use 'Ariel Unicode MS' which is 20+mb of unicode goodness filled with most complete glyph-table, and still see squares there...

**Comment by Subfire** [comment]
i downloaded the latest font(https://github.com/FortAwesome/Font-Awesome/tree/master/fonts), why it cant' be install in Windows?

**Comment by Subfire** [comment]
@davegandy
