### ISSUE TITLE
Icons request: icon-dollar-redo (dollar refund)

### ISSUE THREAD

**Issue by lgants** [FortAwesome/Font-Awesome#10786]
How about a refund icon? There are several monetary icons, but I couldn't find one that would connote a refund. Maybe something similar to the one below? 

![658720-200](https://cloud.githubusercontent.com/assets/18373573/23869036/a5b6acb2-07ef-11e7-8c6f-817b9e21e4c3.png)

**Comment by rosnaib11** [comment]
+1

**Comment by tommotaylor** [comment]
+ 1

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please note that this icon depend on currency and it is not an international representation of a refund.

I've changed the title but I would like to see another example of "refund"

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
