### ISSUE TITLE
 Icon request: fa-payg

### ISSUE THREAD

**Issue by mohanprajapati** [FortAwesome/Font-Awesome#10798]
Request you to build some icon on tax( related to sale tax, income tax, payg).

It is very useful when you make some kind of business website with tax information.
Here is link of one icon related to payg.
https://discoverinjune.com.au/wp-content/uploads/2016/04/xc-359x280.png 

Help will be really appreciated.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
