### ISSUE TITLE
Icon Request: fa-video-marker

### ISSUE THREAD

**Issue by collettezq7** [FortAwesome/Font-Awesome#10801]
A marker icon or icon for the top of a playhead would be awesome; especially with the fill and outline options.

Looks like upside down house. Final Cut, Premiere and Prelude examples below.
![screen shot 2017-03-17 at 10 39 05 am](https://cloud.githubusercontent.com/assets/10457606/24053267/1f6f7e10-0afe-11e7-95c5-1262f3528a89.png)
![screen shot 2017-03-17 at 10 38 37 am](https://cloud.githubusercontent.com/assets/10457606/24053268/1f715370-0afe-11e7-8fd2-1c7e1756cca0.png)
![imgres](https://cloud.githubusercontent.com/assets/10457606/24053307/3ea5e8a0-0afe-11e7-8814-7fc78c04c604.jpg)

**Comment by Lolincolc** [comment]
Hey !
There are multiple way to get something that looks like a video marker : 
> fa fa-shield
> fa fa-envelope-open fa-rotate-180
> fa fa-play fa-rotate-90
This is not perfect but it is a solution.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
