### ISSUE TITLE
Icon Request: fa-request / fa-response

### ISSUE THREAD

**Issue by truhlikfredy** [FortAwesome/Font-Awesome#10837]
I intend it to describe HTTP services, I have document with a table of requests and typical responses, having icons next to them would help visually make that difference.

Sorry I know this is the problem of happiness vs smiley face. I know it's bit abstract because request could be anything and requests might be used outside networking context. Could it be some icon of a server?

For example fa-server and have arrows going into it and out from it.

Alternative would be make abstract fa-input / fa-output icons which could based on fa-download and fa-upload.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
