### ISSUE TITLE
Icon Request: icon-Document-link

### ISSUE THREAD

**Issue by baumgardc** [FortAwesome/Font-Awesome#10849]
I am looking for an icon to represent a link to a document. 
Examples 
![image](https://cloud.githubusercontent.com/assets/18519228/24366948/711dcab6-12e0-11e7-80a5-1ac9df94be21.png)

![image](https://cloud.githubusercontent.com/assets/18519228/24366933/66226748-12e0-11e7-9ebe-7bdcc44da7f3.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
