### ISSUE TITLE
Icon Request: icon-autoplay

### ISSUE THREAD

**Issue by GNSubrahmanyam** [FortAwesome/Font-Awesome#10847]

**Comment by tagliala** [comment]
Could you please provide an example?

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by GNSubrahmanyam** [comment]
@tagliala Actually, I am making custom audio /  video player using HTML5 Audio/Video API. I want to replace autoplay text => icon.

**Comment by GNSubrahmanyam** [comment]
## Autoplay Icon Sample from [iconfinder](https://www.iconfinder.com/icons/99176/autoplay_icon)
![image](https://cloud.githubusercontent.com/assets/18217008/24340942/a4c3c0e4-12d3-11e7-96ab-cb5fc5f42d5f.png)
![image](https://cloud.githubusercontent.com/assets/18217008/24341036/75d63266-12d4-11e7-903d-66ecb4fe8acc.png)


## Autoplay Icon Sample from Windows Control Panel. 
![image](https://cloud.githubusercontent.com/assets/18217008/24340987/2a1ef13c-12d4-11e7-8464-ed2409b88b74.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
