### ISSUE TITLE
Icon Request: fa-chf

### ISSUE THREAD

**Issue by captain-theo** [FortAwesome/Font-Awesome#10896]
I think it would be useful to include Swiss franc in currency icons

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Quoting from: https://github.com/FortAwesome/Font-Awesome/issues/4986#issuecomment-66041192

> > As a program I'd love to see just text currency symbols in particular "US$" instead of just "$" or "CHF" for Switzerland or "HK$" for Hongkong dollar.
>
> "CHF" is not a currency symbol; "CHF" is a currency code in the [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) standard. The correct currency symbol for the Swiss franc is "Fr."

Could you please clarify your request?

**Comment by rjgotten** [comment]
One of my employer's customers actually is wrestling with the lack of a CHF icon as well.

"CHF" is de-facto used as a currency symbol by many Swiss companies and nowadays is much more recognized by the general public than the officially recognized "Fr." or "SFr." symbols.

**Comment by tagliala** [comment]
I understand, but since this is not a standard, it paves the way for USD, AUD, JPY, etc., I should suggest you to go for a [custom build of font awesome](https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome) or simply use [plain css](https://jsfiddle.net/tagliala/hu6qksdb/4/)

I will leave this open, because #2320 is

**Comment by stoem** [comment]
I was going to request this as well and I would argue it is more f a special case than USD or JPY because Swiss Francs doesn't have a 'real' symbol and as the OP stated CHF is the de factor standard. 
I like the pure CSS approach so that should work. 
Any chance you could show us what the CSS syntax would look like to overlay the CHF letters onto  fas fa-square ? I'm struggling with the CSS for that.

**Comment by tagliala** [comment]
Just an example: https://jsfiddle.net/tagliala/tgzouajm/10/

IIRC, there are issues with old browsers when using string in `content`

**Comment by stoem** [comment]
Much appreciated!

**Comment by hpvd** [comment]
+1

**Comment by tagliala** [comment]
Available in FA 6.4.0 Pro

https://fontawesome.com/icons/chf-sign?f=classic&s=solid
