### ISSUE TITLE
fa-recycle alignment and size problem

### ISSUE THREAD

**Issue by thiotes** [FortAwesome/Font-Awesome#10898]
![snippet](https://cloud.githubusercontent.com/assets/26767954/24712010/f471a2c8-1a21-11e7-8fcf-4d0a841ed759.png)

I have tried using fa-recycle, but soon found that it sticks out from other icons by being somewhat misaligned and/or too short. Technically its lowest point does align with other icons, but it does not "feel" correctly aligned since the eye aligns rather with the lefternmost arrow bottom than the tip of the right arrow.

**Comment by tagliala** [comment]
This should be solved in 5.0.0 since all icons were redesigned  from scratch

**Comment by gbjbaanb** [comment]
Results from FA 5.08:

![image](https://user-images.githubusercontent.com/6808175/38779380-6b1a905a-40bf-11e8-886d-3eac33d76bc8.png)

Maybe... the recycle icon is bigger all round than the home icon. and although its tweaked so half the bottom arrow is below the baseline, I'm not sure it looks perfectly "right".  I'd agree with the OP, that the bottom part of the arrow should be considered to be a tail and the arrow stalks should be aligned on the baseline.

**Comment by tagliala** [comment]
I think that they are fine because recycle is narrower than home and they should respect the grid

![image](https://user-images.githubusercontent.com/556268/38781504-b5f0d1b2-40e6-11e8-857f-ff2b4f622894.png)

I'm going to close here

**Comment by gbjbaanb** [comment]
Don't be so literal, I just used Home because some other fiddle had it in place already.

![image](https://user-images.githubusercontent.com/6808175/38782654-c107ab40-40ee-11e8-9f4f-26392a6d14d6.png)

Trash and Recycle - similar problem, no width excuses this time! :-) I do think its correct, but it doesn't look so.

**Comment by tagliala** [comment]
@gbjbaanb sorry, you are right

Anyway, recycle already uses all the vertical available space, so it should be a little bit shorter

Reopening here, but please use custom css at the moment to deal with this

**Comment by gbjbaanb** [comment]
No worries, but surely it should be able to go below the baseline - thinking of fonts, the letter y would look rubbish if it had to sit above the baseline,. I think the recycle arrow should be considered similarly.

**Comment by tagliala** [comment]
This is still an issue with FA 6.1.1: http://jsfiddle.net/tagliala/wr154e6x/8/

I think that @sensibleworld can help here

It happens because the arrowhead is considered part of the icon and have impact on the baseline, but the baseline should probably be the arrow itself.

I don't know if there is enough margin to move down the recycle icon by 1 grid unit

https://github.com/FortAwesome/Font-Awesome/blob/6.x/svgs/solid/recycle.svg

![image](https://user-images.githubusercontent.com/556268/163452608-9fa56d18-0b1c-4012-93b4-42e8b7e25abd.png)

**Comment by sensibleworld** [comment]
Unfortunately, this isn't a change that we can make to the source SVG. There are only so many pixels we can use, and we're using them all! The only way to get this icon to align how you'd like is to manually adjust it in CSS.
