### ISSUE TITLE
Icon request: icon-sc-overview

### ISSUE THREAD

**Issue by SC-Robert** [FortAwesome/Font-Awesome#10901]
Hello team Awesomeness

The company that I work for, Scientrix, requires some font-icons for the development of their program platform. It has been running for over ten years with the development team in Argentina. The team has requested that any icons that we use in the program (it is a web-based program) be a font for re-scaling similar to which you supply.

Could you please assist us in creating two icons (a separate issue will be made for the other icon) to be used in the platform as per the development teams request. These icons will also be used in a section of our website.

![sc-overview](https://cloud.githubusercontent.com/assets/26964697/24753412/4afe578e-1ad2-11e7-931e-0c06d002e39f.jpg)

If you want we have designed these in a vector format, you can e-mail me for the files, I will just need to know what format you would like them in.

Thanks for all your help Awesomeness!

**Comment by Bertuzb** [comment]
convert them to a font using something like https://icomoon.io/ . If you have the vector available there is a good chance you can just convert it and map it to a certain character in your font

**Comment by SC-Robert** [comment]
Thank you, I have tried your suggestion, but if the programmers have a problem then they can come ask you directly. This is a bit out of my field of expertise.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
