### ISSUE TITLE
Icon Request fa-membership

### ISSUE THREAD

**Issue by Henry1502inc** [FortAwesome/Font-Awesome#10950]
The community would greatly welcome a membership/membership plan icon.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Any single color, 16px icon size example?

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by ryankane** [comment]
Maybe instead of person on the ID card, maybe a star?

![card](https://cloud.githubusercontent.com/assets/1094151/25148220/2088873e-2448-11e7-91c2-d5510168ad36.png)

[Demo](https://jsfiddle.net/MrPolywhirl/ojnhafoc/)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
