### ISSUE TITLE
Icon Request: fa-strobe

### ISSUE THREAD

**Issue by ogawamasato** [FortAwesome/Font-Awesome#10996]
common in camera button. Electronic flash icon on the camera button.

CIPA DCG-003

a little bit different from fa-bolt.

(not as same as IEC 6047-5036: Dangerous Voltage)

![flash](https://cloud.githubusercontent.com/assets/17801068/25404100/923075a8-2a39-11e7-8397-1335792d5d1c.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Why it is important to use that very exact icon? Apple and android (google camera) use a standard bolt for their flash feature

**Comment by ogawamasato** [comment]
this is the standard. as I referred to. To writing about the digital camera issue (canon nikon, olympus , sony....), this icon exactly means that meaning.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
