### ISSUE TITLE
Icon request: Planets(Jupiter, Saturn)

### ISSUE THREAD

**Issue by psybersec** [FortAwesome/Font-Awesome#11029]
**I need font awesome icons for Saturn and Jupiter planets.** 

> web application

**Comment by aethior** [comment]
Currently there are:
- https://fontawesome.com/icons/solar-system
- https://fontawesome.com/icons/planet-moon
- https://fontawesome.com/icons/planet-ringed

Related (not duplicate)
- https://github.com/FortAwesome/Font-Awesome/issues/10200

@tagliala `astronomy (category)` label for this request?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
