### ISSUE TITLE
Icon Request: fa-door management alarm

### ISSUE THREAD

**Issue by dtchntxs** [FortAwesome/Font-Awesome#11093]
I'm looking for an icon representing a door management alarm.  Just a sqare with a circle in it, like this: 
![image](https://cloud.githubusercontent.com/assets/28810637/26255564/9c47711a-3c7f-11e7-84d4-7ff8c2992e47.png)

Thanks  :)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a single color, suitable for 16px icon size example?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
