### ISSUE TITLE
Icon request: fa-phone24

### ISSUE THREAD

**Issue by leightonb** [FortAwesome/Font-Awesome#11120]
I would like an icon that indicates a 24-hour phone service, like the attached image.
We use the current fa-phone icon for business-hours but have nothing for the after-hours or 24-hour services.

![24-hours-phone-service_318-61519](https://cloud.githubusercontent.com/assets/29031259/26535982/d9ef6826-4475-11e7-9b17-932f164325c7.jpg)

Image from: http://www.freepik.com/free-icon/24-hours-phone-service_720118.htm

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
