### ISSUE TITLE
HTTPS Website

### ISSUE THREAD

**Issue by NicoHood** [FortAwesome/Font-Awesome#11136]
Please use https for your website in order to provide better security for everyone. Also see:
https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think this is not done because documentation is hosted on GitHub with a custom domain. Ref: isaacs/github#156

I think this needs cloudflare in front of the github docs.

I cannot manage this directly and I don't know if it could be a priority but I'm definitely leaving this open and I would like to see this feature implemented :)

**Comment by matt-halliday** [comment]
You can also look at Caddy as an option. It has a git plugin that can pull the repo for the pages and serve it over https. https://caddyserver.com/docs/http.git

Automatically clones your github repository to web server, served to clients with automatic HTTPS certificate. Neato

**Comment by Soaku** [comment]
https*

**Comment by edmorley** [comment]
This is now fixed (https://fontawesome.com/how-to-use etc) and can be closed.
