### ISSUE TITLE
Can anyone tell me how I can get a fa cleaning or broom icon? They don't have one on their webpage. Many thanks

### ISSUE THREAD

**Issue by glasby** [FortAwesome/Font-Awesome#11151]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please add a 👍  reaction to this request: #239 

In order to get a cleaning icon, the best you can do is to customize font awesome. Take a look at this wiki: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Hope it helps

Closing here
