### ISSUE TITLE
Icon Request: fa-refund

### ISSUE THREAD

**Issue by kylesimpson** [FortAwesome/Font-Awesome#11165]
Requesting an icon that depicts refunding cash to a customer. Perhaps a currency icon with an arrow underneath. 
![refund](https://user-images.githubusercontent.com/5483244/27055676-268d5e40-4f93-11e7-8676-b8cd26783b8f.png)

**Comment by aethior** [comment]
Why not a [custom icon with stacked icons](http://blog.fontawesome.io/2014/09/25/custom-file-types-with-stacked-icons/) using `fa-refresh` and `fa-dollar` icons? (also available with other currency icons). Example: https://codepen.io/anon/pen/xrOrjQ (it's a draft, is possible to do it better)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I would go for the solution suggested by @aethior, hoping that FA 5.0 will provide better dollar and refresh icons (actually, refresh is too tick for a good looking stack).

The icon in the example has the problem that is not international because it depend on currency. We are trying our best to keep icons international

I'm closing here for the moment
