### ISSUE TITLE
Icon Request: fa-pencil-eye

### ISSUE THREAD

**Issue by zubinkadva** [FortAwesome/Font-Awesome#11177]
This is a combination of fa-eye and fa-edit. Below is an example of what it should look like:
https://goo.gl/images/PIDYiR

Thanks.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify the use case of this icon?

**Comment by zubinkadva** [comment]
Hi. Is this icon request approved?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
