### ISSUE TITLE
Icon request: installment

### ISSUE THREAD

**Issue by podrivo** [FortAwesome/Font-Awesome#11174]
This is very common in Brazil. Kind of a cultural thing to split payments for several months.
It could be a calendar with a money sign. 

- `fa-installment` or `fa-calendar-installment`

Some ideas: https://thenounproject.com/search/?q=installment

![screen shot 2017-06-14 at 11 57 10 am](https://user-images.githubusercontent.com/546221/27139237-d4c1b0ae-50f8-11e7-9419-9b29a940ea22.png)![screen shot 2017-06-14 at 12 03 13 pm](https://user-images.githubusercontent.com/546221/27139470-7bc2c91a-50f9-11e7-8fdf-28352c63e788.png)![screen shot 2017-06-14 at 12 03 17 pm](https://user-images.githubusercontent.com/546221/27139473-7dac40c6-50f9-11e7-8b06-93355d87e9af.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Since this icon is not international and it depends on currency, please consider the [icon stack feature](http://fontawesome.io/examples/#stacked) or read this blog post: http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by podrivo** [comment]
Wasn't aware of stacking icons. Thanks for sharing! (:
