### ISSUE TITLE
Icon request: fa-fit

### ISSUE THREAD

**Issue by cyrilchapon** [FortAwesome/Font-Awesome#11180]
Hey.

Something like this :

https://maxcdn.icons8.com/Share/icon/Printing//fit_to_width1600.png

Would be great. My personal use case is a use on leaflet, something like a "fit to screen" stuff

**Comment by cyrilchapon** [comment]
Basically same as [fa-arrows-alt](http://fontawesome.io/icon/arrows-alt/) but with the center cut

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
