### ISSUE TITLE
Icon Request: fa-zero-percent or fa-nocharge

### ISSUE THREAD

**Issue by aquariens** [FortAwesome/Font-Awesome#11197]
when it comes to 0% markup or 0% down payment on any deal it is quite sometime I look for an appropriate FA Icon but didn't seems to find one good so hereby want to request it.
![untitled-1](https://user-images.githubusercontent.com/17455752/27300331-cf5b58d2-5548-11e7-9655-7d4589518242.png)

Thanks...!

**Comment by aquariens** [comment]
Phi also may be the option for the same any way?

![image](https://user-images.githubusercontent.com/17455752/27300568-8d2bbc76-5549-11e7-8247-ee33b5a825a7.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
