### ISSUE TITLE
Icon request: icon-pencil-square-multi

### ISSUE THREAD

**Issue by jasongardnerlv** [FortAwesome/Font-Awesome#11239]
Basically looking for a combination of _pencil-square-o_ and _clone_. Two offset squares with a pencil to indicate editing multiple things.  I'm getting by for now with fa-stack

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
