### ISSUE TITLE
SIL Open Font License and GPL

### ISSUE THREAD

**Issue by tardyp** [FortAwesome/Font-Awesome#1124]
http://en.wikipedia.org/wiki/SIL_Open_Font_License

wikipedia clearly states that SIL OFL is not GPL compatible, despite what is written in font-awesome's license page. Can you clarify?

**Comment by koleary** [comment]
From Drupal.org:

> FontAwesome - SIL OFL is not strictly GPL compatible. It is now labelled as GPL friendly and can not be whitelisted until the revisions to the Drupal.org git and licensing policies the LWG proposed are approved. As soon as that happens, FontAwesome will be whitelisted. If you absolutely need FontAwesome to be included on install, take a look at https://www.drupal.org/node/2427075. A number of other distributions are using FontAwesome via a CDN while we've been waiting for the changes to Drupal.org.

I posted a request for an update on when the Licensing working Group will resolve this.

**Comment by koleary** [comment]
See: 
https://www.drupal.org/node/2139273#comment-10871158

**Comment by jeremykohn** [comment]
The SIL Open Font License isn't considered a [GPL-compatible free software license](https://www.gnu.org/licenses/license-list.html.en#GPLCompatibleLicenses) because it isn't a software license at all. However, it allows bundling the fonts with software, and in fact requires doing so if the fonts are sold. [Here's the FSF's take on it:](https://www.gnu.org/licenses/license-list.html.en#SILOFL)

> The Open Font License (including its original release, version 1.0) is a free copyleft license for fonts. Its only unusual requirement is that when selling the font, you must redistribute it bundled with some software, rather than alone. Since a simple Hello World program will satisfy the requirement, it is harmless. Neither we nor SIL recommend the use of this license for anything other than fonts.








This is supported by [the text of the license itself](http://scripts.sil.org/OFL_web): 

> 1) Neither the Font Software nor any of its individual components,
in Original or Modified Versions, may be sold by itself.

> 2) Original or Modified Versions of the Font Software may be bundled,
redistributed and/or sold with any software, provided that each copy
contains the above copyright notice and this license. 

So there shouldn't be a problem using OFL-licensed fonts in software, including software that's GPL-licensed. But even then, the font itself does not become GPL-licensed:

> 5) The Font Software, modified or unmodified, in part or in whole,
*must be distributed entirely under this license, and must not be
distributed under any other license*. The requirement for fonts to
remain under this license does not apply to any document created
using the Font Software.

(Emphasis added.)

So, the OFL still applies to the font itself. The GPL does not.

Sources: 

[GPL-compatible free software license](https://www.gnu.org/licenses/license-list.html.en#GPLCompatibleLicenses)

[SIL Open Font License version 1.1](http://scripts.sil.org/OFL_web)

**Comment by davelab6** [comment]
This is true as long as the GPL software can use any font, and is just
configured to use a particular (OFL) font. If there was some tight
integration between the program and the font, it might switch from
'aggregate distribution' of 2 separate works, the program and the font,
into a 'derivative (combined) work'

**Comment by jeremykohn** [comment]
I think all you'd have to do is specify, in the licensing/copyright/notice, that the software is GPL-licensed but a separate license applies to the OFL-licensed fonts.
