### ISSUE TITLE
The font-awesome CDN link is not working

### ISSUE THREAD

**Issue by navneetkarnam** [FortAwesome/Font-Awesome#11256]
I tried using the CDN from the get started link and it seems to not work for me. I replaced it with the following in the href part of the CDN and it worked for me: 
 "https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"

<img width="1226" alt="screen shot 2560-07-05 at 6 50 13 pm" src="https://user-images.githubusercontent.com/16421653/27888285-3e9945ee-61b3-11e7-9d80-9dab6ec52358.png">

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The above documenation is correct, if you include Font Awesome in your project (as per Step 1), you should add the path to the font awesome's stylesheet in that way. Since we don't know the exact path on your server, we have to use a placeholder like `path/to/font-awesome/css`.

If you are using maxcdn, that part of the documentation is not for you.

Also, the page is voluntarily skipping instructions for maxcdn in favor of Font Awesome CDN. For what is worth, I do not agree to skip instructions for maxcdn, but that is a choice from the Font Awesome development team and I respect that.

Closing here, hope it helps

**Comment by navneetkarnam** [comment]
Thank you and I would love to contribute to this community. Ohh, I understand. Thank you.
