### ISSUE TITLE
Icon Request: fa-merge-left

### ISSUE THREAD

**Issue by ajbeaven** [FortAwesome/Font-Awesome#11265]
Use case: a sequence of widgets can be joined or merged into the widgets to the left or right. Could also be used for a 'join' icon.

Maybe something like this:
![image](https://user-images.githubusercontent.com/657201/27938756-3417764c-6314-11e7-97a5-22cbc27fcc3a.png)

**Comment by aethior** [comment]
Related #14500.

✔️ `merge-right` (https://fontawesome.com/icons/merge) has been added in v6.1.0.
❌ `merge-left` does not exist yet.

cc/ @tagliala

**Comment by tagliala** [comment]
Renaming as `merge-left`, but `merge-left` can easily be achieved by horizontally flipping the icon

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/gallery-thumbnails?f=classic&s=solid)
