### ISSUE TITLE
searching for change won't find the exchange icon

### ISSUE THREAD

**Issue by huglester** [FortAwesome/Font-Awesome#11306]
Hello,

when you search here: http://fontawesome.io/icons/
for icon **change** you won't find the button **exchange**

Thanks

**Comment by jeremy-collins-optimity** [comment]
Also when you search for **arrow** you won't find **long-arrow-down** (although the oher three in that set of arrows is returned):

![image](https://user-images.githubusercontent.com/10139903/28671976-49f102ae-72d6-11e7-971e-bda65ee07931.png)

**Comment by tagliala** [comment]
@talbs is there anything we could fix with Algolia instead of adding filters?

**Comment by Jerskouille** [comment]
About `change`, this is expected because Algolia only considers search terms as prefixes. If that's something you really want to modify here, a synonym between `change` and `exchange` would do the job.

About the `long-arrow-down`, it's due to the page amount of results (using `hitsPerPage: 20`, which is the default value). This can be changed in the index settings or overridden at query time.

**Comment by Haroenv** [comment]
This has been fixed with the new version 👍
