### ISSUE TITLE
Icon Request: fa-envelope-resend

### ISSUE THREAD

**Issue by rzahang** [FortAwesome/Font-Awesome#11314]
fa-envelope is good for emails , perhaps it would be a good idea to add something like these 
![envelope_message_mail_repeat_resend-256](https://user-images.githubusercontent.com/17567169/28445278-c66caf24-6e06-11e7-9b74-471e170b8c59.png)
![509072-200](https://user-images.githubusercontent.com/17567169/28445287-d1278b14-6e06-11e7-95cd-5b2d41829325.png)

Best,
Reza

**Comment by tagliala** [comment]
Refers to #1181

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
