### ISSUE TITLE
Font Awesome Icon not working for particular user

### ISSUE THREAD

**Issue by Lambo123** [FortAwesome/Font-Awesome#11316]
Hi
We have font awesome icons displayed in our application. I am facing issue that icons are not displayed.

And this problem with only one user on particular server. For other windows users, icons are coming up correctly. 

And the user for whom icons are not getting displayed on one server, works fine on another server. Enabled font download in IE11, but dint work.

Any solution please!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The best you can do is checking our [Troubleshooting Guide](https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting) or existing issues about [IE11](https://github.com/FortAwesome/Font-Awesome/search?q=ie11&type=Issues&utf8=%E2%9C%93)

Since it looks like it doesn't work for a specific machine, it's hard to tell if the issue comes from font awesome.

Also, you should check if other webfonts in the page works

If this don't help please provide **all** details about how icons are loaded (self hosted? cdn?), server configuration (if icons are self hosted), browser settings, browser console output...

Hope it helps, closing here
