### ISSUE TITLE
Icon request: Wishlist

### ISSUE THREAD

**Issue by gabihaley** [FortAwesome/Font-Awesome#11333]
Hello,

I'd like to formally request a Wishlist icon. I know that a lot of shopping websites use a Heart to favorite an item. Our website would like to have a wishlist, something similar to [this](https://thenounproject.com/term/wishlist/1073602/).

We're allowing users to make a wishlist similar to Amazon's wishlists and we feel that an icon similar to the one above works better for our use case than a heart. 

Thank you,
Gabi Gordon

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
