### ISSUE TITLE
Icon request: icon-area

### ISSUE THREAD

**Issue by kenjeegrondin** [FortAwesome/Font-Awesome#11335]
Hi! I'm working in architec marketing and i will be greatful if i had some icons to display data. 

I purpose Area size icon (normal, that it use to total area, but one to balcony area too ; and who know, maybe some other variants!).

Thanks for reading me.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a single color, 16px icon size suitable example?

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by kenjeegrondin** [comment]
Sorry for the delay.

The only example that i found and use for this is : http://collectionequinoxe.com/wp-content/uploads/2017/05/plan.png

This is use for area of unit, appartment, but not relevant if we want to use for balcony area ; but it's a good start!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
