### ISSUE TITLE
when update version , the style: content: '....'  will change or not 

### ISSUE THREAD

**Issue by hpyou** [FortAwesome/Font-Awesome#11368]
in my project, i want to use
```
.my-font{font: normal normal normal 14px/1 FontAwesome;}
.my-font:before{
    content: "\f07c";
}
```
not just font-awesome gived class name.
now i warry about when the version update, `content` will be changed

**Comment by tagliala** [comment]
Hi,

> now i warry about when the version update, content will be changed

They should not change.

Anyway, you should consider using Sass or LESS version and take advantage of variables.

e.g.:

```scss
$fa-css-prefix:       my-font;
```

Will change `.fa` to `.my-font`

Also, you have [variable names](https://github.com/FortAwesome/Font-Awesome/blob/master/scss/_variables.scss) for icons, that should be safer unicode points, but in 5.0 will change how you have to use those variables because of escaping issues #6552

Hope it helps, closing here

**Comment by hpyou** [comment]
@tagliala  ok，thinks
