### ISSUE TITLE
Icon request: icon-file-shopping-cart

### ISSUE THREAD

**Issue by kciola** [FortAwesome/Font-Awesome#11439]
Hello Font-Awesome Team,  
I'd like to request an icon for Purchase Orders.  I need to create purchase order functionality and would like an icon somewhat like the shopping cart but with some type of file next to it.  I plan on using this in a fulfillment service and the icon will be used in navigation as well as on any purchase order screen.
<img width="238" alt="screen shot 2017-08-24 at 11 43 32 am" src="https://user-images.githubusercontent.com/31317558/29674936-a24838c2-88c1-11e7-8e37-7a78fdd8c706.png">

Thank you!!!
Kelli

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
