### ISSUE TITLE
Icon Request: icon-blockchain

### ISSUE THREAD

**Issue by joeldebruijn** [FortAwesome/Font-Awesome#11479]
I did see some requests for Eth or [Ethereum](https://github.com/FortAwesome/Font-Awesome/issues/8754) and there's already a Bitcoin icon.
Maybe following the hype, but would the fundamantal technology faclitating these also deserve an icon?

Maybe too obvious, but something like this one: 
![blockchain](https://user-images.githubusercontent.com/3906940/29960629-bd0ac1e8-8efc-11e7-871e-cf9965aba380.jpg)

**Comment by lucasgonze** [comment]
+1 I landed here searching for a blockchain icon compatible with font-awesome

**Comment by lyricalpolymath** [comment]
My proposal for the [Web3 Design Principles](http://bit.ly/web3DesignPrinciples)

It would need to be a bit reworked for the small sizes but I think it's a starting point
(it's released under [CC BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/4.0/) = must be included in the free pack )

![web3designprinciples_cover_06_chosen](https://user-images.githubusercontent.com/516744/38170833-8b03d822-358e-11e8-8537-f09ca78c1efe.png)

**Comment by joeldebruijn** [comment]
I like this one a lot, blocks/arrows/chain etc.

**Comment by tapastwain** [comment]
+1

**Comment by JoeyKhd** [comment]
+1

**Comment by aweijnitz** [comment]
+1 Would be nice with a generic blockchain icon, independent of a specific technology.

**Comment by WillianGruber** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
