### ISSUE TITLE
Icon request: icon-leather symbol

### ISSUE THREAD

**Issue by longo12** [FortAwesome/Font-Awesome#11478]
Would like a leather symbol icon to place inside my logo on my website, thanks.

![20160330-imga](https://user-images.githubusercontent.com/31487041/29959916-732e28e0-8ef1-11e7-9397-9c67d67ac1ef.jpg)

**Comment by MarcusCalidus** [comment]
This is an internationally officially accepted symbol for genuine leather and should be included
https://www.leather-dictionary.com/index.php/Genuine_leather

**Comment by askurashev** [comment]
+1

**Comment by knitzie2** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
