### ISSUE TITLE
compatible with adobe flash builder 4.6 / flex?

### ISSUE THREAD

**Issue by emage** [FortAwesome/Font-Awesome#1154]
Tried using it on flex and it just shows a lot of errors.  So just wanted to know if its compatible.

**Comment by drmaposa** [comment]
Hi, i discovered that it works on the default Flash Builder Flex SDK (4.6.0) with AIR version 3.1
Im using Apache Flex 4.13.0 and AIR 16. So it tried it and was showing boxes. I then overlayed Adobe Flex SDK 4.6.0 with a new AIR version AIR 16 and it didnt work as well.

So I thing The issue is with AIR 16, unless we are missing something.
