### ISSUE TITLE
Icon request: icon-envelope-alt

### ISSUE THREAD

**Issue by lologic** [FortAwesome/Font-Awesome#11551]
This icon would be helpful for message boxes in a form. There is already a similar icon called "envelope-o" but this icon here has 2 additional lines what makes the icon look a bit better. Below is the icon I expect.

![letter](https://user-images.githubusercontent.com/26777182/30774269-3c20ba8e-a080-11e7-870c-798b4214194b.JPG)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
