### ISSUE TITLE
Icon Request: fa-plus-multi

### ISSUE THREAD

**Issue by Rezystor** [FortAwesome/Font-Awesome#11611]
Hi,

Meaybe can some one create icon for multi create ?
like fa-plus(square, circle , simple)  but multipled plus on icon

su

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request?

Please provide a single color example, suitable to 16px icon size

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by arximughal** [comment]
I guess he meant an icon for an option that would allow someone to create multiple entries. 
The nearest most icon would might look something like this:
https://visualpharm.com/assets/21/Multi%20Edit-595b40b65ba036ed117d300e.svg

But I can't think of any use case, this icon might be necessary for. 
fa-plus is enough.

**Comment by papppeter** [comment]
i think it would be greate if we have a batch create. the create creates multiple elements.

**Comment by tagliala** [comment]
@papppeter any single color example of the icon you have in mind?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
