### ISSUE TITLE
icon request: magnetic resonance machine

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#11627]
A magnetic resonance machine icon, alluding only to the machine, and another with a patient undergoing the examination.

**Comment by tagliala** [comment]
Any single-color, 16px icon size suitable example?

**Comment by pacho2** [comment]
Few are available at:
https://thenounproject.com/search/?q=magnetic%20resonance

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
