### ISSUE TITLE
Icon request: icon-mail-sent/icon-mail-received

### ISSUE THREAD

**Issue by malliwi88** [FortAwesome/Font-Awesome#11638]
Its will be usefull for minimal chats or inbox mails (eJ: email-manager minimal-space-GUI), without of use titles for access to sended or received mails.
![presentacion1](https://user-images.githubusercontent.com/5307894/31679119-cc245f10-b335-11e7-967a-6f56ad6f5112.png)

Thanks a lot

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/inbox-in?f=classic&s=solid)
