### ISSUE TITLE
Icon request: icon-grid

### ISSUE THREAD

**Issue by marcojacobsNL** [FortAwesome/Font-Awesome#11690]
Hereby I want to request a few icons which can be used in multiple projects.

For our own CMS we want to have icons for the different grid columns (for example large-1 or large-6).

We have made some simple icons ourself and we thought it could be useful in Font-awesome
![column1](https://user-images.githubusercontent.com/16101434/32174682-d2cb1b9a-bd82-11e7-9478-27ed13826197.png)
![column6](https://user-images.githubusercontent.com/16101434/32174683-d2e680c4-bd82-11e7-9c7e-a63636554595.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](Request isn't specific enough... also seems like we now have icons that would work for this.)

**Comment by tagliala** [comment]
There are several grids for Free and Pro: https://fontawesome.com/search?q=grid&o=r&s=solid
