### ISSUE TITLE
Icon Request: icon-dao

### ISSUE THREAD

**Issue by dkent600** [FortAwesome/Font-Awesome#11701]
Icon request: icon-dao

This would be used to generically represent any DAO on the Ethereum blockchain.

I supposed it could be grouped under "Brand Icons"

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
