### ISSUE TITLE
Icon Request: fa-blankForm && Icon Request: fa-existingForm 

### ISSUE THREAD

**Issue by mandanna** [FortAwesome/Font-Awesome#11715]
For the user to choose blank form or to choose from the form that is already existing. Blank from icon is already present..  but there is no existing form icon.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
