### ISSUE TITLE
Icon request:icon-jrtt

### ISSUE THREAD

**Issue by zzc0304** [FortAwesome/Font-Awesome#11743]
Hey,may be I need a new icon.
Official website:[今日头条(jrtt)](https://www.toutiao.com/).
Reference resources:[icon](https://s3a.pstatp.com/toutiao/resource/ntoutiao_web/static/image/favicon_8e9c9c7.ico)
Thank you very much.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide more information on this brand?

**Comment by zzc0304** [comment]
Thank you very much for replying to my request.
do you mean the icon of this brand?

**Comment by tagliala** [comment]
@zzc0304 

please provide more information on jrtt

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
