### ISSUE TITLE
Icon request: icon-townhouse (icon-town-house)

### ISSUE THREAD

**Issue by niki-waggle** [FortAwesome/Font-Awesome#11757]
Need more building types to represent home types on a web-app (tracking home types in a map). Would also like for classifying client homes. Already using "building" and "home" for apartments and single family homes.

![townhouse1](https://user-images.githubusercontent.com/32939084/32791477-27d98b50-c92f-11e7-9734-63d5a4a01858.png)
![townhouse2](https://user-images.githubusercontent.com/32939084/32791490-2ce88a60-c92f-11e7-954b-30670a1d7b07.jpg)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
