### ISSUE TITLE
Icon Request: fa-frozenyogurt

### ISSUE THREAD

**Issue by sdf1992** [FortAwesome/Font-Awesome#11779]
Hello i need a frozen yogurt icon for my website

**Comment by sdf1992** [comment]
i post you my handmade icone
![frozen](https://user-images.githubusercontent.com/33875709/33670344-2333ed34-daa5-11e7-8787-dbd58bd0e3af.jpg)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/soft-serve?f=classic&s=solid)
