### ISSUE TITLE
Icon Request: fa-user-circle-plus

### ISSUE THREAD

**Issue by jdeker** [FortAwesome/Font-Awesome#11778]
I need fa-user-circle icon with a plus. There are regular fa-user and fa-user-plus icons but there is no fa-user-circle icon with a plus. 
Thanks

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
