### ISSUE TITLE
Icon Request: fa-mobile-square

### ISSUE THREAD

**Issue by jrapp** [FortAwesome/Font-Awesome#11823]
Hello!

Could you make a fa-mobile-square icon? We have a fa-envelope-square and a fa-phone-square and I can't find a fa-mobile-square. Currently it just looks bad having the regular fa-mobile font next to the other square icons. 

Thanks for your help!

**Comment by marcoroth** [comment]
@jrapp in FA5 you could do something like this:
```
<span class="fa-layers">
   <i class="fas fa-square"></i>
   <i class="fas fa-mobile-alt fa-inverse" data-fa-transform="shrink-6"></i>
</span>```

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
