### ISSUE TITLE
Icon Request: Seasons

### ISSUE THREAD

**Issue by elgaard** [FortAwesome/Font-Awesome#11838]
summer, fall, winter, spring.

Or just summer and winter.

**Comment by tagliala** [comment]
I'm going to close this issue, because:

- it is hard to represent a season
- icons may be already here

Summer: https://fontawesome.com/icons/sun?s=solid
Winter: https://fontawesome.com/icons/snowflake?s=solid
Spring: https://fontawesome.com/search?q=flower&s=solid
Autumn?: https://fontawesome.com/icons/leaf-maple?s=solid

Feel free to comment or open a new request for, let's say `fallen leaf` 🍂
