### ISSUE TITLE
Icon request: fa-globe-arrow-up (publish)

### ISSUE THREAD

**Issue by scripting** [FortAwesome/Font-Awesome#11837]
Most of my software publishes stuff based on what the user is editing. 

So there's got to be an icon that means Publish What's Here Now. 

I've never found a suitable icon in Font-Awesome's collection, it's hard to imagine what it would be, but I wanted to put that out there. 

Apologies in advance if this has been requested previously.

**Comment by wolfy1339** [comment]
I believe that fa-cloud-upload should do the trick

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

if #5404 cointains a suitable example, please rename this to `Icon request: fa-globe-arrow-up (publish)`

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
