### ISSUE TITLE
Icon Request: fa-seo

### ISSUE THREAD

**Issue by fahim159** [FortAwesome/Font-Awesome#11847]
Hi Community,

This is to request to issue following icon for web applications
![fa-seo](https://user-images.githubusercontent.com/34315455/33678897-6b7707a6-dae7-11e7-832c-703f8eacc646.png)

**Comment by tagliala** [comment]
Does one of the following icon fit your use case?
* http://fontawesome.io/icon/line-chart/
* http://fontawesome.io/icon/search/
* http://fontawesome.io/icon/bar-chart/
* http://fontawesome.io/icon/area-chart/
?

**Comment by fahim159** [comment]
This icon representing search engine optimization (SEO). Such icon is commonly using in many websites. I can use http://fontawesome.io/icon/line-chart/ which may serve but the requested icon matches very well. SEO icon will be popular due to its demand.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
