### ISSUE TITLE
Icon Request: fa-accept-all-changes/fa-reject-all-changes/fa-accept-changes/fa-reject-changes

### ISSUE THREAD

**Issue by tesfaMistir** [FortAwesome/Font-Awesome#11859]
I plan to use these icons on text editors to accept changes made for multiple places or single place.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide examples? (single color, suitable for 16px icon size)

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by tesfaMistir** [comment]
Hello,

Thanks for getting back to me. I tried to upload sample icon but it was not
allowing me.
Please find attached.

Best Regards,
Mistire Tilahun
Phone:240-408-6870
Email: tesfayemissy@gmail.com <tesfayemissy@gmail.com>

**Comment by tagliala** [comment]
@tesfaMistir sorry, attachments don't work

Please upload files at https://github.com/FortAwesome/Font-Awesome/issues/11859

**Comment by tesfaMistir** [comment]
![accept-reject-icons](https://user-images.githubusercontent.com/34352085/33848595-3b3db330-de7c-11e7-9fe2-7aa766124742.JPG)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
