### ISSUE TITLE
ux issue on the new website: login icon

### ISSUE THREAD

**Issue by fmonts** [FortAwesome/Font-Awesome#11863]
It took me a lot of time to figure out that this is the login button:

![image](https://user-images.githubusercontent.com/8755314/33741338-8aa08b64-dbac-11e7-99c3-240459bca73d.png)

Am I the only one?

**Comment by viion** [comment]
I doubt you're the only one however I don't think it's much of an issue, that icon is quite standard, the alternative is a "User" icon. If you google "login icon" you get that style, many other "icon sites" will provide a very similar style in different variations.

There is also the arrow going "out" which is Sign out, so it can be easily identified as "in/out" (where as a user icon has no "out").

It might not be too much to ask for the word "Sign-in" next to it, to make it super obvious, however I think the icon is fine.

**Comment by My1** [comment]
why not just write Login or Sign in or whatever next to it, that makes the button bigger and more accessible, okay that might not be the best argument when the site is totally overflowing with AJAX and whatnot that you cant do a thing without Javascript and probably a top-notch browser, especially bad sighted people will be thankful for having a text.

I just see an aria hidden on that icon, but shouldnt aria hidden just be used on icons that are purely decorative? especially considering this is one of THE MOST IMPORTANT buttons on the whole website, I think this should be thought out a bit better.

also you know what I love of sites where any JS if any at all is purely decorative?
if JS doesnt work for some reason (Crazy data throttling on mobile internet cause the js to timeout, the js file itself has error, the server has problems, old or just small-featured browser, or just running noscript for safety reasons) The site still works.

If CSS crashes, the site will definitely look ugly and it may take a while to find stuff you look for, BUT THE SITE WORKS.

contrary to a site which is basically just a big blob of Javascript, if that thing fails for ANY reason, the whole site becomes USELESS.

so lets compare the old page, fontawesome.io (which by the way doesnt have a valid HTTPS cert) to the new one.

when I have JS blocked in chrome, the FA5 site, just has a breakdown to tell me that JS is needed to run the site.

now enter the FA4 site. The site works nicely. There are just 3 things I noticed that arent working. the Dropdowns in the header, which isnt a problem because they are just anchors, and the search, which also doesnt hurt because most if not all browsers already have one built in.

so far this looks PERFECT, but...

There is only ONE problem: The Download is on a modal. but well, there are workarounds as you can just grab the thing from github (which works fine without JS)
but scroll back a few years, to aboout 2015
https://web.archive.org/web/20150415062229/http://fontawesome.io:80/
before the Promotions of Fonticons, Fortawesome and FA5, the Download was a plain link.

also, there are probably more than enough ways to do modals without javascript, at least for the noscript tag, one of them here, found with a very short google search: https://codepen.io/peiche/pen/vhqym (I really need to bookmark this myself), so if you need to do promotions on the old site it would be nice to not block the DL for non-JS users.

I wont say that the new site has to work perfectly without JS but **at least important stuff like the list of icons, docs and license data should be accessible**. comfort features like the search are nice but I wouldnt need those when JS is doing junk, the browser search works also nice enough.

sorry for the wall of text though

**Comment by tagliala** [comment]
@My1 thanks for your feedback. I see your point and I mostly agree.

> why not just write Login or Sign in or whatever next to it

I think that "Login" is still the best way to represent a "login". Also, the screen reader tag is missing, so there could be an accessibility issue.

Personally, I think the Pro team's highest priority was to release FA5. I'm confident they will start addressing other issues soon

**Comment by My1** [comment]
yeah of course. sorry for repetition but especially the Javascript overdrive is kinda annoying, as said nothing agains JS in general (it CAN BE useful after all) but unless we are doing some super-extreme stuff that REALLY needs JS (like office online for example) it should at least work SOMEHOW without, the FA4 page shows nicely how this works.

**Comment by viion** [comment]
Your tone comes off very heavy, don't get too stressed out about this. Suggestions and advance will be definitely looked at and it's not as of big of an issue as expressed.

I do not agree on your JS argument and think it is weak at best. Most (i'd say 99% of people, just a guess...) have JS enabled, most sites require JS these days and data throttling is hardly an issue. Especially not something where turning of JS is going to save you money and prevent you from going over. You might as well ask to remove fonts, images, and reduce the HTML entirely if you're scraping for a few kb's of data (that gets cached). 

Also if you're using FA5 you're likely in a development environment, so you won't be on a mobile network, if you're on a train trying to load FA5 site then what can you honestly expect from the team in that case?

Aside from the login/sign-in troubles (which I think are very minor), the others could probably be put into their own issue as they're not part of the subject of this issue. I'm sure the community would be happy to discuss the weights of using Javascript.

**Comment by My1** [comment]
well from an accessibility standpoint forcing JS isnt a very good Idea.

also the sites I usually use dont die from not having JS (google works, gmail, amazon and facebook too, even twitter and Github), sure they are a lot less comfortable but at the very least they work, and the FA site isnt like a big social network and stuff, it's basically just a site documentation, listing of the icons and downloading FA5.

also as I said the FA4 site had no problems without javascript, and I see no reason why this should need to change.

I have had enough times where JS can get annoying and forcing client side stuff down the drain especially when it is heavily misused more and more these days isnt really awesome.

**Comment by robmadole** [comment]
Thanks @My1 for your feedback. It's always good stuff and I've learned to appreciate your delivery :)

We're gonna stick with JS because it's needed for the experience that we want. We'll be working hard on performance over the next few weeks and months (we know we have a lot of work to do here.) This is our initial release - the first time we've got the car out on the track. We need to take a few laps before it gets up to speed.

We'll look at the accessibility part of it. Great points. Thanks for that.

**Comment by My1** [comment]
but wouldnt it be awesome to have the best of both? meaning without js it works but you get an info that it works better with JS and when JS enabled you get the full experience.

also, why doesnt the external JS have SRI?

SRI solves the big problem that when a server of someone where you get a script from, changes it (for example by being hacked or whatever junk may happen), it will no longer load, preventing ugly stuff from happening.
https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

**Comment by robmadole** [comment]
@talbs assigning this to you so you can give it a thought.

**Comment by talbs** [comment]
Thanks, @robmadole.

**RE: Accessibility** - its on our UX list for the new site/docs to do a full a11y audit and make things as approachable to as many folks as possible. Expect that work to land soon. That will take into account best practices in general with markup and UX as well as how to make JS-powered interactions and content understandable as well (through ARIA).

**RE: Just the Icon for "Sign In"** - We tried to use a pretty universal icon to denote "Signing in" - along with the tooltip and the destination of the link being a dedicated Sign In view, we think this is enough for now. The main navigation of fontawesome.com is destined to changed and be made better overall as we go forward, so I'll keep this feedback around for when we address the nav on a larger level.

Thanks for the good thoughts and for caring so much, folks.

**Comment by My1** [comment]
well instead of tooltipping everything at least the most important links should be a little bit larger than about 1cm² to make it easier to notice. the icon is nice and stuff but apparently not everything notices it immediately (probably also since there usually is some kind of text next to any login button at most places in the web)

**Comment by talbs** [comment]
Thanks, @My1. Appreciate the feedback.

**Comment by talbs** [comment]
Hey, gang. Just wanted to follow-up here. We've made some changes to the site's main nav over the past few months. That sign in link should be a bit clearer since it now includes the label "Sign In" for desktop-level viewport sizes.

Thanks for bringing this to our attention. 😄
