### ISSUE TITLE
FA5: Solid 'filter' icon is too big

### ISSUE THREAD

**Issue by alecpl** [FortAwesome/Font-Awesome#11873]
E.g. if I put that icon a side of 'search' icon, the filter icon looks too big/fat.

**Comment by PeterShaggyNoble** [comment]
Have a look at the [layering section](https://fontawesome.com/how-to-use/svg-with-js#layering) of the docs.

I was able to get those 2 icons to work pretty well together: https://codepen.io/anon/pen/oorVdB

**Comment by alecpl** [comment]
Thanks, but I don't use the full FA stack. All I use is _variables.less and font-icon (.woff, etc.) files.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Icons should follow a grid, I will label this as an enhancement and assign to... (waiting for feedback)

https://fontawesome.com/icons/address-card?style=solid
https://fontawesome.com/icons/sliders-h?style=solid

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
