### ISSUE TITLE
Adobe XD integration

### ISSUE THREAD

**Issue by harunalikadic** [FortAwesome/Font-Awesome#11927]
How to make it work in Adobe XD (works in Illustrator)? FA4 works. FA5 shows just letters, doesn't switch to icon. Material Icons works, when I type "delete" it transforms into the relative icon.
I have just asked the same question also to their user community support. Will repost it here as soon as I receive it.

**Comment by navsterx** [comment]
I just install the fonts and then use the copy to clipboard feature in the gallery. Seems to work fine for me.

**Comment by davegandy** [comment]
We also put ligatures in for all icon names as well. Here's the guide for using on the desktop: https://fontawesome.com/how-to-use/use-on-desktop

**Comment by JwanKhalaf** [comment]
@davegandy this doesn't seem to work in Adobe XD? 
![image](https://user-images.githubusercontent.com/42877376/46791004-117bf880-cd38-11e8-96cb-fced35582436.png)

**Comment by tagliala** [comment]
@JwanKhalaf in order to use ligatures, please make sure:

- You have selected `Font Awesome 5 Free` as font (I can see `FontAwesome`: it's not the expected font name)
- You are using the .otf version of Font Awesome 5, available at https://github.com/FortAwesome/Font-Awesome/releases file name `fontawesome-free-5.4.0-desktop.zip`
- You have installed both solid and regular styles
- You have selected Solid style ([fa-music](https://fontawesome.com/icons/music?style=solid) is not available in the Free version in regular style)
