### ISSUE TITLE
Icon Request: read-later

### ISSUE THREAD

**Issue by codevin** [FortAwesome/Font-Awesome#1193]
It is variation of bookmark - which is folded to look like right arrow. It will be used to add an item to be bookmarked specifically for reading later.

This article has popularized this icon:
http://www.addthis.com/blog/2011/06/22/new-readitlater-icons/#.UaWqmEnHLzo

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
