### ISSUE TITLE
Icon Request: icon-rdf (or similar icon for semantic data)

### ISSUE THREAD

**Issue by cboettig** [FortAwesome/Font-Awesome#1198]
A possible starting point might be the W3C SVG icon for RDF data: 

http://www.w3.org/RDF/icons/rdf_w3c.svg

**Comment by anunos** [comment]
+1

**Comment by smairesse** [comment]
+1

**Comment by hielsnoppe** [comment]
+1

**Comment by agbeltran** [comment]
+1

**Comment by kael** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
