### ISSUE TITLE
Icon Request: arrow-curved

### ISSUE THREAD

**Issue by dyogophoenix** [FortAwesome/Font-Awesome#11991]
I would like to request the inclusion of a curved arrow like these:

↵ - arrow-curved-left ( left, right )
↲ - arrow-curved-long-left ( left, right )

for use in reply comments, list items or point the author for quotes !

**Comment by aethior** [comment]
@tagliala `arrows (category)` label for this request?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/arrow-turn-down-left?f=classic&s=solid)
