### ISSUE TITLE
Icon Request: Real Estate Industry Icons

### ISSUE THREAD

**Issue by jfri** [FortAwesome/Font-Awesome#1199]
I would like to see some icons for the Real Estate industry.

Specifically:

- <s>Bedrooms (icon-bed)</s>
- Bathrooms (icon-bath) #708 
- Square Footage (icon-area)
- For Sale Sign (icon-hanging-sign)
- Apartment Icon (icon-apartment)
- Townhouse Icon (icon-townhouse)
- Price Icon (icon-price-tag)

Other Real Estate industry icons are welcome as well.

**Comment by charly-housl** [comment]
+1 for bed and bath icons!

**Comment by xcode12** [comment]
+1

**Comment by antonvanhooydonk** [comment]
+1 for bath (bathroom)

**Comment by zralokh3** [comment]
+1 definitelly - bathroom, dining room, main/daily room, bedroom  etc.

**Comment by mayersdesign** [comment]
+1

**Comment by laviku** [comment]
+1

**Comment by 2point1creations** [comment]
+1000

**Comment by tagliala** [comment]
Sorry, I need to close this request because it does not meet our updated contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

A bed is already here, a bath is at #708 , for sale is here: #5107

Please open new individual requests for other icons having care of searching before

**Comment by NeoFelipeAS** [comment]
+1

**Comment by tracyalison11** [comment]
+1

**Comment by Samda** [comment]
+1

**Comment by laliev** [comment]
+1

**Comment by alexruizprado** [comment]
+1

**Comment by kikoseijo** [comment]
+1
