### ISSUE TITLE
Icon Request: fa-podcast-square

### ISSUE THREAD

**Issue by jenlampton** [FortAwesome/Font-Awesome#12012]
I am seeking a podcast square icon, much like the request posted in https://github.com/FortAwesome/Font-Awesome/issues/9912

> The icon would be great to have variants similar to other social media icons with inverses and shapes surrounding the image.

The previous issue was closed as a duplicate, but it looks like the fa-podcast-square variant was not added at the same time as fa-podcast icon, so I'm re-opening this request, specifically for the -square version to be added. I have exactly the use-case described in the other issue...

> This icon would be used along other social media icons like Facebook, Twitter, etc, to link to our podcast channel in iTunes.

My other icons in the set are all using the -square versions, so the non-square podcast icon looks out of place. 

The icon should be the inverse of:
<img width="730" alt="fa-podcast" src="https://user-images.githubusercontent.com/397895/34431106-48ca0ff2-ec29-11e7-9b6b-517136b3a3db.png">

Example:
![fa-podcast-square](https://user-images.githubusercontent.com/397895/34431097-350197f6-ec29-11e7-8369-0c4069a65fd3.jpg)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Comment by jenlampton** [comment]
Thanks, for the update. We've switched over to an SVG image library since this issue was opened. Because nobody else has wanted a square version, closing it is sensible.
