### ISSUE TITLE
Icon request: fa-file-clock (timesheet)

### ISSUE THREAD

**Issue by ebaynaud** [FortAwesome/Font-Awesome#12063]
fa-file-clock for timesheets!

Like this one:

![image](https://user-images.githubusercontent.com/1921301/34717722-482d87c2-f534-11e7-8aad-6d1a9d12c395.png) 

Fom http://www.cornerstone-group.com.au/prepare-yourself/timesheet-icon/

**Comment by MatthieuArzel** [comment]
You could alway stack the clock one into the blank file one as a temporary solution. :)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
