### ISSUE TITLE
Icon everywhere on the page

### ISSUE THREAD

**Issue by acarmich** [FortAwesome/Font-Awesome#12080]
Hi there, the play icon we have used on our site for some anchor buttons for some reason appears everywhere on our site and when I inspect it, it says that its a before sudo element. The icon tag has only been placed on anchors in one text block of visual composer wc bakery page builder. Can you please help?

Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This issue tracker should be used to report issues related to Font Awesome. Your request seems a support request

If you are a FA5 pro backer, please try the pro repository, otherwise, please double check your css (inspect elements from the browser development console) then consider using stack overflow

If you still think there is an issue with Font Awesome, please provide a fiddle showing the issue. You can start with the following:

SVG: https://jsfiddle.net/tagliala/a756ay7m/
CSS: https://jsfiddle.net/tagliala/4gcqLvt9/

Closing here

Hope it helps
