### ISSUE TITLE
Icon Request: icon-drag-drop (drag & drop)

### ISSUE THREAD

**Issue by JSchaeuble** [FortAwesome/Font-Awesome#12084]
![icon copy paste](https://user-images.githubusercontent.com/10127877/34936270-0dcbf7e2-f9e1-11e7-9749-1e7dd9ddfe38.png)

For my webapp an icon that symbolizes a drag-and-drop zone would be nice... I googled "drag and drop icon" and found some nice examples, e.g. an "image" (file-image-o) on top of a dotted rectangle... or an arrow on top of a dotted rectangle. couldn't find anything like it in FontAwesome.

Use cases: 

- Icon appears on users profilepic within a small overlay div that has drag-and-drop functionality. If a new image-file is dragged on the icon, the profile pic is dynamically replaced
- Icon appears in a div within an image- or file gallery. User knows even without "Drag files here" that this is a drag-and-drop zone

Wherever this icon appears within my app, I want my user to know instantly: "here I can upload stuff". In my case this is not limited to imagefiles but users can also upload xml and text files in different contexts, so maybe the icon should be "generic" (arrow on dotted rectangle)?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
