### ISSUE TITLE
[FontAwesome5] free version of light icons

### ISSUE THREAD

**Issue by dehghani-mehdi** [FortAwesome/Font-Awesome#12112]
Hi there,

FontAwesome is awesome, we all know that, I was waiting for v5 badly!
BUT when I saw the light version is not available for free, I disappointed.

So my answer to your question __Are we missing something in our results?__ is yes you did, light version of FontAwesome for free.

Thanks.

**Comment by alecpl** [comment]
I already said that in another ticket, but here again... Instead of making Light icons free, please make Regular and Solid free, at least in a way that when there's some Solid icon free, Regular version of that icon should be free and vice-versa.

Light icons didn't existed before, so I think they don't have to be free.

**Comment by robmadole** [comment]
Hey all,

We've thought about this extensively and have to strike a balance between what is free and what is paid. Right now Light and Regular are part of Pro only. For the foreseeable future this will remain the case.

@alecpl we only make a portion of the Regular style free as a courtesy to the users of Font Awesome 4 (think address-book-o).

**Comment by alecpl** [comment]
I appreciate the courtesy. However, there are icons that have only one version free. It would be simpler to:
1. have all solid icons free
2. have all regular icons free
3. have a set of free icons where both regular and solid version is free.
instead of a mix of the above we have now. I'd prefer 3.
