### ISSUE TITLE
Icon Request: fa-thank-you

### ISSUE THREAD

**Issue by reydtianero** [FortAwesome/Font-Awesome#12156]
Would like to request a thank you character with letters "ty"

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Even if this request doesn't explictly violate our contributing guidelines, I will close this because similar requests have been closed too (#11767 #5019)

Also, "TY" is not international and we are trying our best to keep Font Awesome's glyphs language independent

By the way, you can obtain this via CSS or SVG framework:

CSS: https://jsfiddle.net/tagliala/cxhgk1zy/4/
SVG: https://jsfiddle.net/tagliala/29n98o6j/2/

Things may change in the future, in that case we will reopen here
