### ISSUE TITLE
 Icon request: fa-thumbs-horizontal

### ISSUE THREAD

**Issue by Rai-Rai** [FortAwesome/Font-Awesome#12160]
Hi,
currently we have the icons fa-thumbs-up and fa-thumbs-down which is great for voting (" I like it" or "I don't like it").

I'm using these icons to rate incoming requests. But I also need a neutral one where the thumb is shown horizontal. (Meaning for me: Could be a good request, but take an other look at a later date)
Just showing no thumb at all is not possible since this already indicates that I didn't rate it yet.

No thumb-icon: New or unrated request
Thumb-up: Good request
Thum-down: User send garbage ;-)
Thum-horizontal: Not sure yet, will take a look if all the good ones are done.

Here's some mockup for my usecase (ignore the ugly colors):
![test](https://user-images.githubusercontent.com/2023869/35432356-1330d764-0280-11e8-8236-c6454e170374.png)

As you can see, just rotating the existing thumbs isn't a real option (I've tried it of course)

Would be great to see this in an upcoming version, Pro version works for me ;-)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
