### ISSUE TITLE
Icon Request:  Bixby Bridge

### ISSUE THREAD

**Issue by wkaalbe** [FortAwesome/Font-Awesome#12179]
I would like to request a fa icon for Bixby Bridge.
![bixby-bridge-front-view](https://user-images.githubusercontent.com/10901291/35521561-eb15de54-04ce-11e8-8d86-6bd64db7da12.jpg)

Thank you!
Kathryn

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Is this a brand or a landmark?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
