### ISSUE TITLE
Icon Request: fa-exhibition

### ISSUE THREAD

**Issue by muhammetbalci** [FortAwesome/Font-Awesome#12198]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a single color, suitable for 16px icon size example?

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by matthijsmgj** [comment]
Hi,

I would like to request this icon too. It looks like it has not been added since the initial request. So with the current icon request template included I'll try to provide a more comprehensive answer:

**What can it be used for?**
This could be used for exhibitions or at least in my case to represent a list where to find exibitions.

**Example image (optional)**
![image](https://user-images.githubusercontent.com/10169162/79167523-e02a3000-7de7-11ea-9768-5b38c15031ed.png)
![image](https://user-images.githubusercontent.com/10169162/79167733-6d6d8480-7de8-11ea-8712-91c21c66a393.png)
![image](https://user-images.githubusercontent.com/10169162/79167761-8118eb00-7de8-11ea-8223-2ffe7539a39f.png)

**Comment by shasherazi** [comment]
Any updates on this? It's been 5 years almost

**Comment by tagliala** [comment]
Hi,

given that

- there are no upvotes
- the title does not meet our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+)
- two out of three examples are available in FA Pro,

I will consider this closed by
- https://fontawesome.com/icons/presentation-screen?f=classic&s=solid
- https://fontawesome.com/icons/screen-users?f=classic&s=solid

If none of the above icons meet this use case, feel free to fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+)
