### ISSUE TITLE
Upgrading the master branch to Font Awesome 5

### ISSUE THREAD

**Issue by robmadole** [FortAwesome/Font-Awesome#12199]
Creating an issue to discuss the logistics of migrating `master` to Font Awesome 5.

The [`fa-5` branch](https://github.com/FortAwesome/Font-Awesome/tree/fa-5) currently contains the proposed new tree. Note that this new branch is not associated (a descendent) of the current 4.x master branch.

### Things to work through

- [ ] New README.md, are we missing anything?
- [ ] New CONTRIBUTING.md, is it good-to-go?
- [ ] New issue templates in `.github/ISSUE_TEMPLATE`
- [ ] How are we going to handle existing PRs?
- [ ] How are we going to handle existing open issues (docs, V4, requests, general)?
- [ ] What will this do to @tagliala's workflow? How will this affect him?
- [ ] Identify the things we will lose (like the `package.json` file, ability to install from GitHub)
- [ ] Should we direct folks to other repos/locations for specific flavors of Font Awesome (e.g. packages)?
- [ ] Provide list of useful links for community (updates/releases, status, help)

### Main collaborators on this effort:

* @robmadole
* @talbs 
* @tagliala

**Comment by robmadole** [comment]
@tagliala we are prepping for converting the main repository over to be Font Awesome 5. Brian wisely asked if we should go over this with you.

I've listed some of the items that specifically we need to think about. When you get some time give us your thoughts. We aren't going to make this transition until all of us are comfortable with it.

**Comment by tagliala** [comment]
@robmadole thanks for bringing this to my attention

> New README, are we missing anything?

Seems good to me 👍 

>  New CONTRIBUTORS, is it good-to-go?

Contributors = Contributing guidelines? They are awesome!

I hope that the users will not be discouraged to post new requests. I mean, we don't need a single color example for "car", but I definitely need a single color example of "traveling", because it could be a duplicate of an existing issue (airplane leaving) or it could be already here (airplane)

>  New issue templates in .github/ISSUE_TEMPLATE

Amazing!

>  How are we going to handle existing PRs?

Do we have choices? They could be shutted down from settings, and Contributing guidelines could be edited accordingly.

If the free repo source code is generated by the build system, merged PRs will be lost in any case. Is there any chance of cherry-pick commits and use them in the build system?

>  How are we going to handle existing open issues (docs, V4, requests, general)?

Don't know your plans for managing requests, other issues will require more thoughts on my side

> What will this do to @tagliala's workflow? How will this affect him?

Don't worry, I will adapt to the new workflow. 

> Identify the things we will lose (like the package.json file, ability to install from GitHub)

Beside the package.json stuff, I cannot help here.

> Should we direct folks to other repos/locations for specific flavors of Font Awesome (e.g. packages)?
> Provide list of useful links for community (updates/releases, status, help)

Readme has a lot of links, I could use reply templates on case-by-case basis, to provide more information if needed (e.g: CDN outage)

**Comment by robmadole** [comment]
@tagliala 

> I hope that the users will not be discouraged to post new requests. I mean, we don't need a single color example for "car", but I definitely need a single color example of "traveling", because it could be a duplicate of an existing issue (airplane leaving) or it could be already here (airplane)

I'll soften this language a bit. Good catch.

> Do we have choices? They could be shutted down from settings, and Contributing guidelines could be edited accordingly.

Well, we have a choice in the saved response we can use. The more I think about it the more I'm convinced that we need to close all of them. They just will not be applicable any longer once we merge this.

> If the free repo source code is generated by the build system, merged PRs will be lost in any case. Is there any chance of cherry-pick commits and use them in the build system?

No chance for a cherry-pick since the build system doesn't actually contain these files. I've added `.github/PULL_REQUEST_TEMPLATE.md` to warn about this.

> Don't know your plans for managing requests, other issues will require more thoughts on my side

* For docs, I think we have to read the issue and see if it applies to FA5
* For V4 stuff, I say we do an auto-reply ("FA 4 is end-of-life" kind of deal)
* For icon requests we need these to eventually go into the voting system (as icons)
* For general requests they eventually need to make it into our voting system (as feature requests)

We have a chance here to reverse some of the "abandoned community" feel we've earned. @tagliala you've done an amazing job of keeping on top of this project and for the most part we (devs) haven't followed through. That needs to change but we don't have a concrete plan yet. I'd like to earn some trust back with the community.

> Don't worry, I will adapt to the new workflow.

Okay. But if there is something we can do to help you please let us know. You've contributed so much to Font Awesome and have earned a vote at the table. I learned quickly to listen to you when you've brought things up.

**Comment by tagliala** [comment]
> For docs, I think we have to read the issue and see if it applies to FA5
For V4 stuff, I say we do an auto-reply ("FA 4 is end-of-life" kind of deal)
For icon requests we need these to eventually go into the voting system (as icons)
For general requests they eventually need to make it into our voting system (as feature requests)

I'm fine for all of the above points

@robmadole I have a [thin icon](https://github.com/FortAwesome/Font-Awesome/labels/thin%20icon) label for requests. 

I think we can shut down those requests: people needing light icons could go for FA Pro (or other free sets of their choice)

**Comment by xuv** [comment]
Hello

I'm happy to see that you plan to finally merge 5.0 into master. But I'm a little concerned on how this will play for icon contributors.

As I understand it, you have redesigned the whole set plus a whole lot more icons. You've also added 2 more styles to the icons, which will not be part of the free set. And you've done all this over the course of last year supported by a very successful kickstarter campaign. Really congratulations on all that achievement. It's quite amazing and inspiring.

**But how will the community collaboration play in the future?** 
- From what I can read in the FA-5 branch, there is no more build system being shared. All builds are done somewhere else private. And there is no way to replicate it.
- The fact that there is now 3 icon styles (of which 2 are not free) will make any icon submission more difficult to fulfill. Should a contributor design all three icons? Or just the free one? 
- And the future Contributing guidelines still mention that no PR will be accepted for icons and that [any PR will never be merged and attribution will not be given to the contributor of that PR](https://github.com/FortAwesome/Font-Awesome/blob/fa-5/.github/PULL_REQUEST_TEMPLATE.md).

I'd really appreciate an explanation on your intentions and what you expect from the community. Because my understanding here is that this repo will probably just be a file hosting service for the free compiled version of this project and the issues will only be used for icon request and bug reports. I still don't see why someone would do a PR with all this.

Thanks for you time and looking forward to read you.

**Comment by xAphex** [comment]
> How are we going to handle existing open issues (docs, V4, requests, general)?

Make a new repository/branch for V4 and shove everything in there?

**Comment by robmadole** [comment]
@xuv we don't accept icon contributions currently and that won't change with 5. PRs are a great way to illustrate where we have a problem. It's easy to point to code and it can sometimes be the best example.

Because Font Awesome sales a Pro version our build system will for the time being remain private (we've got all of our for-pay icons in there).

We hope that the community will continue much in the same way that it has. Submitting icon requests, bug reports, and using this repo as a way to communicate.

**Comment by xuv** [comment]
@robmadole: thanks for the explanation.

**Comment by robmadole** [comment]
This transition has now been made :+1:

**Comment by tagliala** [comment]
@robmadole thanks for the switch

I was updating my saved replies but templates don't seem to work

How  to reproduce 
1. https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md
2. click on "request a new icon" (or "submit a new issue")

**Comment by robmadole** [comment]
Got it! Nice catch, sir.

**Comment by robmadole** [comment]
Fixed in `master`

**Comment by xAphex** [comment]
@robmadole 
please make a CDN that autoupdates to latest FontAwesome version, something like this:
`<script defer src="https://use.fontawesome.com/releases/latest/js/all.js"></script>`
