### ISSUE TITLE
New site icon code

### ISSUE THREAD

**Issue by mckelveydigital** [FortAwesome/Font-Awesome#12216]
Love the new design guys. Noticed when I copy the <i> tag code from an icon page that the code is wrong. There is a stray 'r' in the class name. 
<img width="793" alt="screen shot 2018-02-01 at 16 12 30" src="https://user-images.githubusercontent.com/23477015/35689253-f3086dea-076a-11e8-98cb-f434db183b27.png">

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Since `fa-sign-out` is only available to Pro users, this issue should belong to the Font Awesome Pro repository.

Anyway, this is the code I get when copying

```
<i class="far fa-sign-out"></i>
```

It is ok, because the r in `far` stands for **r**egular

Please take a look here: https://fontawesome.com/how-to-use/svg-with-js#basic-usage

Hope it helps, closing here
