### ISSUE TITLE
Icon Request: icon-status

### ISSUE THREAD

**Issue by JonMasterson** [FortAwesome/Font-Awesome#1223]
Thanks for all your work!

Example:

Status: http://wpforce.net/media/genericons-by-automattic.jpg

**Comment by codevinsky** [comment]
+1

**Comment by yahyaerturan** [comment]
+1

**Comment by arafiq** [comment]
+1

**Comment by leotm** [comment]
+1

**Comment by semihs** [comment]
+1

**Comment by thpapag** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](fa-signal, fa-tower-broadcast)

**Comment by tagliala** [comment]
It's also available in FA Free https://fontawesome.com/icons/tower-broadcast?f=classic&s=solid
