### ISSUE TITLE
Icon request:icon-fan, icon-cooler, icon-airconditioner, icon-washingmachine, icon-fridge, icon-woven, icon-dryer, icon-stove, icon-radio, icon-musicplayer, icon-socket, icon-charger, icon-light, icon-bedlight, icon-exhaustfan, icon-chimney, icon-gyser

### ISSUE THREAD

**Issue by maniaddanki86** [FortAwesome/Font-Awesome#12261]
### What can it be used for?
Electrical home appliances icons in web pages
### Icon request checklist
I hope it would be great, if we have electrical home appliances icons like below
icon-fan, icon-cooler, icon-airconditioner, icon-washingmachine, icon-fridge, icon-woven, icon-dryer, icon-stove, icon-radio, icon-musicplayer, icon-socket, icon-charger, icon-light, icon-bedlight, icon-exhaustfan, icon-chimney, icon-gyser and so on

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

There is a checklist in the template:
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)
