### ISSUE TITLE
Request for New Icon

### ISSUE THREAD

**Issue by Renu5** [FortAwesome/Font-Awesome#12270]
Hello!

Can i please get a new icon .. similar to the one as ADN icon in font-awesome
Instead of Letter 'A' in the icon.. Can i get the word 'ADR' in the Icon.

Thanks
Renu

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
