### ISSUE TITLE
Youtube square icon wont load - Font Awesome 5

### ISSUE THREAD

**Issue by fayazara** [FortAwesome/Font-Awesome#12276]
### The fa-youtube-square loads for like a millisecond, then shows a crash icon instead

Using <i class="fab fa-youtube-square fa-3x"></i> it does not work, Tweeted about this and font_awesome replied me to raise a bug.

What did you expect? - I just want the icon to be displayed
 
How would you like this to work instead? - Display the youtube icon instead of a x inside a box

### What version and implementation are you using? - Font awesome 5

- [ ] Web Fonts with CSS

https://drive.google.com/file/d/1J_-w356hh8t1ZPqeRoJ0XIpSVXaFuMDk/view - watch this video for better understanding, when I refresh, icon is displayed for a minute then disappears.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Thanks for the video, but we cannot debug this issue with a video, there are a lot of information we should know about (browser? os? version of font awesome? are you loading icons from cdn or from local? are there any javascript or css framework involved? etc.)

Cannot confirm the issue: https://jsfiddle.net/tagliala/qq2eLxo1/7/

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [bug report request template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

Please also take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up
