### ISSUE TITLE
icon pack request: Combat

### ISSUE THREAD

**Issue by BTEK9** [FortAwesome/Font-Awesome#12286]
hey, im a pro user and wanted to know if you guys can make fighting/combat icons. 
swords, rifles, pistols. similar

**Comment by aethior** [comment]
Hi @BTEK9,

- https://fontawesome.com/icons/gun
- https://fontawesome.com/icons/sword
- https://fontawesome.com/icons/swords
- https://fontawesome.com/icons/dagger
- https://fontawesome.com/icons/mace
- https://fontawesome.com/icons/bow-arrow
- https://fontawesome.com/icons/sword-laser
- https://fontawesome.com/icons/swords-laser
- https://fontawesome.com/icons/person-rifle
- https://fontawesome.com/icons/person-military-rifle

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
Pack requests should be moved to the Pro repository, but I do not have the privileges

Since some icons were implemented, I'm considering this request fulfilled

If you want to request another pack or an extension of this pack, please open an issue in the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Closing here
