### ISSUE TITLE
FA5 Pro on Chrome 49

### ISSUE THREAD

**Issue by tyler7771** [FortAwesome/Font-Awesome#12295]
I'm using FA5 Pro on my companies site and it's working great on current versions of browsers. But, we're running into a strange error where on Chrome 49 some of the icons are working and others aren't. We have to support Chrome 49 because a large number of our users are still on Windows XP and it's the latest version of Chrome that's supported on XP.

Icon's are being generated using webfonts with css. I've tried importing the everything.js file and that fixes the rendering issue, but messes up all the sizes of the icons.

Any help would be great!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Since you are a Pro backer asking support for FA5 Pro, I should ask you to open this request in the Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro

Let me know if you have trouble in doing that

Closing here but feel free to comment
