### ISSUE TITLE
fa-search misspelling

### ISSUE THREAD

**Issue by anishaz** [FortAwesome/Font-Awesome#12313]
There is a typo for fa search in this link:

https://fontawesome.com/icons/search?style=solid

It wouldn't work if i did <i class="fas fa-search">.

Fixed with <i class="fa fa-search">

Screenshot of error:
<img width="702" alt="screen shot 2018-02-09 at 11 14 57 am" src="https://user-images.githubusercontent.com/5614019/36045416-7e196018-0d8a-11e8-97bc-0112cbb81538.png">

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`fas` is not a typo. The extra `s` stands for solid and `fa` is an alias for `fas`.

I suppose that your website is loading FA4 instead of FA5

Take a look here: https://fontawesome.com/how-to-use/upgrading-from-4#icon-name-changes

Hope it helps

Closing here
