### ISSUE TITLE
fa martial for the martial status .

### ISSUE THREAD

**Issue by hassan-kassim** [FortAwesome/Font-Awesome#12329]
have any icon for martial status for single and coupled one  fa single and fa couple.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide an example?

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

We have a request for wedding rings: #3025

**Comment by hassan-kassim** [comment]
Hi ,
an icon with man and woman for married symbol . 
separate one for singles.

**Comment by tagliala** [comment]
Hi,

since a man and a woman do not exactly represent a marital status, please use a combination of individual icons or the stacking feature

https://fontawesome.com/icons/male?style=solid
https://fontawesome.com/icons/female?style=solid

https://jsfiddle.net/tagliala/vLae8ted/9/

Hope it helps

Closing here
