### ISSUE TITLE
Icon request: fa-exe and fa-zipped

### ISSUE THREAD

**Issue by livelydevelopment** [FortAwesome/Font-Awesome#12326]
File exensions for executable and zipped files would be helpful.  Examples below:
[exe icon](https://cdn0.iconfinder.com/data/icons/document-file-types/512/exe-512.png)
[zipped icon](https://cdn0.iconfinder.com/data/icons/document-file-types/512/zip-512.png)

Thanks guys, this is a fantastic tool.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

A generic icon for a compressed archive is already here: https://fontawesome.com/icons/file-archive?style=solid

At the moment, I'm going to close this request because:
- You can use the SVG layering feature to implement file extensions (see example);
- You can stack text with icons if you are using CSS or FA 4.7;
- At the basic icon size of 16px, a three letter extension will be too large compared to the icon itself;
- I would like to avoid requests for `.HTML`, `.CSS`, `.JS`, `.SVG`, `.DAT`, `.PNG`, etc.

Example (SVG): https://jsfiddle.net/tagliala/vLae8ted/7/

Docs (SVG): https://fontawesome.com/how-to-use/svg-with-js#layering
Blog post (CSS): http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/

Hope it helps

Closing here
