### ISSUE TITLE
icon show error

### ISSUE THREAD

**Issue by maozhenhua2** [FortAwesome/Font-Awesome#12330]
![font awesome free 5 0 6 free](https://user-images.githubusercontent.com/7087532/36091613-40cdc5e0-101f-11e8-8c20-22e00ca47dac.png)

**Comment by maozhenhua2** [comment]
web-fonts-with-css

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

It seems that your browser (assuming that your image is a screenshot taken on a browser) is not loading the brand fonts

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [bug report request template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)
