### ISSUE TITLE
yall should make os logos 

### ISSUE THREAD

**Issue by james-5** [FortAwesome/Font-Awesome#12359]
it would be really cool if you could make OS  glyph

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Linux distros: #980, #9585
Apple: https://fontawesome.com/icons/apple?style=brands
windows: https://fontawesome.com/icons/windows?style=brands
linux: https://fontawesome.com/icons/linux?style=brands

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
