### ISSUE TITLE
Icon Request: AutoDesk and ESRI Icons

### ISSUE THREAD

**Issue by Zohar127** [FortAwesome/Font-Awesome#12357]
AutoDesk develops many industry standard design/drafting/engineering software packages. It is also very common for programmers to develop their own plugin software applications. Having Icons for AutoDesk products will help developers such as myself design better desktop applications for AutoDesk software.

ESRI GIS Software goes hand-in-hand with design and engineering in civil fields. Those icons will help desktop app developers create a consistent product.

![image](https://user-images.githubusercontent.com/27867704/36210169-bb1eb15e-116b-11e8-9b1c-f3a16a4e0253.png)

![image](https://user-images.githubusercontent.com/27867704/36210189-ca589180-116b-11e8-90f8-c5dd9218b4dd.png)

![image](https://user-images.githubusercontent.com/27867704/36210350-3c9b2c3a-116c-11e8-8b28-6e0b4291f682.png)

![image](https://user-images.githubusercontent.com/27867704/36210370-436d2ce8-116c-11e8-860f-cea4f3a048ea.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
