### ISSUE TITLE
Font awesome is not working and causing delay in loading

### ISSUE THREAD

**Issue by vaibhavdeveloper17** [FortAwesome/Font-Awesome#12382]
My wordpress blog is showing squares when i tried to optimize my site. I even tried editing my .htaccess but problem did not resolve. I want to load fontawesome css without effecting speed of my website. when I inspect Zixca.com it is showing CORS error.
https://tools.pingdom.com/#!/ehMPCw/https://zixca.com

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I've tried to reach zixca.com but I'm getting an "ERR_TOO_MANY_REDIRECTS" error, so I cannot take a look

Since as you said that is a wordpress blog, chances that there could be a lot of other libraries and tools and styles that could interfere with Font Awesome are high.

If you think there is an issue with Font Awesome itself, please provide a reduced test case.

Make sure to fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

Leaving this open

**Comment by tagliala** [comment]
No feedback, closing here
