### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by Harpreetsinghbedi** [FortAwesome/Font-Awesome#12395]
Can you provide some kind of server related icons?

Like:

cpu / processor, dedicated hosting, ram, shared server, cloud hosting, rack server, firewall, database, vps server, ftp, etc.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

server: https://fontawesome.com/icons/server?style=solid
CPU: #8630 
database: https://fontawesome.com/icons/database?style=solid
RAM: #3239
cloud: https://fontawesome.com/icons/cloud?style=solid
firewall: #4519


Please:
* make sure your request isn't already here
* search for duplicates
* create individual requests for each icon
* provide a single color example of the icon you are requesting, because  "ftp" and "vps" are quite abstract

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
