### ISSUE TITLE
Icon Request: fa-nhl-"team"

### ISSUE THREAD

**Issue by naluoli** [FortAwesome/Font-Awesome#12420]
Please would you consider professional teams?  NHL - Kings,  NHL-Dallas etc etc.  NBA-Lakers, NFL-Texans etc etc.  You have some labels... ie amazon etc... professional teams would be great...  example - this is NHL

![image](https://user-images.githubusercontent.com/36716550/36511953-adc2bb06-171d-11e8-87d8-1b5ea0b43dfe.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

At the moment, I'm going to label this as "wontfix".

I should advise you to consider another solution.

PS: if you are a FA5 Pro backer, try to request this category under the Pro repositori at https://github.com/FortAwesome/Font-Awesome-Pro/issues

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
