### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by computer900506** [FortAwesome/Font-Awesome#12438]
Hi
I'm using a wordpress theme Maxhost.
But I can't use the font-awesome icons in this theme, because if I entered the name related to font-awesome library, the icon is not displayed.
For example, there is no 'user' icon in the library.
how can i fix this problem?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Take a look at our get started guide: https://fontawesome.com/get-started

Then follow our docs for usage: https://fontawesome.com/how-to-use/svg-with-js

If you still have issues, please consider to ask your question on stack overflow, because this issue tracker is intended for new requests and bug reports

You can also ask for support to your theme's developer

Next time, please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)
