### ISSUE TITLE
Icon Request: fa-search-with-plus

### ISSUE THREAD

**Issue by Naicos** [FortAwesome/Font-Awesome#12445]
I am looking for a magnifying glass with a plus next to it not inside because that would
be understood as zoom-in.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please consider the stacking feature to implement this:

Docs: https://fontawesome.com/how-to-use/svg-with-js#layering
Example: https://jsfiddle.net/vLae8ted/79/

Ref: #1181

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.]()

**Comment by tagliala** [comment]
This is also available in FA Free: https://fontawesome.com/icons/magnifying-glass-plus?f=classic&s=solid
