### ISSUE TITLE
How long till desktop subsetter?

### ISSUE THREAD

**Issue by sentrypc** [FortAwesome/Font-Awesome#12442]
What is the estimated time frame on this and what it will it do?  Will this allow custom font files, css, scss, etc with the subset we choose?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Since the desktop icon subsetter is a Font Awesome Pro feature, could you please ask this question on the Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have accesso to the above repo, please make sure you have linked your font awesome account to your github account at fontawesome.com

Closing here
