### ISSUE TITLE
FontAwesome icons not showing because of Google Font Plugin?

### ISSUE THREAD

**Issue by gallantlygal** [FortAwesome/Font-Awesome#12476]
Hello,

I had this problem before and tried changing themes, but the problem persists. There are supposed to be social media icons in the menu from FontAwesome. However, they are showing up as blank squares or weird icons, depending. I tried deactivating my Google Fonts plugin to see if that was interfering with it, and that seemed to do the trick. However, I want to keep that plugin activated while seeing the social media icons in the menu. I checked for different versions of FontAwesome in the css, but they all were the same 4.7.0, so I'm not sure how to resolve this. They shouldn't be causing problems for each other like this...

Any advice?
https://gallantlygal.com
^site you can see the issue

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The first error to fix is that you are loading two versions of font awesome (probably one comes from your theme):

```html
<link rel='stylesheet' id='hamlet-lite-font-awesome-css-css'  href='https://gallantlygal.com/wp-content/themes/hamlet-lite/css/font-awesome.css?ver=4.9.4' type='text/css' media='all' />
<!-- ... -->
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
```

If you want to use FA 4.7.0, you can remove the second link because your theme is loading the very same version

The most !important thing, is that you get rid of this rule: 

```css
i {
    font-family: 'Cormorant Garamond'!important;
    font-style: italic!important;
    font-weight: 400!important;
}
```

It is part of your html, at the end of the head tag.

As a workaround, you can use "span" as a tag for font awesome icons, but you should really consider to remove that rule.

Hope it helps

Closing here

**Comment by gallantlygal** [comment]
If I want to use FA 4.7.0, I should remove the second link but leave the first one that says 4.9.4? Also, where can I find those links in the first place?

**Comment by tagliala** [comment]
> If I want to use FA 4.7.0, I should remove the second link but leave the first one that says 4.9.4?

Since there is no FA 4.9.4, my guess is that version number is related to WordPress

I've checked the download css file, and it is a FA 4.7.0

> Also, where can I find those links in the first place?

Sorry but this has to do with WordPress customization or with your theme

This is a relevant question on stack overflow, but you could have done this in a different way: https://stackoverflow.com/questions/41249590/wordpress-add-a-link-tag-to-head

**Comment by pankaj081984** [comment]
Fix the problem in less then 2 mins. Simple replacement of /font-awesome/5.13.0/css/fontawesome.min.css with /font-awesome/5.13.0/css/all.min.css and also font-awesome/5.13.0/js/fontawesome.min.js with /font-awesome/5.13.0/js/all.min.js can fix this issue. https://youtu.be/_GV_pEmLCLU
