### ISSUE TITLE
electricity

### ISSUE THREAD

**Issue by massry** [FortAwesome/Font-Awesome#12470]
Dear,
Need icons for electricity
thank you

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

https://fontawesome.com/icons/bolt?style=solid

If you have something else in mind, please edit this request and fill out our 
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

Closing here
