### ISSUE TITLE
Suggestion : Education icon pack

### ISSUE THREAD

**Issue by pulse14** [FortAwesome/Font-Awesome#12490]
Related to #4079 #1379 #2751 #3297 .....

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

If you are a FA5 Pro backer, feel free to use the Pro repository to request a package

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
