### ISSUE TITLE
Icon Request: fa-money-bill-dollar variation

### ISSUE THREAD

**Issue by dwhaas82** [FortAwesome/Font-Awesome#12525]
a variation of the fa-money-bill-alt icon.  The current one has a 1 in the middle.  Would like one with a $ sign instead.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

There is an alternative "empty" version of the money bill icon in FA5 Pro
https://fontawesome.com/icons/money-bill?style=solid, so I'm going to rename this request as `money-bill-dollar`

Since this icon is currency dependent and we should do the same for each currency in the set (well, except bitcoin 😁), I'm going to consider this request as a "set of icons".

Set of icons does not meet our [icon request checklist](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md), but I will leave this request open for the moment

If you are a Pro backer, you can take advantage of the empty bill and masking feature to create that icon by yourself, or you can ask a set of icons in the Pro repository

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
