### ISSUE TITLE
Icon Request: Construction

### ISSUE THREAD

**Issue by Indiabpowell** [FortAwesome/Font-Awesome#12538]
I think it would be very beneficial to have a set of construction icons added to FontAwesome... For example:  a crane, brick, traffic cone, hard hat, user with a vest... etc.

They already have a lot of great options, but I do think this would be a great category to add. :)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

If you are a pro backer, please open this issue in the font awesome pro repository.

Otherwise, you can open individual issues but please make sure that request aren't already here: #5790 #12500 etc.

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
