### ISSUE TITLE
Facebook-icon is not showing

### ISSUE THREAD

**Issue by emileblume** [FortAwesome/Font-Awesome#12544]
I have a bar with the regular Social Media icons. All icons are displayed except the Facebook-icon.
I use the following code for it: content: "\f39e"; with the following library:
<script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>

How can I make this icon show up?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please take another look at our docs: https://fontawesome.com/how-to-use/svg-with-js#pseudo-elements

Please also provide a reproducible test case, since I cannot reproduce this issue: https://jsfiddle.net/tagliala/qu83xrwp/13/

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)
