### ISSUE TITLE
Icon Request: text outline and text shadow

### ISSUE THREAD

**Issue by shenghou** [FortAwesome/Font-Awesome#12542]
a text page need this;
## text outline：
![image](https://user-images.githubusercontent.com/24260845/37142372-dce76d56-22f2-11e8-9881-c1122a8374a9.png)
![image](https://user-images.githubusercontent.com/24260845/37142536-5ad34f6e-22f3-11e8-9f80-827f08bf7b4b.png)

## text shadow
![image](https://user-images.githubusercontent.com/24260845/37142542-5f7d5582-22f3-11e8-8b27-564e055b6c39.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Have you a single color example for text shadow? The example you provided is not implementable

**Comment by shenghou** [comment]
Sorry , i just used black.

**Comment by aensley** [comment]
@shenghou There is a solution for the text shadow using CSS filter: drop-shadow(): https://github.com/FortAwesome/Font-Awesome/issues/11916#issuecomment-376271281

**Comment by shenghou** [comment]
Hi, thanks for your help @aensley

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
