### ISSUE TITLE
Icon request: Refer and Earn

### ISSUE THREAD

**Issue by gouthami13** [FortAwesome/Font-Awesome#12573]
It can be used for referring the other and earn some benefits in the website(like:getting cash back of Rs 100 or first order free etc)

- This is a single icon 
![referrals-64](https://user-images.githubusercontent.com/22232813/37269726-ddefcafc-25f1-11e8-9d0e-119f4f56accf.png)

its a sample image

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide an example?

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
