### ISSUE TITLE
fa-email

### ISSUE THREAD

**Issue by kallidan** [FortAwesome/Font-Awesome#12572]
How come you kept fa-envelope and removed fa-email?
In our date and era almost no-one use envelopes and surely not on the internet.
Please rename envelop to email soonest and I'm sure you save million of working hours for million developers all around the world by your 15 minute work!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> How come you kept fa-envelope and removed fa-email?

AFAIK, there has never been an alias `email` for `envelope`:
- https://github.com/FortAwesome/Font-Awesome/blob/fa-4/src/icons.yml#L2238
- https://github.com/FortAwesome/Font-Awesome/blob/fa-4/css/font-awesome.css
- https://jsfiddle.net/tagliala/0xt7wf4f/ (no icon)

There is definitely a documentation filter for email, in fact so you will see `envelope` when you search for `email`

![image](https://user-images.githubusercontent.com/556268/37270392-ef1fb76a-25ce-11e8-9de4-e227a9a22947.png)

I know that email could be a better name for this icon, but we cannot change it in FA5 because it will be a breaking change and alias have been dropped.

Ref: https://fontawesome.com/how-to-use/upgrading-from-4

Hope it helps, closing here

PS: The choice of `envelope` goes back to the days of Bootstrap 2, because at the time FA has been a replacement of Glyphicons. Ref: https://github.com/twbs/bootstrap/blob/v2.3.2/less/sprites.less#L55
