### ISSUE TITLE
Icon gallery page is very janky due to long running event handlers while scrolling (etc)

### ISSUE THREAD

**Issue by andydavies** [FortAwesome/Font-Awesome#12588]
I suspect this is what https://github.com/FortAwesome/Font-Awesome/issues/12303 was actually driving at.

When I load the site and scroll I get a really janky experience (on a rMBP, with Chrome 64) - analysing the performance timeline there are event handlers that are blocking the main thread for way too long - often in 250-500ms but even over 1s - and so wreck scrolling.

I've attached screenshot of one example, and if I can find time will dig in a bit further 

![screen shot 2018-03-13 at 10 18 36](https://user-images.githubusercontent.com/427052/37336010-fe3e5984-26a7-11e8-9bd0-f0d905c890e3.png)

**Comment by robmadole** [comment]
We'll work on it. Thanks for the feedback.

**Comment by tagliala** [comment]
Ref: #12215

Browsing the [icons gallery](https://fontawesome.com/icons?d=gallery) feels very sluggish.
On Chrome on Ubuntu 17.10, with an i7 CPU, scrolling down the page drops the FPS to 2 multiple times. 
![image](https://user-images.githubusercontent.com/9826460/35687094-9125228a-074c-11e8-89d8-53f7c7ff53c7.png)

Browsing a subset of icons (663 in the solid pack) still goes below 10FPS multiple times.
![image](https://user-images.githubusercontent.com/9826460/35687154-bd8c014a-074c-11e8-8e6a-0a36a8feb8bc.png)

The old site, while showing all the icons, didn't have performance drops. The [new cheatsheet](https://fontawesome.com/cheatsheet) also works flawlessly, going around 40FPS.
![image](https://user-images.githubusercontent.com/9826460/35687482-a02bb98c-074d-11e8-9990-b986b9aac193.png)

**Comment by tagliala** [comment]
Ref: #12629

I just visited the new website and it is totally unresponsible, I can't scroll or interact with the website at all.

```
Chrome Version 67.0.3372.0 (Official Build) canary (64-bit)
macOS High Sierra 10.13.3 (17D102)
```

https://www.youtube.com/watch?v=D_wA8W3cGak

**Comment by victornpb** [comment]
On safari, the experience is not AS BAD as Chrome, but it is because the way safari handles scrolling independently of WebKit Paint it doesn't lock the scroll bar like on chrome but you end up scrolling on an empty canvas.

**Comment by victornpb** [comment]
Part of the issue is caused by the `transform: translateZ(0);` hack, forcing webkit to render hundreds of layers on the GPU, and keep them on VRAM, this is a really bad practice and why premature optimisations like that are bad. Removing that css property improves scrolling significantly for me.

You should not force rendering engine to create layers unnecessary, because you want to let it raster and keep a smaller in system memory image instead of large amount of layers on video ram (which is more scarce than system ram) 

![screen shot 2018-04-03 at 09 59 59](https://user-images.githubusercontent.com/3372598/38250753-03e05dfe-3726-11e8-8f7f-56eb18d30d00.png)
