### ISSUE TITLE
Icon request: icon-cfdi

### ISSUE THREAD

**Issue by paynalton** [FortAwesome/Font-Awesome#12606]
Hi guys, can i have a CFDI icon???

CFDI is a XML file sha256 signed by the Tax Office to validate invoices and payments.

There are not official CFDI artwork

Thanks.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a single color image of this brand and an official website?

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by paynalton** [comment]
this is the official site but there is not any artwork:  http://www.sat.gob.mx/informacion_fiscal/factura_electronica/Paginas/Anexo_20_version3.3.aspx

Some nice thirth party icons:

http://losimpuestos.com.mx/wp-content/uploads/CFDI.png
http://consysware.com/images/consysware/cas/logo_cfdi.png
http://is3.mzstatic.com/image/thumb/Purple128/v4/ed/f7/d6/edf7d619-7819-be1d-d14a-5747fbf34111/source/512x512bb.jpg

### What can it be used for?

To download and manage actions related with CFDI documents.

### Icon request checklist

- [ X ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ X ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ X ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ X ] I have included at least one example image if it could be helpful (optional)
- [ X ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
