### ISSUE TITLE
5.0.8 has changed the Font Face Family names

### ISSUE THREAD

**Issue by N1ghteyes** [FortAwesome/Font-Awesome#12614]
It looks like all of the font families are now simply called 'Font Awesome 5 Pro' rather than 'Font Awesome 5 Pro Light' etc.

This is for 5.0.8 Pro specifically, as downloaded from the website.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Since this issue is only related to FA5 Pro, could you please open this issue in the Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro ?

If you don't have accesso to that repo, please make sure your fontawesome.com account is linked to your github account at https://fontawesome.com/account/linked-accounts

**Comment by N1ghteyes** [comment]
@tagliala Done :). issue number 1052. I'll close this one off in the mean time then.

Thanks
