### ISSUE TITLE
Multiple Icon Requests and Additions

### ISSUE THREAD

**Issue by themil** [FortAwesome/Font-Awesome#12647]
Hey guys, love the Font-Awesome framework!

Just going through a number of icons. I'm sure these are coming in the future in the 'mysterious categories' in the 54 Icon Packs, but thought I'd put the ideas out there :)

**Warning signs:** Toxic, Nuclear, Poison, Chemical
**Pets:** Fish, Cat, Dog, Bird
**Climate:** More Thermometers (full, half), Heat Waves, Wind
**Technology:** SIM Card, Chemical Reader Cards (two chips instead of 1), Probe, Lightbulb with Light Rays, SD Card, Disk Hard Drive, SSD, VLC Player
**Periodic Table:** All Elemental Abbreviations, Simplified Table
**Nature:** Ripple, Big wave, Small Wave, Trees Other Than Pine
**Military:** ships, tanks, military status symbols (Cornell, Captain)
**Gamer:** Console, Mouse, Earbuds, Wired Headphones, Brands (OBS, Elgato, Scuff, Razer), Stream? (Live?)
**Popular Cryptocurrency:** LTC, ETH, ZEC, XMR, XRP, BCH, Digital Wallet?

Anyways, thanks!!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

If you are a pro user, you can request categories in the Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro. If you don't have access to the Pro Repository, please check that you have linked your github account at fontawesome.com

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
