### ISSUE TITLE
Icon request: mobile-slash

### ISSUE THREAD

**Issue by umbarov** [FortAwesome/Font-Awesome#12661]
📵

**Comment by jbelien** [comment]
Hello @7u7u ,

You can easily do it by "layering" icons `mobile-alt` and `ban` ; have a look at https://fontawesome.com/how-to-use/svg-with-js#layering

**Comment by 7u7u** [comment]
@jbelien thanks

**Comment by aethior** [comment]
*Related Unicode Emoji* #222
📵 [U+1F4F5](https://emojipedia.org/emoji/%F0%9F%93%B5/) No Mobile Phones
Also known as `No Cell Phones`,  `No Phones` and `No Smartphones`.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
