### ISSUE TITLE
Icon Request: Water Digger

### ISSUE THREAD

**Issue by Belligeron** [FortAwesome/Font-Awesome#12685]
For use with Gingr, I'd like to see a good icon for dogs that dig in water bowls. I was thinking a shovel/water combo like this:
![water digger](https://user-images.githubusercontent.com/37710767/37846761-df30205e-2e8b-11e8-8de0-93511149f50f.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
