### ISSUE TITLE
Icon request: Social Network App Icons

### ISSUE THREAD

**Issue by supercreator** [FortAwesome/Font-Awesome#12684]
Request the icon for many social network apps such as the icon that represent the sticker icon in chat box and team icon, following icon, follower icon, friend icon. Thank you Font-Awesome

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
