### ISSUE TITLE
fas fa-circle icon bugs with Firefox

### ISSUE THREAD

**Issue by tomzi** [FortAwesome/Font-Awesome#12706]
Hi,
When i try to set the icon font-size to 3px on Firefox, it looks like 10px.
It works perfectly with Chrome and Safari.
The first one is the icon on Firefox and the other on is the same one with Chrome
![capture d ecran 2018-03-26 a 22 31 03](https://user-images.githubusercontent.com/4091451/37931289-6dc765d2-3145-11e8-88cb-82a18da0efd3.png)
![capture d ecran 2018-03-26 a 22 31 11](https://user-images.githubusercontent.com/4091451/37931303-75e7660e-3145-11e8-9b2e-af186391adba.png)

Do you have a solution ?

Thanks,
Thomas

**Comment by slyk-style** [comment]
Do you have the page link in question. It could be something with your code.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)
