### ISSUE TITLE
Font awesome 5 Free black squares in iOS 9, 10 system font

### ISSUE THREAD

**Issue by vincent7128** [FortAwesome/Font-Awesome#12705]
I try font awesome 5 free icons only show the black square in to iOS 9, 10 system font.
But font awesome 4 works fine.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

Please provide all the information needed and a reproducible test case and I will reopen this
