### ISSUE TITLE
Icon Request: weebly and other website builder icons

### ISSUE THREAD

**Issue by oborseth** [FortAwesome/Font-Awesome#12718]
It would be great to have icons for weebly, wix, squarespace, etc.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
