### ISSUE TITLE
icon fa-lamp 'light' and 'regular' are same, release 5.0.9

### ISSUE THREAD

**Issue by josmaissan** [FortAwesome/Font-Awesome#12725]
Release 5.0.9 
icon `fa-lamp` "light" and "regular" both showing "light" version (at least on [icon overview](https://fontawesome.com/icons?d=gallery&q=lamp&s=light,regular&c=moving) ) 🙄

**Comment by dflock** [comment]
Concur: The new lamp icon in the Moving pack looks identical in [regular](https://fontawesome.com/icons/lamp?style=regular) and [light](https://fontawesome.com/icons/lamp?style=light):

![screenshot_2018-03-28_21-16-11](https://user-images.githubusercontent.com/47756/38069837-66d8b9e0-32cd-11e8-8781-3fcb4cdf0270.png)

**Comment by josmaissan** [comment]
Something is missing I guess

**SVG with JS** at **macOS 10.13.3** latest versions of browsers

![safari](https://user-images.githubusercontent.com/24986277/38079803-15b0cb7a-3340-11e8-8479-15f8ce94e12b.png)
Safari, Opera and Waterfox (at 1st landing)

![firefox](https://user-images.githubusercontent.com/24986277/38079772-03c8c3b8-3340-11e8-94b1-b86532d463e0.png)
Firefox, Vivaldi, "Safari Technology Preview" and Waterfox (at reload)

**Comment by tagliala** [comment]
Hi!

Thanks for reporting this

They are definitely the same icon, or the difference is not tangible 🤦‍♂️

**Comment by talbs** [comment]
Thanks for the keen eyesight and spotting this, @josmaissan. We'll get this fixed right up for you and everyone else.

**Comment by talbs** [comment]
Hey, @josmaissan. Thanks again for bringing this to our attention. 5.0.10 has the fix for this out. The [regular](https://fontawesome.com/icons/lamp?style=regular) and [light](https://fontawesome.com/icons/lamp?style=light) styles should have two distinctive feels - one for your general room decor purposes and the other for more of a mid-century modern feel. 😛 

Let us know if you spot anything weird going on.
