### ISSUE TITLE
Icon Request: Wildlife Icons

### ISSUE THREAD

**Issue by KipOmaha** [FortAwesome/Font-Awesome#12755]
Hi, my name is Steve and I'm new to FA.  Thanks for hosting this repository 👍 !

In any case I'm in the process of getting a website built, and looked through the offerings and didn't find a selection for wildlife, here is a link with the search param for wildlife 
=> https://fontawesome.com/icons?d=gallery&q=wildlife 

 Was wondering if their existed plans to create a few. 

Also, would be happy to share any of my own if I can think of any good ideas 👍 Here's the list I need to get done:

1. Rodents
2. Bugs 
3. Bats
4. Bed Bugs
5. Snakes
6. Spiders 
7. Ants 
8. Rats

Regards,
Steve

**Comment by KipOmaha** [comment]
Below is a link to some work I have done for this issue.

[OneDriveLink](https://1drv.ms/f/s!AiMlv3J2Bh6PpXqM9N8WKf98iVef)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by KipOmaha** [comment]
Thanks, I did end up finding a couple of nature icons :) in the pack too just not under wildlife. As far as requesting a little bit of meta such as adding a tag like `wildlife`, would that be a bug issue/enhancement?

**Comment by tagliala** [comment]
@KipOmaha we are monitoring and improving search tags.

If you want to propose a nature/wildlife filter in the docs, please open a simple new request (without templates)
