### ISSUE TITLE
Icon Request: fa-dashed-arrow

### ISSUE THREAD

**Issue by bhartwell** [FortAwesome/Font-Awesome#12761]
Was hoping to find dashed arrow icons for a project I'm working on. I'm creating an application that involves marking utilities and directional flow of water, other liquids, gas, etc... Solid arrows and dashed arrows are relevant for the application.  Love the work you all have done on creating the current set of icons and how easy it is to implement into my WPF application. Keep up the good work. Thanks. 

![dashedarrow](https://user-images.githubusercontent.com/8823186/38232378-97afdee8-36cb-11e8-9b51-485eef856c72.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request *potentially* involves 474 icons: https://fontawesome.com/icons?d=gallery&c=arrows

Is this limited to:
- arrow-down
- arrow-left
- arrow-right
- arrow-up

?

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
