### ISSUE TITLE
Icon Request: Library (Books, Etc.)

### ISSUE THREAD

**Issue by jboutin** [FortAwesome/Font-Awesome#12776]
It'd be awesome if we had some more library-related icons :smile:.

Examples:
https://png.icons8.com/metro/1600/book.png
https://imageog.flaticon.com/icons/png/512/29/29302.png?size=1200x630f&pad=10,10,10,10&ext=png&bg=FFFFFFFF
https://previews.123rf.com/images/kurdanfell/kurdanfell1506/kurdanfell150600012/48252783-book-icons-library-icons-education-icons-reading-icons-learning-icons-book-pictogram-knowledge-icons.jpg
https://thumbs.dreamstime.com/b/library-icons-vector-illustration-symbol-graphic-design-72450228.jpg

Thanks!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
