### ISSUE TITLE
Please add category house for real-estate agency

### ISSUE THREAD

**Issue by BasicSoft** [FortAwesome/Font-Awesome#12780]
Our company build web sites for real-estate agency, so please add a "house" category with these icons:

- surface area (for rooms measuring)
- rooms (for counting rooms)
- balcony
- terrace
- garden
- bedroom (it will be ok "bed" icon)
- floor levels
- lifter
- parking
- piloty

Here you are some suggestions.
Thanks very much

![area](https://user-images.githubusercontent.com/25501553/38355830-50e68ff8-38be-11e8-9ce6-af545c96b0ee.png)
![floorplan](https://user-images.githubusercontent.com/25501553/38355855-5f37714e-38be-11e8-91f0-d0459b2e9968.png)
![balcony](https://user-images.githubusercontent.com/25501553/38355867-663b4e8e-38be-11e8-9867-46850f3237f7.png)
![terrace](https://user-images.githubusercontent.com/25501553/38355895-799995c6-38be-11e8-9e1b-852cf09b6ee9.png)
![garden](https://user-images.githubusercontent.com/25501553/38355898-7e004b64-38be-11e8-9dd5-8eb7417bbbe4.png)
![floor-level](https://user-images.githubusercontent.com/25501553/38355960-abf546f0-38be-11e8-962a-a8ef155d7636.png)
![elevator](https://user-images.githubusercontent.com/25501553/38355973-affae76e-38be-11e8-9cf4-47164cab1c62.png)
![parking](https://user-images.githubusercontent.com/25501553/38355975-b33b68ae-38be-11e8-86b8-beed146ce570.png)
![piloty](https://user-images.githubusercontent.com/25501553/38355980-b6b5c8bc-38be-11e8-9b04-0b22f0784f47.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

If you are a pro backer, please open this issue in the font awesome pro repository.

Otherwise, you can open individual issues but please make sure that request aren't already here, eg: #1559

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
