### ISSUE TITLE
Icon request: fashion/apparel icon set in FontAwesome Pro

### ISSUE THREAD

**Issue by carloslongen** [FortAwesome/Font-Awesome#12784]
### What can it be used for?

A set of icons for fashion and apparel shopping apps, sites or docs. As it already exists for logistics, medical and other sets in FontAwesome Pro.

### Icon request checklist

- [SET] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [YES] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [YES] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [NO] I have included at least one example image if it could be helpful (optional)
- [YES] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

> [SET] This is a single icon or matched pair (Ex: lock / unlock)

Requests for set are only allowed in the FA5 Pro repository. If you are a FA5 pro backer, please open your request here: https://github.com/FortAwesome/Font-Awesome-Pro

**Comment by carloslongen** [comment]
Hi!

OK, thanks by your feedback.

I'm not actually a Pro customer, but we're going to be. And we would really apreciatte to have an fashion icon set.

I've tried your link https://github.com/FortAwesome/Font-Awesome-Pro, but got an 404 error.

Where is the right place do post?

Thanks in advance.
