### ISSUE TITLE
Icon Request: Brand Icons

### ISSUE THREAD

**Issue by effone** [FortAwesome/Font-Awesome#12789]
MyBB Community Forums:
https://eff.one/img/svg/mybb.svg

Keybase:
https://eff.one/img/svg/keybase.svg

NPM:
https://upload.wikimedia.org/wikipedia/commons/d/db/Npm-logo.svg

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

NPM: https://fontawesome.com/icons/npm?style=brands

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
