### ISSUE TITLE
Icon request: co2

### ISSUE THREAD

**Issue by brunoalreis** [FortAwesome/Font-Awesome#12798]
### What can it be used for?

This icon would represent CO2 gas. It would be usable in IoT measurement context.

### Example image (optional)

https://www.iconfinder.com/icons/388845/carbon_co2_ecology_emissions_environment_oxide_polution_icon#size=256

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by ph0rque** [comment]
>  The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

CO2 is definitely concrete (or at least can be used to make concrete: https://phys.org/news/2016-03-carbon-dioxide-sustainable-concrete.html) 😂

**Comment by brunoalreis** [comment]
@ph0rque, ok. Edited.

**Comment by maxcoffer** [comment]
We're using this ones in IoT software right now, as examples. For CO, CO2, smoke + CO2 detectors.

![co_icons](https://user-images.githubusercontent.com/3885715/52342963-1f583680-2a17-11e9-91e3-578753b47bc6.jpg)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
