### ISSUE TITLE
Icon request: fa-line-alt

### ISSUE THREAD

**Issue by thammarith** [FortAwesome/Font-Awesome#12805]
### What can it be used for?

Same as `fa-line` except it should be only the speech bubble with the word LINE without the rounded retangle. 

The reason for asking another one is because `fa-line` is too small and incomprehensible when scaled down.

### Example image (optional)

[Example image](https://imgur.com/a/SSEH1)

### Icon request checklist

- [/] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [/] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [/] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [/] I have included at least one example image if it could be helpful (optional)
- [/] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
