### ISSUE TITLE
Icon Request - Jewish symbols

### ISSUE THREAD

**Issue by freedmandil** [FortAwesome/Font-Awesome#12835]
As a fontawesome user it would be awesome to have a variety of Jewish-themed icons
these include as examples:
![icons](https://user-images.githubusercontent.com/17168031/38632805-79dbf198-3dc6-11e8-8024-de0a6735c374.jpg)
there are many jewish themed icons perhaps each one needs to be reviewed separately?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
