### ISSUE TITLE
Game Developer Brands

### ISSUE THREAD

**Issue by Ronacs** [FortAwesome/Font-Awesome#12845]
Can we have 

- Discord (head icon only), 

- Ubisoft logo, 

- EA,

And others that are related to the game industry. 

 ![image](https://user-images.githubusercontent.com/16950427/38691243-2a0952cc-3e35-11e8-8e67-245f14cd4d2c.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
