### ISSUE TITLE
hope add to Unionpay、alipay、wechatpay icon

### ISSUE THREAD

**Issue by wolfan** [FortAwesome/Font-Awesome#12859]
![捕获.JPG](https://i.loli.net/2018/04/15/5ad2d04fba2ac.jpg)
from http://chuangzaoshi.com/icon/

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
