### ISSUE TITLE
Icon Request: fa-xenforo, fa-buycraft, fa-spigotmc, fa-mc-market

### ISSUE THREAD

**Issue by DoubleThePsycho** [FortAwesome/Font-Awesome#12863]
[XenForo](https://imgur.com/a/U8qV5)
[BuyCraft](http://pbs.twimg.com/profile_images/965967142012190720/JbCSlFtR.jpg)
[SpigotMC](https://pbs.twimg.com/profile_images/378800000032830602/c3ddbb8ebdbb08f1dbae769e3235611b_400x400.png) [Alt](https://proxy.spigotmc.org/309f539b2d1e8ffa7e3bf2e42aca882a7bb2d61e?url=http%3A%2F%2Fi.imgur.com%2FIWLFB8x.png)
[MC-Market](https://pbs.twimg.com/profile_images/662169291282747392/MuaVsCyf_400x400.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
