### ISSUE TITLE
Font Awesome Brands stopeed displaying in Chrome

### ISSUE THREAD

**Issue by SashaBurkhardt** [FortAwesome/Font-Awesome#12868]
We have a purchased package of Font Awesome; all files reside in our own server. As of April 12, 2018, all Font Awesome Brands icons stopped displaying in the latest Chrome version (Google Chrome - Version 65.0.3325.181 (Official Build) (64-bit), Mac OS)

We are using CSS + Web font approach.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Since I cannot confirm this issue: https://jsfiddle.net/tagliala/cy2gk6ys/19/ (Chrome 65 / macOs 10.13.4), could you please provide a reproducible test case?

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

Please also check your development console

**Comment by giacomodeglinnocenti** [comment]
I actually found that it's OK to just include the fontawesome-all.css and NOT the others, BUT when using the brand icons, the css selector in HTML DOM must be `fab` and not `fa`.

Really confusing this lack of backward compatibility... or is this a bug?

**Comment by tagliala** [comment]
Glad you solved

> Really confusing this lack of backward compatibility... or is this a bug?

Maybe you removed the v4-shims javascript file from your assets?

All versions of FA5 require `fab` for brands

Please take a look here: https://fontawesome.com/how-to-use/upgrading-from-4#icon-name-changes

**Comment by giacomodeglinnocenti** [comment]
Ok, didn't know about this change, nice to know.

Now I see that in the fa website, in the icon detail, there was already a correct selector example I didn't notice before `<i class="fab fa-facebook-square"></i>`.

Thanks for support.
