### ISSUE TITLE
Your Documentation on adding single Icons does not Work

### ISSUE THREAD

**Issue by ZeroPie** [FortAwesome/Font-Awesome#12871]
This Works (index.js):
```
import fontawesome from '@fortawesome/fontawesome'
import solid from '@fortawesome/fontawesome-free-solid'

// Add the icon to the library so you can use it in your page
fontawesome.library.add(solid.faUser)
```

This does not (index.js): 
```
import fontawesome from '@fortawesome/fontawesome'
import faUser from '@fortawesome/fontawesome-free-solid/faUser'
import faCircle from '@fortawesome/fontawesome-free-regular/faCircle'
import faFacebook from '@fortawesome/fontawesome-free-brands/faFacebook'

fontawesome.library.add(faUser)
fontawesome.library.add(faCircle)
fontawesome.library.add(faFacebook)
```

My Code: (index.js)

```
import fontawesome from '@fortawesome/fontawesome'
import faBars from '@fortawesome/fontawesome-free-solid/faBars'
fontawesome.library.add(faBars)
```

Error:
```
Uncaught TypeError: Cannot read property 'default' of undefined
    at Object.<anonymous> (app.js:12)
    at c (app.js:4367)
    at Function.r.import (app.js:4367)
    at app.js:4364
    at app.js:4367
:4444/@fortawesome/fontawesome-free-solid/faBars Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:4367 @fortawesome/fontawesome-free-solid/faBars not found on request
```

let faBars = require('@fortawesome/fontawesome-free-solid')
Did not work either

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately I cannot confirm, this is working in my use case: https://github.com/diowa/ruby2-rails5-bootstrap-heroku/blob/master/app/javascript/packs/application.js#L14-L17

Do you mean that the icons are not showing or that tree shaking is not working?

Could you please provide as much information as you can and maybe a reproducible test case?

**Comment by voveson** [comment]
I'm having an issue with this as well. The documented process does not work for me. What's strange is, when I enter `FontAwesome` in the browser console, I see that `Window.FontAwesome` has been set, and `Window.FontAwesome.library` is an object with definitions for the icons I have imported. The icons do not render -- instead I see the 'missing icon' placeholder (blinking circle with a ? inside).

I am also seeing the same behavior as @CrashToDesktop. Using destructuring I can get it to work, but at the cost of bloating my build with **_all_** of the icons, rather than the ones I am explicitly importing. Also, I am able to completely eliminate all `fontawesome.library.add(...)` statements, and icons still render.

**Comment by tagliala** [comment]
Hi,

please open new issues and provide reproducible test cases.

If you are using other technlogies in your stack (e.g.: gulp), please take a look at #13232

If you need an example of tree shaking working in Webpack 4, please take a look at https://github.com/FortAwesome/Font-Awesome/issues/13260#issuecomment-398409989

If you need an example of tree shaking working in Webpack 3 + Rails webpacker, please take a look at https://github.com/tagliala/fontawesome5demo

I'm going to close here because we changed a lot of things in Font Awesome 5.1.0

Please upgrade and take a look at the new documentation:
https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers
https://fontawesome.com/how-to-use/on-the-web/advanced/svg-javascript-core

**Comment by voveson** [comment]
Thanks, @tagliala! I didn't realize so much had changed. Everything works great after upgrading and following the new docs.

**Comment by rgkeith3** [comment]
Just going to comment here because I was dealing with this and found a solution. I'm trying to cut down my bundle size by only importing the icons i need.

`import faHome from '@fortawesome/free-solid-svg-icons/faHome';`
doesn't work as illustrated in this thread

and `import { faHome } from '@fortawesome/free-solid-svg-icons';` imports the whole 'free-solid-svg-icons'

however i found that `import { faHome } from '@fortawesome/free-solid-svg-icons/faHome';` works as you'd expect the first example to work and cuts down bundle size significantly if you're only using a few icons.

**Comment by tmaly1980** [comment]
Without the braces assumes there's an "export default" . With the braces just looks for an export named that variable. There's a huge difference.

**Comment by Doctorrr** [comment]
Have bought "Pro".
 
`import { library, dom } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-free/js/all";
import { faSearch } from "@fortawesome/pro-light-svg-icons";
import { faBars } from "@fortawesome/pro-light-svg-icons";
library.add(faSearch);
library.add(faBars);
dom.watch();`

the first one (faSearch) is working perfect, second one is not at all.
