### ISSUE TITLE
Icon request: fa-food-truck

### ISSUE THREAD

**Issue by ngandhy** [FortAwesome/Font-Awesome#12875]
### What can it be used for?

This can be used for identifying mobile food and food trucks 

### Example image (optional)

https://www.pinterest.com/pin/412431278351560098/
https://thenounproject.com/term/food-truck/5363/

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/truck-utensils?f=classic&s=solid)
