### ISSUE TITLE
Icon request: relief-valve

### ISSUE THREAD

**Issue by bfbrey** [FortAwesome/Font-Awesome#12884]
### What can it be used for? OSHA Process Safety Management App tracking relief valves

 Instead of a "chip" use the icon as a container for an item number

### Example image (optional)
![image](https://user-images.githubusercontent.com/30204230/38905394-b8fa7e70-426d-11e8-9c03-bd608c32b050.png)

### Icon request checklist

- [ x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x ] I have included at least one example image if it could be helpful (optional)
- [x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Any single color, 16px size suitable example?

**Comment by bfbrey** [comment]
Hi Geremia,

 

Thanks for the speedy reply…any single color would be great…it’s just the shape that maters or something close.

That would be a fabulous addition to my app!

 

Billy Brey

**Comment by tagliala** [comment]
@bfbrey

Sure, they will definitely be single color icons.

I've asked if you can provide a single color icon as an example for the implementation, suitable for the 16px icon size

Please do not attach them to emails because they will not work

Use https://github.com/FortAwesome/Font-Awesome/issues/12884

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
