### ISSUE TITLE
request: renewable-energy

### ISSUE THREAD

**Issue by SteffenMangold** [FortAwesome/Font-Awesome#12903]
Iconset for renewable energy like:
wind turbine, photovoltaic, electrical tower, tree, cole powerplant, atom powerplant, dam.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by SteffenMangold** [comment]
?? What did I miss ???
"Example image (optional)"
I respect the request checklist

**Comment by tagliala** [comment]
> Should I really submit a single request for every Icon from the set?

Yes, because single requests are easier to maintain

If you are a Pro Backer, you can request a set in the Pro repository

**Comment by SteffenMangold** [comment]
Oh the I have to go to  Pro repository :)

**Comment by SteffenMangold** [comment]
Ho do I gett to the  Pro repository?
