### ISSUE TITLE
Icon Request: fa-asap

### ISSUE THREAD

**Issue by weberci** [FortAwesome/Font-Awesome#12917]
Hello Folks,
i´d like to request a new Icon. It would be so great if you could implement a button like this.
It is the Name of our Company - but you could also take it as "as soon as possible", what we also stand for.
We want to use it to modify our cplace-development and Homepage.
Thank you so much in advance!
I wish you a nice Weekend :) 
Greetings Cindy

(I also attached it as an EMF-Picture)
![fa-asap](https://user-images.githubusercontent.com/38278242/39036174-056ae2ac-447d-11e8-98d1-e09d5a48ac0a.jpg)
[fa-asap.zip](https://github.com/FortAwesome/Font-Awesome/files/1931143/fa-asap.zip)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
