### ISSUE TITLE
Icon Request: Airplay, Cast, Picture-in-Picture

### ISSUE THREAD

**Issue by BenjaminHoegh** [FortAwesome/Font-Awesome#12925]
- video-airplay
- video-cast
- video-picture-in-picture _( Could also be named `video-pip` )_

See [#10991](https://github.com/FortAwesome/Font-Awesome/issues/10991) for a example of Picture in Picture icon

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
