### ISSUE TITLE
Icon request: icon-binder

### ISSUE THREAD

**Issue by pnwfox** [FortAwesome/Font-Awesome#12946]
A binder please. This could be used for Reports or Submittals, common in government and AEC industries. It could also be an alternative for education-related fields

![100155-200](https://user-images.githubusercontent.com/25514513/39216803-fa84ab40-47d1-11e8-8ebe-9d69b9e484b4.png)
Patrick Snyder's from the Noun Project, but has room for improvement

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
