### ISSUE TITLE
Icon Request: fa-laptopscreen

### ISSUE THREAD

**Issue by amyelzea** [FortAwesome/Font-Awesome#12981]
Please create laptop screen icon w/pointer. We have a few icons, that would like to have extended access to via Font-Awesome.
Thanks.

Laptop Screen
Laptop
Computer

![computer](https://user-images.githubusercontent.com/24258716/39442578-575db344-4c77-11e8-8a49-e41b804e5f42.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Since we already have laptop and mouse pointer, given the specific use case of this icon, I would go for layering: https://fontawesome.com/how-to-use/svg-with-js#layering

SVG implementation: https://jsfiddle.net/tagliala/kmgntg1b/2/

Hope it helps

Closing here
