### ISSUE TITLE
Academic icons

### ISSUE THREAD

**Issue by mocnik-science** [FortAwesome/Font-Awesome#12998]
Hi!

I would really love to see some academic icons:
* journal, book, paper (publication), poster, thesis
* conference
* publish
* particles, dna (already existing), satellite, etc.
* teacher
* university
* etc.

Thank you so much for considering!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
