### ISSUE TITLE
Icon Request: fa-mail-slash

### ISSUE THREAD

**Issue by demonaro** [FortAwesome/Font-Awesome#13013]
fa-mail-slash
I want set icon for "mail not send" or "failed to mail send"

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
