### ISSUE TITLE
Icon request: Military/Branches of the Military

### ISSUE THREAD

**Issue by cityriver** [FortAwesome/Font-Awesome#13014]
### What can it be used for?

When representing branches of the military with graphics! My specific 

### Example image (optional)

I think this probably means all branches: Army, Navy, Air Force, Marines, Coast Guard, (do I have them all?) and possibly one that represents them all together?

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

>  This is a single icon or matched pair (Ex: lock / unlock)


Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
