### ISSUE TITLE
Icon request: icon-cross-stitch

### ISSUE THREAD

**Issue by pixelnourish** [FortAwesome/Font-Awesome#13020]
Detonating separate sections of a crafter's website/shop, used for navigation purposes, show graphically that a pattern for download/purchase is for cross stitching

![image](https://user-images.githubusercontent.com/182633/39590114-d498e24a-4eb4-11e8-8f3e-ba44feb601a5.png)

Something like this is the best example I could find. Basically a threaded needle in the middle of making the X stitch

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
