### ISSUE TITLE
Need Anatomy and Body Systems Icons

### ISSUE THREAD

**Issue by gskaplan** [FortAwesome/Font-Awesome#13034]
For medical application, need body systems such as "Spine, Upper Extremities (shoulders, arm, etc.), Lower Extremities (knee, ankle, leg, etc.), ears, nose, throat, lungs, heart, renal system (kidneys), urinary/sexual, brain, nerves, muscles, etc. This would make an awesome category. I have only found a few icon sets that cover some of these, but nothing covers them all. Icons don't need to be detailed, just need to convey the associated body system.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
