### ISSUE TITLE
Icon times ( \f00d ) is missing in free version of FA when using in css file.

### ISSUE THREAD

**Issue by iiic** [FortAwesome/Font-Awesome#13040]
When I want to use "Font Awesome 5 Free" in CSS (icon in pseudo element `content`) icon times ( \f00d ) is missing.
FA is linked from CDN by `<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css"… ` (also v5.0.10 was the same).
Another icons are working normally, only times is in free version missing.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please note that `fa-times` in regular style is only available in FA5 Pro: https://fontawesome.com/icons/times?style=regular

In order to use solid icons in pseudoelements, please remember to set the font-weight to 900: https://jsfiddle.net/tagliala/jhusu54b/1/

Docs: https://fontawesome.com/how-to-use/web-fonts-with-css#pseudo-elements

Hope it helps

Closing here

**Comment by urigross** [comment]
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> Please note that `fa-times` in regular style is only available in FA5 Pro: https://fontawesome.com/icons/times?style=regular
> 
> In order to use solid icons in pseudoelements, please remember to set the `font-weight` to `900`: https://jsfiddle.net/tagliala/jhusu54b/1/
> 
> Docs: https://fontawesome.com/how-to-use/web-fonts-with-css#pseudo-elements
> 
> Hope it helps
> 
> Closing here

Thank you so much for solving this :)
