### ISSUE TITLE
Solid icons stopped working in pro version

### ISSUE THREAD

**Issue by lauraburgin** [FortAwesome/Font-Awesome#13068]
We were using fontawesome-pro-5.0.8. Last week, the solid icons were fine. Today I noticed none of them showed. If I don't use font-weight: 900, then they show (but they are not the solid icons). See attached screenshots.

I've now downloaded and installed fontawesome-pro-5.0.12, and that seems to have fixed the issue (I had to do this on a few sites). But we don't want to have another surprise like that in the future. What can I do to avoid this?

![screen shot 2018-05-08 at 8 49 19 am](https://user-images.githubusercontent.com/25495960/39768284-b76bb606-529d-11e8-95ca-b9791e8a6fa5.png)
![screen shot 2018-05-08 at 8 49 12 am](https://user-images.githubusercontent.com/25495960/39768285-b78977ae-529d-11e8-988a-89184274d8ca.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I can't figure out your issue but the icon showing does not belong to solid icons

It is `far fa-cog`, since `fas fa-cog` is filled-in, so there could be issues in the solid font file.

Could you please open this issue in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Also, please make sure to provide all the information required by our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

You haven't specified if you are using FA5 Pro from the CDN or on your own server and if there could have been cache or loading issues (check your browser debug console). Also, make sure that there aren't conflicting CSS rules

Closing here

**Comment by lauraburgin** [comment]
Thanks for your response, that repo doesn't seem to exist?
https://github.com/FortAwesome/Font-Awesome-Pro

Could you please send me the correct link? Thanks!
