### ISSUE TITLE
Icon request: company-plus / company-minus / company-edit

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#13081]
### What can it be used for?
Let's suppose I have an Web Application (or Desktop App) where I have to manage Companies, like add a Company, Edit a Company, etc... 
Would be nice to have this represented . I don't know if the image below is the best option, but it illustrates the idea.

### Example image (optional)
![icon](https://user-images.githubusercontent.com/32393343/39815523-99949e28-536e-11e8-8b18-92fac13f0324.jpeg)

### Icon request checklist
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by dolibarr95** [comment]
Hi !
Could be done with layer ?
https://fontawesome.com/how-to-use/svg-with-js

**Comment by giovannigaspar** [comment]
I managed to do it by using a layer... Didn't know it was possible. Pretty nice feature. Now, FontAwesome is more awesome for me than before 😛 

Thanks Again!

**Comment by dolibarr95** [comment]
you're welcome ;)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/building-user?f=classic&s=solid)
