### ISSUE TITLE
Icon request: legal-court

### ISSUE THREAD

**Issue by TexasSwede** [FortAwesome/Font-Awesome#13084]
This icon could be used for legal applications and websites, community websites, maps, etc.

My vision was initially a building with the scales of justice, or possibly with a gavel.
But here are some icons I think would be good inspiration:  

![legal-justice-and-court-icons-clip-art-vector_csp16505469](https://user-images.githubusercontent.com/3178455/39849169-a6a37bcc-53d0-11e8-834b-3e83d82c0913.jpg)

I think #6, #8, #10, #14 and #16 would work.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Also, we already have https://fontawesome.com/icons/balance-scale?style=solid and https://fontawesome.com/icons/gavel?style=solid

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by tushar0907** [comment]
Hii, can someone explain me the meaning of this icon-balance or justice icon showing in my github repo?

**Comment by tagliala** [comment]
> Hii, can someone explain me the meaning of this icon-balance or justice icon showing in my github repo?

Hi, If I've got this question correctly, it is an icon that indicates the software license

Anyway, GitHub icons are unrelated to Font Awesome
