### ISSUE TITLE
Icon request: guitar; piano; trumpet; harp; flute

### ISSUE THREAD

**Issue by silaswittrock** [FortAwesome/Font-Awesome#13086]
### What can it be used for?

Can be used in many occasions.
- For a band or orchestra
- Music shop
- Music artist
- Playlists
- Etc.

I am missing a lot of musical instruments. Besides a guitar, think of the drums, violin, trumpet, clarinet, flute, trombone, harp, horn and piano.

### Example image (optional)

Guitar
![image](https://user-images.githubusercontent.com/26166757/39867803-06464e20-5457-11e8-8008-2604cf56afb1.png)

Harp
![image](https://user-images.githubusercontent.com/26166757/39867820-197faa36-5457-11e8-99aa-634ff5a23df6.png)

Piano
![image](https://user-images.githubusercontent.com/26166757/39867845-310bea2a-5457-11e8-830e-d8c0934eb226.png)

Trumpet
![image](https://user-images.githubusercontent.com/26166757/39867863-44db0996-5457-11e8-8f4b-f58ad0cc55d0.png)

Drum
![image](https://user-images.githubusercontent.com/26166757/39867894-699a6ff6-5457-11e8-9061-28e038fc5672.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
