### ISSUE TITLE
Icon request: GDPR compliant

### ISSUE THREAD

**Issue by Alexander-Kreisler** [FortAwesome/Font-Awesome#13093]
### What can it be used for?

Add to form fields and language indicating compliance with the new EU data compliance regulation. 
### Example image (optional)
https://www.eugdpr.org

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Is there any official GDPR logo?

**Comment by Surbma** [comment]
+1 for this icon

There is a graphics guide for the European emblem, so stars should follow this guide:
http://publications.europa.eu/code/en/en-5000100.htm

Just an idea: a lock icon in stars should do it.

And the cookie icon is also very-very important: #2845

**Comment by AndreaPappi** [comment]
+1

**Comment by mariusdumitru** [comment]
+1

**Comment by biscaldis** [comment]
+1

**Comment by sgranata82** [comment]
+1

**Comment by Nephilim72** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
