### ISSUE TITLE
Icon Request:  Stairs Up:  fa-stairs-up, fa-stairs-down

### ISSUE THREAD

**Issue by kevin8479** [FortAwesome/Font-Awesome#13101]
Stairs Up-- can represent stairs, a floor in a building, can represent movement upwards, mobility upwards.  I am thinking something really simple here a few steps with an up arrow.

**Comment by dolibarr95** [comment]
hi !
https://github.com/FortAwesome/Font-Awesome/issues/5881

**Comment by Ocean97Li** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
