### ISSUE TITLE
Icon request: fft

### ISSUE THREAD

**Issue by poposhka** [FortAwesome/Font-Awesome#13125]
### What can it be used for?

Signal analysis, DSP

### Example image (optional)

something along the lines of Broadcom's logo: https://yt3.ggpht.com/a-/AJLlDp1_-cJzF98uVHEyAjTYq9j8lK2Ru6aGFhNG3Q=s900-mo-c-c0xffffffff-rj-k-no

a peak signal in the frequency spectrum with harmonic peaks to the sides

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
