### ISSUE TITLE
Icon Request: More media player control icons

### ISSUE THREAD

**Issue by Helmi** [FortAwesome/Font-Awesome#13127]
forward 5/10/30 (ex: https://d.pr/i/HZr48R)
rewind/replay 5/10/30 (ex: https://d.pr/i/NhfYoU)

turtle/bunny for speed changes

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

> turtle/bunny for speed changes

duplicate of #2453, please +1 that request


Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
