### ISSUE TITLE
Icon Request: fa-datatypes-*

### ISSUE THREAD

**Issue by mbaas2** [FortAwesome/Font-Awesome#13126]
I'd love a few icons to indicate datatype when browsing data in my app.

- fa-datatypes-bool: to indicate boolean data (true/false), 01 would be good enough (see #6812)

- fa-datatypes-int/float (fas-hash is good for "numeric"). Unsure how to distinguish int/float, perhaps stairs for int an a wave  for "float"...?

- fa-datatypes-text (currently I use font for that, not completely happy with it)

What do others think? For my purposes this would be sufficient, but perhaps "date" could be interesting, too.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please open individual requests and avoid duplicate (#6812 is a duplicate) 

Please also refer to https://github.com/FortAwesome/Font-Awesome/issues/4867#issuecomment-61240928

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
