### ISSUE TITLE
Icon request: icon-obsolete and icon-draft

### ISSUE THREAD

**Issue by davidthegray** [FortAwesome/Font-Awesome#13132]
I often work on a document library manager and I would need icons to represent documents in **preliminary/draft/provisional** state, and documents that are **superseded/obsolete**. It would be great if the icons were related to each other, and general, not only representing documents (they could apply to software versioning for instance). I don't have much of an idea of how those concepts could be represented graphically. I think that they would be useful in many situations.

Thanks.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
