### ISSUE TITLE
Fa still word in some icons

### ISSUE THREAD

**Issue by FlowUpMedia** [FortAwesome/Font-Awesome#13150]
I dont know if this is an issue or not, but in the docs says:

> The fa prefix has been deprecated in version 5. The new default is the fas solid style and the fab style for brands.

But I came across with some icons that still works with "fa", for example "fa fa-link", "fa fa-search", "fa fa-angle-left", i don't know if there are more.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> But I came across with some icons that still works with "fa", for example "fa fa-link", "fa fa-search", "fa fa-angle-left", i don't know if there are more.

They are supposed to work, it is just an alias for `fas`.

Deprecated means that it will be removed in Font Awesome 6.

In other words, if you have an existing project with `fa` it's ok, but if you are starting a new project, we do not advise to use `fa` because it will be removed

Hope it helps

Closing here
