### ISSUE TITLE
Icon category request: flourishes, separators

### ISSUE THREAD

**Issue by downhillmedia** [FortAwesome/Font-Awesome#13162]
At Brian's suggestion:

### What can it be used for?

Often used as section separators in a page layout or as a visual cue at the end of an article. Graphic design elements.

### Example image (optional)

![flourish](https://user-images.githubusercontent.com/9484212/40188241-80bc017a-59c7-11e8-9d3e-c0fdd3367398.png)

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`) No, but Brian said to do this here.
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
