### ISSUE TITLE
Unexpected behaviour with fa-google-* brand icons

### ISSUE THREAD

**Issue by BrutalSwede** [FortAwesome/Font-Awesome#13165]
I recently migrated to the latest version of FA (5.0.13) and this issue emerged.

I am trying to use the brand icons for buttons to use when selecting which identity provider to use. With the `fab fa-facebook-square` icon I get the behaviour I expect, and that worked in 4.7.0, which is that the button turns in to the icon.

`<button type="submit" class="fab fa-facebook-square" name="provider" ...`
Works fine.

`<button type="submit" class="fab fa-google-plus-square" name="provider" ...`
Doesn't work

I've tried using other Google icons and none of the ones I tried work.

[Here is a picture of the issue](https://i.imgur.com/A6tEqKt.png)

Thanks in advance :)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> I recently migrated to the latest version of FA (5.0.13) and this issue emerged.

Which version? SVG or CSS? Given the usage, CSS I guess.

> `<button type="submit" class="fab fa-facebook-square" name="provider" ...`

Just want to point out that we recommend a different usage (separate `<span>` or `<i>` tag just for the icon). Also, this will not work out of the box with the SVG implementation unless [nest `<svg>` tags instead of replacing](https://fontawesome.com/how-to-use/svg-with-js#auto-replace-svg-nest) option is enabled

> Here is a picture of the issue

Thanks, but if you provide a reproducible test case it would be easier for us to help you

BTW, I'm unable to replicate, so meanwhile I'm closing here

https://jsfiddle.net/tagliala/6yrybgho/3/

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

Please also check our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up
