### ISSUE TITLE
Icon request: fa-physical-therapy

### ISSUE THREAD

**Issue by MrRod** [FortAwesome/Font-Awesome#13171]
### What can it be used for?

Health apps or websites geared towards alternative medicine. For example, one case of use would be a menu to request chiropractors, massage therapists, etc.

### Example image (optional)

![image](https://user-images.githubusercontent.com/969951/40263841-610ffd0c-5ae6-11e8-9b03-f7eccbfceea9.png)

![image](https://user-images.githubusercontent.com/969951/40263844-6507365a-5ae6-11e8-926c-a655f31b786b.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by ag288** [comment]
Any updates on this?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
