### ISSUE TITLE
Icon Request: fa-user-in-store (vendor)

### ISSUE THREAD

**Issue by arjuntech25** [FortAwesome/Font-Awesome#13185]
used for vendors / suppliers in inventory systems

![707803_store_512x512](https://user-images.githubusercontent.com/32214822/40359569-db8ad30c-5de0-11e8-873a-22816ab73c38.png)
![images](https://user-images.githubusercontent.com/32214822/40359570-dbc38d6e-5de0-11e8-9d66-069d9f4bb98e.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Does https://fontawesome.com/icons/store?style=solid fit your use case?

**Comment by jbnv** [comment]
I'm looking for a pair of icons to represent clients and vendors. Basically, they are both organizations of people; the difference is that a client is someone who pays you for goods/services, and a vendor is someone you pay for goods/services. (And to make it more complicated, we also have manufacturers, who are organizations that make the stuff we get from vendors.) I'm not sure that the store icon actually represents that concept.

**Comment by MarcusAfolabi** [comment]
This solve it all `<i class="fas fa-store"></i>`

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
