### ISSUE TITLE
Font Awesome JS CDN is injecting Google Analytics

### ISSUE THREAD

**Issue by chthomos** [FortAwesome/Font-Awesome#13180]
After checking the cookies used in a website of mine, I noticed that fontawesome.com adds the following two cookies: _ga and _gid . Obviously these are google analtyics cookies.

I am currently working on making our website GDPR compliant. This requires that the user gives consent about usage of tracking cookies. on the visited website. How can Google Analytics be disabled from the JS CDN in such case?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I need clarifications on this, but I'm pretty sure that the CDN doesn't set cookie by itself.

Analytics cookies are set when you visit `fontawesome.com` because the domain is set as `.fontawesome.com`

Please clear your cookies, reload the page which uses the CDN and check if you can see `_ga` and `_gid`

You can use this page: https://tagliala.github.io/fa13051, source:

```html

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <script defer src="https://use.fontawesome.com/releases/v5.0.12/js/all.js" integrity="sha384-Voup2lBiiyZYkRto2XWqbzxHXwzcm4A5RfdfG6466bu5LqjwwrjXCMBQBLMWh7qR" crossorigin="anonymous"></script>

    <title>Hello, world!</title>
  </head>
  <body>
    <span class="fab fa-6x fa-playstation"></span>
  </body>
</html>
```


Then, after visiting `fontawesome.com`, check again

I'm not an expert of setting up CDNs, so I'm asking @robmadole if there is a way to exclude use.fontawesome.com from setting cookies

**Comment by chthomos** [comment]
Wow, thank you for the detailed answer. You are absolutely right here. The google tracking script is not injected. 

If rob can help that would be a great deal. Otherwise, do you plan to set up a cookie consent controller in font-awesome.com so that users can opt-in / opt-out as required by GDPR 

Thanks again!

**Comment by robmadole** [comment]
We'll post updates to our privacy policy on fontawesome.com which should contain all the information you need @chthomos. We don't have this updated yet.

**Comment by chthomos** [comment]
Thanks a lot @robmadole !

**Comment by JuiceyDuecy** [comment]
Hi guys, any update on this?

**Comment by robmadole** [comment]
Our privacy policy has been updated. @JuiceyDuecy are you looking for something else?
