### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by Geimsiello** [FortAwesome/Font-Awesome#13181]
### What can it be used for?

For weather ui/website etc.

### Example image (optional)

https://iconstore.co/wp-content/uploads/2015/12/weather-featured.png

### Icon request checklist

Entire set for weather icons

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please ref to #155 if you want some more weather icons

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
