### ISSUE TITLE
Icon request: Web Developer Technologies

### ISSUE THREAD

**Issue by Nojil** [FortAwesome/Font-Awesome#13200]
It would be really nice to have a collection of web development language icons. YOu guys already ahve a few but seem to missing a lot of core languages such as: TypeScript, SASS, LESS, Mocha, Express, MySQL, MongoDB,  to list a few. I have created separate requests for these icons.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
