### ISSUE TITLE
Icon Request: fa-

### ISSUE THREAD

**Issue by srikanthtarun** [FortAwesome/Font-Awesome#13227]
![current-trip](https://user-images.githubusercontent.com/39690582/40601591-6d006db0-6273-11e8-8632-292af77bf5ec.png)
Requesting icon in UTF-16BE

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Is this a duplicate of #5138?

**Comment by srikanthtarun** [comment]
I just want the utf code for the image i have uploaded for.
It will be very appreciated if you provide me the code.

Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
