### ISSUE TITLE
Icon pack request: Real estate

### ISSUE THREAD

**Issue by graph-kgrondin** [FortAwesome/Font-Awesome#13229]
Hi!

I don't know if we can request a icon pack, but i'm working on real estate and do a lot of website about it.

I always need icons for it but i have to search on Google some icons and them make my owns on illustrator to have similar design between icons i found... It will save me times to have this package in my Font Awesome Pro!

Right now, here some icons that comes in my mind for this package : plans, area, balcony area, residential project, commercial project, amenities (such as pool, hotel services, personnal garden, rooftop terrace, etc.)

They can be a lot of them, that's why i came with a pack request! :-) 

I hope you will take time to consider my request! Good job for all you have already done!

**Comment by machiaveli88** [comment]
+1

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

If you are a Pro Backer, you can request sets in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
