### ISSUE TITLE
Cannot show some icons via webfonts

### ISSUE THREAD

**Issue by tylerlong** [FortAwesome/Font-Awesome#13239]
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Page Title</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css">
</head>
<body>
  <i class="fa fa-car"></i>
  <br/>
  <i class="fa fa-twitter"></i>
  <br/>
  <i class="fa fa-leaf"></i>
</body>
</html>
```

![image](https://user-images.githubusercontent.com/733544/40701525-c305b58c-6410-11e8-8d2a-af63cb9dd956.png)

You can see that `twitter` icon is not shown.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please note that the class name for brand icons is `fab` instead of `fa`. Also, if you are starting a new project, we recommend to use `fas` instead of `fa` because the `fa` prefix is deprecated and will be removed in FA 6

Hope it helps, closing here

Docs: https://fontawesome.com/how-to-use/web-fonts-with-css#basic-use
