### ISSUE TITLE
Icon Request: Boat, Ship

### ISSUE THREAD

**Issue by michaelmoulsdale** [FortAwesome/Font-Awesome#1323]
Boat and Ship similar to the ones on Icomoon would be great.

**Comment by AnanthaVishnu** [comment]
+1 for boat

**Comment by FickleLife** [comment]
+1 for boat

**Comment by agaio** [comment]
+1 for ferry-ish thing

**Comment by henleywc** [comment]
+1

**Comment by davegandy** [comment]
Ship added to 4.3.0-wip branch. Closing.

**Comment by sdupd-gbatuyong** [comment]
Thank you, folks.

—Port of San Diego (we like ships!)

**Comment by brentdeacon** [comment]
+1 for a small boat

**Comment by sarahtevendale** [comment]
Icon request: fa-sailboat

I'm building a website for a holiday rental cottage and would really appreciate a sailboat icon, such as the one below, so that I can use it to illustrate the activities available in the area of the rental cottage.

The bicycle, hotel/bed, food and paws icons are super and ideal for some of the facilities, but a sailboat, rather than the large ship that already exists, would be a great help, thank you.

(Sorry if this is in the wrong place, it's my first visit here)

Thanks, Sarah

![boat-159368_640](https://cloud.githubusercontent.com/assets/15999209/11367458/a2d5f2f6-92ab-11e5-84e0-cca39d0b8bc5.png)

**Comment by tagliala** [comment]
@sarahtevendale please +1 #5079

**Comment by xmuskrat** [comment]
+1 ship, side view.
