### ISSUE TITLE
Icon request: fa-calendar-sync

### ISSUE THREAD

**Issue by agagnon** [FortAwesome/Font-Awesome#13234]
I'm building a calendar application and I would like to have icons for recurring events.

![calendar-recurring](https://user-images.githubusercontent.com/1794026/40678676-2d85074a-634f-11e8-96c8-83f707eec440.png) ![recurring](https://user-images.githubusercontent.com/1794026/40678677-2dacda0e-634f-11e8-9fd6-3b5e56767159.png)

**Comment by tagliala** [comment]
recurring is already available:
https://fontawesome.com/icons/sync-alt?style=solid
https://fontawesome.com/icons/sync?style=solid

Please note that you can get calendar-sync via svg transformations:
https://jsfiddle.net/8oqL3b5p/203/

**Comment by agagnon** [comment]
Oops. Sorry about that. I tried a lot of keyword and never found it. I never thought of it as "sync". I scrolled all the icons, but I guess I overlooked it.

Thanks.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
