### ISSUE TITLE
Icon request: fa-broadcast

### ISSUE THREAD

**Issue by joeellis** [FortAwesome/Font-Awesome#13242]
### What can it be used for?

This icon would be a single icon, similar to the already existing `fa-broadcast-tower` except that it would not include the tower.  Reason is because currently, `fa-broadcast-tower` comes off looking more like a glitchy / mis-encoded "A" at smaller sizes than as a symbol representing the idea of "broadcast."

### Example image (optional)
![signal](https://user-images.githubusercontent.com/49288/40738238-a33e14e0-6408-11e8-8f24-f103c06db0ab.png)

### Icon request checklist
- [x] This is a single icon or matched pair (Ex: lock / unlock)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: Icon request: magical-unicorn)
- [x] I have searched for existing issues and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> fa-broadcast-tower comes off looking more like a glitchy / mis-encoded "A" at smaller sizes

I can't agree more :)

IIRC, this is a duplicate, but I'm not able to find the oiriginal request so I'm leaving this open

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/signal-stream?f=classic&s=solid)
