### ISSUE TITLE
Memory game using fontawesome icons causes glitch that chooses wrong card.

### ISSUE THREAD

**Issue by Sizu24** [FortAwesome/Font-Awesome#13282]
I am working on a memory game using font awesome icons for each card. When I use the script for font awesome, icons show up correctly on each card, but clicks the wrong card. Game was working fine a week ago, and now all of a sudden this is happening, without any changes to the code.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a reduced test case showing the issue?

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by Sizu24** [comment]
HTML code:
https://codeshare.io/29VzgX

CSS code:
https://codeshare.io/5Xmrgl

Javascript code:
https://codeshare.io/5v4eZL

Click on the cards, and most of the time the wrong card will flip. Game is not complete, but this part is preventing me from going any further. When I take off the fontawesome CDN, the correct cards will flip. I've tried several versions of the CDN starting with the latest. Also have tried different browsers, and on different computers.

Browsers:
Safari  Version 11.1 (13605.1.33.1.2)
and
Chrome Version 66.0.3359.181 (Official Build) (64-bit)

SVG and JS

**Comment by tagliala** [comment]
@Sizu24 thanks

Could you please setup a working demo of the issue?

You should be able to use codepen.io or http://jsfiddle.net/

Also pay attention to:
- insert just the minimum amount of code to replicate
- remove the unused version of font awesome from head tag
- update font awesome to the latest available version, 5.0.13

**Comment by Sizu24** [comment]
https://codepen.io/anon/pen/bKwwNg

Let me know if that works

**Comment by Sizu24** [comment]
Feel like this issue happens after I use a setTimout() function. I re-did the game, from scratch and started seeing this issue again after a few minutes of using the setTimout function to remove a class.

**Comment by tagliala** [comment]
Thanks for the codepen.

You are using `font-size: 0` to hide elements and  `font-size: 35px` to show them: there are a lot of other options of doing that

Please take a look at this fiddle: https://codepen.io/anon/pen/QxdKEE

I've:
- Placed the configuration option before the loading of the script: [order matters](https://fontawesome.com/how-to-use/font-awesome-api#configuration)
- Set the font size to 35 in `.card`
- Added a couple of rules to show the `<i>` tag only if the `.flipped` class is also set on a card

In this way, I'm not getting odd results. Since events are attached to the `<li>` tag, you can also avoid the nested elements: https://codepen.io/anon/pen/pKRERe

@robmadole is this something we can do about this? There appears to be issues when the font size is 0

**Comment by Sizu24** [comment]
This fixed the issue! Finally someone figured this out. THANK YOU for helping, and for the tips!!
