### ISSUE TITLE
Icon request: box-question

### ISSUE THREAD

**Issue by di-soric** [FortAwesome/Font-Awesome#13294]
## **What can it be used for?**
This icon would be the perfect counterpart of the box-check icon to show two availabilities: In stock / on request

## **Example image**

![box-question](https://user-images.githubusercontent.com/40058033/41150741-09ea0570-6b0f-11e8-8f94-4d2182386b47.png)

[box-question.pdf](https://github.com/FortAwesome/Font-Awesome/files/2083815/box-question.pdf)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
