### ISSUE TITLE
Icon Request: fa-pbuh

### ISSUE THREAD

**Issue by umarmughal** [FortAwesome/Font-Awesome#13299]
Please add icon for "Peach Be Upon Him" image below, i can provide icon, ai, png all the files, also available on internet, Thank You!

![pbuh](https://user-images.githubusercontent.com/1124947/41171725-9eb02e70-6b62-11e8-8b9f-3605257de1cb.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
