### ISSUE TITLE
Fonts not translating

### ISSUE THREAD

**Issue by kristinirvine26** [FortAwesome/Font-Awesome#13300]
The facebook font doesn't change to the icon even when the font is changed to font awesome- it shows up as a box. Some other fonts such as the globe are in a different style from the one shown on the site.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)
