### ISSUE TITLE
Icon Request:item information

### ISSUE THREAD

**Issue by AntiaOnly** [FortAwesome/Font-Awesome#13308]
Default style  And Transfer style 
![pic01](https://user-images.githubusercontent.com/34832091/41282758-773f1862-6e67-11e8-880f-1e7c322a2b8c.png)
![pic02](https://user-images.githubusercontent.com/34832091/41282761-781a6c1e-6e67-11e8-9733-6932891ae6cb.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide more information about this icon?

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by tagliala** [comment]
> 1.Side navigation of a user project requires support for polychromatic icons to meet project requirements。

Please note that icons are limited to a single color

Eventually the SVG Framework will support duotone icons, but the duotone should be a presentational feature (single color)

> 3.This is a a single icon,It's just a different display state.(Default And Transfer )

If this is a single icon, please provide just one example in single color

Also, I need more clarification about this request 

1. Is this a brand?
2. What does this icon represent?
3. Is there a use case for a generic Font Awesome user for such an icon?

**Comment by tagliala** [comment]
@njdmznkj

CSS: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
SVG: https://github.com/FortAwesome/Font-Awesome/issues/13240#issuecomment-394082423

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
