### ISSUE TITLE
Icon request: icon-between-range, icon-outside-range

### ISSUE THREAD

**Issue by webwakko** [FortAwesome/Font-Awesome#13307]
Would be nice to have an icon that can be placed between 2 input fields for dates, numbers, etc... to show a "between" search...
could be something like  > / < (where left input is bigger then and right is smaller than).
It could also be used reversed... in case needed (< / >)  but I assume nobody searches smaller than before bigger than ;)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide single color example of what you are looking for? Search on google images

**Comment by webwakko** [comment]
this is a good example for outside range... and https://icons8.com/icon/11239/source-code .. can't find one with reversed arrows..

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
