### ISSUE TITLE
Icon Request: fa-yoga

### ISSUE THREAD

**Issue by rawthriver** [FortAwesome/Font-Awesome#13321]
As yoga become popular in this world, it would be cool to make some yoga icons:
1) one (or 2-3) yoga pose: e.g. lotus pose (essential), warrior pose, tree pose (fa-yoga-lotus, fa-yoga-warrior, fa-yoga-tree)
2) fa-yoga-mat (rolled yoga mat)
3) fa-yoga-om (om sign)
Thanks in advance. Your icons really awesome;)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Single icon to represent yoga: #6032 

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
