### ISSUE TITLE
Icon Request: user-clipboard

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#13325]
Std user icon with clipboard superscript.

What I wanted to use it for:

copy username to clipboard.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.]()
