### ISSUE TITLE
sticker-mule works with <i class> but does not work in css f3f7

### ISSUE THREAD

**Issue by thatsinsurance** [FortAwesome/Font-Awesome#13333]
I am able to use this icon with the following 
<i class="fab fa-sticker-mule"></i>

however the code\f3f7 in this css

.fancy-bullet-points li::before, .fancy-bullet-points.red li::before {
	font-family: FontAwesome;
	content: "\f3f7";
	font-size: 36px;
	margin-right: 12px;
}

example on this page  https://www.pinkequine.com/product/diamond-wave-crystal-bridle/
if you use Inspect Element and change the tick to the mule icon you just get a square box with the f3f7 text but no icon.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

There are a couple of issues:
1. Your website is loading both SVG and Webfont versions of Font Awesome 5, please choose for one of them;
2. A plugin is loading FA 4.2.0, and that's why `font-family: FontAwesome;` works because it should not work.

The FA JavaScript code is loaded by `edc048f0-c6f6-4c82-bce9-24046693721b.js`. The css is loaded via CDN in the head tag of your HTML. Since using pseudo-elements with SVG [is not recommended](https://fontawesome.com/how-to-use/svg-with-js#pseudo-elements) and requires extra configuration, please consider to avoid pseudo-elements or use the Webfont version

The plugin loading FA 4.2 is `ultimate-member`. Please remove references to FA 4.2

Docs:
- https://fontawesome.com/how-to-use/web-fonts-with-css#pseudo-elements (CSS)
- https://fontawesome.com/how-to-use/svg-with-js#pseudo-elements (SVG)

Hope it helps, closing here
