### ISSUE TITLE
Icon request: bill pay

### ISSUE THREAD

**Issue by Nojil** [FortAwesome/Font-Awesome#13343]
Any way you can add an icon like this:
![capture](https://user-images.githubusercontent.com/11978772/41618942-c74e8f36-73c1-11e8-9b76-0d65e5f6aaba.PNG)

I work for a bank and we would love to see a lot more "banking" icons.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
