### ISSUE TITLE
Icon Request: Deposit/Widthdraw

### ISSUE THREAD

**Issue by Nojil** [FortAwesome/Font-Awesome#13342]
Any way yall can make this deposit/withdraw icon
![capture](https://user-images.githubusercontent.com/11978772/41618904-ad854220-73c1-11e8-8302-66e7803c1295.PNG)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.]()

**Comment by tagliala** [comment]
@sensibleworld I guess this is one of https://fontawesome.com/search?q=deposit&o=r&s=solid

**Comment by sensibleworld** [comment]
Also this: https://fontawesome.com/icons/arrow-up-arrow-down?f=classic&s=solid (based on the image in the original issue)
