### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by Rosa-Leeke** [FortAwesome/Font-Awesome#13341]
Are there any icons aimed at the catering/restaurant trade?
I am looking for the following; meat, fish, soups, starters, shellfish, desserts etc.
Thanks in advance. 
Phil

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

There are several requests in the [food category](https://github.com/FortAwesome/Font-Awesome/labels/food%20%28category%29)

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
