### ISSUE TITLE
Icon Request: Germ and Phage

### ISSUE THREAD

**Issue by yonist** [FortAwesome/Font-Awesome#13349]
Examples:

Germ:
https://experiencelife.com/article/your-germ-cloud/

Phage 
http://www.mdpi.com/viruses/viruses-09-00050/article_deploy/html/images/viruses-09-00050-g001.png

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
