### ISSUE TITLE
Angle icons FA 4.7 do correspond with FA 5 regular ones

### ISSUE THREAD

**Issue by jevanlingen** [FortAwesome/Font-Awesome#13352]
After an app's recent update, I noticed the angle icons of Font Awesome 4 (e.g. [fa-angle-right](https://fontawesome.com/v4.7.0/icon/angle-right/)) do look a lot more like the [regular version ](https://fontawesome.com/icons/angle-right?style=regular) of the angle icons provided by Font Awesome 5. As the regular icons are only available for PRO, upgrading forces use of the solid icons.

Is this by design, of should this be considered a bug?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your question seems legit

**Comment by robmadole** [comment]
@jevanlingen this is by design. We spent a lot of time in version 5 making the icons visually similar and the same weight. The version 4 icons were _not_ consistent. Even though the old v4 `angle-right` may be visually closer to the Regular style we never had a goal of making the upgrade from 4 to 5 visually consistent. Our goal was to make 5 consistent with itself ;)
