### ISSUE TITLE
Users should be able to use seats after registering entering the serial number

### ISSUE THREAD

**Issue by Snorkeler** [FortAwesome/Font-Awesome#13359]
As far as I know, the only way to use the library is by sending it locally to the users, which prevents from using the search box online.

Users who want to use the whole library should be able to register with their own email account and introduce the serial number afterwards, without the restraints of having to use it locally.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request?

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by Snorkeler** [comment]
What does it mean that I have five seats per licence?
Thank you.

**Comment by tagliala** [comment]
Sorry, got it. 

Since that's a license question about font Awesome Pro, could you please ask this question in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

If you don't get an answer from other people in the team, please ping me

Hope it helps

Closing heere
