### ISSUE TITLE
Request icon: Network routing

### ISSUE THREAD

**Issue by dtouzeau** [FortAwesome/Font-Awesome#13372]
Example:
![management-console](https://user-images.githubusercontent.com/280586/41742015-0c6258dc-759d-11e8-8da1-754d41b73142.png)

**Comment by dtouzeau** [comment]
Can illustrate, Centralize, global management, routing, sharing, team leader..;

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
