### ISSUE TITLE
Not Found: @fortawesome/pro-light-svg-icons@latest

### ISSUE THREAD

**Issue by kemalcany** [FortAwesome/Font-Awesome#13414]
Hi

After the 5.1.0 upgrade the new packages are not fount in npm registry. Is this a temporary bug?

Thanks

```
kemals-MBP:sayardocs Kemal$ npm install --save @fortawesome/pro-light-svg-icons
npm ERR! code E404
npm ERR! 404 Not Found: @fortawesome/pro-light-svg-icons@latest
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

There are issues on the pro npm repository with 5.1.0 ref #13386

Could you please open this issue in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

**Comment by andretagweb** [comment]
I got the same problem, and you link redirect for 404 page

**Comment by tagliala** [comment]
@andretagweb I'm pretty confident this issue has been solved.

Could you please open a new issue by filling out our  [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)?

Note: if the issue is about Font Awesome Pro, the proper repository is https://github.com/FortAwesome/Font-Awesome-Pro

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account#linked-accounts

**Comment by dishui** [comment]
I have the same issue. since my github account is personal, I can not link my account with the pro, since a few people has this issue, why does every one has to file the same bug?

**Comment by mankarsandesh** [comment]
@tagliala  what you share link is not found. can you check once?

**Comment by tagliala** [comment]
Hi @mankarsandesh, things have changed in those years. Feel free to open issues related to the pro packages in this repo

**Comment by werpeladriano** [comment]
You need to create a file named `.npmrc` in your root folder with you authToken to install the lib in your project, like this:

```
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken={yourToken}
```
