### ISSUE TITLE
Icon request: fa-marker-inside-area (geofence)

### ISSUE THREAD

**Issue by daanvanrobays** [FortAwesome/Font-Awesome#13423]
### What can it be used for?

I would use it in an application with google maps to describe a marker point that is located inside a certain area / [geo-fence](https://en.wikipedia.org/wiki/Geo-fence)

This icon could have a filled version and a blank one.

An example image below:
[Example Image](https://strategus.com/wp-content/uploads/2016/05/factor-icon-geofencing1-300x300.png)

[Example Image](http://icons.iconarchive.com/icons/icons8/ios7/256/Maps-Geo-Fence-icon.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
