### ISSUE TITLE
Icon request: comp-cluster

### ISSUE THREAD

**Issue by DarkMajestic** [FortAwesome/Font-Awesome#1342]
Hello font awesome,
My team and i love your library's awesomeness!
Please could you create an computer cluster icon

We are building an app that monitors application servers and some of these are clustered were looking for an icon to easily show this.

i was thinking of something like one of the following...
![comp-cluster4](https://f.cloud.github.com/assets/4728803/674894/238b421c-d8e5-11e2-8671-464147aeb752.png)

![comp-cluster3](https://f.cloud.github.com/assets/4728803/674903/42daf964-d8e5-11e2-8310-78526d613763.png)

![comp-cluster2](https://f.cloud.github.com/assets/4728803/674905/48519696-d8e5-11e2-9c7d-064ab462aeb1.png)

![comp-cluster](https://f.cloud.github.com/assets/4728803/674908/4ddc3d1e-d8e5-11e2-91c6-301a7de7fdfb.png)

Thanks,

James

**Comment by jourdain** [comment]
+1

![bdb43c32-da53-11e5-8284-b9e4154be04e](https://cloud.githubusercontent.com/assets/294518/13290357/87041cde-dad0-11e5-8cd7-a91bca8b5d54.png)

We also have an SVG version of it, if you prefer.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
