### ISSUE TITLE
Icon request: arrows-h and arrows-v corresponding unidirectional arrow

### ISSUE THREAD

**Issue by nick-iCars** [FortAwesome/Font-Awesome#13440]
### What can it be used for?
when a matching single direction arrow is required to be used alongside or in connection with the two or four way arrow icons

I'm using the bi-directional arrow icon but also need to use the uni-directional arrow in it's place in certain contexts, but the icons don't match.
### Example image (optional)

![image](https://user-images.githubusercontent.com/23464282/41990967-cbf62944-79f8-11e8-91ad-364092aafda3.png)

### Icon request checklist

- [x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x ] I have included at least one example image if it could be helpful (optional)
- [ x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.]()
