### ISSUE TITLE
Icons requests: icon-realestate

### ISSUE THREAD

**Issue by graph-kgrondin** [FortAwesome/Font-Awesome#13487]
### What can it be used for?

I'm looking to have some icons that i can put on website talking about real estate. It will be use to present informations about home, appartments, condos, commercial area, etc.

### Icons requests checklist

- [ ] Plans (to say that a section contains plans for floors or units)
- [ ] Area (sq.ft, pi², etc.) or more representative like diffence between balcony, interior or garage.
- [ ] Building icon that represent the type of building (residential, commercial, etc.)
- [ ] Amenities (such as pool, hotel services, personnal garden, rooftop terrace, etc.)
- [ ] Interiors informations (put bedroom, bathroom and other things that fit inside of the pack and add others such as an icon for deskroom, garage, etc.)

**Comment by richardbmx** [comment]
@graph-kgrondin  Hello my name is Richard Caseres I am a graphic designer and I like to make contributions to the different open source projects, I see that you want some icons ... I can gladly do it for you if you agree, however I need some specific additional details about what you want do ... regards ...

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by tagliala** [comment]
If you are a Font Awesome Pro customer, you could request a set of icons in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
