### ISSUE TITLE
Icon request: icon-express-cog

### ISSUE THREAD

**Issue by gucotta** [FortAwesome/Font-Awesome#13505]
### What can it be used for?

It can be used to express optimized ways of setting things up.

### Example image (optional)

![express_setup](https://user-images.githubusercontent.com/33966755/42427313-41141ed4-8304-11e8-9299-d163ce4bd0d1.png)

or the svg variation 😬 

[express_setup.zip](https://github.com/FortAwesome/Font-Awesome/files/2174413/express_setup.zip)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by gucotta** [comment]
I kind of made a mix of the shipping-fast and cog icons.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
