### ISSUE TITLE
Icons request: IT Technologies.

### ISSUE THREAD

**Issue by adsingh14** [FortAwesome/Font-Awesome#13500]
We need some IT technologies icon in v4

Useful for:
- Portfolios

Some of them I remember right now:
- Adobe softwares (Photoshop, Illustrator, After Effects)
- Javascript, JQuery, Bootstrap

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
