### ISSUE TITLE
Premier League Football Brands - Man Utd, Arsenal

### ISSUE THREAD

**Issue by mobillica** [FortAwesome/Font-Awesome#13541]
Can we get a few Premier League football brands for Font Awesome?

Liverpool
Arsenal 
Manchester Utd

?
![arsenal-fc-logo-13320315bb-seeklogo com](https://user-images.githubusercontent.com/41201086/42700135-c009e85e-86ba-11e8-95d4-b23fbd0342c8.png)
![manchester-united-logo-black-and-white](https://user-images.githubusercontent.com/41201086/42700187-e5728b8c-86ba-11e8-9b75-9d08b173830e.png)
![2ad493cca6ceaa181a70ac72e1b1f349](https://user-images.githubusercontent.com/41201086/42700188-e5916ae8-86ba-11e8-93c5-34274e49e74b.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

If you are a Pro backer, you can open requests for icon sets in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
