### ISSUE TITLE
网页图标第三行第二列文字显示错位

### ISSUE THREAD

**Issue by zhejiang10086** [FortAwesome/Font-Awesome#13551]
网页图标第三行第二列文字显示错位

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

Please also write in English
