### ISSUE TITLE
Icon request: traffic-jam

### ISSUE THREAD

**Issue by MarcoSpoenemann** [FortAwesome/Font-Awesome#13561]
### What can it be used for?

Web-Applications, indicating traffic jam.

### Example image 

https://de.wikipedia.org/wiki/Datei:Zeichen_124_-_Stau,_StVO_1992.svg

I think three cars are enough to indicate a traffic jam.

**Comment by msneujink** [comment]
Would be nice to have an traffic-jam icon!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/cars?f=classic&s=solid)
