### ISSUE TITLE
Icon request: fa-stem-dash

### ISSUE THREAD

**Issue by abhimanyusingh** [FortAwesome/Font-Awesome#13589]
I need an icon of stem-dash like this one Thanks!
![stem-dash](https://user-images.githubusercontent.com/3057450/43031090-d453669c-8c68-11e8-9e80-c805922875ff.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request? What a stem-dash is? What does your example represent? What is  the use case?

**Comment by abhimanyusingh** [comment]
This icon is mostly to represent parent and child relation. here is the example
![screen shot 2018-07-26 at 11 19 55 am](https://user-images.githubusercontent.com/3057450/43271807-83fe5438-90c6-11e8-8496-7b5b898aea17.png)

**Comment by abhimanyusingh** [comment]
@tagliala do you need more information?

**Comment by abhimanyusingh** [comment]
@tagliala i didn't hear any thing from you?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
