### ISSUE TITLE
Request: liter/litre symbol

### ISSUE THREAD

**Issue by lonix1** [FortAwesome/Font-Awesome#13585]
We can use HTML `&#8467;` (<span>&#8467;</span>) but it's narrow and ugly.
Need a pretty symbol for this.
Should be named "litre" as that is the correct SI unit.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
