### ISSUE TITLE
Icon request: fa-circle-notch-dashed

### ISSUE THREAD

**Issue by abhimanyusingh** [FortAwesome/Font-Awesome#13593]
I need an icon like this one (just the outer circle)

![quick-filter](https://user-images.githubusercontent.com/3057450/43031145-aa443cc2-8c69-11e8-9f60-e479af2f51d4.png)

Thanks!

**Comment by tagliala** [comment]
In order to label this request, its title should reflect what the icon actually represent.

Here it is a reference to our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

The icon represents `fa-filter` inside a somewhat-dashed circle, let's say a `circle-notch-dashed`

So, the proper name for this request should be `fa-filter-circle-notch-dashed`, and I would be fine with that title.

Anyway, for better chances of being included, I personally think that we should split this icon into two separate requests.

The outer icon does not strictly represent the concept of "in progress": it is a cicle with dashed lines, and could be used also for a spinner.

The inner icon, fa-filter, is already here

Then, you can combine the outer circle with other icons using the stacking feature.

Eg:
- static: http://jsfiddle.net/tagliala/9tercwpy/19/
- animated: http://jsfiddle.net/tagliala/9tercwpy/22/

**Comment by abhimanyusingh** [comment]
@tagliala you are right, if we can have circle with dashed lines, we can combine the outer circle with other icons using the stacked features. hence I editing the name of this icon-request to "fa-circle-notch-dashed".

thanks

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
