### ISSUE TITLE
Icon request: fa-windows (two fa-window)

### ISSUE THREAD

**Issue by abhimanyusingh** [FortAwesome/Font-Awesome#13596]
I need an icon of mannequin like this one

![empty-browser](https://user-images.githubusercontent.com/3057450/43031156-f2f61210-8c69-11e8-97e6-4fb14d298078.png)

Thanks!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/window-restore?f=classic&s=solid)
