### ISSUE TITLE
Icon Request: fa-car-valet

### ISSUE THREAD

**Issue by mseminatore** [FortAwesome/Font-Awesome#13605]
An icon representing valet parking of car.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a single color example suitable for 16px icon size?

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by mseminatore** [comment]
Sure.  Here is a representative example of what I was thinking.  Obviously this one cannot be copied as is, but it provides the basic idea.

![image](https://user-images.githubusercontent.com/16830648/43162447-e072e298-8f3f-11e8-88ed-cb6e66245c95.png)

**Comment by mseminatore** [comment]
@tagliala Let me know if this is not the feedback you need.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
