### ISSUE TITLE
Icon Request: icon-balloon-dog

### ISSUE THREAD

**Issue by Magical1** [FortAwesome/Font-Awesome#13607]
It would be great for the all the children's entertainers out there if we could get a balloon dog icon based on the iconic single balloon dog, for use on our websites please?
![balloon dog with fluffy tail](https://user-images.githubusercontent.com/2847821/43093289-92ea4464-8ea7-11e8-9269-f19c71e9a3ab.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
