### ISSUE TITLE
How can i upgrade font awesome from v4.4.0 to 5.1.1 in opencart

### ISSUE THREAD

**Issue by 7oda187** [FortAwesome/Font-Awesome#13612]
Hello team,

Kindly can anyone please assist and let me know how can i upgrade font awesome from v4.4.0 to 5.1.1 i'm using OC 2.3.0.2

Your help will be much appreciated.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Since this strictly depend on how you use Font Awesome, you should ask opencart developers at https://github.com/opencart/opencart/

I've noticed that they are using pseudoelements, so I will not suggest you to try with v4 shims

By the way, there are upgrading to Font Awesome 5 (5.0.9) in their 3.1 version

Hope it helps

Closing here

Ref:
- https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#shims
- https://github.com/opencart/opencart/blob/3.0.2.0/upload/catalog/view/theme/default/stylesheet/stylesheet.css#L515-L521
