### ISSUE TITLE
Icon request: construction icons

### ISSUE THREAD

**Issue by GordonWerner** [FortAwesome/Font-Awesome#13623]
### What can it be used for?

icons could be used for construction projects, developers, architects, construction firms, unions, trade worker guilds, home/building repairs, etc ...

some of these ideas already exist, but would do well cross-pollinated to a Construction Icon category

Collection of tools:
hammer
screw driver
nails
drill
tape measure
wrench
pliers
saw
table saw
hard hat
paint brush
paint roller
ladder
etc ...

also equipment:
cement mixer
crane
dump truck
forklift
etc...

### Example image (optional)

![800px_colourbox8278779](https://user-images.githubusercontent.com/5200015/43218014-0d748ef0-8ff8-11e8-9606-efac7aedf8dd.jpg)
![800px_colourbox8286743](https://user-images.githubusercontent.com/5200015/43218015-0d875b16-8ff8-11e8-8c1f-1233879734c1.jpg)
![511600032-1024x1024](https://user-images.githubusercontent.com/5200015/43218016-0d99362e-8ff8-11e8-94b6-ba47dcbc34c9.jpg)

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x] I have included at least one example image if it could be helpful (optional)
- [x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

If you are a Font Aewsome 5 backer, you can request sets in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
