### ISSUE TITLE
Icon request: cleaning icons

### ISSUE THREAD

**Issue by GordonWerner** [FortAwesome/Font-Awesome#13622]
### What can it be used for?

Could be used for Hotels, Cruise Ships, businesses that perform cleaning (commercial and/or residential) duties

Examples:
Vacuum
Mop
Broom
Scrub Brush
Recycle
Trash
Spray Bottle
Gloves
Plunger/Toilet Brush
Bucket
Sponge
etc ...

Would also make for a good group of icons (Cleaning for instance)

### Example image (optional)

![111155-wiping](https://user-images.githubusercontent.com/5200015/43217409-6ae871d4-8ff6-11e8-80b5-67112f096552.png)
![177551-house-cleaning-pictograms](https://user-images.githubusercontent.com/5200015/43217410-6afbb6ae-8ff6-11e8-9415-03a68e148793.png)
![20735682-cleaning-icons](https://user-images.githubusercontent.com/5200015/43217412-6b274922-8ff6-11e8-9cc8-e5e42276d4e1.jpg)
![big-cleaning-icons-set-vector-1675919](https://user-images.githubusercontent.com/5200015/43217413-6b3aafa8-8ff6-11e8-9117-8b522906706d.jpg)

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x ] I have included at least one example image if it could be helpful (optional)
- [x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

If you are a Font Aewsome 5 backer, you can request sets in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
