### ISSUE TITLE
Icon request: window-with-globe (webpage)

### ISSUE THREAD

**Issue by houseall** [FortAwesome/Font-Awesome#13658]
### What can it be used for?
Web page (single icon)

### Example image (optional)
![webpage200x200](https://user-images.githubusercontent.com/1569084/43372464-34beaf20-936f-11e8-83af-e7b566618396.png)
 

Icon to represent MIME type for web page.  Recognizable with www (i.e. globe in browser).  More realistic when compared to browser f37e icon.  Not a duplicate.

**Comment by tagliala** [comment]
@houseall no, thanks. 

> Has this icon been add to the backlog?

Please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

and here: https://fontawesome.com/community/leaderboard/new

**Comment by houseall** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
