### ISSUE TITLE
Icon Request: fa-car-horn

### ISSUE THREAD

**Issue by mseminatore** [FortAwesome/Font-Awesome#13652]
An icon to represent beeping or honking a car horn.  A representative icon, apologies for the poor cropping.

![image](https://user-images.githubusercontent.com/16830648/43359056-fa186fe2-9250-11e8-951b-09b3b2fa2881.png)

**Comment by tagliala** [comment]
Does https://fontawesome.com/icons/bullhorn?style=solid fit your needs?

**Comment by mseminatore** [comment]
Hi, this is for an app that can remotely beep a car horn.  The bullhorn might work but doesn't exactly convey the meaning.  I admit that it is a difficult concept to capture.  Maybe a representation with a car in the image?  

Or maybe an icon for a bugle/trumpet.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
