### ISSUE TITLE
Icon request: sticker

### ISSUE THREAD

**Issue by thor-2018** [FortAwesome/Font-Awesome#13663]
I'd like to request an icons:

- sticker

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a single color example?

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by InsanityMeetsHH** [comment]
Example:
![new-sticker-512](https://user-images.githubusercontent.com/35538671/43568852-0c70f4c8-9636-11e8-81b2-66d769b84fa4.png)
Basically a shape (e.g. square and circle) with a lifted edge.

**Comment by sergiohampel** [comment]
Hi! 

Any news about this thread?

I'd like to use some icon like Instagram sticker symbol.

See bellow:

![](https://siri-cdn.appadvice.com/wp-content/appadvice-v2-media/2017/04/instagram-stories-stickers_e30a2962f99014d2cdbe7cc97ff2f8c5-xl.jpg)

**Comment by luizlbon** [comment]
I've tried to make a symbol like the examples above, using the stacked properties, but the results were awful.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome! [Take a look at it here.](https://fontawesome.com/icons/note-sticky?f=classic&s=solid)
