### ISSUE TITLE
Icon Request: Footnote Symbols

### ISSUE THREAD

**Issue by KzooDrew** [FortAwesome/Font-Awesome#13681]
I would like to see footnote symbols added to font awesome.  The symbols are listed here: https://en.wikipedia.org/wiki/Note_(typography)#Numbering_and_symbols

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesom! [Take a look at it here.](https://fontawesome.com/icons/superscript?f=classic&s=solid)
