### ISSUE TITLE
install v5.2 but node_modules/readme.md is v4.7

### ISSUE THREAD

**Issue by spaceman27** [FortAwesome/Font-Awesome#13690]
I install latest version 5.2
but copy an simple example on fontawesome homepage. don't not work
I checked in node_modules/readme.md file, it actually v 4.7

How does this happen? I deleted node_modules folder and npm install still not solve issue

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Since there is no official 4.7 Font Awesome node package, please check that you are using the official Font Awesome packages.

Ref: 
- https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers
- Advanced SVG usage: https://fontawesome.com/how-to-use/with-the-api/setup/getting-started

Hope it helps

Closing here
