### ISSUE TITLE
Icon request: icon-terminal-alt

### ISSUE THREAD

**Issue by Berkmann18** [FortAwesome/Font-Awesome#13709]
### What can it be used for?
Bash and Batch are core shellscripts used for Linux/Unix and Windows respectively and there are no shellscript/terminal icons that could substitute them.

### Example image (optional)
![Bash](https://images.ecosia.org/aaASWzOquaTogSLEBLXQI5bBhRs=/0x390/smart/https%3A%2F%2Fcdn.dribbble.com%2Fusers%2F1285930%2Fscreenshots%2F4040291%2Fbash-logo-by-vd_1x.png)
![Batch](https://images.ecosia.org/Ys6usdBJsqVltfoJmn0O2Z6f4PU=/0x390/smart/http%3A%2F%2Fwww.progassignments.com%2Fwp-content%2Fuploads%2F2016%2F06%2FDOS-Batch-Language-Assignment-Help.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
> there are no shellscript/terminal icons that could substitute them.

Does https://fontawesome.com/icons/terminal?style=solid fit your needs?

**Comment by Berkmann18** [comment]
That would go well with Batch but Bash is usually associated with the version where you can see "$_" instead of ">_".

**Comment by tagliala** [comment]
> That would go well with Batch but Bash is usually associated with the version where you can see "$_" instead of ">_".

@Berkmann18 sorry for being pedantic but I would like to disagree on this.

This is the official Terminal icon on macOS:

![image](https://user-images.githubusercontent.com/556268/43709638-a110dab4-996d-11e8-9d06-417420115050.png)

and it comes with bash by default.

Also, you can use zsh. In other words, the command language is independent from the shell itself. If you need to distinguish between bash and batch that's fine but please rename the request to "icon-terminal-alt" and specify that you need `$ _` instead of `> _` and the use case

**Comment by Berkmann18** [comment]
I suppose it's a Linux (specific to most distros) thing that doesn't apply to Unix (OSX, ...).
And that's using Bash not ZSH (which uses % by default).
So I guess in terms of popularity it would make more sense to have it as `icon-terminal-alt`.

**Comment by rpdelaney** [comment]
Bash has an "official" logo: https://github.com/odb/official-bash-logo

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
