### ISSUE TITLE
Icon Request: fa-input

### ISSUE THREAD

**Issue by javxp79989940** [FortAwesome/Font-Awesome#13702]
I designed a system that allows users to define the form elements themselves. I want to use Font-Awesome to identify it more aesthetically. But you can't find the material of the Input element and palette element.

**Comment by danieldraper** [comment]
To add some clarity for others that may stumble across this, something like:

<img width="249" alt="CleanShot 2020-08-12 at 23 24 53@2x" src="https://user-images.githubusercontent.com/1016423/90020314-0d81de80-dcf3-11ea-8890-88f70e6004f5.png">

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
