### ISSUE TITLE
SASS implementation of pencil-alt does not work

### ISSUE THREAD

**Issue by REPTILEHAUS** [FortAwesome/Font-Awesome#13731]
Hi, I am trying to sue the pencil-alt icon and its the only one that appears to be missing.. its in the variable files etc but just doesnt appear for some reason even though other solid icons appear no problem.. im using the SASS implementation, ive added my font dir, and included the following in my main stylesheet:

```
@import "./fontawesome/scss/fontawesome.scss";
@import "./fontawesome/scss/solid.scss";
@import "./fontawesome/scss/brands.scss";
@import "./fontawesome/scss/regular.scss";
```

trying to use it like so:

```
.edit {
  @include fa-icon;
  @extend .fas;

  &:before {
    content: fa-content($fa-var-pencil-alt);
  }
}
```

**Comment by REPTILEHAUS** [comment]
actually i notice that if i remove this import ```@import "./fontawesome/scss/regular.scss";``` it works.. not really a good solution.. any ideas.. i need to be able to use all icons

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

There is an issue in the documentation at https://fontawesome.com/how-to-use/on-the-web/using-with/sass#mixins 

The example doesn't work because `@include fa-icon;` overrides `font-weight: 900`, set by `@extend .fas;`

You can use:

```scss
.edit {
  @extend .fas;

  &:before {
    content: fa-content($fa-var-pencil-alt);
  }
}
```

and you will get the same result as `fas fa-pencil-alt`.

Anyway, there is a difference in the stylesheet.

The rule at line 12 is not present in `.fas` https://github.com/FortAwesome/Font-Awesome/blob/5.2.0/web-fonts-with-css/scss/_mixins.scss#L4-L13

Ref: #13170

@talbs @robmadole any thoughts?

**Comment by robmadole** [comment]
Ah yeah, I see that. Darn you Sass. Working on a fix.

**Comment by robmadole** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sass mixins don't work](https://trello.com/c/NFbMhf5n/230-sass-mixins-dont-work)

**Comment by robmadole** [comment]
Ok this will go out in 5.3.0.  All fixed up in the build system.

**Comment by tagliala** [comment]
@robmadole could you please mention me in the fix? I would like to take a look
