### ISSUE TITLE
Icon request: kitchenette

### ISSUE THREAD

**Issue by ergec** [FortAwesome/Font-Awesome#13744]
### What can it be used for?
To describe facilities on a dorm/hotel/travel website

### Example image (optional)

https://www.iconfinder.com/icons/491546/cabinet_cupboard_fridge_home_kitchen_kitchenette_icon
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJ27fdfKOxfA6WxHGKmz4LWIEczGViR0sTsoxbiALnVjTcqcGA
https://danezisaccommodation.com/wp-content/uploads/2017/12/kitchen_icon-300x300.png
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSBzryikvPcZuCkcnsqnsx0fMgYWTgdairq9_XxZYopXXmyGxL

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
