### ISSUE TITLE
Feature request: Remove unwanted icons using an online font builder

### ISSUE THREAD

**Issue by wenn32** [FortAwesome/Font-Awesome#13747]
### Describe the problem you'd like to see solved or task you'd like to see made easier

Remove unwanted fonts.

### Is this in relation to an existing part of Font Awesome or something new?

New Feature request.

### What is 1 thing that we can do when building this feature that will guarantee that it is awesome?

A font build tool or some sort which allows me to select fonts that I use and then download it to my personal blog without taking up lot of file size. 11MB is a lot for using 4-6 icons. :)
Examples: fontello.com, icomoon.io

### Why would other Font Awesome users care about this?

1. Bandwidth.
2. Firewall restrictions to use public CDN.
3. App size decreases considerably.

### On a scale of 1 (sometime in the future) to 10 (absolutely right now), how soon would you recommend we make this feature?

I don't want to be selfish and take up lot of your time but sooner the better for the world.

### Feature request checklist

- [ ] This is a single feature (i.e. not a re-write of all of Font Awesome)
- [ ] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: moar cowbell`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome-Pro/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The good news is that this feature is already available through the built-in tree-shaking feature. More information at https://fontawesome.com/how-to-use/with-the-api/other/tree-shaking

The other good news is that this feature is going to be implemented for our Pro users: https://fontawesome.com/updates

Otherwise, feel free to use fontello or other online tools for subsetting the webfont version of font awesome

Closing here
