### ISSUE TITLE
Icon request: icon-ok-empty

### ISSUE THREAD

**Issue by rhollow** [FortAwesome/Font-Awesome#1375]
An empty version of the existing icon-ok (&#xf00c;) could serve the following use case:

• In a list of tasks, tasks that have not yet been competed could be indicated by icon-ok-empty. Completed tasks can be marked by the existing icon-ok. While incompleteness could be communicated for each task by the absence of icon-ok, having a clear, related symbol that contrasts with icon-ok would be helpful.
![icon-ok-empty](https://f.cloud.github.com/assets/1303144/684801/d922fc1e-da07-11e2-88ad-d08659ec90fb.png)
![icon-ok-empty with baseline](https://f.cloud.github.com/assets/1303144/684802/dd459a86-da07-11e2-92ef-8bbc696b322f.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
