### ISSUE TITLE
Icon request: Fraction-Template

### ISSUE THREAD

**Issue by rowejs** [FortAwesome/Font-Awesome#13780]
### What can it be used for?

On a scientific calculator, when you press the fraction button, a template to type in a fraction appears on the screen. I'd like to do this same thing in HTML and javascript.

### Example image (optional)
![976466_vw_etz00_1021941101](https://user-images.githubusercontent.com/40009415/44229968-a37ce000-a191-11e8-9760-78a7d22bfd28.jpg)
(The first button in the row of green buttons - it looks like a solid rectangle on top of an empty rectangle with a line between)

### Icon request checklist

- [YES ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [YES] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [YES] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [YES] I have included at least one example image if it could be helpful (optional)
- [YES] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
@rowejs could you please find a single color example on google images easier to identify and to see?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
