### ISSUE TITLE
Icon Request: fa-torah

### ISSUE THREAD

**Issue by Wingo5315** [FortAwesome/Font-Awesome#13784]
I think this icon would be useful when it comes to referring to Jewish religious texts in the Torah and displaying The Torah in general. There are two suggestions I have about how to make this icon:
- Use the current book icon with the Star of David on the front
- Something like this:
![image](https://user-images.githubusercontent.com/25369857/44296154-7bd06980-a2b0-11e8-9681-b8cd2699c723.png)

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/torah?style=solid

**Comment by AndreasAdler** [comment]
Hi,

the new religon icons from version 5.3 are really nice.
Although I have some notes.

1. The Jewish bible is called [Tanakh](https://en.wikipedia.org/wiki/Hebrew_Bible). It contains the Torah (fieve books of Moses), the Nevi'im and the Ketuvim. So I think the icon "torah" should be renamed to "tanakh".
2. Both the Hewbrew and the Arabic language are right-to-left languages so the book front cover usually is on the "back". I think it would make those icons more authentic when the book would be mirrored to indicate the rtl text flow (see [Quran sample photo](https://goo.gl/images/gKGpuQ) and [Tanakh sample photo](https://goo.gl/images/U6ujxr).)

What do you think?

**Comment by sensibleworld** [comment]
@AndreasAdler Would something like this work as an update? We'd change the `torah` to a scroll, and add a new icon for `tanakh` with the book flipped

<img width="641" alt="screenshot 2018-12-17 16 06 26" src="https://user-images.githubusercontent.com/529604/50115566-c4c00c80-0215-11e9-990a-7b032baf7de5.png">

**Comment by AndreasAdler** [comment]
@sensibleworld Definitely an improvement over the old icon. 👍🏻

**Comment by perymimon** [comment]
as a Jew the start on the book above not reference me like a Jew think. perhaps it look more like as a Islamic star. or the mark used in the past to mark Jews.
The Star of David looks completely different. google on it . 

The first suggestion above seems much more correct and authentic, because the form of the icon is the form of the original Torah scroll of Judaism made of one piece. Indeed, it contains basically  only the Torah or the Torah is the first thought when you see the Icon so `fa-torah` sound right and easy to remember.

**Comment by sensibleworld** [comment]
@AndreasAdler @perymimon Thanks for the feedback! We made a couple of updates in the latest release of Font Awesome.

The `fa-torah` icon now contains a more accurate Star of David and is in scroll form: 
https://fontawesome.com/icons/torah?style=solid

We've also added a new `fa-tanakh` icon with book in the correct orientation: 
https://fontawesome.com/icons/tanakh?style=solid

**Comment by yringler** [comment]
It's so nice to see some Jewish font icons! Great work!
Regarding fa-torah : I see the thought process there (it was switched to a scroll, and it was made Jewish with a star of David), but as current it is not a Torah scroll. All Torah scrolls are opened horizontally, and, being as they contain a considerable amount of text, most of the scroll will always be wrapped around 2 wooden poles.

There are 4 primary forms (IMHO )for a Torah scroll.
1. Ashkenazi open 
![image](https://user-images.githubusercontent.com/4070825/52380930-a28c8300-2a3d-11e9-89ec-919c2d41d16e.png)
1. Ashkenazi closed 
![image](https://user-images.githubusercontent.com/4070825/52381012-eb443c00-2a3d-11e9-8681-fac34c7c57c7.png)
1. Sefardi open
1. Sefardi closed

If there will only be one icon, I would suggest using the Ashkenazi open torah scroll (as @Wingo5315 and @perymimon). It is universally and instantly recognizable.

To give a little more context, [here's a link explaining how a Torah scroll is used](https://www.chabad.org/library/article_cdo/aid/365942/jewish/The-Torah-Reading.htm).

**Comment by sensibleworld** [comment]
Thanks for the feedback, @yringler! We'll look into getting this updated.

**Comment by HodofHod** [comment]
@sensibleworld Thank you so much for reopening this (and for creating it)!

 I just wanted to chime in to agree with @yringler and the others above. It's so great to see Jewish icons, and I hesitate to seem ungrateful (because I'm not), but the current one isn't recognizable as a Torah, which has a very well-known and established "look". This is evidenced by a quick image search for "[torah](https://www.google.com/search?q=torah&tbm=isch)" or "[torah icon](https://www.google.com/search?q=torah+icon&tbm=isch)".

Personally my preference would be to have an Aleph  (the first letter of the Hebrew alphabet) instead of a Star of David, for a variety of reasons (e.g., the aleph is actually used in the Torah scroll itself), but either way would be great.

Again, thank you!

**Comment by sensibleworld** [comment]
Thanks for all of the feedback on this icon folks. The update was just released: https://fontawesome.com/icons/torah?style=solid
