### ISSUE TITLE
Icon request: Root

### ISSUE THREAD

**Issue by way2285** [FortAwesome/Font-Awesome#13783]
Can you please create an icon for a root?  I would like it to use an icon that resembles a tree root to indicate a "root task" in a menu.
[https://www.google.com/search?q=root+icon&rlz=1C1CHBF_enUS749US749&tbm=isch&source=iu&ictx=1&fir=f6JSkPtkoAl3XM%253A%252CvRHUblsZQFtzPM%252C_&usg=AFrqEzc1hubp4e4L7sY8bg-uqtckJNk6aQ&sa=X&ved=2ahUKEwinoaWs9PTcAhUQzlkKHRnIDY0Q9QEwDHoECAUQHA#imgrc=f6JSkPtkoAl3XM:](url)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
