### ISSUE TITLE
Icon request: camera-retro-alt (old instagram brand)

### ISSUE THREAD

**Issue by vasvaller** [FortAwesome/Font-Awesome#13795]
### What can it be used for?

We can use it for instagram on sites. We need it because now you have no filled instagram icon. 

### Example image (optional)

<img width="180" alt="xnip2018-08-21_10-50-03" src="https://user-images.githubusercontent.com/42568726/44388390-ac263b00-a530-11e8-8f99-fb0057ff2595.png">
<img width="195" alt="xnip2018-08-21_10-49-51" src="https://user-images.githubusercontent.com/42568726/44388391-acbed180-a530-11e8-8595-7a4be2aecdc9.png">
<img width="123" alt="xnip2018-08-21_10-49-42" src="https://user-images.githubusercontent.com/42568726/44388392-acbed180-a530-11e8-9016-3fb5375418a9.png">

### Icon request checklist

- [+] This is a single icon (different variants of filled icon)
- [+] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [+] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [+] I have included at least one example image if it could be helpful (optional)
- [+] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please note that non of the above icons represent a filled-in version of the instagram brand

There is a request for a square version of the instagram icon available at #9223

Renaming to `camera-retro-alt` https://fontawesome.com/icons/camera-retro?style=solid

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
