### ISSUE TITLE
Icon request: stay

### ISSUE THREAD

**Issue by rent-is** [FortAwesome/Font-Awesome#13812]
### What can it be used for?

indication for stay during holidays, place to stay overnight
pack: travel icons

### Example image (optional)
`
<span class="fa-layers fa-fw">		
	<i class="fal fa-warehouse" data-fa-transform="shrink-1 up-1"></i>		
	<i class="fas fa-square FGwhite" data-fa-transform="down-2" ></i>	
	<i class="fal fa-bed" data-fa-transform="shrink-6 down-2" ></i>		
</span>	
`
![stay](https://user-images.githubusercontent.com/42088137/44574016-79767f80-a788-11e8-940a-17fe04508925.png)

alternative 1
![stay-alt2](https://user-images.githubusercontent.com/42088137/44574047-84c9ab00-a788-11e8-8938-c73107815cba.png)

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
