### ISSUE TITLE
Icon request: icon-radius

### ISSUE THREAD

**Issue by r-man** [FortAwesome/Font-Awesome#13839]
### What can it be used for?

The icon can be used to display measurement results

### Example image

![default](https://user-images.githubusercontent.com/1829702/44789923-8fc87500-aba6-11e8-849f-4becb2d8935b.png)

### Icon request checklist

- [x] This is a single icon
- [x] The title starts with "Icon request: " and is followed by the requested icon name
- [x] I have searched for existing issues and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image
- [x] The request is for a concrete object

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
