### ISSUE TITLE
Icon Request: icon-tag-add and icon-tag-remove

### ISSUE THREAD

**Issue by igal-getrailo** [FortAwesome/Font-Awesome#1384]
these can be useful to many users IMHO, maybe as simple as adding a + and - signs on top of the current icon-tag

TIA

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
