### ISSUE TITLE
Icon request: transgender-double

### ISSUE THREAD

**Issue by PandyLegend** [FortAwesome/Font-Awesome#13845]
### What can it be used for?
As you have mars-double and venus-double, which can be used to represent and male and female couple respectively, it would make sense to also have a transgender-double to represent a trans couple. 
Additionally, similar to the venus-mars pairing, trans-venus and trans-mars icons would also make sense.

### Example image (optional)
I think it's self explanatory

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Actually, Font Awesome gender symbols are taken from wikipedia: https://en.wikipedia.org/wiki/Gender_symbol#Sociology

In our knowledge, the `double male` does not represent a male couple, but [Male homosexuality](https://en.wikipedia.org/wiki/Gender_symbol#Sociology) and it is used to represent the sexual orientation of a single person

If you can point me to another wikipedia-like resource about gender symbols, I would be happy to take a look and discuss it with the team

Otherwise, if you need to represent couples, I should ask you to consider layering/stacking features, because we take gender equality very seriously and, as you mentioned, we should provide all possible combinations of couples (transgender-double, mars-transgender, venus-transgender, mars-stroke-transgender...)

Ref:
- SVG: https://fontawesome.com/how-to-use/on-the-web/styling/layering
- CSS: https://fontawesome.com/how-to-use/on-the-web/styling/stacking-icons

Test implementation:
http://jsfiddle.net/tagliala/gzc0ksmp/5/
