### ISSUE TITLE
Icon Request: driving navigational icons.

### ISSUE THREAD

**Issue by sinfuljosh** [FortAwesome/Font-Awesome#13847]
The icons found in navigation and driving directions sites for things like merge-left, merge-right. 

Similar to these https://github.com/mapbox/directions-icons/tree/master/src/png/dark

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry but I cannot leave this request open because we do not accept requests for icon sets in the Free Repository (icon sets are hard to manage and to implement).

If you are a Pro user, you can request a set in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Closing here

**Comment by sinfuljosh** [comment]
Thanks didn’t realize I posted to the wrong one.
