### ISSUE TITLE
Icon request: chair-left (and chair-right)

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#13867]
### What can it be used for?

To indicate classroom seat type for stadium seating, where the desktop flips up from the side of the chair. An icon for left-handed and right-handed seats. (not a single image to be flipped on the vertical axis)
The attached image is copyrighted.

### Example image (optional)

![image](https://user-images.githubusercontent.com/16199122/44948912-9be94800-addb-11e8-9f0a-082614ea20a7.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

How can I distinguish between a left handed seat and a right handed seat? Could you please provide examples for both?

**Comment by timmackey** [comment]
rotate the image on the vertical axis

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
