### ISSUE TITLE
Icon Request: fa-domain  ||  Can Any One Will Help Me GETTING DOMAIN NAME ICONS.. LIKE [.COM/.IN/.ORG/.NET/.CO.IN/.LIVE AND SO ON...]

### ISSUE THREAD

**Issue by Ask4HD** [FortAwesome/Font-Awesome#13872]
Hello.. Friends.. Im Completly New Persone HERE..!! Please Make My  Wish Comes TRUE IF Anyone Can..!!
... I want Some Icons.. domain name.. extensions.. like ..   .COM / .NET / .ORG / .CO.IN / .LIVE  ... AND SO ON... I want this icons to be appeare on my WEBSITE.. INSTEADE OF SOCIAL LINKS.. SO THAT, I CAN DISPLAY THIS.. DIFFERENT EXTENSION OF MY SITE... INSTEADE OF SOCIAL LINKS.. SO WITHOUT THIS ICONS ITS NOT POSSIBLE ANY HOW.. SO PLEASE HELP ME GUYS.. YOUR ALL MY LAST HOPE..!! IM SRY IF SAID SOMETHING NOT NECCESSARY..!!

**Comment by Ask4HD** [comment]
Here.. is some Example.. from GoDaddy Web Home PAGE
![screenshot 3](https://user-images.githubusercontent.com/42902870/44952010-93534900-ae91-11e8-9ab4-f81afc3874e1.png)
Just Giving You Idea About The Pattern Of ICON.. Colour Scheme DOESNT MATTERS..!!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
