### ISSUE TITLE
Icon request for social media sites

### ISSUE THREAD

**Issue by vinot19** [FortAwesome/Font-Awesome#13887]
Hi,

Thank you so much for producing these wonderful icons. This is such a tremendous help for our project.

I would very much appreciate if you can add icons for MySpace.com, Ask.fm, livejournal.com, so we can use them to highlight the links to these sites.

Thank you so much from our team and I,
Vinoth Kumar

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
