### ISSUE TITLE
Icon Request: Food Requirement / Restaurant Icons

### ISSUE THREAD

**Issue by blizzardengle** [FortAwesome/Font-Awesome#13898]
### What can it be used for?

Well I'm sure this list could be bigger it would be nice to have icons for common dietary requirements and restaurant menus such as the following. Note that the names do not have to be what is listed in the parentheses:

- GMO Free (dietary-gmo-free)
- Gluten Free (dietary-gluten-free)
- Dairy Free (dietary-dairy-free)
- Nut Free (dietary-nut-free) / Tree Nut Free (dietary-tree-nut-free)
- Vegan (dietary-vegan) 
- Vegetarian (dietary-vegetarian) ==> #4950

### Example Images

The icons should have a similar feel to them and could be graphic like this GMO Free icon:

[![noun_non gmo_58377](https://user-images.githubusercontent.com/11205240/45125387-7639a700-b12b-11e8-86c2-eb22d75ee0ed.png)](https://thenounproject.com/term/non-gmo/58377/)

or they could all be text like this text version of the GMO Free icon:

![non-gmo-icon](https://user-images.githubusercontent.com/11205240/45125582-5656b300-b12c-11e8-9785-f3a01dd3301e.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
   **DISCLAIMER**: There are similar threads but not requests exactly related to this see [Food Icon Categories #1895](https://github.com/FortAwesome/Font-Awesome/issues/1895) and [Allergen specific class of icons #13383](https://github.com/FortAwesome/Font-Awesome/issues/13383).
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

If you are a Font Awesome Pro backer, you can request a set of icons in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
