### ISSUE TITLE
Icon Request: fa-lightbulb-exclamation-on

### ISSUE THREAD

**Issue by stphnwlkr** [FortAwesome/Font-Awesome#13902]
Please consider an "on" version of fa-lightbulb-exclamation? I attempted to use stacking but the "light-rays" causes the centers to not align.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Since `lightbulb-exclamation` is a FA Pro exclusive icon, could you please open this issue in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
