### ISSUE TITLE
Icon request: Fruit icons

### ISSUE THREAD

**Issue by CherryPlaysRoblox1** [FortAwesome/Font-Awesome#13918]
### What can it be used for?
If I want to make a list of fruits or something and I want an icon for each of them, or if I want to make a website about eating healthy, I can use apples, or bananas, etc.

### Icon request checklist

- [V ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [V ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ V] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ V] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

This request does not meet:

> This is a single icon or matched pair (Ex: lock / unlock)


Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
