### ISSUE TITLE
facebook icon 

### ISSUE THREAD

**Issue by ahmedmansour1997** [FortAwesome/Font-Awesome#13919]
facebook icon's unicode is wrong in this link 
https://fontawesome.com/icons/facebook-f?style=brands
the right on is in here 
https://fontawesome.com/v4.7.0/icon/facebook

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`f39e` is the correct unicode point for `facebook-f` in Font Awesome 5.0
`f09a` is the correct unicode point for `facebook` in Font Awesome 4.7

I think that mapping `f09a` to `facebook` instead of `facebook-f` was the right choice to do, because `facebook` is the official brand logo for Facebook

@talbs any thought?

**Comment by ahmedmansour1997** [comment]
thanks for your reply ,
i didn't notice that i was using another version of font awesome.

**Comment by talbs** [comment]
> I think that mapping f09a to facebook instead of facebook-f was the right choice to do, because facebook is the official brand logo for Facebook.

@tagliala, sorry for the delay. Yes, we completely agree with your comment above and that was the main reason we changed unicode values when redesigning and cleaning things up for Version 5.

We tried to note those changes on https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#name-changes. I'm attaching a screenie of all of the `facebook`-related ones below.

![image](https://user-images.githubusercontent.com/163763/47227983-1a04ac80-d392-11e8-82cc-6be826a777a5.png)

Closing this issue since this was a planned change and we've documented the difference between versions. Shout if we can help clear this up any further or support upgrading from version 4 to 5.
