### ISSUE TITLE
New Icon: Clipboard Cross

### ISSUE THREAD

**Issue by jamiechorlton-fd** [FortAwesome/Font-Awesome#13936]
Along the lines of the fa-clipboard-check icon and fa-clipboard icon I would like to see an fa-clipboard-cross icon (the opposite of fa-clipboard-check).

I have been developing a system for a treatment provider recently and an icon set of the three clipboards would be very helpful!

Great work people!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
