### ISSUE TITLE
Icon request: icon-poloshirt

### ISSUE THREAD

**Issue by busaway** [FortAwesome/Font-Awesome#13942]
### What can it be used for?
for explaining a visual dress code thing with something with collar required. it can be a polo shirt image, or collared shirt

### Example image (optional)

![polo shirt](https://upload.wikimedia.org/wikipedia/commons/8/8c/Polo_Shirt_Basic_Pattern.png)

### Icon request checklist

- [x] This is a single icon 
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
@tagliala `clothing-fashion (category)` label for this request?

**Comment by aethior** [comment]
@tagliala `clothing-fashion (category)` label for this request?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
