### ISSUE TITLE
Icon request: Barn

### ISSUE THREAD

**Issue by RummelAgency** [FortAwesome/Font-Awesome#13963]
### What can it be used for?

 Farming

### Example image (optional)

![icons-for-new-website_0002_layer-4](https://user-images.githubusercontent.com/43376948/45688036-51c3ce80-bb1e-11e8-95a2-169250bebdc0.png)

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
Hi @RummelAgency,

The `fa-farm` icon was added in v5.9.0.
Check https://fontawesome.com/icons/farm

Regards.

**Comment by tagliala** [comment]
It is not exactly the same thing, farm is #1470

**Comment by aethior** [comment]
> It is not exactly the same thing, farm is #1470

👍, I just edited my reply to avoid future confusions.

**Comment by tagliala** [comment]
But maybe farm would fit the use case of this request

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/farm?f=classic&s=solid)
