### ISSUE TITLE
Icon Request: fa-scoop

### ISSUE THREAD

**Issue by beelocal** [FortAwesome/Font-Awesome#13973]
**What can it be used for?**
I am designing a site for a grocery store that sells bulk dry goods

**Example image (optional)**
Would like it like this but inverted horizontally so the handle is facing to the left. [https://thenounproject.com/term/scoop/93808/](url)

**Icon request checklist**

- [X]   This is a single icon or matched pair (Ex: lock / unlock)
- [X]   The title starts with "Icon request: " and is followed by the requested icon name (Ex: Icon request: magical-unicorn)
- [X]   I have searched for existing issues and to the best of my knowledge this is not a duplicate
- [X]   I have included at least one example image if it could be helpful (optional)
- [X]   The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

Thank you!!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
