### ISSUE TITLE
Icon requests: Game Icons

### ISSUE THREAD

**Issue by Barsnes** [FortAwesome/Font-Awesome#13993]
It would be nice to have icons for different games, here is a list of games that should be added if this is approved:

- CSGO
- Hearthstone
- Rocket League
- League of Legends
- Overwatch
- FIFA
- Fortnite
- PUBG
- Dota 2
- Rainbow Six
- Madden
- Paladins

**What can it be used for?**
Referencing different games, either in articles, upcoming matches, etc.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
