### ISSUE TITLE
Icon Request: icon-name

### ISSUE THREAD

**Issue by sunnnnnner** [FortAwesome/Font-Awesome#13997]
希望能够添加关于邮箱(email)相关的font。

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Are you looking for https://fontawesome.com/icons/envelope?style=solid ?

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
