### ISSUE TITLE
Icon Request: dollar with slash

### ISSUE THREAD

**Issue by leacardenas** [FortAwesome/Font-Awesome#14004]
<img width="51" alt="dollar" src="https://user-images.githubusercontent.com/24193144/46041242-8b24ad00-c0cf-11e8-9f22-59ca26af5bcb.PNG">

A dollar sign but with a slash in it

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
