### ISSUE TITLE
Icon request: Freezer

### ISSUE THREAD

**Issue by manojsa** [FortAwesome/Font-Awesome#14028]
### What can it be used for?

This can be used to denote freezer which is used in hospitals to store blood or to store any cell related parts.

### Icon request checklist

- [1] This is a single icon,
- [ 2] The title starts with "freezer " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ 3] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate.

**Comment by xmuskrat** [comment]
Also can be used to denote chilled containers on ships.

**Comment by xmuskrat** [comment]
![image](https://user-images.githubusercontent.com/59917/56762907-daaa8480-6755-11e9-9d11-fdcd721b5394.png)

**Comment by aethior** [comment]
@tagliala `household (category)` label for this request?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
