### ISSUE TITLE
continuing problems with CDN (Pro)

### ISSUE THREAD

**Issue by lfelton** [FortAwesome/Font-Awesome#14022]
Hi - I'm a paid up Pro subscriber.

There were problems several times yesterday where pro.fontawesome.com was unreachable for large periods of time. I've noticed that there have been several issues today as well (time outs and very slow page loading due to no/slow response for your Pro CDN). I'm in Europe, UK on a BT broadband if that makes any difference.

Do you know what the issue is? I'm going to have to go back to serving font awesome from my own server if access to your CDN continues to be unreliable as it's causing pages from my web site to not load, or load without icons.

**Comment by lfelton** [comment]
Sorry, I'm misleading you slightly: I've also switched to my EE 4G in case it was an interop problem with BT, not your CDN (even though other CDN were loading). However, the problem still occurs there. Sorry for any confusion.

**Comment by tagliala** [comment]
Hi, 

sorry for the inconvenience. We know there were been performance issues with the free CDN.

At the moment everything is fine here (EU - Italy) with the Pro CDN

Please let us know in a few hours if the situation is back to normal.

**Comment by Brampage** [comment]
Last week I had this problem for half an hour.
Right now the CDN is also not working.
It's not stable.

**Comment by kokoshneta** [comment]
The Pro CDN is consistently much slower than the free CDN for me. Using the Pro CDN on any page at all consistently adds anywhere between five seconds and a whole minute of loading time to _every_ page load (there doesn’t seem to be any caching going on). It’s been this way for at least four or five months (I’ve generally just made do with free icons to prevent slow loading times, but it is annoying).

This is on a VPS server also located in the UK.

**Comment by tagliala** [comment]
@kokoshneta could you please send your message at hello@fontawesome.com or report your issue in the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

If you will not get a fast answer, please mention me here

**Comment by fabswt** [comment]
Same here. Specifically: **loading the JS file from the CDN is ultra-slow**. The CSS file loads fine. Other JS files from other sites are okay. It's been like this for *at the very least* 2 weeks. With such speeds, I wouldn't use it i production – **frequently 10+ sec.**

I'm using layered icons inside primary buttons and the lag makes it very unsightly (the left icon hasn't finished rendering and will show up as is for about ten seconds): 

<img width="304" alt="Screen Shot 2019-04-18 at 6 57 56 PM" src="https://user-images.githubusercontent.com/3042488/56377981-fec50d80-620b-11e9-9324-b91f09ba17a6.png">

FYI, I'm including the file from a `.localhost` domain that I've added to the list of authorized sites in my FontAwesome profile. This is how I'm including the JavaScript file:

    <script defer src="https://pro.fontawesome.com/releases/v5.8.1/js/all.js" integrity="sha384-GBwm0s/0wYcqnK/JmrCoRqWYIWzFiGEucsfFqkB76Ouii5+d4R31vWHPQtfhv55b" crossorigin="anonymous"></script>

And so this is the kind of speeds I am getting, notice how everything else is fine:

<img width="1840" alt="Screen Shot 2019-04-18 at 6 51 45 PM" src="https://user-images.githubusercontent.com/3042488/56377717-4ac38280-620b-11e9-914f-2986e4c2ae2e.png">

**Comment by tagliala** [comment]
@fabswt thanks for reporting this

If you can disclose your country it could be helpful to understand if the issue depends on your region. Otherwise, feel free to send an email at hello@fontawesome.com 

At the moment I do not have issues here in Italy.

Load time without cache: ~1.3s. With cache: ~31ms

![image](https://user-images.githubusercontent.com/556268/56378840-86ac1700-620e-11e9-83a7-727eb96103e1.png)
![image](https://user-images.githubusercontent.com/556268/56378847-8c096180-620e-11e9-91f4-b09aaaa1bed8.png)

**Comment by fabswt** [comment]
@tagliala I'm writing from Hungary.

I tried from CodePen (after adding codepen.io as an authorized domain) on the odd chance that this was related to my using it on `.localhost`), but the issue is still here.

If I try with a VPN, the problem is still here. Might be not as acute… at about 2000-3000ms for various locations, but it's still an issue. Keep in mind, all other resources load in about 55ms.

Maybe check with the CDN company? Can send you more details if that helps.

**Comment by fabswt** [comment]
P.S.: I realize only now that `all.js` is a hefty 4 MB in size… is there any service to bundle just the icons I need and lighten up the load?

**Comment by tagliala** [comment]
> Maybe check with the CDN company? Can send you more details if that helps.

Please drop a line at hello@fontawesome.com . Also include details of your connection and a link to this thread. Let me know if you will not get answers in a few hours

> I realize only now that all.js is a hefty 4 MB in size… is there any service to bundle just the icons I need and lighten up the load?

With modern front-end development tools such as webpack, you can take advantage of tree-shaking and reduce the file size to just icons you are using. 

https://fontawesome.com/how-to-use/with-the-api/other/tree-shaking

The subsetter tool is on its way for Pro users

Otherwise you can simply download `all.js`, remove all the icons you aren't using, and host it on your server

**Comment by fabswt** [comment]
I'd argue that the current downtime is another example that the CDN cannot be trusted (2h+ downtime on and off.)

I know I'm not and won't be using it in production.

**Comment by tagliala** [comment]
Hi, we are migrating to a new DNS provider

Sorry about the issue

Ref: https://status.fortawesome.com/incident/101

**Comment by tagliala** [comment]
Let's use #11146, even if it is closed
