### ISSUE TITLE
Icon request: icon-robotic-arm

### ISSUE THREAD

**Issue by cheics-d2l** [FortAwesome/Font-Awesome#14053]
For automation tasks where we don't want to personify the automation too much.

![robotarm](https://user-images.githubusercontent.com/8430763/46367771-81112a00-c64c-11e8-8dd2-af96328e9af8.png)

**Comment by r-man** [comment]
+1

**Comment by Crissov** [comment]
There is a related Unicode emoji coming, but it is intended to show a prosthetic arm.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/conveyor-belt-arm?f=classic&s=solid)
