### ISSUE TITLE
Icon request: containers

### ISSUE THREAD

**Issue by jenicevazquez** [FortAwesome/Font-Awesome#14071]
### What can it be used for?

Logistics systems

### Example image (optional)

Maybe like the Docker icon

### Icon request checklist

- [x ] This is a single icon or matched pair (Ex: `lock` / `unlock`) Single icon
- [ x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x ] I have included at least one example image if it could be helpful (optional)
- [ x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We already have a container icon: https://fontawesome.com/icons/container-storage?style=solid

Do You need an icon representing multiple containers?

**Comment by vampirak** [comment]
Sorry, I had not seen the PRO icons, by the way, congratulations, I love your work, I was looking for an icon with multiple containers to represent shipment. Thank you.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.]()
