### ISSUE TITLE
Icon request: fa-rotate-left, fa-rotate-right

### ISSUE THREAD

**Issue by akendrick451** [FortAwesome/Font-Awesome#14092]
Request for image rotate left and image rotate right icon. 

I know this has been requested before, and a suggestion to use undo and redo in it's place. 

I believe that is a bad solution. Icons for redo and undo should be used for that purpose. It is confusing to try to use them for another purpose.

**Comment by mikejf-pr** [comment]
Honestly, these icons are fairly well established for design rotate and flip.

![image](https://user-images.githubusercontent.com/35911870/46773029-de8d3100-cd46-11e8-9dcc-d028c58cca40.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.]()
