### ISSUE TITLE
Icon request: WiFi-4 / 5/ 6

### ISSUE THREAD

**Issue by KevinvOosterhout** [FortAwesome/Font-Awesome#14095]
### What can it be used for?

To differentiate between wifi standards. The standards are being renamed as 802.11n will become wifi-4, 802.11ac will become wifi-5 and 802.11ax will become wifi-6. see (https://www.wi-fi.org/discover-wi-fi/wi-fi-6) 

### Example image (optional)

![image](https://user-images.githubusercontent.com/1365476/46791224-f2ce2f80-cd40-11e8-95c7-41d40f391e9a.png)

### Icon request checklist

- Wifi icon
- Number with the icon to differentiate the standard being used

**Comment by roalvesrj** [comment]
@KevinvOosterhout  Excellent request! I need it too, but from what I could see, they haven't implemented it until today :(

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Thisrequest is legit, but please keep in mind that **in a web application with Font Awesome Pro** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: http://jsfiddle.net/tagliala/2s78abqk/26/

Ref:

https://fontawesome.com/v6/docs/web/style/power-transform
https://fontawesome.com/docs/web/style/mask
https://fontawesome.com/docs/web/style/layer

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
