### ISSUE TITLE
Icon request: fa-sauna

### ISSUE THREAD

**Issue by c2ofh** [FortAwesome/Font-Awesome#14109]
### What can it be used for?

For baths or hotels or for the complete northern europe region.

### Example image (optional)

![image](https://user-images.githubusercontent.com/10913793/46910991-55e1e100-cf50-11e8-8d4d-33abdf1fdb82.png)

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by Crissov** [comment]
Unicode emoji #222:
🧖‍♀️🧖‍♂️

**Comment by szczemp** [comment]
I just make this icon for hotel service.
https://u.lkn.pl/png/sauna_55Gy.png
It is a combination and modification of free fontawesome icons. Here I used trash, cup of cofee and swimming pool ladder.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
