### ISSUE TITLE
Discord Icon Not Working

### ISSUE THREAD

**Issue by gleeful** [FortAwesome/Font-Awesome#14101]
![image](https://user-images.githubusercontent.com/23424193/46876658-e4e5e080-ce0c-11e8-9e6e-c8a9bbe823c9.png)

The rest of the icons work just fine, just not this one.

Edit: Someone said to add "fab" to it, but I'm unsure what they mean by that.
I changed the code from 
`,"fa-discord" => "\\f392",`
to 
`,"fab fa-discord" => "\\f392",` and to ,`"fab-discord" => "\\f392",` and neither of them worked.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[fa-discord](https://fontawesome.com/icons/discord?style=brands) has been introduced in version 5.0

I'm pretty confident you are using an old 4.x version of Font Awesome, because YouTube icon has been changed in version 5.0

Please refer to https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4 if you are interested in upgrading to Font Awesome 5.x

Hope it helps

Closing here

**Comment by blakecannell** [comment]
I'm experiencing this with `5.0.8`. All other icons (I've tested) work fine. Discord does not. The svg seems to be present in the javascript file, so I'm not sure what's happening here. 🤷‍♂️ 

![Screen Shot 2019-03-22 at 3 42 12 pm](https://user-images.githubusercontent.com/629240/54801047-21214500-4cb9-11e9-8785-3ea97f828ccb.png)

**Comment by tagliala** [comment]
@blakecannell please open a new issue and fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by Sarthak-Sidhant** [comment]
For Me, Discord's Old Icon Show Up.

**Comment by tagliala** [comment]
@Sarthak-Sidhant probably your application is using (directly or indirectly - via a third party library) an outdated version of Font Awesome. 

Please make sure that you are using FA >= 5.15.4

Ref: https://github.com/FortAwesome/Font-Awesome/issues/18171#issuecomment-899420582
