### ISSUE TITLE
Icon request: expand-long, expand-short

### ISSUE THREAD

**Issue by jacobg** [FortAwesome/Font-Awesome#14117]
### What can it be used for?

open/close a directory tree, open/close a set of accordion fieldsets

### Example image (optional)

Taken from IntelliJ:
<img width="25" alt="screen shot 2018-10-15 at 10 09 55 am" src="https://user-images.githubusercontent.com/736985/46958686-68e7d480-d068-11e8-8b27-b9e2e5e088ca.png">

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
