### ISSUE TITLE
Icon request: fa-floorball

### ISSUE THREAD

**Issue by tinu88** [FortAwesome/Font-Awesome#14112]
Hi.

It would be create if there can be an icon with a floorball. I prefer floorball, so I can't user der soccer and basketball-icon:)

Thank you for check.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
