### ISSUE TITLE
Icon request: fa-map-marker-alt-plus

### ISSUE THREAD

**Issue by jojo12** [FortAwesome/Font-Awesome#14115]
for our extension events on locations we would need an "add new location" icon. If the location is just in the table, we can use "location". But if there is a new place to add, we don't have a fontawesome icon

it is parallel as "calendar-plus" to add a new eventdate

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
