### ISSUE TITLE
icon request: icon reorder with angles

### ISSUE THREAD

**Issue by jbranc** [FortAwesome/Font-Awesome#1412]
The new set of icon-angle-\* are great for the popular thin/minimalist desigs and look great alongside light and ultralight fonts.

Would it be possible to get a version of icon-reorder that uses these thin icon-angle-up and icon-angle-down?

thanks!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
