### ISSUE TITLE
Icon request: race-track

### ISSUE THREAD

**Issue by samuelbuzin** [FortAwesome/Font-Awesome#14141]
### What can it be used for?

I want to have a better ui on a website. I list all of the race track for a endurance championship host on iRacing.com and want to put some icons. I already find the map-marked for the location of the track.

### Example image (optional)

Maybe something like this : 
![circuit_car_racing_track_race-512](https://user-images.githubusercontent.com/32632404/47253328-5d722000-d451-11e8-9ae2-69bf354a4ea5.png)
(from http://graphics8.info/pixabay/rphoto/race-circuit-icon.html)

### Icon request checklist

I find a "track" request but if I understand the issue it's for an other type of track (here for a race track)

Cheers o/

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
