### ISSUE TITLE
Icons to consider

### ISSUE THREAD

**Issue by mtsweir** [FortAwesome/Font-Awesome#14152]
I have a client who is converting from Bootstrap 3 > 4, they were using a large set of BS glyph icons which I am now using your set to replace them. I did struggle here and there with a few and managed to find relevant replacements.

However, there were a few that I couldn't replace, mainly around audio icons. Attached are the ones I was unable to replace:

<img width="172" alt="screen shot 2018-10-22 at 12 45 14 pm" src="https://user-images.githubusercontent.com/4976660/47273874-b4662980-d5f8-11e8-8386-12467587a514.png">

<img width="496" alt="screen shot 2018-10-22 at 12 45 23 pm" src="https://user-images.githubusercontent.com/4976660/47273876-b4fec000-d5f8-11e8-9992-3ff782b442fc.png">

<img width="538" alt="screen shot 2018-10-22 at 12 45 32 pm" src="https://user-images.githubusercontent.com/4976660/47273877-b5975680-d5f8-11e8-9552-3bd35410a39b.png">

Not saying these should be in your set, but more just mentioning these ones as even tried Material Icons and didn't have much luck either.

**Comment by InsanityMeetsHH** [comment]
I made a [codepen](https://codepen.io/anon/pen/ePjMBo) for you.
May be you can use something from there.

**Comment by InsanityMeetsHH** [comment]
I made a [codepen](https://codepen.io/anon/pen/ePjMBo) for you.
May be you can use something of there.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
