### ISSUE TITLE
Crypto-DLT icons

### ISSUE THREAD

**Issue by studiosquash** [FortAwesome/Font-Awesome#14165]
Some icons related to the emerging crypto space are a must, specially for the developers working on decentralised apps. Terms like Blockchain, ledger, DLT, hash, crypto-currency, encryption, transaction, smart-contract and so on. Can be a category in itself.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
