### ISSUE TITLE
Donate icon does not show in chrome 70

### ISSUE THREAD

**Issue by paladox** [FortAwesome/Font-Awesome#14175]
Hi, the donate icon does not show in chrome 70 but does in safari, see bellow

chrome:

<img width="305" alt="screenshot 2018-10-26 at 01 05 33" src="https://user-images.githubusercontent.com/5727000/47537011-42713700-d8bb-11e8-8488-310b0b0d21a6.png">

Safari:

<img width="364" alt="screenshot 2018-10-26 at 01 05 59" src="https://user-images.githubusercontent.com/5727000/47537016-51f08000-d8bb-11e8-96f9-629448e74cf4.png">

This is the html code i use for the donate button:

```
<i class="far fa-donate"></i>
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, cannot replicate.

![image](https://user-images.githubusercontent.com/556268/47553523-a15c9d80-d907-11e8-9c84-6cea901d9345.png)

[far fa-donate](https://fontawesome.com/icons/donate?style=regular) is only available for Font Awesome Pro, so this issue should belong to the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Anyway, your icon looks like [fas fa-donate](https://fontawesome.com/icons/donate?style=solid) (filled-in dollar), so please make sure of the following:
- You are using Font Awesome >= 5.0.9
- You have a Pro License and you are entitled to use `far fa-donate`
- You have properly configured Font Awesome Pro (at the moment it isn't, 'cause it is showing its solid counterpart)
- There isn't a third-party plugin loading a version of Font Awesome older than 5.0.9, because this will generate random issues like yours (ref: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up)

Closing here
