### ISSUE TITLE
Icon request: Phage (Bacteriophage)

### ISSUE THREAD

**Issue by yonist** [FortAwesome/Font-Awesome#14186]
### What can it be used for?

For Biology information systems 

### Example image (optional)

![image](https://user-images.githubusercontent.com/499992/47617832-44faa900-dad4-11e8-99de-5f8f7e9b25f3.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
