### ISSUE TITLE
Icon request: a star with sharped edges

### ISSUE THREAD

**Issue by shaharlz** [FortAwesome/Font-Awesome#14196]
### What can it be used for?
rating

### Icon request checklist

- [pair - a star-filled / empty(bordered) ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to close this one because [we already have star icons](https://fontawesome.com/icons?d=gallery&q=star&c=interfaces&m=free) and sharp edges does not fit the look and feel of other icons in our sets

If you need a star with sharp edges, please consider another solution

Closing here
