### ISSUE TITLE
Whatsapp icon doesn't work on desktop

### ISSUE THREAD

**Issue by gabrielemaffoni** [FortAwesome/Font-Awesome#14192]
Hi, the whatsapp icon is not working on desktop. I tried typing unicode and copying and pasting from the website. The font is the right one (Fa-Brands), but it keeps showing me a square.

[screenshot 2018-10-29 at 16 37 12](https://user-images.githubusercontent.com/23501528/47665398-efd49b00-db98-11e8-90d3-02df02872138.png)

Any help?!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)
