### ISSUE TITLE
Icon request:  zero-icon / zero-slash

### ISSUE THREAD

**Issue by sreddypaknati** [FortAwesome/Font-Awesome#14206]
I have a Scenario like, when  i click on the toggle button, i can see all the labels of x axis bar chart including zero values also when i click on that toggle button it shoud hide the zero valued labels and shows lables which contains greater than 1.

Simply, it is a toggle with zero-icon / zero-slash icon.

Thank you :)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
