### ISSUE TITLE
Icon request: tumbleweed

### ISSUE THREAD

**Issue by o8e** [FortAwesome/Font-Awesome#14207]
> You have no billing history yet

Cue tumbleweed. For when you want to be a little more light hearted.

[Potential inspiration](https://image.flaticon.com/icons/png/128/1055/1055305.png)

**Comment by SteppingHat** [comment]
Yes, this please!

**Comment by aethior** [comment]
@tagliala `nature (category)` label for this request?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
