### ISSUE TITLE
Icon request: rat

### ISSUE THREAD

**Issue by Crissov** [FortAwesome/Font-Awesome#14247]
In order to fully support all local variants of Asian zodiac signs #5927, a Rat would be necessary.

🐀 U+1F400 #222

**Comment by aethior** [comment]
> 🐀 [U+1F400](https://emojipedia.org/rat/) #222

Also known as `Rodent`.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/mouse-field?f=classic&s=solid)
