### ISSUE TITLE
Icon request: city service fleet vehicles

### ISSUE THREAD

**Issue by JesseGIS** [FortAwesome/Font-Awesome#14244]
I would love to see some icons representing various city service vehicles such as: snow plow trucks, street sweepers, mowers, tow trucks, leaf pickup, garbage trucks.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

If you are a Font Awesome Pro user, you can request icon sets at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

**Comment by JesseGIS** [comment]
Sorry for the inconvenience, I should have read the guidelines first.  Quick question...would you prefer I submit a request individually for each icon or should I put them all in one request?

**Comment by tagliala** [comment]
>  Quick question...would you prefer I submit a request individually for each icon or should I put them all in one request?

in the free repository please adhere to the contributing guidelines (1 icon per request or matched pair)

In the pro repository, you can request a set
