### ISSUE TITLE
Icon Request: icon-remove-sign-alt

### ISSUE THREAD

**Issue by RabidPuffin** [FortAwesome/Font-Awesome#1426]
It'd be awesome to have the remove sign in box form, like you've been building out other items like the edit, plus, and minus…

I know that it can be done with stacking but I miss the transparency the others afford.

Thanks!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
