### ISSUE TITLE
Icon request: racoon

### ISSUE THREAD

**Issue by dudetj** [FortAwesome/Font-Awesome#14266]
### What can it be used for?

Our use case would be to link to Animal Control issues in a big city.

### Example image (optional)

![159737-200](https://user-images.githubusercontent.com/22713161/48362911-b27d0c80-e672-11e8-9809-a8a7c2bf0a86.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by Crissov** [comment]
Related Unicode emoji #222:

- [🦝](http://emojipedia.org/raccoon/) U+1F99D Raccoon

**Comment by josephofiowa** [comment]
Popping in to say I absolutely support a font awesome raccoon.

**Comment by 20jasper** [comment]
We need font awesome racoon

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/raccoon?f=classic&s=solid)
