### ISSUE TITLE
Icon request: icon-banks-brazil

### ISSUE THREAD

**Issue by 083digital** [FortAwesome/Font-Awesome#14299]
### What can it be used for?

I need the icons of the main Brazilian banks. (bank of brazil, bradesco, itau, etc)
I also need some platforms like pagseguro, asaas.

### Example image (optional)

bradesco: http://prntscr.com/lkgd29
banco do brasil: http://prntscr.com/lkgcwn
caixa: http://prntscr.com/lkgct2
itau: http://prntscr.com/lkgcoa
santander: http://prntscr.com/lkgcmg
citibank: http://prntscr.com/lkgcd1
pagseguro: http://prntscr.com/lkgc8v
asaas: http://prntscr.com/lkgc5g

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)
