### ISSUE TITLE
Icon request: triathlon

### ISSUE THREAD

**Issue by mshovelt** [FortAwesome/Font-Awesome#14304]
I know we already have icons for the individual sports (running, cycling, swimming) but it would be good to get a triathlon icon if possible.

**Comment by georgeboot** [comment]
Example image:

![Triathlon](https://static.thenounproject.com/png/533273-200.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
