### ISSUE TITLE
Icon request: Poker Planning Icons

### ISSUE THREAD

**Issue by jpierront** [FortAwesome/Font-Awesome#14318]
### What can it be used for?

It could be used as a "task complexity" following the "poker planning" standard. (0, 1/2, 1, 2, 3, 5, 8, 13, 20, 40, 100, Infinity, ?)

If you don't want to do so much variation of an icon, a single icon of a playing card will do the job.

### Example image (optional)

![planning-poker-cards](https://user-images.githubusercontent.com/1228441/48985694-85b50480-f10a-11e8-86b6-7b5675614962.png)

![playing-card](https://user-images.githubusercontent.com/1228441/48985791-2c4dd500-f10c-11e8-8222-92001d22da7b.jpg)

### Icon request checklist

- [x] This is multiple icons (Or a single icon at worst)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please fix this request and make sure it follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)?

**Comment by jpierront** [comment]
@tagliala Sorry, it's done.

If the 13 icons pack idea is rejected (Poker planning), the single icon version (Single card) is already requested here: https://github.com/FortAwesome/Font-Awesome/issues/2101

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
