### ISSUE TITLE
Icon request: icon-palm-oil

### ISSUE THREAD

**Issue by joshmoto** [FortAwesome/Font-Awesome#14322]
### What can it be used for?

Well it can used on sites that have to state that their product is palm oil free or contains palm oil.

It can use in conjunction with `fa-ban` to say its free.

### Example image (optional)

Theres are ton of stuff on google images https://www.google.co.uk/search?q=palm+oil+free

I'm sure you guys can figure something cool out. Maybe the leaf pattern which is quite distinctive.

Anyway food for thought, I think we owe it to the creatures of the jungle.

**Comment by InsanityMeetsHH** [comment]
Made with layers and / or stack: https://codepen.io/anon/pen/JeadJd
I chose `fa-tint` as symbol for the oil.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could this be considered a combination of #7640 and `fa-ban`, such as *fa-palm-ban* ?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
