### ISSUE TITLE
Icon request: search-heart

### ISSUE THREAD

**Issue by jessim67** [FortAwesome/Font-Awesome#14325]
### What can it be used for?

Can be used to search among a list of favorites, or i would like to use it in my charity application to search for a particular charity.

### Example image (optional)

The same as the search or the search-plus icon, but with a heart in the center of the magnifying glass.

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by InsanityMeetsHH** [comment]
Made with layers: https://codepen.io/anon/pen/xQJeGJ

**Comment by jessim67** [comment]
i didn't know you could do this, thank you!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
