### ISSUE TITLE
Icon request: icon-washing-care-icons

### ISSUE THREAD

**Issue by baselineshift** [FortAwesome/Font-Awesome#14336]
A series of icons to show laundry care.

![care_icons](https://user-images.githubusercontent.com/6177254/49290952-69192380-f4a0-11e8-8b56-03c6f87d0818.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately I cannot keep this open because it doesn't meet our [contributing guidelines for new icon requests](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

If you are a Pro user, you can request icon sets in the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
