### ISSUE TITLE
Icon pack Request: fitness

### ISSUE THREAD

**Issue by tclarkson7** [FortAwesome/Font-Awesome#14341]
A set of icons in a pack, dedicated to health and fitness, that could include things such as walking, swimming, weights, weight lifting and more.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately I cannot keep this open because it doesn't meet our [contributing guidelines for new icon requests](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

If you are a Pro user, you can request icon sets in the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
