### ISSUE TITLE
Icon request: value-proposition-canvas

### ISSUE THREAD

**Issue by BroosB** [FortAwesome/Font-Awesome#14356]
### What can it be used for?

To represent the value proposition canvas. Just like the business model canvas this is used in business worldwide the describe value propositions, the combination of your customer's jobs, pains and gains (the customer profile) and your products/services, pain relievers and gain creators (value map). More information here: https://youtu.be/ReM1uqmVfP0. 
The icon can be used in all kinds of business applications, such as business plans, dashboards, apps etc.

### Example image (optional)

![image](https://user-images.githubusercontent.com/25501633/49451223-fdf08980-f7de-11e8-833c-6a5ebccd487b.png)
or
![image](https://user-images.githubusercontent.com/25501633/49451276-21b3cf80-f7df-11e8-8a77-32119b803be9.png)

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
