### ISSUE TITLE
Icon request: icon group for industry

### ISSUE THREAD

**Issue by rr-appadaptive** [FortAwesome/Font-Awesome#14393]
### What can it be used for?

Industry 4.0 is one of the essential aspects of digitization whereas web-applications are by far the fastest growing part of this aspect and ...

Fontawesome is a key-player for the digital world and offers a bunch of icons but ...

... has no icon-group for Industry.
... has several icons for "santa-claus" but none for "machine", "cnc-machine", "machine-tool", "nc-program" and so on.

To cut a long story short: It would be more than great if fontawesome could be the icon-supplier for Industry 4.0 applications as well.

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately I cannot keep this open because it doesn't meet our [contributing guidelines for new icon requests](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

If you are a Pro user, you can request icon sets in the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
