### ISSUE TITLE
Throwing err during npm install 

### ISSUE THREAD

**Issue by aniket-jogal** [FortAwesome/Font-Awesome#14406]
hi there,

i'm using font Awesome pro 5.5.0 version. whenever trying to do npm install it is throwing err that 

"npm ERR! code E401
npm ERR! 401 Unauthorized: @fortawesome/pro-light-svg-icons@5.5.0"

and

"npm ERR! code E401
npm ERR! 401 Unauthorized: @fortawesome/fontawesome-common-types@0.2.8"

need solution for this.
as we are using font awesome for our  4 projects and there is same err for every project.

![font awesome err](https://user-images.githubusercontent.com/22929688/50040831-efbd2b80-0070-11e9-92be-b99b4f417183.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Since this issue is related to Font Awesome Pro, it should belong to the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro
If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Anyway, please check that your npm configuration is fine, you should add your token to your .npmrc file. Follow the guide at https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers

If you still have problems, please open a new issue in the pro repository providing all the information you can.

Hope it helps

Closing here
