### ISSUE TITLE
Bug: fa-google-plus (fab) doesnt stack well with fa-circle

### ISSUE THREAD

**Issue by My1** [FortAwesome/Font-Awesome#14400]
### Describe the problem

Stacking fa-google-plus (fab) with any version of fa-circle leads to them being vertically offset from each other

### What did you expect?

them lining up perfectly

### What version and implementation are you using?

Version: 5.6.1
Browser and version: Chrome 70, 71

**Web Fonts with CSS**

### Reproducible test case

https://codepen.io/My1/pen/VVJOXp

### Bug report checklist

- I have filled out as much of the above information as I can
- I have included a test case because my odds go _way_ up that the team can fix this when I do
- I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi My1,

could you please clarify the issue to me?

![image](https://user-images.githubusercontent.com/556268/49933866-1e020600-fecd-11e8-96ca-00496b64396d.png)

What is wrong with those icons?

**Comment by My1** [comment]
![image](https://user-images.githubusercontent.com/6696524/49933981-733e1780-fecd-11e8-92fb-079051f39fbb.png)

**Comment by tagliala** [comment]
@My1 Ok, I was able to replicate on Windows 10. Does not happen on macOS 11

**Comment by My1** [comment]
also apparently doesnt happen on android.

**Comment by My1** [comment]
what other feedback would be needed?

**Comment by tagliala** [comment]
Ok, thanks.

So svgs are not exactly the same:
https://github.com/FortAwesome/Font-Awesome/blob/master/svgs/solid/circle.svg
https://github.com/FortAwesome/Font-Awesome/blob/master/svgs/brands/google-plus.svg

The problem here is that we include brand icons "as they are": we do not expect that `google-plus` plays well with `fa-circle`, even if the brand comes inside a circle. Don't know if it is the case, let's see!

Anyway, let's assign @talbs so he will eventually take a look

**Comment by My1** [comment]
but then why is this only a thing on windows?

as far as it looks to me they are pretty much the same except for a little bit of space.

**Comment by tagliala** [comment]
The circle in brand icons is slightly different from the one of other icons, I think because brands do not follow the same 16 unit grid as the other styles.

- https://github.com/FortAwesome/Font-Awesome/blob/master/svgs/solid/circle.svg
- https://github.com/FortAwesome/Font-Awesome/blob/master/svgs/brands/google-plus.svg
- https://github.com/FortAwesome/Font-Awesome/blob/master/svgs/brands/adn.svg
- https://github.com/FortAwesome/Font-Awesome/blob/master/svgs/brands/bandcamp.svg

I'm going to assign @sensibleworld, maybe he can take a look and clarify

**Comment by sensibleworld** [comment]
Thanks, @tagliala. Looks like the issue may be related to artboard size. Our standard circle icon has a viewbox of 512 x 512 pixels. The icon art itself is actually 496 x 496 pixels. The G+ icon, however has a viewbox of 496 x 512 pixels.

I'll get a fix out for the G+ icon to address this. May need to do so on some other brand icons as well.

**Comment by bradshroyer** [comment]
Why not just remove? Google+ is dead: https://support.google.com/plus/answer/9217723?hl=en

**Comment by tagliala** [comment]
@bradshroyer that's a good point. We are preserving some icons for historical reasons and to avoid breaking backward compatibility. I hope that with version 6 we can remove some dead brands

**Comment by tagliala** [comment]
Confirm fixed in 5.13.1

![image](https://user-images.githubusercontent.com/556268/85182011-bbd74d80-b287-11ea-88a6-04f3c8a209a8.png)
