### ISSUE TITLE
Icon request: rotate-clockwise, rotate-clockwise-alt, rotate-counterclockwise, rotate-counterclockwise-alt

### ISSUE THREAD

**Issue by devou33** [FortAwesome/Font-Awesome#14417]
### What can it be used for?
Icon indicates that an object can be rotated either clockwise or counterclockwise.

**NOTE: Needs to be used in conjunction with undo/redo.** I know that is why this has been rejected in the past, but It would be in the same toolbar so it's similar but different with a hashed line instead of solid (or other ideas below).

### Example image (optional)
![screen shot 2018-12-18 at 4 49 48 pm](https://user-images.githubusercontent.com/7987602/50187905-492d9080-02e5-11e9-8770-3fc2991b52e5.png)

### Icon request checklist

- [✓] This is a matched pair (Ex: `lock` / `unlock`)
- [✓] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [✓] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [✓] I have included at least one example image if it could be helpful (optional)
- [✓] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/search?q=arrow-rotate&o=r&s=solid)
