### ISSUE TITLE
Icon Request: F-Type Mandolin

### ISSUE THREAD

**Issue by blackbret94** [FortAwesome/Font-Awesome#14427]
Font awesome current offers 3 mandolin icons but all represent A-type mandolins.  I would like a much more prestigious F-type mandolin represented.  I cannot afford an F-type mandolin in real life but I have higher standards for my website.

I have a website that involves Mandolin and I would love to use mando/guitar/banjo iconography on here. http://bretblack.com/tab-transpose/

Thanks!
- Bret

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Just to clarify for other people: 3 mandolin icons = 1 "guitar" icon in three stiles (solid, regular, light)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
