### ISSUE TITLE
Icon-request: icon-adjust-screen

### ISSUE THREAD

**Issue by yhojann-cl** [FortAwesome/Font-Awesome#1443]
Please, make an icon for adjust screen and new item.
It need for picture editor: zoom in (ok), zoom out (ok), adjust (fail), flip (use icon-rotate-left and right), new template (fail, use icon-plus, need asteric icon please).

Thanks.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
