### ISSUE TITLE
Icon request: vartical-bars (audio bars)

### ISSUE THREAD

**Issue by chezzzer** [FortAwesome/Font-Awesome#14440]
### What can it be used for?

Playing Audio

### Example image (optional)

![image](https://americanwarriorradio.com/wp-content/uploads/2018/02/animated-sound-bars.gif)

`its there its just white`

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Do
- https://fontawesome.com/icons/signal?style=solid
- https://fontawesome.com/icons/chart-bar?style=solid

fit your use case?

**Comment by ChezzerYT** [comment]
I want a random one, like audio is playing not audio connection status

**Comment by aethior** [comment]
Hi @chezzzer,

Something like [fa-waveform-lines](https://fontawesome.com/icons/waveform-lines) icon?

Regards.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome! [Take a look at it here.](https://fontawesome.com/icons/chart-simple?f=classic&s=solid)
