### ISSUE TITLE
Icon request: cog-slash

### ISSUE THREAD

**Issue by ecadagiani** [FortAwesome/Font-Awesome#14457]
### What can it be used for?
When you want a button to override automatic system, is a single icon (simple cog exist already, but you can make cogs-slash and cog-slash). The slash is like icon "comment" vs "comment-slash"

### Icon request checklist

- [x] This is a single icon ( but you can make variant with cogs-slash and cog-slash).
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve this icon with the layering and masking features of the SVG framework:

http://jsfiddle.net/tagliala/u4h19ecy/

**Comment by Crousticraft** [comment]
Thanks a lot for your response and your jsFiddle, it would be great to have a special icon, it could simplify the code.
For now I'm going to use your jsFiddle

And... Happy New Year ;)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
