### ISSUE TITLE
Icon request: fa-car-seat-heater

### ISSUE THREAD

**Issue by mseminatore** [FortAwesome/Font-Awesome#14471]
### What can it be used for?

Display car seat heater

### Example image (optional)

![image](https://user-images.githubusercontent.com/16830648/50710856-07a91f00-1021-11e9-9460-6a6ad3c4bae2.png)

### Icon request checklist

- [Yes ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ Yes] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [Yes ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [Yes] I have included at least one example image if it could be helpful (optional)
- [Yes ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by mseminatore** [comment]
@tagliala seems like this should be in **transportation icons** and not web apps.

**Comment by tagliala** [comment]
@mseminatore thanks for the heads-up. I've changed the label to the proper category

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
