### ISSUE TITLE
2 Icons not displaying correctly

### ISSUE THREAD

**Issue by ApertureDevelopment** [FortAwesome/Font-Awesome#14507]
### Describe the problem

2 Icons have a additional / breaking outline inside / on them

### What did you expect?

Displaying the TeamSpeak and Discord logo using FA- CSS

It should look like this: 
https://fontawesome.com/icons/discord?style=brands
and this:
https://fontawesome.com/icons/teamspeak?style=brands

How it does look:
![screenshot 677](https://user-images.githubusercontent.com/16450982/51281353-6c318a00-19e2-11e9-99fc-61590399b9b2.png)
![screenshot 679](https://user-images.githubusercontent.com/16450982/51281356-6e93e400-19e2-11e9-80f0-4010fd90ad7c.png)

### What version and implementation are you using?

Version: 5.6.3
Browser and version: Google Chrome 71.0.3578.98 

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

implement FA- CSS Free and use this code:
```html
<i class="fab fa-teamspeak"></i>
<i class="fab fa-discord"></i>
```

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This issue has been already reported once: #12865

#12865 is locked because it does not include a reproducible test case (and does not meet our contributing guidelines)

I'm still not able to reproduce this issue: https://jsfiddle.net/tagliala/5b9okq42/7/

Please check your stylesheet, the `font-weight` property applied to icons and anything else that may effect the rendering of the icon

**Comment by ApertureDevelopment** [comment]
I found it. I set a ``font-weight: bold;`` on the icons

**Comment by tagliala** [comment]
Glad you solved and thanks for having shared the solution
