### ISSUE TITLE
React- unicode

### ISSUE THREAD

**Issue by haileyylum** [FortAwesome/Font-Awesome#14514]
Hi,

Currently I working with React.js, I wish to replace the library Slick.js arrows to font awesome, but I tried to overwrite the unicode, font-weight and font-family like working in normal html,css but it does not comes out, anyone can give me a hand on this?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Are you going to use Font Awesome CSS or Font Awesome SVG?

Instructions for the CSS framework:
- https://fontawesome.com/start (select Free / All / Webfont and follow instructions)
- https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Instructions for SVG, with our official React component: 
- https://fontawesome.com/how-to-use/on-the-web/using-with/react

For your use case, I think you need to use the CSS framework, so you can take a look here: https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements#define

Anyway, please keep in mind that this is not a support forum. If you have questions on how to replace Slick.js with Font Awesome, please consider Stack Overflow (as per https://fontawesome.com/support#use-troubleshooting)

Otherwise, if you find issues in the docs or in Font Awesome itself, feel free to open a new request having care of filling out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

Hope it helps

Closing here
