### ISSUE TITLE
Icon request: datamatrixbarcode

### ISSUE THREAD

**Issue by danelson49** [FortAwesome/Font-Awesome#14513]
It would be great to have a datamatrix barcode icon added to the logistics pack. 1D barcodes are stale. 2D datamatrix barcodes are the future of barcode scanning in supply chain. 

![image](https://user-images.githubusercontent.com/46798236/51351701-d987fe00-1a68-11e9-89e7-1bc0fd389ebb.png)

**Comment by mtaylor091** [comment]
+1

I am a big fan of the logistics pack you provide and having this icon added would be awesome!

**Comment by danelson49** [comment]
tagliala could you please add the Logistics Pack tag to this new Icon request?

**Comment by tagliala** [comment]
@danelson49 thanks for the heads-up

**Comment by danelson49** [comment]
Thank you @tagliala!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
