### ISSUE TITLE
Icon request: guide-dog

### ISSUE THREAD

**Issue by erniomaldo** [FortAwesome/Font-Awesome#14521]
### What can it be used for?

The icon can be used as accesiblity friendly place, in my personal use case, i need to make known what vehicules are guide dog capable for better service.

### Example image (optional)

![22651617](https://user-images.githubusercontent.com/26859702/51410376-14059f80-1b2a-11e9-9308-da81abc5044d.jpg)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

Thanks!

**Comment by sensibleworld** [comment]
@erniomaldo Does this icon fit the bill, or are you thinking of something more specific? https://fontawesome.com/icons/dog-leashed?style=solid

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
