### ISSUE TITLE
Icon Request: money-slash

### ISSUE THREAD

**Issue by Larsmyrup** [FortAwesome/Font-Awesome#14534]
### What can it be used for?

I need an icon to show when something is free. Often in opposition to something that needs to be paid for.

### Example image (optional)

I have no example image, but believe one of the existing 'money' icons with a slash would be a great way to do this. @tagliala's answer, is exactly how i imagined it.

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by nickdnk** [comment]
+1 :)

**Comment by Larsmyrup** [comment]
Hi @tagliala!

You're right, that's a good workaround. However i use the desktop version cause i'm developing native Android. I'm not sure if the layering works there as well?

Thanks for the help though.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
