### ISSUE TITLE
Icon Request: brake and accelerator

### ISSUE THREAD

**Issue by PimoZi** [FortAwesome/Font-Awesome#14539]
when the project is about autodrive,they will work
![accelerator](https://user-images.githubusercontent.com/36178684/51588790-231c9100-1f20-11e9-89cf-b3a9f90a9a33.jpg)
![accelerator-o](https://user-images.githubusercontent.com/36178684/51588791-23b52780-1f20-11e9-922e-997c12ad176e.jpg)
![brake](https://user-images.githubusercontent.com/36178684/51588792-244dbe00-1f20-11e9-8c7f-f0619092ce7a.jpg)

**Comment by PimoZi** [comment]
when the project about autodrive，they will work

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Is this a request for one or two icons?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
