### ISSUE TITLE
Icon request: icon-trau-viet

### ISSUE THREAD

**Issue by trumvip** [FortAwesome/Font-Awesome#14538]
### Icon request checklist

- [x] This is a single icon or matched pair (trau-viet)
- [x] The title starts with "Icon request: icon-trau-viet" and is followed by the requested

 icon name (Icon request: icon-trau-viet)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

-- edit: attachment removed

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I've removed the attached .zip file.

Could you please add an inline example image ?

Please take a look at [this guide](https://guides.github.com/features/mastering-markdown/) if you have troubles in inserting images

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
