### ISSUE TITLE
Icon request: fa-flag-mx 🇲🇽

### ISSUE THREAD

**Issue by miguelpeniche** [FortAwesome/Font-Awesome#14541]
Several uses for global purposes. Remember: USA is not the only country in the world, flags of all world should be fair.

![1200px-flag_of_mexico svg](https://user-images.githubusercontent.com/3253845/51609396-a49fff00-1edf-11e9-8865-951c1033b1fd.png)

![1200px-flag_of_mexico svg-convertimage](https://user-images.githubusercontent.com/3253845/51609541-06606900-1ee0-11e9-9641-9da04a28a257.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, I have to close this one for the moment.

Ref: #4735, #10258, #6193, #1336, and others

> But there is a USA flag!

Yes, I know.

**Comment by tagliala** [comment]
Reopening here

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Comment by sensibleworld** [comment]
Just a quick note that we're moving all individual country-flag requests to a single open issue: https://github.com/FortAwesome/Font-Awesome/issues/20288
