### ISSUE TITLE
Icon request: hashtag-alt

### ISSUE THREAD

**Issue by talbs** [FortAwesome/Font-Awesome#14569]
### What can it be used for?

A few of our users have shared with us that they've used the `slack-hash` brand icon (https://fontawesome.com/icons/slack-hash) alongside our power transforms or custom CSS to produce an alternate hashtag icon. 

With https://github.com/FortAwesome/Font-Awesome/issues/14568 in the works, which removes that now non-official brand icon, we want to support having an alternate style of hashtag icon that satisfies the above anecdotal cases.

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
