### ISSUE TITLE
Icon request: icon-nose

### ISSUE THREAD

**Issue by mister-este** [FortAwesome/Font-Awesome#14578]
### What can it be used for?

A simple nose

### Example image (optional)

![Nose](https://cdn3.iconfinder.com/data/icons/medcare/512/nose-512.png)

**Comment by Crissov** [comment]
Related Unicode emoji: #222

- [👃 U+1F443](http://emojipedia.org/nose/)

**Comment by avilao** [comment]
Would use it 👍

**Comment by dgaultiere** [comment]
+1

**Comment by aethior** [comment]
Hi @mister-este!

This icon was added in v6.2.1.
Check https://fontawesome.com/icons/nose

Regards.

cc/ @tagliala

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/nose?f=classic&s=solid)
