### ISSUE TITLE
Using font-awesome files in bower in the END PRODUCT 

### ISSUE THREAD

**Issue by bEnnAbEEL** [FortAwesome/Font-Awesome#14585]
I have a very serious question posted here regarding your article.
https://stackoverflow.com/questions/54469515/how-to-include-bower-components-files-css-js-from-any-framework-in-end-product

Can you please have a look and let help me out here.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Starting from version 5, we have official npm packages for both svg and css frameworks and we do not support bower anymore. Also, Font Awesome 4.7 is in EOL.

Anyway, [bower itself](https://github.com/bower/bower#bower---a-package-manager-for-the-web) [has been recommending yarn or npm](https://bower.io/blog/2017/how-to-migrate-away-from-bower/) for new projects.

The other packages you mentioned (jquery, owl carousel) are on npm and since you are starting a new project, I can suggest you to use yarn or npm instead of bower

Our documentation on how to use FA5 with npm/yarn: https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers

I hope that someone could help you on stackoverflow if you must use bower but I'm going to close here, sorry

**Comment by tagliala** [comment]
@bEnnAbEEL maybe this could help you: https://github.com/FortAwesome/Font-Awesome/pull/6227#issuecomment-141921117
