### ISSUE TITLE
Feature request: display icons without using any prefix at all

### ISSUE THREAD

**Issue by pierremacedo** [FortAwesome/Font-Awesome#14598]
When creating dynamic websites like Wordpress, we developers must limit the number of icons we make available in the theme because we're forced to use prefixes. See the following situation:

`<i class="fas fa-2x fa-<?php echo get_theme_mod('your_selected_icon'); ?>"`
It'll will work fine if the user selects an icon that uses the fas prefix, but what if a brand icon is selected? That's the problem. 

One could say output the entire tag for a certain icon. But we're talking about more than 2k icons and the only WP Customize framework that has a Font Awesome control (Kirki) outputs only the icon name.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We have an [official WordPress plugin](https://wordpress.org/plugins/font-awesome/)

Does that help?

**Comment by pierremacedo** [comment]
This plugin isn't helpful. We still have to use prefixes.

**Comment by pierremacedo** [comment]
In fact, Font Awesome 4 was perfect for this because the **fa** prefix was the only one required. I see the best option is to stick to the version 4.

**Comment by tagliala** [comment]
> because the fa prefix was the only one required.

We need different prefixes to differentiate between different font styles.

In example, if you want the same prefix for both `far` and `fas` icon, you have to find a workaround for icons which have both styles (eg: star, heart) because they will share the same unicode point (that was different in FA4)

If you want to implement a plugin with a single dropdown menu and share the maximum amount of code of your actual implementation, I would suggest to provide a database like

|icon name|icon class|
|----------|-----------|
|Twitter (Brand)|twitter fab|
|Heart (solid)|heart fas|
|Heart (regular)|heart far|

And change

```
<i class="fas fa-2x fa-<?php echo get_theme_mod('your_selected_icon'); ?>"
```

to

```
<i class="fa-2x fa-<?php echo get_theme_mod('your_selected_icon'); ?></i>"
```
