### ISSUE TITLE
Request: sign-blank (outlined)

### ISSUE THREAD

**Issue by ThiloL** [FortAwesome/Font-Awesome#1466]
I would need for http://fortawesome.github.io/Font-Awesome/icon/sign-blank/ a equvalent sized outlined box.
http://fortawesome.github.io/Font-Awesome/icon/check-empty/ is sized slightly different

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
