### ISSUE TITLE
Icon request: Heatmap

### ISSUE THREAD

**Issue by tschaka1904** [FortAwesome/Font-Awesome#14677]
### What can it be used for?

This icon would be used in the scientific sector.

### Example image (optional)

In the end, it would lead you to something like this: 
![Heatmap](https://i.stack.imgur.com/M9lU6.jpg/)

Maybe something like this: 
https://thenounproject.com/term/heat-map/1529250/

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
