### ISSUE TITLE
Icon request: graphic-equalizer

### ISSUE THREAD

**Issue by terryschwarz** [FortAwesome/Font-Awesome#14685]
sort of a dup #10852 but image to match google material ...

![image](https://user-images.githubusercontent.com/47600614/53345681-77ca7780-38e3-11e9-9b38-0c09c5dadf99.png)

In our case we are trying to shift away from google icons as awesome has more selections and google's images are inconsistent to awesome (typically in line thicknesses and arrow heads) . We used this image to indicate that there is a relationship between objects without being specific about the relationship so has nothing to do with audio (so so you suggestion of fa-sliders for #10852 would be inappropriate in our case).

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/waveform-lines?f=classic&s=solid)
