### ISSUE TITLE
Icon Request: Five New Baseball Player Icons

### ISSUE THREAD

**Issue by nklockwood** [FortAwesome/Font-Awesome#14693]
### Example image (optional) 
Swing - https://www.flaticon.com/free-icon/baseball_511710
Throw - https://www.flaticon.com/free-icon/baseball-player_511687
Catch - https://www.flaticon.com/free-icon/baseball-player_511689
Homerun - https://www.flaticon.com/free-icon/home-run_511708
Stretch - https://www.flaticon.com/free-icon/stretching_120513#term=stretching&page=1&position=15

### Icon request checklist

- [NO ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ Yes] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ Yes] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [Yes ] I have included at least one example image if it could be helpful (optional)
- [ Yes] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, but requests for icon sets are not allowed in the Free repository because they are hard to manage.

If you are a Font Awesome Pro backer, you can request for a set in the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro

If you are a Font Awesome Pro backer but you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Hope it helps

Closing here
