### ISSUE TITLE
Icon request: fa-video-question

### ISSUE THREAD

**Issue by N0RTHW00D** [FortAwesome/Font-Awesome#14707]
### What can it be used for?

Indicating to users that clicking on the icon will load a help video.

### Example image (optional)

This icon would be a mashup up fa-video with fa-question-square by placing the question mark inside the video icon.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please notice that you can achieve this icon by using layering, transform, and masking features of the SVG Framework

Demo: https://jsfiddle.net/tagliala/z12wdapb/41/

**Comment by N0RTHW00D** [comment]
That's awesome, thanks for the quick reply!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
