### ISSUE TITLE
Icon request: icon-area

### ISSUE THREAD

**Issue by atspzr07** [FortAwesome/Font-Awesome#14718]
### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide an example?

**Comment by atspzr07** [comment]
Sir, what example?

**Comment by tagliala** [comment]
An example of the icon you are requesting (please do not use email attachments, they don't work)

**Comment by atspzr07** [comment]
okke.sir
https://pngimage.net/wp-content/uploads/2018/05/area-icon-png.png
https://www.flaticon.com/free-icon/shape_715859#term=area&page=1&position=51

**Comment by tagliala** [comment]
@atspzr07 does https://fontawesome.com/icons/draw-polygon?style=solid fit your use case?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
