### ISSUE TITLE
Icon request: price-list-euro (book-euro-sign)

### ISSUE THREAD

**Issue by MaklaCof** [FortAwesome/Font-Awesome#14712]
### What can it be used for?

For price list.

### Example image (optional)

![image](https://user-images.githubusercontent.com/1589573/53804829-ccf03400-3f48-11e9-86ac-f208d61d5654.png)

![image](https://user-images.githubusercontent.com/1589573/53804872-ed1ff300-3f48-11e9-9fa3-f4bbdfc7af14.png)

Probably also with $ currency.

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We have a "price list" for dollar: https://fontawesome.com/icons/file-invoice-dollar?style=solid and since your design recalls that icon, I'm going to rename to `file-invoice-eur`

Your request is legit, but please notice that you can achieve both the above designs by using layering, transform, and masking features of the SVG Framework

Demo: https://jsfiddle.net/cw58n9e3/

Docs:
- https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
- https://fontawesome.com/how-to-use/on-the-web/styling/masking
- https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by MaklaCof** [comment]
@tagliala 
I would like to say that `file-invoice` is not the same as `price-list`. I am not sure if renaming the title was legitimate in this case.

`file-invoice` indicates invoice (usually `pdf`), but `price-list` indicates completely different thing. It could be used in:
- On every page where prices are mentioned. For example you sell doors, houses, software ... People often search for price link (and `price-list` icon would be more suitable then `file-invoice`)

**Comment by tagliala** [comment]
> I would like to say that file-invoice is not the same as price-list. I am not sure if renaming the title was legitimate in this case.

While I understand that the use case is different,

this icon

![image](https://user-images.githubusercontent.com/1589573/53804872-ed1ff300-3f48-11e9-9fa3-f4bbdfc7af14.png)

looks a lot like 

![image](https://user-images.githubusercontent.com/556268/53871691-084c3a80-3ffd-11e9-84ff-82ec63eac908.png)

(available at https://jsfiddle.net/tagliala/L17f528g/3/ - no transparency unfortunately).

I personally do not think that the folded top-right corner could change the meaning of this icon. 

Since we are trying to keep names and design consistent, I still think that a better name for this request  is `file-invoice-eur`

Of course, developers can use that icon to represent whatever they want (price lists, financial reports, invoices, etc.)

Said so, I would be happy to change my mind if you can further explain your thoughts

**Comment by MaklaCof** [comment]
But I though I already did:
- `file-invoice` is more or less used when generating invoice (`pdf` **file**).
- `price-list` is used when you want to list prices for specific product:
  - [link0](https://www.google.com/search?q=price+list&tbm=isch&source=hp&sa=X&ved=2ahUKEwi-m_qr8-3gAhXyyaYKHZqLBc4QsAR6BAgEEAE)
  - [link1](https://www.rtc-krvavec.si/en/planning-a-visit/price-list)
  - [link2](https://www.ntf.uni-lj.si/ntf/en/study/office/office-otgo/price-list/)

Maybe price-list is not the best choice of words. I mean an icon that would represent list of products with prices.  
Or better said catalogue prices.

It could be a book with all the products and there prices.

![image](https://user-images.githubusercontent.com/1589573/53896398-3e58e100-4034-11e9-8cf8-57100376c420.png)

I think this could be stacked (`book-alt` and `euro`) but I am using Angular, and It would be nice to have standalone icon. I allow the user to choose his own icons.

Even better would be a tool, where we could create new icons (with transitions) and receive SVG source. That would be awesome.

**Comment by tagliala** [comment]
Thanks, got that!

**Comment by nazbar** [comment]
![book-euro](https://user-images.githubusercontent.com/120754810/208193485-d7c825c9-4b42-4e12-bc7f-c488174c9945.svg)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Comment by tagliala** [comment]
Ref: #20294
