### ISSUE TITLE
icon request: icon-compress-vertically

### ISSUE THREAD

**Issue by jagadish1209** [FortAwesome/Font-Awesome#14722]

**Comment by jagadish1209** [comment]
We are suppose to expand a table cells content vertically, To do that we are suppose to show an icon.
please check below for your reference
https://thenounproject.com/term/pinch/230521/

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
