### ISSUE TITLE
Icon request: airbrush

### ISSUE THREAD

**Issue by tinkertailordesign** [FortAwesome/Font-Awesome#14728]
### What can it be used for?

This icon would be for the existing category of Design, or a new category of Art / Crafts / Hobby

### Example image (optional)

![image](https://user-images.githubusercontent.com/48409132/54085470-74e57300-4336-11e9-8a65-2436e36527ed.png)

### Icon request checklist

- Could be a matched pair (e.g. 'spraying' / 'not spraying')

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
