### ISSUE TITLE
Icon request: calendar-in, calendar-out

### ISSUE THREAD

**Issue by mogurimogu** [FortAwesome/Font-Awesome#14724]
### What can it be used for?
check-in and check-out for travel and hotels are very common today

### Icon request checklist

- [ ] calendar-in
- [ ] calendar-out

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide examples for the icons you are requesting?

**Comment by mogurimogu** [comment]
Hi,
Thanks for the answer!

Of course, here is an example:

![check-out](https://user-images.githubusercontent.com/40238711/54034778-0ed2e180-41b8-11e9-811a-8e5f3fa52659.png)
![check-in](https://user-images.githubusercontent.com/40238711/54034710-e3e88d80-41b7-11e9-8e8e-d5826c66c7f8.png)

**Comment by tagliala** [comment]
Thanks.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering feature of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/10/

Ref:
- https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
- https://fontawesome.com/how-to-use/on-the-web/styling/masking
- https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by mogurimogu** [comment]
Oooh great, thank you very much!
It is really awesome 😄

**Comment by carlbradwell17** [comment]
+1 for this request, as it duplicates #14745

**Comment by aethior** [comment]
@tagliala `time (category)` label for this request?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
