### ISSUE TITLE
fa-holly-berry not working

### ISSUE THREAD

**Issue by srangara** [FortAwesome/Font-Awesome#14731]
I can't get any of the holly berry icons to work (fas, far, fal).

**Comment by srangara** [comment]
Actually, add several holiday-related icons:
tree-christmas
christmas-tree
bells
star-christmas

I'm able to use many others, as seen here: https://bwmc.reposterous.com/

**Comment by InsanityMeetsHH** [comment]
I can see on your website that you have installed Font Awesome Pro 5.5.0 but you need at least Font Awesome Pro 5.6.0.
All your listed icons names (except christmas-tree which doesn't exist) are available since 5.6.
Example: https://fontawesome.com/icons/holly-berry?style=solid
Top right corner stands "Updated: Version 5.6.0"

**Comment by tagliala** [comment]
@InsanityMeetsHH thanks

@srangara please make sure that you are using Font Awesome Pro >= 5.6.0

**Comment by drinkingsouls** [comment]
I can't get the Xmas related icons to work either, specifically fa-holly-berry. Says on Font Awesome it's available on free version.
Using 5.15.4 from Font Awesome: https://use.fontawesome.com/releases/v5.15.4/css/all.css
I can see it's in the css but it doesn't show?

**Comment by tagliala** [comment]
Can you please provide a reproducible test case? Please make sure that you are using FA >= 5.6.0 (maybe that the CSS is up to date but the webfont isn't)

**Comment by CodelineRed** [comment]
Hey @drinkingsouls 
I made an example in [jsfiddle](https://jsfiddle.net/9df054L8/).
As you cann see, it works in FA 5.15.4
Maybe you don't use css class `fas`?
Have a nice day!
