### ISSUE TITLE
fa-linkedin-in isn't included

### ISSUE THREAD

**Issue by Studio384** [FortAwesome/Font-Awesome#14738]
The `fab fa-linkedin-in` icon is broken in the latest 5.7.2: https://fontawesome.com/icons/linkedin-in?style=brands.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Cannot replicate: https://jsfiddle.net/tagliala/1o7sevju/4/

This issue usually happens when there are third-party css rules that override font-weight or ad-blockers enabled.

If you still think there is an issue in Font Awesome, please edit the first post by filling out [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

Meanwhile, closing here

**Comment by Studio384** [comment]
![Annotation 2019-03-13 090839](https://user-images.githubusercontent.com/1693592/54262860-a301c780-456f-11e9-8f20-c5983e59bbd3.png)

It is literally not loading on the Font Awesome website and anywhere else I use it.

**Comment by tagliala** [comment]
@Studio384 as I mentioned before, I think it is a third-party extension related to ad-block or privacy

![image](https://user-images.githubusercontent.com/556268/54267274-3be91080-4579-11e9-99b4-bbb9c7dcfc39.png)

Pleas try in incognito mode / safe mode / with third-party extensions disabled
