### ISSUE TITLE
Icon request: Hair and makeup icon set

### ISSUE THREAD

**Issue by katiecs3** [FortAwesome/Font-Awesome#14741]
### What can it be used for?

Hair and makeup icon set (7 icons total): 
 • hair-style 
 • hair-color (hair dye brush)
 • eye-makeup (mascara brush)
 • lip-makeup (lip stick)
 • face-makeup (blush brush)
 • skin-care (lotion bottle)
 • special-effects (wand?)

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, but requests for set are not allowed in the Free repository because they are hard to manage.

If you are a Font Awesome Pro baker, you can open this issue in the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro

If you are a Font Awesome Pro backer and you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Hope it helps

Closing here

**Comment by katiecs3** [comment]
That link leads to a 404 page?
