### ISSUE TITLE
Icon request: fa-mona / fa-monacoin

### ISSUE THREAD

**Issue by tamaina** [FortAwesome/Font-Awesome#14755]
### What can it be used for?
Logo for [MonaCoin (MONA)](https://monacoin.org/), one of the major cryptocurrencies in Japan. 

### Example image (optional)
MonaCoin has two types of logomarks.
One of them is the design of "M" with two lines: https://drive.google.com/drive/u/0/folders/0B0ClK0uKFKIhUVdwNV9XbFpjY28
The other is the design of coin with "モナー (Monā)"'s face: https://monacoin.org/files/monacoinimg.zip

![mona](https://user-images.githubusercontent.com/7973572/54398240-952d7d00-46fc-11e9-9917-8caebc0e974b.png)
https://s3.arkjp.net/misskey/46b926fb-418b-4581-8535-87e766aceb69.svg

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
