### ISSUE TITLE
Icon request: fa-event

### ISSUE THREAD

**Issue by toriatchorus** [FortAwesome/Font-Awesome#14753]
### What can it be used for?
Promoting events, concerts, or performances. 

### Example image (optional)

![image](https://user-images.githubusercontent.com/48566979/54383061-9eb8d580-4667-11e9-9f82-e5a23078e8a5.png)
![image](https://user-images.githubusercontent.com/48566979/54383069-a4162000-4667-11e9-9b43-e649269a0bd8.png)
![image](https://user-images.githubusercontent.com/48566979/54383089-a9736a80-4667-11e9-8262-9164d0d508a1.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

https://fontawesome.com/icons/users-class?style=solid may fit this use case

Anyway, this request needs:
- a better name (event is too generic and may be represented by a calendar)
- simpler examples (suitable for 16px icon size).

Request at #153 (spotlight) may cover this use case

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
