### ISSUE TITLE
Icon request: row-height or height or size

### ISSUE THREAD

**Issue by jlitchfield** [FortAwesome/Font-Awesome#14750]
### What can it be used for?

It could be used to show display density for tables, etc. It could be a matched set; small medium large

### Example image (optional)

Similar to text-height, but for rows or other things with height, but mainly rows.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Any single color example?

**Comment by jlitchfield** [comment]
Hello!

Happy to be here!

By single color example do you mean an actual design?

**Comment by tagliala** [comment]
yes! an example of the icon you want to be added

**Comment by lyinglow** [comment]
![image](https://user-images.githubusercontent.com/12749776/59098302-cbebeb80-8917-11e9-9b63-339c878433cc.png)
Just like this would be very handy.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
