### ISSUE TITLE
Icon request: protein

### ISSUE THREAD

**Issue by matteoferla** [FortAwesome/Font-Awesome#14765]
### What can it be used for?

Proteins are the molecules encoded by DNA that do the reactions, give cells structure and cause disease when they go wrong.

An icon would be good for biochemistry/biomedical sites to show protein related things (structures, features, effects a genetic mutation have) when the fa-dna icon is already used (say for DNA-level details).

(Example of an interactive protein project I am working on: [https://ngl.matteoferla.com/markup](https://ngl.matteoferla.com/markup))

### Example image (optional)

SVG I made: [https://github.com/matteoferla/PyMOL-to-NGL-transpiler/blob/master/images/protein.svg](https://github.com/matteoferla/PyMOL-to-NGL-transpiler/blob/master/images/protein.svg)

### Icon request checklist

- [x] This is a single icon —but fa-dna would technically be it's match
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
@tagliala `medical / health (category)` label for this request?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
