### ISSUE TITLE
Icon request:  fa-flag-ni 🇳🇮

### ISSUE THREAD

**Issue by JackZeled0n** [FortAwesome/Font-Awesome#14763]
What can it be used for?

To include in websites and apps made in Nicaragua, for Programmers and Designers.

Example: 

https://thenounproject.com/search/?q=nicaragua&i=777568

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry but flags are out of scope at the moment

> ...but there is a USA flag!

Yes, I know.

Please consider an .svg based solution

Ref: #4735

Closing here

**Comment by tagliala** [comment]
Reopening here

**Comment by JackZeled0n** [comment]
> 
> 
> Reopening here

Thanks

**Comment by JackZeled0n** [comment]
How can I see the flag icon?

**Comment by tagliala** [comment]
@JackZeled0n the flag has not been implemented yet.

Please take a look at https://fontawesome.com/community/leaderboard/new#faqs if you need more information on how requests work

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Comment by sensibleworld** [comment]
Just a quick note that we're moving all individual country-flag requests to a single open issue: https://github.com/FortAwesome/Font-Awesome/issues/20288

**Comment by JackZeled0n** [comment]
Thanks @sensibleworld
