### ISSUE TITLE
Bug: fa-layers-text in React: Layered Text does not update

### ISSUE THREAD

**Issue by RELnemtzov** [FortAwesome/Font-Awesome#14768]
Using Font Awesome 5 and React 16.8 and trying to layer an icon with text using the methods detailed [here](https://www.npmjs.com/package/@fortawesome/react-fontawesome#advanced) and [here](https://fontawesome.com/how-to-use/on-the-web/styling/layering).

When the layered text gets updated dynamically, the layered text does not update.

In the below code sandbox, this issue can clearly be seen:

- The top layered icon was created using the above linked methods and should be how I would expect it to work, but the number inside does not update.

- The bottom icon works as expected with regards to updating, but clearly is not "layered" properly, with the `fa-layers-text` being the difference.

Reproduction:
https://codesandbox.io/s/9jroz2803p

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

FortAwesome/react-fontawesome#225 makes me think that this feature has not been implemented yet in react.

@robmadole any thoughts?

**Comment by robmadole** [comment]
@RELnemtzov the `@fortawesome/fontawesome` package which you are using is deprecated.

The new package is called `'@fortawesome/fontawesome-svg-core'`. However, you can't just simply switch to this package and have everything working. The example you list uses some features that are not compatible with React because of React's virtual DOM mechanism.

As @tagliala mentioned the layer text has not been implemented in the React library yet so you will not be able to use that feature until it is.
