### ISSUE TITLE
FontAwesome cause full postback on asp.net

### ISSUE THREAD

**Issue by DrViente** [FortAwesome/Font-Awesome#14773]
I Using the last versione of Fontawesome 4 in asp.net Web Forms, i've got some pages with UpdatePanel, when i click con a button that cause a server action if I click precisely on the icon the page goes on full postback instead of a normal partial postback. There is the possibility to solve that?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, I cannot help on this issue, but it doesn't look like related to Font Awesome but rather on events propagation. If you are able to provide a reproducible test case (with Font Awesome 5, since Font Awesome 4 is in EOL) filling out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md) I will take a look

Leaving this open for feedback from the community.

**Comment by DrViente** [comment]
Sorry, i don't understand
what do you mean by "event propagation"?

**Comment by tagliala** [comment]
https://medium.freecodecamp.org/a-simplified-explanation-of-event-propagation-in-javascript-f9de7961a06e

**Comment by DrViente** [comment]
I create a solution, i need to stop propagation on i tag and then simulate click, like that: 
` $('.fa').off('click').click(function (event) {
        event.stopPropagation();
        if (!(this.parentNode === null)) {
            this.parentNode.click();
        }
    });`

this works for normal button with runat server, but not for asp:LinkButton, any suggestion?

**Comment by DrViente** [comment]
I found the solution, the problem was of the updatepanel of asp.net

**Comment by tagliala** [comment]
Glad you've solved

**Comment by GamiDaga** [comment]
and the solutio is??? pls help xd
