### ISSUE TITLE
Icon request: file-invoice-dollar-plus-circle, file-invoice-dollar-minus-circle

### ISSUE THREAD

**Issue by felinuxsas** [FortAwesome/Font-Awesome#14786]
Usefult for an accounting software (web application)

![imagen](https://user-images.githubusercontent.com/9337043/54790507-60da2500-4c04-11e9-86c6-ff943de5d929.png)

![imagen](https://user-images.githubusercontent.com/9337043/54790511-65064280-4c04-11e9-9bc0-c5f95675baaf.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering feature of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/30/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by felinuxltda** [comment]
That's right when you use it manually but sometimes people store the name of an icon on a database table to generate menus with icons and texts  dynamically. Credit and debit notes are very used concepts on accounting apps. Thank you.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
