### ISSUE TITLE
Icon request: feed bag

### ISSUE THREAD

**Issue by amnocas** [FortAwesome/Font-Awesome#14826]
### What can it be used for?

As an icon for app or website  for topics related with fish feed, can also be applied for cattle and as an icon for grain.

### Example image (optional)

![image](https://user-images.githubusercontent.com/16328190/55072483-24cf1600-5083-11e9-9497-58a2c0be9586.png)

![image](https://user-images.githubusercontent.com/16328190/55072503-331d3200-5083-11e9-81c4-1b8956294801.png)

### Icon request checklist

- This is a single icon 
- Icon request: feed bag
- I have searched for existing issues (https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate. There are bags but shopping or lady bags not feed.
- I have included two example images if it could be helpful
- The request is for a concrete object

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
