### ISSUE TITLE
Icon request: fa-clock-exclamation-triangle

### ISSUE THREAD

**Issue by latricewilliams** [FortAwesome/Font-Awesome#14827]
### What can it be used for?

When showing a list of items where some of them can be expired, a quick visual indicator would be helpful.

### Example image (optional)
![expired_B-512](https://user-images.githubusercontent.com/37335808/55097909-328c9780-5093-11e9-9307-51d3e9f95322.png)

### Icon request checklist

- Single Icon
- I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- This could simply be a warning over the clock icon, or the clock icon showing time elapsed
- The request is for a concrete object

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering feature of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/39/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by latricewilliams** [comment]
I was unaware of the additional functionality available. Thats very helpful, thanks!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
