### ISSUE TITLE
fa-linkedin icon missing?

### ISSUE THREAD

**Issue by samazadi** [FortAwesome/Font-Awesome#14854]
Hello, when I try to import the linkedin icon it throws an error saying it doesnt exist:

import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faCode,
  faLinkedin
} from '@fortawesome/free-solid-svg-icons'
library.add(
  faCode,
  faLinkedin
)

Modules:

    "@fortawesome/fontawesome-svg-core": "^1.2.12",
    "@fortawesome/free-solid-svg-icons": "^5.6.3",
    "@fortawesome/react-fontawesome": "^0.1.4",

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

linked-in belongs to brand icons.

Please take a look at this section of the documentation: https://fontawesome.com/how-to-use/with-the-api/setup/importing-icons#icon-names

Hope it helps

Closing here, but feel free to comment

**Comment by eugenet12** [comment]
In case anyone else lands on this chain, the new link for documentation is: https://fontawesome.com/how-to-use/javascript-api/setup/importing-icons#packages

The linked-in icon is in the @fortawesome/free-brands-svg-icons package which you may need to install (e.g. npm install @fortawesome/free-brands-svg-icons).

**Comment by SaerwenLis** [comment]
I just installed this and the icon is missing, I get: "Attempted import error: 'faLinkedInIn' is not exported from '@fortawesome/free-brands-svg-icons' (imported as 'faLinkedInIn')."

The problem seems to be that when yo copy the import on the web is written like this: <FontAwesomeIcon icon={faLinkedInIn} /> but in the package the name is faLinkedinIn

**Comment by tagliala** [comment]
Hi @SaerwenLis, can you clarify this issue?

**Comment by SaerwenLis** [comment]
Oh sorry, the individual Import for react on the web is written with an i capital letter, like this icon={faLinkedInIn} (faLinkedInIn) but the actual icon on the package is with i lower case like this faLinkedinIn so the import won't work unless you manually change it, sorry it's such a minor issue but I expend quite a time on it because I'm a begginer...

**Comment by tagliala** [comment]
> the individual Import for react on the web is written with an i capital letter,

Thanks for the clarification, I've managed to find it. Will open a separate issue

**Comment by briannasharpe** [comment]
Hello!!

Been struggling with this issue as well, here are a few other instances where the doc snippets for individual imports are not matching what's actually accepted:

```
faLinkedIn → faLinkedin
faHTML5Logo → faHtml5
faAlternateCSS3Logo → faCss3Alt
faJavaScript(JS)Square → faSquareJs
```
(doc import → accepted import)

**Comment by tagliala** [comment]
@briannasharpe thanks for the report. I've opened a new issue at FortAwesome/fontawesome#3033

**Comment by MuluKidan** [comment]
> fontawesome#3033

Hi, Exactly where can I make the change?
