### ISSUE TITLE
Icon request: case-sensitive case-insensitive

### ISSUE THREAD

**Issue by GerritDeMeulder** [FortAwesome/Font-Awesome#14860]
### What can it be used for?

Toggle a  search between case-sensitive and case insensitive

### Example texts  (not an image, but since this about text, I think it fits)

case-sensitive:  A≠a 
case insensitive:  A=a 

### Icon request checklist

- [X] This is a matched pair 
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
-> extended version, because others only ask for case sensitivity 
and those requests are not closed
- [X] I have included at least one example (text )
- [X] The request is for a concrete object

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
