### ISSUE TITLE
Icon request: user-chat

### ISSUE THREAD

**Issue by seabass86** [FortAwesome/Font-Awesome#14887]
### What can it be used for?

Single icon to display a user chat. Based on user-md-chat, just without the md device over the user's shoulder.

### Example image (optional)

Icon user-md-chat, just without medical device

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve this icon in Font Awesome Pro with the power transforms, masking, and layering feature of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/we7gtcvk/31/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by seabass86** [comment]
Oh thanks for pointing the power transform out to me! That helps!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
