### ISSUE TITLE
Icon Issue: fa-megaport

### ISSUE THREAD

**Issue by GoblinTimes** [FortAwesome/Font-Awesome#14900]
When I attempt to use fa-megaport if only shows a square, the icon does not render.

Example, the fa-coins show just fine but the fa-megaport is just a square

![Imgur](https://i.imgur.com/QnSOHcJ.png)

**Comment by nothingrandom** [comment]
Are you using the `fab` class or the `fa` class? `fa-megaport` is part of the brands icon pack, so you need to use `<i class="fab fa-megaport"></i>`

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

@GoblinTimes as @nothingrandom said, please make sure that your markup is correct

Also, please double check that you are using Font Awesome >= 5.1.0, because `megaport` has been implemented in that version

Ref:
- https://fontawesome.com/icons/megaport?style=brands
- https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here but feel free to comment
