### ISSUE TITLE
FA desktop on mac - doesnt recognise icons having "-"

### ISSUE THREAD

**Issue by smejky** [FortAwesome/Font-Awesome#14913]
when i write down i.e. "user", it converts to the user icon, but when i want to write down "user-tie", it converts to the icon of user and "-tie" remains as a text. it happens also when i copy the text from website, so i'm sure that the dash is proper. this issue happens with all the icons having "-" in theirs names.

![Screenshot 2019-04-17 at 12 14 26](https://user-images.githubusercontent.com/745881/56280526-aa863480-610a-11e9-9e83-e8353a21f037.png)

mac os x mojave, font awesome todays download.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`user-tie` in regular style (the icon is showing the regular style, otherwise the user would be filled in as in [fas fa-user](https://fontawesome.com/icons/user?style=solid) is only part of Font Awesome Pro

My guess is that you are using Font Awesome 5 Free and you need [fas fa-user-tie](https://fontawesome.com/icons/user-tie?style=solid)

I can suggest you to make sure that you have selected **Solid** font style

I'm going to close here, but feel free to keep commenting

**Comment by smejky** [comment]
well, yeah solid font style works! thanks a lot! loving font-awesome!

maybe you can mention the solid font style [here](https://fontawesome.com/how-to-use/on-the-desktop/setup/getting-started) and [here](https://fontawesome.com/how-to-use/on-the-desktop/referencing-icons/using-ligatures), i think it will help lot of people.

**Comment by tagliala** [comment]
@smejky thanks for the feedback

@talbs I've read the doc and I agree with @smejky: selection of Solid style should be explicitly mentioned in the docs

Eg:

Between https://fontawesome.com/how-to-use/on-the-desktop/referencing-icons/using-ligatures#set-typeface and https://fontawesome.com/how-to-use/on-the-desktop/referencing-icons/using-ligatures#type-name, you can see the font style implicitly switching to solid

### 1 
![image](https://user-images.githubusercontent.com/556268/56293209-f7790380-6128-11e9-8387-17494b6cbde8.png)

### 2

![image](https://user-images.githubusercontent.com/556268/56293132-d2849080-6128-11e9-8cf2-bec322c439d2.png)
