### ISSUE TITLE
Icon request: icon-roofing

### ISSUE THREAD

**Issue by Nateamus** [FortAwesome/Font-Awesome#14924]
### What can it be used for?

I represent many construction companies and the absolutely delightful Font Awesome Pro series unfortunately has a derth of good construction icons. Roofing is the one I need most urgently.

### Example image (optional)

https://user-images.githubusercontent.com/33788381/56460636-eddae000-6362-11e9-867a-f56787ca6276.png)

### Icon request checklist

- [x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x ] I have included at least one example image if it could be helpful (optional)
- [x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by Nateamus** [comment]
Thank you all so much for your incredible work!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
