### ISSUE TITLE
Icon request: thermostat

### ISSUE THREAD

**Issue by Siege36** [FortAwesome/Font-Awesome#14935]
Thermostat: useful in home automation

similar to the thermostat here:
https://materialdesignicons.com/

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Does https://fontawesome.com/icons/tachometer-alt?style=solid fit your use case?

**Comment by Siege36** [comment]
I did look at that, but no not really. Less speedometer like, would really like something similar to the look of a nest or ecobee.
https://png.pngtree.com/svg/20151124/10ee5d229d.svg
https://www.ecobee.com/consumerportal/svg/overview/abouttile_ecobee3.93c02070.svg

**Comment by DavydeVries** [comment]
Thermostat icon of Tado° looks like this:
![Screenshot 2020-02-11 at 14 38 35](https://user-images.githubusercontent.com/7860305/74241369-3261ae80-4cdc-11ea-9b58-816d21d63da8.png)

But I guess that this issue needs more description/explanation what @Siege36 is looking for. Currently there are a lot of [temperature](https://fontawesome.com/icons?d=gallery&q=temperature) icons from the weather package release. So something like fa-thermometer-half in a device form kinda way, I guess?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
