### ISSUE TITLE
Icon of viber not work

### ISSUE THREAD

**Issue by kitsmol** [FortAwesome/Font-Awesome#14955]
### Describe the problem

Icon vibe not displayed on the site
![image](https://user-images.githubusercontent.com/50081332/56867332-a56b9400-69ec-11e9-8efa-910bbb9b9dd0.png)

### What version and implementation are you using?

Version: 
Browser and version: 

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Bug report checklist

- [ ] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

As I can see from the Instagram icon and from the syntax, you are using an old version of Font Awesome.

At the moment I cannot recall which version of Font Awesome are you using, but it is definitely < 4.7

Ref (instagram): https://fontawesome.com/v4.7.0/icon/instagram

Anyway... [fa-viber](https://fontawesome.com/icons/viber?style=brands) has been introduced in version 5.0.3, so please make sure that you are using Font Awesome >= 5.0.3. Also, please make sure that you are using the proper syntax `fab` instead of `fa`

Ref: https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

Last but not least, please keep in mind that third party libraries, plugins, themes, etc. may load an older version of Font Awesome.

Hope it helps

Closing here, but feel free to comment
