### ISSUE TITLE
Slow loading page for FontAwesome

### ISSUE THREAD

**Issue by fakhamatia** [FortAwesome/Font-Awesome#14960]
I use `all.min.js` FontAwesome in my site and it's load js file every time i enter the page or reload page.
My site place on local network and i can't use CDN because it's not connect to internet. 
I placed the script tag in bottom of body tag its right?
If i enable caching Apache on server side it's fix?

![Screenshot from 2019-04-30 18-32-37](https://user-images.githubusercontent.com/20030910/56967894-60c03400-6b77-11e9-90ea-76e0eca3fcae.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think this issue is not related to Font Awesome, but it is a generic question on how to properly cache assets on a website. Please take a look at stackoverflow

> I placed the script tag in bottom of body tag its right?

The position is fine

> If i enable caching Apache on server side it's fix?

Yes, it should fix. But I recommend to avoid long-term caching of static files without hash fingerprints.

E.g.: rename `all.min.js` to `all.5.8.1.min.js` and cache the latter

Ref:
- https://webpack.js.org/guides/caching/ 
- https://guides.rubyonrails.org/asset_pipeline.html#what-is-fingerprinting-and-why-should-i-care-questionmark

Closing here, but feel free to comment
