### ISSUE TITLE
Web font doesn't appear on Safari only with one domain name

### ISSUE THREAD

**Issue by Maxhou00** [FortAwesome/Font-Awesome#14963]
### Describe the problem

I cannot see the icon on Safari  with the domain name `mywebsite.com` instead I have a blank or an icon with write "no glyphe", but I can see them on every other browser like Firefox or Chrome even on safari IOS with the same domain name.

On my CDN I have register the following domain name `mywebsite.azurewebsites.net`. I don't think it's matter because it work on other browser

On `mywebsite.azurewebsites.net` it work with every browser even safari

>

### What did you expect?

I expect to see the icon same with Firefox and Chrome

### What version and implementation are you using?

Version: 5.8.1
Browser and version: Safari 12.1

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

I only have only copy/past the font between two `div` tag

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> On my CDN I have register the following domain name mywebsite.azurewebsites.net. I don't think it's matter because it work on other browser

Sorry, I didn't get this. Are we talking about Font Awesome Pro and whitelisted domains?

Could you please provide a link to the website or a reproducible test case?

**Comment by Maxhou00** [comment]
Yes it's about the whitelisted domains.

Here is the website:

**Comment by tagliala** [comment]
@Maxhou00 thanks.

I cannot replicate on my Safari, but I've noticed that the website is also loading Font Awesome 4.7.0

![image](https://user-images.githubusercontent.com/556268/57063727-742ce580-6cc4-11e9-85f8-c72a57e03b68.png)

Since it could cause issues, could you please try to remove it and try again?

PS: I would also suggest to make something about javascript files, the website is downloading 12 Mb of js

![image](https://user-images.githubusercontent.com/556268/57063702-611a1580-6cc4-11e9-99d9-cd8e025ef59a.png)
