### ISSUE TITLE
Icon request: eirin-g, eirin-pg12, eirin-r15, eirin-r18

### ISSUE THREAD

**Issue by kheldorn** [FortAwesome/Font-Awesome#14973]
### What can it be used for?

I'm looking for content rating icons, specifically for the japanese Eirin Rating used to classify movies into four categories.

The four categories being:
- G: General Audiences. All ages admitted.
- PG12 (PG-12): Parental Guidance Requested. Some material may be unsuitable for children under 12. Parents are advised to accompany their children during the film.
- R15+ (R-15): Restricted to teenagers 15 and over only. Children and teenagers under the age of 15 are banned from viewing the film.
- R18+ (R-18): Restricted to adults only. Children and teenagers under the age of 18 are banned from viewing the film.

See https://en.wikipedia.org/wiki/Eirin#Current_ratings_set for more details.

The icons would be used on a website like IMDB but with a focus on japanese animation, aka anime.

### Example image (optional)

Wikipedia has all 4 icons required ready in SVG format:
https://en.wikipedia.org/wiki/Eirin#/media/File:Eirin_Rated_G.svg
https://en.wikipedia.org/wiki/Eirin#/media/File:Eirin_Rated_PG12.svg
https://en.wikipedia.org/wiki/Eirin#/media/File:Eirin_Rated_R15%2B.svg
https://en.wikipedia.org/wiki/Eirin#/media/File:Eirin_Rated_R18%2B.svg

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
