### ISSUE TITLE
Icon request: webinar

### ISSUE THREAD

**Issue by Lizziebeth10** [FortAwesome/Font-Awesome#14980]
### What can it be used for?

Different from a video, might or might not have a person.  Screen-sharing. 

### Example image (optional)

![webinar-sample](https://user-images.githubusercontent.com/17460584/57158435-699c4a00-6db1-11e9-835d-2d38ea8961eb.png)

### Icon request checklist
Single icon best of my knowledge this is not a duplicate

**Comment by SiljaJ** [comment]
Any news on this? Icons for webinar/ videochat/ onlinemeetings would be very helpful in the current situation.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
