### ISSUE TITLE
icon-request: icon-cloud-shield

### ISSUE THREAD

**Issue by chris1000** [FortAwesome/Font-Awesome#14987]
Hello I was wondering if it would be possible to get an icon of a cloud with a shield overlaying it. I think this would be perfect (especially for my site) to convey a "secure cloud".

![cloud](https://user-images.githubusercontent.com/7182759/57197325-f3742080-6f33-11e9-829a-fd563dd26ae2.png)

Or maybe a cloud with a lock over it?

Thank you!!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering feature of the SVG Framework and Font Awesome Pro.

Demo: https://jsfiddle.net/tagliala/e1bfz6gc/28/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by chris1000** [comment]
Thank you so much for your quick response! That second solution for the free version worked perfectly, thank you so much!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
