### ISSUE TITLE
Icon request: icon-klarna-sofort

### ISSUE THREAD

**Issue by flohaun** [FortAwesome/Font-Awesome#14986]
### What can it be used for?

**Klarna is a big european payment provider. It includes the "Pay now" (=Sofort") Solution.**

### Example image (optional)

**Here you find all visual assets:** https://developers.klarna.com/resources/branding-visuals/merchant-assets/at/ 

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Since we have a request for:
- klarna: #4340;
- sofort: #9487; and
- klarna-sofort: (this one)

Could you please provide more information on why we need three separate requests?

**Comment by mansoorahmad** [comment]
@tagliala - Any idea when 'klarna-sofort' icons will be available? Thanks.

**Comment by tagliala** [comment]
No feedback, closing here

**Comment by gekkedev** [comment]
What the OP probably meant was that there are three separate logos. *Klarna* itself uses a peace sign (in a unique style). Often you will see this logo with the addition of the writing *Klarna.*:
![image](https://user-images.githubusercontent.com/17025257/104326536-1ff28500-54ea-11eb-9561-99b2ea26e28c.png)

Since they acquired *Sofort/Sofortüberweisung*, you may also encounter a designated logo for *Sofort* payments (subtitled with Sofort. instead):
![image](https://user-images.githubusercontent.com/17025257/104327657-4d8bfe00-54eb-11eb-9d87-558e75f7f7f1.png)

Seldomly you still encounter this hybrid (but this is surely not what OP requested):
![image](https://user-images.githubusercontent.com/17025257/104327713-5b418380-54eb-11eb-8607-a42679a7499c.png)

**Comment by tagliala** [comment]
@gekkedev thanks for the clarification

So this is the new logo of #4342 ?

**Comment by gekkedev** [comment]
@tagliala excuse my late reply; the hybrid versions I showed above cannot be found in their API/Branding docs anymore, even if you could probably still manage to find it on their CDN for compatibility reasons. This is because *Klarna* acquired the payment gateway *Sofortüberweisung* and created those hybrid logos shown above, where "Sofortüberweisung" became "Sofort", and finally the whole brand was eradicated. According to the styleguide, everything is supposed to say Klarna now and their different payment methods would be kept apart by simply adding localized text labels like "wire transfer" or "credit card" to it.
I believe of all three related Icon choices ([*Sofortüberweisung*](#4342), the hybrid version(s), and [Klarna](#4340)) #4342 is the oldest one (**should be closed IMHO**) and #4340 the newest one. Since the hybrid version likely had a shorter lifetime than the original, it should stay closed because supporting old icons would create dead weight to this beautiful icon set and could lead to the impression (for new implementations) that these icons are still recommendable to use.
#4340 is the one to add with the most use cases. :smiley:

**Comment by tagliala** [comment]
@gekkedev thanks, I've closed #4342 for the moment
