### ISSUE TITLE
telegram

### ISSUE THREAD

**Issue by rarfx** [FortAwesome/Font-Awesome#14988]
### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

telegram icon is available since Font Awesome 5.0.0

https://fontawesome.com/icons/telegram?style=brands
https://fontawesome.com/icons/telegram-plane?style=brands

Make sure that you are using the latest version of Font Awesome

Here it is an upgrade guide from v4: https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

Hope it helps

Closing here
