### ISSUE TITLE
Icon request: icon-carrot

### ISSUE THREAD

**Issue by stevschmid** [FortAwesome/Font-Awesome#1499]
We would like to display a carrot icon for vegetarian and vegan menus. The carrot icon could also be used to indicate vegetable content.

![ruebli](https://f.cloud.github.com/assets/2707380/754501/129d4b82-e58b-11e2-82eb-6d67c5e07ebc.png)

**Comment by tagliala** [comment]
Adding to 5.0.0 milestone via #1895

**Comment by G-Driver** [comment]
+1

**Comment by dfyx** [comment]
+1

**Comment by Crissov** [comment]
🥕 [U+1F955](http://emojipedia.org/carrot/) Carrot Unicode emoji #222

**Comment by cosydney** [comment]
I would use the carrot 🥕 to represent motivation 😂

**Comment by oriadam** [comment]
It is preferred to use the more widely used vegan icon, instead of a carrot:
http://images.sasongsmat.nu/vegetarianmark/vegetarian-mark.svg

**Comment by dfyx** [comment]
@oriadam As I explained in another issue, I need to have an icon for "vegetarian" in the same table as some green check marks so those would be too similar and easily confused, especially on small screens.

**Comment by oriadam** [comment]
@dfyx A carrot is both vegetarian, vegan, raw-vegan, healthy, and it looks close to the spicy symbol of a hot chilly. I think a carrot is a poor and confusing choice for a menu.
If you don't like the v mark, maybe   🙗  for vegetarian and  🙗🙗  for vegan, or any of these other other unicode symbols
## 🌿 🍃 💚❧❦🎔ⱱⱴ 

found at: http://www.amp-what.com/unicode/search/heart http://www.amp-what.com/unicode/search/leaf

**Comment by dfyx** [comment]
Yeah, those might work, thanks. It's amazing how much more useful those unicode emoji got in the last few years.

For some context there's also an old comment at https://github.com/FortAwesome/Font-Awesome/issues/6787#issuecomment-113561918. As mentioned I run a registration website for small community meetups where guests can select "with meat", "vegetarian" or "I'll bring my own food". The distinction between vegetarian and vegan is not too important for us because we don't offer "vegan" as a separate option (though the vegetarian meals might occasionally be vegan). With the one or two vegan guests out of about 50 to 70 in total, it's more convinient for everyone if they provide their own food.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/carrot?style=solid
