### ISSUE TITLE
Icon request: key-square, key-rectangle (generic keyboard keys)

### ISSUE THREAD

**Issue by dasprinzip** [FortAwesome/Font-Awesome#14991]
for doing manuals. press "windows and e" to open "windows file explorer". it's more or less like fa-circle. the empty key can then be combined with a letter or icon (with fa-group). i am only talking about the "empty" key itself (standard, wide)

https://s.smore.com/u/thumbs/thumb-b6c9d4eb7649eca67e4f73a1508a5129.png

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Does [square](https://fontawesome.com/icons/square?style=solid) fit your request for `key-standard` ?

Also, in Font Awesome Pro, there is [rectangle-widescape](https://fontawesome.com/icons/rectangle-landscape?style=solid) that could be slightly enlarged to fit the use case of `key-wide`

Demo: https://jsfiddle.net/tagliala/e1bfz6gc/37/

**Comment by dasprinzip** [comment]
Thank you for your suggestion and your workload. Of course it would be possible to do it in a way like this. But I thought that a "more like a key" button would look better. Maybe the horizontal lines should be a bit bent. Or the outline is normal and a second inner line is bent. The thinking about keys even generates more demands, such like icons for ctrl, alt, command, return, space, ... . But step-by-step. Maybe the keys themselves should be performed with standard css and without fontawesome. Otherwise maybe the font-awesome team have good ideas for keys and they see a need for it.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
