### ISSUE TITLE
Icon request: icon-carmaker-psa

### ISSUE THREAD

**Issue by psa-hub** [FortAwesome/Font-Awesome#15007]
### What can it be used for?

Carmakers brand logos - PSA Group (Peugeot, Citroën, DS Automobiles, Chevrolet, Opel, Vauxhall, Distrigo)
![psagroup](https://user-images.githubusercontent.com/50480567/57512294-90a3d000-730b-11e9-8624-5a0256961375.jpg)

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately I cannot keep this open because it doesn't meet our contributing guidelines for new icon requests

> ❌  This is a single icon or matched pair (Ex: lock / unlock)

If you are a Pro user, you can request icon sets in the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
