### ISSUE TITLE
Icon request: obstacle-run

### ISSUE THREAD

**Issue by georgeboot** [FortAwesome/Font-Awesome#15008]
### What can it be used for?
These days, there are a lot of obstacle runs around the world. FA provides icons for some sports, but nothing that comes close to an obstacle run.

### Example image (optional)
![Example obstacle-run icon](https://image.shutterstock.com/image-vector/black-silhouettes-people-overcoming-obstacle-260nw-1055404481.jpg)

![Example obstacle-run icon](https://us.123rf.com/450wm/elenabutus/elenabutus1804/elenabutus180400044/100311186-stock-vector-black-silhouette-of-a-man-jumping-over-the-wall-obstacle-race-symbol-vector-illustration-.jpg?ver=6)

![Example obstacle-run icon](https://us.123rf.com/450wm/elenabutus/elenabutus1805/elenabutus180500005/100847321-stock-vector-black-silhouette-of-athletic-man-overcoming-the-obstacle-obstacle-course-symbol-vector-illustration-.jpg?ver=6)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
