### ISSUE TITLE
For some users, not even the empty rectangles

### ISSUE THREAD

**Issue by DayKirby** [FortAwesome/Font-Awesome#15024]
I use regular and Pro versions, and I use it both through a CDN and not, and usually have no problems. Almost all users see the icons no problem, but I have at least one user who is not seeing the icons, and not even the empty rectangles (which I would expect if there was a loading issue). There is empty space where the icons would be, which expect is a clue. I've never seen this behavior before, any ideas? The users are in the same work environment (firewall?) and managed by the same IT group (browser settings?)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

>  There is empty space where the icons would be, which expect is a clue. I've never seen this behavior before, any ideas? The users are in the same work environment (firewall?) and managed by the same IT group (browser settings?)

Any chance the icons we are talking about are brands of social media, such as facebook, linkedin, twitter?

Anyway... it seems related to some user setting, but please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md) because we need more information to provide help

**Comment by DayKirby** [comment]
No, not brands. Basic things like arrows, help and warning symbols.

**Comment by DayKirby** [comment]
Template filled out
