### ISSUE TITLE
Icon Request: fa-company-card

### ISSUE THREAD

**Issue by HTMLGuyLLC** [FortAwesome/Font-Awesome#15029]
### What can it be used for?

Linking to a company's profile. I use fa-id-card currently for linking to user profiles. This would compliment it perfectly.

### Example image

![company-card](https://user-images.githubusercontent.com/2415447/57737418-a7cf1e80-7679-11e9-82a0-d6468a8e0e03.jpg)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
