### ISSUE TITLE
Icon request: icon-call-forward

### ISSUE THREAD

**Issue by savinayd** [FortAwesome/Font-Awesome#15053]
Can I get icon for. 
Call forward
Call Received
Dialed
Missed call
![Missed call](https://user-images.githubusercontent.com/50899300/58248530-fc5d5280-7d79-11e9-8f71-88e1eb37ab19.png)
![Completed Call](https://user-images.githubusercontent.com/50899300/58248533-fc5d5280-7d79-11e9-80ca-b92feab4b40a.png)
![Call forword](https://user-images.githubusercontent.com/50899300/58248543-01ba9d00-7d7a-11e9-8bad-d10c587126e0.png)
![Asset 102@25x](https://user-images.githubusercontent.com/50899300/58248544-01ba9d00-7d7a-11e9-85ba-3196d6f83972.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request contains some duplicates from #3701, fa-incoming-call, fa-outgoing-call, fa-missed-call, please +1 that request

Leaving this open as call-forward

Please [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/phone-arrow-right?f=classic&s=solid)
