### ISSUE TITLE
Icon request: share-ios-alt

### ISSUE THREAD

**Issue by drbarnard** [FortAwesome/Font-Awesome#15056]
### What can it be used for?

Sharing links, content, etc.

### Example image (optional)

We created this variation of the iOS share icon for Weather Up and would love to see it used in Font Awesome. It gives a similar feel to the iOS share icon without directly replicating it and IMO improving the aesthetics.

<img width="473" alt="Screen Shot 2019-05-23 at 10 00 05 AM" src="https://user-images.githubusercontent.com/10518871/58264273-3101e780-7d43-11e9-8d37-3983e81e7f17.png">

**Comment by tagliala** [comment]
Related to #10619, but not a duplicate

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome! [Take a look at it here.](https://fontawesome.com/icons/arrow-up-from-bracket?f=classic&s=solid)
