### ISSUE TITLE
Icon Request: Shield-Old

### ISSUE THREAD

**Issue by Chaboi45** [FortAwesome/Font-Awesome#15081]
I really ❤️ the old FA4 shield icon: https://fontawesome.com/v4.7.0/icon/shield, and want to use it in our FA5 site. Does anyone mind adding this FA4 shield icon with a name like `shield-old` to FA5? This addition will be greatly appreciated. :)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Does [shield-alt](https://fontawesome.com/icons/shield-alt?style=solid) fit your use case?

**Comment by Chaboi45** [comment]
That **was** our alternate solution for our website, but the old FA4 shield icon seems to fit better in our case.

**Comment by Chaboi45** [comment]
I think it's probably easy to implement it because the SVG file already exists.

**Comment by Chaboi45** [comment]
@tagliala, is this coming anytime soon?

**Comment by tagliala** [comment]
@Chaboi45 it is unlikely to come soon

Please take a look at https://fontawesome.com/community/leaderboard/new#faqs, there is a lot of information on how requests work

PS: there is a guide to customize the svg framework and the example contains instructions on how to add icons from FA4 https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome#svg-framework

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
