### ISSUE TITLE
Icon request: bitcoinz

### ISSUE THREAD

**Issue by cryptorex** [FortAwesome/Font-Awesome#15082]
### What can it be used for?

BitcoinZ is a crypto project based on the power of community and open source.  BTCZ has as self-sustaining payment gateway (https://pay.btcz.app/) and an icon would help web sites include the logo in their 'We Accept' sections as payments they accept.  Similar to cc-paypal, cc-mastercard, fa-bitcoin, fa-ethereum.

### Example image (optional)

https://en.wikipedia.org/wiki/File:Bitcoinz_logo_dark_250px.png#/media/File:Bitcoinz_logo_dark_250px.png

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
