### ISSUE TITLE
Sizing problem with exclamation icon

### ISSUE THREAD

**Issue by RSalgadoAtala** [FortAwesome/Font-Awesome#15090]
When using the exclamation icon (_fa-exclamation_) on an `<i>` element, the icon becomes huge, and covers most of the button and a significant portion of the window. I'm using Bootstrap, and the issue only occurs when the `<i>` element has the Bootstrap _pr-2_/_pl-2_ classes (or above, but the _pr-1_/_pl-1_ classes are not a problem). It doesn't happen with any other button that I've used so far (about 30).

Versions I'm using:

- Font-Awesome version 5.8.2, (SVG with JS implementation).
- jQuery version 3.3.1 (and jQuery Migrate 3.0.0).
- Bootstrap version 4.1.3.
- Google Chrome 74.

**Fiddle**: https://jsfiddle.net/xgvfs9a6/

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I can confirm this issue, and I also can confirm that it is not related to exlamation icon itself. In your case, any narrow icon will do the same (`fa-arrows-alt-v` and `pr-2`, for example)

Also, I think this issue is not strictly related to Font Awesome, it is rather an edge case of using `<svg>`, `box-sizing: border-box`, `padding`, `overflow: visible`, and `height: 1em`

I've reproduced the issue in plain html here: https://jsfiddle.net/tagliala/gkdvtqwj/29/

It appears that all the available space for the `svg` icon (`0.375rem`) is being swallowed up by the "huge" `padding`, so the icon has no horizontal space. `height: 1em` and `overflow: visible` do the rest.

As a fast workaround, if you can't refactor your code, I suggest you to apply `fa-fw` class to all icons, so you will be sure that icons will not be too narrow.

Let's ask @robmadole some thoughts about this

**Comment by robmadole** [comment]
Yeah I agree with @tagliala. That padding effectively ejects the icon. This needs to be refactored as Geremia suggests or implemented in another way. This is something that the SVG elements will do in this case.
