### ISSUE TITLE
Icon request: fa-calendar-bolt

### ISSUE THREAD

**Issue by janklever** [FortAwesome/Font-Awesome#15109]
**What can it be used for?**
Icon used for 'lightning' offers (offers available for a short period) or for seasonal periods.

**Example image**
![image](https://user-images.githubusercontent.com/1753966/58960016-a24a8d00-877c-11e9-9b42-f5798b1c038a.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering feature of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/92/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
