### ISSUE TITLE
图标搜不到

### ISSUE THREAD

**Issue by zhouyunfang** [FortAwesome/Font-Awesome#15100]
在搜索的时候有很多图标搜不到;不知道是没有还是怎么样;比如,订单,客服之类的

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, I do not speak Chinese.

As per google translate:

> There are a lot of icons that can't be found in the search; I don't know if it is still or not; for example, orders, customer service, etc.

Yes, that's true. Looking for "orders" or "customer service" the search is not going to provide results. We are costantly improving our search terms, so if we see a lot of searches for the above terms we will eventually add some related icons to those.

We prefer to use concrete objects to represent icons. Since "customer service" is an abstract concept, you can look instead for "user with headset", "headset", "life ring":
- https://fontawesome.com/icons/user-headset?style=solid (available in FA Pro)
- https://fontawesome.com/icons/headset?style=solid
- https://fontawesome.com/icons/life-ring?style=solid

"orders" may be represented by "invoice" / "file"
- https://fontawesome.com/icons/file-alt?style=solid
- https://fontawesome.com/icons/file-invoice-dollar?style=solid
- https://fontawesome.com/icons/file-invoice?style=solid

Anyway, you can request new icons by filling out our [icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

Closing here, hope it  helps
