### ISSUE TITLE
Icon request: icon-windsock-down

### ISSUE THREAD

**Issue by aescobarsamcla** [FortAwesome/Font-Awesome#15104]
Hi,
could be nice have a matched pair of current windsock icon for indicating "no wind", see attached image. The idea is to clearly getting down the sock.
Thank you.
![NoWind](https://user-images.githubusercontent.com/36436864/58857579-ec147400-86a5-11e9-8ec0-c75c1486c19d.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/windsock?f=classic&s=solid)
