### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by electronyxbazaar** [FortAwesome/Font-Awesome#15118]
**What can it be used for?**
Bank with Rupee, Euro, Dollar, Pound, Yen Symbol

**Example image (optional)**
https://www.google.com/search?q=bank+icon&safe=off&rlz=1C1CHWA_enIN628IN628&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj0htO6htfiAhUzXHwKHclpA10Q_AUIECgB&biw=1366&bih=657

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request does not meet our contributing guidelines because of the following points:
- This is a single icon or matched pair (Ex: lock / unlock)
- The title starts with "Icon request: " and is followed by the requested icon name (Ex: Icon request: magical-unicorn)

Please fix this request as per my feedback

I think this request is about something like `fa-university-dollar` and other currencies.

If I'm correct, the request is valid but there should be individual request for each currency. Font Awesome Pro customers can request icon sets in the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro

Said so, you can achieve those icons with the power transforms, masking, and layering feature of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/94/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

Meanwhile, closing here
