### ISSUE TITLE
Icon request: icon-corgi

### ISSUE THREAD

**Issue by purplelady105** [FortAwesome/Font-Awesome#15112]
**What can it be used for?**
This icon could be used on social networking sites to signify something cute or happy.
Also, who wouldn't love to incorporate an adorable Corgi silhouette into their project?

**Example image (optional)**

![image](https://user-images.githubusercontent.com/28715727/58987366-31af6a80-8794-11e9-9871-8279f3c1d7c7.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by shellzj** [comment]
I completely agree. Corgi for FontAwesome 6!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
