### ISSUE TITLE
v5 upgrade: pseudo elements using $fa-var-... as content no longer working

### ISSUE THREAD

**Issue by echjordan** [FortAwesome/Font-Awesome#15111]
In v4 the icon codes in _variables.scss have quotes, in v5 they do not. 
v4: https://github.com/FortAwesome/Font-Awesome/blob/v4.7.0/scss/_variables.scss
v5: https://github.com/FortAwesome/Font-Awesome/blob/5.8.2/scss/_variables.scss

This is causing any pseudo elements with ```content: $fa-var-...``` not to show up with manually adding quotes.

I've done some digging and I can use ```unquote('"#{ $fa-var-angle-down }"')``` but I'm hoping there's another solution/something else I'm missing that's more systemic so I don't have to change every one of my pseudo elements using an fa variable!

Is there something explicit I need to change with v5 related to utf-8? https://stackoverflow.com/questions/50576364/sass-escaping-quotation-marks-font-awesome-5

Thanks so much!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We had to remove quotes because of #6728

A good approach is the one followed by Font Awesome itself, using the [`fa-content` function](https://github.com/FortAwesome/Font-Awesome/blob/ba907eaec40fab01d410c3023a5572b2cb46cea6/scss/_variables.scss#L15), that will take care of escaping problems.

Ref: https://github.com/FortAwesome/Font-Awesome/blob/master/scss/_icons.scss#L9

Does it help?

**Comment by echjordan** [comment]
Yes this is helpful, thanks for a quick response.
