### ISSUE TITLE
Icon request: more email/notifications icons

### ISSUE THREAD

**Issue by tim-peterson** [FortAwesome/Font-Awesome#1512]
I've noticed a lack of email/notification icons in Font Awesome's collection. One that I like in the [Glyphicons](http://glyphicons.com/) set is a "@" sign, goes by the name "glyph-e-mail" and looks like this: 

![screen shot 2013-07-08 at 12 51 37 am](https://f.cloud.github.com/assets/1173307/759459/8ea3f5e0-e78a-11e2-9db4-b1f98221d8d4.png)

Others that might also be worth considering are variations on the Font Awesome's `icon-inbox` and look like this:

![screen shot 2013-07-08 at 12 53 30 am](https://f.cloud.github.com/assets/1173307/759458/7f005c78-e78a-11e2-8e31-92b1bd73afad.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
