### ISSUE TITLE
Add programming/coding icons?

### ISSUE THREAD

**Issue by malcolmjr96** [FortAwesome/Font-Awesome#15140]
HTML/HTML5
CSS/CSS3
PHP
C/C++
C#
JavaScript
etc

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Some of the icons you requested are already availabe (e.g: [html](https://fontawesome.com/icons/html5?style=brands), [javascript]()), others have their own request (eg: [c++](https://github.com/FortAwesome/Font-Awesome/issues/14021))

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
