### ISSUE TITLE
Icon request: fuel pressure

### ISSUE THREAD

**Issue by xmuskrat** [FortAwesome/Font-Awesome#15158]
**What can it be used for?**
fuel pressure, gas compression, oil chamber, engine with fuel

**Example image (optional)**
![gas_compression_oil_chamber_engine_combustion_fuel-512](https://user-images.githubusercontent.com/59917/59533591-d1f64500-8ea0-11e9-8f16-4a29a083798d.png)

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ X The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by xmuskrat** [comment]
![image](https://user-images.githubusercontent.com/59917/59533678-197cd100-8ea1-11e9-9123-d19a43f76a75.png)

Alt icon

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
