### ISSUE TITLE
Fontawesome 5.9.0 not showing fa-wave-square

### ISSUE THREAD

**Issue by Nopzen** [FortAwesome/Font-Awesome#15150]
**Describe the bug**
importing my all.min.css from the NPM package in the index of my react application

if i add the all.css the ::before element is added as described here https://github.com/FortAwesome/Font-Awesome/issues/15137 Iam not using kit tho, I'am using the NPM Package and fonts.

**To Reproduce**
import the all.min.css from the npm package and try to use the following icon `<i class="fas fa-wave-square"></i>`

**Expected behavior**
To see the wave square icon, i don't see anything not even the default square for missing char, when inspecting the dom the ::before element is missing aswell for the dom element.

**Screenshots**
<img width="77" alt="Screen Shot 2019-06-13 at 12 01 55" src="https://user-images.githubusercontent.com/2326591/59423816-2cc16b00-8dd3-11e9-87e3-36cadfb69ade.png">
<img width="713" alt="Screen Shot 2019-06-13 at 12 02 14" src="https://user-images.githubusercontent.com/2326591/59423824-2fbc5b80-8dd3-11e9-8771-f9226e953fb8.png">

**Version and implementation**
Version: 5.9.0 (Pro)
Browser and version: Chrome 75

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> if i add the all.css the ::before element is added as described here #15137 Iam not using kit tho, I'am using the NPM Package and fonts.

This is not the same issue as #15137. Also, you should not need special css since you are not using pseudoelements (as per `fas fa-wave-square`)

Unfortunately your use case is extremely hard and time consuming to reproduce.

Could you please provide a reproducible test case? Maybe a link to live/staging webapp

Please also double check that there aren't cache issues and that the served webfont files (.woff2 format, in your case) are the one from 5.9.0 and not older versions (you may try other 5.9.0 icons and check if they shows)

**Comment by Nopzen** [comment]
Hi @tagliala 

Sorry for the inconvenience, This was a cashing issue in webpack, after i updated the npm package npm.

Fixed with a refresh of webpack.

**Comment by tagliala** [comment]
No problem, glad you've solved 👍
