### ISSUE TITLE
Upgrade from v4 to v5 with pseudoelements too complicated 

### ISSUE THREAD

**Issue by theFallen78** [FortAwesome/Font-Awesome#15168]
to be honest someone will delete or close this 
it just needs to be said .
you guys took something beautiful and easy to use.
and overly complicated it for no reason .

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request? Are you referring to Font Awesome Kits?

**Comment by theFallen78** [comment]
yes . 
what happened to just having "fa fa-check"  "fa fa-users"
now its "fas fa-check" or "far fa-alarm-clock"
whats wrong with just having "fa " and not  ".fa,.fas,.far,.fal,.fab "
and when i want to append icons to tags using before
now i have to do this
`font-family: "Font Awesome 5 Free" !important; font-weight: 400; content: "\f14a" ! important;`
and this might not work for all icons 
and on the main site its a little hard to navigate to previous versions 

i know it seems like am venting or something but what am saying is it used to be easy to use font awesome

**Comment by theFallen78** [comment]
and thanks for responding

**Comment by tagliala** [comment]
Ok, thanks, got it, you mean the upgrade process from FA4 to FA5 when using pseudoelements.

I understand your frustration, and I'm aware that there is no silver bullet and v4 shims won't help in your use case.

The manual update process needed by pseudoelements is documented at [Update CSS Pseudo Element Rules](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4). New unicode points are available at [Icon Name Changes Between Version 4 and 5](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#name-changes)

We chose to use different prefixes because now we have 4 different icon styles (solid, regular, light, and brands) and we chose to use the `font-weight` property to differentiate between styles.

In FA5, icon use the same unicode point for all its styles. This is a breaking change when upgrading in your use case, but it provides a lot of help when switching from one style to another, especially when used on desktop via ligatures.

So let's sum up:
- Font name changed from `FontAwesome` to `"Font Awesome 5 Free"` or `"Font Awesome 5 Brands"`
- The default `font-weight` for pseudoelements should be set to `900`
- The `font-weight` of outline icons is `400`
- The unicode point of outline (regular) icons is the same as solid icons

Refs: 
- [Basic Use](https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use)
- [Upgrading from Version 4](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4)

Hope it helps, closing here but feel free to comment
