### ISSUE TITLE
Icon request: left / right versions of current level-up / down icon

### ISSUE THREAD

**Issue by terryschwarz** [FortAwesome/Font-Awesome#15171]
**What can it be used for?**
to indicate moving into something like a directory

**Example image (optional)**
Insert the example image here if necessary.
![image](https://user-images.githubusercontent.com/47600614/59690375-56054100-91af-11e9-8ced-bac7e7479c2c.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
Hi @terryschwarz,

`fa-turn-up`: https://fontawesome.com/icons/turn-up
`fa-turn-up-left`: ❌ missing.
`fa-turn-up-right`: ❌ missing.

`fa-turn-down`: https://fontawesome.com/icons/turn-down
`fa-turn-down-left`: https://fontawesome.com/icons/turn-down-left
`fa-turn-down-right`: https://fontawesome.com/icons/turn-down-right

There are currently no icons for `fa-turn-up-left` and `fa-turn-up-right`. 🤔

Regards.

cc/ @tagliala

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/turn-down-right?f=classic&s=solid)
