### ISSUE TITLE
Icon request: database-atom (Data Science)

### ISSUE THREAD

**Issue by abhijithragav** [FortAwesome/Font-Awesome#15180]
**What can it be used for?**
Data Science is an emerging field which is going on to become one of the most requested professions in the world.
**Example image (optional)**
![Data Science](https://user-images.githubusercontent.com/22400185/59741443-a43a4300-9288-11e9-9214-4d6031c5e064.png)
**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve that icon with the power transforms, masking, and layering feature of the SVG Framework and Font Awesome Pro.

Demo: https://jsfiddle.net/tagliala/c061tk3e/5/

I've changed the title because of 

> The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering
