### ISSUE TITLE
problem printing desktop fonts

### ISSUE THREAD

**Issue by kwrosenzweig** [FortAwesome/Font-Awesome#15194]
I have the fonts installed on my Mac.  I am using Apple Pages to design a document.  The fonts appear correctly on the screen, but when I print the file from Apple Pages or save as a PDF and print, the icons are distorted.

**Comment by tagliala** [comment]
@kwrosenzweig sorry, but I really need that you fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md) because I cannot replicate.

This is the screenshot PDF exported by Pages 8.0 on macOS 10.14.5 with Font Awesome Free 5.9.0

![image](https://user-images.githubusercontent.com/556268/60115020-4bc9e080-9775-11e9-9e42-b768daa0f07d.png)

Otherwise, please provide all the information you can, including:

1. Font Awesome version 
2. Specify if you are using FA Pro or FA Free
2. Confirm that you have installed the `.otf` and not the .`ttf`
3. macOS version
4. Pages version
5. Icons affected
6. Size of the distorted icons
7. Screenshot of the PDF with distorted icons

**Comment by kwrosenzweig** [comment]
The link you keep giving me takes me to a normal issue page.  There is no template.

The issue isn't on the screen, it is in the print out.  I have installed the otf.  I am using FA 5.9.0 desktop.

Max os 10.14.5
pages 8.0
fonts are 30 -25 points size

I am using the users icon, puzzle, phone, truck, network, any other.

Thank you.  Sorry about the template thing.  I don't know what to do about that.

**Comment by tagliala** [comment]
@kwrosenzweig thanks, I've updated my links. There was a typo, my bad

> The issue isn't on the screen, it is in the print out. 

Sorry, I cannot replicate

![image](https://user-images.githubusercontent.com/556268/60127247-ffd86500-978f-11e9-8dde-cc8b47ef30db.png)

Leaving this open for feedback from the community

**Comment by kwrosenzweig** [comment]
I tried the same 4 fonts you just posted in black and this is what I get...
![IMG_2673](https://user-images.githubusercontent.com/52179781/60128175-03ec8e80-9760-11e9-80f9-e4e23b12404f.jpg)

**Comment by tagliala** [comment]
I've printed directly from Pages, should I try something else? (i.e.: convert to pdf and then print the pdf)

**Comment by kwrosenzweig** [comment]
I also cannot get the fonts to work in Word.  I printed directly from Pages.

**Comment by tagliala** [comment]
> I also cannot get the fonts to work in Word

Word for mac?

Word for windows has problems: #14614

**Comment by kwrosenzweig** [comment]
Word for Mac

Kevin Rosenzweig
kwrosenzweig@gmail.com

**Comment by tagliala** [comment]
@kwrosenzweig could you please clarify the issues you are experiencing?

**Comment by kwrosenzweig** [comment]
Word for Mac, fonts don't work at all.  I can see that I have chosen font awesome font and type the name of the font and the words do not turn into the font.  When I copy from the cheat sheet, the icon is a square with a question mark in it.

In apple pages, the font show up not he screen when I type the name, but do not print properly.  See previous image I posted.

**Comment by tagliala** [comment]
Sorry but I can't help. I do not own Word for Mac

**Comment by kwrosenzweig** [comment]
I am more concerned about the printing issue from Apple Pages...

**Comment by kwrosenzweig** [comment]
was a printer firmware issue

**Comment by tagliala** [comment]
@kwrosenzweig thanks for letting us know

**Comment by tjkohli** [comment]
We're having this issue with an HP LasterJet Color printer as well— it seems to have the latest firmware. Has anyone found a workaround?

**Comment by tagliala** [comment]
@tjkohli are you printing from the web? Could you please share more details?

**Comment by tjkohli** [comment]
Printing from Pages on Mac.
- FontAwesome Pro (5.15.1)
- macOS Big Sur 11.1
- Pages 10.3.9
- HP LaserJet Enterprise M652

Have tried printing directly from Pages, and also exporting to PDF and printing that way. The icons appear as small artifacts (small triangles/random shapes).

One way that works:
- Export PDF from Pages > Import into Adobe Illustrator > Print from Illustrator

**Comment by tagliala** [comment]
> FontAwesome Pro (5.15.1)

Can you confirm you are using the `.otf` desktop version of Font Awesome?

**Comment by tjkohli** [comment]
> > FontAwesome Pro (5.15.1)
> 
> Can you confirm you are using the `.otf` desktop version of Font Awesome?

Ahh, yes they are .otf, sorry for not documenting that earlier.

<img width="303" alt="Screen Shot 2021-01-27 at 8 15 50 PM" src="https://user-images.githubusercontent.com/7361247/106075878-795ad680-60dc-11eb-9db8-c69429942a5d.png">

**Comment by tagliala** [comment]
Could you please try with the TTF (just tu understand if they work) and with other icon fonts using the PUA? 

I can think about https://github.com/Templarian/MaterialDesign-Webfont/tree/master/fonts

**Comment by kapfab** [comment]
I’m sorry to comment such an old issue, but the problem with the desktop fonts is still there.

Tested with latest macOS (Sonoma 14.5) and an HP Laserjet printer (M254dw) with its latest firmware (20230822).

Everything looks fine in Pages and in the PDF export but printed icons look like garbage.

This is the same with the latest V5 OTF font (Pro and Free) and the TTF font whose link you posted above and —to a lesser extent (some icons print fine, others print as the same garbage)— with the latest V6 OTF font (Free).

Interestingly, in V5 all font styles have the same problem but in V6 many Solid icons print fine (Regular icons still mostly print as garbage).

EDIT: To remove a variable from the equation, the issue is not caused by Pages or any other app, it is the same with all software I tried that —I guess— directly render the font (and it prints fine as soon as they convert the glyphs to shapes when adding effects like outline, shadow, etc.). I’ll try the font with software not using macOS' system font rendering engine and let you know of the outcome.

**Comment by robmadole** [comment]
@kapfab do you think this is associated specifically with the M254DW HP? Does this have the HP PostScript support in it?

**Comment by kapfab** [comment]
I think all HP LaserJet have builtin Postscript support.
I’d not be surprised if the issue had to do with a lot of if not all HP LaserJet printers.

@tjkohli above seemed to have the same issue (https://github.com/FortAwesome/Font-Awesome/issues/15194#issuecomment-768544261), but I don’t know which model of HP LaserJet printer they used.

I’m using AirPrint with my HP printer (not the other ones), the issue might be linked to its `urf` format conversion.
I tried with non-HP non-AirPrint printers and all looks fine.
I don’t have non-HP AirPrint capable printers around but I’ll try to print on the HP without AirPrint to investigate…

**Comment by kapfab** [comment]
The font is printing fine when using the HP PCL driver that comes with macOS.
So the issue definitely seems to come from AirPrint (be it on macOS or iOS) but I don’t know yet if it’s a bad encoding on the Apple side or a bad decoding on the HP side. I have to find a non-HP AirPrint printer to check that.

Also, I talked about this issue with an IT guy (without telling him my suspicions about AirPrint), and he told me he has already seen this problem with some fonts (he didn’t remember if it was on HP printers or not) and he fixed it by not using AirPrint but the vendor driver.
