### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by silva-thiago** [FortAwesome/Font-Awesome#15207]
**What can it be used for?**
Eu uso o Fontawesome nos sites que desenvolvo e no projeto atual senti a necessidade de usar um ícone que representasse a proteção contra os raios solares, o ícone do raio UV.

**Example image (optional)**
https://www.istockphoto.com/br/vetor/infogr%C3%A1fico-de-gr%C3%A1fico-de-%C3%ADndice-de-uv-gm1026123896-275204836
https://www.istockphoto.com/br/vetor/logotipo-de-sol-uv-estilo-simples-gm1021645156-274354203

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)
![istockphoto-1021645156-1024x1024](https://user-images.githubusercontent.com/20340261/60371482-c4c47480-99cf-11e9-881e-dc0bf88cafca.jpg)
![istockphoto-1026123896-1024x1024](https://user-images.githubusercontent.com/20340261/60371483-c4c47480-99cf-11e9-82a6-f0c22a692555.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Does https://fontawesome.com/icons/sun?style=solid fit your use case?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
