### ISSUE TITLE
Icon request: circle-1, circle-a, round-rect-1, round-rect-a

### ISSUE THREAD

**Issue by drbarnard** [FortAwesome/Font-Awesome#15235]
**What can it be used for?**
Other fonts have numbers and letters that can be used on the web, but it would be nice to have numbers and letters as svg symbols that match the feel of Font Awesome and are contained in circles and/or round rects.

**Example image (optional)**
![circled-a](https://user-images.githubusercontent.com/10518871/60623948-a5e82880-9da9-11e9-80db-281cfc541979.png)
![round-rect-1](https://user-images.githubusercontent.com/10518871/60623949-a5e82880-9da9-11e9-91f0-652c94056eed.png)
![circle-1](https://user-images.githubusercontent.com/10518871/60623950-a5e82880-9da9-11e9-966b-17b58140a101.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm afraid that this request will lead to #5019 or #14629, which I'm keeping closed at the moment because they are out of scope.

`A` is already available as `fa-font` https://fontawesome.com/icons/font?style=solid and `fa-font-circle` as well as `fa-font-square` could be achieved with the power transforms, masking, and layering feature of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/13/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

Anyway... I think that a single request for `1`, with a specific use case (must be different form #13175) meets our contributing guidelines

**Comment by aethior** [comment]
Hi @drbarnard,

Check the [**Alphabet Icons category**](https://fontawesome.com/icons/categories/alphabet) and [**Numbers Icons category**](https://fontawesome.com/icons/categories/numbers).

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
Circle and square numbers and letters have been added to FA Pro

**in a web application** it is possible to create circle/square numbers and letters in FA Free by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/96/

Ref:

https://fontawesome.com/v6/docs/web/style/power-transform
https://fontawesome.com/docs/web/style/mask
https://fontawesome.com/docs/web/style/layer
