### ISSUE TITLE
icon-dadaCenter-on

### ISSUE THREAD

**Issue by zhudage** [FortAwesome/Font-Awesome#15247]
![icon-dadaCenter-on](https://user-images.githubusercontent.com/6283658/60791341-060a1080-a196-11e9-9b4f-ae92d14407e4.png)

**Comment by zhudage** [comment]
System menu icon customization

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
