### ISSUE TITLE
icon-dataCenter

### ISSUE THREAD

**Issue by zhudage** [FortAwesome/Font-Awesome#15246]
![icon-dadaCenter](https://user-images.githubusercontent.com/6283658/60791080-7cf2d980-a195-11e9-9dac-3797a1e32d63.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
