### ISSUE TITLE
Innovation, smartcities, artificial intelligence, workforce transformation

### ISSUE THREAD

**Issue by jjmoody72** [FortAwesome/Font-Awesome#15270]
Hi!

I would love to see some icons that convey those mentioned in the header.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

If you are A Font Awesome Pro consumer, you can request icon sets in the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
