### ISSUE TITLE
Icon Request: pistons

### ISSUE THREAD

**Issue by xmuskrat** [FortAwesome/Font-Awesome#15275]
**What can it be used for?**
pistons (in a car engine)

**Example image (optional)**
![image](https://user-images.githubusercontent.com/59917/61470001-1c9e2d80-a935-11e9-8db1-3868f7af8187.png)

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by danielcongrove** [comment]
+1

It doesn't necessarily have to be pistons, but any sort of automobile motor or engine icon would be nice.

![image](https://user-images.githubusercontent.com/2227958/61542055-cef5f380-aa0e-11e9-9c5f-f8c37b588922.png)

**Comment by tagliala** [comment]
@danielcongrove please upvote #4175 for that design

**Comment by marceloverdijk** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/engine?f=classic&s=solid)
