### ISSUE TITLE
Icon request: Ataturk figure

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#15319]
Founder of the Republic of Turkey, Mustafa Kemal Atatürk 's badge as well as his signature. Google it with "Atatürk rozet" and "Atatürk imza" respectively.
Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a single color example, suitable for 16px icon size and a use case for this icon?

Also, which is the proper category for this icon? Political? Brand?

**Comment by 1denizci** [comment]
Thanks for the response.
Category may be historical, political, leaders.

This sample 480x480 px from my phone. Smaller seamed weird.

My best

**Comment by tagliala** [comment]
Hi, 

> This sample 480x480 px from my phone. Smaller seamed weird.

E-mail attachment don't work, please post the example at https://github.com/FortAwesome/Font-Awesome/issues/15319

**Comment by 1denizci** [comment]
![20190801_144559](https://user-images.githubusercontent.com/7515587/62291152-d59f5480-b46b-11e9-80d7-79955510e7f7.jpg)
128x128 px

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
