### ISSUE TITLE
Usage with Web Components

### ISSUE THREAD

**Issue by abenz1267** [FortAwesome/Font-Awesome#15316]
Hi,

is it possible to use Fontawesome with Web Components? I can't get it working. For example with LitElement:

```javascript
import { library, dom } from "@fortawesome/fontawesome-svg-core";
import { fal, faArrowUp } from "@fortawesome/pro-light-svg-icons";
import { LitElement, html, customElement } from "lit-element";

@customElement("my-component")
class MyComponent extends LitElement {
	constructor() {
		super();

		library.add(fal, faArrowUp);

		dom.watch();
	}

	render() {
		return html`
			<i class="fal fa-arrow-up"></i>
		`;
	}
}

```

The `<i>` tag inside the render function won't be replaced by the appropriate icon. Any solution to this?

Regards

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, I can't help on this. Waiting for feedback from the community

> `import { fal, faArrowUp } from "@fortawesome/pro-light-svg-icons";`

This doesn't look correct to me. It means that you are importing all icons in the set and faArrowUp, which is already in all icons. Anyway, this is not the problem here

Ref: https://fontawesome.com/how-to-use/with-the-api/setup/importing-icons#icon-names

**Comment by abenz1267** [comment]
I actually solved this. I stumbled across this documentation: https://fontawesome.com/how-to-use/with-the-api/methods/dom-watch

So you gotta do ```javascript
// @ts-ignore <-- if you use typescript
dom.watch({
  autoReplaceSvgRoot: this.shadowRoot,
  observeMutationsRoot: this.shadowRoot
})
```

I hope this helps someone else besides me.

Regards

**Comment by thigh** [comment]
@abenz1267 I know this is old and the issue is closed but I was wondering if you had problems with the generated svg graphic displaying the icon properly using your solution?

For some reason the path seems to be incorrect when the <i> tag is replaced with the <svg> causing the icon to not render in the proper location. Hovering over the tag I can see that the path has a dimension of 512x512 and it appears that the element is well below and to the right of where it is supposed to be, and also not visible.

I am using a similar config as you (Bulma w/ LitElement) so this solution seems great, if only the dang icon renders :)
