### ISSUE TITLE
Icon Request: fa-web

### ISSUE THREAD

**Issue by roopashetty** [FortAwesome/Font-Awesome#15359]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

If you are looking for an icon to represent world wide web, you can use https://fontawesome.com/icons/globe?style=solid or upvote #6763

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
