### ISSUE TITLE
Icon request: icon-user-arrow-right

### ISSUE THREAD

**Issue by trantorLiu** [FortAwesome/Font-Awesome#15369]
**What can it be used for?**
Can be used when send an invitation (such as follow request or friend request) to an user. Just like the friend-request-sent icon of Facebook.

**Example image (optional)**
![Screen Shot 2019-08-13 at 6 21 38 PM](https://user-images.githubusercontent.com/1210031/62934488-46912580-bdf7-11e9-966c-70b0aa048969.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/157/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
