### ISSUE TITLE
Icon request: <sport>-referee

### ISSUE THREAD

**Issue by dzsoundnirvana** [FortAwesome/Font-Awesome#15362]
A series of <sport> referees.

**What can it be used for?**
This icon can be used to go along with the current sport items (football, bat, soccer ball) in the library. Say if a sports site is being developed and there are pages for baseball, football, soccer/futbol, etc., these ref. icons can go along with them.

**Example image (optional)**
Each sport has it's own ref. They all have equipment particular to their sport they have to wear when officiating. A case would be baseball and the ref, would have either a face mask on or the chest pad or in the case of soccer/futbol, they would have either a card (the yellow, red card) or a sideline ref's. flag. An example of a sideline ref's equipment in soccer are the flags: https://www.shutterstock.com/image-illustration/soccer-assistant-sideline-referee-flag-103041584 
An icon like this can also go along with the current icons that appear when the term "flag" is searched for.  
The person with the flag signaling is similar to https://www.dreamstime.com/stock-illustration-assistant-referee-soccer-flag-image92133221

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md). Please open new individual request and provide single-color, small-size friendly examples for each icon

If you are a Font Awesome Pro customer, you can request this set in the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository and you are a Font Awesome Pro customer, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
