### ISSUE TITLE
Add icon gojek and gopay please

### ISSUE THREAD

**Issue by ianpwk** [FortAwesome/Font-Awesome#15391]
Add gojek and gopay for next update font awesome

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

If you are going to request two brands, `gojek` and `gopay`, please open two new individual requests by filling out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md). Adding the official website of the above brands would be better

Please also take a look at our [Brand Icons Leaderboard](https://fontawesome.com/community/leaderboard/brands#faqs), you will find a lot of information on how requests wokr
