### ISSUE TITLE
Icon request: fa-search-home

### ISSUE THREAD

**Issue by shaneedwardtaylor** [FortAwesome/Font-Awesome#15401]
**What can it be used for?**
home search icon to be used on a real estate web site

Basically just using your fa-search and putting the fa-home inside the search icon, same way your fa-search-dollar icon looks, only with a home icon instead of the dollar icon on the inside ;)

thanks in advance guys!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/171/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
