### ISSUE TITLE
Icon request: square-broken (earthquake)

### ISSUE THREAD

**Issue by mattdurso** [FortAwesome/Font-Awesome#15407]
**What can it be used for?**
Geospatial/weather mapping applications; to indicate the center of an earthquake

**Example image (optional)**
![earthquake_example](https://user-images.githubusercontent.com/54330640/63377368-9d49b280-c355-11e9-978a-7652e8efc0c4.PNG)
Maybe something like this. Some earthquake icons show a house with a crack through it which looks especially strange if shown on a map, the center being in the middle of the ocean.
Also, the heart monitor icon conflicts if a map also features health intelligence.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

You can obtain a decent design by using the power transforms and masking features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/172/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
