### ISSUE TITLE
Can't copy and paste the broken heart glyph from your gallery.

### ISSUE THREAD

**Issue by bigpurplefish** [FortAwesome/Font-Awesome#15414]
I can't copy and paste the broken heart glyph from your gallery. When I try to paste into a document, nothing is pasted.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[heart-broken](https://fontawesome.com/icons/heart-broken?style=solid) has been introduced in Font Awesome 5.6

The first thing to check is that you are using Font Awesome 5.6 or greater (latest version is 5.10.1)

Please check here: https://fontawesome.com/how-to-use/on-the-desktop/other-topics/troubleshooting#updating

![image](https://user-images.githubusercontent.com/556268/63437048-1fa3a680-c42a-11e9-8279-552f68881b42.png)

But... Font Awesome's .otf files >= 5.7.0 have issues with some Microsoft products and so you may see [arrow-circle-right](https://fontawesome.com/icons/arrow-circle-right?style=solid) instead of `heart-broken`. Ref: #14614

The solution is to install FA 5.6.3, but if you need an icon intruduced after FA 5.7.0, sorry but at the moment we do not have a solution. Someone says that using .ttf files work, I cannot make them work on an ancient version of MS Office

I'm going to close here, but if you are still having issue, please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)
