### ISSUE TITLE
Icon request: icon-bpmn || icon-business-process

### ISSUE THREAD

**Issue by nilei** [FortAwesome/Font-Awesome#1541]
Dear all,

it would be great if you could create an icon that represents a process like understand in the BPMN.

We would use that for our ticket process management and modeling software.

Example icon:

![icon-bpmn](https://f.cloud.github.com/assets/3751637/774465/2b3e7666-e95a-11e2-9875-a393d1fab8a3.png)

Cheers, Nils

PS: If you guide me a little I would be more than happy to create the icon myself and send you a pull request.

**Comment by ekkis** [comment]
I don't know how to +1 this idea.  I deal with processes all day and having an icon for it would be awesome

**Comment by ekkis** [comment]
also, viksel had requested the BPMN standard, which could be added as an alternative.  visually it doesn't convey to me the notion of a process, but it is a standard.  see: https://github.com/FortAwesome/Font-Awesome/issues/4129

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
