### ISSUE TITLE
Illustrator

### ISSUE THREAD

**Issue by fmcdigital** [FortAwesome/Font-Awesome#15423]
**What can it be used for?**
For using in portfolio showing the softwares I used.

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to close this because Illustrator is a subset of #1970

Even if individual requests are better, #1970 is an old request with a lot of +1s, and at the time we didn't have strict guidelines about icon sets, so please let's use that one for the moment.
