### ISSUE TITLE
Icon request: fa-users-edit

### ISSUE THREAD

**Issue by snolan** [FortAwesome/Font-Awesome#15428]
**What can it be used for?**

This is a single icon.

Icon would be used to indicate that multiple users can edit a record.
The icon would be similar to the fa-user-edit icon, but with multiple users.

https://fontawesome.com/icons/user-edit?style=regular

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
