### ISSUE TITLE
Icons are not showing up with 5.10.2

### ISSUE THREAD

**Issue by edwolfe807** [FortAwesome/Font-Awesome#15445]
I have a basic HTML file:

```
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="/dist/font-awesome/css/fontawesome.min.css">
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div><i class="fas fa-key"></i></div>
    </body>
</html>
```
If I use, fontawesome.min.css, I get squares instead of the icon; if I use solid.min.css, I get nothing at all.  I've tried in Firefox, Opera, Edge and Internet Explorer.

![image](https://user-images.githubusercontent.com/31911923/63858555-ad741a00-c973-11e9-80d1-45dd782721a4.png)

What is wrong?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please try to include `fontawesome.css` and `solid.css` ? You need them both for solid icons. Otherwise, you can load `all.css` by itself

Ref: https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself#using-certain-styles

Let me know
