### ISSUE TITLE
Icon request: reorder

### ISSUE THREAD

**Issue by mkollarc** [FortAwesome/Font-Awesome#15443]
The existing reorder icons do not totally grasp the idea, and are more fitting for text elements etc. This one fits reordering more in a general sense.

Example image
![image](https://user-images.githubusercontent.com/54618801/63835701-943a9000-c9aa-11e9-8c7d-e6094d5158e1.png)

**Comment by bryc** [comment]
The `sort` icon which is already well established, conveys reordering well enough, IMO.

**Comment by jtylrr** [comment]
> The `sort` icon which is already well established, conveys reordering well enough, IMO.

I think sort = change order. Reorder = manually change positions. Would also like a reorder icon (though simple enough to make one)

**Comment by bryc** [comment]
Have you seen [`sort`](https://fontawesome.com/icons/sort?s=solid)? It's just showing up and down arrows. It's vague and multi-purpose, what's not to love. There are [dedicated sorting](https://fontawesome.com/icons/arrow-down-wide-short?s=solid) icons that imply a predefined order which I agree wouldn't help indicate to the user that sorting can be done manually.

But there are other dual-arrow icons, [one with a line between them](https://fontawesome.com/icons/arrow-down-up-across-line?s=solid), which is even better, perfect even. 

Though this specific 3-bar design would be a nice addition:

![image](https://user-images.githubusercontent.com/1408749/167217141-746be3d3-dbb8-44ab-b9f6-43b39e63a381.png)

Or maybe something like this (a bit ugly but conveys the drag concept well):
![image](https://user-images.githubusercontent.com/1408749/167217823-497a3276-661c-4956-b294-e3bdd0b93a38.png)

I don't really like the OP design because it doesn't properly convey multi-directional re-ordering, but that's just me.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
