### ISSUE TITLE
Icon request: Lawn, Children park, Chef

### ISSUE THREAD

**Issue by Pratik-9020** [FortAwesome/Font-Awesome#15477]
**What can it be used for?**
i want icon for lawn, children park, and chef

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

We already have a chef hat: https://fontawesome.com/icons/hat-chef?style=solid

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
