### ISSUE TITLE
Icon Request: content

### ISSUE THREAD

**Issue by tobiasBurkill** [FortAwesome/Font-Awesome#15475]
Would love an icon that suggests content on a website. So things like lines for text and squares for images within a blocks. 

See example below: 

![Screenshot 2019-09-03 at 11 05 55](https://user-images.githubusercontent.com/7430514/64164348-fb3cc680-ce3a-11e9-9cc6-d5468e66de7f.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
