### ISSUE TITLE
Icon request: bars-caret-down

### ISSUE THREAD

**Issue by carl-parrish** [FortAwesome/Font-Awesome#15567]
**What can it be used for?**
Useful for dropdown buttons or to indicate that a section of an app/site has a pull-down.
Could perhaps be solved by having the arrow-alt-from-top icon show in the search results for pull-down. 
 
**Example image (optional)**
https://iconscout.com/icon/pull-down-1
https://www.istockphoto.com/vector/pull-down-projector-screen-icon-vector-gm838497966-136645599

**Icon request checklist**
- [x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x ] I have included at least one example image if it could be helpful (optional)
- [x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/255/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
