### ISSUE TITLE
Icon for - pet pack... more pet related like; Vet, Veterinarian, Pet Doctor / Pet Store / Pet Food / Pet Boarding

### ISSUE THREAD

**Issue by Toyguns** [FortAwesome/Font-Awesome#15568]
**What can it be used for?**
I have a pet related website im working on and could use more pet icons.  I know you have dogs, cats, birds, horses, even unicorns and dragons :)
PET PACK!!!!

**Example image (optional)**
You guys are great with coming up with these icons, I love them all! You would do a better job then me. I tried to layer some but the Icon then becomes really big if not, you can't tell what the icon is.

**Icon request checklist**
- [ ] Veterinarian
- [ ] Pet Store
- [ ] Pet Food
- [ ] Pet Boarding
- [ ] Dog Parks
- [ ] Feel free to add more I'll use them :)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

If you are a Font Awesome Pro customer, you can request icon sets on the Font Awesome Pro repository https://github.com/FortAwesome/Font-Awesome-Pro

If you are a customer but you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Closing here

**Comment by Toyguns** [comment]
Tagliala

Why did it not meet your Contributing Guidelines?

**Comment by tagliala** [comment]
@Toyguns 

This request partially fills our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md).

In the template there is also a checklist with seven points

The first point is the following:

> - [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)

We prefer individual requests on the public repo, sets are hard to manage.

Feel free to open individual requests for each icon, but please provide examples
