### ISSUE TITLE
New transportation mode

### ISSUE THREAD

**Issue by hhfrancois** [FortAwesome/Font-Awesome#15599]
Hi, maybe an idea for new icons
fa-eunicycle
fa-segway
fa-escooter
fa-esk8
fa-ebike

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by hhfrancois** [comment]
ok, didn't see, I do
