### ISSUE TITLE
Icon request: 3pmsf (three peak mountain snowflake / winter tires)

### ISSUE THREAD

**Issue by stevekr** [FortAwesome/Font-Awesome#15601]
**What can it be used for?**
Three-Peak Mountain Snowflake Symbol (3PMSF) is used to describe winter tyres that meet the specific snow traction performance requirements.

**Example image (optional)**
![Image](http://www.rubberassociation.ca/files/Mountain%20Snowflake%20(small).jpg)

**Icon request checklist**
- [x] This is a single icon
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
