### ISSUE TITLE
Icon request: icon-inspire

### ISSUE THREAD

**Issue by guptaashwanee** [FortAwesome/Font-Awesome#15617]
**What can it be used for?**
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)
![Inspire Graphics logo](https://user-images.githubusercontent.com/52340682/65803133-5b552d00-e19b-11e9-8474-8415ef58a865.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide more details about this request?

Is `inspire` a brand? If it is, could you please tell us more about this brand and add a link to the official website?

**Comment by guptaashwanee** [comment]
Hi!

This (Inspire) is a company name that I am opening it. and I want an
inspire icon on my website.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
