### ISSUE TITLE
Icon request: icon-spinner-alt + Spinning speed and direction classes

### ISSUE THREAD

**Issue by ioleo** [FortAwesome/Font-Awesome#1561]
Hi,

I would like to request an alternative spinner icon, similar to ![packagist loading icon](https://packagist.org/bundles/packagistweb/img/loader.gif).

Also, it would we nice if you could choose the direction and speed of rotating by adding special classes, eg:
- `icon-spin-cw` spinning clockwise
- `icon-spin-ccw` spinning counter-clockwise

And special classes to control the speed if animation (some icons look better when they spin slower/faster):
- `icon-spin-x1` **5s** animation
- `icon-spin-x2` **4s** animation
- `icon-spin` or `icon-spin-x3` **3s** (default) animation
- `icon-spin-x4` **2s** animation
- `icon-spin-x5` **1s** animation

**Comment by anthonator** [comment]
:+1: variable spin speeds

**Comment by norn** [comment]
+1 for speeds

**Comment by bogini** [comment]
+1

**Comment by anthonyboutinov** [comment]
+1

**Comment by Findiglay** [comment]
+ 1

**Comment by Kledal** [comment]
:+1:

**Comment by gmani2urs** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
