### ISSUE TITLE
Icon request: icon-polar-plot

### ISSUE THREAD

**Issue by CamKelly** [FortAwesome/Font-Awesome#15613]
**What can it be used for?**
Polar plots are a valuable way to represent a graph that is based on an angle between 0-359 degrees and one other variable such as wind speed. The plotted value can be say maximum sailboat speed at a specific angle and wind speed.

**Example image (optional)**
Insert the example image here if necessary.
![image](https://user-images.githubusercontent.com/2694598/65741869-22965480-e0c4-11e9-9d0a-7118eb0ca247.png)

**Icon request checklist**
- [ x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x] I have included at least one example image if it could be helpful (optional)
- [ x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a single color example suitable for small icon size? (16px)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
