### ISSUE TITLE
Icon request: old-people

### ISSUE THREAD

**Issue by viktoranders** [FortAwesome/Font-Awesome#15615]
**What can it be used for?**
There is a lot of icons for children and babies, in the same situation I often need a icon for old people

**Example image (optional)**
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAXBIyRB-d7QZDqI3MuqxvK7gtDGnQK5ag-Gw9MUBZh7ZTQKl5rw

https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMozT7nV4bZRwXX50qfjD_W08Y04rEfwnk1d62Ls7SG_evCuSQvw

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
*Related Unicode Emoji* #222
🧓 [U+1F9D3](https://emojipedia.org/emoji/%F0%9F%A7%93/) Older Person
Also known as `Older Adult`.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome! [Take a look at it here.](https://fontawesome.com/icons/person-cane?f=classic&s=solid)
