### ISSUE TITLE
@mixin sr-only are overwriting other mixins

### ISSUE THREAD

**Issue by raky291** [FortAwesome/Font-Awesome#15623]
**Is your feature request related to a problem? Please describe.**
the sr-only mixin are overwriting the Bootstrap mixin, and can overwrite any other library

we can easily fix this issue by importing first fontawesome and then bootstrap or manually import every scss files except `@import 'screen-reader';`

**Describe the solution you'd like**
but I think we should have an option as a variable to enable and disable those styles and avoid conflicts with other libraries, eg. `$fa-enable-screen-reader: true! default;`

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community, thanks for reporting this, and sorry for the delay in my reply.

Yes, it is correct, I think we should prefix that class. It could be done in FA6 as a breaking change

The solution of excluding the file is a good one, but may be not the best one. As you say, a variable set to true by default would be better

**Comment by stevelacey** [comment]
I'll note this here since I am not sure it warrants a new issue, but getting unprefixed `sr-only` out of the kits would also be beneficial since they conflict with other libraries that Font Awesome is commonly used with.

For example `md:not-sr-only` does not work in Tailwind when also using Font Awesome 6, due to the way FA is loaded overwriting anything in the application stylesheets.
