### ISSUE TITLE
Doesn't show on Chrome 

### ISSUE THREAD

**Issue by hrfahimi** [FortAwesome/Font-Awesome#15642]
I try to show the Infinity icon on a web page by this code. i can't see that in Google Chrome but in Firefox show:
`                  
                    <h2>
                        <i class="fa fa-infinity" aria-hidden="true"></i>
                        INFINITY
                    </h2>
` 
 Google Chrome v77.
Firefox v69.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Usually this happens because the website is using multiple versions of Font Awesome and maybe an older one takes priority over the newest one.

Please make sure that your application is loading FA >= 5.0.13

Please also note that third party plugins / libraries / framework may load another version of FA, so check your development console

Hope it helps

Closing here, but feel free to comment

**Comment by hrfahimi** [comment]
For the last note, I should say that it happens when icon insert inside of `<h2></h2>`.
FA v5.11.2 all
