### ISSUE TITLE
Icon request: map-zone (center, multi, mesh)

### ISSUE THREAD

**Issue by Skrol29** [FortAwesome/Font-Awesome#15653]
**What can it be used for?**

A « zone » icon option would be great when creating a certain mapping applications (drawing, rendering, ...), and somewhere else to illustrate that some information is spread over a zone

There is basically 3 types of common zones : 
- centered around a point
- mutlipart strayed zone (any zone whatever)
- meshed (that is for territories for examples)

**Example image**

map-zone-center 
![image](https://user-images.githubusercontent.com/2864356/66295088-d1b80480-e8ea-11e9-8f4a-05d3743f8107.png)
![image](https://user-images.githubusercontent.com/2864356/66295091-d5e42200-e8ea-11e9-8b44-8907c7bb3daa.png)

map-zone-multi 
![image](https://user-images.githubusercontent.com/2864356/66295109-de3c5d00-e8ea-11e9-896a-39328c36fab2.png)

map-zone-mesh
![image](https://user-images.githubusercontent.com/2864356/66295116-e3011100-e8ea-11e9-88ef-61a109fe59f6.png)

**Icon request checklist**
- [x] This is a matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues]
es) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
