### ISSUE TITLE
Seedling Icon not available on the OTF but available on the website!

### ISSUE THREAD

**Issue by Amort** [FortAwesome/Font-Awesome#15660]
Hello,

On Fontawesome website there is an icon named Seedling, I loved it and wanted to use it in my project but It seems that the icon is no longer available on the OTF file downloaded from the website.

Please double-check if you can make it available again.

Best,
AMR

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot replicate macOS 10.14 / Pages / FA 5 Free 5.9.0 and the newest 5.11.2: 
![image](https://user-images.githubusercontent.com/556268/66455361-db687600-ea6a-11e9-9038-fcf17f94c4c2.png)

But it may be related to another issue that is plaguing us since 5.7.0: #14614 

Please provide more information

Meanwhile, closing here
