### ISSUE TITLE
Icon request: fa-user-calendar-day (monthly tenants)

### ISSUE THREAD

**Issue by martindubenet** [FortAwesome/Font-Awesome#15679]
**What can it be used for?**
Useful to represent a **monthly tenant** VS an owner (represented by fa-user-crown until we get a fa-user-house).

**Example image (optional)**
A simple combination of the already existing **fa-user + fa-calendar-day**.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/212/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
