### ISSUE TITLE
Icon request: Parent Folder

### ISSUE THREAD

**Issue by danmacryan** [FortAwesome/Font-Awesome#15783]
**What can it be used for?**
This would indicate a way to navigate to the parent folder or parent directory

**Example image (optional)**

- http://icons.iconarchive.com/icons/tpdkdesign.net/refresh-cl/256/folder-black-parent-icon.png
- https://previews.123rf.com/images/transylvania/transylvania1706/transylvania170602796/81152206-parent-directory-multi-colored-flat-icons-on-plain-square-backgrounds-included-white-and-darker-icon.jpg
- https://cdn0.iconfinder.com/data/icons/pixel-perfect-at-16px-volume-3/16/5123-512.png

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Any example?

**Comment by danmacryan** [comment]
I have edited the original issue with more information.
I don't know what happened. I entered lots of information, but it didn't save.
Hopefully it sticks this time.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
