### ISSUE TITLE
Buggy rendering on PhantomJS since version 5.7.0

### ISSUE THREAD

**Issue by Kiyus7** [FortAwesome/Font-Awesome#15792]
Hi,

I am using Fontawesome in a project where I do screenshots through PhantomJS. It worked well until version 5.7.0 of FA, since then rendering is weirdly tilted:

![fontawesome_bug](https://user-images.githubusercontent.com/28563176/68544984-a4b2b200-03c0-11ea-9553-18ab1d417624.png)

I'm using the WebFont version (because SVG doesn't work with Phantom as far as I can tell).

Any idea where this is coming from (something in particular changed in version 5.7.0) and if it's fixable? Unfortunately it prevents me from upgrading to the newest versions.

Thanks!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Yes, we have changed some internals but it looks like that phantomjs is rendering icons with the italic style.

Could you please try with `<span>` and check if it is the same? Also, please try font awesome by itself without any other css rule

PS: I've migrated from phantomjs to chromedriver because phantomjs' development [has been abandoned about two years ago](https://github.com/ariya/phantomjs/issues/15344), so we will probably not going to fix this issue

**Comment by Kiyus7** [comment]
I thought it was about italic too so I tried with another element than i, and still does the same (removed all other CSS too).

I'll take a look at Chromedriver ; that said if it turns out to be an easy fix that would be appreciated :)

**Comment by tagliala** [comment]
> that said if it turns out to be an easy fix that would be appreciated :)

Well... I mean, PhantomJS is an abandoned headless browser for test purposes which displays icons with incorrect style, I will not investigate this issue any further if it is on our side 😅

**Comment by Kiyus7** [comment]
Haha yeah, by "easy fix" I meant "that doesn't even require investigation", in case the origin of the issue was obvious. Thanks anyway ;)

**Comment by tagliala** [comment]
Sorry, I'm going to close here as label as wontfix for the moment
