### ISSUE TITLE
Icons intermittently loading on kits

### ISSUE THREAD

**Issue by Coysh** [FortAwesome/Font-Awesome#15803]
**Describe the bug**
Occasionally, on a page load - a single icon on the page will not load correctly and display the "not found" icon. This has only happened since moving from a `npm` packaged font-awesome script to using kits.

**To Reproduce**
Hard to reproduce, but seems to happen about 1 in 15 page loads (approx)
https://www.eauk.org/about-us

**Expected behavior**
The icon to load correctly

**Screenshots**
`<i class="far fa-envelope fa-lg"></i>`
![image](https://user-images.githubusercontent.com/5764356/68663139-16f8d300-0536-11ea-8659-57ffc81f29b5.png)
![image](https://user-images.githubusercontent.com/5764356/68663130-0ea09800-0536-11ea-9117-9721cd77cea5.png)

`<i class="far fa-play-circle"></i>`
![image](https://user-images.githubusercontent.com/5764356/68663182-224bfe80-0536-11ea-99cf-6c7e4d376677.png)
![image](https://user-images.githubusercontent.com/5764356/68663202-28da7600-0536-11ea-8c9b-620548e3b1f8.png)

**Version and implementation**
Version: 5.11.2
Browser and version: Chrome - 78.0.3904.87 

- [X] SVG with JS
- [ ] SVG Sprites
- [ ] On the Desktop
- [ ] Web Fonts with CSS

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by usabilitest** [comment]
I've seen this on my site on occasion.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I can reproduce on your site, and in a fiddle with the source code of your html, but debugging with all the other scripts would require time and maybe the issue is somewhere else.

I've tried with this fiddle created from your website's body tag without other scripts and I've refreshed ~ 50 times without getting the error: https://jsfiddle.net/tagliala/8y72msgd/7/

Please try the following:

1. Fix [html validation errors](https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.eauk.org%2Fabout-us)
2. Disable all other scripts and check if the problem is still there. If it is fixed, please add scripts one by one until you are able to reproduce that

**Comment by Coysh** [comment]
I'll keep monitoring, but believe this issue has been fixed. I've done general clear-up on the site, but nothing that I think would have caused this.
