### ISSUE TITLE
Icon request: MMA hand in glove

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#15819]
**What can it be used for?**
To indicate Mixed Martial Arts such as the UFC. Events, training, fighters et cetera

**Example image (optional)**
![Ronin-X-treme-glove-zwart-rood-1](https://user-images.githubusercontent.com/7556992/68990126-eee4d900-0881-11ea-8451-19754e7cc888.jpg)
![40684_1](https://user-images.githubusercontent.com/7556992/68990134-f99f6e00-0881-11ea-9843-85ae5606a1d4.jpg)
![ufc-glove-motor-glove-mma-hand-glove-motorcyle-driving-glove-punching-bespecialtou-1803-08-bespecialtou@7](https://user-images.githubusercontent.com/7556992/68990136-002de580-0882-11ea-9503-a7cfac9ec765.jpg)

A lot of paying customers buy Font Awesome Pro mostly for the sports icon so this is a big oversight.

This had been requested but was closed for some reason
https://github.com/FortAwesome/Font-Awesome/issues/14802

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
