### ISSUE TITLE
Please stop setting __stripe_mid cookie

### ISSUE THREAD

**Issue by mariusa** [FortAwesome/Font-Awesome#15813]
We're including this in our app index.html
```
<script defer src="https://kit.fontawesome.com/123123.js" crossorigin="anonymous"></script>
```
We cannot reproduce the behavior, but after a few days of using an app having this script, cookie ```__stripe_mid``` appears.
![Screenshot from 2019-11-15 11-41-07](https://user-images.githubusercontent.com/1283842/68933201-d9e24a00-079c-11ea-9c5a-ccd785c700c6.png)

There's no need to set cookies, unless you want to track our users. We're forced by EU law to explain these in our cookie policy and there's no reasonable explanation.

Please stop setting cookies. 
Thank you

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please try in an incognito window?

That cookie should come from fontawesome.com and it should affects users which have visited our website. In other words, visitors of your website should not have that

**Comment by mariusa** [comment]
I see, thanks. It's strange that Chrome shows it on other sites than fontawesome.com, why is that?

I'll delete the cookie manually, stop visiting fontawesome.com and see if it appears in the next few days.

**Comment by tagliala** [comment]
You're welcome!

> I'll delete the cookie manually, stop visiting fontawesome.com and see if it appears in the next few days.

Yes, please, let us know but double check that you didn't visit fontawesome 😁 

> I see, thanks. It's strange that Chrome shows it on other sites than fontawesome.com, why is that?

That's because the cookie is set at domain level. It is one of the reasons why it is suggested to always use `www` instead of the naked domain for websites.

Also, we could think to use other (cookie-less) domains for kits and related stuff (e.g.: kit-fontawesome.com, cdn-fontawesome.com) but this decision is not up to me, sorry 😅
