### ISSUE TITLE
Icon request: packet-loss

### ISSUE THREAD

**Issue by nathan-fiscaletti** [FortAwesome/Font-Awesome#15827]
**What can it be used for?**
To display packet loss

**Example image (optional)**
This is my favorite design i've seen so far for **packet loss**. (taken from Battlefield)
![image](https://user-images.githubusercontent.com/1699763/69192443-31105380-0aea-11ea-8044-994b2566a8d8.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by JoshuaDoshua** [comment]
Throwing in another packet loss concept
<img src"https://support.rocketleague.com/hc/article_attachments/360036612934/rl_connection_icons.jpg" />

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
