### ISSUE TITLE
Icon request: network-latency

### ISSUE THREAD

**Issue by nathan-fiscaletti** [FortAwesome/Font-Awesome#15828]
**What can it be used for?**
To display network latency (the amount of time a packet takes round trip between two hosts)

**Example image (optional)**
This is my favorite example i've seen so far for **network-latency**. (Taken from Speedtest.net)
![image](https://user-images.githubusercontent.com/1699763/69192484-4a190480-0aea-11ea-8984-b8edc512d628.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by wastu01** [comment]
still not find now.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
