### ISSUE TITLE
Icon request: relay baton

### ISSUE THREAD

**Issue by aaronhudon** [FortAwesome/Font-Awesome#15829]
**What can it be used for?**
To symbolize relay races, or handing off from one person to another.

**Example image (optional)**
A hand holding a baton, passing to another hand.

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)
![image](https://user-images.githubusercontent.com/4406811/69206870-d20b0880-0b02-11ea-878d-52aa31c16ca7.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
