### ISSUE TITLE
Icon request: condom-packet

### ISSUE THREAD

**Issue by lzzzzzzz** [FortAwesome/Font-Awesome#15831]
**What can it be used for?**
A condom in packet icon for use in sexual health promotion, sex education, and sexual health products.

**Example image (optional)**
https://cdn1.iconfinder.com/data/icons/smashicons-romance-lifestyle-outline/57/7_-Condom-_romance_lifestyle_love_sex-512.png

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
