### ISSUE TITLE
[PRO] Fontawesome packages are not found in the npm registry.

### ISSUE THREAD

**Issue by pardonmeme** [FortAwesome/Font-Awesome#15846]
**Describe the bug**
What happened? What are you seeing? How did you arrive here?
Until now I was always using the file .npmrc to get packages with fontawesome PR and it worked perfectly fine. But since last friday, all our build fails because the packages cannot be found in npm registry. Did something changed?

**To Reproduce**
Have a fontawesome pro version and try to install with the .npmrc alias and the token

**Expected behavior**
How would you like this to work instead?
I would expected the fontawesome pro to be found in the npm registry and be installed.

**Screenshots**
![wat](https://user-images.githubusercontent.com/35489260/69537932-6c46d280-0f81-11ea-83b0-de1ce7deb7f5.png)

**Version and implementation**
    "@fortawesome/fontawesome-svg-core": "^1.2.25",
    "@fortawesome/pro-duotone-svg-icons": "^5.11.2",
    "@fortawesome/pro-light-svg-icons": "^5.11.2",
    "@fortawesome/pro-regular-svg-icons": "^5.11.2",
    "@fortawesome/pro-solid-svg-icons": "^5.11.2",
    "@fortawesome/react-fontawesome": "^0.1.5",

**Bug report checklist**
- [ x] I have filled out as much of the above information as I can
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by GonzaSanchez** [comment]
Hey! i was able to download it again by updating my `.npmrc`. I didn't know it has a different syntax 
https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please check your `.npmrc` as @GonzaSanchez mentioned

Then feel free to send an email to hello@fontawesome.com

**Comment by GonzaSanchez** [comment]
Also you should uninstall all your fontawesome deps, check that your lock file doesn't any fontawesome deps and then reinstall it. This is because the `.npmrc` removed the token from the url, but the lock file still had it in the url.

**Comment by pardonmeme** [comment]
That is quite a big of a breaking change, all previous CI builds fails now with the previous .npmrc setup.
True, after updating and removing package-lock and reinstalling again node_modules it worked but still.

**Comment by tagliala** [comment]
Hi, is this still an issue?

**Comment by Turbotailz** [comment]
In my case, my `.npmrc` file was using the correct format but I was still getting 404 errors. Simply removing `package-lock.json` and running `npm i` again resolved the issue for me.

**Comment by heinrich-fresh** [comment]
I have the same issue. 
tried to setup a new machine and all projects that uses fontawesome. Just the free basic icons gives me this error. 

Error message:
npm ERR! code E401
npm ERR! Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/",service="npm.fontawesome.com"

Not sure if it has to do with the fact that font awesome made their free packages private as well or something.

**Comment by tagliala** [comment]
> Not sure if it has to do with the fact that font awesome made their free packages private as well or something. 

Nope, free packages are free and are available in the public npm repo. Please remove your `yarn.lock`/`package-lock.json` and reinstall. If that does not work, please check that there aren't `.npmrc` files or global npm settings 

If you are a pro customer, please send an email to hello@fontawesome.com to get free support

BTW...

I'm going to close and lock here because:

1. This post contains different, unrelated issues 
2. License issues should be addressed via hello@fontawesome.com
3. At the moment I'm writing, it is not possible for formers customer to download the latest npm package they are entitled to download, please send an email to hello@fontawesome.com
3. Pro subscribers have docs available at https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers#installing-pro
4. If someone is reading here and none of the above comments help, they should open a new [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md) and provide all the information we need to debug
