### ISSUE TITLE
FontAwesome CSS Pseudo-elements 

### ISSUE THREAD

**Issue by laskalash** [FortAwesome/Font-Awesome#15907]
CSS Pseudo-elements only works with brand
its only show a square with:
"font-family: "Font Awesome 5 Free"; font-weight: 900; content: "\f007";"

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
