### ISSUE TITLE
Icon Request: fa-rodas

### ISSUE THREAD

**Issue by travieso97** [FortAwesome/Font-Awesome#15917]
This icon is used for a commercial management program, on windows and web platforms
![icon](https://user-images.githubusercontent.com/47193161/70358263-eeb77800-1846-11ea-85d6-ec4751573caa.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request?

Is this a brand?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
