### ISSUE TITLE
Icon request: dash

### ISSUE THREAD

**Issue by jhil** [FortAwesome/Font-Awesome#15912]
**What can it be used for?**
The dash has been popular recently to represent an indeterminate state in an input button like a radio button or checkbox. Having a simple horizontal line proportionally similar to the checkmark would be extremely useful! This would be similar to the `minus` icon, but thicker and shorter.

**Example image (optional)**
![CleanShot 2019-12-05 at 16 13 23](https://user-images.githubusercontent.com/2228347/70284796-2e645e00-177a-11ea-8040-3c3efd3a291d.png)
![image](https://user-images.githubusercontent.com/2228347/70284806-36240280-177a-11ea-8b0a-1d19d07291b2.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think https://fontawesome.com/icons/minus-square?style=solid fits your use case

We also have a request for an undetermined at #2055, but it is a square instead of a dash

Hope it helps

Feel free to comment if you think that minus-square doesn't fit this use case

Meanwhile, closing here
