### ISSUE TITLE
Icon request: icon-search-with-lines

### ISSUE THREAD

**Issue by innovate-invent** [FortAwesome/Font-Awesome#15921]
**What can it be used for?**
This can be used to represent reviewing a document, analysing data, searching text, watching a written conversation.

**Example image (optional)**
This was made by combining the align-left icon with the search icon:

[analyse.svg.zip](https://github.com/FortAwesome/Font-Awesome/files/3942398/analyse.svg.zip)
![analyse](https://user-images.githubusercontent.com/1768820/70484001-3e907c00-1a9f-11ea-94c2-f78bb4a0ff4b.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by Rogermass** [comment]
Icon request: ManageBac [.zip file](https://drive.google.com/file/d/1D0pz-FfGD55BqKo2BEFGGdoCX8-En5O_/view?usp=drivesdk)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
