### ISSUE TITLE
Add Kenyan shilling symbol

### ISSUE THREAD

**Issue by mayeedwin** [FortAwesome/Font-Awesome#15945]
**Let's have Kenyan currency symbols which are;**

1. **Ksh** ( text )
2. **/-** ( symbols )

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm leaving this open, but please take a look at this comment about non-symbol currencies: https://github.com/FortAwesome/Font-Awesome/issues/10896#issuecomment-299140688

**Comment by mayeedwin** [comment]
Thank you for the reference. Let look at it. Good work 👍

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
