### ISSUE TITLE
Feature Request: Fix install docs / pro installation process

### ISSUE THREAD

**Issue by mswilson4040** [FortAwesome/Font-Awesome#15959]
**Is your feature request related to a problem? Please describe.**
Font Awesome pro installation

**Describe the solution you'd like**
This is really more of a question and guidance on how to work with font-awesome pro.

1.) Since there is a private API key required (via an npmrc file) to use font-awesome pro, what's the recommendation on how you store this? I have a public project using font-awesome pro and therefore I would need to keep my key in a place that's publicly accessible. Is there a different way to do this?
2.) Per the instructions on the **Using a package manager** page, it suggests the following:
`npm install --save-dev @fortawesome/fontawesome-pro`

Why is the recomended install method to flag the dependency as dev dependency? This means that the npm package would never be bundled up for a production build (since it's a dev dependency). Am I missing something here? Shouldn't it be `--save` and not `--save-dev`?

**Describe alternatives you've considered**
1.) Instead of keeping a local .npmrc file with an api key, have an app registration that has the key. That would in turn generate a public key that anyone could use. However, since you registered the app, the pro-restriction would still be in play since the app registration process would require you to register a URL so nobody else could use your public key. Lots of other 3rd party 'things' operate like this (ie: Facebook)
2.) Fix documentation to install `--save` instead of `--save-dev`

**Additional context**

**Feature request checklist**
- [x] This is a single feature (i.e. not a re-write of all of Font Awesome)
- [x] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: moar cowbell`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome-Pro/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I will try to respond at the best of my knowledge, but I need to mention @robmadole 

>  I have a public project using font-awesome pro

This should not be allowed by the license. Ref: https://fontawesome.com/license#what-creators-may-not-do

> Why is the recomended install method to flag the dependency as dev dependency? This means that the npm package would never be bundled up for a production build (since it's a dev dependency). Am I missing something here? Shouldn't it be --save and not --save-dev?

Because it depends on your assets build system. In Rails' Webpacker (based on Webpack), on Webpack, and Rollup flows, it should be fine to have Font Awesome as a development dependency. Ref: #14504

It is unclear to me at the moment why `save` is a better option rather than `save-dev`, I've asked on #14504

Hope it helps

**Comment by mswilson4040** [comment]
`--save-dev` is reserved for dependencies that are only needed during development time. `--save` is reserved for packages that are required to ship with the application...

https://docs.npmjs.com/files/package.json#dependencies

**Comment by tagliala** [comment]
>  Is the requirement that it can't be open source?

I think the issue is with distributing a commercial product like Font Awesome Pro in an open source project

Please refer to the Pro repo, I have two official comments here:
- https://github.com/FortAwesome/Font-Awesome-Pro/issues/911#issuecomment-350281782
- https://github.com/FortAwesome/Font-Awesome-Pro/issues/1026#issuecomment-366489711

Feel free to send an email to hello@fontawesome.com
