### ISSUE TITLE
Icon Request: fa-energymeter

### ISSUE THREAD

**Issue by psuresh246** [FortAwesome/Font-Awesome#15986]
Hi,
I need a single icon for identifying energy meters, used for energy & utitilites web solutions. 
I am attaching an image i would like to have as fa icon.

Thanks.
![meter](https://user-images.githubusercontent.com/22386293/71349231-87aef880-2594-11ea-8f7e-c4d56f4b2994.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
