### ISSUE TITLE
Icon request: Mike Gester

### ISSUE THREAD

**Issue by MikeGester2** [FortAwesome/Font-Awesome#16015]
![My Logo Transparent 2](https://user-images.githubusercontent.com/51404158/71768127-67951700-2f4e-11ea-8a5b-2cb1fe1d6b90.png)
**What can it be used for?**
Describe how this could be used / the use case for this icon.
** > this is for my website that i make then i make a logo of it to represets me in everything.
>this is a single icon
>theres an image i uploaded 
> this is not a duplicate**
**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> this is for my website that i make then i make a logo of it to represets me in everything.

If this is the logo of your website and it is not relevant for other Font Awesome users, I think that the best option is to provide it as a standard SVG.

Otherwise, if you need it in "font awesome form", I think that the best option is customize the library. I suggest the npm + svg implementation for doing this

You may also consider to [sponsor this icon](https://fontawesome.com/community/leaderboard/brands#faqs) in the set, but I think this is not the case

References:
- https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
- https://fontawesome.com/community/leaderboard/brands#faqs

Hope it helps

Closing here
