### ISSUE TITLE
not working in html in sublime text 3

### ISSUE THREAD

**Issue by dangerbha1** [FortAwesome/Font-Awesome#16019]
<i class="fas fa-car"></i> is not working after including your website and all (using bootstrap framework)......whereas...........
<i class="fa fa-car"></i> is working ........

in previous versions " fa fa-search" is given and being copied and used in html......
but in v5.12.0 ....this bug i.e., fas instead of fa is being copied and not let the html icon work properly

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)
