### ISSUE TITLE
Icon request: Кафе Шупа

### ISSUE THREAD

**Issue by derpinapederina** [FortAwesome/Font-Awesome#16023]
![Varijanta-2](https://user-images.githubusercontent.com/59549159/71795036-7827b900-3044-11ea-8ddc-d25b25234cf0.png)
![Varijanta-2](https://user-images.githubusercontent.com/59549159/71795071-a60cfd80-3044-11ea-833c-f6f0a9819fbb.png)
![Varijanta-2A](https://user-images.githubusercontent.com/59549159/71795072-a6a59400-3044-11ea-9755-6206308cc272.png)

**What can it be used for?**
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

is this live chat? omg
sory i just need it for my university project for the web site, and that is also for a web site that i will be doing pro bono (its the official logo of a bar/coffee place)
a have no idea how this platform works, its 5:30h in the morning, and I did not sleep for days now... so my apologies for being unprofessional/uneducated enough etc...
so i just basicaly need it "fontawesome" form, I thought it is way easiear than this. so sory once again

**Comment by derpinapederina** [comment]
and i need just this thingy that looks like a house, but is actally a shed, and that is also the name of the place, where I work which I love etc..
so, once again, have no idea if I am speaking with a "machine" or real person, 

so in each case, best wishies, hope you have nice day Christmas eve today :)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> so, once again, have no idea if I am speaking with a "machine" or real person,

Real mach... hum... person here 😅

> sory i just need it for my university project for the web site, and that is also for a web site that i will be doing pro bono (its the official logo of a bar/coffee place)

If this is the logo of your website and it is not relevant for other Font Awesome users, I think that the best option is to provide it as a standard SVG.

Otherwise, if you need it in "font awesome form", I think that the best option is customize the library. I suggest the npm + svg implementation for doing this

You may also consider to [sponsor this icon](https://fontawesome.com/community/leaderboard/brands#faqs) in the set, but I think this is not the case

References:
- https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
- https://fontawesome.com/community/leaderboard/brands#faqs

Hope it helps

Closing here
