### ISSUE TITLE
Icon request: Finance Related Icons

### ISSUE THREAD

**Issue by rohaanthakare** [FortAwesome/Font-Awesome#16039]
Can we have some more finance related icons for below.
1. Deposit Money / Credit 
2. Withdraw Money / Debit
3. Transfer Money
4. Expense
5. Account Statement (for this we can use existing list icon).
6. Money to Take 
7. Budget Manager
7. Money to Give

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

There is at leaste a duplicate : #13342, then we need examples and individual icon request for each icon in the list

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
