### ISSUE TITLE
Yarn not installing fontawesome

### ISSUE THREAD

**Issue by vijayst** [FortAwesome/Font-Awesome#16047]
**Describe the bug**
Yarn is not able to install fontawesome because of 401 error. On navigating to the URL which has the tgz file, I get a basic auth dialog.

**To Reproduce**
My Yarn lock file has this entry:
```
"@fortawesome/fontawesome-free@^5.2.0":
  version "5.10.1"
  resolved "https://npm.fontawesome.com/@fortawesome/fontawesome-free/-/fontawesome-free-5.10.1.tgz#dec28ee02c3fc51da46d53ce4da9d5787312fbd7"
  integrity sha512-PYncBhgN1l02mwHmczukexmu4yRTjRDAAdcK62jdWSAW8epcnZ9K2win/7rMrffiv/c7XLVDA8vD+yi6WyvbGQ==
```

**Expected behavior**
Yarn should install FontAwesome

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately at the moment the License Server is down, so if you need a pro package please refer to #16046 

Anyway, given that this is a 401 error and not a 402 and you are requesting `fontawesome-free`, the issue you reported is different.

If you are a Pro costumer, we have recently changed our npm authentication, please refer to https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers#installing-pro for the new instructions

If you are not a Pro customer or you were a Pro customer, you should switch from the private npm repo (npm.fontawesome.com) to the public pro repository (registry.yarnpkg.com or registry.npmjs.org according to your node package manager tool). In order to do that, please remove and reinstall font awesome packages

Hope it helps

Closing here but feel free to comment

**Comment by vijayst** [comment]
Even when I do `yarn add @fortawesome/fontawesome-free`, I get a 401 error as it is pointing to `https://npm.fontawesome.com/@fortawesome/fontawesome-free/-/fontawesome-free-5.10.1.tgz`.

**Comment by lwhiteley** [comment]
i have the same issue. doesnt seem to just be fontawesome

https://github.com/yarnpkg/yarn/issues/8242#
