### ISSUE TITLE
Icon Request: fa-waterbottle

### ISSUE THREAD

**Issue by rh-pazarlama** [FortAwesome/Font-Awesome#16048]
Hi there,

We will really be appreciated if you create and share with us a "water bottle" icon. We will use it on our website at the "Water Bottle" segment which is selling office and stationery products. The icon we need  can be similar to:
![canteen (1)](https://user-images.githubusercontent.com/59733664/72154186-07c0c500-33c1-11ea-84af-690c2434f75d.png)
![canteen (2)](https://user-images.githubusercontent.com/59733664/72154188-07c0c500-33c1-11ea-8fd6-a20e9916e7d5.png)
![canteen](https://user-images.githubusercontent.com/59733664/72154189-08595b80-33c1-11ea-8620-3ba0b1ede969.png)

**Comment by aethior** [comment]
Hi @rh-pazarlama,

This icon has been added in v6.1.0.
Check https://fontawesome.com/icons/bottle-water

Regards.

cc/ @tagliala

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome! [Take a look at it here.](https://fontawesome.com/icons/bottle-water?f=classic&s=solid)
