### ISSUE TITLE
Icon request: circle-clone

### ISSUE THREAD

**Issue by DrawbotDesign** [FortAwesome/Font-Awesome#16053]
**What can it be used for?**
This would be the equivalent of the "Clone" icon but as a rounded circle instead of as square. I had stakeholder feedback that a square as a bullet feels like it should be clickable, so if it is not, a circle works better. But if you need a bullet that implies multiple circles clustered together, there's not much of an option.

**Example image (optional)**
https://fontawesome.com/v4.7.0/icon/circle-o
This would be the icon, to make with an extra O extending off the right side, behind the main O

**Icon request checklist**
- [single] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)
[https://imgur.com/WJoHslW](url)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
