### ISSUE TITLE
app.js:52117 Uncaught TypeError: Cannot read property 'add' of undefined     at Module../resources/assets/js/fontawesome.js (app.js:52117)

### ISSUE THREAD

**Issue by Junaidejaz111** [FortAwesome/Font-Awesome#16062]
Laravel 5.6
code: 
import fontawesome from '@fortawesome/fontawesome-free';

import faCaretUp from '@fortawesome/fontawesome-free-solid-svg-icons/faCaretUp';
import faCaretDown from '@fortawesome/fontawesome-free-solid-svg-icons/faCaretDown';
import faStar from '@fortawesome/fontawesome-free-solid-svg-icons/faStar';
import faCheck from '@fortawesome/fontawesome-free-solid-svg-icons/faCheck';

fontawesome.library.add([faCaretUp, faCaretDown, faCheck, faStar]);

error:
Uncaught TypeError: Cannot read property 'add' of undefined
    at Module../resources/assets/js/fontawesome.js (app.js:52117)
    at __webpack_require__ (app.js:20)
    at Object../resources/assets/js/app.js (app.js:51950)
    at __webpack_require__ (app.js:20)
    at Object.0 (app.js:52139)
    at __webpack_require__ (app.js:20)
    at app.js:84
    at app.js:87

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)

> import fontawesome from '@fortawesome/fontawesome-free';

Looks wrong to my eyes. Please take a look at our API documentation: https://fontawesome.com/how-to-use/with-the-api/setup/getting-started

Hope it helps

Closing here
