### ISSUE TITLE
Icon request: keyboard special keys

### ISSUE THREAD

**Issue by oskerlau** [FortAwesome/Font-Awesome#16100]
**What can it be used for?**
Can be very useful on learning materials to display keys to press, eg: Esc, Ctrl, Shift, Enter, Apple, F5, Fn, Page Up, etc etc...

**Example image (optional)**
![2020-01-22_115947](https://user-images.githubusercontent.com/5934070/72859205-b85a8d00-3d0e-11ea-94fe-fa163538d6ff.jpg)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request contains:
- A duplicate (#1293)
- An unknown number of icons (hard to manage)
- An icon that has been already implemented: https://fontawesome.com/icons/backspace?style=solid

Also, there are several duplicates of this request that have been closed (e.g: #10867) because our contributing guidelines don't allow sets. If we consider F1 to F12 special keys, this would need the effort to build request for ~ 100 icons

@sensibleworld what we can do here?

**Comment by taxilian** [comment]
I suspect that most of the keys could be made by combining multiple icons if you had one (or a few) basic shape icons for a keycap. Perhaps that would be acceptable?

**Comment by taxilian** [comment]
You could probably just use "rectangle-landscape" for many of them, but it would be nice to have a few icons specifically designed to be various "key" shapes. That said, it's very likely that you could do a pretty decent job of these just by using the techniques mentioned in https://fontawesome.com/how-to-use/on-the-web/styling/layering

I would really love to see some better base icons to use for this, though.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Comment by yunylz** [comment]
Any updates?
