### ISSUE TITLE
Icon request: truck-with-trailer (articulated lorry)

### ISSUE THREAD

**Issue by CipherNet** [FortAwesome/Font-Awesome#16114]
**What can it be used for?**
This can be useded to illustratrea a driving certificate with the type of CE or when you have to book a truck with a trailer for transportation etc.

**Example image (optional)**
Combination of "fa-truck-moving" and "fa-trailer" in a sequense

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by CipherNet** [comment]
Any news on this one, expected timeline etc ?

**Comment by tagliala** [comment]
Hi!

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

**Comment by aethior** [comment]
*Related Unicode Emoji* #222
🚛 [U+1F69B](https://emojipedia.org/emoji/%F0%9F%9A%9B/) Articulated Lorry

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
