### ISSUE TITLE
Icon request:fas fa facebook

### ISSUE THREAD

**Issue by aicha2019** [FortAwesome/Font-Awesome#16119]
**What can it be used for?**
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think this could be a bug report, in the meaning that the facebook icon is not working for you, because we already have facebook icons in different flavours

- https://fontawesome.com/icons/facebook-square?style=brands
- https://fontawesome.com/icons/facebook-f?style=brands
- https://fontawesome.com/icons/facebook?style=brands

It is possible that you are either:
- using the wrong prefix (it should be `fab`, not `fas`); or
- have an ad-blocker that prevents your browser to load social icons

Please clarify

Meanwhile, closing here
