### ISSUE TITLE
Icon Request: cross

### ISSUE THREAD

**Issue by manattweb** [FortAwesome/Font-Awesome#1611]
Would like to request a new icon of a cross, which could be the plus icon with the horizontal bar moved up vertically. Something like:

![icon_cross](https://f.cloud.github.com/assets/3402707/827994/20468770-f0a9-11e2-97a9-e97e3f997232.png)

I plan to use this on various websites that are built for religious non-profits.

**Comment by boydspace** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by mirdala** [comment]
+1

**Comment by nikkiroylance** [comment]
+1

**Comment by bsrome** [comment]
+1

**Comment by ewillstudios** [comment]
+1

**Comment by didoulr** [comment]
+1

**Comment by hellsing71** [comment]
+1

**Comment by gustavohellwig** [comment]
+1

**Comment by MrZach** [comment]
+1

**Comment by Guestrevu** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by webcaetano** [comment]
+1

**Comment by Uniphix** [comment]
+1

**Comment by Mihailiuc** [comment]
+1 on this one!

Please give a +1 to this one also, is refereed also to Christians
https://github.com/FortAwesome/Font-Awesome/issues/8239  (for doctrinal statement)
https://github.com/FortAwesome/Font-Awesome/issues/2088 (church)
https://github.com/FortAwesome/Font-Awesome/issues/8123 (bible)

**Comment by GermanKiwi** [comment]
+1

**Comment by CarlosHAraujo** [comment]
+1

**Comment by zuck** [comment]
+1

**Comment by rdehuyss** [comment]
+1

**Comment by jbnv** [comment]
+1

**Comment by machiaveli88** [comment]
+1

**Comment by psmak4** [comment]
As an alternative until this gets added, there is a pure css cross that can be done ([https://css-tricks.com/examples/ShapesOfCSS/](https://css-tricks.com/examples/ShapesOfCSS/), at the bottom of the page).  Just modify the width and top values for the :after to get it lined up how you want.

**Comment by davidfreels** [comment]
+1

**Comment by sandeejackson** [comment]
+1 -- could really use this one.

**Comment by cre8tivediva** [comment]
+1

**Comment by sbsnet** [comment]
+1

**Comment by ahmetertem** [comment]
+1

**Comment by biwin** [comment]
+1

**Comment by Memaddog** [comment]
+1

**Comment by Crissov** [comment]
## Christian crosses and symbols
* † U+2020 Dagger ([Ob]long Cross)
* ☓ U+2613 Saltire (St. Andrew’s Cross) – U+1F7A8–E
* ☥ U+2625 Ankh
* [☦ U+2626 Orthodox Cross](http://emojipedia.org/orthodox-cross/)
* ☧ U+2627 Chi Rho (Constantine’s Cross)
* ☨ U+2628 Cross of Lorraine
* ☩ U+2629 Cross of Jerusalem
* ♁ U+2641 Earth
* ♰ U+2670 West Syriac Cross
* ♱ U+2671 East Syriac Cross
* ✚ U+271A Heavy Greek Cross – U+1F7A1–7
* **[✝ U+271D Latin Cross](http://emojipedia.org/latin-cross/)**
* ✠ U+2720 Maltese Cross
* 🕈 U+1F548 Celtic Cross

**Comment by GermanKiwi** [comment]
@Crissov  what's your point in posting a list of different cross-based emojis? This thread is to request a standard Christian cross symbol, as depicted by the OP in the top post here. None of your emoji in your list are the correct cross shape, with the sole exception of your "Latin Cross". In any case, Font Awesome is not based on emoji. The emoji in your list are too thin and not suitable for this purpose.

**Comment by Crissov** [comment]
@GermanKiwi If FA adds any religious symbol, people will demand various others or regard their omission as discrimination. In each request issue, participants should agree on the proper shape, name(s) *and* code(s), in my opinion. I agree that U+271D is the most likely choice and added a note to my previous comment.

I don’t know which font is used to render the characters above on your system. I did not intend to propose any of their glyphs as a shape for a cross symbol in FA.

**Comment by GermanKiwi** [comment]
@Crissov, if other users want other types of symbols, including other variations on the standard cross shape, then they need to create separate Github issues for them. One issue per request. This issue here is for a standard Christian cross (a.k.a. "Latin cross"), as depicted and requested in the top post, not any other type of cross-related symbol.

Also there's nothing discriminatory about omitting other religious symbols and only including the ones that are most requested or that make the most commercial sense. That's no more discriminatory than it is to include an icon for a soccer ball and rugby ball but not a volleyball. Font Awesome is a commercial undertaking, not a government institution - its developers shouldn't have to cater to every individual's whim and fancy on the basis of some imagined sense of "fairness" or equality.

**Comment by tagliala** [comment]
> Also there's nothing discriminatory about omitting other religious symbols and only including the ones that are most requested or that make the most commercial sense. That's no more discriminatory than it is to include an icon for a soccer ball and rugby ball but not a volleyball. 

I personally do not agree with this, I'm more on @Crissov's side.

As far as I can tell, religion is a sensitive topic

E.g: from [Facebook's community standards](https://www.facebook.com/communitystandards)

> Facebook removes hate speech, which includes content that directly attacks people based on their: 
> [...]
* Religious affiliation,
* Sexual orientation,
* Sex, gender, or gender identity, or

There is no reference to "sports" or "soccer team"

Also, we added [all gender icons](http://fontawesome.io/icons/#gender) to avoid any kind of discrimination and we should do the same for religions.

Problem is that the list of religions is [pretty big](https://en.wikipedia.org/wiki/List_of_religions_and_spiritual_traditions) 😐

**Comment by jbnv** [comment]
The rule is that an icon must receive 100 requests in order to be created, right? If 100 people request the Muslim crescent, make it. If 100 people request the Flying Spaghetti Monster, make it. The only way someone can claim discrimination is if the icon meets the requirements that FA makes for creation and FA refuses to create it. 

FA discriminates against requests for icons all the time. Several of my requests were turned down. Can I have them if I claim they are part of my religion?

**Comment by GermanKiwi** [comment]
I'm not familiar with the "100 requests" rule, but @jbnv is nevertheless correct with his point. The primary deciding factor for a new icon should simply be demand, rather than some sense of fairness. I see no point in the developer spending time on new icons that nobody (or virtually nobody) actually wants.

We have lots of +1's in this thread for a Christian cross, and scores and scores of +1's at #2088 for a church icon. But I can't find any issue for a Muslim crescent, or a Judaic star of David. There is an issue with a small handful of votes for a mosque (#5146) and also a Buddhist temple (#6655) - they're not in high demand - but no requests for a synagogue or other houses of worship. That's very telling.

As @jbnv mentioned, discrimination would be if 100s of people voted for a mosque (for example) and the developer deliberately ignored it. However I would go further and say that even in that case, the developer is under no obligation to comply with such requests. It's his project, and he is (and should be) free to make his own decisions based on whatever criteria he wants. Who says he has to be fair?

Facebook's community standards are referring to hate speech, which is not what we are discussing here. Omitting a particular religious icon is not hate speech, ie. it does not constitute "content that directly attacks people based on their religion". :)

Font Awesome is inherently discriminatory - if you want to define it that way - in that by including any icon, it automatically excludes other icons that belong to the same icon category. For example, FA has an icon for WhatsApp, but not (yet) for Facebook Messenger or Viber etc. So FA is "discriminating" against all the folk who need a Messenger icon (that includes me!) I don't think that's wrong though.

As @tagliala rightly noted, the list of religions is pretty big - too big to cater to them all. It doesn't make any sense to then ignore the scores of users who are requesting certain popular icons like a cross or church just because there are too many other religions to cater to.

Also, I think gender icons are a little different - if only because there aren't that many of them, and it's therefore fairly easy to just create them all together. And I'd have no problem if the developer took just the top 3-4 major religions and created icons just for them too. That would be a good solution, as it's still based primarily on demand.

**Comment by epelowski** [comment]
+1 Wow. Three years and no cross yet? Is this developer anti-religion? There are quite a few themes for churches that use FontAwesome too. Is FontAwesome the only option for creators of themes??

**Comment by GermanKiwi** [comment]
Take it easy, @epelowski - just because the developer hasn't dropped everything to make the icon you want doesn't mean he's anti-religion, and such baseless and impolite accusations won't help any. Remind me how much you're paying for Font Awesome? Yeah, you get to use the developer's work for free! There are currently 3795 open issues (ie. new icon requests) for Font Awesome here on Github. Why should your request take priority over all the others?

You're under no obligation to use this free font. There are many others available on the internet (just ask Google) which you could integrate with your theme - or you could check out [Fort Awesome](https://fortawesome.com) - from the same developer - it has more icon sets available, and allows you to add your own icons too - of course, you have to pay for that functionality. Or you could wait for Font Awesome version 5, which comes out next year - the developer has just completed a record-breaking Kickstarter project for it - did you contribute any money towards it?? It will include many new sets (groups) of icons, including a religious set.

**Comment by epelowski** [comment]
I apologize for my words @GermanKiwi. Long day at work, stressed out, not an excuse for my reaction however. I am sorry for acting out.  That is great news that the developer is working on release 5. As far as donations and kickstarter, It is my sincere hope that theme developers that charge money for their themes and that use Font Awesome as an integrated part of their theme do contribute monetarily to Font Awesome. I guess I feel a little burned that I paid good money for a theme for a church to then find out that there are no icons for churchs, crosses, religion in general, but yet Font Awesome is tightly integrated into the theme.

**Comment by GermanKiwi** [comment]
No problem. Yes, I'm sure many theme developers that use FA will have contributed towards its Kickstarter project. In fact a total of 35,550 people contributed over $1 million (the original goal was just $30,000). But if you purchased a church theme with the understanding it would include religious icons, then your quarrel is really with the theme developer, not with FA. Font Awesome has no control over which themes integrate it. :)

**Comment by princeofnaxos** [comment]
+1

**Comment by pezjr** [comment]
So font awesome.io is not going to have any religious icons than it is a waste of money for me to order Font Awesome 5 Pro, or use any font awesome on my wedsite, I"ll have to find another icon set that has religious icons that work with WordPress

**Comment by GermanKiwi** [comment]
@pezjr what makes you assume that Font Awesome isn't going to have any religious icons? The developer has already stated in the past that FA5 will include a religious icon set.

**Comment by pezjr** [comment]
Thank you for classifying that question up, that is what I got from reading
some post. Do you know fontawesome 5  would be available

**Comment by holzee** [comment]
+1 Need it badly for 2 websites

**Comment by mwidjaja1** [comment]
+1

**Comment by tonywatkins** [comment]
+1

**Comment by manattweb** [comment]
Glad to see this request is still open, which means there is hope for the inclusion of this icon in FA 5.

**Comment by kls803** [comment]
+1  -- I was just looking at the list of religious icons. The icon for the Sikh faith is a pretty amazing.

**Comment by tonywatkins** [comment]
It's great to have the church icon now, but it is limited in use compared to symbols for major religions. Yes, religion is a sensitive subject, but there is no problem having icons for the 6 major world religions:

- Christianity
- Islam
- Judaism
- Hinduism
- Buddhism
- Sikhism

**Comment by kls803** [comment]
These are the icons I was referring to -- from the page on world religions at Wikipedia. The ones on the right are the ones that **tonywatkins** mentioned. I think it would be nice to have those at least. 

https://en.wikipedia.org/wiki/List_of_religions_and_spiritual_traditions#/media/File:RELIGIONES.png

**Comment by Wingo5315** [comment]
+1 
Change the name of this request to fa-christian-cross so it’s clearer what you’re asking for.

**Comment by AlistairW** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/cross?style=solid
