### ISSUE TITLE
sort-circle results in 2 different symbols

### ISSUE THREAD

**Issue by ppnp253** [FortAwesome/Font-Awesome#16124]
"sort-circle" on 5.12.0 results in two different symbols. Copying the icon from the cheat sheet also displays foreign characters.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)
