### ISSUE TITLE
Icon Request: icon-gamerscore

### ISSUE THREAD

**Issue by jasonclemons** [FortAwesome/Font-Awesome#1614]
Requesting a Gamerscore icon to add. The icon is located next to the Gamerscore here: http://gamercard.xbox.com/en-US/RealJBlaze.card

An icon already exists for achievements, which is `icon-trophy`, and none is needed for Microsoft Points as that system is being phased out in the next few weeks.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
