### ISSUE TITLE
npm.fontawesome.com is down again

### ISSUE THREAD

**Issue by rnicholus** [FortAwesome/Font-Awesome#16151]
**Describe the bug**
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/pro-regular-svg-icons/-/pro-regular-svg-icons-5.11.2.tgz: Request failed \"502 Bad Gateway\"".

**To Reproduce**
see above

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

It seems the license server is unstable, and goes down quite often. Are there any plans to stabilize this? 

I'm seeing a bunch of other similar reports in this repo.

**Comment by tagliala** [comment]
Hi, sorry for the late reply, this should have been solved several hours ago

**Comment by rnicholus** [comment]
Are there any plans to stabilize this? The server goes down regularly - builds break often due to this. And I've seen other similar reports in this repo.

**Comment by rnicholus** [comment]
Since it's difficult to even keep the server running, I have concerns about how secure this endpoint is. Is this server audited regularly? What other practices or processes are in place to ensure this instance remains trustworthy?

**Comment by tagliala** [comment]
> , I have concerns about how secure this endpoint is. Is this server audited regularly? What other practices or processes are in place to ensure this instance remains trustworthy?

@robmadole can you provide some clarification on the above questions?

**Comment by robmadole** [comment]
The service is now managed by a company called CloudSmith. We've had two occurrences of downtime since we switched to them. One was 4 hours and the other was about 30 minutes. (The 4 hour downtime was a misconfiguration of our bandwidth limits that hit in the middle of the night for our team and we had no monitoring for it.)

Statistically speaking CloudSmith has better stability and up-time than NPM itself. We have an SLA with CloudSmith and it hasn't been violated.

I can understand your doubts about the service @rnicholus. But we feel we are now in good hands with our current setup.

**Comment by hypeJunction** [comment]
And again :(

**Comment by robmadole** [comment]
Very sorry, @hypeJunction and all! They've (Cloudsmith) let us know that they have all hands on deck to get this fixed. We'll report details here: https://status.fortawesome.com/incidents/qw0hgjnyy7bt

**Comment by hypeJunction** [comment]
Our CI/CD pipelines are unhappy, but seems to be better now.
