### ISSUE TITLE
Icon request: three-directions and one-flow-direciton

### ISSUE THREAD

**Issue by csouza95** [FortAwesome/Font-Awesome#16159]
**What can it be used for?**
My case I want to use it to explain various flow types
> To _three-directions_: Where it began from only one branch and end on different branches;
> To _one-flow-direction_: For explain a flow that began from one branch and terminate on same branch;
> A variant to three-directions is a opposite of it, where it begin from many branches and terminate as one only.

**Example image (optional)**
three-directions:
https://www.iconfinder.com/icons/2115399/business_decisions_decision_decision_making_decisions_directions_icon
https://iconscout.com/icon/directions-43
one-flow-direction:
https://www.onlinewebfonts.com/icon/522335

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
