### ISSUE TITLE
Icon request: cmm

### ISSUE THREAD

**Issue by csouza95** [FortAwesome/Font-Awesome#16161]
**What can it be used for?**
> Coordinates Measuring Machine (CMM).
> Used to explain a equipment or tool from measuring rooms.
> To variants we want specific icons from measuring and material analyses labs
>> pull-out test;
>> weld-macrography test;
>> traction test;
>> weld-ultrasound test;
>> measuring tape;
>> scan arm measuring machine;

**Example image (optional)**
> https://measurement-solutions.co.uk/img/cmmsoftware_1.jpg
> https://static.renishaw.net/media/thumbnails/240high/c0e2356215464383866885ef368f593c.jpg

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Any single color example suitable for small icon size (16px)?

**Comment by csouza95** [comment]
A good exempla is it:

![image](https://user-images.githubusercontent.com/60274917/74166571-8b124800-4c05-11ea-8a48-932af393ed19.png)

**Comment by tagliala** [comment]
Thanks

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
