### ISSUE TITLE
New cookie issue in Chrome

### ISSUE THREAD

**Issue by cadilhac** [FortAwesome/Font-Awesome#16162]
Chrome has changed how it deals with cross-site cookies. So now I see a new message in the console when visiting my web site that uses fontawesome:

> A cookie associated with a cross-site resource at http://fontawesome.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`.

Do you plan to do something?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Do you plan to do something?

This should have been already fixed, as per https://github.com/FortAwesome/Font-Awesome/issues/15643#issuecomment-551365537

> So now I see a new message in the console when visiting my web site that uses fontawesome:

Please note that you see this message because you have visited fontawesome.com, and does not have impact on users that only visited your website

In order to fix this, you should delete your cookies related to fontawesome.com

This is a duplicate of #15643, please take a look there if you need more information

Closing here
