### ISSUE TITLE
Icon request: fa-locks

### ISSUE THREAD

**Issue by peps** [FortAwesome/Font-Awesome#16167]
**What can it be used for?**
This icons would be used for Password Confirmation form fields. 

**Icon request checklist**
- I'm thinking it would just be a large lock, with a small lock bottom corner or a large lock, with a small refresh icon.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry for the late reply.

Any idea of how this icon should look like?

**Comment by peps** [comment]
Maybe 2 locks overlapping eachother. Like the Clone icon, but with locks. 

https://fontawesome.com/icons/clone?style=solid

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
