### ISSUE TITLE
Icon request: icons oriented to academic world

### ISSUE THREAD

**Issue by gmw-web** [FortAwesome/Font-Awesome#16176]
It would be nice to have some more icons oriented to the **academic** world.

For example:
- Education (globe with graduation cap?)
- Professor
- Scientist (more lab oriented version of professor)
- (Study) desk
- Student (user with glasses?)
- Homework (stack of school books/papers/etc with a light above it? or a book with a reading glass?)
- Studying (user at a desk reading?)
- Case study (clipboard with graph/
- University (current university icon looks more like a roman temple than a university building)
- Open Science Framework (brand icon)
- Etc.

---

Some difficult ones:
- Online study
- Lab study
- Data collection

These last few could depicts a study in which participants take part either online or in a lab space. The goal of such a study is to gather data for scientific research.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
