### ISSUE TITLE
Icon Request: user-with-pills

### ISSUE THREAD

**Issue by Ideographik** [FortAwesome/Font-Awesome#16196]
**What can it be used for?**
Describe how this could be used / the use case for this icon.
We are graphic designers working on "design for all". We w ant to enrich and develop a common global library of icons to be used in the care sector and understandable by people with sensory and cognitive deficiency, but adaptable to specific countries - in this case France. This icon is to remind people to take their medicine.

**Example image (optional)**
Insert the example image here if necessary.
![eatpills-1](https://user-images.githubusercontent.com/60878308/74530562-a0031a00-4f2a-11ea-8a1d-a0c15cfe0175.png)
![eatpills-2](https://user-images.githubusercontent.com/60878308/74530577-a5f8fb00-4f2a-11ea-9ede-06942a642796.png)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
