### ISSUE TITLE
Icon request: Backup icon

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#1620]
Requesting a Backup icon to add.

![Backup icon](http://icons.iconarchive.com/icons/mcdo-design/smooth-leopard/256/Backup-Folder-Blue-icon.png)

**Comment by jasperf** [comment]
Yeah, would be great to have too.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
