### ISSUE TITLE
Icon request: Currency Polish Zloty

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#1621]
Icon request: Currency Polish Zloty

----> zł

http://en.wikipedia.org/wiki/Polish_złoty

**Comment by paulbreslin** [comment]
+1

**Comment by gerdald** [comment]
+1

**Comment by stoem** [comment]
yes please

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
