### ISSUE TITLE
fontawesome files not working on my server

### ISSUE THREAD

**Issue by armengeo** [FortAwesome/Font-Awesome#16223]
Hello All,

I have downloaded fontawesome-free-5.6.1-web.zip from https://github.com/FortAwesome/Font-Awesome/releases/tag/5.6.1 and unzipped it on my server. 

It seems that the following works https://www.247defensivedriving.com/0newsite/test.php

However this does not https://www.247defensivedriving.com/0newsite/test2.php

The only difference is the path to the all.css file.

Please advise. Thanks.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please check your browser development console.

You can find the following error:

```
Failed to find a valid digest in the 'integrity' attribute for resource 'https://www.247defensivedriving.com/0newsite/css/fontawesome-free-5.6.1-web/css/all.css' with computed SHA-256 integrity 'itJ72h1A/bbVx311d3UOsTSq0/gWJpyV2Ei6yVQze+I='. The resource has been blocked.
```

This means that you are using the same integrity checksum of the CDN css resource, but the files are different, because `test2.php` is not using the minimized version of all.css

My advices:

1. Use the minified all.css
2. Remove the `integrity` and `crossorigin` attributes from the tag if you are hosting the css file on your own server

Hope it helps

Closing here

**Comment by armengeo** [comment]
That worked.  Thank you.
