### ISSUE TITLE
fab fa-instagram-square is not working

### ISSUE THREAD

**Issue by avatar8** [FortAwesome/Font-Awesome#16227]
fab fa-instagram-square is listed as a free icon, but it doesn't work. An example can be seen at http://www.dominet.ca/whiteclaw/ where the Instagram icon should be appearing between the Facebook and Twitter icons.

No CDN will work including anything generated from the fontawesome website.

The only way to get the icon to appear is by including the complete fontawesome library with the site files (hosting locally).

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please note that [fa-instagram-square](https://fontawesome.com/icons/instagram-square?style=brands) has been introduced in FA 5.12.1, but the above website is using FA 5.7.0.

Please update links to the CDN

Please also remove the reference to `brands.css`, because they are included in `all.css`

Hope it helps

Closing here
