### ISSUE TITLE
Icon Request: icon-question-mark

### ISSUE THREAD

**Issue by emilyrose23** [FortAwesome/Font-Awesome#16239]
Icon would be used to describe level of data privacy, in this case Anonymous. (requesting Anonymous, Confidential, non-confidential). I created the icon in Word.

![anonymous](https://user-images.githubusercontent.com/61434980/75190187-60e87c00-5715-11ea-922e-5b4786651b82.png)
![image](https://user-images.githubusercontent.com/61434980/75190210-6e056b00-5715-11ea-8f70-94b7cc6b317c.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We have a couple of icons that could fit this use case:
- https://fontawesome.com/icons/user-secret?style=solid
- https://fontawesome.com/icons/mask?style=solid

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering feature of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/312/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
