### ISSUE TITLE
Icon request: Industrial Floor Cleaning

### ISSUE THREAD

**Issue by martindubenet** [FortAwesome/Font-Awesome#16234]
**What can it be used for?**

- Illustrate heavy duty janitorial cleaning,
- Industrial floor waxing,
- Industrial sweeper.

**Proposed images**

- The zip file contains the 3 SVG icons with complete un-flatten layers (for you to adjust it as it please).
- The original Illustrator file.

## Attached icons

- **[Industrial-sweeper_Original-Light-Regular-Solid.zip](https://github.com/FortAwesome/Font-Awesome/files/4243124/Industrial-sweeper_Original-Light-Regular-Solid.zip)**
- ![icon_industrial-sweeper_fa-light](https://user-images.githubusercontent.com/4236385/75129607-ae260880-5697-11ea-9375-ed39de722ff6.png)
- ![icon_industrial-sweeper_fa-regular](https://user-images.githubusercontent.com/4236385/75129656-e88fa580-5697-11ea-9c8d-fa87f56775ec.png)
- ![icon_industrial-sweeper_fa-solid](https://user-images.githubusercontent.com/4236385/75129612-b2522600-5697-11ea-88b0-07cb06427bb8.png)

**Comment by martindubenet** [comment]
Regarding copyrights, I designed these icons myself. Use them as you want.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
