### ISSUE TITLE
404s after switching to SVG version

### ISSUE THREAD

**Issue by Deralict** [FortAwesome/Font-Awesome#16276]
Since I switched to the SVG version, I always get these 404 errors showing up in the console, generated by https://kit-pro.fontawesome.com/releases/latest/js/pro.min.js. How can I eliminate them?
<img width="743" alt="Screenshot 2020-03-05 11 47 26" src="https://user-images.githubusercontent.com/13838253/76020084-a5bfa000-5ed7-11ea-8877-67a4c4944dfd.png">

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

As I can see from the screenshot, you are trying to access brand icons with the solid style.

Please make sure you are using the proper syntax, `fab fa-google-plus` instead of `fas fa-google-plus`, note the fa**b** instead of fa**s** prefix

Docs: https://fontawesome.com/icons/google-plus?style=brands

Hope it helps

Closing here, but feel free to comment if this doesn't help
