### ISSUE TITLE
Icon request: home-pound / home-dollar

### ISSUE THREAD

**Issue by LiamSpence-DCC** [FortAwesome/Font-Awesome#16290]
**What can it be used for?**
Cost of Housing / Council tax / Home expenses

**Example image (optional)**
Insert the example image here if necessary.
![https://www.n-kesteven.gov.uk/_resources/assets/inline/custom/5/51733.jpg](https://www.n-kesteven.gov.uk/_resources/assets/inline/custom/5/51733.jpg)
https://www.n-kesteven.gov.uk/_resources/assets/inline/custom/5/51733.jpg

**Icon request checklist**
- [Match] The is a matched icon, it could use a Pound symbol, and a Dollar symbol.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please split this request in two separate ones?

We have a lot of currencies, and pound and dollar are related as much as euro/pound, jpy/dollar, and any other combination of currencies

Also, you can create an icon that could fit this use case by using the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/327/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
