### ISSUE TITLE
Icon request: Per Time/Distance Icon

### ISSUE THREAD

**Issue by Arniox** [FortAwesome/Font-Awesome#16305]
**What can it be used for?**
This can be used for input or output for per hour, per meter, per km and etc.

**Example images (optional)**
![Per Hour](https://user-images.githubusercontent.com/26326378/76472462-7a4e2f80-645a-11ea-978f-6a6173d5389f.png)
![Per Km](https://user-images.githubusercontent.com/26326378/76472700-33ad0500-645b-11ea-9136-b187a7529f17.png)
![Per Second](https://user-images.githubusercontent.com/26326378/76472702-34459b80-645b-11ea-8730-66db26e9308e.png)
![Per Min](https://user-images.githubusercontent.com/26326378/76472704-34de3200-645b-11ea-8c90-23911a98f8a1.png)
![Per Day](https://user-images.githubusercontent.com/26326378/76472706-34de3200-645b-11ea-9348-803e45e03f8d.png)

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think this can be implemented with the layering feature of the SVG framework

Ref: https://fontawesome.com/how-to-use/on-the-web/styling/layering
Demo: https://jsfiddle.net/tagliala/L17f528g/332/

Since this:
- is a request for a set
- there are a lot of units
- units depend on country
- day is an English word (and we try to avoid words in icons)
- including letters at 16px icon size is difficult

I'm going to close here for the moment
