### ISSUE TITLE
Request for TfL Brand Icons

### ISSUE THREAD

**Issue by ezeikel** [FortAwesome/Font-Awesome#16325]
Wondering If the following icons can be added:
- Tube
- London Overground
- DLR
- TfL Rail
- National Rail

Examples here: https://tfl.gov.uk/plan-a-journey

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

There are some duplicates: #11815

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

If you are a Font Awesome Pro customer, you can request for icon sets in the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro?

If you are a Font Awesome Pro customer, and you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Closing here
