### ISSUE TITLE
Icon request: Expand user-graduate set to include user variations

### ISSUE THREAD

**Issue by mouseball-ca** [FortAwesome/Font-Awesome#16341]
**What can it be used for?**
The standard user icons have variations such as user-times, user-plus, user-lock, user-unlock, user-cog and user-tags. It would be font awesome if these variations were also available for the user-graduate icon. Primary use case would be education applications

Many Thanks for your considerations :)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

--

If you are a Font Awesome Pro customer, you can request for sets in the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro

If you are a font Awesome Pro customer and you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

--

Also, please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/339/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

Closing here
