### ISSUE TITLE
Icon Request : Reduce (invert of expand) icon

### ISSUE THREAD

**Issue by Nabellaleen** [FortAwesome/Font-Awesome#1635]
icon-expand exists, with an arrow to the right, but it could be nice to have also the expand to the left.

It could be named "icon-reduce" or "icon-collapse-left".

(I can't use icon-rotate-180 in IE7, so no, it's not an answer :p)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
