### ISSUE TITLE
Unlink icon not render with unicode in html

### ISSUE THREAD

**Issue by Xarkam** [FortAwesome/Font-Awesome#16360]
Hello, I try to use[ unlink icon](https://fontawesome.com/icons/unlink?style=solid) from free solid . But I can't obtain the icon. See my code after.
Css:
```css
select {
    font-family: "Font Awesome 5 Free";
    font-weight: 900;
}
```
Html:
```html
<select class="form-control" id="availableRoles">
    <option disabled="" selected="" value="0"> -- select a role -- </option>
    <option value="Administrator">&#xf007; Administrator</option>
    <option value="User">User</option>
    <option value="Anonymous">&#xf127; Anonymous</option>
</select>
```
Render:
![image](https://user-images.githubusercontent.com/331816/77438620-58539600-6de6-11ea-883d-78378e913d8f.png)

What am I doing wrong?

Fontawesome version: lastest 5.13.0
Thanks.

**Comment by esoyke** [comment]
Nor is it now working from CSS. This was working for me in v4, version 5 upgrade broke unicode, at least on the free library.

https://codepen.io/esoyke/pen/ZEGZdvr

**Comment by tagliala** [comment]
@Xarkam 

Sorry for the late reply. We never supported this usage and we strongly advise to use a javascript plugin for this use case because the above implementation is not cross-platform compatible.

Ref: #996

Hope it helps

---

@esoyke 

- Please remove `https://static.fontawesome.com/css/fontawesome-app.css` from the assets, it is the style for the font awesome website
- The codepen is loading Font Awesome Pro css, but css is referencing to `Font Awesome Free`

Fixed pen: https://codepen.io/tagliala/pen/yLNWOOB

Docs: https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements

Closing here

**Comment by tagliala** [comment]
@esoyke you're welcome, glad you solvede
