### ISSUE TITLE
Icon request: leads

### ISSUE THREAD

**Issue by Daniel4Digital** [FortAwesome/Font-Awesome#16399]
**What can it be used for?**
I miss financial icons, icons for representing:

All Leads - funnel-dollar (already exists, and could be used)
New Leads - funnel-dollar
Returning/Old Leads - funnel-minus

Tracked Leads - funnel-map-marker/funnel-map-marker-alt
New Tracked Leads - funnel-map-marker-dollar
Returning/Old Tracked Leads - funnel-map-marker-minus

Untracked Leads - funnel-map-marker-slash/funnel-map-marker-alt-slash
New Untracked Leads - funnel-map-marker-dollar-slash
Returning/Old Untracked Leads - funnel-map-marker-minus-slash

Total Investment
Tracked Investment
Untracked Investment

Total Revenue
Tracked Revenue
Untracked Revenue

A funnel can represent the leads very well, so it could be a start for creating more funnel ones.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> This is a single icon or matched pair (Ex: lock / unlock)

This doesn't look like a single icon, could you please clarify?

**Comment by Leinad4Mind** [comment]
It's a multiple matched pair.
I just didn't want to flood with many match pairs.
By the names I give it's simple to understand the mixed of font awesome icons that already exists, but could be mixed. Or someone could have a better idea and create something better that would represent each one of those icons.

**Comment by Daniel4Digital** [comment]
instead of flooding with requests, since its all related, I asked all on the same issue. Makes more sense to me.

The icons would be:
funnel-plus
funnel-minus
funnel-map-marker
funnel-map-marker-alt
funnel-map-marker-dollar
funnel-map-marker-plus
funnel-map-marker-minus
funnel-map-marker-slash
funnel-map-marker-alt-slash
funnel-map-marker-dollar-slash
funnel-map-marker-plus-slash
funnel-map-marker-minus-slash

As you can see its all matched pairs, following the same idea as funnel-dollar (that already exists)

BUT, if someone has a better idea to develop new icons to represent all the above cases, I am all ears.

**Comment by tagliala** [comment]
> instead of flooding with requests, since its all related, I asked all on the same issue. Makes more sense to me.

Sorry, this is not possible, since this is a request for 60 new icons. Feel free to open individual requests of strictly paired icons. Please also provide examples

Please also consider using simpler icons and composition, by using the SVG framework with the features I've mentioned before:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

If you are a Font Awesome Pro customer, you can request sets in the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
