### ISSUE TITLE
Wordpress Plugin Activation fails: Your WordPress server failed trying to send a request to the Font Awesome API server.

### ISSUE THREAD

**Issue by dan91** [FortAwesome/Font-Awesome#16395]
**Describe the bug**
When trying to activate the Font Awesome Wordpress plugin, I get the error:
```
Plugin could not be activated because it triggered a fatal error.
The Font Awesome plugin caught a fatal error: Font Awesome could not be activated.
Your WordPress server failed trying to send a request to the Font Awesome API server.
```

**Version and implementation**
Plugin: 4.0.0-rc19
Wordpress: 5.3.2
PHP: 7.0.33
OS: Ubuntu 16.04

**Comment by tagliala** [comment]
@mlwilkerson could you please take a look here?

**Comment by mlwilkerson** [comment]
Hi @dan91. Thanks for the report.

This error might happen if your WordPress server is not connected to the internet, or if your hosting or internet service provider has blocked something that needs to be allowed, or if your PHP installation on which WordPress depends lacks adequate extensions (such as `openssl` with an appropriate cipher) in order to make a secure request to the Font Awesome API server.

In any case, there should be some additional, more detailed diagnostic output on your web browser's JavaScript console (or Web Console) after this fatal error is shown in WordPress admin. Could you let me know what information you find in that console?

Here's another diagnostic you could try, if you have shell access to your server, or you could provide this to your hosting provider as a reference point for what you need to work on your server. You should able to run this command:

```
curl -H "Content-Type: application/json" --data '{ "query": "{ release(version: \"latest\") { version } }" }' https://api.fontawesome.com
```

and see a result that looks like this:

```
{"data":{"release":{"version":"5.12.1"}}}
```

**Comment by futandrew** [comment]
> 

I am having the same problem. I think this is because of my server provider's problem. 
`curl: (7) Failed to connect to api.fontawesome.com port 443: Connection refused`

However, is there a way I can bypass this and use my own API and or kit on the server instead? Thanks.

**Comment by mlwilkerson** [comment]
@futandrew no, this plugin requires connection to the Font Awesome API server to retrieve metadata about available icons and releases. It also uses the API server for icon search, and for discovering your kits and their configurations if you connect your Font Awesome account with an API token. If your webhost server configuration is such that it cannot connect to the Font Awesome API server, and you can't have that server configuration changed, then it means that this plugin is not compatible with your WordPress server setup.

You can still use Font Awesome on WordPress, including Kits, including Font Awesome Pro, just not using this plugin.

[Here is documentation](https://fontawesome.com/docs/web/use-with/wordpress/install-manually) about another approach you could take: manual installation on WordPress.
