### ISSUE TITLE
Icon request: Warrant

### ISSUE THREAD

**Issue by nikid506** [FortAwesome/Font-Awesome#16423]
**What can it be used for?**
Describe how this could be used / the use case for this icon.
To represent our enterprise web application called "warrants"

**Example image (optional)**
attached

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`) no
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`) warrant
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate - found a similar topic and the icon would have been suitable but I didn't know how to get it.
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺) yes

**Comment by tagliala** [comment]
@nikid506 sorry, can't see the attached image

**Comment by nikid506** [comment]
Here you go

**Comment by tagliala** [comment]
@nikid506 sorry again... email attachment don't work. Please paste your image on github at: https://github.com/FortAwesome/Font-Awesome/issues/16423

**Comment by nikid506** [comment]
the files will not upload.  here are links to examples
https://www.iconfinder.com/icons/614472/document_expenses_fine_forfeit_penalty_warrant_icon
https://www.iconfinder.com/icons/1837660/diploma_document_grant_hand_warrant_icon

**Comment by tagliala** [comment]
@nikid506 thanks for the example.

We have a very similar icon in FA Pro: `file-certificate` https://fontawesome.com/icons/file-certificate?style=solid

Could you please clarify why `file-certificate` does not work for your use case and you need exactly the design in the example?

**Comment by nikid506** [comment]
Yes that will be fine.  I also need one to represent a court case, but I’m already using the plain briefcase for something else.  Do you have anything similar to this?
https://fontawesome.com/icons/business-time?style=regular

**Comment by nikid506** [comment]
Good Morning,
Do you have anything that represents networking of people, job, employment etc.

**Comment by tagliala** [comment]
@nikid506 

> Yes that will be fine.  

Ok, but I need to close here, since the icon is already present in the Pro set. If you want to know why that icon is in Pro rather than Free, please take a look here https://fontawesome.com/community/leaderboard/new#faqs

---

> Yes that will be fine.  I also need one to represent a court case, but I’m already using the plain briefcase for something else.  Do you have anything similar to this?
https://fontawesome.com/icons/business-time?style=regular

You can create that icon in Font Awesome Free by using the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/366/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

---

> Do you have anything that represents networking of people, job, employment etc.


Please use the search on both font awesome and on the issue tracker to see if there is any icon or request that fits your need

useful links:
- https://fontawesome.com/icons?d=gallery&s=solid&c=business&m=free (Free Business Icons)
