### ISSUE TITLE
pakistan

### ISSUE THREAD

**Issue by ijazmrd** [FortAwesome/Font-Awesome#16456]
`<img src="
![Desert](https://user-images.githubusercontent.com/30998544/79040361-4d2fa100-7c01-11ea-9fa1-b60c66cd622d.jpg)
"/>

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
