### ISSUE TITLE
Icon request: temperature-medium

### ISSUE THREAD

**Issue by marceloverdijk** [FortAwesome/Font-Awesome#16515]
Currently there is a ` temperature-high` and `temperature-low` icon.
It would be nice to include a `temperature-medium` icon to indicate not cold not warm.

This would be similar to the existing `thermometer-full`, `thermometer-half` and `thermometer-empty` icons (which also have more variants than only the boundaries).

And even more visually, maybe `temperature-normal` could also be introduced to accompany `temperature-hot` and `temperature-frigid` maybe?

This would give application indicating temperature's more options.

And I think the most building blocks to introduce these icons are there.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome! [Take a look at it here.](https://fontawesome.com/icons/temperature-half?f=classic&s=solid)
