### ISSUE TITLE
Icon Request: fa-flower-edelweiss

### ISSUE THREAD

**Issue by Ddorf965** [FortAwesome/Font-Awesome#16517]
Hi We want to use an edelweiss as Icon.
Could you create this for us?
![Cermony Favicon](https://user-images.githubusercontent.com/54677936/80202149-7f8bc600-8625-11ea-967e-5e974ec1e5a0.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
