### ISSUE TITLE
fa-instagram-square doesn't appear

### ISSUE THREAD

**Issue by maucel89** [FortAwesome/Font-Awesome#16521]
Hi,

When I try to use fa-instagram-square it doesn't appear anything.

You can see from my site url:
http://maucel89.altervista.org/guide/renders/render4/test-social-icons.php

**Version and implementation**
Version: I tried with 5.12.0 and 5.13.0
Browser and version: All browser

- [ ] SVG with JS
- [X] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Comment by tagliala** [comment]
Ciao!

Thanks for being part of the Font Awesome Community.

> Version: I tried with 5.12.0 and 5.13.0

Instagram square icon has been introduced in version 5.12.1, and at the moment I can see 5.12.0 on the website. Please make sure to update both the css and the webfont files

Hope it helps

Closing here

**Comment by maucel89** [comment]
![D7033BCC-C647-4DDF-8B47-7422D5573D68](https://user-images.githubusercontent.com/6852253/80274796-4020b080-86dd-11ea-9c4b-27dff4f55064.jpeg)
Where you can see Instagram square icon?

**Comment by tagliala** [comment]
@maucel89 

By inspecting your website, I can see that it is loading a self-hosted version of FA 5.12.0

![image](https://user-images.githubusercontent.com/556268/80275582-8d535100-86e2-11ea-89be-bd75f80d3d05.png)

FA 5.12.0 does not incldue `fab fa-instagram-square`, you need at least FA 5.12.1 

Please make sure that your website is loading a newer version of both css and webfont filers.

Also, check if the cache properly expires old assets: since filenames are not fingerprinted, it should generate new `ETag`s

**Comment by maucel89** [comment]
![Schermata 2020-04-20 alle 18 11 05](https://user-images.githubusercontent.com/6852253/80280500-c56b8b80-8704-11ea-91bf-37a2b1d18089.png)
You're right, I updated the cache and now I see a japan icon.

**Comment by tagliala** [comment]
@maucel89 probably you forgot to update the font files in `webfonts` folder

This refers to the [svg version](maucel89.altervista.org/guide/renders/render4/font/fontawesome/fa-brands-400.svg), so you may have updated woff2, but please check

![image](https://user-images.githubusercontent.com/556268/80280944-ceaa2780-8707-11ea-8017-3a117f0dbc42.png)

**Comment by tagliala** [comment]
Ref: https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself#using-web-fonts

**Comment by maucel89** [comment]
Clear, thank you for your precious support.

**Comment by tagliala** [comment]
@maucel89 di niente 👍
