### ISSUE TITLE
Is npm.fontawesome.com down?

### ISSUE THREAD

**Issue by bolyesz** [FortAwesome/Font-Awesome#16540]
**Describe the bug**
Failing builds on build agents since last Thursday (23.4.2020)

`An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/fontawesome-pro/-/5.13.0/fontawesome-pro-5.13.0.tgz: read ECONNRESET".`

**To Reproduce**
https://downforeveryoneorjustme.com/npm.fontawesome.com reports that it's down for everyone, but https://status.fortawesome.com/ reports that npm.fortawesome.com is operational

**Expected behavior**
Builds won't fail

**Screenshots**

**Version and implementation**
Version: 5.13.0

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Failing builds on build agents since last Thursday (23.4.2020)

Cannot replicate here at the moment

Please check if it is reachable from your browser at https://npm.fontawesome.com/

Also, please send an email to hello@fontawesome.com with a link to this thread, so you don't need to explain the situation again. Someone from the Pro Team should follow up and ask to provide some command line logs

> https://downforeveryoneorjustme.com/npm.fontawesome.com  reports that it's down for everyone

This is expected, because npm.fontawesome.com is a private repo and returns a 401 error message for unauthorized users. According to the service used to check, it may interpret 401 as an error and answer with "yes, it is down"

Example from https://www.uptrends.com/tools/uptime

![image](https://user-images.githubusercontent.com/556268/80480841-aa418b80-8951-11ea-8857-0d7e369ace31.png)

I'm going to close here, but feel free to comment
