### ISSUE TITLE
Icon-request: chalkboard-teacher-slash

### ISSUE THREAD

**Issue by interduo** [FortAwesome/Font-Awesome#16544]
**What can it be used for?**
We use that icon to mark people as verifier. We assign that function and deassign.

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by interduo** [comment]
> Demo: https://jsfiddle.net/tagliala/L17f528g/389/

The first type of slash is ok for that icon. (the demo showes other icon)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
