### ISSUE TITLE
Icon request: audit

### ISSUE THREAD

**Issue by daynemay** [FortAwesome/Font-Awesome#16549]
**What can it be used for?**

An "audit" icon could be useful in navigating to or representing a section of any application that provides audit capability. In the context of my particular use case, I'm referring to the audit of server log files. 

An audit icon might also be useful in the context of a financial audit.

**Example image (optional)**
<img width="354" alt="audit_done_poorly" src="https://user-images.githubusercontent.com/834477/80614303-aa568f80-8a14-11ea-8c5a-cf2afcf78592.png">

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Does https://fontawesome.com/icons/file-search?style=solid fit your use case?

**Comment by daynemay** [comment]
Thank you! That's certainly the best suggestion we've had - "audit" was a bit of a head-scratcher! I'll take it to my team to discuss.

I _had_ [searched for "search"](https://fontawesome.com/icons?d=gallery&q=search), since we current use an icon very similar to the plain [search](https://fontawesome.com/icons/search?style=solid) "magnifying glass" icon. But clearly I failed to notice the suitability of [file-search](https://fontawesome.com/icons/file-search?style=solid) among the results.

**Comment by tagliala** [comment]
You're welcome, I should have renamed this as `align-justify-search`

If that icon fits your use case, please close this issue. Since it is already present in FA Pro, I cannot leave this request open in the free repo for the moment (I should mark it with "Available in FA Pro" and close).

Also, you can achieve similar icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/396/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering
