### ISSUE TITLE
Icon request: fa-e or fa-internet

### ISSUE THREAD

**Issue by FGIKCM** [FortAwesome/Font-Awesome#16542]
Icon for all "internet" things (like e-business, e-paper, ...)

It should looks like the `@` icon, but with a `e` instead of the `a`

**Icon request checklist**
- [X] This is a single icon
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Icon for all "internet" things (like e-business, e-paper, ...)

Do you have an existing use case for this icon? Iw would help because at the moment letters are out of scope.

I have this #2828 open for +1s but temporarily labeled as wontfix

**Comment by FGIKCM** [comment]
Hello,

uses cases on my company: all the "old paper things" that everybody want now on our Intranet. For example : "Contract Check-List", signed before by hand, transformed on "e-Contract Check-List" with electronic signature.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
