### ISSUE TITLE
Icon request: fa-ron (code currency for romanian leu)

### ISSUE THREAD

**Issue by james-rolon** [FortAwesome/Font-Awesome#16558]
**What can it be used for?**
Describe how this could be used / the use case for this icon.

This icon is to represent the Romania currency of RON.  

**Example image (optional)**
it would literally just be: RON (can be outline or filled)

**Icon request checklist**
- [x] This is a single icon
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We prefer to use unicode currency symbols rather than ISO codes, eg: `€` instead of `EUR`. At the moment, [we don't have currencies with code](https://fontawesome.com/icons?d=gallery&q=currency&s=solid).

I can leave individual requests about currency codes open (e.g.: #10896) but I'm asking if this can be turned in a request for leu `L` symbol

**Comment by james-rolon** [comment]
Good Morning,

Yes we can definitely turn this request into a request for the leu L symbol.

Please let me know the next steps I need to take to move forward in the process.

Thanks in advance.

James R

**Comment by tagliala** [comment]
Hi @james-rolon you're welcome

> Please let me know the next steps I need to take to move forward in the process.

There is no much else you can do You may be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work.

You may also be interested in [Customizing Font Awesome](https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome)

**Comment by james-rolon** [comment]
Good Morning,

I just had a conversation with a Romanian citizen and he informed that the official bank of Romania uses RON and they don’t use or have an official symbol of leu L. 

With that being said is it still possible for your team to create a font awesome icon for Romania RON?

**Comment by tagliala** [comment]
> With that being said is it still possible for your team to create a font awesome icon for Romania RON?

I can rename the request

About the customization, you are free to do anything you want

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
