### ISSUE TITLE
Icon request: menstruation

### ISSUE THREAD

**Issue by danrydell** [FortAwesome/Font-Awesome#16564]
I am requesting a women's period icon (as opposed to men's period; we've all had that, mine was the 80's)

**What can it be used for?**
Besides the more informal situations, I was recently developing an online shop, and we had to make our own icons for women (that ever present half of the human race) related issues, FA was enough for the other categories, but this icon would have been handy.
We have icons for coughs and allergies, toilet paper, plus more gender icons than average folk can name. I think it would be a great addition to have the **period** icon; and while we are at it, also **tampons**, **women pads**, **moon cups** and **hoosier belts** (though I am not sure if the ladies still favor these ones).

In regards to design, and foreseeing suggestions that we have the **tint** icon,  bear with me: 

Back in 2017 Plan UK polled people for a period emoji.
This is the one that won the poll and got submitted to the consortium:
![image](https://user-images.githubusercontent.com/2573185/80834321-c878e700-8bf0-11ea-9bac-5f91e912ac5e.png)

This were the options:
![image](https://user-images.githubusercontent.com/2573185/80834464-0fff7300-8bf1-11ea-8ef7-bd755d5ae46b.png)

And the consortium chose none of the above, but came up with its own:
![image](https://user-images.githubusercontent.com/2573185/80834591-4c32d380-8bf1-11ea-949c-fec9b2b5343b.png)

Which as you can see says period much like this one,

![image](https://user-images.githubusercontent.com/2573185/80834731-91ef9c00-8bf1-11ea-8501-fbdb81c99ffe.png)

spells horse.

A drop of blood is more versatile, nothing to argue here, it means period, blood, wound, donation, vampire booze and many other things. But I would like to challenge the effectiveness of a multiple interpretations icon as an icon. I can just see the texts: 

![period](https://user-images.githubusercontent.com/2573185/80835746-afbe0080-8bf3-11ea-9013-04f509386c4f.jpg)

Be that as it may, I would like to insist also on the aforementioned _women's products_ (should I request them separately?) in the hopes that no one suggests they should be covered with the **band-aid** icon. 

Thank you :o)

**Icon request checklist**
- [X] This is a single icon
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We already have a `drop` icon, [fa-tint](https://fontawesome.com/icons/tint?style=solid), you can choose the color you want

Demo: https://jsfiddle.net/tagliala/y693z45a/15/

Does it work for your use case?

**Comment by danrydell** [comment]
Thank you for that suggestion, but no. That's just what I was referring to, the drop icon is inespecific and misleading; I grant you that, for lack of a better icon, this is the closest and for the while it will do, but I contend there should be a more appropriate one; and/or various ones.

:O)

**Comment by tagliala** [comment]
Thanks for the clarification.

I didn't get if you are suggesting a specific icon to implement. It would be helpful to add it in the title, because:

> The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

Menstruation is quite abstract and `fa-tint` may fit the use case.

If you are open to suggestions, I can leave add the `waiting for feedback` label and wait for feedback from the community

> That's just what I was referring to, the drop icon is inespecific and misleading; 

Sure, but IMHO it also depends on the context in which you are showing the icon.

> Be that as it may, I would like to insist also on the aforementioned women's products (should I request them separately?)

Yes, please. Also provide a single color example for each request, and use the concrete object as title where available (let's avoid `period`/`woman-period`)

PS: with power transforms, masking, and layering features of the SVG Framework, you can stack `calendar` and `tint` to implement another icon that may better fit this use case:

Demo: https://jsfiddle.net/tagliala/y693z45a/23/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because the request is not specific enough. Ideally, we'll be able to include a collection of icons related to this topic in the future.
