### ISSUE TITLE
fa-spinner fa-spin override of defined fa-$iconName

### ISSUE THREAD

**Issue by WHMCSChance** [FortAwesome/Font-Awesome#16616]
Looking for a little help here with an issue I am seeing.

I am currently utilizing the fa-upload icon for a button and when the button is clicked, we add fa-spinner fa-spin to the class name.  Currently, it is not overriding the fa-upload icon to fa-spinner.  It simply spins the fa-upload icon instead.  I have changed to other icons we use that I know work in this manner like fa-arrow fa-sign-in fa-cog and these get overridden with fa-spinner and then that icon spins until the action is completed and then returns to the defined icon for the button.

Are there specific/certain icons that will not be overridden in the manner outlined above?

Here is an example of what were seeing:

`<i class="fas fa-upload fa-fw"></i>`

Then we append the fa-spinner fa-spin to the class:

`<i class="fas fa-upload fa-fw fa-spinner fa-spin"></i>`

In this case, it will continue to display the fa-upload icon and spin it but other icons (as noted above) will change to fa-spinner and then spin that and then when we remove the fa-spinner fa-spin class it reverts back to the original icon.

Ive scoured the interwebs for anything I can find on this and coming up dry so any help here would be greatly appreciated.

Here is a POC from what I have found where it overrides some and others it does not:

https://codepen.io/whmcschance/pen/ZEbRvZL

Thanks!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

It happens because of cascading stylesheets: `upload` comes after `spinner`, so the last class found in the stylesheet has the priority. If you try `fa-virus`, you will experience the same expected behavior.

Also, Brands (or regular icons) will not spin because they have different `font-weight` and/or `font-family` and `fa-spinner` is only available with `fas` prefix in Font Awesome Free

If you want to implement this function by just adding and removing a single css class, which may preferable for your use case, you should go for a couple of lines of custom css

Demo: https://codepen.io/tagliala/pen/PoPaXYR

Does this help?

**Comment by WHMCSChance** [comment]
@tagliala This is exactly what I was looking for.  I just needed some context on why this was happening and I didn't even think to look in the defined CSS.

This helps tremendously and I appreciate the assist!
