### ISSUE TITLE
SpringBoot

### ISSUE THREAD

**Issue by avijitliberty** [FortAwesome/Font-Awesome#16658]
Please add icons for SpringBoot, SpringCloud etc.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please open new, individual requests (one for each brand) by filling out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

Please also add an example of the icon, it is not clear from https://spring.io/projects/spring-boot what is spring boot's icon and how it differs from springcloud
