### ISSUE TITLE
CSS3 Validation Warnings

### ISSUE THREAD

**Issue by 9mido** [FortAwesome/Font-Awesome#16652]
Fontawesome v5.13 has quite a few CSS3 validation warnings. Any chance these will get fixed anytime soon?

https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css

```
-moz-osx-font-smoothing is an unknown vendor extension
-webkit-font-smoothing is an unknown vendor extension
-webkit-animation is an unknown vendor extension
-webkit-animation is an unknown vendor extension
Unrecognized at-rule @-webkit-keyframes
-webkit-transform is an unknown vendor extension
-webkit-transform is an unknown vendor extension
-ms-filter is an unknown vendor extension
-webkit-transform is an unknown vendor extension
-ms-filter is an unknown vendor extension
-webkit-transform is an unknown vendor extension
-ms-filter is an unknown vendor extension
-webkit-transform is an unknown vendor extension
-ms-filter is an unknown vendor extension
-webkit-transform is an unknown vendor extension
-webkit-transform is an unknown vendor extension
-ms-filter is an unknown vendor extension
-webkit-transform is an unknown vendor extension
-webkit-filter is an unknown vendor extension
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Any chance these will get fixed anytime soon?

Sorry, those will not be fixed in FA 5 in the output CSS.

You can customize css to remove prefixes for the browsers you don't need

We are using Autoprefixer to generate browser prefixes according to our [compatibility matrix](https://fontawesome.com/how-to-use/on-the-web/other-topics/browser-support)

In FA6, `-ms-filter` and `-webkit-filter` should disappear, but, at the moment I'm writing, I cannot say the same for:
- `-moz-osx-font-smoothing`
- `-webkit-font-smoothing`
- `-webkit-animation`
- `@-webkit-keyframes`

Ref:
- https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth
- https://caniuse.com/#search=keyframes
- https://caniuse.com/#feat=css-animation

Hope it helps

Closing here
