### ISSUE TITLE
fa-instagram-square isn't in the latest cdn?

### ISSUE THREAD

**Issue by reptile18** [FortAwesome/Font-Awesome#16674]
**Describe the bug**
using the icon as described [here](https://fontawesome.com/icons/instagram-square?style=brands) brings up nothing.

If I open the cdn css file for version 5.8.1, it doesn't list fa-instagram-square

**To Reproduce**
use the cdn link https://use.fontawesome.com/releases/v5.8.1/css/all.css and your cdn embed code

**Expected behavior**
The icon should show up in that cdn file above (currently, it only contains fa-instagram, not fa-instagram-square

**Screenshots**

**Version and implementation**
Version: 5.8.1, according to the css 
Browser and version: 

- [ ] SVG with JS
- [X ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [X ] I have filled out as much of the above information as I can
- [X ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

fa-instagram-square has been introduced in version 5.12.1, as you can see in the docs page at https://fontawesome.com/icons/instagram-square?style=brands (top right in desktop view, just above the icon in mobile view)

Please use the latest CDN link to use instagram-square

Hope it helps

Closing here

**Comment by reptile18** [comment]
In the future, can the font awesome page list which starting version a particular icon is introduced in?

**Comment by tagliala** [comment]
We had this information in the [old cheatsheet](https://fontawesome.com/v4.7.0/cheatsheet/) but I cannot see it anymore.

@robmadole @talbs is there any other page with this information?

If it isn't, any chance to add the version as extra information in the search page together with the glyph unicode point?

I was thinking to something like this

![image](https://user-images.githubusercontent.com/556268/82377440-f00ae480-9a23-11ea-810f-0a4c116d0b8d.png)

(sorry for the poor paint skills)

![image](https://user-images.githubusercontent.com/556268/82377297-c356cd00-9a23-11ea-9488-e5c8ba598e34.png)

**Comment by robmadole** [comment]
@tagliala those are some nice MSPaint skills! ☺️

I've got this added to the work board. Oddly enough this has come up a few more times. So I've created a pitch to see if we can get some developer time on it.

**Comment by dakotalightning** [comment]
It's also missing from the desktop free and pro versions.

**Comment by tagliala** [comment]
@dakotalightning please clarify your issue, but before take look here:

> fa-instagram-square has been introduced in version 5.12.1, as you can see in the docs page at https://fontawesome.com/icons/instagram-square?style=brands (top right in desktop view, just above the icon in mobile view)

Desktop troubleshooting: https://fontawesome.com/how-to-use/on-the-desktop/other-topics/troubleshooting

**Comment by dakotalightning** [comment]
Hey @tagliala 

I've tried to install both versions of 5.13.0 pro and free. All the attempts have failed to show the icon.

**Comment by tagliala** [comment]
Hi @dakotalightning I think I can replicate, will manage this internally and let you know

**Comment by tagliala** [comment]
Hi @dakotalightning 

Please ignore my previous message (I've deleted it)

This issue is about the web version, while yours is about the Desktop one. 

Please try the following, and if you still are not able to fix, open a new issue by following our 
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)

1. Uninstall Font Awesome font files from your system
2. Restart your computer
3. Download 5.13.0 Desktop font files
4. Install the .otf font files
5. Make sure that your system is loading the correct version
![image](https://user-images.githubusercontent.com/556268/84121833-ea5b5a00-aa37-11ea-945a-d2d9cfc8e922.png)
6. Open your application of choice
7. Make sure that your application of choice is not caching fonts (search on google)
8. Select "Font Awesome 5 Brands Font Family"
9. Type `instagram-square` or copy the glyph from the website
![image](https://user-images.githubusercontent.com/556268/84122052-255d8d80-aa38-11ea-9c36-b0568134622d.png)
