### ISSUE TITLE
Icon request: vs (versus)

### ISSUE THREAD

**Issue by jbnv** [FortAwesome/Font-Awesome#16678]
The letters "VS." Abbreviation for "versus."

**What can it be used for?**
Sports, competitions.

I don't know how universal this abbreviation is, and there may be one that is more universal.

**Comment by aethior** [comment]
*Related Unicode Emoji* #222
🆚 [U+1F19A](https://emojipedia.org/emoji/%F0%9F%86%9A/) Vs Button

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
