### ISSUE TITLE
Instagram Square Icon

### ISSUE THREAD

**Issue by paulrds** [FortAwesome/Font-Awesome#16673]
Hi! I tried to set the Instagram square icon in my HTML and it does not show on the page. The others icons work fine, but this one does not.

The icon I'm talking about: https://fontawesome.com/icons/instagram-square?style=brands

Thank you for the amazing content that you guys have!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

It is most probably due because your application is running an older version of Font Awesome.

As you can see in the docs instagram-square has been added in FA 5.12.1. Please make sure that you are using FA 5.12.1 or newer

Please also note that some third-party plugins, themes, libraries may load an older version of Font Awesome that may take precedence over yours, double check that this is not the case

Hope it help

Closing here, but feel free to comment
