### ISSUE TITLE
Icon request: erd-crow-left

### ISSUE THREAD

**Issue by wls** [FortAwesome/Font-Awesome#16685]
**What can it be used for?**
Describing 1:N relationships in Entity Relationship Diagrams (such as making buttons for a tool to constructing them). Ideally available in different orientations (though that could be done with transformations). This might best fall in a family of ERD relationships including 1:1, N:1, N:N, etc. 

**Example image**
<img width="337" alt="ERD-icons" src="https://user-images.githubusercontent.com/537381/82505028-cb1d7c80-9aca-11ea-927a-af1e2820b673.png">

_Specifically I'm just looking for crow feet._

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
