### ISSUE TITLE
Icon request: fa-guitars-slash

### ISSUE THREAD

**Issue by MohdishUK** [FortAwesome/Font-Awesome#16701]
**What can it be used for?**
I'm using the fa-guitars to signify that a user is part of a guitar band.
Having a 'slash' icon would enable people to not be part of guitar band.

**Icon request checklist**
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of Font Awesome Pro SVG Framework.

Demo: https://jsfiddle.net/tagliala/zrcxo5d8/15/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
