### ISSUE TITLE
workout icons

### ISSUE THREAD

**Issue by BeyoncesHomeboy** [FortAwesome/Font-Awesome#16711]
They are rarely any icons out there for exercises and it would be great if we started adding those to Font-Awesome. Bench press, squat, elliptical, and so on. 

Thank you

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
