### ISSUE TITLE
@fortawesome/fontawesome-free does not contain metadata/*.json

### ISSUE THREAD

**Issue by leon** [FortAwesome/Font-Awesome#16733]
**Describe the bug**
The npm version of font awesome seems to strip the json metadata files.

I need the *.json files to build an icon picker.

**To Reproduce**
https://unpkg.com/browse/@fortawesome/fontawesome-free@5.13.0/metadata/

There are no .json files

**Expected behavior**
I would like the npm dist to include the json metadata files.

Is there a reason that they are stripped, or is it a ignore file that needs updating?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

There could be a couple ofreasons:

1. `icons.json` is way bigger than `icons.yml` (3MB vs 300KB for Free, 14 MB vs 600KB for Pro) and it has been excluded from the package to reduce the download size;
2.`icons.json` has been implemented after `icons.yml`, and it is missing from the package because we forgot to add it.

Let's ask @robmadole

**Comment by robmadole** [comment]
It's the size. The icons.json basically includes duplicates of every single icon. We wanted to keep the package small.

**Comment by tagliala** [comment]
Ok, closing here
