### ISSUE TITLE
Icon request: zoom webex zoho-meeting gotomeeting google-meet microsoft-teams

### ISSUE THREAD

**Issue by pooran** [FortAwesome/Font-Awesome#16740]
**What can it be used for?**
For icons used in any mobile app when meeting with any of the listed brands

**Example image (optional)**
![image](https://user-images.githubusercontent.com/116028/83167763-27694780-a12e-11ea-9621-6a37f31dabd6.png)
![image](https://user-images.githubusercontent.com/116028/83167787-305a1900-a12e-11ea-8ee7-a0d64844be55.png)
![image](https://user-images.githubusercontent.com/116028/83167833-3e0f9e80-a12e-11ea-8f92-11e87303e8ee.png)
![image](https://user-images.githubusercontent.com/116028/83167865-48319d00-a12e-11ea-8c9a-8587fec37a16.png)
![image](https://user-images.githubusercontent.com/116028/83167894-4ff14180-a12e-11ea-9646-e299df66ba21.png)
![image](https://user-images.githubusercontent.com/116028/83167920-5a134000-a12e-11ea-8966-9a40e6c70281.png)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
