### ISSUE TITLE
Icon request: led-strip

### ISSUE THREAD

**Issue by ACJUK** [FortAwesome/Font-Awesome#16755]
**What can it be used for?**
Describe how this could be used / the use case for this icon.
To represnt LED strips, for example under cabinet LED strips in a kitchen

**Example image (optional)**
![LED icon](https://user-images.githubusercontent.com/40578133/83390456-c9688880-a3e9-11ea-979f-c6f5ce01cbdc.png)

 (I'm not a designer but this is kind of what I mean)

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Do you have a better example that plays well with our 16x16 grid and renders properly at default 16px icon size?

**Comment by ACJUK** [comment]
Hi

Thanks for coming back to me. I don't. But I work with a graphic guy who
will know what to do so I'll ask him on Monday.

Cheers
Andy

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
