### ISSUE TITLE
Icon request: icon-nintendoswitch , icon-gog  , icon-stadia icon-epicgames 

### ISSUE THREAD

**Issue by darrius1923** [FortAwesome/Font-Awesome#16760]
The icons could be used on websites related to video games, either to show what platform they are available on or that the icon works as a link to reach the required website, and not put a boring text with a link

Single icons.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

> icon-nintendoswitch

Sorry, cannot implement any Nintendo icon. Ref: https://github.com/FortAwesome/Font-Awesome/blob/master/CHANGELOG.md#590---2019-06-04
