### ISSUE TITLE
Font awesome 5 future updates

### ISSUE THREAD

**Issue by thimfy** [FortAwesome/Font-Awesome#16775]
As i can see you are going to release Version 6 that is paid version of font awesome.
So you will not provide any update on version 5 ?
Is this safe to use? will you provide update or not?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> So you will not provide any update on version 5 ?

FA 6 will be also available for Free,  just like Font Awesome 5.

> Is this safe to use? will you provide update or not?

FA5 will probably not receive new icons, but it will be maintained for bug fixes. In order to get new icons, you should upgrade to FA6 Free

Ref: https://fontawesome.com/6#how-will-version-6-be-available

Hope it helps

@robmadole please correct me if I'm wrong

**Comment by robmadole** [comment]
@tagliala all correct :+1:

**Comment by tagliala** [comment]
Ok, thanks, closing here

@thimfy feel free to comment if you need further clarification
