### ISSUE TITLE
Icon request: auction, bid, RFP (Request for Proposal), offer

### ISSUE THREAD

**Issue by CaporalF** [FortAwesome/Font-Awesome#16779]
**What can it be used for?**
Building a marketplace App/Website that rely on auctions and request for proposals

**Description**
This would be a series of icons to support the market place concept.
-  Auction currently using the gavel (f0e3) icon but would be great to have one with the base.
-  bid currently using the paint brush (f55d) as an approximation to a voting paddle. Would be better if it had a big number on it and did not have the horizontal line separating the brush handle from the bristle. It would be even better if it were circular [like in this picture](https://images.app.goo.gl/ZLZeXwxSPjJwq1SC8).
- RFP or Request for Proposal currently using file-signature (f573), but would like it to be more explicit with for example the letter RFP showing on the paper
- Offer or response to RFP, currently using the hand-holding (f4bd) as a base. This one is a bit more abstract and I would be open to suggestions.

Thank you,

All these icon would have partner icons which would modify the base icon with a modifier in the upper right corner:
- New with a +
- Delete/Cancel base icon with an X
- Hide (Auction, RFP) with a mute or volume slash icon
- Accept (Bid. Offer) base icon with a check mark icon
- Reject (Bid, Offer) base icon crossed over
- Watch/Follow/Like currently coupling the icon with the RSS icon
- Search (Auction, RFP) currently coupling the icon with the search glass

**Icon request checklist**
- [  ] This is a single icon or matched pair (Ex: `lock` / `unlock`).**No but all related**
- [ x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x ] I have included at least one example image if it could be helpful (optional)
- [ x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and apologies for the late reply.

> [ ] This is a single icon or matched pair (Ex: lock / unlock).No but all related

I understand that the above icons are all related in your use case, but I still think this request should be split into individual request because:
- they makes sense individually
- one contains letters
- one is too abstract and requires brainstorming

> Auction currently using the gavel (f0e3) icon but would be great to have one with the base.

we can have this icon (gavel-with-base) as an alternative way to represent an auction can exists independently from other icons ref: #bid

> bid currently using the paint brush (f55d) as an approximation to a voting paddle.

A vote paddle makes sense 

> RFP or Request for Proposal currently using file-signature (f573), but would like it to be more explicit with for example the letter RFP showing on the paper

We try our best to avoid using letters, to provide icons that are language independent.

SVG Framework has a feature to stack text on icons: https://fontawesome.com/how-to-use/on-the-web/styling/layering

> Offer or response to RFP, currently using the hand-holding (f4bd) as a base. This one is a bit more abstract and I would be open to suggestions.

Requires brainstorming and/or feedback from the community, it is better to have this separately

Closing here
