### ISSUE TITLE
Icon request: interrobang

### ISSUE THREAD

**Issue by wallyfoo** [FortAwesome/Font-Awesome#16784]
For expressing clear puzzlement and surprise, there can be no substitute for the interrobang.

What‽ Who‽ Where‽

‽

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/interrobang?f=classic&s=solid)
