### ISSUE TITLE
cloud-upload and cloud-upload-alt

### ISSUE THREAD

**Issue by cgodfrey-mf** [FortAwesome/Font-Awesome#16798]
I have used it before but now it says it is not here!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)
