### ISSUE TITLE
Icon request: raw materials

### ISSUE THREAD

**Issue by aminamiridarban** [FortAwesome/Font-Awesome#16796]
**What can it be used for?**
Industry and ERP Applications

Description: Raw Materials, Ingredients,Minerals

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Any example?

**Comment by aminamiridarban** [comment]
Hi back

There is a lot of examples if you google it
The main issue is the idea behind designing a unique one for font awesome.
 If no idea, Just try to google a phrase like this pattern :
**<[Mineral | Ingredient | Raw Material | Material]> <[Pictogram | Vector | Symbol | Sign]>**
Use your creativity, be a little awesome 😉

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Comment by sahil-hadvani** [comment]
"fa-duotone fa-light fa-cart-flatbed-boxes"
"fa-regular fa-person-dolly"
