### ISSUE TITLE
.fa-stack-xx not square size

### ISSUE THREAD

**Issue by Nantor** [FortAwesome/Font-Awesome#16812]
When Is use the stacked version of Font-Awesome, the Icons are no longer stacked since 5.5. This lead to issues, where some CSS-Frameworks expect an Icon squarish.

Here is a jsFiddle-Link with Bulma.io Framework as an example: https://jsfiddle.net/8e5g71az/1/

I see no reason why the width is 25% greater than the height. So this could be changed back?

- Version: 5.5+
- Browser and version: any
- SVG with JS

**Bug report checklist**
- I have filled out as much of the above information as I can
- I have included a test case because my odds go _way_ up that the team can fix this when I do
- I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Sorry for the breaking change, but this has been done to fix an issue when stacking wide icons like book-open with the CSS framework.

Demo: https://jsfiddle.net/zye03bav/

Also, documentation about stacks warns that some use cases may need style changes:

Quoting from: https://fontawesome.com/how-to-use/on-the-web/styling/stacking-icons
> Some Custom CSS Required
> You'll need to write your own custom rules if you change the default font-size of stacked icons as well as depending on your layout needs (by default stacked icons are set to display: inline-block; and vertical-align:middle;).

Since you are using the SVG Framework, it is worth to note that you can go for layering, masking, and power transforms instead of `stacking`: https://fontawesome.com/how-to-use/on-the-web/styling/layering

Demo: https://jsfiddle.net/5drL1ng0/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

Hope it helps

Closing here

**Comment by Nantor** [comment]
OK, thanks for the nice answer.

**Comment by tagliala** [comment]
Welcome 👍
