### ISSUE TITLE
Icon request: for webshops

### ISSUE THREAD

**Issue by Kolacc** [FortAwesome/Font-Awesome#16838]
**What can it be used for?**
We like to use Font Awesome icons in our webshops but many icons or similar icons we can't find currently in FA.

**Icon request checklist**
- [ ] product (an icon which properly symbolize that's a product)
- [ ] category (an icon which properly symbolize that's a category or product list)
- [ ] comparison (currently we're using the balance-scale, but maybe you can create more similars)
- [ ] add to comparison
- [ ] remove from comparison
- [ ] free shipping (it might be a version of current truck icon)
- [ ] service, plus service for a product (no idea what kind of icon would be exact for this)
- [ ] payment (an icon which symbolize payment from cash to credit cards)
- [ ] shipping type
- [ ] payment type
- [ ] add to cart
- [ ] remove from cart
- [ ] delete the content of cart
- [ ] change the content of cart, refresh the cart
- [ ] coupon
- [ ] time countdown (for sale prices)
- [ ] thumbnails (for images)
- [ ] no-image
- [ ] language (for change the language)
- [ ] currency (for change the currency)
- [ ] new (symbolize that product is new, prefer a language independent)
- [ ] explicit (a 18+ symbol for explicit products)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
