### ISSUE TITLE
Icon request: smartcard-chip

### ISSUE THREAD

**Issue by ChrisLail** [FortAwesome/Font-Awesome#16837]
**What can it be used for?**
For when reference a credit card chip or security related to door access cards

**Example image (optional)**
![image](https://user-images.githubusercontent.com/5090610/85807532-32f56180-b720-11ea-80c9-cfeae24d8f3b.png)

**Icon request checklist**
- [X] This is a single icon 
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of or shares too much similarity with [this request.](https://github.com/FortAwesome/Font-Awesome/issues/1696)
