### ISSUE TITLE
Size of icon

### ISSUE THREAD

**Issue by ajtruckle** [FortAwesome/Font-Awesome#16845]
Please see:

![Size](https://user-images.githubusercontent.com/7985331/85941153-ff315c00-b918-11ea-94d0-9e6593db1863.png)

.. at the top of my [website](https://www.publictalksoftware.co.uk).

Part of the HTML:

`<i class="fa fa-language"></i>`

I tried to style:

```
.fa-language {
     font-size: 2em;
}
```

I don't know how to make my combo / icon of a consistent height.

**Comment by tagliala** [comment]
Hi!

This is a generic question and it is related to CSS rather than Font Awesome.

If you need to visually align and center the select box and the icon, please search on google, check stack overflow, or take a look at how bootstrap implements its [input groups](https://getbootstrap.com/docs/4.0/components/input-group/)

> ```
> .fa-language {
>    font-size: 2em;
> } 
> ```

Please avoid this, it will change `fa-language` size everywhere in the website. We have a css utility class `fa-2x` to double the size of an icon.

Hope it helps

Closing here

Ref:
- https://fontawesome.com/how-to-use/on-the-web/styling/sizing-icons
