### ISSUE TITLE
share alt ikonu kayıp (lang tr)

### ISSUE THREAD

**Issue by darkthefor1312414** [FortAwesome/Font-Awesome#16850]
....

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

From google translate:

> share subscript missing

Sorry, I don't understand

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)
