### ISSUE TITLE
Kits or CDN for website that is on Github?

### ISSUE THREAD

**Issue by sebfischer83** [FortAwesome/Font-Awesome#16854]
Hi,

Is it allowed to use any of this for my page that is hosted on Azure but the source code is available on Github? With CDN I can restrict the allowed domains but what is about Kits? Can anyone copy from any page the Javascript link and is it anywhere?

**Comment by tagliala** [comment]
@robmadole since page views for kits are limited, I don't know the answer for this question: I didn't get how they work 😅

Do you mind to clarify?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
