### ISSUE TITLE
cdn not working properly.

### ISSUE THREAD

**Issue by thelamewizard** [FortAwesome/Font-Awesome#16868]
using the cdn script tag sent to my email:
i class="fas fa-hotel"
gives a blank square.
i class="fa fa-hotel"
gives a different icon ("fas fa-bed "to be exact)
and if i enter any other icons after that it just wont show anything after the first icon.

using link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" wors fine though.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request?

> using the cdn script tag sent to my email:

Ok, you mean the `kit` link ? 

Could you please provide a link to a reproducible test case?

**Comment by thelamewizard** [comment]
thankl you for the reply. Yes, i mean the kit link. 

Im a novice in html so it is entirely possible im doing something wrong, but i will post the test case for you soon as i get a chance to condense it so that theres not too much unnecessary code to read through.

**Comment by thelamewizard** [comment]
i've uploaded html files to my github for you. link: https://github.com/thelamewizard/fontawsome-issue-example

**Comment by tagliala** [comment]
Thanks, got it.

That CDN (`https://use.fontawesome.com/xxx.js`) is an old beta service based on FA4, please do not use it in new projects.

Please consider switching to FA5 syntax (`fas fa-hotel`), upgrade FontAwesome version (latest is 5.13.1) and if you want to use a kit rather than the CDN link, please create a proper kit link (`https://kit.fontawesome.com...`)

Ref:
- https://cdn.fontawesome.com/
- https://fontawesome.com/start

Hope it helps

Closing here
