### ISSUE TITLE
hello an icon doesn't work for me

### ISSUE THREAD

**Issue by Bao500ct** [FortAwesome/Font-Awesome#16874]
hi, I wanted to use the unity icon (fa-unity) on my wordpressd site, but I don't understand why it doesn't work, all the others work. can you help me?

icon link: https://fontawesome.com/icons/unity?style=brands

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)

[fa-unity](https://fontawesome.com/icons/unity?style=brands) has been introduced in Font Awesome 5.12.0, so please double check that you are using Font Awesome 5.12.0 or newer versions

Please note that third-party plugins/themes/libraries may load an older version of Font Awesome that may take precedence on yours: check that it is not your case. Our [Troubleshooting Guide](https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting) and [Troubleshooting Wiki](https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting) could help.

Closing here
