### ISSUE TITLE
Icon request: Charts

### ISSUE THREAD

**Issue by jeesim2** [FortAwesome/Font-Awesome#16889]
**What can it be used for?**
Describe how this could be used / the use case for this icon.

* Meaning an 'Dashboard' that includes multiple charts

current dashboard icon is something like just car's dashboard.
but on the web, many times, dashboard means a page that includes multiple charts.

I can't find a proper icons even in pro icon list.

**Example image (optional)**
Insert the example image here if necessary.

![image](https://user-images.githubusercontent.com/1100831/86985471-4dbde080-c1cc-11ea-897c-8e16a12c060a.png)
![image](https://user-images.githubusercontent.com/1100831/86985488-557d8500-c1cc-11ea-8b79-430be8ac16c7.png)

https://www.google.com/search?q=dashboard+icon&tbm=isch&source=iu&ictx=1&fir=beRsFmu7I0JICM%252CFfFKrDj3IdZHfM%252C_&vet=1&usg=AI4_-kQY2ZZpOrkTLRq0mpUG_4XmiI9tIg&sa=X&ved=2ahUKEwiwpt-q_b7qAhWbOnAKHQZJAQEQ9QEwAHoECAoQGw&biw=1626&bih=916#imgrc=4ErnKRgBsP-unM

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`) : single
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
