### ISSUE TITLE
Something is not working properly from the documentation

### ISSUE THREAD

**Issue by skchinna7** [FortAwesome/Font-Awesome#16893]
fas and far and fal are not working on a website so please do something

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)
