### ISSUE TITLE
Icon Request: fa-fan

### ISSUE THREAD

**Issue by tsarak** [FortAwesome/Font-Awesome#16896]
I've setup a flow in node-red to control fans in a server cabinet. I'd like to use either an icon for the side menu or an icon for individual switches for the fans, ... or both 8-) (in case I cannot use the same icon for both cases)
Thanks in advance and ...keep the good work!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> (in case I cannot use the same icon for both cases)

Since we already have a [fan](https://fontawesome.com/icons/fan?style=solid) icon, could you please provide a single color. small size suitable example of the icon you have in mind?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
