### ISSUE TITLE
Icon request: contactless-safety-tool

### ISSUE THREAD

**Issue by mkredmond** [FortAwesome/Font-Awesome#16918]
**What can it be used for?**
Contactless safety tools are becoming very common at the moment, to assist people in opening doors, pressing elevator buttons, and performing a number of other daily tasks where a person wants to avoid touching an object with their fingers. This icon could be used to illustrate what the tool looks like on many websites that provide instruction and guidelines as businesses and schools are opening back up.

**Example image (optional)**
![Contactless Safety Tool](https://user-images.githubusercontent.com/16856992/87694931-d1437880-c75c-11ea-91d2-9bcd002d6865.png)

**Icon request checklist**
- [x] This is a single icon
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
