### ISSUE TITLE
New type image

### ISSUE THREAD

**Issue by das2348** [FortAwesome/Font-Awesome#16914]
I would like to have some pictures of buildings like tables, chairs, houses and so on so that you can see what the ICONS are and develop them so that I have a restaurant in the background and a table in the dining room and all that stuff

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
