### ISSUE TITLE
sort-by-order-alt is 9-1 not 9-0?

### ISSUE THREAD

**Issue by WanderingZombie** [FortAwesome/Font-Awesome#1691]
http://fortawesome.github.io/Font-Awesome/icon/sort-by-order-alt/

If sorting alphabetically has an icon with Z-A and A-Z, why do you use 1-9 and 9-1 instead of 0-9 and 9-0 as is more common?

**Comment by sensibleworld** [comment]
Cleaning up some old issues, and came across this one. Because the `sort` icons are typically meant to indicate a list of items, it seems to make sense to only include digits that can be counted. In a numeric list, the first item is usually a "1" and not a "0".

I'd be open to considering an `alt` version of the icon, if there was enough user support for it.
