### ISSUE TITLE
Icon request: ventilation for covid-19

### ISSUE THREAD

**Issue by ittun55** [FortAwesome/Font-Awesome#16920]
**What can it be used for?**
Attention for ventilation against covid-19

**Example image (optional)**
window and I/O allows

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
