### ISSUE TITLE
Icon request: Products

### ISSUE THREAD

**Issue by robcarruthers** [FortAwesome/Font-Awesome#16921]
**What can it be used for?**
Product listings or product pages.

**Example image (optional)**
![Screen Shot 2020-07-17 at 1 22 55 PM](https://user-images.githubusercontent.com/40727678/87738058-a591c280-c830-11ea-88eb-f29e76549793.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
