### ISSUE TITLE
Icon request: user-network

### ISSUE THREAD

**Issue by ux-jessica** [FortAwesome/Font-Awesome#16936]
**What can it be used for?**
Converting chart-network into user-network would be used to identity networking events and human connections. 

**Example image (optional)**
https://cdn5.vectorstock.com/i/1000x1000/43/09/social-networking-line-icon-concept-social-vector-22874309.jpg

**Icon request checklist**
Independent Icon - This is a single icon or matched pair (Ex: `lock` / `unlock`)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
