### ISSUE TITLE
Icon request: ñ symbol

### ISSUE THREAD

**Issue by unsnapp8** [FortAwesome/Font-Awesome#16958]
**What can it be used for?**
ñ as a character itself has become a cultural and linguistic icon of Spanish/Castilian. Its often displayed on its own just to symbolize Spanish. More info here: https://en.wikipedia.org/wiki/%C3%91#Cultural_significance

The character, while it does exist as a unicode character (not unlike Font Awesomes' + or ^ symbols) it would be nice to have it in Font Awesome, in a font consistent with other Font Awesome characters.

**Example image (optional)**
ñ

**Comment by aethior** [comment]
This icon is under discussion in #18831.
This request is older, but I think is better to solve the started discussion in the other issue.
The error was mine for not checking if the other request was a duplicate before to post.
Sorry.

cc/ @tagliala

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
