### ISSUE TITLE
youtube

### ISSUE THREAD

**Issue by luckydevil9717** [FortAwesome/Font-Awesome#16957]
**What can it be used for?**
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

YouTube icon is available since a lot of time

https://fontawesome.com/icons/youtube?style=brands
https://fontawesome.com/icons/youtube-square?style=brands

Make sure that you have a proper version of Font Awesome installed (only FA >= 5.0.0 is supported at the moment)

If you have troubles on how to use Font Awesome take a look at our documentation website:
https://fontawesome.com/start
https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here
