### ISSUE TITLE
Icon request: keycap-alt

### ISSUE THREAD

**Issue by cubano100pct** [FortAwesome/Font-Awesome#16968]
**What can it be used for?**
Can be used for showing on the screen keyboard shortcuts to press on screen help pages.

**Example image (optional)**
Keycap image with ALT inside
http://legionfonts.com/img-fonts/keycaps-regular/keycaps-regular-font-preview.jpg

I would like to see keycap icons for all the 104 keys plus MacOS command key

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
