### ISSUE TITLE
Icon request: fa-pln

### ISSUE THREAD

**Issue by facero972** [FortAwesome/Font-Awesome#16982]
**What can it be used for?**
It will be used to show the currency sign for money value in Poland

**Icon request checklist**
- [ ] This is a single icon 
- [ ] I have searched for existing issues and to the best of my knowledge this is not a duplicate
- [ ] I use others currency sign for money included in Font Awesome

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
