### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by LiaoZhJ** [FortAwesome/Font-Awesome#16991]
如图
![图片](https://user-images.githubusercontent.com/61783208/89382166-ef354500-d72c-11ea-89de-5694bef3f73b.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

From google translate:

> 如图

"As shown"

This comes from the old FA 4.7 documentation, which is in EOL , and it problably comes from a third-party documentation, because we do not I cannot replicate at https://fontawesome.com/v4.7.0/cheatsheet/

Hope it helps

Closing here

**Comment by tagliala** [comment]
Please upgrade to Font Awesome 5: https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4
