### ISSUE TITLE
Icon Request: Whiteboard

### ISSUE THREAD

**Issue by unsnapp8** [FortAwesome/Font-Awesome#17007]
**What can it be used for?**
This would be very useful for education related websites, and could probably look similar to the chalkboard icon

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome! [Take a look at it here.](https://fontawesome.com/icons/chalkboard?f=classic&s=solid)
