### ISSUE TITLE
Icon request: room-board

### ISSUE THREAD

**Issue by glisczni** [FortAwesome/Font-Awesome#17034]
**What can it be used for?**
Room & board or Housing & Dining for colleges and universities

**Example image (optional)**
House with knife and fork or half plate & fork and half bed

**Icon request checklist**
- [ x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x ] I have included at least one example image if it could be helpful (optional)
- [ x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> House with knife and fork or half plate & fork and half bed

Any image example?

**Comment by glisczni** [comment]
One of these perhaps. Housing & Dining

[ZQImTJWI+u4AAAAASUVORK5CYII=]


[wOhB2nSl3zL1QAAAABJRU5ErkJggg==]


Nicole Glisczinski
Digital Experience Manager
Fox Valley Technical College
glisczni@fvtc.edu<mailto:glisczni@fvtc.edu>
920-225-5935

Fox Valley Tech is moving forward with a full set of offerings using remote and in-person instruction to ensure your safety and success. Learn more: http://www.fvtc.edu/Forward.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
