### ISSUE TITLE
Icon Request: icon-cloud-print

### ISSUE THREAD

**Issue by kristianserrano** [FortAwesome/Font-Awesome#1704]
Google Cloud Print is a fantastic way of print pages and documents to remote printers. Additionally, it also enables users to send those same assets to Chrome browsers on their other devices as well as saving PDF copies to Google Drive. The biggest important factor is that it works on mobile UIs, too, allowing a user to print from an Android phone or iPhone with a simple tap.

Google already has their own image (named icon-cloudprint coincidentally) that is a perfect model for the icon (see attached).
![image](https://f.cloud.github.com/assets/1796189/898675/ab8275a6-fb1c-11e2-9421-08733bee0690.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
