### ISSUE TITLE
Icon request: folder-public and folder-private

### ISSUE THREAD

**Issue by Khuthaily** [FortAwesome/Font-Awesome#17093]
**What can it be used for?**
1. public folder: this would represent content that is open to the public.

1. private folder: this would represent content that is not open to the public.

**Example image (optional)**
Similar to existing icons:

1. "folder" icon with "eye" icon in the center for the new public folder

1. "folder" icon with "eye-slash" icon in the center for the new private folder

I was able to create these icons by "stacking" existing icons, but the size of the newly created icon was big (due to the required use of "fa-2x"). I used CSS to override size properties, but I thought it be good to have native icons for "folder-public" and "folder-private."

**Icon request checklist**
- [matched: public/private ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [X ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
