### ISSUE TITLE
Icon request: search_check

### ISSUE THREAD

**Issue by pigsinspace** [FortAwesome/Font-Awesome#17117]
**What can it be used for?**
magnifying glass with Checkmark inside. -- used to indicate a search has been completed or that an inspection is completed

**Example image (optional)**
Insert the example image here if necessary.
![image](https://user-images.githubusercontent.com/6531214/92183456-5533eb80-ee03-11ea-85a3-41c562cd4f9c.png)

**Icon request checklist**
- [either ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X ] I have included at least one example image if it could be helpful (optional)
- [ X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
