### ISSUE TITLE
Unable to click and open the icon.

### ISSUE THREAD

**Issue by milindsingh98** [FortAwesome/Font-Awesome#17145]
The icons need to right-click and opened in a new tab rather than directly load on the same page.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)
