### ISSUE TITLE
Icon request: Nail Salon / Manicure Hand

### ISSUE THREAD

**Issue by kphandev** [FortAwesome/Font-Awesome#17157]
**What can it be used for?**
It could be used for nail salon businesses or cosmetology businesses

**Example image (optional)**
https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/strongnails-1588107006.png?crop=0.5xw:1xh;center,top&resize=768:*

**Icon request checklist**
- [ X ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ X ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ X ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ X ] I have included at least one example image if it could be helpful (optional)
- [ X ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a single color, 16px icon size suitable example?

**Comment by kphanplan** [comment]
Hi Geremia,
I was thinking something like this:
[image: font-awesome-sugg.jpg]
Thanks for your time and quick response,

Kevin Phan

**Comment by tagliala** [comment]
Hi @kphanplan sorry but email attachments do not work

Please upload the example at https://github.com/FortAwesome/Font-Awesome/issues/17157

**Comment by kphanplan** [comment]
![hand](https://user-images.githubusercontent.com/57550661/93496307-0a26d780-f8dd-11ea-8d54-77a3f4109d93.jpg)

Sorry about that. Hopefully this works...

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
