### ISSUE TITLE
NPM Install problem 2

### ISSUE THREAD

**Issue by ingrocha** [FortAwesome/Font-Awesome#17178]
I'm trying install fortawesome pro on angular using `ng add @fortawesome/angular-fontawesome` and it return me this:

`npm ERR! Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/"` 

 i have my .npmrc file like this:

```
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
```

And i try with the NPM command but it's the same response

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Is this the same problem as #17147 ?

Anyway, if it is something related to license, please send an email to hello@fontawesome.com

**Comment by ingrocha** [comment]
So let me understand my "for life license" its turns out it wasn't for life. am i right?

And because of that i cant install in my projects fontawesome pro? and i can use the css files?

**Comment by tagliala** [comment]
> So let me understand my "for life license" its turns out it wasn't for life. am i right?

Hi, the license for FA 5 is for life, but the use of the private npm repository or the pro kit cdn isn't, sorry

This is a comment by Rob to clarify: https://github.com/FortAwesome/Font-Awesome/issues/17147#issuecomment-692775989

> And because of that i cant install in my projects fontawesome pro?

You can! A new page has been added to the Docs to provide instructions on how to download npm packages and use them locally (or in a self-hosted private npm repo): https://fontawesome.com/how-to-use/on-the-web/setup/using-the-npm-download

For deploy workflows, after you have downloaded npm packages, you should be able to edit `package.json` as explained here: https://github.com/FortAwesome/Font-Awesome/issues/17147#issuecomment-693491890

> And i can use the css files?

Sure, you can do anything that does not involve npm private repository or hosted pro kits

@robmadole please review this answer, I may have missing something

**Comment by plamenh** [comment]
> > So let me understand my "for life license" its turns out it wasn't for life. am i right?
> 
> Hi, the license for FA 5 is for life, but the use of the private npm repository or the pro kit cdn isn't, sorry
> 
> This is a comment by Rob to clarify: [#17147 (comment)](https://github.com/FortAwesome/Font-Awesome/issues/17147#issuecomment-692775989)
> 
> > And because of that i cant install in my projects fontawesome pro?
> 
> You can! A new page has been added to the Docs to provide instructions on how to download npm packages and use them locally (or in a self-hosted private npm repo): https://fontawesome.com/how-to-use/on-the-web/setup/using-the-npm-download
> 
> For deploy workflows, after you have downloaded npm packages, you should be able to edit `package.json` as explained here: [#17147 (comment)](https://github.com/FortAwesome/Font-Awesome/issues/17147#issuecomment-693491890)
> 
> > And i can use the css files?
> 
> Sure, you can do anything that does not involve npm private repository or hosted pro kits
> 
> @robmadole please review this answer, I may have missed something

You can't! svg-core and common-types are behind the paywall!

**Comment by robmadole** [comment]
@plamenh the `@fortawesome/fontawesome-svg-core` and `@fortawesome/fontawesome-common-types` are both public and free:

- https://www.npmjs.com/package/@fortawesome/fontawesome-svg-core
- https://www.npmjs.com/package/@fortawesome/fontawesome-common-types

When we've seen issues it's normally because of a `package-lock.json` or `yarn.lock`. Or you still have an errant `.npmrc` file that it pointing to `npm.fontawesome.com`.

**Comment by plamenh** [comment]
@robmadole Thanks for the clarification, but I tried everything (deleting .npmrc, node_module, package-lock, etc.) and nothing worked. Plus, using the free version of the common types is unlikely to work (tried that already with packaging the files manually from the free version and it is missing the pro types/icon names).

**Comment by tafelnl** [comment]
I have a similar issue. Until recently I had no problems installing the pro package from a local file.

My package.json contents looks like the following:

```
{
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.17",
    "@fortawesome/free-brands-svg-icons": "^5.14.0",
    "@fortawesome/pro-light-svg-icons": "file:fontawesome/fortawesome-pro-light-svg-icons-5.14.0.tgz",
    "@fortawesome/pro-regular-svg-icons": "file:fontawesome/fortawesome-pro-regular-svg-icons-5.14.0.tgz",
    "@fortawesome/pro-solid-svg-icons": "file:fontawesome/fortawesome-pro-solid-svg-icons-5.14.0.tgz"
  },
  "devDependencies": {
    "@fortawesome/fontawesome-pro": "file:fontawesome/fortawesome-fontawesome-pro-5.14.0.tgz"
  }
}
```

Ergo it installs the fontawesome pro from a local directory (I have a pro license). It should not make a connection to the fontawesome server to check for license. And even if it did, it should be okay, since I am not using the npm services (excluded in my license). 



```bash
$ npm i file:fontawesome/fortawesome-pro-light-svg-icons-5.14.0.tgz

npm ERR! code E401
npm ERR! Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/"
```

**Comment by tafelnl** [comment]
Ah, already found the issue. I did delete the `.npmrc` config. But I forgot about the global variable in npm.
So running

```bash
npm config delete "@fortawesome:registry"
```

solved my problem

**Comment by walkerworks** [comment]
Late to the party - but how does one "download npm packages and use them locally" as per  https://fontawesome.com/how-to-use/on-the-web/setup/using-the-npm-download - when their license has already expired?
I don't seem to have access to the NPM (tgz) packages anymore for download (not even the ones at the highest version I still have access to).

**Comment by tagliala** [comment]
@walkerworks please send an email at hello@fontawesome.com

https://fontawesome.com/download#pro-packages works for users with an active subscription

**Comment by walkerworks** [comment]
>https://fontawesome.com/download#pro-packages works for users with an active subscription 
I understand.  I did send an email to that email and haven't heard back yet.  As I understood from the chain above - since the pro-package npm download only works for active subscriptions, I needed to go and download the package tgz's myself and self-host them.  Is that not what plamenh was saying above (commented on Sep 24, 2020)?

**Comment by tagliala** [comment]
Will try to ping the team, you should be able to get by email the latest npm you were entitled to download

We also should provide an automatic feature to allow old subscribers to download the packages by themselves, but at the moment this has not been implemented yet

**Comment by tagliala** [comment]
I'm going to close and lock here because:

1. This post contains different, unrelated issues 
2. License issues should be addressed via hello@fontawesome.com
3. At the moment I'm writing, it is not possible for formers customer to download the latest npm package they are entitled to download, please send an email to hello@fontawesome.com
3. Pro subscribers have docs available at https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers#installing-pro
4. If someone is reading here and none of the above comments help, they should open a new [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md) and provide all the information we need to debug
