### ISSUE TITLE
Using FontAwesome Pro in Angular

### ISSUE THREAD

**Issue by aha-tech** [FortAwesome/Font-Awesome#17188]
We're trying to switch out the free font-awesome 5 icons with pro icons in our Angular 10 application. We're currently importing the free fonts by [Explicit Reference](https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/usage/explicit-reference.md) like so (in component.ts)

```
import { faLock } from "@fortawesome/free-solid-svg-icons";
```
However, when using the pro icons it seems that no TypeScript files are provided, no `.d.ts` or ES module file seems to be included in the `@fortawesome/fontawesome-pro` npm package.

I know that we can go with the css solution, but we'd like to keep the explicitness and the tree-shaking possibilities, since we're using only a few of the icons.

My question is; is importing the pro icons in TS possible? It seems weird that the free icons allow this but the pro icons do not.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)

> However, when using the pro icons it seems that no TypeScript files are provided, no `.d.ts` or ES module file seems to be included in the `@fortawesome/fontawesome-pro` npm package.

Any reproducible test case?

I'm not an angular developer, but if your use case requires to import from `@fortawesome/free-solid-svg-icons`, then you should convert this to `@fortawesome/pro-solid-svg-icons`, so the proper packages to include are:

- `@fortawesome/fontawesome-svg-core`
- `@fortawesome/pro-solid-svg-icons`
- `@fortawesome/angular-fontawesome@...`

Please note that `@fortawesome/fontawesome-pro` is an all-in-one repository which includes almost everything and is supposed to be used for CSS implementation

**Comment by aha-tech** [comment]
Hey, thank you for your response!
I was directed here by FontAwesome support.
Thank you for your replies, that was exactly what I needed. I'll close the issue

**Comment by tagliala** [comment]
Welcome!
