### ISSUE TITLE
fontawesome-svg-core

### ISSUE THREAD

**Issue by pixels-farm** [FortAwesome/Font-Awesome#17217]
Hi all. Please help.
In this new reality of yours, how can i install fontawesome-svg-core without authentication fail?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> In this new reality of yours, how can i install fontawesome-svg-core without authentication fail?

Probably this is because your subscription is expired and npm is trying to download this package from the private npm repository

Both `fontawesome-svg-core` and `fontawesome-common-types` are available in the npm/yarn public repositories, so you just have to remove offending font-awesome entries from `.npmrc` and entries pointing to the private npm repo in `yarn.lock` `package-lock.json`

Ref: #17147

**Comment by pixels-farm** [comment]
THanx. You saved me for the second time now. Have a good day!
