### ISSUE TITLE
Icon request: icon-pregnant/fetus/neonate

### ISSUE THREAD

**Issue by fschou** [FortAwesome/Font-Awesome#17221]
I am building webapp for academic research use in the neonatal-perinatal field. I am looking for icons for pregnant women, fetus/placenta, and neonate.

Hyperlinks for images of [pregnant women](https://uclahealth.org/westlake-village-obgyn/pregnancy-information), [fetus](https://www.uclahealth.org/obgyn/images/Maternal_Fetal_Medicine/Fetus_in_Utero.jpg), and [neonates](https://www.uclahealth.org/mattel/for-parents) are provided.

Thank you for your creativity and efforts.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/person-pregnant?f=classic&s=solid)
