### ISSUE TITLE
Icon Request: fa-smarthome

### ISSUE THREAD

**Issue by turner72** [FortAwesome/Font-Awesome#17264]
Since font-awesome icons are often used in node red, a collection of smart home icons would be very nice. I miss the following icons: dashboard, radiator, fan, heating, motion detection, air, humidity, CO2, power usage, window status and more.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Some of the afermentoined icons are already present in Font Awesome

Unfortunately I need to close this request because it does not meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

We accept single, individual requests (but please [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones)

If you are a Font Awesome Pro costumer, you can request icon sets in the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro?

If you are a Font Awesome Pro customer and you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
