### ISSUE TITLE
Icon request: fa-zen-yandex-square

### ISSUE THREAD

**Issue by DeNiFoTAR** [FortAwesome/Font-Awesome#17278]
**What can it be used for?**
To using it as a button for going at user profile (https://zen.yandex.ru/id/...)

**Example image (optional)**
Link for SVG:
http://cache-mskm904.cdn.yandex.net/download.cdn.yandex.net/from/yandex.ru/support/ru/zen/files/zen-icon.svg
Link for PNG:
http://cache-mskmar08.cdn.yandex.net/download.cdn.yandex.net/from/yandex.ru/support/ru/zen/files/zen-icon.png

**Icon request checklist**
<i class="fa fa-zen-yandex-square" aria-hidden="true"></i>
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
