### ISSUE TITLE
Doc: invalid HTML

### ISSUE THREAD

**Issue by David263** [FortAwesome/Font-Awesome#17289]
You appear to have invalid HTML in the "adding-custom-styles.html" example on page https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use .

Your example contains CSS code that is not included inside any HTML tag other than <head></head>. Even if some browser supports this, it is not standard.

Perhaps you left out a <style> tag? But note that inline <style> is currently considered a security violation in CSP.

I won't submit a pull request since many GitHub developers ignore these.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this

> Perhaps you left out a <style> tag?

Definitely, there is a style tag missing

>  But note that inline `<style>` is currently considered a security violation in CSP.

You can avoid inline `style` tags and use proper `css` files if they don't work with your use case because of strict CSP headers

> I won't submit a pull request

Thanks for the willing to help. This repository is generated by a build system, so these are not the actual source files of Font Awesome. In any case, documentation is not in this repo

Let's assign @talbs

Direct link: https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use#additional-styling-options

**Comment by talbs** [comment]
Thanks for raising this issue and bringing it to our attention. https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use#additional-styling-options should be updated now to include the proper HTML and context.

Shout if there's anything else we can do to make this documentation better.
