### ISSUE TITLE
Adding a hover filter causes icon to move

### ISSUE THREAD

**Issue by mrlife** [FortAwesome/Font-Awesome#17310]
**Describe the bug**
Adding the following to the `:hover` of the Tags icon causes it to move.

**To Reproduce**
1. Visit the page for an icon, e.g. Tags: https://fontawesome.com/icons/tags?style=solid
2. Right-click and inspect one of the Tags icons, e.g. the one that shows "size: 7x" when you hover over it
3. Select its parent `span`
4. Using the inspector, activate its hover state
5. Find the hover rule and add a `filter`, e.g.
```
.hover-indigo:focus, .hover-indigo:hover {
	color: #4c6ef5;
	filter: blur(); /* added this line */
}
```
6. Using the inspector, disable its hover state
7. Hover over the icon you right-clicked before and notice that the icon moves when you hover.

**Version and implementation**
Version: 5.15.1 Pro all.min.js
Browser and version: Safari 14.0

- [x] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

fontawesome's website contains a lot of extra styling and css, it is better to provide a reduced test case

Any chance to replicate the bug here?

https://jsfiddle.net/tagliala/gxd2s1h3/

**Comment by mrlife** [comment]
@tagliala Thanks, I tried that. I couldn’t pinpoint the issue. It’s happening in my project and also on the FontAwesome website.

**Comment by tagliala** [comment]
@mrlife please try to reduce the css of your project to the minimum amount of style that can reproduce the issue

I have some hints:
- Use the same icon that is giving you isseus
- Use the exact size in pixel that is giving you issues
- Check "odd" and "even" width icons (icons do not have the same width on Font Awesome by design choice. It is possible that this bug only affect certain widths)
- Check if the icon needs to be horizontally centered to reproduce the bug
- Check container with different width in pixels (odd or even)

**Comment by mrlife** [comment]
@tagliala I haven’t been able to pinpoint the issue and will go with another approach.

**Comment by crstian** [comment]
The thread is already closed, but I think it might be helpful for others.

The issue with CSS filters is likely due to changes in the way the browser renders elements with CSS filters. This can happen because some filters, like blur(), might affect how the element is displayed, causing a slight shift or resize.

Try to use the `will-change` property. It helps the browser optimize how it handles changes for the specified CSS property, preventing the jump effect.

```
.hover-indigo, .hover-indigo {
  will-change: blur;
}

.hover-indigo:focus, .hover-indigo:hover:hover {
  filter: blur();
}
```

Hope that helps.

**Comment by amphibian** [comment]
@crstian THANK YOU for this tip, it absolutely fixed this long-running issue for me (in my use case, using `opacity`).
