### ISSUE TITLE
Icon request: matrix

### ISSUE THREAD

**Issue by dlinning-jockey** [FortAwesome/Font-Awesome#17329]
**What can it be used for?**
Matrices are used in higher level mathematics. They represent a 2 dimensional "grid" of numbers, and are useful for things such as 3d transforms in graphics programs.

Use cases: Mathematics tutoring application, indication of a "grid" layout (that a table-style icon does not represent).

**Example image**
![Matrix icon example](https://user-images.githubusercontent.com/62891957/97495696-f176fc00-1935-11eb-8162-f0f6b3f78306.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
