### ISSUE TITLE
icon aplican en mi pagina

### ISSUE THREAD

**Issue by cutoche** [FortAwesome/Font-Awesome#17339]
<body>
    <header>
        <div class="menu-bar">
            <a href="#" class="bt-menu"><span class="icon-list2"><i class=" icon far fa-bars"></i></span>Menú</a>
        </div>
    </header>
</body>

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)
