### ISSUE TITLE
Icon request: fa-print-labels

### ISSUE THREAD

**Issue by alfvicente** [FortAwesome/Font-Awesome#17331]
**What can it be used for?**
 To help identify the proper printer when there are multiple types of printing media, in this case for adhesive labels (i.e. Zebra printers)

**Example image (optional)**
![Screenshot_2020-10-28 adhesive label printer icon - Búsqueda de Google](https://user-images.githubusercontent.com/26693592/97498108-59cfd880-194a-11eb-96aa-6a42343d62b0.png)

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
