### ISSUE TITLE
Icon Request: Smiley-Doctor

### ISSUE THREAD

**Issue by tikkertok** [FortAwesome/Font-Awesome#17344]
**What can it be used for?**
I want to use it for my tumblr blog, and I'm not quite sure how to change the icons other than with other GitHub ones. I have a new thing I'm doing called "Health Tips" since my blog revolves around Big Hero 6 and I want to put them in a convenient folder

Here's the image: https://em.wattpad.com/08fa67a2a6e4fa6077f76fec54216bd0e75406bd/687474703a2f2f692e696d6775722e636f6d2f7653686e726c562e6a7067?s=fit&h=360&w=360&q=80

Either the card or the face would do, I'd design it myself but I just don't know how to apply to my theme the way I want it, this seemed like the best option. I am aware of the MD and Doctor icons.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Does https://fontawesome.com/icons/user-md?style=solid fit your use case?

**Comment by tikkertok** [comment]
I would prefer the other one but I would use this as temporary

**Comment by tagliala** [comment]
@tikkertok it is ok to leave this open, but please:

- edit title (should be smiley-doctor?)
- clarify that you know the existence of `user-md` icon
- provide a different use case for the icon that is not covered by `user-md`

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
