### ISSUE TITLE
Icon Request: fa-matlab,fa-cpp,fa-tableau,fa-latex,fa-sql

### ISSUE THREAD

**Issue by gerrypol** [FortAwesome/Font-Awesome#17347]
Hello

Could you please add the following to fontawesome
[pics.zip](https://github.com/FortAwesome/Font-Awesome/files/5474125/pics.zip)

The requested logos are: Matlab, Latex, SQL, Tableau and C++

I have also tried to convert them to fonts using iconmoon
[icomoon-v1.0.zip](https://github.com/FortAwesome/Font-Awesome/files/5474127/icomoon-v1.0.zip)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

Ref: #4432, #2176, #10999, #9555, #14021
