### ISSUE TITLE
Icon request: Online Meeting

### ISSUE THREAD

**Issue by Sainik69** [FortAwesome/Font-Awesome#17357]
**What can it be used for?**
This can be used for Tuition Websites and websites which create apps for Meetings

**Example image (optional)**
I don't have an Image, but I can describe.
You can make Desktop screen with users on it.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> You can make Desktop screen with users on it.

Something like [user-chart](https://fontawesome.com/icons/user-chart?style=solid) without the arrow?
Or [user-class](https://fontawesome.com/icons/users-class?style=solid) may fit this use case

**Comment by Sainik69** [comment]
Both may fit this but can make it free?
Sincerely,
Sainik69

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
