### ISSUE TITLE
Wrong icon rendering on Safari

### ISSUE THREAD

**Issue by ArtFK** [FortAwesome/Font-Awesome#17353]
Hello, 

I'm having a strange render problem with a Font Awesome-Icon when the site is running on Safari. I'm attaching an example of the false render, and another with the right render. 

This is how it looks and should not: 
<img width="80" alt="wrong_render" src="https://user-images.githubusercontent.com/55387235/97867310-e7764400-1d0d-11eb-8709-17915c1c6bdf.png">

And this is how it looks right: 
<img width="78" alt="right_render" src="https://user-images.githubusercontent.com/55387235/97867320-ee04bb80-1d0d-11eb-886a-24058f94d35d.png">

Strange thing is that the wrong render occurs only the first time you visit the site. Once you have refreshed, the icon displays right. This only happens in Safari. Chrome and Firefox are displaying the icon right. The site is made with "The Gem" Theme in Wordpress. 

Thank you,

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)

>  The site is made with "The Gem" Theme in Wordpress.

Please replicate this issue without third-party plugins / themes / libraries, we do not provide support for third-parties
