### ISSUE TITLE
Icon request: clock-long-arrows-up (uptime)

### ISSUE THREAD

**Issue by Hyperx837** [FortAwesome/Font-Awesome#17376]
**What can it be used for?**
If we download install the fontawesome font locally, we can use uptime icon for fetch scripts

check list
    [ single ] This is a single icon or matched pair (Ex: lock / unlock)
    [ x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: Icon request: magical-unicorn)
    [ x ] I have searched for existing issues and to the best of my knowledge this is not a duplicate
    [  ] I have included at least one example image if it could be helpful (optional)
    [ x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. relaxed)

**Comment by Anu2006-dev** [comment]
https://i.imgur.com/UoEBO5I.png
scale down this image to view the sample

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think this could be renamed because it represents a clock with arrows, while `uptime` is an abstract concept.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/460/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by Anu2006-dev** [comment]
sorry+for+being+a+noob

**Comment by Anu2006-dev** [comment]
Oh, didn't knew that. Btw is there a way to build font awesome locally

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
