### ISSUE TITLE
Icon request: Drawer, drower guide and a sliding door 

### ISSUE THREAD

**Issue by marcoIornware** [FortAwesome/Font-Awesome#17370]
Drawer, drower guide and a sliding door icon- To expand the household/ hotel categorie. I would like to use those icons to specify some product categories for our customers. 

**Example image (optional)**
![Screenshot 2020-11-05 at 12 41 36](https://user-images.githubusercontent.com/73996598/98237127-b774ae00-1f64-11eb-956d-ff858a61f078.png)

<img width="60" alt="Screenshot 2020-11-05 at 12 47 03" src="https://user-images.githubusercontent.com/73996598/98237972-03742280-1f66-11eb-901b-4c4cb7e19dfa.png">

![Drawer-Guide](https://user-images.githubusercontent.com/73996598/98238245-61a10580-1f66-11eb-924b-10391c49d999.jpg)

**Icon request checklist**  Checked
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional) 
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
