### ISSUE TITLE
Having issues with fontawesome over https://vercel.com/

### ISSUE THREAD

**Issue by sujalgoel** [FortAwesome/Font-Awesome#17412]
### Issue : 
![issue](https://cdn.discordapp.com/attachments/244238416248569857/778341875152191508/unknown.png)
### Packages and dependencies that i am using and i don't think their is any premium version included : 
```
"dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.30",
    "@fortawesome/free-brands-svg-icons": "^5.14.0",
    "@fortawesome/vue-fontawesome": "^0.1.10",
    "@sentry/browser": "^5.21.1",
    "@sentry/integrations": "^5.21.1",
    "axios": "^0.21.0",
    "core-js": "^3.6.5",
    "vue": "^2.6.11",
    "vue-axios": "^3.1.3",
    "vue-router": "^3.2.0",
    "vuex": "^3.4.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.1.3",
    "eslint-plugin-vue": "^6.2.2",
    "prettier": "^1.19.1",
    "vue-template-compiler": "^2.6.11"
  },

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Are you a Font Awesome Pro costumer?

Anyway, I can see that your package manager is trying to download font awesome from the private npm repo (`npm.fontawesome.com`).

- If you don't want to download from that private repo because you need the free package, please remove your `lock` file and make sure that there is no global `.npmrc` configured to point `@fortawesome` to the private npm repo

Take a look at https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers

**Comment by sujalgoel** [comment]
I am really thank full of you! Thank you so much sir! Also, your reply to my query was pretty quick. once again thank you for helping me out!

**Comment by sujalgoel** [comment]
Thanks it worked for me! I am really glad that you helped me with the issue!

**Comment by tagliala** [comment]
welcome, glad you solved
