### ISSUE TITLE
Icon request: 3G, 4G, and 4G LTE (mobile communications technology)

### ISSUE THREAD

**Issue by lukejbaldwin** [FortAwesome/Font-Awesome#1741]

**Comment by SmattyCore** [comment]
Would love to see these at least 4G, 4G LTE or 5G, respectively.

**Comment by jake-cryptic** [comment]
Would really appreciate these icons for one of my projects :)
Maybe similar design to Android signal bars with a little '3g', 'H+', '4G', 'LTE', '5G' in the corner

**Comment by zatmar** [comment]
Up

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
