### ISSUE TITLE
Icon Request: fire / police groups

### ISSUE THREAD

**Issue by admjmaddox** [FortAwesome/Font-Awesome#1742]
To whom it may concern;

My name is Terry Handel and I am the I.T. Director for Miller County 911 in Tuscumbia Missouri (www.mce911.com).

We love the medical icons and are wondering if there is a possibility for some law enforcement and fire department based icons that would help our citizens on our site. I would also like to see some type of 'dispatch' icon's that include the maltese cross, sheriff's star (or police shield) and the Star of Life logos in simultaneous position...  We understand if the dispatch can not be done. Unfortunately I do not have any references at this time except for our county's 911 logo
[mfn email logo](https://f.cloud.github.com/assets/5194727/936269/3b0c6e9e-00a8-11e3-8433-b0a6b0095928.png)
.

Thank your for your attention in this matter, and look forward to correspondence regarding these icons.

**Comment by dpfem** [comment]
+1

**Comment by DarrenPaulWright** [comment]
+1

**Comment by LionelMeroni** [comment]
+1

**Comment by jodibean** [comment]
+1 for police badge

**Comment by mkline1554** [comment]
+1

**Comment by eappell** [comment]
Wow, over 5 years for this request and absolutely no response from FA.  That's a little disappointing.  I supported the kickstarter campaign for 5 Pro, and would really like to see some support for the law enforcement community...

**Comment by jeisel-northglenn** [comment]
Work for a city government - a police-style badge (or sheriff style for the counties) would be really helpful.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
