### ISSUE TITLE
Font-Awesome icons are not appearing

### ISSUE THREAD

**Issue by DaleMFrancis** [FortAwesome/Font-Awesome#17421]
I have really simple logic to request a font-awesome icon but the icon does not appear on the page. 

First in my index.html I've referenced the CDN including my Pro kit number. 

Second in my angular.json file I've included the following: 
            "styles": [
              "src/styles.css",
              "node_modules/bootstrap/dist/css/bootstrap.min.css",
              "node_modules/font-awesome/css/font-awesome.min.css"
            ],

Finally, here is the super-simple html: 
               
               <span class="fas angle-left"></span> -->

One of these is commented out because I wasn't sure if "fas angle-left" was correct of if "fas faAngleLeft was correct.  I've also tried other permutations.  

But no matter what I try, the icon doesn't appear on the page. 

Can someone advise?  Thank you.

**Comment by DaleMFrancis** [comment]
It looks like my message may have been corrupted.  The html choices were: 

                         <span class="fas faAngleLeft"></span> 
                                             OR
                         <span class="fas angle-left"></span>

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> First in my index.html I've referenced the CDN including my Pro kit number.

> Second in my angular.json file I've included the following:

Using Font Awesome by referencing the CDN asset in `<head>` and the link to css in `angular.json`, means that the you are going to load Font Awesome twice. You need just one of them.

Font Awesome comes with various flavors, so developers can find the best fit for their needs. Please do not mix up Kit / CDN /  CSS implementation via npm / SVG JS implementation via npm and our official angular component: they are all different approaches and you need to pick one.

For example, if you want to use the JavaScript SVG implementation, you should go for npm SVG js + angular component

```
  <span class="fas faAngleLeft"></span> 
  <span class="fas angle-left"></span> 
```

Neither is correct. `fas fa-angle-left` is the correct class (if you are using Font Awesome CSS/SVG+JS implementation).

Check our Docs:
- https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use
- https://fontawesome.com/icons/angle-left?style=solid
- https://github.com/FortAwesome/angular-fontawesome

PS: as a Pro customer, you can send an email to hello@fontawesome.com and get dedicated support

I'm going to close here because this issue tracker is for bugs and requests.

If you think there is a bug in Font Awesome, feel free to fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md) and provide a reproducible test case

Hope it helps
