### ISSUE TITLE
android icon was not visiable in html

### ISSUE THREAD

**Issue by Goheljay** [FortAwesome/Font-Awesome#17447]
when i write the code in html and after adding the android icon. then 
the icon was not visible

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)
