### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by nayan98** [FortAwesome/Font-Awesome#17457]
Icons for many programming languages like C , C++ are not there

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

> Icons for many programming languages like C , C++ are not there

Some of the aforementioned languages already exist as individual request, please [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
