### ISSUE TITLE
Icon request: lung-and-heart

### ISSUE THREAD

**Issue by Persern** [FortAwesome/Font-Awesome#17462]
For cardiopulmonary diagnostics using a combined lung and heart icon.

![cardiopulmonary](https://user-images.githubusercontent.com/15012220/101483734-e2ce2c80-3958-11eb-969b-dee8f29c9b5f.png)

**Comment by Persern** [comment]
We have partner that using your awesome icons for theirs health journal system EHR. 
Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that **in a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/102/

Ref:

https://fontawesome.com/v6/docs/web/style/power-transform
https://fontawesome.com/docs/web/style/mask
https://fontawesome.com/docs/web/style/layer

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
