### ISSUE TITLE
fa fa-sign-out not working

### ISSUE THREAD

**Issue by tkadz-zz** [FortAwesome/Font-Awesome#17464]
<i class="fa fa-sign-out"></i>
<span class="fa fa-sign-out"></span>

The above sign-out icon is not working or displaying on html pages

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)

**Comment by ghost** [comment]
Each Font Awesome icon has its name based on the version of the stylesheet you're using so it's better to use the current version of icons provided by their official website.  But for your problem try to check the version of your font awesome at the header file of your HTML code.

**Comment by SanaullaParvez** [comment]
Try fa fa-sign-out-alt
