### ISSUE TITLE
Icon request: search-key

### ISSUE THREAD

**Issue by ddubthekid** [FortAwesome/Font-Awesome#17472]
**What can it be used for?**
This icon would be perfect for Search Engine "keyword(s)"

**Example image (optional)**
<img width="81" alt="Screen Shot 2020-12-10 at 10 03 08 AM" src="https://user-images.githubusercontent.com/57237577/101804771-2fd40f00-3acf-11eb-9980-1cb55dc76e09.png">
+
<img width="78" alt="Screen Shot 2020-12-10 at 10 03 16 AM" src="https://user-images.githubusercontent.com/57237577/101804790-35c9f000-3acf-11eb-961d-86eeb6b02e4e.png">
=
something like: 
<img width="107" alt="Screen Shot 2020-12-10 at 10 03 33 AM" src="https://user-images.githubusercontent.com/57237577/101804820-3cf0fe00-3acf-11eb-8a18-07add3c9fb44.png">

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/475/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
