### ISSUE TITLE
Icon request: mini-bar

### ISSUE THREAD

**Issue by rbriuglia** [FortAwesome/Font-Awesome#17473]
**What can it be used for?**
Hi, I'm collecting icons to best represent the services of a b&b on the website

**Example image (optional)**
https://thenounproject.com/term/mini-bar/599674/

**Icon request checklist**
- [single] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [mini-bar] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
