### ISSUE TITLE
Icon request: set of all movie-genre icons

### ISSUE THREAD

**Issue by healthymike** [FortAwesome/Font-Awesome#17478]
**What can it be used for?** Am loooking for all movie genres to be done as font-awesome icons.

Describe how this could be used / the use case for this icon.
Will be used for my site anyway and others with movie genres instead of the boring listings without the movie genres.

**Example image (optional)**
Insert the example image here if necessary. would be light and dark and also good to be multi-colored....it would be so awesome to have these...

![movie-genre example sreenshot](https://user-images.githubusercontent.com/7598293/102011437-e6ff9e80-3cf8-11eb-9257-13eb585088be.png)
[](url)

**Icon request checklist**
- [ X] This is a single icon or matched pair (Ex: `lock` / `unlock`) ACTUALLY, I want to have all official movie genres done
- [ X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate - i DON'T THINK THEY EXIST EXCEPT FOR SOME .PSD FILES I FOUND, NOT FA 
- [ X] I have included at least one example image if it could be helpful (optional)
- [ X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺) :)
IF i CANT' GET HELP WILL GET SOME CREATED/RE-PURPOSED FOR MY OWN SITE PRIVATELY
-CANNOT ATTACH FILES UNTIL I KNOW IF YOU WISH TO PURSUE IT AS I HAVE A PRIVATE DESIGNER LOOKING AT THIS IF YOU DON'T WANT TO DO IT HERE. I WILL WANT TO WRITE THE GENRE UNDER THE ICON.

THANK YOU.

SORRY FOR THE ALL CAPS. JUST FOR EMPHASIS. NO ANGER. JUST PEACE & LOVE!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Am looking for all movie genres to be done as font-awesome icons.

Sorry, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

If you are Font Awesome Pro customer, you can request icon sets in the Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro?

If you are Font Awesome Pro customer and you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

---

For this particular set, "all movie genres" doesn't help in understanding how many icons are in the set, how many has been done (e.g., [alien](https://fontawesome.com/icons/alien?style=solid) is already available)

So I would procede in this way:
- Create a list of genres
- Change the entries from genre to the exact object they represent (e.g., science fiction => alien)
- Check if the icon has been already implemented and add a note to the list
- Open individual issues in the free repo or request for a set in the pro repo (again, only for pro customers, sets are hard to track and implement)

Hope it helps

Closing here

**Comment by healthymike** [comment]
okay, thank you anyway
