### ISSUE TITLE
Icon request: Drive-file

### ISSUE THREAD

**Issue by PabloNaKai** [FortAwesome/Font-Awesome#17496]
![See example](https://static.tumblr.com/ldd2kms/auVqd13y7/drive.svg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is an edge case, because it uses a brand and mixes it with a standard Font Awesome icon. Said so, if we put this in brand icons, we can't have `far fa-google-drive-file`, and if we put it in the standard set, we will have standard icons containing a brand.

Plus, we are trying our best to follow brand icons and keep them separated

I'm going to ask @sensibleworld for some thoughts about this request

*But...* please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/477/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
