### ISSUE TITLE
Linked in icon not working?

### ISSUE THREAD

**Issue by beckyddesign** [FortAwesome/Font-Awesome#17531]
Hi,
I've never had this issue before, but I've added a Linked In Icon, and it's not rendering properly. Please check the footer on https://garfieldconservatory.org/. It's the last in the series of social icons.  This is the code in the widget:

<a href="https://www.linkedin.com/company/garfield-park-conservatory-alliance" target="blank" title="Follow us on LinkedIn"> <i class="fab fa-linkedin" aria-hidden="true"></i></a>

What am I missing? Please let me know.
Thank you,
Becky

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I can see that your website is loading version 4.5.0 and also 4.7.0, which is probably added via javascript because I can't find it in the source code

```
<link data-minify="1" rel='stylesheet' id='fontawesome-css'  href='https://garfieldconservatory.org/wp-content/cache/min/1/font-awesome/4.5.0/css/font-awesome.min-a540d881e76e023a9957de4ff37ee83d.css' type='text/css' media='all' />
 ```

Since you are using the new syntax for Linkedin (`fab fa-linkedin`), it correctly does not work. If you try with the old syntax (`fa fa-linkedin`) it does

Please notice that Font Awesome 4.x is EOL and is not supported.

You could remove all the occurrences of FA 4.x in your website and try our official wordpress plugin: https://fontawesome.com/how-to-use/on-the-web/using-with/wordpress

Hope it helps

Closing here, but feel free to comment

**Comment by beckyddesign** [comment]
Thank you so much for the quick response. I didn't realize about the multiple versions, I'll have to track that down. Changing the class from fab to fa (I wondered about that) did indeed fix the immediate issue. Much appreciated.
