### ISSUE TITLE
Icon request: sol de mayo

### ISSUE THREAD

**Issue by cosentinowebdev** [FortAwesome/Font-Awesome#17551]
**What can it be used for?**
Describe how this could be used / the use case for this icon.
"sol de mayo"
national icon of several latam countries

**Example image (optional)**
Insert the example image here if necessary.

[https://i.pinimg.com/originals/1b/34/3c/1b343cd1e3fcd2db227779d8c934bc87.jpg](url)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
