### ISSUE TITLE
Icon request: globe-antarctic, globe-arctic

### ISSUE THREAD

**Issue by SpatialDigger** [FortAwesome/Font-Awesome#17563]
**What can it be used for?**
Describe how this could be used / the use case for this icon.
In the same ways as globe-europe, globe-americas etc.
For climate change and spatial distribution information

Oceania has already been requested (see lik), this would give complete world coverage (even if the Arctic is not a continent).
https://github.com/FortAwesome/Font-Awesome/issues/17365

**Example image (optional)**
Insert the example image here if necessary.
In the theme of the other globe- icons

**Icon request checklist**
- [ yes] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ yes] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [yes ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ comparable examples exist] I have included at least one example image if it could be helpful (optional)
- [ yes] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
`fa-earth-antarctic` and `fa-earth-arctic` according with the current icon names.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
