### ISSUE TITLE
Most fonts and icons aren't showing on some sites

### ISSUE THREAD

**Issue by Domino054** [FortAwesome/Font-Awesome#17564]
Hey there. I think I might want to discuss a few issues I'm having. For some reason, icons show up as a dotted circle with a changing exclamation point/question mark, and some fonts have the words "font awesome fontawesome.com -->". I'm not sure why this is happening on my end, but I think might be a bug I'm having. I hope this gets fixed soon.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)
