### ISSUE TITLE
Icon request: Database platform icons (Oracle/SQL Server/PostgreSQL etc)

### ISSUE THREAD

**Issue by alexmasharov2013** [FortAwesome/Font-Awesome#17579]
**What can it be used for?**
You already have all kinds of brand icons, but no database platforms. These would be incredibly useful in the context of any application or website that deals with database services - which are you can imagine is a rather broad subject matter.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

Duplicates:
- #17166 
- #6052
- #2725
