### ISSUE TITLE
Icon showing as boxes.

### ISSUE THREAD

**Issue by rokplays** [FortAwesome/Font-Awesome#17585]
For some reason, randomly all the FA icons on my website turned into boxes. This is the code and what it looks like : 
`				<div class="col-md-3 top-info text-left mt-lg-4">
					<h6>Need Help?</h6>
					<ul>
						<li>
							<i class="fas fa-phone"></i> Message US (Via WhatsApp)</li><br>
						<a href="https://wa.me/message/EOVSSQKWK6QFL1" target="_blank">Click HERE</a>
					</ul>
				</div>`
![image](https://user-images.githubusercontent.com/58662046/105859205-27368a00-5fe4-11eb-87ee-b116d38a22c3.png)

Thanks.

**Comment by songiso** [comment]
Did you include the link from where you got you FA icon in the <head></head> section of HTML?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)
