### ISSUE TITLE
Changed styles from v4 to v5

### ISSUE THREAD

**Issue by calculuschild** [FortAwesome/Font-Awesome#17584]
**Describe the bug**
Disclaimer: I was sent here as the next good place to get help after attempting to get help via email and being told I need a Pro license to get email support.

Is there any way to access some of the old icons from v4 after upgrading to v5? I noticed, for example, the "book" icon has changed quite a bit, and I started getting complaints from users that the new icon isn't as clear what it is supposed to be at a glance, but I also would like to be able to keep my libraries up to date. I didn't want to purchase a full $99 license just to ask a question.

Any help would be appreciated.

**To Reproduce**
https://fontawesome.com/v4.7.0/icon/book
vs
https://fontawesome.com/icons/book

**Expected behavior**
I would expect to have access to the old icons somehow while keeping my libraries up to date.

**Screenshots**

**Version and implementation**
Version: 5.x

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Disclaimer: I was sent here as the next good place to get help after attempting to get help via email and being told I need a Pro license to get email support.
> I didn't want to purchase a full $99 license just to ask a question.

You are in the most appropriate place, email support is dedicated to Pro customers. No way you need to do that, probably there was a misunderstanding

> Is there any way to access some of the old icons from v4 after upgrading to v5?

There are several options (apart from the commercial Pro Kits which allow customers to upload custom icons).

### SVG + JS (easiest)

The easiest method uses the SVG+JS framework. We already have a customization example for this specific use case: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome#svg-framework

The example adds FA4's old `fa-list` to FA5

### CSS (easy)

If you are not using the SVG + JS framework, you can customize FA4 so it can work side by side with FA5. 

You should download FA4's source files and change some variables. It is roughly explained here: #12959

### CSS (hard)

Another chance is to customize the webfont, but that will make updates a lot harder and require third party tools like Fontello / Icomoon

> I would expect to have access to the old icons somehow while keeping my libraries up to date.

We update icons for several reasons, mostly because of uniformity.

For this particular case, the choice to change from a 3D to a 2D books has been done for uniformity with other icons and also to allow [other books](https://fontawesome.com/icons?d=gallery&q=book&s=solid&m=free)

We also listen to the community. AFAIK this is the first feedback we've got about `fa-book`, so this has not come to our attention before. And I can see that FA6's book icon is almost identical to FA5's one, so I do not expect changes in FA6.

I personally think that FA5's book icon is more versatile and in line with all the set

@sensibleworld any thoughts?

Ref:
- https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by calculuschild** [comment]
Thanks! This looks like a good place to start.

Is there any plan in the future to build in access to the older styles in an easier way? Maybe with a secondary optional shim file that we can load up alongside v5, perhaps using another prefix `fa4` as suggested in #12959 so there's no conflict? I can agree with the decision to update a lot of icons to fit some uniform style, but there's so much good work that already went into the old version and it would be nice to make them compatible without manually editing the source files.

As far as the book goes, people were saying it looked like a "paper-towel dispenser" or "a box opened on one end". I don't know if I agree with them but what can I do.

**Comment by sensibleworld** [comment]
Yeah, the easiest way right now to use icons from v4 alongside v5 icons is to become a Pro subscriber and use our Icon Upload feature. Alternately, of course, you can just stick with version 4 entirely! :)

**Comment by tagliala** [comment]
> Is there any plan in the future to build in access to the older styles in an easier way?

Not that I know. That would require to host an alternative CDN version of FA4. Should not take too much of effort, but we are sunsetting the first-party CDN in favor of first-party Kits or third-party CDNs.

Let's see after the release of FA6 if there will be such a request

> As far as the book goes, people were saying it looked like a "paper-towel dispenser" or "a box opened on one end". I don't know if I agree with them but what can I do.

I somehow agree, but I don't know how the book icon can be improved. Maybe with a third line of text and by reducing border radius it could look better. Feel free to open a new request asking for a redesign

PS: does by any chance [book-open](https://fontawesome.com/icons/book-open?style=solid) work better for your use case?
