### ISSUE TITLE
Icon request: user-convicted

### ISSUE THREAD

**Issue by felixboons** [FortAwesome/Font-Awesome#17614]
**What can it be used for?**
Can be used in a criminality type of theme. For example: to display how many criminals are convicted as a result of a criminal event.

**Example image (optional)**
Maybe something like these two examples:
[User mug shot 1](https://cdn1.iconfinder.com/data/icons/crimes-and-justice/100/16-512.png)
[User mug shot 2](https://cdn0.iconfinder.com/data/icons/healthcare-science-and-government/64/shot-police-identification-criminal-mug-arrest-512.png)

Or something along the lines of this:
[User in jail](https://image.flaticon.com/icons/png/128/40/40188.png)

**Icon request checklist**
- [x]  This is a single icon
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
