### ISSUE TITLE
Icon request: user-suspect

### ISSUE THREAD

**Issue by felixboons** [FortAwesome/Font-Awesome#17613]
**What can it be used for?**
Can be used in a criminality type of theme. For example: to display how many suspects are involved with an criminal event.

**Example image (optional)**
I was thinking of the existing fa-user, with kind of a black bar across the eye area. Something like the image below, but then a pixel-perfect variant like you guys know well how to make.

![icon-request-fa-user-suspect](https://user-images.githubusercontent.com/22641882/107102250-2db1d680-681a-11eb-9408-231f2b2374f6.png)

**Icon request checklist**
- [x]  This is a single icon
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
