### ISSUE TITLE
Drupal icon is outdated and needs to be updated

### ISSUE THREAD

**Issue by alexdmccabe** [FortAwesome/Font-Awesome#17633]
**Describe the bug**
I visited the Drupal icon page and saw that it is outdated.

**To Reproduce**
Icon in FA: https://fontawesome.com/icons/drupal
Current Drupal logos: https://www.drupal.org/about/media-kit/logos

**Expected behavior**
Updated icon should be used. SVG files attached in .zip file.

[drupal_svg.zip](https://github.com/FortAwesome/Font-Awesome/files/5982932/drupal_svg.zip)

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for bringing this to our attention.

I can see that Drupal's logo has been already updated by @sensibleworld in the 6.x branch and released in alpha2

FA6 is in private alpha at the moment, if you are a Pro customer you can test it, otherwise please wait for the stable release

Thanks

**Comment by alexdmccabe** [comment]
Thanks!
