### ISSUE TITLE
Icon request: fa-geo.woff2: 50 states, countries, continents

### ISSUE THREAD

**Issue by DeepDivDigital** [FortAwesome/Font-Awesome#17700]
**What can it be used for?**
50 States, Countries, and Continents outlines in fa-geo.ttf, fa-geo.woff2, etc formats
Not to be confused with flags.

**Example image (optional)**
Outline maps on 50 states, countries, and continents
Example:
https://en.wikipedia.org/wiki/File:Texas_in_United_States.svg

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

For the moment I'm going to close here because country silhouettes (and flags) are out of scope. Please consider an alternative library.

This request requires ~ 750 new icons ((50 states + 195 countries + 5 continents) * 3 styles). Also, each glyph contains a lot of points and they will be too complex to be rendered at small sizes (16px)

Moreover, requests for icon sets does not meet our contributing guidelines for the Free Repo:

>  This is a single icon or matched pair (Ex: lock / unlock)

FA Pro customers can request sets in the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro

If you are a customer and you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
