### ISSUE TITLE
Icon request: user-staff

### ISSUE THREAD

**Issue by gmw-web** [FortAwesome/Font-Awesome#17711]
**What can it be used for?**
Could be used to indicate workplace relationships/hierarchy between users.

**Example image (optional)**
![staff](https://user-images.githubusercontent.com/27803283/110494522-faea4f00-80f3-11eb-9a4d-20b98f19c35e.png)
(but lose the moustache to keep things neutral)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
