### ISSUE TITLE
Icon request: icon-moneyTruck

### ISSUE THREAD

**Issue by aktxyz** [FortAwesome/Font-Awesome#17714]
**What can it be used for?**
This is an icon to show moving money, to be used for transfers/payments/advances/p2p/etc ... or any time you want to represent moving money

**Example image (optional)**
I was thinking something like truck-moving or truck with a $ in the box ... it may also be nice to have a few other currency symbol options (euro rmb etc)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
