### ISSUE TITLE
Icon request: widget

### ISSUE THREAD

**Issue by gnpsi** [FortAwesome/Font-Awesome#17713]
**What can it be used for?**
Widget Menu Icon
![image](https://user-images.githubusercontent.com/43901802/110587941-a3adb280-81b7-11eb-9ff1-7527ee6e8aed.png)

**Example image (optional)**
<img width="177" alt="스크린샷 2021-03-10 오후 3 33 52" src="https://user-images.githubusercontent.com/43901802/110586929-449b6e00-81b6-11eb-8cce-b979414e72ec.png">

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
Hi @gnpsi,

The roundered icon is [fa-table-cells-large](https://fontawesome.com/icons/table-cells-large).

Regards.

cc/ @tagliala

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
