### ISSUE TITLE
Icon request: eua-white

### ISSUE THREAD

**Issue by IFFR-Baba** [FortAwesome/Font-Awesome#17724]
**What can it be used for?**
Is the logo of my Virtual Airlines on Microsoft Flight Simulator 2020 and i would like to use it for me website 

**Example image (optional)**

![eua-white](https://user-images.githubusercontent.com/66707961/110985486-cb924700-836c-11eb-9e8b-8e169deceb3b.png)

**Icon request checklist**
- [v ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [v ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [v ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ v] I have included at least one example image if it could be helpful (optional)
- [ v] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Is the logo of my Virtual Airlines on Microsoft Flight Simulator 2020 and i would like to use it for me website

Could you please clarify this request?

**Comment by IFFR-Baba** [comment]
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> > Is the logo of my Virtual Airlines on Microsoft Flight Simulator 2020 and i would like to use it for me website
> 
> Could you please clarify this request?

So, I have a virtual airline on microsoft flight simulator 2020 and I would like to have a custom icon to add it in our site, I would find it great to have our own icon in our site

**Comment by tagliala** [comment]
Thanks for the clarification.

Since this icon does not represent an existing brand and as far as I got other Font Awesome users don't need to reference your website, I should suggest you to consider different options:

- Free alternative: a custom build. Very easy with SVG Framework: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
- Commerical software: Custom icon with our Pro Kits: https://fontawesome.com/how-to-use/on-the-web/using-kits/uploading-icons
- [Sponsor the icon](https://fontawesome.com/community/leaderboard/brands#faqs). Sponsored icons will be added to Font Awesome Free

If you provide a reference to your site and a valid use case (e.g. "I want to request an icon for AwesomeSocialNetwork (`https://awesomesocial.example.com`) so people can add a link to their profile") and I will consider reopening
