### ISSUE TITLE
Icon request: fa-laptop-upload, fa-laptop-download

### ISSUE THREAD

**Issue by cdac2019** [FortAwesome/Font-Awesome#17721]
need icon both combine upload +laptop and  downloade+laptop

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/502/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by cdac2019** [comment]
Thanks, it was pretty cool icon

**Comment by tagliala** [comment]
Hi, welcome. I've edited the demo and added a couple of more ideas that I think works better

![image](https://user-images.githubusercontent.com/556268/110938775-a84ba580-8334-11eb-9c6e-bfb9abf74afc.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
