### ISSUE TITLE
Icon request: support

### ISSUE THREAD

**Issue by udaykiran2897** [FortAwesome/Font-Awesome#17778]
**What can it be used for?**
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We do have a couple of icons to represent "support":

- https://fontawesome.com/icons/user-headset?style=solid (PRO)
- https://fontawesome.com/icons/life-ring?style=solid
- https://fontawesome.com/icons/headset?style=solid

If they don't feet your needs, feel free to open a new request having care to:
- Provide an example 
- A possible better title (concrete object instead of idea, so that the example is not necessary)
- Explain why [icons tagged with support]() don't work for your case
- [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before

Closing here
