### ISSUE TITLE
Icon request: 'shopping-bag-plus'

### ISSUE THREAD

**Issue by gtirard** [FortAwesome/Font-Awesome#17785]
**What can it be used for?**
Same as cart-plus, but with a shopping bag instead of the shopping cart. To allow users to add items in the shopping bag.

**Icon request checklist**
- [ ] This is a single icon
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- Should be easy to create, adding a + sign in the middle of the existing 'shopping-bag' icon

**Comment by tagliala** [comment]
> I’m not sure it would work for the light style though?

Yes, it works and looks quite good with stack: https://jsfiddle.net/tagliala/gxd2s1h3/7/

https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
