### ISSUE TITLE
CSS showing Error for -ms-filter property as not found in fa 5.15.3 version

### ISSUE THREAD

**Issue by nandkishorakangire** [FortAwesome/Font-Awesome#17820]
There is an issue in Font Awesome as CSS throwing an error '-ms-filter property not found' in Font Awesome 5.15.3  version. So using offline font or icons not possible due to an error as browser isn't allowing it to render.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)
