### ISSUE TITLE
Icon request: neurodiversity-flag

### ISSUE THREAD

**Issue by devlavender** [FortAwesome/Font-Awesome#17831]
**What can it be used for?**
In communication about autism, specially by self-advocacy groups and by the autism rights movement; for the Autism Acceptance Day (april 2nd), Autism Acceptance Month (april) and the  Autistic Pride Day (june 18th); and for communication by people with other neurodiversity types (i.e. ADHD, dyslexia, etc)

**Example image (optional)**
https://en.wikipedia.org/wiki/File:Neurodiversity_Symbol.svg

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Since we are limited to icons in a single color, does https://fontawesome.com/icons/infinity?style=solid work for this use case?

I know that it is not identical, but the best we could do is to add a slightly different infinite icon like this one: 
![image](https://user-images.githubusercontent.com/556268/115353645-0e8bd980-a1b9-11eb-8e8c-90e606e91b73.png)

**Comment by oldlavender** [comment]
@tagliala thanks, and I really apologize for taking so long to answer, I ended up not seeing the notification until now. 

> Hi!
> 
> Since we are limited to icons in a single color, does https://fontawesome.com/icons/infinity?style=solid work for this use case?

Well, the color is typically the distinguishable feature of the symbol for it represents the diversity in the spectrum. But I do understand that fa icons are in a single color and have some idea of the reasons for that, so I guess that can't be done.

> 
> I know that it is not identical, but the best we could do is to add a slightly different infinite icon like this one: ![image](https://user-images.githubusercontent.com/556268/115353645-0e8bd980-a1b9-11eb-8e8c-90e606e91b73.png)

I think the shape is perfect, IMO it's quite better than the infinite symbol. I think this could be included right now. But if there's a way to add a 'neurodiversity' writing, like this it would be even better:
![image](https://user-images.githubusercontent.com/24969130/154277576-ea85ea41-e5ea-467c-bc57-160b2bdb1bbc.png)

I mean just the writing, not necessarily the effects.

With changes in writing there could be also some derived icons, like the autism-flag, with just "Autism", and the actually-autistic, with the text "Actually Autistic", and the autistic-pride, with the text "Autistic Pride", for instance, if it's not too much to ask. I think the autism-flag and the autistic-pride icons would be quite useful in web pages of autism and autistic pride events, etc, while the actually-autistic would be great for profiles, personal pages/blogs of autistic users, etc.

Best regards,
Bruno Moreira-Guedes

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
