### ISSUE TITLE
Icon request: non-alcoholic-drink

### ISSUE THREAD

**Issue by TimmJensen** [FortAwesome/Font-Awesome#17858]
**What can it be used for?**
Describe how this could be used / the use case for this icon.
To be able to show a cocktail recipe, contains alchohol or not.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Insert the example image here if necessary.

I think an example is necessary for this icon

**Comment by TimmJensen** [comment]
![image](https://user-images.githubusercontent.com/29592319/116407155-c2343f80-a831-11eb-9a65-5dbcc9a22fb3.png)

I've attached an example here.

**Comment by tagliala** [comment]
Thanks for the example

We tend to avoid text in Font Awesome icons because they lead to localization issues.

Also, the provided example is too complex for 16px icon size: ![image](https://user-images.githubusercontent.com/556268/116408192-cf9df980-a832-11eb-915b-4c6a1dbd46f2.png)

Is there any other example:
- without text
- which plays well at 16px icon size

**Comment by TimmJensen** [comment]
I understand, what about something like this:

![image](https://user-images.githubusercontent.com/29592319/116408610-49ce7e00-a833-11eb-9d61-ee6a2cffe866.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
