### ISSUE TITLE
Icon request: ADHD Neurodivergent brains

### ISSUE THREAD

**Issue by RuthSss** [FortAwesome/Font-Awesome#17857]
Icon for ADHD
I wish to make a blog to create awareness about ADHD in my community here. ADHD is something new and it is not recognized by our society (Malaysian). I am bad at graphic designing. Hence, I would appreciate some contribution on this at the same time to lend help for ADHD community here in Malaysia. 

My motive to create this blog, because I believe that there are still many people in my society are struggling with their life unknowingly that they may have mental health issue. In regards to this, I want to help to spread the awareness and voice out about ADHD which I,  myself is diagnosed with it. 

If there is any creative and talented ADHDer out there who come across this request. I humbly seek for your kind help. 

Thank you.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
