### ISSUE TITLE
Icon request: pangolin

### ISSUE THREAD

**Issue by MWWorks** [FortAwesome/Font-Awesome#17862]
**What can it be used for?**
Currently missing from the Animals category. Would be good to have because a) they are a symbol of endangered wildlife and conservation (as one of the most illegally trafficked animals) and b) because they are very cute :)

**Example image (optional)**
Here are some reference images: https://wallpapercave.com/pangolin-wallpapers

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
