### ISSUE TITLE
Not showing icons when deploy to heroku

### ISSUE THREAD

**Issue by pedroherreraj** [FortAwesome/Font-Awesome#17906]
Hey! 
When i work locally, the icons are shown, but when i deploy to heroku the dissapear. I look in the website but the answer didnt work for me? What should i do?

Locally:
<link href="http://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">
All ok with this

On deploy:
I tried what is shown in the website

<head>
<script defer src="../../node_modules/@fortawesome/fontawesome-free/css/all.min.css"></script>
<script defer src="../../node_modules/@fortawesome/fontawesome-free/js/all.js"></script>

</head>

<body>
<i class="fas fa-user"></i> 
 <i class="fab fa-github-square"></i> 
</body>

The path is ok. I dont know what the error might be

Thank you!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, this is a help request and it is out of the scope of this repositoru. You may try to ask on Stack Overflow.

If you are a Font Awesome Pro costumer, you may also ask for dedicated support at hello@fontawesome.com

Since there are a lot of different ways of bundling your assets and deploying them on Heroku, it is hard and time consuming to say what is going, wrong without having all the details, so I strongly suggest to provide as many details as you can and a reproducible test case

Anyway, Font Awesome [does work on Heroku](https://ruby3-rails6-bootstrap-heroku.herokuapp.com/). [Here](https://github.com/diowa/ruby3-rails6-bootstrap-heroku) you can find the source code to deploy a Rails application and serve Font Awesome SVG's npm modules with webpacker, served by puma. Other methods will also work, but again they depend on how the application is deployed

Hope it helps

Closing here
