### ISSUE TITLE
Icon request: mobile-cracked

### ISSUE THREAD

**Issue by lhulbert** [FortAwesome/Font-Awesome#17900]
**What can it be used for?**
A version of fa-mobile (or one of its variations) with a cracked screen can be used to represent broken phone. This could be used on websites for phone repair shops or insurance companies.

**Example image (optional)**
![94281-200](https://user-images.githubusercontent.com/83889416/118308050-66c9a900-b4e3-11eb-9dc0-42d6c3641d63.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
