### ISSUE TITLE
Request setting a default icon when icon not found

### ISSUE THREAD

**Issue by ooo2003003v2** [FortAwesome/Font-Awesome#17916]
Hello there.
Is there any ways to set a icon when the icon doesnt in the IconName type in fontawesome common types?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

You mean to fallback on a specific icon when the requested icon is not found when using the SVG Framework?

**Comment by ooo2003003v2** [comment]
I'm letting the user to chooses the icon they want and I want to handle if the icon not found shows a default icon for not found. Any idea?

```
  const formSideMenuIcon = (icon: string) => {
      if (icon.indexOf(".svg") > -1)
        return <ReactSVG className="side-menu-svg" src={"icon/" + icon} />;
      else {        
          return <FontAwesomeIcon icon={icon as IconName} />;
      }
    };
```

**Comment by tagliala** [comment]
I'm not familiar with React and typescript.

Maybe you can check if the icon is defined through the core JavaScript API?

```js
import { findIconDefinition } from '@fortawesome/fontawesome-svg-core'

// returns undefined if the icon is missing
if (findIconDefinition({ prefix: 'fab', iconName: icon })) {
  // ...
}
```

There is also an undocumented way (so this may change) that could be faster since it is just checking the existence of a key:

```
import { library } from '@fortawesome/fontawesome-svg-core'

if (Object.prototype.hasOwnProperty.call(library.definitions.fab, 'github')) {
  // ...
}
```

Ref: 
- https://fontawesome.com/how-to-use/javascript-api/setup/getting-started
- https://fontawesome.com/how-to-use/javascript-api/methods/findicondefinition

@robmadole is there a better way?

**Comment by ooo2003003v2** [comment]
Oh great. That's exactly what I'm looking for. Thanks a lot
