### ISSUE TITLE
Icon request: swastika

### ISSUE THREAD

**Issue by ManasMadrecha** [FortAwesome/Font-Awesome#17936]
**What can it be used for?**
It denotes auspiciousness in Hindu, Jainism, and Buddhism religions.
 
**Example image (optional)**
https://commons.wikimedia.org/wiki/File:HinduSwastika.svg

Note: The dots can be omitted.

![image](https://user-images.githubusercontent.com/65993481/119630348-7ecaf200-be2c-11eb-9273-70c33e8cfa8b.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by minecrawler** [comment]
+1

In East Asia, 卍 denotes Buddhism and Buddhist temples and should be added to include this important religion and content for East Asia!

E.g. to mark things on maps and in menus:

![Map of Tokyo, Japan, highlighting Biddhist temple symbols](https://github.com/FortAwesome/Font-Awesome/assets/1130708/e890e926-636a-4695-9ad7-4dddf2cd458f)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
