### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by deadmann** [FortAwesome/Font-Awesome#17955]
`Refund` -- when you are about to cancel an order, or return a product
`delivered` -- when you deliver something in a logistic / shopping environment
`checking`, or `overviewing` -- in my case I want to indicate the process of the logistic is not yet starting, and it is not yet viewed or processed by any one
`processing` -- processing something by human or machine...

are missing...

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please open new, individual request and please provide examples for icons, because `delivered` is abstract and hard to represent, while [box-check](https://fontawesome.com/v5.15/icons/box-check?style=solid) isn't

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
