### ISSUE TITLE
Icon request: overview / not-overviewd | checked / not-checked

### ISSUE THREAD

**Issue by deadmann** [FortAwesome/Font-Awesome#17967]
**What can it be used for?**
Can be useful in dashboard, for example you have new record in your database and you can show the number of record that are not checked, or overviewed by your team.... or those who take minimum action, and someone attended to.

**Example image (optional)**
https://cdn.onlinewebfonts.com/svg/img_509213.png
https://cdn0.iconfinder.com/data/icons/seo-and-internet-marketing/70/SEO_and_Internet_Marketing-02-512.png
https://image.flaticon.com/icons/svg/86/86158.svg

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi,

could you please clarify this request? I don't get how many icons this request includes.

There are some icons that may do the job in FA Pro:
- https://fontawesome.com/v5.15/icons/clipboard-list-check?style=solid
- https://fontawesome.com/v5.15/icons/file-search?style=solid
- https://fontawesome.com/v5.15/icons/file-chart-line?style=solid
- https://fontawesome.com/v5.15/icons/file-chart-pie?style=solid

Also, we try our best to keep icons as simple as possible so that they can be used at 16px icon size

> > I have searched for existing issues and to the best of my knowledge this is not a duplicate
> 
> the issue list is crowded by unrelated stuffs

Any example of the searches you tried?

**Comment by deadmann** [comment]
The following are ok somehow, still, they do not include the version in which it indicates the reverse, the absence...
> - [x] https://fontawesome.com/v5.15/icons/clipboard-list-check?style=solid
> - [x] https://fontawesome.com/v5.15/icons/file-search?style=solid
> - [ ] https://fontawesome.com/v5.15/icons/file-chart-line?style=solid
> - [ ] https://fontawesome.com/v5.15/icons/file-chart-pie?style=solid

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
