### ISSUE TITLE
Icons shown with older version are not shown with newer version.

### ISSUE THREAD

**Issue by domino2** [FortAwesome/Font-Awesome#17990]
When using the most recent version, icons are not shown in the browser.
On the other hand, switch to version 4.7.0 is showing icons fine.

https://codesandbox.io/s/wild-mountain-q0z9h?file=/index.html

You can see two styles in the src, one commented out which is working and another used which is issued.
I don't understand what I'm doing wrong as it seems to me a bit inconsistent.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> `https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/fontawesome.min.css`

This link is not the correct one, because it only includes the shared css of Font Awesome. Please use `all.css` or add individual styles that you are interested in (`solid.css`, `regular.css`)

Syntax changed in FA5, your have two options:
1. Add `v4-shims.css` to your stylesheets
2. Update the syntax (`fa fa-circle-o`  => `far fa-circle`, `fa fa-youtube` => `fab fa-youtube`)

Docs: https://fontawesome.com/v5.15/how-to-use/on-the-web/setup/upgrading-from-version-4

Partially fixed codepen: https://codesandbox.io/s/silent-voice-zkr0j?file=/index.html

Hope it helps

Closing here
