### ISSUE TITLE
Include easily-accessible version information

### ISSUE THREAD

**Issue by jigarius** [FortAwesome/Font-Awesome#18009]
## The problem

* I am maintaining an old website that has FontAwesome
* There is no easy way for me to find the version of font awesome it uses
* If there were a version.txt or if the readme included the version number, it would be easy to find the version number.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> There is no easy way for me to find the version of font awesome it uses

The version number should be present in the license of the CSS file. Did you try there?

> If there were a version.txt or if the readme included the version number, it would be easy to find the version number.

I think this will not solve the issue, because if someone is hosting Font Awesome on their server those files will be removed from production assets. Also, some minifiers could (wrongly) strip the license file from the CSS.

**Comment by jigarius** [comment]
Unfortunately, there is no version string in the `LICENSE.txt`.

```

**Comment by jigarius** [comment]
The above signature is not there in the version I have. However, I got lucky. In `variables.less`, there is a var declaration:
```
@fa-version: "5.7.0";
```
