### ISSUE TITLE
Icon request: row-density

### ISSUE THREAD

**Issue by ebrenesTY** [FortAwesome/Font-Awesome#18048]
3 icons for row density.  The are typically used to show how tight you want table rows (default, roomy, compact).
![Screen Shot 2021-07-02 at 9 59 03 AM](https://user-images.githubusercontent.com/86843286/124293324-28805b80-db1c-11eb-9356-e8f5d88128c4.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think that
- [fa-bars](https://fontawesome.com/v5.15/icons/bars?style=solid); and
- [fa-align-justify](https://fontawesome.com/v5.15/icons/align-justify?style=solid)

covers 2 out of 3 cases

There is also [fa-grip-lines](https://fontawesome.com/v5.15/icons/grip-lines?style=solid), but bars are wider

**Comment by ebrenesTY** [comment]
@tagliala those are close, but really the icon would have the same number of lines and then the negative space between them would be less and more vs. just less lines.

**Comment by nimabrownlee** [comment]
@tagliala Any chance this gets added in version 6? These icons and another one stops me from buying the license.

**Comment by tagliala** [comment]
@nimabrownlee please take a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

> These icons and another one stops me from buying the license.

With FA Pro and Kits or SVG + Free you can add custom icons to your set: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome#svg-framework

It is also possible with CSS, but it is more complex (same link as before)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
