### ISSUE TITLE
Icon request: Casino icon (building)

### ISSUE THREAD

**Issue by Madaluna** [FortAwesome/Font-Awesome#18082]
**What can it be used for?**
To describe the gambling industry. Would be awesome if it were more than 1.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Any example of how this icon should look like?

We have:
- https://fontawesome.com/v5.15/icons/dice?style=solid
- https://fontawesome.com/v5.15/icons/coins?style=solid

And a request for a poker chip icon #1004, maybe more requests are here

**Comment by Madaluna** [comment]
![casino](https://user-images.githubusercontent.com/84723532/125925900-a288e4e4-ad41-4344-b2fe-02b00ed20e2b.png)
Something like this would be awesome.

**Comment by tagliala** [comment]
Ok got it, thanks for the clarification and for the example

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
