### ISSUE TITLE
Icon request: icon-input-textarea

### ISSUE THREAD

**Issue by pb-z** [FortAwesome/Font-Awesome#1810]
This icon will tell user that it is for paragraph text input field.

**Comment by mikethedj4** [comment]
+1 

![textbox](https://cloud.githubusercontent.com/assets/2473707/5607349/9b460e78-941d-11e4-8355-1d899a5fdd7a.png)

**Comment by henleywc** [comment]
+1

**Comment by dmland** [comment]
+1, but a design that corresponds better to FA's other icons, please.

**Comment by aethior** [comment]
~~Duplícate of #17592?~~

cc/ @tagliala

**Comment by aethior** [comment]
@tagliala check here please. :)

**Comment by tagliala** [comment]
Not a duplicate, textarea is different. Should be represented with a slightly higher textinput

- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/input-pipe?f=classic&s=solid)
