### ISSUE TITLE
Icon request: Ripped-

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#18112]
**What can it be used for?**

To show a ripped blanket or that this animal rips blankets

**Example image (optional)**

![image](https://user-images.githubusercontent.com/88024270/127113663-a9f6c450-c4a3-4dc2-bbe4-6e540344502b.png)

**Icon request checklist**
- [x] This is a single icon or matched pair `lock` 
- [x] The title starts with "Icon request: " and is followed by the requested icon name 
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
