### ISSUE TITLE
Icon request: barber-razor

### ISSUE THREAD

**Issue by dejvidko** [FortAwesome/Font-Awesome#18128]
Icon for barber shop menu

![image](https://user-images.githubusercontent.com/88290591/127841949-0f7c9977-109f-4bbc-97f0-430a5abac2ff.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
*Related Unicode Emoji* #222
🪒 [U+1FA92](https://emojipedia.org/emoji/%F0%9F%AA%92/) Razor

**Comment by aethior** [comment]
Related (not duplicated):

`razor`: #15869
`barber-razor`: #18128
`electrick-razor`: #15871

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
