### ISSUE TITLE
Icon request: Sore throat, sneeze, tiredness

### ISSUE THREAD

**Issue by lautaja2** [FortAwesome/Font-Awesome#18136]
**What can it be used for?**
Symptoms for COVID and/or influenza 

**Example image (optional)**
Insert the example image here if necessary.
https://media.istockphoto.com/vectors/sore-throat-thin-line-icon-symptom-of-flu-influenza-cold-vector-vector-id1164549124?k=6&m=1164549124&s=612x612&w=0&h=MIUItwwIU7vUAb0DRXwJKulsvLTy4NIJB-ZAyHLTnlM=

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request? It is not clear if this is a request for a single icon or three icons

If you are requesting three icons, please open three individual request with specific title and please add a single color example that works at small font size, especially for "tiredness" (it's an abstract concept hard to represent)

We already have a sneeze/cough icon: https://fontawesome.com/v5.15/icons/head-side-cough?style=solid

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
