### ISSUE TITLE
icon request: debugging steps

### ISSUE THREAD

**Issue by JerGallagher-TMobile** [FortAwesome/Font-Awesome#18138]
There currently aren't any icons options for debugging in font-awesome, such as:
- step-over 
- step-into
- step-out
- set-breakpoint
- remove-breakpoint
- go-next-breakpoint
- go-prev-breakpoint

Visual examples from chrome dev tools:
![image](https://user-images.githubusercontent.com/56324769/128224101-3f36de94-3ffb-422f-8898-2dcd663dbee7.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I don't know if it is a good idea to keep this request open.

Requests for icon set do not meet our contributing guidelines **but** this is a specific set, the pause icon is already available, and the other ones are strictly related

Said so, this is a request for 7 * 5 icons (7 icons in 5 different styles) **and** other debuggers may require extra icons

I will keep this open for a while and wait for feedback from the community

**Comment by JerGallagher-TMobile** [comment]
Hi

Thanks for your feedback.  I did submit a request form for the icon-set using a template after creating this issue..

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
