### ISSUE TITLE
Icon request: sliding-gate

### ISSUE THREAD

**Issue by dresende** [FortAwesome/Font-Awesome#18137]
**What can it be used for?**

This could be used in cases where we want to address a house gate, not a door nor a garage door. This is specially useful for example for home automation applications.

**Example image (optional)**

These are not icon example but rather images of a sliding gate for consideration:

![Screenshot 2021-08-04 at 18 00 57](https://user-images.githubusercontent.com/157494/128223278-4df2f07e-caae-4d81-ad3b-9297f41c1daa.png)

**Icon request checklist**

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
