### ISSUE TITLE
Icon request: fa-ts, fa-ts-square

### ISSUE THREAD

**Issue by sametweb** [FortAwesome/Font-Awesome#18169]
**What can it be used for?**
Most programming languages and frameworks have their own icons. TypeScript needs to be on the list.

I found in the issues that somebody else requested an icon for TS but it's a 4-year-old topic and does not follow the contribution guidelines so here is mine.

**Example image (optional)**
https://upload.wikimedia.org/wikipedia/commons/4/4c/Typescript_logo_2020.svg

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi, 

> I found in the issues that somebody else requested an icon for TS but it's a 4-year-old topic and does not follow the contribution guidelines so here is mine.

Thanks for opening a request that meets our contributing guidelines, but #11890 is perfectly fine since at the time we didn't have contributing guidelines. Also, requests for brands like typescript are 100% unambiguous, so the title is enough

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here as a duplicate #11890
