### ISSUE TITLE
Icon request: fa-afghani-sign (Afghanistan Currency Sign ؋)

### ISSUE THREAD

**Issue by afsheen1** [FortAwesome/Font-Awesome#18160]
Hello,

As developer using the icon set for designing some time it required to get currency sign of specific country. the sign of Afghanistan currency not available in fontawesome.

It will be great to have one.

example img: https://image.shutterstock.com/image-vector/afghani-icon-currency-symbol-vector-600w-364286816.jpg

thanks :)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
