### ISSUE TITLE
Icon request: fa-location-dot-square

### ISSUE THREAD

**Issue by jrahma** [FortAwesome/Font-Awesome#18168]
Hi,

Please add a square location icon

`https://www.iconfinder.com/icons/2748523/location_map_marker_pin_icon`

Thanks,
Jassim

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but if you are using Font Awesome on a web application, please keep in mind that you can achieve this icon with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/zfbpsok1/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
