### ISSUE TITLE
Icon Request: fa fa-graduation-cap-vidi

### ISSUE THREAD

**Issue by irtadmin** [FortAwesome/Font-Awesome#18176]
Please help me to create an icon for my old website. I need the icon "fa fa-graduation-cap" with the word "VIDI" on right sub 

Thank you so much for your support!

![image](https://user-images.githubusercontent.com/70309624/129705393-d97fcac5-e726-4b79-afe7-92bc8f0a56ed.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
