### ISSUE TITLE
Solid pseudo elements not working

### ISSUE THREAD

**Issue by streater3000** [FortAwesome/Font-Awesome#18186]
So I have been able to get regular and brand pseudo elements to work.

I cannot get the solid pseudo elements to work. I have struggled for months on this. Things I have tried:

`.lock a:before{
font-family: 'Font Awesome 5 Free'!important;
content: "\f023"!important;
font-weight: 900!important;
}`
`.lock a:before{
  font-family: 'Font Awesome\ 5 Free';
content: '\f023';
font-weight: 900;
}`
`
.lock a:before{
font-family: 'Font Awesome 5 Solid';
content: "\f023";
font-weight: 900;
}
`
someone even said to add this on a forum:
`
.fas {
font-family: "Font Awesome 5 Free Solid", "Font Awesome 5 Free" !important;
}`

I am loading the code with this which works for regular icons and brands:
`   @font-face {
    font-family: 'Font Awesome 5 Brands';
    font-style: normal;
    font-weight: 400;
    src: url("../webfonts/fa-regular-400.eot");
  src: url("../webfonts/fa-regular-400.eot?#iefix") format("embedded-opentype"), url("../webfonts/fa-regular-400.woff2") format("woff2"), url("../webfonts/fa-regular-400.woff") format("woff"), url("../webfonts/fa-regular-400.ttf") format("truetype"); }
`
I also tried this:
`   @font-face {
    font-family: 'Font Awesome 5 Free';
    font-style: normal;
    font-weight: 900;
    src: url("../webfonts/fas-solid-900.eot");
  src: url("../webfonts/fas-solid-900.eot?#iefix") format("embedded-opentype"), url("../webfonts/fas-solid-900.woff2") format("woff2"), url("../webfonts/fas-solid-900.woff") format("woff"), url("../webfonts/fas-solid-900.ttf") format("truetype"); }
`
I also tried this in the header:
`<link href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" rel="stylesheet" />`

At one point I signed up for Font Awesome Pro because I thought their support could help but they only gave me one word answers with no direction. Thankfully they gave me a refund.

Also, I can't use the plugin because it gives me Sanitizer Errors on Firefox... this is why I am trying to load it with code.

Any ideas? 

Any help greatly appreciated since the documentation doesn't answer this... nor any other forums (I have probably read them all... this has been a months long search).

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

There are many ways of using Font Awesome, and for me it is difficult to understand how it is used in your particular case

Said so, it looks like you are self-hosting but you also tried the CDN of the CSS implementation, so I'm going to exclude SVG for the moment

I will provide you a working demo with the CDN, because self-hosting requires additional configuration and it is up to the end user to make sure that everything is working (mime types, cache invalidation, stylesheet references to the font)

Working demo (5.15.4 / CSS / CDN): https://jsfiddle.net/tagliala/vbhdn9te/2/

Docs:
- Self hosting: https://fontawesome.com/v5.15/how-to-use/on-the-web/setup/hosting-font-awesome-yourself
- Pseudo elements (with CSS implementation): https://fontawesome.com/v5.15/how-to-use/on-the-web/advanced/css-pseudo-elements 

Since I'm not able to reproduce, I'm going to close here

Feel free to comment or to edit the opening post with a reproducible test case showing the issue

**Comment by streater3000** [comment]
Yes I have it set up like the demo... all icons work except the solid.

My guess it has something to do with how I am importing it:
`   @font-face {
    font-family: 'Font Awesome 5 Brands';
    font-style: normal;
    font-weight: 400;
    src: url("../webfonts/fa-regular-400.eot");
  src: url("../webfonts/fa-regular-400.eot?#iefix") format("embedded-opentype"), url("../webfonts/fa-regular-400.woff2") format("woff2"), url("../webfonts/fa-regular-400.woff") format("woff"), url("../webfonts/fa-regular-400.ttf") format("truetype"); }
`

What is the correct @font-face code? Any ideas here?
