### ISSUE TITLE
yarn add error with pro

### ISSUE THREAD

**Issue by ryderevans** [FortAwesome/Font-Awesome#18183]
I'm getting this error message when running yarn add

 @fortawesome/pro-light-svg-icons@npm:^5.14.0: The remote server failed to provide the requested resource

I'm also getting it also with the link copied from your website - for pro and not free.

I've followed the instructions for registering my pro code. Server is sending back a 404 error code.

**Comment by AndrewsGomesViamo** [comment]
I'm having the same issue

**Comment by tagliala** [comment]
Hi @AndrewsGomesViamo 

The source of this issue changes from case to case and we can't do too much on the free repo

I would suggest to take a second look at the docs: https://fontawesome.com/docs/web/setup/packages#installing-pro

Then please try to debug your configuration. Check your `.npmrc` files, there should be an entry pointing the `@fortawesome` namespace to the NPM pro repository.

You should be able to have detailed information by running `yarn config list --verbose`
 
It will output a list of paths in which there could be a `.npmrc` loaded by yarn and the actually loaded configuration, that may include
 
```
info npm config
{
  ...
  '@fortawesome:registry': 'https://npm.fontawesome.com/',
  '//npm.fontawesome.com/:_authToken': 'A-TOKEN'
}
```

If the authToken is an environment variable, please also double check that the variable returns a correct value

After it is sure that your configuration is ok, please send an email at hello@fontawesome.com because it could be a license issue and as a Pro user you have dedicated support

---

I'm going to close this issue because there is not much that we can do on the free repo about private npm issues
