### ISSUE TITLE
Icon request: flag-uae 🇦🇪 

### ISSUE THREAD

**Issue by jrahma** [FortAwesome/Font-Awesome#18194]
Hi,

Please add UAE flag

Thanks,
Jassim

**Comment by ASKayed** [comment]
🇦🇪

**Comment by jrahma** [comment]
It will be great if you add both rectangle and circle flags

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Comment by sensibleworld** [comment]
Just a quick note that we're moving all individual country-flag requests to a single open issue: https://github.com/FortAwesome/Font-Awesome/issues/20288
