### ISSUE TITLE
Icon Request: House, Land, Gross Area

### ISSUE THREAD

**Issue by JTGMAGIC** [FortAwesome/Font-Awesome#18203]
Hey,
I use these icons a lot, I use in real estate business but can be use in more places. 

Something like this
![Screenshot 2021-08-26 160547](https://user-images.githubusercontent.com/5827892/130988032-a7c2b9dd-205a-4dd9-92f9-acb89480d053.png)

Thanks and have a good week.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
