### ISSUE TITLE
Icon request: map-marker-play

### ISSUE THREAD

**Issue by demiantres** [FortAwesome/Font-Awesome#18215]
**What can it be used for?**
A map marker marking the start of a route.

**Example image (optional)**
A marker symbol with a "Play" triangle inside.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/557/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by demiantres** [comment]
Thanks. We are using the Pro version of FontAwesome on a desktop application which relies on fonts.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
