### ISSUE TITLE
icons are not visibale

### ISSUE THREAD

**Issue by raghad-farhud** [FortAwesome/Font-Awesome#18218]
hi, I love your website, it makes my journey way easier!
I just want to report about a problem the icons exest on the website but with no shape!
here's the photo to explain 
the icons are the ones with purple background:
![‏‏لقطة الشاشة (257)](https://user-images.githubusercontent.com/86526536/131376646-ee5c65db-9ba6-444e-88d4-54d6994ee30d.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)
