### ISSUE TITLE
Cross-site scripting & FireFox

### ISSUE THREAD

**Issue by hmarclewis** [FortAwesome/Font-Awesome#18220]
Because **FireFox** now disallows cross-site scripting, loading my FontAwesome javascript fails on that browser.  Works a treat on the latest **Safari** & **Chrome** on **MacOS**, though.  Awesome product -- Thanks!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)

**Comment by hmarclewis** [comment]
It was just a heads-up that since the <script> tag to load the FontAwesome javascript was implemented, FireFox changed the rules to disallow cross-site scripting, which is what your <script> tag does.

It isn't a bug, necessarily, but it does mean that now the millions of FireFox users can't view Webpages that use the FontAwesome package (which they previously COULD view)...

--haydn
