### ISSUE TITLE
Icon request: aspen leaf

### ISSUE THREAD

**Issue by kfloyde** [FortAwesome/Font-Awesome#18227]
**What can it be used for?**
I would use this in logo design and bulleted lists (ie: newsletters)

**Example image (optional)**
![img_ 119](https://user-images.githubusercontent.com/7378909/131699467-0133a759-8d3e-43e3-b88d-01affe972a3b.png)
There are lots of ideas available on Adobe Stock: https://adobe.ly/3DE4jJi

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
