### ISSUE TITLE
Icon request: user-cat

### ISSUE THREAD

**Issue by hopeiessdespair** [FortAwesome/Font-Awesome#18234]
**What can it be used for?**
This icon could be used for teams and selection screens, as well as credits and to differentiate members of groups.

**Example image**
![fas fa-user-cat](https://user-images.githubusercontent.com/89989086/131867643-ae4214c5-f50e-471a-935a-7455c2113620.png) (Not the best, but I think it's a good reference.)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
