### ISSUE TITLE
Hi the I am facing this problem

### ISSUE THREAD

**Issue by Pinto1232** [FortAwesome/Font-Awesome#18249]
pinto1232.github.io/:9 GET https://pinto1232.github.io/css/font-awesome.min.css net::ERR_ABORTED 404
pinto1232.github.io/:10 GET https://pinto1232.github.io/webfonts/fa-brands-400.svg net::ERR_ABORTED 404
pinto1232.github.io/:11 GET https://pinto1232.github.io/webfonts/fa-regular-400.svg net::ERR_ABORTED 404
pinto1232.github.io/:12 GET https://pinto1232.github.io/webfonts/fa-solid-900.svg net::ERR_ABORTED 404
pinto1232.github.io/:109 GET https://pinto1232.github.io/img/pic-4.png 404

My resources is not showing

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)

Please also notice that this tracker is dedicated to report bug. If you need support, please ask a question on Stack Overflow

From your use case, I suppose you want to host Font Awesome by yourself. Docs: https://fontawesome.com/v5.15/how-to-use/on-the-web/setup/hosting-font-awesome-yourself
