### ISSUE TITLE
v5.15 Pro license, React yarn add "Token string should not contain spaces"

### ISSUE THREAD

**Issue by dyspop** [FortAwesome/Font-Awesome#18264]
**Describe the bug**
_What happened?_ When I `yarn add @fortawesome/fontawesome-pro` I get 
```
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome%2ffontawesome-pro: Invalid token header. Token string should not contain spaces.".
info If you think this is a bug, please open a bug report with the information provided in "/usr/src/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

_How did you arrive here?_
1. Get valid Pro license
2. Google "React Font Awesome Pro"
3. Find and follow page https://fontawesome.com/v5.15/how-to-use/on-the-web/using-with/react
4. Identify prerequisite configuration is necessary and head to https://fontawesome.com/v5.15/how-to-use/on-the-web/setup/using-package-managers
5. Want to do per-project and with yarn and environment variables
6. Create .npmrc in root of project (same level as package.json) with 
```
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=${FONTAWESOME_NPM_AUTH_TOKEN}
```
7. Add FONTAWESOME_NPM_AUTH_TOKEN  to .env 
```
FONTAWESOME_NPM_AUTH_TOKEN=XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX npm install --save @fortawesome/fontawesome-pro
```
8. enter command `yarn add @fortawesome/fontawesome-pro`

Note that `yarn add @fortawesome/fontawesome-pro` works if I put the FONTAWESOME_NPM_AUTH_TOKEN directly in the .npmrc

**Version and implementation**
@fortawesome/fontawesome-pro@5.15.4

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, can't replicate.

It looks like that the system is fetching from the environment a wrong token with spaces

### Reduced test case

I've tried by creating a new folder with `.npmrc`

```
$ ls -a
.      ..     .npmrc
```

```
$ cat .npmrc 
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=${FONTAWESOME_NPM_AUTH_TOKEN}
```

```
$ npm init --yes
Wrote to package.json:

{
  "name": "fa18264",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "Geremia Taglialatela",
  "license": "ISC"
}
```

Trying without token:

```
$ yarn add @fortawesome/fontawesome-pro
yarn add v1.22.11
error An unexpected error occurred: "Failed to replace env in config: ${FONTAWESOME_NPM_AUTH_TOKEN}".
info If you think this is a bug, please open a bug report with the information provided in "yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

(good, that was expected)

And now with token
```
$ FONTAWESOME_NPM_AUTH_TOKEN=XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX yarn add @fortawesome/fontawesome-pro
yarn add v1.22.11
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ @fortawesome/fontawesome-pro@5.15.4
info All dependencies
└─ @fortawesome/fontawesome-pro@5.15.4
✨  Done in 3.40s.
```

### Versions

macOS: 11.5.2
bash: 5.1.8
node: v14.16.1
npm: 7.11.2
yarn: 1.22.11

> 7. Add FONTAWESOME_NPM_AUTH_TOKEN  to .env
> 
> ```
> FONTAWESOME_NPM_AUTH_TOKEN=XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX npm install --save @fortawesome/fontawe
> ```

I'm probably missing something here.

As far as I can understand, you should have a third-party library who takes care of loading into system environment the variables found in the local `.env` file. Please double check that the `.env` file is correct and the token is correctly found in the system environment. Loading the token through `.env` is an additional step and should be avoided in a reduced test case.

I also have a FA token defined as a global variable in and it works

PS: as a Pro Customer, you can get dedicated support at hello@fontawesome.com

Since this repo is intended to report bugs on the Free version and I can't directly help with Pro token-related requests, I'm closing here, but feel free to comment
