### ISSUE TITLE
Icon request: petri-dish

### ISSUE THREAD

**Issue by RaptorTrap** [FortAwesome/Font-Awesome#18270]
An icon which represents a petri dish.
It could be used in laboratory based settings. Would also fit in the Science Category, there are already flasks, vials, ...
Example icon:
https://www.svgrepo.com/svg/259291/petri-dish

**Comment by aethior** [comment]
*Related Unicode Emoji* #222
🧫 [U+1F9EB](https://emojipedia.org/emoji/%F0%9F%A7%AB/) Petri Dish

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
