### ISSUE TITLE
Icon request: folder-sync (reopen)

### ISSUE THREAD

**Issue by sanjanas23** [FortAwesome/Font-Awesome#18288]
![image](https://user-images.githubusercontent.com/91129035/134162712-3695ae71-6fcf-43f0-963c-f0f3f034ea50.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that **in a web application** it is possible to create an icon that fit the use case by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/585/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by aethior** [comment]
Alternative name `folder-rotate`.

@tagliala Also add `file (category)` label to this request?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
