### ISSUE TITLE
Icon request: uniform

### ISSUE THREAD

**Issue by haunted-path** [FortAwesome/Font-Awesome#18336]
**What can it be used for?**
Can be used by police, military, security guards, etc.  You can use it on a site that sells uniforms, you can use it on a site that police or service members use to denote areas specific to them, specific to uniforms, or to represent police or service men and women.

**Example image (optional)**
I don't have an example but I can think of two ways this could look.  One it could be a jacket with epaulets, a square on the chest above pockets, and a shirt and tie (the square would denote ribbons, name tags, etc).  The other way would be a person icon but wearing a police/officer type hat in the above jacket or one similar. 

You could further expand the utility by including one with and one without a police badge on one of the pockets.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> The other way would be a person icon but wearing a police/officer type hat in the above jacket or one similar.
> You could further expand the utility by including one with and one without a police badge on one of the pockets.

The above icons are part of FA6 Pro:
- https://fontawesome.com/v6.0/icons/user-police?s=solid
- https://fontawesome.com/v6.0/icons/user-police-tie?s=solid
- https://fontawesome.com/v6.0/icons/user-pilot?s=solid
- https://fontawesome.com/v6.0/icons/user-pilot-tie?s=solid

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
