### ISSUE TITLE
Icon request: black-friday

### ISSUE THREAD

**Issue by mariante** [FortAwesome/Font-Awesome#18345]
**What can it be used for?**
The SINGLE icon black-friday can be used on the November Black Friday for all years.

**Example image (optional)**
![example](https://i.imgur.com/3yOH6n5.jpg)

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and for this request

Your request is legit, and "black friday" is quite international. We generally avoid to include text in our icons also because they don't play well at small font size (16px)

**In a web application**, I suggest to use power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/apn7keq8/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
