### ISSUE TITLE
Icon request: intersection

### ISSUE THREAD

**Issue by RasitAyaz** [FortAwesome/Font-Awesome#18404]
**What can it be used for?**
This can be useful for describing joint/common features of two different things. Difference and union icons can also be added.

**Example image (optional)**
![intersection](https://user-images.githubusercontent.com/45076094/139737160-b9c10b19-7734-4a9f-8069-2c226d487bf3.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to consider this a subset of  #9631, please add a 👍🏼 reaction to that request

I've renamed `intersection` to `object-intersection`, because we already have an [intersection](https://fontawesome.com/v5.15/icons/intersection?style=solid) icon
