### ISSUE TITLE
Icon request: fa-traffic-ticket

### ISSUE THREAD

**Issue by heziw** [FortAwesome/Font-Awesome#18403]
**What can it be used for?**
Show traffic tickets.
This is a single icon.

**Example image (optional)**
Maybe something with a document and a car.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Any single color example suitable for small icon size (16px)?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
