### ISSUE TITLE
Preload of icons before showing in bootstrap modal

### ISSUE THREAD

**Issue by turik97** [FortAwesome/Font-Awesome#18414]
Hello, I have a few icons displayed in bootstrap modals but the problem is that when the modal is opened for the first time, the icons appear 'on user's eyes', is there a way to preload them so when the modal is shown for the first time the icons are already loaded there?  I use FA cdn

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

>  I use FA cdn

Can you please clarify how are you loading Font Awesome?

**Comment by turik97** [comment]
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> > I use FA cdn
> 
> Can you please clarify how are you loading Font Awesome?

<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />

**Comment by turik97** [comment]
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> > I use FA cdn
> 
> Can you please clarify how are you loading Font Awesome?

Via <link rel="stylesheet">

**Comment by tagliala** [comment]
Thanks, so your application is using the CSS/Webfont implementation and that there are no icons in the page outside the modal, or the icon in the modal is in a different style (`far` instead of `fas`)

Is that correct?

**Comment by tagliala** [comment]
Anyway... this is a generic question related to webfonts, because they are loaded by the browser on-demand.

You can use `preload` to preload the webfont file (in its woff2 format, so content may still flash on older browsers)

Demo: https://jsfiddle.net/tagliala/e92Lnvkr/1/
Demo without Font Awesome: https://jsfiddle.net/tagliala/e92Lnvkr/3/

![Uploading image.png…]()

(set `Disable cache` and `Slow 3G` throttling in network panel too see the issues)

Docs: https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload

Hope it helps

Closing here
