### ISSUE TITLE
When i use font awesome icons in dropdown menu , it is not working 

### ISSUE THREAD

**Issue by SkhollaSocial** [FortAwesome/Font-Awesome#18460]
![font-awesome-icon-issue-1](https://user-images.githubusercontent.com/93820114/142722859-40097d67-7c0d-4c19-93ab-e84c9c278b97.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I've edited the opening post because it looks like advertising rather than a bug report

> When i use font awesome icons in dropdown menu , it is not working

Using Font Awesome inside a standard HTML dropdown box is not a supported use case, also because of some OS limitations

Ref: #996

Solution: https://github.com/FortAwesome/Font-Awesome/issues/996#issuecomment-322332662

Closing here, but If I did not get this request, feel free to open a new issue by filling out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)
