### ISSUE TITLE
Icon request: work-at-home

### ISSUE THREAD

**Issue by xue35** [FortAwesome/Font-Awesome#18469]
**What can it be used for?**
Given COVID-19, more and more companies are enabling employees to hybrid-mode working both work in office and work at home. This icon can be use to indicate he/she work at home.

**Example image (optional)**
[Example 1.](https://image.freepik.com/free-vector/working-home-icon-company-allows-employees-work-from-home-coronavirus-covid-19-illustration-concept_37225-449.jpg)
[Example 2](https://www.pngitem.com/pimgs/m/518-5184824_png-freeuse-stock-vector-work-working-icon-work.png)

**Icon request checklist**
- [] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

In version 5.14.0 we have introduced [laptop-house](https://fontawesome.com/v5.15/icons/laptop-house?style=solid) for this use case

Does this icon fit your use case?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/house-laptop?f=classic&s=solid)
