### ISSUE TITLE
Icon Request: Antibody

### ISSUE THREAD

**Issue by machineage** [FortAwesome/Font-Awesome#18495]
**What can it be used for?**
antibody treatments and conditioning is used in various medical treatments for diseases such as cancer and COVID. It's generally presented as a dual lined Y shape (see image purple and teal objects in image going for the flowery looking receptors). Sometimes they're represented with more structure (see second and third images).

**Example image (optional)**
![image](https://user-images.githubusercontent.com/15336132/145260237-966680f0-6f91-483a-a42d-27c7c9e269d8.png)
![image](https://user-images.githubusercontent.com/15336132/145261071-c5624ee0-c99f-48c1-884e-5e08ab756788.png)
![image](https://user-images.githubusercontent.com/15336132/145260862-b4e24c6c-ebed-4dbd-bf2a-8f462084879f.png)

**Icon request checklist**
- [Single] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
