### ISSUE TITLE
Icon request: replace

### ISSUE THREAD

**Issue by rivets** [FortAwesome/Font-Awesome#18494]
**What can it be used for?**
For example, you have an image (or file) associated with something and you would like to exchange it for another one.  It indicates uploading something new that replaces whatever is there.  N.B this is not the same as the previously requested search and replace idea.

**Icon request checklist**
- [x] This is a single icon
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think that there are some icons that can fit this use case: https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=exchange&m=free

Otherwise, do you have any example?

**Comment by rivets** [comment]
I don't have an example and there isn't really one in the set that I feel captures the act of replacing. There are things like circular arrows but that doesn't say replace to me. Currently I use the fireplace icon - since it has the word replace in it! That doesn't say replace either (more like burn it up) but it's a convenient place holder. Something that indicates overwriting is what is needed but I don't have a good image of what that would be like at the moment.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
