### ISSUE TITLE
Not working icon

### ISSUE THREAD

**Issue by eKeja** [FortAwesome/Font-Awesome#18506]
Seems not to be working on my project:
https://fontawesome.com/v5.15/icons/head-side-mask?style=solid

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)

Without details, I can only think that this issue is related to an outdated version of Font Awesome, please make sure that your application is using FA >= 5.14 to use this icon

**Comment by eKeja** [comment]
This is very poorly of FontAwsome then. In stead of offering a page with all the needed questions to report a bug, i get to a Github-page looking like a forum.
Also, when i can choose from the free icons library at fontawesomes website, it just simply should work. I really dont care about the different versions!

**Comment by tagliala** [comment]
Hi,

> This is very poorly of FontAwsome then. In stead of offering a page with all the needed questions to report a bug, i get to a Github-page looking like a forum.

You should be able to see a template with all the questions and information we need when opening a new issue, like this:

![image](https://user-images.githubusercontent.com/556268/145858203-c1081d50-441f-4a3a-a50f-26e1572b92a1.png)

I've provided also a link to the bug report template in my previous answer

Could you please share the process that led you to a new empty template?

> Also, when i can choose from the free icons library at fontawesomes website, it just simply should work. I really dont care about the different versions!

There are a lot of different ways of using Font Awesome to cover as many use cases as possible.

In our [start page](https://fontawesome.com/start), we suggest to use Kits because it's the fastest and easy way of using Font Awesome.

If you want an easier way of using icons regardless of the version, you can use Kits and select "Latest 5.x" version from the dropdown list, so Font Awesome will **automatically upgrade** and cover your use case, so you don't need to check the version number before using a new icon

![image](https://user-images.githubusercontent.com/556268/145858973-9127362f-a24a-4f19-888f-db19100e486c.png)

Hope this helps

**Comment by eKeja** [comment]
Hi! I am going to try this later. Thanks.

Kind regards,
Keja Baas

Op ma 13 dec. 2021 18:23 schreef Geremia Taglialatela <
***@***.***>:
