### ISSUE TITLE
Icon request: forest

### ISSUE THREAD

**Issue by ajalexsmith** [FortAwesome/Font-Awesome#18518]
**What can it be used for?**
With the environment being a hot topic, a forest would be a great indicator on sites for planting tree's

**Example image (optional)**
https://thumbs.dreamstime.com/z/forest-vector-illustration-trees-vector-illustration-forest-icons-set-forest-icon-outline-style-forest-icon-vector-145515982.jpg

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We have a Pro icon [trees](https://fontawesome.com/v5.15/icons/trees?style=solid)

Does it fit this use case?

**Comment by ajalexsmith** [comment]
Hi Tagliala,

I was personally thinking a few more than 2,
In our use case, we're showing the single tree icon to plant 1 tree, the trees icon for 2-9 then ideally a forest for 10+

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
