### ISSUE TITLE
Icon request: Media player play back speeds

### ISSUE THREAD

**Issue by jarendt21** [FortAwesome/Font-Awesome#18543]
**What can it be used for?**
Media player playback speed for on demand media. 

**Example image (optional)**
Example, give users the ability to change the playback speed next to the media player time.
**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
<img width="1047" alt="playback-example" src="https://user-images.githubusercontent.com/50432895/147681604-82b2909a-bb43-42f0-a58b-7939ee664727.png">

- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make
[Helix DS (IN PROGRESS) (4).zip](https://github.com/FortAwesome/Font-Awesome/files/7789704/Helix.DS.IN.PROGRESS.4.zip)
 an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
