### ISSUE TITLE
Icon request: file-sds

### ISSUE THREAD

**Issue by dfgd** [FortAwesome/Font-Awesome#18541]
**What can it be used for?**
This icon can be used to represent sds files, safety data sheet

**Example image (optional)**
![Untitled](https://user-images.githubusercontent.com/3756986/147501423-b89ce20f-03a7-4dbd-81e7-896f8d758121.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by SadiinsoSnowfall** [comment]
you could use text layering ontop of the `far/fa-file` icon to get the same result :
```html
<span class="fa-layers fa-fw">
    <i class="far fa-file"></i>
    <span class="fa-layers-text fa-inverse" data-fa-transform="shrink-12 down-1" style="font-weight:800; color: black; font-family: 'Segoe UI'">SDS</span>
</span>
  ```
![image](https://user-images.githubusercontent.com/32017313/148552391-6c62c840-c41b-4fa9-b796-a9058469f7f6.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
