### ISSUE TITLE
Icon Request: fa-sql

### ISSUE THREAD

**Issue by shaounak** [FortAwesome/Font-Awesome#18557]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

If this is a generic request for sql, it may be a duplicate of #9555

If it is a request for MySql, then it could be a duplicate of #6052
