### ISSUE TITLE
FA-Bolt icon served via kit isn't displaying correctly

### ISSUE THREAD

**Issue by benjeater** [FortAwesome/Font-Awesome#18588]
**Describe the bug**
FA-Bolt icon does not display correclty when loaded via kit

**To Reproduce**

1. Add kit to header of index.html
2. Add fa-bolt icon as per documentation (`<i class='far fa-bolt'></i>`)
3. See that the icon isn't displayed correctly

**Expected behavior**
The icon is displayed correctly as per the FontAwesome site (https://fontawesome.com/v5.15/icons/bolt?style=regular)

**Screenshots**
Expected icon:
https://ibb.co/GRTsmfd

Actual icon:
https://ibb.co/56YS6dR

**Version and implementation**
Version: Latest 6.x
Browser and version: Google Chrome Version 97.0.4692.71 (Official Build) (x86_64)

- [ ] SVG with JS
- [X] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and for reporting this.

As far as I can see, this issue is related to a Pro kit using FA 6 beta 3 ("Version: Latest 6.x"), even if the documentation is referring to FA5

In FA6, `bolt` is https://fontawesome.com/v6.0/icons/bolt?s=regular, while the old bolt has been renamed to `bolt-lightning` https://fontawesome.com/v6.0/icons/bolt-lightning?s=regular

If you are using FA6 without compatibility shims, you may want to change `bolt` to `bolt-lightning`

I think that there may be a bug: FA6's `bolt-lightning` should be added to the free set as a replacement of FA5's `bolt` and shims fixed accordingly, while FA6's `bolt` should be moved to the Pro set

Let's ask @robmadole for some feedback

**Comment by sensibleworld** [comment]
Jumping in to say that the standard `bolt` icon did indeed get a redesign in version 6. We also kept the old design and renamed it to `bolt-lightning` to more accurately reflect the design metaphor.

In our official v6 release (coming soon), both `bolt` and `bolt-lightning` will be part of FA Free.
