### ISSUE TITLE
Icon request: Electronic Health Record

### ISSUE THREAD

**Issue by mheidebrecht** [FortAwesome/Font-Awesome#18595]
**What can it be used for?**
Allow an individual electronic health record to be identified within an EHR software application.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

EHR has already been requested at #14403, but since this request is for an abstract object, please take a look at the comments there

If you have something specific in mind, feel free to open a new request by filling out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md) and remember to provide an example, so we can find a better title

Closing here, but feel free to comment
