### ISSUE TITLE
Minor site content issue

### ISSUE THREAD

**Issue by Krogoth132** [FortAwesome/Font-Awesome#18592]
Check code for this symbol, 
https://fontawesome.com/v5.15/icons/circle?style=regular

code "f111" also used for 

https://fontawesome.com/v5.15/icons/circle?style=solid

Looks like "regular circle" should have code "f10c"

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The described behavior is expected. In FA5, icons share the same unicode point among all the styles, because we use `font-weight` property to change the style

> Looks like "regular circle" should have code "f10c"

Yes, that was expected in FA4. If you ran into this issue while upgrading from v4 to v5, please take a look at our documentation at https://fontawesome.com/v5.15/how-to-use/on-the-web/setup/upgrading-from-version-4

Closing here, but feel free to comment
