### ISSUE TITLE
Icon request: price

### ISSUE THREAD

**Issue by Evroremontnik** [FortAwesome/Font-Awesome#18604]
Icon request: price

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Price should be covered by https://fontawesome.com/v5.15/icons/tag

If you have something different in mind, feel free to open a new request by filling out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md). Please remember to provide an example, since "price" is quite an abstract concept
