### ISSUE TITLE
css não carrega...

### ISSUE THREAD

**Issue by antoniojoaquimm** [FortAwesome/Font-Awesome#18607]
Então o codigo css da pagina não esta carregando.
não consigo acessar a pagina de maneiro alguma pois esta dando este erro sempre

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I can understand what it is written but there are not enough information to debug. Is this issue related to fontawesome.com? Is it related to a web app you are developing?

From google translate:

> So the css code of the page is not loading.
I can't access the page at all because it's giving this error always

Please fill our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md) and provide all the information we ask to help you debugging this issue

Closing here
