### ISSUE TITLE
Uploading an unfilled stroke icon to my kit incorrectly fills the icon

### ISSUE THREAD

**Issue by hudri** [FortAwesome/Font-Awesome#18606]
**Describe the bug**
I wanted to add unfilled, outline/stroke-width icons from lucide.dev to my kit. Uploading outline icons with ` fill="none" stroke="currentColor" stroke-width="2"` turns them into filles icons.

**To Reproduce**
Example icon: https://lucide.dev/icon/airplay

Uploaded source:
`<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
  <path d="M5 17H4a2 2 0 01-2-2V5a2 2 0 012-2h16a2 2 0 012 2v10a2 2 0 01-2 2h-1"></path>
  <polygon points="12 15 17 21 7 21 12 15"></polygon>
</svg>`

Generated SVG after uploading: 
`<svg aria-hidden="true" focusable="false" data-prefix="fak" data-icon="airplay" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="uploaded-icon-preview svg-inline--fa fa-airplay" style="width: 1em;"><path fill="currentColor" d="M106.667 362.667H85.333A42.667 42.667 0 0142.667 320V106.667A42.667 42.667 0 0185.333 64h341.334a42.667 42.667 0 0142.666 42.667V320a42.667 42.667 0 01-42.666 42.667h-21.334M256 320l106.667 128H149.333L256 320z" class=""></path></svg>`

**Expected behavior**
Unfilled stroke-width / stroke icons must stay unfilled after uploading

**Comment by tagliala** [comment]
Hi,

thanks for reporting this

As far as I know, custom uploaded svgs must follow certain guidelines.

Here there are a couple a links that could help:

- https://fontawesome.com/v5.15/how-to-use/on-the-web/using-kits/prepping-icons-for-upload
- https://fontawesome.com/v5.15/how-to-use/on-the-web/using-kits/troubleshooting-uploads

Since I'm not into icon design, I can ask @sensibleworld for some feedback here

**Comment by sensibleworld** [comment]
Yeah, unfortunately, our icon upload does not support stroked icons. This is primarily due to how typefaces need to be built. In order to upload your icon, you'll need to first outline your strokes.

You'll want the SVG to look something like this:

`<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M3.29289 4.29289C3.48043 4.10536 3.73478 4 4 4H20C20.2652 4 20.5196 4.10536 20.7071 4.29289C20.8946 4.48043 21 4.73478 21 5V15C21 15.2652 20.8946 15.5196 20.7071 15.7071C20.5196 15.8946 20.2652 16 20 16H19C18.4477 16 18 16.4477 18 17C18 17.5523 18.4477 18 19 18H20C20.7957 18 21.5587 17.6839 22.1213 17.1213C22.6839 16.5587 23 15.7957 23 15V5C23 4.20435 22.6839 3.44129 22.1213 2.87868C21.5587 2.31607 20.7957 2 20 2H4C3.20435 2 2.44129 2.31607 1.87868 2.87868C1.31607 3.44129 1 4.20435 1 5V15C1 15.7956 1.31607 16.5587 1.87868 17.1213C2.44129 17.6839 3.20435 18 4 18H5C5.55228 18 6 17.5523 6 17C6 16.4477 5.55228 16 5 16H4C3.73478 16 3.48043 15.8946 3.29289 15.7071C3.10536 15.5196 3 15.2652 3 15V5C3 4.73478 3.10536 4.48043 3.29289 4.29289Z" fill="black"/>
<path d="M12.7682 14.3598C12.5782 14.1318 12.2968 14 12 14C11.7032 14 11.4218 14.1318 11.2318 14.3598L6.23179 20.3598C5.98339 20.6579 5.92984 21.0728 6.09442 21.4242C6.259 21.7755 6.61199 22 7.00001 22H17C17.388 22 17.741 21.7755 17.9056 21.4242C18.0702 21.0728 18.0166 20.6579 17.7682 20.3598L12.7682 14.3598ZM12 16.562L14.865 20H9.13505L12 16.562Z" fill="black"/>
</svg>`

I'll also note that we have a similar icon already in version 6: https://fontawesome.com/v6.0/icons/airplay?s=regular
