### ISSUE TITLE
Blank Squares - Occasional problem in Safari (iOS)

### ISSUE THREAD

**Issue by User5842** [FortAwesome/Font-Awesome#18622]
I haven't checked on my site for about three days, and when I went to check on it today, I noticed that my FA Icons were instead showing up as blank squares.

I have asked some of my friends (on different mobile browsers) to check my site, and they have confirmed that they _are_ able to see the icons.

I just wanted to bring this up if it is possibly an issue with FA or perhaps just a Safari regression. I looked through #7770, but there did not seem to be any sound advice on the consumer end.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please use #7770

As per
- https://github.com/FortAwesome/Font-Awesome/issues/7770#issuecomment-611442336
- https://github.com/FortAwesome/Font-Awesome/issues/7770#issuecomment-504114161

That issue looks like it does not depend by Font Awesome.

Since it affects the CSS version because of some unexpected webfont unload, you can switch to the SVG implementation

Closing here, but feel free to report your experience at #7770. Please also add as many details as you can:
- iOS and safari version
- Device
- FA version, implementation (CSS / SVG)
- FA loading approach (KiT, CDN, third-party CDN, self-hosted)

**Comment by User5842** [comment]
Thanks for the prompt response! I will try your suggested advice.
