### ISSUE TITLE
Icon Request: fa-

### ISSUE THREAD

**Issue by afloat42** [FortAwesome/Font-Awesome#18624]
Hi it would be wonderful if you create sports icon like gym, football, basketball

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We have a Sports category with a lot of icons, including balls to represent football and basketball as well as a dumbbell to represent gym

https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=sport&c=sports

Also, there are requests for more sports, in example #10913

I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

Feel free to open new, individual requests for each sport you need, having care of [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here
