### ISSUE TITLE
wrong icon

### ISSUE THREAD

**Issue by zafernci** [FortAwesome/Font-Awesome#18649]
I want the use that icon(https://fontawesome.com/v5.15/icons/slack-hash?style=brands) but when i put that code into my page(<i class="fab fa-slack-hash"></i>) coming a different icon

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)
