### ISSUE TITLE
Icon request: gear-arrow-right

### ISSUE THREAD

**Issue by Matthias-DS** [FortAwesome/Font-Awesome#18682]
It can be used for importing configuration files, icon for integrations, ...

Something like: 
![image](https://user-images.githubusercontent.com/17382864/153569058-beac68f2-853e-4c4c-bb2e-afd0230b40a8.png)

**Icon request checklist**
- [Yes ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [Yes] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [Yes] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [Yes] I have included at least one example image if it could be helpful (optional)
- [Yes] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by gdvalderrama** [comment]
Maybe you could stack the cog icon (regular) and the arrow right icon (solid)?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
