### ISSUE TITLE
Icon request: blur-linear

### ISSUE THREAD

**Issue by prak222** [FortAwesome/Font-Awesome#18689]
Hi 
Can you please help me to add https://icon-icons.com/icon/blur-linear/138860 icon to font-awesome 

Thank you

**Comment by Tausif4171** [comment]
> Hi Can you please help me to add https://icon-icons.com/icon/blur-linear/138860 icon to font-awesome
> 
> Thank you

> Hello prak222,
>Please read this article it will help you => ( https://fontawesome.com/v5/docs/web/use-kits/upload-icons )

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
