### ISSUE TITLE
payment gateway of bangladesh

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#18687]
we need all payment gateway of Bangladesh icons. such as bKash, Nagad, Roket, Upay, SureCash, Ok Bangladesh, Trust Axiata Pay, Bank Asia etc

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> we need all payment gateway of Bangladesh icons. such as bKash, Nagad, Roket, Upay, SureCash, Ok Bangladesh, Trust Axiata Pay, Bank Asia etc

Please make an individual request for each one of those brands, by filling in our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

Please also make [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones because maybe a brand has been already requested

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here
