### ISSUE TITLE
Icon missing: fa-solid fa-t

### ISSUE THREAD

**Issue by fkm** [FortAwesome/Font-Awesome#18697]
The way I understand your [website](https://fontawesome.com/icons/t?s=solid) the set of free solid icons should include the "T" icon.

But looking at the [package directory](https://github.com/FortAwesome/Font-Awesome/tree/6.x/js-packages/%40fortawesome/free-solid-svg-icons) here on GitHub I cannot see a `faT.js`.

Other alphabet icons seem to be missing too.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think it is because there are too many files in that folder

![image](https://user-images.githubusercontent.com/556268/153912586-02c233a2-402b-45c7-9d2a-4b5cce3ed876.png)

You can use the search feature

![image](https://user-images.githubusercontent.com/556268/153912808-a6f45fe0-5890-47ea-b3cb-b1cb77c6ebd3.png)

<img width="696" alt="image" src="https://user-images.githubusercontent.com/556268/153912852-041a814f-7984-4c6f-9170-b9c024d439a2.png">

Hope it helps

**Comment by fkm** [comment]
*Thank you very much!*

That helped a lot! :smiley:
