### ISSUE TITLE
Icon request: blood-bag

### ISSUE THREAD

**Issue by shehi** [FortAwesome/Font-Awesome#18700]
An icon depicting Blood would be very useful, especially for Blood-Donation and related topics. 

Additionally, the concept of Bleeding is also very useful in gaming, specifically RPG world.

Thank you for great work!

Happy Customer

**Comment by tagliala** [comment]
Hi!

Does [fa-droplet](https://fontawesome.com/icons/droplet?s=solid) (maybe in `#660000` or `#aa0000`) fit the use case?

**Comment by shehi** [comment]
Might work in certain contexts. For some others, something like a "dagger/sword with droplets on it" and  "a bloodbag with O+ written on it" would fit better. Please close this if creating such icons isn't feasible at the moment. And again, thank you for great library!

**Comment by tagliala** [comment]
> dagger/sword with droplets on it" and "a bloodbag with O+ written on it" would fit better. 

Got it. This is why we ask for concrete objects. Representing blood may be difficult, a blood bag instead is way more clear 

I've edited the first post and renamed this request as "blood bag"

> Please close this if creating such icons isn't feasible at the moment. 

You may be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

> And again, thank you for great library!

Welcome

**Comment by shehi** [comment]
So hopes for a dagger with dripping blood are dead now. Hahaha, kidding.
Thank you.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
