### ISSUE TITLE
Installing Free version with react, getting a license error (should default to free)

### ISSUE THREAD

**Issue by dk8996** [FortAwesome/Font-Awesome#18711]
I followed the documentation on this site (https://fontawesome.com/v6/docs/web/use-with/react/). I'm getting the following error after 
```
fortawesome/fontawesome-svg-core/import.macro: config license must be either 'free' or 'pro' Learn more: https://www.npmjs.com/package/@fortawesome/fontawesome-svg-core
```
As per documentation,

I add the following package.json (npm i)
```
    "@fortawesome/fontawesome-svg-core": "^1.3.0",
    "@fortawesome/free-solid-svg-icons": "^6.0.0",
    "@fortawesome/free-regular-svg-icons": "^6.0.0",
    "@fortawesome/react-fontawesome": "latest",

```

Imports
```
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { solid, regular, brands } from '@fortawesome/fontawesome-svg-core/import.macro' // <-- import styles to be used
```

**Comment by dk8996** [comment]
I fixed this by adding the following to `package.json`. This should be part of the documentation.
```
  "babelMacros" : {
    "fontawesome-svg-core" : {
      "license": "free"
    }
  }
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and apologies for the late reply.

> This should be part of the documentation.

It is actually part of the documentation: https://fontawesome.com/v6/docs/web/use-with/react/add-icons

![image](https://user-images.githubusercontent.com/556268/154558101-f8f01623-f041-434f-82a3-fb3a28236369.png)

It is not part of the setup because there are different use cases and you may not need `babelMacros`

Closing here, but feel free to comment

**Comment by ghost** [comment]
@dk8996 You save me man! No need for babel-config.js and babel-plugin-macros.js when using React js and Vite. Thank you!!!
