### ISSUE TITLE
Icon request: comments-question-xmark

### ISSUE THREAD

**Issue by OlsonDev** [FortAwesome/Font-Awesome#18719]
Looking for the `comments-question-*` collection to be extended with one that has a "response" to the question as an `xmark`.

Initial request was [here](https://github.com/FortAwesome/Font-Awesome/issues/15985).

Ref: https://fontawesome.com/icons/comments-question-check?s=solid

Thanks!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
