### ISSUE TITLE
Icon request: programming languages

### ISSUE THREAD

**Issue by thevedicdeveloper** [FortAwesome/Font-Awesome#18721]
Hi Team, Can we get icons of the programming languages and different frameworks, below are few examples

- [ ] C++
- [ ] C
- [ ] Java
- [ ] JavaScript
- [ ] HTML
- [ ] CSS
- [ ] Flutter
- [ ] React
- [ ] React Native
- [ ] Firebase
- [ ] Google Cloud
- [ ] Azure
- [ ] AWS
- [ ] and other similar icons

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

This repository does not allow requests for icon sets, because they are hard to manage.

Also, some icons like HTML and CSS are already here, and others like Java have already a request

Feel free to open individual requests for any language you need, but please check before that
1. The language is not here yet https://fontawesome.com/search?s=solid%2Cbrands
2. There aren't requests for that language: https://github.com/FortAwesome/Font-Awesome/search?q=java&type=issues

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
