### ISSUE TITLE
Icon Request: tachometers are circular in FA6

### ISSUE THREAD

**Issue by fishshadower** [FortAwesome/Font-Awesome#18730]
like this：
![gauge](https://user-images.githubusercontent.com/47311591/154884946-730bdab6-209a-455c-99a5-96587d4dfda3.jpg)

Now there is no semicircular logo in the chart

**Comment by jzsenthy** [comment]
In v6 can we have both the circular "gauge" icon (that's currently in v6), as well as adding the semicircular "tachometer" icon from v5? We are using both icons for different purposes and it seems strange that one is missing from v6.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
