### ISSUE TITLE
Icon request: memo needs a memo-circle-x

### ISSUE THREAD

**Issue by saeho** [FortAwesome/Font-Awesome#18752]
**Is your feature request related to a problem? Please describe.**
"memo" icons need a "memo-circle-x" (memo with X).
"memo" has a "memo-circle-check" counterpart. But what's the point when there's no "memo-circle-x"? I can't use "memo-circle-check" until I have the opposite equal counterpart (the x).

**Describe the solution you'd like**
I'd like a "memo-circle-x"

**Describe alternatives you've considered**
Only other option now is to use file-xmark and file-check. However, memo is nice. And I'd like to use it.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
