### ISSUE TITLE
Icon request: text-raised / text-engraved

### ISSUE THREAD

**Issue by Jony01** [FortAwesome/Font-Awesome#18772]
![unnamed_](https://user-images.githubusercontent.com/15888762/156756707-3af3542b-4003-4e95-b22b-fb43ce85d702.png)

Icon for represents Engraved and Raised text

**Comment by Jony01** [comment]
![image](https://user-images.githubusercontent.com/15888762/156768497-43b4357d-4768-4d7b-9c98-cdd784bfb400.png)

**Comment by Jony01** [comment]
![image](https://user-images.githubusercontent.com/15888762/156772156-ca3f3020-fbf1-47f1-a681-ffc11ae42d6e.png)

**Comment by tagliala** [comment]
@Jony01 thanks

I think they are a good starting point. Of course they need to be single color (not greyscale), but the second example gives an idea of how this can be achieved

**Comment by Jony01** [comment]
![image](https://user-images.githubusercontent.com/15888762/156774072-4fa01f2b-8640-45d0-a32d-d6a26fb86336.png)

**Comment by Jony01** [comment]
Only inspiration which come to my mind

**Comment by Jony01** [comment]
16x16 Pixels icon:
![image](https://user-images.githubusercontent.com/15888762/166635238-89dcd8e7-d011-45f9-9658-699dbfa5b995.png)
SVG files with icons
![engraved](https://user-images.githubusercontent.com/15888762/166635868-bcf073cf-45ff-463c-bda8-1eea5b8315bb.svg)
![raised](https://user-images.githubusercontent.com/15888762/166635871-02f2606f-804c-4c99-bce2-b699e112523e.svg)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
