### ISSUE TITLE
Icon request: old hand-rock icon as hand-grab

### ISSUE THREAD

**Issue by SolarCola** [FortAwesome/Font-Awesome#18786]
In Font Awesome 5, the 'hand-fist' icon was also very useful as a hand grabbing something. The new hand-back-fist that replaced hand-rock looks great, but doesn't look like a hand grabbing something. Could the old hand-rock be brought back as hand-grab, to help distinguish between a fist, and a hand grabbing something?

Use cases could include cursors or use-cues to help indicate a object is draggable.

**Comment by tagliala** [comment]
Hi!

Thanks for this feedback

Let's ask @sensibleworld

**Comment by SolarCola** [comment]
@tagliala Sorry to bother you again, but what would be the typical response time from sensibleworld? Because I'm looking through old icon request and typically they responded within a few days. Could it be that sensibleworld missed this notification? I am not a regular user of Github so I don't really know how notifications work...

**Comment by sensibleworld** [comment]
@SolarCola Sorry for the radio silence! I think this is a valid request, but it may take a little bit for me to take action on it, as we're focused on some bug fixes and other updates at the moment. In the meantime, if you're using a Font Awesome Kit, you can always download the old v5 icon and upload it as a custom icon. Thanks!

**Comment by SolarCola** [comment]
@sensibleworld  No problem, very understandable! Thank you for suggesting that solution, I think that can work for us in the meantime.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
