### ISSUE TITLE
New Icon: zoom-cover or zoom-contain (scale video letterboxing)

### ISSUE THREAD

**Issue by brendon** [FortAwesome/Font-Awesome#18798]
I don't think there's anything as succinct as the way Apple does it in their video player interface:

![IMG_9541](https://user-images.githubusercontent.com/81871/157530106-94fcb290-82ea-4930-b432-f0078bf14615.jpeg)
![IMG_9542](https://user-images.githubusercontent.com/81871/157530124-1bc72837-cb1a-4fbe-989a-a7c4e22ecd17.jpeg)

It just basically means either show the whole video with letterboxing as required, or zoom the video in so that it covers the screen or window.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Do we have better names for this request?

`cover` and `contain` are a little bit abstract

**Comment by brendon** [comment]
Haha! I’m from CSS land man. That’s what it’s called there.

I honestly can’t think of a better way to describe it. It’s a kind of zoom but we already have zoom icons.

**Comment by brendon** [comment]
Perhaps scale-cover and scale-contain?

**Comment by tagliala** [comment]
Hi, I've also tried with iOS voiceover to have a better name and it labels that button as "zoom"

I've added some keywords in the title

**Comment by brendon** [comment]
Thanks @tagliala :) Much appreciated :D

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Comment by brendon** [comment]
This doesn't feel like a niche icon to me. It has a clear purpose, to show people they can zoom and crop something to the viewport, or to view that something in the full with padding on each side of the thing that is narrower than the viewport.
