### ISSUE TITLE
Icon Request: fa-

### ISSUE THREAD

**Issue by NC-Teacher** [FortAwesome/Font-Awesome#18809]
![logo_site](https://user-images.githubusercontent.com/91735599/158135550-8d1f9af5-e754-4df4-a4ff-92590bdf78fc.jpg) FIVE CONTINENTS TOUR

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

Please provide more details about this icon, as well as a single color example that suits at small icon size (16px)
