### ISSUE TITLE
Why is fa-xmark not square dimensions?

### ISSUE THREAD

**Issue by millansingh** [FortAwesome/Font-Awesome#18802]
Hi there.

I am working on a project, and I am noticing that my fa-xmark icon is not being properly sized. The element it is in (a button) has a font-size of 14px, and so I would expect the xmark icon to be 14x14 size, but it is 8.75x14, and it looks like the viewbox for the svg is set to "0 0 320 512" which is causing the incorrect sizing.

It seems like this is on purpose, but I can't understand why. This is a square-shaped icon but has unnecessary space above and below the icon in order to make it a non-square shape. If this is an improper question for GitHub, I apologize, but it felt like the most appropriate place.

Edit: FWIW, the icon in Figma (using the Font Awesome figma component) renders it out at 14x14, so there's clearly a mismatch between the repo svg and that.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Icons in Font Awesome have the same height but different width by design choice

Examples:
- full-height https://fontawesome.com/icons/pipe?s=solid - [SVG](https://github.com/FortAwesome/Font-Awesome/blob/6.x/svgs/solid/pipe.svg)
- https://fontawesome.com/icons/exclamation?s=solid (`xmark`'s case) - [SVG](https://github.com/FortAwesome/Font-Awesome/blob/6.x/svgs/solid/exclamation.svg)
- https://fontawesome.com/icons/square?s=solid - [SVG](https://github.com/FortAwesome/Font-Awesome/blob/6.x/svgs/solid/square.svg)
- full-width https://fontawesome.com/icons/gamepad?s=solid - [SVG](https://github.com/FortAwesome/Font-Awesome/blob/6.x/svgs/solid/gamepad.svg)
- https://fontawesome.com/icons/minus?s=solid - [SVG](https://github.com/FortAwesome/Font-Awesome/blob/6.x/svgs/solid/minus.svg)

The extra vertical spacing is needed to keep icons vertically centered without additional rules and for the webfont implementation I guess

> Edit: FWIW, the icon in Figma (using the Font Awesome figma component) renders it out at 14x14, so there's clearly a mismatch between the repo svg and that.

Let's ask @sensibleworld, I may be wrong

Docs: https://fontawesome.com/docs/web/add-icons/upload-icons/icon-design

**Comment by millansingh** [comment]
@tagliala I understand that consistency and why it's necessary. What I am getting at is that I don't understand why the xmark icon specifically is the same bounding box as the exclamation mark instead of square, considering the icon itself is square. This just seems completely non-sensical.

**Comment by tagliala** [comment]
> What I am getting at is that I don't understand why the xmark icon specifically is the same bounding box as the exclamation mark

Is this related to Figma specifically?

I'm asking because SVG `viewBox`es are different

- exclamation (128x512) https://github.com/FortAwesome/Font-Awesome/blob/6.x/svgs/solid/exclamation.svg?short_path=a020474
- xmark (320x512) https://github.com/FortAwesome/Font-Awesome/blob/6.x/svgs/solid/xmark.svg?short_path=f979566

**Comment by millansingh** [comment]
@tagliala sorry about the exclamation. I thought you were saying it had the same viewBox as the xmark. I am not talking about Figma specifically, though it is strange that the Figma component is square when the actual repo svg isn't. What I am getting at is that it makes no sense that the repo xmark svg doesn't have a square viewbox given that it's a square-shaped icon. There's no reason to use a non-square viewbox cause the icon itself is square.

**Comment by tagliala** [comment]
Thanks for the clarification

I'm just trying to provide the information I know. Let's wait for Jory's feedback

> though it is strange that the Figma component is square when the actual repo svg isn't.

I do not use Sigma, but the Font Awesome plugin adds some stuff. Maybe https://github.com/FortAwesome/Font-Awesome/issues/18545#issuecomment-1005703293 clarifies

> What I am getting at is that it makes no sense that the repo xmark svg doesn't have a square viewbox given that it's a square-shaped icon.

`square` does not have a square viewbox either, it is 448x512: https://github.com/FortAwesome/Font-Awesome/blob/6.x/svgs/solid/square.svg?short_path=245c837

**Comment by sensibleworld** [comment]
Hey there. Sorry for the radio silence. I explain it a bit more here in [this particular comment.](https://github.com/FortAwesome/Font-Awesome/issues/18698#issuecomment-1040414786). But the TLDR is that the viewbox widths of our icons vary (the heights are all the same) because our icons started life as a typeface. 

It's not ideal, I know, and this question is coming up more and more recently, so finding a solution that is both backwards compatible and works as expected for newer folks is definitely something I'd like to figure out.

In the meantime, there is a fixed-width (`fa-fw`) class you can add in web implementations to make all of the icon widths consistent. 

And, fwiw, we made an update to the Figma component recently so that the default bounding box matches our other versions, but there are now other options, as well.

<img width="463" alt="CleanShot 2022-03-13 at 08 17 21@2x" src="https://user-images.githubusercontent.com/529604/158059068-ef560664-e9e9-4530-b608-eb0974fe0364.png">

**Comment by millansingh** [comment]
@sensibleworld Thanks for the detailed feedback. Unfortunately the fa-fw fix isn't going to work for me, because the core issue is the actual empty space above and below the icon (since it makes the xmark look too small compared to the text it's next to without increasing the scale of the icon which then messes with the padding of the outer element).

I was able to substitute a different icon for this specific use case which doesn't have the space above and below, so this isn't a pressing concern right this minute thankfully. That said, I still don't really get why this particular icon was designed at 10x16 when it seems clearly to be a better fit for 16x16. But also I get that at this point, it doesn't really matter given that many probably rely on it being the size it is right now. I don't know what the solution here is...messing with the viewbox doesn't really solve it either. It almost feels like it'd have to be a separate icon all-together.

**Comment by sensibleworld** [comment]
Thanks for the further clarification, @millansingh. The problem you're having is less with our viewbox, and more with the sizing of the glyph itself. The primary reason for the `xmark` glyph being smaller is for visual balance. (The same is true of our `check` and `plus` icons). If it shared the same height/width as some of our bigger icons, it starts to feel spindly, and out of place.

All that said, I certainly think there's a case to add some variants that are larger (and perhaps with "outlined" versions, as well). I'll consider it!

**Comment by millansingh** [comment]
@sensibleworld I guess I just disagree regarding the icon being too large (at least with xmark specifically). I think it looks weird and too small right now lol. Maybe there is a case for full-width versions of some icons like xmark? Would love to see that, though I imagine that will take some time to actually come to fruition if you guys decided to do so.

**Comment by sensibleworld** [comment]
@millansingh I can totally see where you're coming from. As it stands, there are a couple of options:

- Use a Font Awesome kit, and upload the v5 version of `xmark` to use alongside the new icons
- Wait about 4 hours or so and use our new `xmark-large` icon that's being released in version 6.1.0 (available later today, hopefully) 😉

**Comment by millansingh** [comment]
@sensibleworld haha thanks, I definitely didn't expect to get the new icon so quickly! Glad to have been a Kickstarter backer. :)
