### ISSUE TITLE
Icon request: beers icon variations

### ISSUE THREAD

**Issue by kaisplanet** [FortAwesome/Font-Awesome#18816]
![Hop](https://user-images.githubusercontent.com/101620870/158315539-8418cc3f-c0bb-4bb6-8f48-38b0285f2fd8.png)
![Beer Barrel](https://user-images.githubusercontent.com/101620870/158315548-6c7f2dce-6b28-4eca-8652-8b84fb435020.png)
![Draft Beer](https://user-images.githubusercontent.com/101620870/158316236-7d591911-8589-4f25-bd52-2b0d964381ef.png)
![Opener 2](https://user-images.githubusercontent.com/101620870/158316258-b1d34729-96fd-4378-b3cb-214c3f1f8722.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

Please make individual requests
