### ISSUE TITLE
How to rollback latest version to an older version

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#18814]
Hi,
My project was updated to the latest version of pro by mistake. How do I rollback from version 6 and restore version 5?
Cash McCall

**Comment by tagliala** [comment]
Hi

> My project was updated to the latest version of pro by mistake. How do I rollback from version 6 and restore version 5?

you mean that your project is using a Kit set on `latest`?

Try the following:
1. Navigate to https://fontawesome.com/kits
2. Select your kit
3. Navigate to settings
4. Change "Latest 6.x" to "Latest 5.x"

**Comment by ghost** [comment]
Using npm. 
Normally, I would just  do something like
.npm .uninstall "package name"
.npm .install --save "package name @ version number"
but fontawesome-pro did not seem to like that and I was wondering if there were any special considerations

**Comment by tagliala** [comment]
Could you please provide more details?

- What packages are you using?
- Are you using [semver ranges](https://github.com/npm/node-semver#ranges)?

Without information, I can suspect it is the case of `@fortawesome/fontawesome-svg-core` being updated to [1.3.0](https://www.npmjs.com/package/@fortawesome/fontawesome-svg-core/v/1.3.0-beta3). If this is the case, please revert to 1.2.36 (range `~1.2.36`) and you should be fine

If that is not the case, feel free to report your issue here and remember that as a pro customer you have dedicated support at hello@fontawesome.com

**Comment by ghost** [comment]
Update for anyone in the future that landed here: DO NOT issue your npm commands through the integrated Visual Studio 2022 Package Manager Console. Open Powershell, navigate to the project directory and issue the usual commands to uninstall and then re-install the package using the desired version number. 
Works as expected.
@tagliala Thanks for being so responsive

**Comment by tagliala** [comment]
welcome

If that was the issue, please note that the need to downgrade fontawesome-svg-core is a bug on our side and it was not supposed to break in a patch release, so apologies for this issue

We are tracking and addressing this issue at #18663 (and others)

closing here
