### ISSUE TITLE
Icon request: memo-slash

### ISSUE THREAD

**Issue by itd13** [FortAwesome/Font-Awesome#18811]
Hello, please consider adding a slashed version of the current fa-memo, and/or file-lines thanks!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that **in a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/2s78abqk/2/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transform
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by itd13** [comment]
Hi,
Woah, thanks for blowing my mind! Hadn’t dug through enough documentation to come across the approaches mentioned.

Thanks again,
Dario


D. FARINA ***@***.*** | 438.822.7732

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
