### ISSUE TITLE
Icon request: Microsoft

### ISSUE THREAD

**Issue by fepegar** [FortAwesome/Font-Awesome#18845]
Hi all, and thanks for this project!

My request is for the Microsoft logo. I guess it would look a bit like

■■
■■

But with equal horizontal and vertical spacing.

I'm happy to help if necessary, but I wouldn't know where to start :)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request and fix the title?

[microsoft](https://fontawesome.com/icons/microsoft?s=brands) is already available as a brand, so I think that this request is not about the Microsoft logo

**Comment by fepegar** [comment]
Oops, sorry about that title and thanks for your reply. Let me give you some context.

I have been working on adding a Microsoft authentication provider for [Girder](https://girder.readthedocs.io/en/latest/), a data management platform by Kitware. I don't have much experience with web development. I've been using their other providers as reference and noticed that they used [Fontello](https://fontello.com/) for the icons, and all seem to be from Font Awesome. I searched "microsoft" and there were no results, so here I am. Am I asking in the wrong place?

**Comment by tagliala** [comment]
Thanks for the clarification

> I've been using their other providers as reference and noticed that they used [Fontello](https://fontello.com/) for the icons, and all seem to be from Font Awesome

Fontello is a third party service which uses Font Awesome to create a customised icon set based on different sets.

The problem is that they use Font Awesome 4.7, and microsoft icon has been added to Font Awesome 5.0.0, so it is not available on that service

> Am I asking in the wrong place?

I think that the issue to follow is fontello/fontello#665, and at this point they could be interested in upgrading to FA 6.1

Also, Fontello allows to import custom svgs, but I do not know if that is possible from the command line interface by using the APIs as [Girder is doing at the moment](https://github.com/girder/girder/blob/master/girder/web_client/fontello/fontello.config.json)

**Comment by fepegar** [comment]
I'll talk to the Girder and Fontello folks, then. Thanks a lot!
