### ISSUE TITLE
Icon request: icon-car-fire

### ISSUE THREAD

**Issue by rickyv3** [FortAwesome/Font-Awesome#18852]
Hi,

Can we see an icon that resembles a car on fire? That would be helpful for our use case.

Thank you!
RV

**Comment by gdvalderrama** [comment]
Maybe as an alternative you can stack the car and fire icons.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
