### ISSUE TITLE
Icon request: computer-speaker-keyboard-mouse

### ISSUE THREAD

**Issue by LevaCompany** [FortAwesome/Font-Awesome#18932]
PC,Speaker,Keyboard,Mouse icon in category [Devices + Hardware Icons](https://fontawesome.com/icons/categories/devices-hardware)

Code: `<i class="fa-solid fa-computer-speaker-keyboard-mouse"></i>`, `<i class="fa-regular fa-computer-speaker-keyboard-mouse"></i>`, `<i class="fa-light fa-computer-speaker-keyboard-mouse"></i>`,  `<i class="fa-thin fa-computer-speaker-keyboard-mouse"></i>`,  `<i class="fa-duotone fa-computer-speaker-keyboard-mouse"></i>`

**Comment by tagliala** [comment]
Hi!

You mean PC,Speaker,Keyboard,Mouse in a single icon?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
