### ISSUE TITLE
Icon request: balcony-sun-sea (balcony sea view)

### ISSUE THREAD

**Issue by IgorIlgiyaev** [FortAwesome/Font-Awesome#18935]
For example
https://wallpaperaccess.com/full/1166721.jpg

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by tagliala** [comment]
Sorry, templates are not working :\

**Comment by tagliala** [comment]
Please provide an example of the icon you are requesting

**Comment by IgorIlgiyaev** [comment]
Updated

**Comment by tagliala** [comment]
Thanks. Any single color example that works at 16px?

**Comment by IgorIlgiyaev** [comment]
![D60F3F8F-A6D6-43D2-8729-1D19925B813C](https://user-images.githubusercontent.com/20319110/164887450-001c52b3-29ff-4e0a-8e55-f39bd4aaa5c6.jpeg)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
