### ISSUE TITLE
more icons about pop culture ( TV shows , Movies)

### ISSUE THREAD

**Issue by salohman** [FortAwesome/Font-Awesome#18956]
I really wanted an Icon for Heisenberg from breaking bad , I see there's some icons for star wars which is cool but there's none for any tv show

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+)
