### ISSUE TITLE
Icon request: rotate-slash

### ISSUE THREAD

**Issue by Mtn-View** [FortAwesome/Font-Awesome#18973]
I would like an icon like fa-rotate, but with a slash through it. The general idea is that I'd have fa-rotate for an item that was synced, fa-rotate-exclamation for an item that had a sync error, and fa-rotate-slash for an item that has not been synced yet.
![37214828-8336b55e-23b6-11e8-8f29-4f8626018963](https://user-images.githubusercontent.com/4822773/165862002-cbd3dad8-326b-4de4-8145-ec83824427f0.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Is this a request for two icons?

**Comment by Mtn-View** [comment]
It is not. I'm requesting an icon like fa-rotate, but with a slash through it, similar to the center icon in the attached image.

**Comment by tagliala** [comment]
Thanks for the clarification.

Please keep in mind that **in a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/120/

Ref:

https://fontawesome.com/v6/docs/web/style/power-transform
https://fontawesome.com/docs/web/style/mask
https://fontawesome.com/docs/web/style/layer

**Comment by Mtn-View** [comment]
Oh that's neat, thanks. I'll have to try that on Monday.

**Comment by Mtn-View** [comment]
Looks like I won't be able to use that feature in my project after all. Thanks for the tip, though!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
