### ISSUE TITLE
Icon Request: file-pen-alt

### ISSUE THREAD

**Issue by Tragen** [FortAwesome/Font-Awesome#18977]
I used v5 icons of this icons
file-pen, file-minus, file-xmark, file-plus
Now, they don't fit together as file-pen has the pen on the side and not inside the file anymore.
As the icons have a maximum size of 32x32 pixels in our software, the file-pen is smaller in the height as the size is used by the width of the icon.  Could you add a file icon with the pen inside?

Thanks.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

@sensibleworld should this be considered a bug or have priority?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
