### ISSUE TITLE
Icon request: icon-mjolnir

### ISSUE THREAD

**Issue by DesignCapn** [FortAwesome/Font-Awesome#19012]
Heathenry is an ancient and global religion reconstructed in the last 40 years as an inclusive belief system. Please consider adding the religion's common icon, Mjolnir, to the list of available religious symbols. If the Jedi and Pastafarians can have theirs, I would argue we Heathens should be able to have theirs.

Attached is a file of outline and filled versions for consideration.

![fa-mjolnir](https://user-images.githubusercontent.com/105076437/167196968-653a37e2-e498-4aa9-a78a-3d7648f4f109.png)
![fa-mjolnir-o](https://user-images.githubusercontent.com/105076437/167196979-fec9fc1a-4f67-4d47-bd58-01d8bd9e7106.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
