### ISSUE TITLE
can someone help css content icon not show

### ISSUE THREAD

**Issue by arbaz0198** [FortAwesome/Font-Awesome#19017]
hi, I'm using a first-time CSS content icon but it's not working.
I'm using at this site http://rafi.nka-consult.com/

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I can't find occurrences of Font Awesome, because the website appears to use font icons processed by icomoon

We do not provide support for third party libraries / plugins, but if you have an issue with Font Awesome feel free to provide more information (and a reduced reproducible test case using Font Awesome)
