### ISSUE TITLE
Icon Request: fa-big-size-tiles

### ISSUE THREAD

**Issue by bbolcsa** [FortAwesome/Font-Awesome#19023]
Please create an icon for us with the attached graphics. 
We would like to use it on csempe-shop.hu as an infographic icon fro big size tiles.

![noun-standing-man-1457391](https://user-images.githubusercontent.com/105200693/167368746-643b9549-5427-46e4-ab55-944d1b4e0fc5.svg)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
