### ISSUE TITLE
Icon request: Concrete

### ISSUE THREAD

**Issue by bhubbard** [FortAwesome/Font-Awesome#19029]
Would like to see icons for concrete. Here are some examples:

https://www.vectorstock.com/royalty-free-vector/reinforced-concrete-icon-vector-30415088
https://www.vectorstock.com/royalty-free-vector/reinforced-concrete-icon-vector-3173638
![reinforced-concrete-icon-vector-31736383](https://user-images.githubusercontent.com/3837/167518699-36b8a8c7-4d3c-4e59-8bc7-f20b15b408c2.png)
![reinforced-concrete-icon-vector-30415088](https://user-images.githubusercontent.com/3837/167518700-8b70f2a6-f370-471f-8699-71e251e96ee7.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
