### ISSUE TITLE
Icon Request: fa-repeat-slash

### ISSUE THREAD

**Issue by mtachaudhary** [FortAwesome/Font-Awesome#19038]
![image](https://user-images.githubusercontent.com/22431578/168336499-d8290dba-a549-4abb-9fe9-6d058f41fd7e.png)

Please add the "No Repeat" icon, opposite of `fa-repeat`. My suggestion is to draw a single diagonal line on the **repeat icon** and give it the name `fa-no-repeat`. Both repeat and no-repeat icons mat used for recurring and non-recurring events, respectively.

What is your opinion?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that **in a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/139/

Ref:

https://fontawesome.com/v6/docs/web/style/power-transform
https://fontawesome.com/docs/web/style/mask
https://fontawesome.com/docs/web/style/layer

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
