### ISSUE TITLE
Icon request: fa-filter-floppy-disk

### ISSUE THREAD

**Issue by bzi-pro** [FortAwesome/Font-Awesome#19047]
A filter icon with a floppy disk for save

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that **in a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/143/

Ref:

https://fontawesome.com/v6/docs/web/style/power-transform
https://fontawesome.com/docs/web/style/mask
https://fontawesome.com/docs/web/style/layer

**Comment by bzi-pro** [comment]
Hi

The problem is, that I use this great fonts in a xamarin.forms application. Is there a similar function like the power transformation in c# or xaml?

Regards,
Bruno

Von: Geremia Taglialatela ***@***.***>
Gesendet: Samstag, 28. Mai 2022 17:25
An: FortAwesome/Font-Awesome ***@***.***>
Cc: Bruno Zimmermann ***@***.***>; Author ***@***.***>
Betreff: Re: [FortAwesome/Font-Awesome] Icon request: fa-filter-floppy-disk (Issue #19047)


Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that in a web application it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/143/

Ref:

https://fontawesome.com/v6/docs/web/style/power-transform
https://fontawesome.com/docs/web/style/mask
https://fontawesome.com/docs/web/style/layer

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
