### ISSUE TITLE
Enhancement: Differences between 'nfc' and 'nfc-slash'

### ISSUE THREAD

**Issue by aethior** [FortAwesome/Font-Awesome#19057]
![nfc](https://user-images.githubusercontent.com/1769227/169434283-0ea47635-6ea3-49f0-8723-65b8b970a0a8.gif)

**Comment by sensibleworld** [comment]
What's happening here is that exported SVG paths are redrawn when we import into our build-system, and they'll always be slightly different depending on an icon's composition. In the case of this icon, because there's a "slash" element in it, the way the paths are drawn is different than the standard non-slash version. What's more is that an icon may have a slightly different path depending on implementation (SVGs handle curves different than some typefaces, for example).

This is all to say that minor differences like these are expected. If there's a MAJOR difference between icons, we can likely make an update, but for something as small as this, there's not a ton I can do. I'm going to close the issues where I don't think an update is going to fix much.
