### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by besho12** [FortAwesome/Font-Awesome#19055]
Can you please add a thumbtack icon from the top view
![thumbtack](https://user-images.githubusercontent.com/40858313/169421032-dfdd6fe8-4045-465c-b188-c940fe14d5e5.PNG)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify why https://fontawesome.com/icons/thumbtack?s=solid does not fit the use case?

**Comment by besho12** [comment]
Hi
mmm, yup it's looks good. Thanks

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/thumbtack?f=classic&s=solid)
