### ISSUE TITLE
Icon request: magnifying-glass-auto

### ISSUE THREAD

**Issue by mshababR** [FortAwesome/Font-Awesome#19094]
Hi

I think it would be good to have automatic zoom or automatic magnifying glass icon.
Example from:
https://www.iconfinder.com/icons/1386693/actual_auto_zoom_automatic_magnifier_magnifying_glass_scale_view_icon
![image](https://user-images.githubusercontent.com/69140730/171608089-fd027a9b-fea3-4ff2-97ef-c7e9415ca3c7.png)

Thank you!

**Comment by mshababR** [comment]
Hi

Any chance to have this icon in the near future?

**Comment by tagliala** [comment]
Hi!

You be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

A workaround that does not look good because of the different font-weight, may be the following: https://jsfiddle.net/tagliala/bfa6uhse/177/

Ref:

https://fontawesome.com/v6/docs/web/style/power-transform
https://fontawesome.com/docs/web/style/mask
https://fontawesome.com/docs/web/style/layer

**Comment by mshababR** [comment]
Thank you tagliala for the useful information!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
