### ISSUE TITLE
Icon request: book-arrow-down

### ISSUE THREAD

**Issue by taophp** [FortAwesome/Font-Awesome#19106]
### Use case

Link to download an ebook.

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that **in a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/157/

There are also other stacking options with Font Awesome Pro: https://jsfiddle.net/tagliala/2s78abqk/29/

https://fontawesome.com/v6/docs/web/style/power-transform
https://fontawesome.com/docs/web/style/mask
https://fontawesome.com/docs/web/style/layer

**Comment by taophp** [comment]
@tagliala Great ! I wasn't aware of all those transform possibilities ! Thanks for you help.

**Comment by tagliala** [comment]
Welcome!

Reopening for tracking purposes, this request is legit

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
