### ISSUE TITLE
Icon request: list-plus, list-xmark

### ISSUE THREAD

**Issue by Biohazard90** [FortAwesome/Font-Awesome#19102]
Icons to manage list entries, similar to these Android playlist icons, just adjusted to match fa-list:

Material icon playlist add: https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Aplaylist_add%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048
![image](https://user-images.githubusercontent.com/5513441/172030740-ff35f6eb-09a5-429c-9b9d-a3468bde1f88.png)

Material icon playlist remove:  https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Aplaylist_remove%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048
![image](https://user-images.githubusercontent.com/5513441/172030744-8f7586d8-3270-4042-bb71-2f55a021903a.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that **in a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/149/

Ref:

https://fontawesome.com/v6/docs/web/style/power-transform
https://fontawesome.com/docs/web/style/mask
https://fontawesome.com/docs/web/style/layer

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
