### ISSUE TITLE
Icon request: Function keys (60 icons)

### ISSUE THREAD

**Issue by Vitcesar** [FortAwesome/Font-Awesome#19108]
Just like there are letters and numbers icons I think it might be available simple alphanumeric icons like F1, F2, etc, for all twelve function keys.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
