### ISSUE TITLE
No Report/Labels icons

### ISSUE THREAD

**Issue by unpococloco** [FortAwesome/Font-Awesome#19127]
I am creating a UI where my users need to print reports and mailing labels.

Was shocked to discover FA had neither icon.

Please create some?

FWIW, I use FA dark icons.

Thanks!

Please see attached samples taken from Filemaker Pro

![sample_labels_icon](https://user-images.githubusercontent.com/61477993/173431057-2be84d03-f2b4-4c2e-9904-d8c4640fa364.png)
![sample_report_icon](https://user-images.githubusercontent.com/61477993/173431059-0b2978ef-dab4-4990-be53-71aeea8b4b45.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think that https://fontawesome.com/icons/table-cells?s=solid or https://fontawesome.com/icons/table?s=solid may fit the use case for "labels"

https://fontawesome.com/icons/file-lines?s=solid may fit the use case for person list report. There are other files related icons at https://fontawesome.com/icons/categories/files

Please open two individual requests by filling out on the GitHub website two [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+), one for each icon.

Please also clarify in the requests why the existing icons do not fit the use case (it will be enough something like "the design does not fit because the borders should be separated)

Closing here, but feel free to comment if I've missed something

**Comment by unpococloco** [comment]
I have complied with your new icon request instructions.

In the mean time, your suggestions are acceptable compromises until FA releases better alternatives.

Thanks!

Steve
	Mark Stevens (Steve) Willis, PhD
Director of Software Development
Life Christian University
	(813) 909-9720 x777
   	
	(813) 909-9730
   	
	(928) 899-9895
	lcus.edu <https://cookiefree.lcus.edu/>	   	
	***@***.*** ***@***.***>	   	 
CONFIDENTIALITY NOTICE: This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.
