### ISSUE TITLE
Icon request: mailing-labels

### ISSUE THREAD

**Issue by unpococloco** [FortAwesome/Font-Awesome#19132]
### Use case

In any menu where printed mailing labels is an option.

Your existing fa-table and fa-table-cells are marginally acceptable for this, but I feel they should be inverted (black cells on white) to better indicate a page of labels, rather than table cells.

To further indicate this is printed output, you could add a turned-down corner at upper-left.

Just some ideas. You folks are the icon gurus, so knock me out with your cool take on this!

### Example image

![173431057-2be84d03-f2b4-4c2e-9904-d8c4640fa364](https://user-images.githubusercontent.com/61477993/173663315-91e8faa5-a31f-4446-810b-115ba5a9412e.png)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
