### ISSUE TITLE
Icon request: printed-report or printed-document

### ISSUE THREAD

**Issue by unpococloco** [FortAwesome/Font-Awesome#19131]
### Use case

In any menu where a printed report is an option.

Your existing fa-file-lines doesn't render well at the sizes I will be using them, specifically the lines blur into obscurity.

### Example image

![173431059-0b2978ef-dab4-4990-be53-71aeea8b4b45](https://user-images.githubusercontent.com/61477993/173661748-12750ce5-6272-4fb3-87bd-3bfbd360e440.png)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
