### ISSUE TITLE
Icon request: Sunbed

### ISSUE THREAD

**Issue by Jukien** [FortAwesome/Font-Awesome#19140]
### Use case

Add a sunbed or a deckchair, first variant.

This icon can be useful for holidays and beach context. You already have the umbrella-beach. It could be great to have the sunbed too :sunglasses:

### Example image

First variant, a simple sunbed where we could change the color of the tissue.
Having it diagonally would be nice I think.

![image](https://user-images.githubusercontent.com/32452023/174433997-7d5378a0-296a-488a-a505-77b111a9384c.png)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
