### ISSUE TITLE
Icon request: Switch all hand icons to 4 fingers

### ISSUE THREAD

**Issue by plachta-zabatt** [FortAwesome/Font-Awesome#19149]
### Use case

I believe that as is most hand icons look 'too wide' 5 fingers is too many for the icon, or there is simply too much space b/w fingers! The Simpsons knew what they were doing, give us 4 fingers, or go back to the more tightly spaced fingers, please! 

Thank you for your time.

### Example image

**v5.15.4**
![image](https://user-images.githubusercontent.com/67343014/175552877-41a7167c-a5d4-4099-80c8-5449434f0a2e.png)

**v6.1.1**
    **I believe all of these look far too wide & strange **
![image](https://user-images.githubusercontent.com/67343014/175553132-73656a68-9fc4-493d-b5de-85851e377a55.png)
![image](https://user-images.githubusercontent.com/67343014/175553350-34b650c7-9f7f-472a-9752-d543d4bb5fd1.png)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
