### ISSUE TITLE
Icon request: icon-pro

### ISSUE THREAD

**Issue by Sportsa** [FortAwesome/Font-Awesome#19159]
Similar to the PRO icon - I think it would be great to have a BASIC word based icon and a PREMIUM word based icon

Pro is often used to denote a PRO level of service, however, PREMIUM is more often used - there is nothing other than crowns that could be used by a service to denote this as a badge

Thanks!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We tend to avoid the use of words inside icons, for different reason. In this case in particular, words are subject to localization issues and having multiple letters in a single icon will reduce readability at small sizes

I will keep this request open, but please consider alternatives.

Also, FA6 comes with a font, so you can compose PRO: https://jsfiddle.net/tagliala/ex4hp3yn/7/

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
