### ISSUE TITLE
Bug: 401 Access Denied to free assets

### ISSUE THREAD

**Issue by auberryberry** [FortAwesome/Font-Awesome#19150]
### Bug description

Not sure if this is a transative error but font-awesome is coming into our build via TailwindCSS, we're seeing 401 access denied for all of our users on free assets via fontawesome npm CDN.

Looks like permissions on endpoints have been changed by mistake.

### Reproducible test case

https://npm.fontawesome.com/@fortawesome/free-regular-svg-icons/-/6.1.1/free-regular-svg-icons-6.1.1.tgz

### Screenshots

![image](https://user-images.githubusercontent.com/394716/175576508-58b50105-946c-401b-8065-a3a98d16adce.png)

### Font Awesome version

v6.1.1

### Serving

Font Awesome CDN

### Implementation

Other (as specified in the bug description)

### Browser and Operating System

- WSL & OSX

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by anixan** [comment]
I also getting this issue, failing as auth seems to now be required :/

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I can see that this example is using the private NPM repository `https://npm.fontawesome.com`, which is restricted to Pro Users

Since it is not specified in the opening post, could you please confirm that you are a Pro user?

**Comment by auberryberry** [comment]
Hola amigo,

Not using pro at all.

**Comment by auberryberry** [comment]
I've told a lie, it was coming in via babylonJS inspector, I've removed it for now. I'm sure it's a transitive issue.

**Comment by tagliala** [comment]
>  I've told a lie, it was coming in via babylonJS inspector, I've removed it for now. I'm sure it's a transitive issue.

Hi, my question is that if you are a Font Awesome Pro user, then you can use the pro private npm repository to download Font Awesome Free, otherwise you should use the public npm / yarn repository

In case that you are not a Font Awesome Pro User, probably there is a misconfiguration

Please check your `.npmrc` files, there should be an entry pointing the `@fortawesome` namespace to the NPM pro repository. Remove that configuration, then remove font-awesome from `yarn.lock` and retry

You should be able to have more information by running `yarn config list --verbose`

It will output a list of paths in which there could be a `.npmrc` loaded by yarn and the actually loaded configuration, that may include

```
info npm config
{
  ...
  '@fortawesome:registry': 'https://npm.fontawesome.com/',
  '//npm.fontawesome.com/:_authToken': 'A-TOKEN'
}
```

the above lines should be removed. The expected repository used in yarn is `https://registry.yarnpkg.com/@fortawesome`

**Comment by auberryberry** [comment]
Well played, a little cross-pollination going on there, thank you.
