### ISSUE TITLE
Icon request: PygmyGoat Hoof (GoatHoof,  Hoof,  PygmtGoat ¯\_(ツ)_/¯  )

### ISSUE THREAD

**Issue by wolfspyre** [FortAwesome/Font-Awesome#19215]
### Use case

Use case

Its a hoof print. it could also be stacked behind other icons to add horns :)

Icon request checklist

  ✔️  The title starts with "Icon request: " and is followed by the requested icon name
  ✔️  This icon does not represent a brand
  ✔️  This is a single icon or matched pair (Ex: lock / unlock)
  ✔️ The request is for a concrete object,  ✔️  I've included an example image
  ✔️   I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
  ✔️   I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

### Example image

![Goat Hoof](https://user-images.githubusercontent.com/1680659/181128388-9a846e58-90c6-4509-82c9-b54419f2c5ef.svg)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
