### ISSUE TITLE
Icon request: phone-pause

### ISSUE THREAD

**Issue by maxresnikoff** [FortAwesome/Font-Awesome#19341]
### Use case

Would love to see a phone with a pause button alongside. 
Much like phone-plus: [](https://fontawesome.com/icons/phone-plus?s=solid&f=classic), but with a pause icon. 

Used for VOIP systems to put someone on hold

### Icon request checklist

- [x] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by Pyvonix** [comment]
@maxresnikoff Something like that?

Solid icon:
![image](https://cdn-icons-png.flaticon.com/512/483/483968.png)

Light icon:
![image](https://cdn-icons-png.flaticon.com/512/481/481321.png)

**Comment by maxresnikoff** [comment]
Lovely! Will do the trick thanks!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
