### ISSUE TITLE
Icon request: faChevron* icons missing from free-regular-svg-icons.

### ISSUE THREAD

**Issue by keith-aa** [FortAwesome/Font-Awesome#19342]
### Use case

The faChevron* icons are provided in free-solid-svg-icons but are missing in free-regular-svg-icons. Can you please add them?

Here is a list of missing icons:
faChevronCircleDown
faChevronCircleLeft
faChevronCircleRight
faChevronCircleUp
faChevronDown
faChevronLeft
faChevronRight
faChevronUp
faCircleChevronDown
faCircleChevronLeft
faCircleChevronRight
faCircleChevronUp

### Example image

All the images can be found at https://fontawesome.com/icons/. For example, faCircleChevronRight is https://fontawesome.com/icons/circle-chevron-right?s=regular&f=classic

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> The faChevron* icons are provided in free-solid-svg-icons but are missing in free-regular-svg-icons. Can you please add them?

A subset of regular icons is available in the free version mostly because they were outlined icons of FA4 or for other use cases like switching from empty heart/star to filled heart/start

Example:
- V4: https://fontawesome.com/v4/icon/star-o
- V5+: https://fontawesome.com/icons/star?s=regular&f=classic

If you are interested in regular icons because they better fit your use case, please consider to buy FA Pro

Sorry, but I will close this otherwise we can have a similar request for each one of the regular icons not included in the free set, hope you understand

Closing here, but feel free to comment

**Comment by keith-aa** [comment]
Thanks for the quick response and clarification! Keep up the great work!
