### ISSUE TITLE
Icon request: conversation - meeting

### ISSUE THREAD

**Issue by paquinmathieu** [FortAwesome/Font-Awesome#19374]
There are icon with "bubble" already, but I would make good use of a icone that shows 2 person actually talking together or representing meeting someone
Something like this for example , any better idea is welcomed
![image](https://user-images.githubusercontent.com/70521253/195191889-dbd812e9-8282-4b13-bc75-f670c63d1083.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
