### ISSUE TITLE
Icon request: shield-car

### ISSUE THREAD

**Issue by bradherman** [FortAwesome/Font-Awesome#19375]
Shield with a car inside to represent insurance policies.  Or potentially car-shield with car, and small shield on bottom right corner.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that **in a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/174/

Ref:

https://fontawesome.com/v6/docs/web/style/power-transform
https://fontawesome.com/docs/web/style/mask
https://fontawesome.com/docs/web/style/layer

**Comment by bradherman** [comment]
Oh cool, it looks like Power Transforms and Masking are both possible in React Native as well, which is where we're using this.  Will give it a shot!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
