### ISSUE TITLE
Icon request: Chevron Up Down

### ISSUE THREAD

**Issue by bcorcoran** [FortAwesome/Font-Awesome#19434]
### Use case

I'd like to request a chevron-up-down that is an upward-facing chevron placed above a downward-facing chevron, like "chevron-up-down" on https://heroicons.com/

The most common use case is for a select menu handle. 

Although it's *possible* to use layers to create this concept, chevrons are centered which make icon generation with layers a little less than straightforward (you have to position both separately). I think this being its own discrete icon has a fair amount of value relative to the effort involved to create it.

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/angles-up-down?f=classic&s=solid)
