### ISSUE TITLE
Icon request: (general/gas/oil/water) tank (full/half/quarter/three-quarters/empty)

### ISSUE THREAD

**Issue by Rilnaista** [FortAwesome/Font-Awesome#19435]
### Use case

Due to the gas crisis in germany I add a digital meter to my gas tank in the yard. I would like to display the current level on my smarthome dashboard by the same way as I display the current level of other items. There I use the battery icon and thats fits for me.

I don't wan't to use the battery icon for tanks. It's similar, but not the same. 

On my way to search for a usefull item I recognized that there are no icons which can be used for undefined tanks, nor for gas / oil or water tanks.

It would be very nice if you could add some general icons and perhaps some special icons for oil / water / gas.

I love this clean icon set!

Thank you!

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
