### ISSUE TITLE
Icon request:  chatbot v4/v5

### ISSUE THREAD

**Issue by karekauan** [FortAwesome/Font-Awesome#19453]
### Use case

Useful for situations where currently available robot icons are not clear enough to indicate that the robot references a chatbot.

### Example image

![chatbot](https://user-images.githubusercontent.com/71836200/204612942-96a6ca02-5396-470a-8ca9-769379c21f07.png)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

There is already a chatbot icon available in FA Pro: https://fontawesome.com/icons/message-bot?s=solid&f=classic

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/message-bot?f=classic&s=solid)
