### ISSUE TITLE
Icon request: Sobriety Icons

### ISSUE THREAD

**Issue by AbbyJanke** [FortAwesome/Font-Awesome#19482]
### Use case

Mobile/Web applications designed for those in recovery. IE: Alcoholics Anonymous, Narcotics Anonymous logos along with a "fa-coin" that as more space on top to stack numbers (ie: 1, 2, 3, 14, 23, etc for months/years)

This could also fit under the healthcare category as at least within the US recovery is considered a medical disease.

### Example image

![AA](https://user-images.githubusercontent.com/487798/208266437-216d1d97-1ca8-4b67-8df8-7991da3ef89b.png)
AA
![NA](https://user-images.githubusercontent.com/487798/208266445-b5bca703-c654-42e2-b612-545162d6b8eb.gif)
NA
![coin](https://user-images.githubusercontent.com/487798/208266484-1b815c4e-603d-44a4-9234-1a98923489e2.png)
This is similar to `fa-coin-blank` but I would like to see the blank area a little bigger to easily read the numbers placed on top of it using the stack function.

There are plenty of other ones like CA (it's CA in a circle) but these 2 are the more common ones.

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
