### ISSUE TITLE
Icon request: "Subscribe" / "Subscription"

### ISSUE THREAD

**Issue by jaradc** [FortAwesome/Font-Awesome#19505]
I searched but couldn't find a "subscribe" / "subscription" icon.
I lack vision for what it could look like. It's usually the word "Subscribe" in the background with a pointer hand over it illustrating someone clicking a subscribe button. But how to fit all that concept into an icon, I'm not sure.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

As per our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+), we prefer requests for concrete objects because it is hard to implement an icon that represents "subscription"

Also, we tend to avoid icons containing text, because they have internalization issues and long words like "subscribe" will not work for the base icon size of 16px

I'm going to close here, but if someone from the community comes up with an idea I will reopen
