### ISSUE TITLE
Icon request: hand-plane

### ISSUE THREAD

**Issue by jxpx777** [FortAwesome/Font-Awesome#19547]
### Use case

This icon would be used in reference to woodworking projects, linking to tool manufacturers, etc. More abstractly, it represents something being hand-crafted.

### Example image

![image](https://user-images.githubusercontent.com/24182/217033380-cd969fa5-e7f6-4d6e-8dc3-b418173ff400.png)

(from https://www.istockphoto.com/vector/retro-vintage-woodworking-wood-fore-plane-jack-plane-design-gm1173074900-325682593)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
