### ISSUE TITLE
Icon request: icon-new, icon-flor, icon-corte de diamante, icon-anillo, icon-name, icon-women, icon-men, icon-gemas

### ISSUE THREAD

**Issue by emmavaz88** [FortAwesome/Font-Awesome#19555]
### Use case

los necesito para personalizar el 
![menu 1](https://user-images.githubusercontent.com/125078964/218160121-29d95e6f-6371-4848-a9f2-d50cbe44a754.jpg)
menú] de mi sitio web

### Example image

![WhatsApp Image 2023-02-09 at 11 59 12 AM](https://user-images.githubusercontent.com/125078964/218161306-8660777c-76e4-48d3-bc42-d4fb97e63fea.jpeg)
![joya](https://user-images.githubusercontent.com/125078964/218161311-edc333f5-4e78-4dde-a575-bdf0dd5e76b1.png)
![hombre](https://user-images.githubusercontent.com/125078964/218161314-f3aa84c9-c0b3-4ff4-a468-c934958e27d9.png)
![mujer](https://user-images.githubusercontent.com/125078964/218161316-7c6fcc4a-3ee4-4fb5-b71d-fb7a795abf90.png)
![aretes](https://user-images.githubusercontent.com/125078964/218161317-6fbf9b67-bee4-4900-9a81-a27ac544c5db.png)
![nuevo-producto](https://user-images.githubusercontent.com/125078964/218161319-b0b1351b-e421-4238-9ace-1ebd25c3f680.png)
![anillo-de-bodas](https://user-images.githubusercontent.com/125078964/218161321-b4f3a639-af69-4d61-b97c-b01d613cd87a.png)
![flor](https://user-images.githubusercontent.com/125078964/218161324-38d3e478-bc89-4831-b93b-bb7e289e35d5.png)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

>This is a single icon or matched pair (Ex: lock / unlock)

Sorry, but this request does not meet our contributing guidelines

Please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+) correctly.

Please also search for existing request and for existing icons, because I can see that some icons have been implemented

Closing here, but feel free to comment if I've missed something
