### ISSUE TITLE
Icon request: Icon request: icon-new_3324

### ISSUE THREAD

**Issue by emmavaz88** [FortAwesome/Font-Awesome#19556]
### Use case

![menu 1](https://user-images.githubusercontent.com/125078964/218223202-9c3c01c8-a113-4c78-b57e-f851051fa2fd.jpg)

### Example image

[new_3324.zip](https://github.com/FortAwesome/Font-Awesome/files/10712044/new_3324.zip)
 adjunto el archivo icono para su mayor facilidad

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
