### ISSUE TITLE
Bug: New Sharp industry icons are not aligned

### ISSUE THREAD

**Issue by Llorx** [FortAwesome/Font-Awesome#19562]
### Bug description

Industry icons are not aligned between them. Solid industry has different height as regular industry, and industry-windows has a height offset compared to normal industry. This does not happen in Classic industry icons.

### Reproducible test case

https://user-images.githubusercontent.com/702490/219316371-164976f3-cbf6-4bdc-aacb-50c245de8830.gif

### Screenshots

![chrome_8xBHbqn928](https://user-images.githubusercontent.com/702490/219316371-164976f3-cbf6-4bdc-aacb-50c245de8830.gif)

### Font Awesome version

v6.3.0

### Serving

Other (as specified in the bug description)

### Implementation

Other (as specified in the bug description)

### Browser and Operating System

- Chrome 109 Windows 10.

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by sensibleworld** [comment]
Hi there! I think this is just an issue with our search interface caused by the "industry-windows" text jumping to two lines. The icons themselves should still be consistent when used or downloaded.

**Comment by Llorx** [comment]
Oh, thank you for your reply!

Still the industry regular and industry solid have different ceiling height.

**Comment by sensibleworld** [comment]
Hi @Llorx, the differing heights is by design. We don't lock our icon proportions/sizes to always be consistent between weights. We're more concerned with the balance of the design themselves. In the case of this particular icon, the thicker line-weight of the regular style means necessitated making the height (and width of the chimney, for example) larger so the icon felt in-proportion with other icons in the Regular style.
