### ISSUE TITLE
Icon request: rectangle-history-circle-minus

### ISSUE THREAD

**Issue by tatwater** [FortAwesome/Font-Awesome#19575]
There already exists a `rectangle-history` and a `rectangle-history-circle-plus`! Considering using these for follow & unfollow icons, but there's no equivalent minus version for unfollowing! Would love to have this option.

Thanks!

**Comment by sensibleworld** [comment]
While it's not currently an official icon, you can make this using our Icon Wizard!

<img width="1267" alt="CleanShot 2023-02-21 at 13 56 59@2x" src="https://user-images.githubusercontent.com/529604/220434522-9eda2672-91d2-4349-8588-631ef39b387d.png">

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

In addition to @sensibleworld's answer

Your request is legit, but please keep in mind that **in a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo:
- https://jsfiddle.net/tagliala/2s78abqk/39/

**Heads-up!** Pro customers can also implement this icon with the [Icon Wizard](https://fontawesome.com/v6/docs/web/add-icons/icon-wizard#contentHeader)

Ref:
- https://fontawesome.com/v6/docs/web/style/power-transform
- https://fontawesome.com/docs/web/style/mask
- https://fontawesome.com/docs/web/style/layer
- https://fontawesome.com/v6/docs/web/add-icons/icon-wizard#contentHeader

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
