### ISSUE TITLE
Icon request: download-pdf

### ISSUE THREAD

**Issue by Fragusan** [FortAwesome/Font-Awesome#19581]
### Use case

This could be a popular file usage icon (as are file-excel and file-word ) but unified with the download.

### Example image
suggested logo [here](https://i.ibb.co/RHqq62T/download-pdf.png)

### Icon request checklist

- [x]  The title starts with "Icon request: " and is followed by the requested icon name

 - [x] This icon does not represent a brand
- [x] This is a single icon or matched pair (Ex: lock / unlock)
- [x] The request is for a concrete object, or I've included an example image
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by itgenolife** [comment]
you can use this  https://fontawesome.com/icons/file-pdf?s=solid&f=classic

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
