### ISSUE TITLE
Icon request: rectangle-wide-round (pill)

### ISSUE THREAD

**Issue by jssmtmmns** [FortAwesome/Font-Awesome#19611]
A wide rectangle with corner radius. Basically the toggle icon, without a switch in it, but the footprint of 'rectangle-wide'.

Use case:
visualizing a button style in an editor.

![Screenshot 2023-03-14 134906](https://user-images.githubusercontent.com/105083254/225094350-b70d8fe9-8857-4abf-b874-c0464cdf1b01.png)

**Comment by karthiknadar1204** [comment]
i would like to work on this issue,please assign it to me

**Comment by prajaktakap00r** [comment]
I would like to contribute . Please assign

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
