### ISSUE TITLE
Icon request: Chart Settings

### ISSUE THREAD

**Issue by derrichDeu** [FortAwesome/Font-Awesome#19629]
In the age of BI - a symbol that clearly indiciates you'll be working with the setup of a visual(Chart) would be great.

a filled Gear with Bars inside is how I would envision this symbol. 
Something similar to the below:
![image](https://user-images.githubusercontent.com/123731047/227504270-0890a0d0-ef01-4c5c-b58f-dbce456e2703.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or it's just not a good fit for Font Awesome. But if you feel really strongly about it, feel free to make your case by submitting a new issue.

That said, you can create a version of any of the above icons with the gear as a modifier with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
