### ISSUE TITLE
Icon request: fa-person-figure-skating

### ISSUE THREAD

**Issue by delijah** [FortAwesome/Font-Awesome#19643]
### Use case

An icon that describes the olympic discipline "figure skating".

### Example image

<img width="108" alt="Screenshot 2023-04-03 at 16 33 27" src="https://user-images.githubusercontent.com/237739/229541698-c228064b-10df-45c3-9f6f-c0abd56f852a.png">

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome! [Take a look at it here.](https://fontawesome.com/icons/person-skating?f=classic&s=solid)
