### ISSUE TITLE
Icon request: image-exclamation, nft-exclamation, image-check, nft-check

### ISSUE THREAD

**Issue by slrsven** [FortAwesome/Font-Awesome#19662]
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/115986191/231124355-4535ed91-c9f1-48e0-affa-d1bd2004a024.png">

Hey there,
I see way bigger edge-cases covered so why not add for these as well.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
