### ISSUE TITLE
Icon request: shield-bolt

### ISSUE THREAD

**Issue by joshbartholomew** [FortAwesome/Font-Awesome#19680]
A shield with a bolt inside

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! (Or at least a version with a bolt to the side) [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
