### ISSUE TITLE
Bug: The unicode version of fa-globe has the wrong icon.

### ISSUE THREAD

**Issue by tomasantunes** [FortAwesome/Font-Awesome#19694]
### Bug description

The icon fa-globe shows the following unicode: f0ac. But when I use this code I get a different icon.

### Reproducible test case

https://codepen.io/tomasantunes/pen/wvYdapX

### Screenshots

![font-awesome-bug1](https://user-images.githubusercontent.com/12017352/234356921-a10627d9-0643-42cf-b133-7d5f94bf17f4.jpg)

### Font Awesome version

v6.4.0

### Serving

Font Awesome CDN

### Implementation

CSS

### Browser and Operating System

- Firefox 112 on Windows 10.

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This is happening because `all.css` includes v4 compatibility and the class definition falls back on v4

The proper usage would be:

```css
.icon::before {
  font-family: "Font Awesome 6 Free";
  font-weight: 900;
  content: "\f0ac";
}
```

Ref: https://fontawesome.com/docs/web/setup/upgrade/pseudo-elements#updating-font-rule-syntax

Hope it helps

Closing here, but feel free to comment
