### ISSUE TITLE
Icon request: fa-webhook

### ISSUE THREAD

**Issue by hamidh2** [FortAwesome/Font-Awesome#19698]
### Use case

Hi there, There are multiple webhook icons in the font-awesome official website that doesn't exist in **@fortawesome/free-solid-svg-icons** package, I would appreciate it if you add them cause it would be more useful.

p.s: I'm using this package in the Angular project.

### Example image

![Untitldsadsaed](https://user-images.githubusercontent.com/41614055/234828661-62679ec0-4e55-46ca-96ad-5021c5a8816f.png)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/webhook?f=classic&s=solid)
