### ISSUE TITLE
Icon request: Subscription-plan

### ISSUE THREAD

**Issue by karan1803** [FortAwesome/Font-Awesome#19701]
need icon  for the subscription plan list
![screenshot-drive google com-2023 04 28-13_43_17](https://user-images.githubusercontent.com/59016533/235093255-f071b9a9-9aef-44dd-9b03-24a2d62ff2a3.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
