### ISSUE TITLE
Icon request: Barrel Sauna

### ISSUE THREAD

**Issue by danaering** [FortAwesome/Font-Awesome#19708]
Hello,
We just installed panoramic barrel saunas at our lodge.  Very unique!  Would love to let guests know by addin a "barrel sauna" icon to our website.  Something like: https://www.shutterstock.com/image-vector/outdoor-mobile-wooden-barrel-sauna-icon-1789406933.

Could you add a "barrel sauna" icon?

Thanks
Danae

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
