### ISSUE TITLE
Icon request: calendar-alt

### ISSUE THREAD

**Issue by mwarble** [FortAwesome/Font-Awesome#19728]
Love your icons; however, I find that your calendar icons don't look very much like calendars.  The hooks at the top are too prominent, the squares representing the weekdays are too few, and they need to be more rectangular and less square.

I find many of your calendar icons look like buildings with smoke stacks and some look like car batteries.

Any chance you could create an alternative calendar icon that looks more this?

https://icons.expo.fyi/Ionicons/calendar

Thank you.

**Comment by tagliala** [comment]
Hi,

Thanks for being part of the Font Awesome Community, for your feedback, and appreciation for our icons!

> The hooks at the top are too prominent, the squares representing the weekdays are too few, and they need to be more rectangular and less square.

*Disclaimer: ChatGPT helped me in writing this answer*

We value your opinion and understand your concerns about the calendar icons. The design constraints for small sizes, such as 16px, often pose challenges in representing intricate details. The icon in the example is ~ 40x40 

To ensure legibility and clarity at smaller sizes, we had to simplify the calendar icons. The prominent hooks and fewer squares representing weekdays were intentional choices to maintain recognizability within the limited pixel space. We aimed for a balance between conveying the essence of a calendar and maintaining visual coherence at a small scale.

However, we acknowledge that there's room for alternative designs for larger sizes where more details can be accommodated. Creating a separate set of icons specifically tailored for larger sizes is indeed an option. However, it's important to note that designing a comprehensive set with 6000+ icons would be a significant undertaking.

@sensibleworld what do you think?

**Comment by mwarble** [comment]
Hi thanks for the response.

 

Would it be possible to get a custom icon designed at the larger size?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it would require too much of a change to our existing icons.
