### ISSUE TITLE
FA CDN doesnt work

### ISSUE THREAD

**Issue by OIITCONZ** [FortAwesome/Font-Awesome#19738]
According to FA you add one line into your page, then use the icons and it works. 
I have a kit, open to the world. It fails in every situation. 

Here's the test page - using minimal code. 
it uses the line given by FAs system and the test icons from FA page. 
All it shows is squares. 

<html>
	<head>
		
		<meta charset="utf-8">
			<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

				
					<title>Hello, world!</title>
<script src="https://kit.fontawesome.com/a8ab96ba8a.js" crossorigin="anonymous"></script>
				</head>
				<body>
				
				<i class="fa-solid fa-user"></i>
<i class="fa-regular fa-user"></i>
<i class="fa-light fa-user"></i>
<i class="fa-thin fa-user"></i>
<i class="fa-duotone fa-user"></i>

					</body>
				</html>

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The markup is using the new 6.x syntax (`fa-solid`) but the kit is configured for 5.15.4

You can either:
- Use the old syntax; or
- Update the Kit to 6.x

Demo: https://jsfiddle.net/tagliala/eLdyf6g8/

**Please also restrict your kit to specific domains**

Closing here, but feel free to comment

**Comment by zawrabh** [comment]
I was also facing the same issue "Font Awesome Showing Box instead of Icons". 

![image](https://github.com/FortAwesome/Font-Awesome/assets/95751390/096bfae0-2e28-4caa-9dcf-c6b5f997ccfe)

After much searching, I finally got the solution on the internet.

instead of using

`<link rel = "stylesheet" href = "https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.1/css/fontawesome.min.css">`

use this instead

`<link rel = "stylesheet" href = "https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">`

My issue got fixed

![image](https://github.com/FortAwesome/Font-Awesome/assets/95751390/0ecc41d6-5bf7-4c7e-a7a9-a9ddbb59b4fb)

I found the solution on [stackoverflow](https://stackoverflow.com/questions/29331137/font-awesome-showing-box-instead-of-icons)

**Comment by tagliala** [comment]
Hi,

this solution is actually a downgrade to Font Awesome v4, which may be ok for your application but it will not allow to use FA6.

I can notice that the link is to a third-party cdn is loading `fontawesome.min.css`, which is not the full stylesheet, but just the base one. It should include `all.min.css` to also include icons.

Note: we do not provide support to third-party CDNs, but the documentation for self-hosting is helpful for this use case: https://fontawesome.com/docs/web/setup/host-yourself/webfonts

---

Said so, if you have a specific issue, please fill out our [bug report template for web applications](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=bug%2Cneeds-triage&template=100_web_bug_report.yml&title=Bug%3A+), having care of providing a reproducible test case. Unfortunately a screenshot does not help to understand
