### ISSUE TITLE
Icon request: display-user

### ISSUE THREAD

**Issue by mheidebrecht** [FortAwesome/Font-Awesome#19737]
### Use case

Use case: give users the ability to graphically represent a telehealth session

### Example image

![display-person](https://github.com/FortAwesome/Font-Awesome/assets/17099726/2259c994-976d-4da3-976e-a5500b766e4a)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
