### ISSUE TITLE
Icon request: castell

### ISSUE THREAD

**Issue by Iron7III** [FortAwesome/Font-Awesome#19771]
### Use case

There are many pages about the casteller world, although it is a niche that is quite closed to Catalan culture, they are made around the world and they have performed in many foreign countries.
It is a very remarkable Catalan tradition and it would be a great contribution to official and unofficial pages of this.
There are other pages that have this icon, but it would be amazing to have everything centralized and with the same unique design that you give to the icons.

### Example image

![10168086](https://github.com/FortAwesome/Font-Awesome/assets/73746664/dbbbe695-e019-404b-9319-b8a8f05255e5)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
