### ISSUE TITLE
Icon request: person-singing

### ISSUE THREAD

**Issue by Brayman30** [FortAwesome/Font-Awesome#19784]
It would be great to have an icon of a person who is singing similar to the other person-verb icons.

### Use Case
To represent choirs, vocalist, and just singing in general as opposed to the closest current alternatives which are either the music or microphone icons, neither of which really mean singing on their own

### Example Image
Something like [this icon](https://icons8.com/icon/20290/singing) from Icon8's Material Filled Icons.
![Black](https://img.icons8.com/?size=512&id=20290&format=png)

```[tasklist]
### Icon Request Checklist 
- [x] The title starts with "Icon request: " and is followed by the requested icon name
- [x] This icon does not represent a brand
- [x] This is a single icon or matched pair (Ex: lock / unlock)
- [x] The request is for a concrete object, or I've included an example image
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)
```

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
