### ISSUE TITLE
Icon request: user-money(-bag)

### ISSUE THREAD

**Issue by xtay2** [FortAwesome/Font-Awesome#19809]
For Members that still have to pay their fee.

![Font Awesome user-money](https://github.com/FortAwesome/Font-Awesome/assets/19871577/f4201451-e70e-4538-9239-d3c62f3cb4a5)

```[tasklist]
### Tasks
```

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
