### ISSUE TITLE
Icon request: icon-num10

### ISSUE THREAD

**Issue by Roeidamri** [FortAwesome/Font-Awesome#19803]
Hello, I need Icon with a Solid 10 
1-0 does not working well.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> 1-0 does not working well.

You can play with `margin` and [`letter-spacing`](https://developer.mozilla.org/en-US/docs/Web/CSS/letter-spacing?retiredLocale=it) css properties according to the implementation you are using

CSS: https://jsfiddle.net/tagliala/k7heosdc/3/
SVG: https://jsfiddle.net/tagliala/4xwm9no8/2/

I'm going to close this request because it can lead to an infinite number of requests
