### ISSUE TITLE
Bug: A rectangle appears instead of an icon

### ISSUE THREAD

**Issue by Kirmez** [FortAwesome/Font-Awesome#19833]
### Bug description

I used (link) in the head putting a link from cdn library into href 
But instead of an icon, a rectangle with a cross appears

### Screenshots

![Screenshot 2023-07-25 181253](https://github.com/FortAwesome/Font-Awesome/assets/107321567/f26ce32f-5a83-4221-abe1-64654ad30934)

### Font Awesome version

v6.4.0

### Serving

Font Awesome CDN

test case

https://64c009b050d2b50259029fef--beamish-crisp-255a45.netlify.app/

### Implementation

CSS

### Browser and Operating System

Chrome on Window 11

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi @Kirmez please provide a reproducible test case, it is required for this kind of issues

**Comment by Kirmez** [comment]
Adding a link
https://64c009b050d2b50259029fef--beamish-crisp-255a45.netlify.app/

**Comment by tagliala** [comment]
Thanks.

So this is loading Font Awesome 6.4.0  CSS implementation from a third-party CDN (not supported)

The problem is that the icon is loaded with the old syntax `fa fa-telegram` without compatibility mode (a separate CSS which I do not suggest to load for new applications).

The new syntax requires `fab fa-telegram`. Please change to the new syntax and it will work

Please take a look at our docs: https://fontawesome.com/docs
