### ISSUE TITLE
Icon request: icon-ukraine 🇺🇦

### ISSUE THREAD

**Issue by PK12FCB** [FortAwesome/Font-Awesome#19839]
would it be possible to make Ukraine flag or symbol?

![png-transparent-gift-logo-ukraine-tshirt-coat-of-arms-of-ukraine-trident-national-symbols-of-ukraine-clothing-zazzle](https://github.com/FortAwesome/Font-Awesome/assets/141042529/dac80a7f-b1f8-4eaf-990b-34d3d4154bd5)

thanks in advance

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Comment by tagliala** [comment]
Ref: #20288
