### ISSUE TITLE
Icon request: Tag + Dollar Sign

### ISSUE THREAD

**Issue by wrm0925** [FortAwesome/Font-Awesome#19864]
Tag icon with dollar sign inside like below:
<img width="90" alt="Screenshot 2023-08-17 at 10 52 49 AM" src="https://github.com/FortAwesome/Font-Awesome/assets/142518570/7d0e4138-4424-43cd-b97e-fd9be1a4d479">

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that **in a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/199/

Since `far fa-tag` is not available in Font Awesome Free, but in FA Pro it is possible to use stack: https://jsfiddle.net/tagliala/bfa6uhse/202/

Ref:
- https://fontawesome.com/v6/docs/web/style/power-transform
- https://fontawesome.com/docs/web/style/mask
- https://fontawesome.com/docs/web/style/layer
- https://fontawesome.com/v6/docs/web/add-icons/icon-wizard#contentHeader

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
