### ISSUE TITLE
Icon request: user-tie-slash

### ISSUE THREAD

**Issue by achiyat** [FortAwesome/Font-Awesome#19870]
Please add or create a "user-tie-slash" icon

**Comment by achiyat** [comment]
I would appreciate an update to the email: achiya308@gmail.com

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that **in a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo:
- https://jsfiddle.net/tagliala/bfa6uhse/204/

**Heads-up!** Pro customers can also implement this icon with the [Icon Wizard](https://fontawesome.com/v6/docs/web/add-icons/icon-wizard#contentHeader)

<img width="1079" alt="image" src="https://github.com/FortAwesome/Font-Awesome/assets/556268/a7f81d74-19f9-4582-bf55-438f3f3c85cf">

Ref:
- https://fontawesome.com/v6/docs/web/style/power-transform
- https://fontawesome.com/docs/web/style/mask
- https://fontawesome.com/docs/web/style/layer
- https://fontawesome.com/v6/docs/web/add-icons/icon-wizard#contentHeader

**Comment by tagliala** [comment]
> I would appreciate an update to the email: REDACTED

In order to receive notifications, please subscribe to this issue on github and make sure to enable github notification.

I will remove the comment with your email address because it is considered private information

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
