### ISSUE TITLE
Icon request: truck-check

### ISSUE THREAD

**Issue by Flinsch** [FortAwesome/Font-Awesome#19871]
In our software we have delivery trips. Each trip delivers to several destinations (trip stops). In the trip overview we have different icons to display the respective delivery status also in visual form (not only in text): just `truck` for pending deliveries; `truck-fast` for the current next trip stop or `truck-ramp-box` if the actual delivery is already in progress; `truck-clock` in case of a delay; or `truck-bolt` in case of an unspecific problem (another new icon `truck-question` might be good here too). But we are still missing an icon for a completed delivery. A new `truck-check` would be great here!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that **in a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo:
- (mask) https://jsfiddle.net/tagliala/bfa6uhse/207/

Ref:
- https://fontawesome.com/v6/docs/web/style/power-transform
- https://fontawesome.com/docs/web/style/mask
- https://fontawesome.com/docs/web/style/layer
- https://fontawesome.com/v6/docs/web/add-icons/icon-wizard#contentHeader

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
