### ISSUE TITLE
Icon request: diagram-sentence

### ISSUE THREAD

**Issue by nateclonch** [FortAwesome/Font-Awesome#19882]
There are icons for diagram, but none of them are related to sentence diagrams, which would be useful for conveying the idea of grammar and phrase/sentence structure.
![diagram-sentence](https://github.com/FortAwesome/Font-Awesome/assets/8261341/5a5717bc-149f-4548-a761-fb9bde5c62dd)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
