### ISSUE TITLE
Icon request: Sports

### ISSUE THREAD

**Issue by deepak-kumar-swain** [FortAwesome/Font-Awesome#19895]
### Use case

Need Icons for sports and stake holders like Cricket, Football, badminton, Kabaddi, Hockey, Volley Ball, Base Ball etc.

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Most of the explicitly listed icons sports are already available, both in the free and Pro sets

Ref: https://fontawesome.com/icons/categories/sports-fitness

and as requests

Ref: #19430

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Since This request does not meet our contributing guidelines for new icons (this is not a request for a single icon), I'm going to close here

**Comment by deepak-kumar-swain** [comment]
Ref: https://fontawesome.com/icons/categories/sports-fitness

Here we have icons for sports.
But its not sufficient.
As I wanted to take pro plan to use in my sports app.
I am looking for icons specifically for various sports and all related partners.
Means for cricket, Batsman icon, Bowler icon, Umpire's different sign icons.
For football, Refree, Refree with cards, Player with football etc.
