### ISSUE TITLE
Icon request: acid-splash

### ISSUE THREAD

**Issue by Arniox** [FortAwesome/Font-Awesome#19918]
Our company needs an icon that represents corrosion, acid corrosion, weather corrosion, etc.
We're a building and construction company and we need something to properly represent **Corrosion Zoning**

Something like this:
![corrosion icon svg](https://i.imgur.com/w5D6LDO.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
