### ISSUE TITLE
Icon request: icon-music-transcribe

### ISSUE THREAD

**Issue by Sporran** [FortAwesome/Font-Awesome#1995]
This icon will be of certain use to all those creating music applications permitting pitch shift (transcription). The icon can be created by simple combination of the following two icons:

icon-music
icon-resize-vertical

**Comment by MVcodeartbr** [comment]
could you provede some example?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
