### ISSUE TITLE
Icon request: icon-local-file & icon-cloud-file

### ISSUE THREAD

**Issue by sensorykaro** [FortAwesome/Font-Awesome#19967]
- file icon with a small locaction pin bottom right
- file icon with a small cloud symbol bottom right

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
