### ISSUE TITLE
Icon request: waterslide

### ISSUE THREAD

**Issue by YellowPhoenix18** [FortAwesome/Font-Awesome#19993]
Could you please make a waterslide-icon?

**Comment by mononoke813** [comment]
Greetings! I'd like to make my first ever contribution but I'm a little hesitant. Is there a specific way I go about providing a waterslide-icon? Do I screenshot from a source, like Canva? Do I make it myself? Does it need to be in black and white or is color ok?

**Comment by tagliala** [comment]
Hi @mononoke813,

thanks for your willing to help, but as per our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/6.x/CONTRIBUTING.md), at the moment we do not accept Pull Request containing icons

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
