### ISSUE TITLE
Icon request: vr-headset

### ISSUE THREAD

**Issue by BenWoodford** [FortAwesome/Font-Awesome#20010]
### Use case

Note: This is not a duplicate of `fa-vr-cardboard` or `fa-head-side-goggles`

Google Cardboard is a _very_ old bit of VR tech now, and not at all representative of the state of VR (to the point of being somewhat detrimental to people's mental image of what VR is). It'd be nice to have something a bit more up to date as a representation of VR headsets in 2023, maybe following the silhouette of the Meta Quest 2 or similar with a headstrap and such.

I know we have `fa-head-side-goggles` but when you want just the headset (e.g. showing the headset icon next to a battery icon, etc) it makes a lot more sense to have just the headset itself

### Example image

https://media.gamestop.com/i/gamestop/11107421/Meta-Quest-2-64GB - product reference

This is a great ref: https://guide-images.cdn.ifixit.com/igi/FD5mT1QrMJSsxcXV.large

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
