### ISSUE TITLE
Icon request: vr-controller

### ISSUE THREAD

**Issue by BenWoodford** [FortAwesome/Font-Awesome#20011]
### Use case

To go with the VR headset icons, having controllers would be a big help, I often find myself having to use the `fa-hand` icon to represent a controller.

Most controllers follow a fairly standard silhouette now, so there is a general opinion for "this is what a VR controller looks like", having one that also shows handedness (by not being symmetrical) would be great too for showing left/right controllers.

### Example image

Specifically _not_ this as this is an Oculus Remote from years ago: https://thenounproject.com/icon/vr-controller-4802925/ - or this, which is a PS Move controller: https://thenounproject.com/icon/vr-controller-1819034/

These are a great example as they're not brand-specific (HTC, Pico and Meta all follow this silhouette, ignoring the newer Quest 3 controllers which are a diversion from the norm): https://thenounproject.com/icon/hand-controller-4980320/ and they also show handedness. They're also a great example of how you could handle duotone

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
