### ISSUE TITLE
Bug: Kit Custom Icon `.fak` missing `line-height: 1;` in `.scss` and `.less` assets

### ISSUE THREAD

**Issue by Cow258** [FortAwesome/Font-Awesome#20044]
### Bug description

The class `.fak`, `.fa-kit` are missing the `line-height: 1;`,
that cause the font icon vertical height slightly off.

### Reproducible test case

Just download it from Pro Plan Kit

### Screenshots

![image](https://github.com/FortAwesome/Font-Awesome/assets/14261588/cf3c18c6-3925-4310-8f41-c9face1950a4)
![image](https://github.com/FortAwesome/Font-Awesome/assets/14261588/c885ed95-b7c5-4695-8bfa-7c844a2e9fd5)
![image](https://github.com/FortAwesome/Font-Awesome/assets/14261588/d87d9c4f-b82b-423e-96a5-b8270971f22c)

### Font Awesome version

v6.5.1

### Serving

Kit, Self-hosted

### Implementation

CSS

### Browser and Operating System

Any browser and OS

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by robmadole** [comment]
@mlwilkerson I think we are missing the line-height. Do you recall any reason why we left this out when working on Kits?

**Comment by mlwilkerson** [comment]
@robmadole no, I don't recall any such reason. If it's missing, then I think it was just a mistake.

**Comment by mlwilkerson** [comment]
On closer examination, this issue is more specific, and more subtle. It's specific to SCSS and Less because of how `line-height` is handled differently in those assets.

The `css/custom-icons.css` does appear to have `line-height: 1` in the `.fak` rule. As the screenshots above show in the original report, it's the `custom-icons.scss` asset that lacks `line-height: 1` in its `fak` rule.

In other words, the reported problem is with the SCSS assets, not the CSS assets.

However, it might not be the case that there _should be_ a `line-height: 1` in the `fak` rule of `custom-icons.scss`.

Compare to the corresponding rules in official familyStyle assets, like the `fas` rule in `solid.scss`. It also lacks `line-height: 1`.

For the official familyStyles, however, there's a `line-height: 1` being assigned in `_core.scss` (as shown in the screenshot above). And there's also something happening with `line-height: 1` in `_mixins.scss` via the extension of the `fa-icon` mixin. But there's no entry for `.fak, .fa-kit` in `_mixins.scss`.

There's a _similar_ (though not identical) pattern for the Less case. What's similar is that `line-height: 1` comes from the `fa-icon` mixin via `_mixins.less`. What's different is that in `_core.less`, there's no `line-height: 1` being assigned to the official familyStyles either. So they all get their `line-height: 1` default from the rules in `_mixins.less`, and since there's no rule in `_mixins.less` for `.fak,.fa-kit`, it lacks the default `line-height: 1` in the Less case as well.
