### ISSUE TITLE
Icon request: Kiosk (info point / device / terminal)

### ISSUE THREAD

**Issue by m-gallesio** [FortAwesome/Font-Awesome#20057]
### Use case

We want to track whether a user has registered to an application via an own mobile device or a kiosk. We are not sure yet if we are going to use an icon to display this information; for now we plan to use one of the `tablet` icons.

This is not the same as https://github.com/FortAwesome/Font-Awesome/issues/12460 which covers food stands and the like.

### Example image

A simple image search: https://duckduckgo.com/?q=kiosk+terminal&t=ffab&iar=images&iax=images&ia=images

Some ugly SVG mockups:
![kiosk](https://github.com/FortAwesome/Font-Awesome/assets/46478501/5fdb40b1-e1ae-4ae7-9b21-ee70787e8ecd)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
