### ISSUE TITLE
Icon request: PKR currency

### ISSUE THREAD

**Issue by imsargana** [FortAwesome/Font-Awesome#20058]
### Use case

Green color represented as PAK and half round P and red line consider as R, lower part of R is showing like road to be come bigger wish to our currency rise time to time.

### Example image

![PKR SIGN](https://github.com/FortAwesome/Font-Awesome/assets/154630454/cbac7868-db99-4036-83dc-cda1bf7e700e)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Is there any official reference of this currency symbol (like wiki or government official website)?

Does it have a unicode character?

As far as I can see from wiki, there are no unicode symbols and PKR is represented as `Re` or `Rs`.

We already have `Rs`: https://fontawesome.com/icons/rupee-sign?f=classic&s=solid

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
