### ISSUE TITLE
Icon request: soya

### ISSUE THREAD

**Issue by jarntz** [FortAwesome/Font-Awesome#20086]
### Use case

It would be great to have a soya bean icon in Font Awesome, especially for using in a design that is created for an app or website dedicated to food or health.

### Example image

![image](https://github.com/FortAwesome/Font-Awesome/assets/60695875/5064bcdb-53e8-4fac-a1ce-a0491852cb8f)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/peapod?f=classic&s=solid)
