### ISSUE TITLE
Icon request: building-plus

### ISSUE THREAD

**Issue by mfiworklife** [FortAwesome/Font-Awesome#20095]
A building/house with a plus icon. If you fx want to add a department or company to a selection.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
