### ISSUE TITLE
Icon request: Cryptocurrency (generic)

### ISSUE THREAD

**Issue by Diwannist** [FortAwesome/Font-Awesome#20105]
### Use case

This icon could be used to visually represent a generic cryptocurrency payment method.

### Example image

Remove the blue outside.
![polymathhero_cryptocurrency_symbol_C_ed7cc99c-5e26-4461-a190-d8a8aedac5fb](https://github.com/FortAwesome/Font-Awesome/assets/32558483/0a3ac1e5-6783-423d-9d2a-47b5081acb2c)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment]
Hi,

so this is a request for a "generic" criptocurrency icon, correct?

**Comment by Diwannist** [comment]
Yes, that is correct! Thank you for responding!

On Feb 8, 2024, at 2:23 PM, Geremia Taglialatela ***@***.***> wrote:

﻿

Hi,

so this is a request for a "generic" criptocurrency icon, correct?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
