### ISSUE TITLE
Icon request: CV (text to represent Curriculum Vitae)

### ISSUE THREAD

**Issue by gungorMetehan** [FortAwesome/Font-Awesome#20112]
### Use case

A "CV" (curriculum vitae) icon would be nice for personal blogs/sites.

### Example image

![cv](https://github.com/FortAwesome/Font-Awesome/assets/102655648/a2e7ea06-ddf3-44d3-a207-99cb102d7988)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`C` and `V` icons are available as individual icons in FA Free. It is possible to combine them to obtain the requested icon

Also:
- there was a previous request for a "CV" icon which has been addressed by file-user: https://github.com/FortAwesome/Font-Awesome/issues/19542#issuecomment-1411765427
- we do our best to avoid text inside icons to avoid localization issues

I'm keeping this request open, but please consider alternatives

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
