### ISSUE TITLE
Icon request: Screen Aspect Ratio

### ISSUE THREAD

**Issue by ErikFunke** [FortAwesome/Font-Awesome#20114]
### Use case

Icons for different screen / image sizes would be nice

### Example image

![1_1](https://github.com/FortAwesome/Font-Awesome/assets/79810577/8efdf9e1-024c-4ee7-bc17-53f35d06e044)
![9_16](https://github.com/FortAwesome/Font-Awesome/assets/79810577/a46c1873-d708-41d9-bf6f-f94b9a589d75)
![16_9](https://github.com/FortAwesome/Font-Awesome/assets/79810577/d485ccf9-63d1-4aff-b543-ce151804a7a2)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
