### ISSUE TITLE
Icon request: Stenograph

### ISSUE THREAD

**Issue by cmjone171** [FortAwesome/Font-Awesome#20150]
### Use case

An icon similar to the examples below can be used in web design to represent the stenographer profession which includes court reporters and CART captioners.

### Example image

![istockphoto-1389027491-1024x1024](https://github.com/FortAwesome/Font-Awesome/assets/96886839/2ec436ba-5ad1-4e38-ac87-89245562da67)

This example was created by lastspark from <a href="https://thenounproject.com/browse/icons/term/shorthand/" target="_blank" title="shorthand Icons">Noun Project</a>: 
![noun-shorthand-2360512](https://github.com/FortAwesome/Font-Awesome/assets/96886839/2ce715a9-cf53-429e-a764-ba7fe445b94a)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
