### ISSUE TITLE
Icon request: table-magnify, database-magnify, table-eye, database-eye

### ISSUE THREAD

**Issue by ALISA2291** [FortAwesome/Font-Awesome#20187]
A magnifying glass over a table or database to represent inspecting data.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
