### ISSUE TITLE
Icon request: fa-tag-plus and fa-tag-minus

### ISSUE THREAD

**Issue by liamgecko** [FortAwesome/Font-Awesome#20204]
### Use case

In our product we utilise tags regularly. We have an activity feed where all activity is shown, this includes when tags are added or removed. There are plus/minuses for loads of icons but not the tag icon :( 

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)

**Comment by liamgecko** [comment]
Hi.

I think some work is needed to the wizard before it's a viable alternative
to my request.

I thought I'd test it out with a tag with plus icon and as you can
see...far from ideal.

Liam

[image: Screenshot 2024-07-17 at 10.59.55.png]
