### ISSUE TITLE
Certain icons not being recognized in Figma

### ISSUE THREAD

**Issue by MollyPeredo** [FortAwesome/Font-Awesome#20211]
Lately, I've noticed that certain icons don't display properly in Figma. I've tried all of the basic troubleshooting and nothing is working. Please fix this, it's affecting my ability to create screens in Figma that my devs can use.

The two icons I've had the most trouble with are file-ppt and globe-pointer.

![image](https://github.com/FortAwesome/Font-Awesome/assets/132949361/5367a726-ba74-4134-95d2-17539a1d9766)
![image](https://github.com/FortAwesome/Font-Awesome/assets/132949361/80c02bc2-cc88-42f6-bafa-41b293665319)

**Comment by sensibleworld** [comment]
Hey Molly -

Those are both icons that were added relatively recently to Font Awesome, so you'll need to make sure you have the newest fonts downloaded and installed. We often recommend:

- Close all apps
- Delete old installation of Font Awesome from your font manager
- Download + install new version of Font Awesome

Deleting before installing is important so that the font manager doesn't hold on to the old cache.
