### ISSUE TITLE
Icon request: fa-wheelchair-parking

### ISSUE THREAD

**Issue by rwiersma99** [FortAwesome/Font-Awesome#20210]
I would love to add an icon for a parking with a wheelchair. I use Font Awesome to display location accessibility on a website. Could this be added?
Something like this: 
![parkeerplaats 1](https://github.com/FortAwesome/Font-Awesome/assets/46010166/d720b61c-81b1-4bea-94dc-c64d0cf85ac4)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
