### ISSUE TITLE
Bug: Changing icon style doesn't work - shows undefined

### ISSUE THREAD

**Issue by kimey-robertson** [FortAwesome/Font-Awesome#20311]
### Bug description

When you click on an icon on the website, you are given the option to choose solid/regular/light/duotone. If you click on any of these, the UI bugs out and disappears, and the class name shows an undefined. 

It's not possible to use any other icon type other than solid

### Reproducible test case

https://fontawesome.com/v5/icons/info-circle?f=classic&s=solid

### Screenshots

![Screenshot 2024-07-25 at 9 46 59 PM](https://github.com/user-attachments/assets/74085398-273f-4dfc-962f-5fad837a70bb)
![Screenshot 2024-07-25 at 9 46 11 PM](https://github.com/user-attachments/assets/5a75bd73-9d2a-43e9-9cf0-9cd009c9cb6e)

### Font Awesome version

v6

### Serving

Kit, Other (as specified in the bug description)

### Implementation

Other (as specified in the bug description)

### Browser and Operating System

Chrome MacOS

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Confirmed, thanks.

@robmadole this is a little bit tricky

> https://fontawesome.com/v5/icons/info-circle?f=classic&s=solid

Does not work directly, because there is a bug on url rewrite when navigating the docs

So the steps are the following

1. Go to https://fontawesome.com/v5/search?q=info-circle&o=r
2. Click on `info-circle`
3. 🐞 First bug here! The link in the navbar changes to `https://fontawesome.com/v5/icons/info-circle?f=classic&s=solid`, which is not valid
4. When the modal appears, click on `regular` style
5. 🐞 Second bug (the one reported) here


I do not see errors in the console

**Comment by ej2** [comment]
This turned out to be an issue with the search index. The index has been rebuilt and the issue resolved.

**Comment by kimey-robertson** [comment]
> This turned out to be an issue with the search index. The index has been rebuilt and the issue resolved.

Thanks for fixing it!
