### ISSUE TITLE
Icon request: icon-accented-non-latin-letters

### ISSUE THREAD

**Issue by Miazebra** [FortAwesome/Font-Awesome#20349]
It would be nice to have the letter Å, Ä, Ö as icons :)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to consider this request as a subset of #18831

At the moment, that request has been declined, but I still think that the request should extend to all non-latin letters (at least) and kept open, even if we do not have the resources of working on this (that's a massive amount of icons)

Closing here, also because this request does not meet our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+), but feel free to comment if I've missed something
