### ISSUE TITLE
Icon Request: icon-byz-music

### ISSUE THREAD

**Issue by mcolburn** [FortAwesome/Font-Awesome#2041]
Thank you for _awesome_ icons!  We are developing a worldwide resources for Eastern Orthodox Christian music, which often makes use of Byzantine notation.  The icon-music icon is great for scores that are in Western music.  Ideally, we would like an icon that is immediately recognizable as representing the Byzantine notation.  Attached is a graphic that shows what we would like.  Thanks very much for considering our request!
![icon-byz-music](https://f.cloud.github.com/assets/1334217/1221461/dd78401c-26ec-11e3-9eb9-9bda065e467e.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
