### ISSUE TITLE
Icon Request: icon-relationship (icon-people-network)

### ISSUE THREAD

**Issue by glennelliott72** [FortAwesome/Font-Awesome#2079]
Would be great to have a Font Awesome icon that represents a relationship. It could be an image of two or three people with links between them a bit like this: http://www.symplicity.com/assets/Icon_-_Plugins_-_People_Network.png

My usage is for a nav bar link to a page in a CRM application that shows a network diagram of how various contacts relate to one another.

Thanks, Glenn.

**Comment by jmfarp2011** [comment]
+1 > need something to show relationships between objects, not just people. A simple 3-4 vertices force-graph type icon. Similar to the sitemap icon, but not hierarchical.

**Comment by vira-lytvyn** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
