### ISSUE TITLE
Icon request: friends

### ISSUE THREAD

**Issue by LouiseDD** [FortAwesome/Font-Awesome#2159]
Hi

Would love a friends icon PLEASE. Something like two people holding hands or hugging ? 

THANK YOU :)

**Comment by tekamolo** [comment]
Ok but there is already a request for the "friends" tag at least

https://github.com/FortAwesome/Font-Awesome/issues/2883

**Comment by dabaliyan** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
