### ISSUE TITLE
Icon request: icon-3D Render

### ISSUE THREAD

**Issue by AdrianB86** [FortAwesome/Font-Awesome#2179]
Hi,

Thanks for the great work. I have 4 icons that if you could create icons out of that would be incredible!

Here is 1 of 4.

3D Render
![3d render-02](https://f.cloud.github.com/assets/5740579/1375663/eb64978c-3a85-11e3-9b2b-b76335ff5f91.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome! [Take a look at it here.](https://fontawesome.com/icons/cube?f=classic&s=solid)
