### ISSUE TITLE
Icon request: icon-Motion Graphics

### ISSUE THREAD

**Issue by AdrianB86** [FortAwesome/Font-Awesome#2181]
Hi,

Thanks for the great work. I have 4 icons that if you could create icons out of that would be incredible!

Here is 3
![motion graphics-02](https://f.cloud.github.com/assets/5740579/1375728/ea72ee68-3a86-11e3-85c8-9c322dd7eca7.png)
 of 4.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
