### ISSUE TITLE
Icons request: going by industry

### ISSUE THREAD

**Issue by loginetsolutions** [FortAwesome/Font-Awesome#2248]
Hi,
First of all thanks for Font Awesome. It's a nice one and I'm currently using it.
Personal, I need more trucking related suck as: container, trailer, driver, dispatcher, manager, tire, garage and so on. It will be nice to have icons and match the existing truck and road icons. Also, the financial ones: expense, asset, quote, rate, invoice, item, and so on.

My request is about going by industry. 
http://www.istockphoto.com/search/lightbox/7986599/#1c92d0be
We all build websites in different industry: education, dentist, cooking, games, trucking, directories, software etc.

![stock-illustration-21964382-black-trucking-icons](https://f.cloud.github.com/assets/4643440/1410214/1770fcc6-3da1-11e3-97c0-45da3e8556d1.jpg)

Thanks and best regards,
Adrian

PS: We have the medical icons already. Why not the financial ones?

**Comment by tagliala** [comment]
Hi,

FA 5.0 Pro comes with icon packs. There are sports and logistic packs. Some of the icons are also included in FA5 Free.

Anyway, closing here because of https://github.com/FortAwesome/Font-Awesome/issues/2248#issuecomment-32591193

PS: FA 5 Pro backers and users could request icon categories under the FA5Pro repo
