### ISSUE TITLE
Icon request: icon-download-mp3

### ISSUE THREAD

**Issue by mshgna** [FortAwesome/Font-Awesome#2339]
While the general download icon is great, it would be nice to have an icon for specifically downloading/opening MP3 as well (and maybe other file types, WAV, OGG, or even PDF, etc.)

![image](https://f.cloud.github.com/assets/5852255/1466059/698cdd1e-456b-11e3-9fa2-853965efa150.png)

![image](https://f.cloud.github.com/assets/5852255/1466074/8496b1f2-456b-11e3-9069-a44f93ca116d.png)

Could also have a downward arrow added as well coming out the bottom, similar to this: 
![image](https://f.cloud.github.com/assets/5852255/1466106/dce41ade-456b-11e3-91b1-80c78c3be3d7.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/file-mp3?f=classic&s=solid)
