### ISSUE TITLE
Icon request: torrent or peer-to-peer

### ISSUE THREAD

**Issue by dch** [FortAwesome/Font-Awesome#2355]
Lots of legitimate use cases for download links / icons on desktops and browsers, also mobile buttons in future.

Here are a couple ideas I had for a project I am working on. They are loosely based on an RSS broadcast icon & some custom bar bell style things.

![pipestream](https://f.cloud.github.com/assets/284368/1480153/ad4344d2-469f-11e3-82c1-5e3699f9ff81.png)
![ansible](https://f.cloud.github.com/assets/284368/1480154/b12dc842-469f-11e3-90f0-db59675d498b.png)

My favourites are still the original hand-drawn pen / ink ones, black & white looks nice.

**Comment by martindale** [comment]
+1 on a generic torrent icon.  It is needed.

**Comment by dakt** [comment]
+1

**Comment by Crob0** [comment]
+1

**Comment by tryton-vanmeer** [comment]
+1

**Comment by Inumedia** [comment]
+1 for peer to peer icon

**Comment by martindale** [comment]
@dch any updates on your project?  If this is an example of your work, we'd love to see more!

**Comment by pahwaranger** [comment]
+1 for icon

**Comment by AaronActu** [comment]
+1 'cause I needed 👍

**Comment by ozanbatuhanceylan** [comment]
+1 for p2p icon

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
