### ISSUE TITLE
Icon Request: fa-langflag-[languagecode]

### ISSUE THREAD

**Issue by thotzl** [FortAwesome/Font-Awesome#2364]
"flags" for multilingual websites.

for example:

fa-langflag-en
![en](https://f.cloud.github.com/assets/1067907/1490656/2ac55fa4-4799-11e3-8809-60e0520079ef.png)

fa-langflag-de
![de](https://f.cloud.github.com/assets/1067907/1490657/2ec825aa-4799-11e3-9888-d56a33b0d21f.png)

fa-langflag-fr
![fr](https://f.cloud.github.com/assets/1067907/1490658/32f08da2-4799-11e3-8f53-22b0ad733f66.png)

edit:
used Sansation Bold for the icons:
http://www.fontsquirrel.com/fonts/sansation?q%5Bterm%5D=sansation&q%5Bsearch_check%5D=Y

**Comment by bennyp123** [comment]
+1

**Comment by Crissov** [comment]
I remember icons looking like `((en))`, `⸨de⸩` or `⪫fr⪪` were quite common once, cf. 🔊 🗣.

**Comment by morgzz** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
