### ISSUE TITLE
Icon Request: fa-envelope-lock

### ISSUE THREAD

**Issue by lokeshnaicker** [FortAwesome/Font-Awesome#2371]
Need a icon for Secure Email (ie envelop and lock)

**Comment by aethior** [comment]
Alternative name `envelope-lock`.

**Comment by tagliala** [comment]
**In a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/185/

**Heads-up!** Pro customers can also implement this icon with the [Icon Wizard](https://fontawesome.com/v6/docs/web/add-icons/icon-wizard#contentHeader). It's just one click

![image](https://user-images.githubusercontent.com/556268/221375686-6265b1a4-3a8f-45ea-b5f8-90647e89b3b3.png)

Ref:
- https://fontawesome.com/v6/docs/web/style/power-transform
- https://fontawesome.com/docs/web/style/mask
- https://fontawesome.com/docs/web/style/layer
- https://fontawesome.com/v6/docs/web/add-icons/icon-wizard#contentHeader

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
