### ISSUE TITLE
Icon request: icon set for driving school

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#2391]
icon set for use on a driving school site.
![stock-vector-european-drivers-license-categories-symbols-128325800](https://f.cloud.github.com/assets/3840400/1506314/602244d8-491e-11e3-9a57-a87bcb87be2f.jpg)

**Comment by dpfem** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
