### ISSUE TITLE
Icon Request: fa-smallLetter

### ISSUE THREAD

**Issue by Nicharee** [FortAwesome/Font-Awesome#2394]
Hi, you added a capital letter" (i.e. fa-font) already, but users may want to differentiate (and indicate by using font awesome icons) between "capital" and "small" letters. Hence I suggest/request to also add a "small a" in addition to the already existing "capital A" (I suggest you use the same font for the "small a" as you are using for the "capital A" already).

Thanks

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/font-case?f=classic&s=solid)
