### ISSUE TITLE
Icon Request: icon-microphone-listening

### ISSUE THREAD

**Issue by tksfz** [FortAwesome/Font-Awesome#2425]
Hi I'd like an animated version of the existing icon-microphone.  It should be animated to indicate that the microphone is turned on and the web page is listening.

This is to be used in conjunction with the upcoming JavaScript Speech Recognition API.  The speech API allows you to hook into various speech recognition events.  You can see the existing demo at:

https://www.google.com/intl/en/chrome/demos/speech.html

It would be natural to use icon-microphone for the microphone.  And to use an animated microphone when the speech recognition is listening.

Thanks.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
