### ISSUE TITLE
Icon request: fa-printers

### ISSUE THREAD

**Issue by EnricoEls** [FortAwesome/Font-Awesome#2432]
Good day Font-Awsum.

First off thanx for the great icons... helps a lot with my development work.

I did a search for a print icon for multiple files but didn't find any (unless I was blind again). The reason I would like such an icon is that in a few cases I had to make a distinction between printing a single file or multiple files and was limited in using only an icon, no button with text and then an icon for example. It would be great if you could create something in this line for use in other projects where such distinction has to be made. As stated above this is the only place were this type of icon will be used so if you decline the creation of such an icon it would be understandable, I can't expect you guys making an icon for a single requester for a single reason, I mean we are all busy people after all.

I'm sorry for the weak design of the attachment, it was made in paint and I'm not really a painter =). Also excuse any grammar or spelling mistakes, its not my best area.

Regards E. Els.

![untitled](https://f.cloud.github.com/assets/4813756/1561179/25c32b6a-5029-11e3-85ee-fce5497ef34b.jpg)

**Comment by ssc-hrep3** [comment]
Just use some css (position: absolute, font-size, etc.) and overlap two or three of these printer icons, as they do not differ from each other. Then you can use the text-shadow property to add a font shadow.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
