### ISSUE TITLE
Icon Request: chatty and sassy

### ISSUE THREAD

**Issue by thejart** [FortAwesome/Font-Awesome#2459]
Here's an example of what they look like:
http://www.succeedwithaurora.com/wp-content/uploads/2011/09/IMG_00021.jpg

Chatty is on the left and Sassy is on the right.  I assume you'll be dropping everything to make this happen.  Thank you for your awesome fonts and efforts.

Jarrett
/huge fan

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
