### ISSUE TITLE
Icon Request: icon-magazine

### ISSUE THREAD

**Issue by ingernet** [FortAwesome/Font-Awesome#2503]
There's one for book, which is great - but I would like one that looks more like an open magazine. Kind of like this, except maybe more pronounced curve to the page edges - http://us.123rf.com/400wm/400/400/bryanjhall/bryanjhall1008/bryanjhall100800003/7742690-open-magazine-with-blank-white-pages-on-a-white-background-file-includes-paths-for-each-page.jpg

**Comment by dijim** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by Pseudo-Nym** [comment]
+1

**Comment by ersinyilmaz** [comment]
+1

**Comment by dngunraj** [comment]
+1

**Comment by leyamcir** [comment]
+1

**Comment by kapilsharma** [comment]
+1

**Comment by hanoii** [comment]
+1

**Comment by cmendoza-hds** [comment]
+1

**Comment by dulledesign** [comment]
+1

**Comment by otplsteve** [comment]
+1

**Comment by vivianyulunko** [comment]
+1

**Comment by bethmdx** [comment]
+1, but simpler suggestion
![screen shot 2015-12-17 at 14 44 20](https://cloud.githubusercontent.com/assets/16337995/11898102/3cc0c19a-a58d-11e5-968c-30b95c984986.png)

**Comment by lukemcd** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by jamiechong** [comment]
+1

**Comment by sanek4life** [comment]
+1

**Comment by WakanaMatsumoto** [comment]
+1

**Comment by seezee** [comment]
+1. Would be great for a blog index.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome! [Take a look at it here.](https://fontawesome.com/icons/book-open?f=classic&s=solid)
