### ISSUE TITLE
Icon Request: delivery-onlineshop

### ISSUE THREAD

**Issue by ADESATOS** [FortAwesome/Font-Awesome#2518]
Hello,

I'd like to request two icons for use in onlineshops:
home delivery and delivery free use.

You can contact me for further questions. 

Thanks
Marc

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
