### ISSUE TITLE
Icon Request: fa-full-page

### ISSUE THREAD

**Issue by RichardAlan** [FortAwesome/Font-Awesome#2643]
My web site has a sidebar which can optionally be hidden. I can use the fa-columns icon to show the page with a sidebar although it's a bit confusing as the vertical line is in the middle. I would like to request an icon like fa-columns but with no center vertical. I could then use this to switch between having and not having a sidebar.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
