### ISSUE TITLE
Icons Request: fa-jangada

### ISSUE THREAD

**Issue by pisandelli** [FortAwesome/Font-Awesome#2660]
Hey guys! You're really aewsome! Cheers from Brazil!
Well, my team had the ideia for an "eiffel tower" icon because we have some guys working in Brazil and other in Paris. So we thought that was very nice to put an eiffel tower in the adress of Paris. The other part of the team is in Fortaleza (Brazil), so we thought a symbol from here could be very nice to put in our adress. We're on the beach and the fisherman uses an especific boat we call "jangada". It will be so nice see an icon like this! :smile:
And.. why not make an icon set with the world symbols... eiffel, jangada, Christ (Rio), Liberty Statue, Pyramids, etc... it will be very nice! :+1: 

Here's examples of Jangada:
Google Search: http://goo.gl/OF4Xk5

![jangada](https://f.cloud.github.com/assets/1986634/1817852/61ac7354-6fcb-11e3-8785-6cd8dd7cdd02.gif)

![jangada002](https://f.cloud.github.com/assets/1986634/1817851/4b729b86-6fcb-11e3-96b5-3f529c2cdec2.jpg)

THANK YOU SO MUCH!!!

**Comment by G-Driver** [comment]
+1 why not :)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
