### ISSUE TITLE
icon request : algorithm scaling order

### ISSUE THREAD

**Issue by ryneches** [FortAwesome/Font-Awesome#2689]
There are a lot of situations where one has the option of selecting several different algorithms they might apply to the same problem, and where the user is billed for the run time (e.g., services like DNANexus). It would be really wonderful to have some icons to quickly (and graphically) communicate to the user how the different algorithms tend to scale. 

Constant
Linear
Log(n)
n Log(n)
Quadratic
Polynomial
Exponential
Superexponential

It's a bit niche perhaps, but this is the sort of concept that is often awkward and confusing to succinctly explain in words, but where a well designed icon makes it clear what is meant.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
