### ISSUE TITLE
Icon Request: fa-blank or fa-none or fa-empty

### ISSUE THREAD

**Issue by RichardAlan** [FortAwesome/Font-Awesome#2729]
I would like to have a blank icon that I could use for spacing purposes. I realize this functionality could be achieved in other ways but to simplify my coding this would really help. 

Here's an example using AngularJS. 

```
    <span class="fa" data-ng-class="{fa-blank: row.current == true, fa-spinner: row.current == false}"></span>
```

Having the ability to swap in the fa-blank icon makes it very clear to see what's happening.

**Comment by volomike** [comment]
I tried fa-fw and that made too wide of a space. For example, imagine you have:

```
<a href="tel:123-456-7890"><i class="fa fa-phone"> Call an agent<br>
<i class="fa fa-fw"></i> 123-456-7890</a>
```

You'll find in the second line after the `BR` that the blank icon is too wide in that spacing.

There's a better fix:

```
<a href="tel:123-456-7890"><i class="fa fa-phone"> Call an agent<br>
<i class="fa fa-phone fa-blank"></i> 123-456-7890</a>
```

Then, add a class in your CSS like so:

```
.fa-blank
{
visibility:hidden !important;
}
```

**Comment by vahidhedayati** [comment]
```
.hide-icon {
  opacity:0;
}

```

You can add another class which is declared above to where it is called - the issue  with above `visibility:hidden !important;` is you get padding that would be with image etc in this frame work I am using and the opacity way keeps everything as is if it was there.

**Comment by mohsinworld** [comment]
This code helped me <i class="fa fa-blank"></i>

**Comment by kotimalli** [comment]
<i class="fa fa-blank"></i>

**Comment by bobvandevijver** [comment]
@volomike You need to apply the `fa-fw` on every icon in your list (which you should do anyways)

**Comment by eteisman** [comment]
I'm using Volomike's solution, and it works. This also seems elegant.

**Comment by allexiusw** [comment]
> I tried fa-fw and that made too wide of a space. For example, imagine you have:
> 
> ```
> <a href="tel:123-456-7890"><i class="fa fa-phone"> Call an agent<br>
> <i class="fa fa-fw"></i> 123-456-7890</a>
> ```
> 
> You'll find in the second line after the `BR` that the blank icon is too wide in that spacing.
> 
> There's a better fix:
> 
> ```
> <a href="tel:123-456-7890"><i class="fa fa-phone"> Call an agent<br>
> <i class="fa fa-phone fa-blank"></i> 123-456-7890</a>
> ```
> 
> Then, add a class in your CSS like so:
> 
> ```
> .fa-blank
> {
> visibility:hidden !important;
> }
> ```

Nice solution...

**Comment by trebor** [comment]
i'd like to chime in here, on a closed issue so perhaps i am shouting into the wind, but there REALLY should be an `fa-blank` or some such icon.  all these other solutions WORK, but require extra code and special logic.  and even in this one issue we see people choosing different solutions, and thus no standard approach.

`fa-blank` is a clean uniform way to solve this problem.  no one needs to add extra random CSS or conditional logic anywhere.  it would promise to behave just like every other icon in terms of sizing/scaling.

one and done.

**Comment by jessycormier** [comment]
> i'd like to chime in here, on a closed issue so perhaps i am shouting into the wind, but there REALLY should be an `fa-blank` or some such icon. all these other solutions WORK, but require extra code and special logic. and even in this one issue we see people choosing different solutions, and thus no standard approach.
> 
> `fa-blank` is a clean uniform way to solve this problem. no one needs to add extra random CSS or conditional logic anywhere. it would promise to behave just like every other icon in terms of sizing/scaling.
> 
> one and done.

I would like to add to this with another context which is using the [angular-fontawesome](https://github.com/FortAwesome/angular-fontawesome) tool, where simply using the idea of "fa-fw" isn't available in the traditional context.

A use cases where blank my be more useful than maintaining customized CSS codes for particular use cases:

When managing a menu that may or may not have icons for each item. We could simply apply a blank icon with `fa-fw` (or in my case `[fixedWidth]="true"`) and all words in the menu would stay aligned in an easy-to-manage way without introducing relative positioning or other margin alignment tricks (technically slows down page rendering performance but in most cases is too small of a scale to matter)

EDIT

I should also offer a solution for anyone that may be in a similar situation.

Since Font Awesome Icons respect text color changes, you're able to use a simple icon like `fa-square` and match the text color to the background color. Not useful in all situations but for some may resolve the issue.

```html
<fa-icon
    class="text-light"
    [icon]="faSquare"
    [fixedWidth]="true">
</fa-icon>
```
_Above example is in a bootstrap style system and on a card with a bg-light allowing the icon to be hidden_ 

```html
<i class="fa-solid fa-square text-light"></i>
```
_Above example would be normal use case for Font Awesome._

**Comment by timtucker-dte** [comment]
What's the recommended approach here with Font Awesome v7 now that fixed width is the default for icons and fa-fw is deprecated?
