### ISSUE TITLE
Icon request: fa-bullhorn-reverse

### ISSUE THREAD

**Issue by saeed3234** [FortAwesome/Font-Awesome#2777]
Hi 
I'm interested in using fa-bullhorn in my website with RTL language. I need the icon reversed so that its loudspeaker - if that is the right term to use - is facing the text in front of it not the mouthpiece side. Some thing like the attached photo. 
How can I do that? Should a new icon be developed? Thanks in advance!
![fa-bullhorn](https://f.cloud.github.com/assets/6469688/1972504/9eaa84f8-8349-11e3-9b5f-5ae83c9e5c04.gif)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
