### ISSUE TITLE
Icon Request: fa-dogecoin

### ISSUE THREAD

**Issue by tim-peterson** [FortAwesome/Font-Awesome#2822]
As seen at [Reddit](http://reddit/r/dogecoin) and other places, it would be cool if a "Ɖ" icon existed for Dogecoin (`fa fa-doge`).

Dogecoin is growing in popularity quite fast and so having an icon for it would make for a nice counterpart to FontAwesome's Bitcoin icon (`fa fa-btc`).

**Comment by lcurrit** [comment]
+1

**Comment by Henrycobaltech** [comment]
+1

**Comment by snooz** [comment]
+1

**Comment by mjarlund** [comment]
+1

**Comment by xxxwww** [comment]
+1

**Comment by stonary** [comment]
+1

**Comment by Baker** [comment]
+1

**Comment by Manaiakalani** [comment]
+1 It's been two years! Can this be implemented?

**Comment by qsypoq** [comment]
:+1:

**Comment by sikfeng** [comment]
+1

**Comment by raistlinthewiz** [comment]
no more needed any more - doge is already dead lol

**Comment by kode54** [comment]
Doge is still alive and kicking as far as networks go, and has managed to keep a relative value in BTC that keeps it at a fairly consistent level relative to non-Monopoly money.

**Comment by Manaiakalani** [comment]
+1 bump to see this implemented! :)

**Comment by Pulsar35** [comment]
+1 ♥

**Comment by G33kNoob** [comment]
up please

**Comment by DamianPilot382** [comment]
Much upvote
Please add
Amaze

**Comment by mdrideout** [comment]
Another year, another upvote!

**Comment by zaridan** [comment]
+1 - Time for the Ð to be added, pretty please.

**Comment by DreamingCoders** [comment]
@robmadole

**Comment by cyb3rs3ntry** [comment]
Whelp.. Doge is the official icon for Twitter now... so let's make it happen. 👯

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
