### ISSUE TITLE
Icon Request: greek alphabet (lowercase / uppercase: 144 icons)

### ISSUE THREAD

**Issue by fredericoregateiro** [FortAwesome/Font-Awesome#2828]
Hello,

Thanks for this helpful project, it's really well done.

There are several icons that i think shoulb be part of this project, the greek alphabet. I'm a mathematician and the greek letters are always needed.

There are others icons that could be added like the mobius strip, the infinite symbol and many many others.

Thanks,
Frederico

**Comment by tagliala** [comment]
Temporary labeled as wontfix

**Comment by nwhitmont** [comment]
delta symbol needed for financial related

**Comment by SorenSaket** [comment]
+1

**Comment by My1** [comment]
if the greek alphabet is too much then why are some of them in FA?

just curious, nothing more

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
