### ISSUE TITLE
Icon Request: madman

### ISSUE THREAD

**Issue by Tidus79CSIS** [FortAwesome/Font-Awesome#2868]
Hi,
I'm developing a medical application where I need to be able to show the person's details such as if he/she has psychic disorders. It would be convenient to have an icon such as a head with a funnel to show that. 
Examples : http://www.vipsantereunion.com/00_smiley/smiley_fou-entonnoir.gif
http://a400.idata.over-blog.com/278x300/4/03/26/83/1/Peillon.jpg
Thank you in advance for considering my request.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
