### ISSUE TITLE
Icon request: icon-crowns (currency)

### ISSUE THREAD

**Issue by andersvinther** [FortAwesome/Font-Awesome#2902]
A currency icon for "crowns" would be great.

More info: https://en.wikipedia.org/wiki/Crown_%28currency%29

The symbol of crown is usually "kr". Some countries use another symbol for it like Íkr, -, Kč, Sk. Various names for crown depend on official language of country:

```
Czech and Slovak: koruna
Norwegian and Danish: krone
Estonian: kroon
Icelandic and Faroese: króna
Swedish: krona
```

Thanks :-)

**Comment by DonBananos** [comment]
+1

**Comment by giulioferri** [comment]
+1

**Comment by rcosco** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
