### ISSUE TITLE
Icon request: icon-seat, icon-empty-seat

### ISSUE THREAD

**Issue by acornejo** [FortAwesome/Font-Awesome#2903]
This is nice for displaying seating tables for events, concerts, airline-style layouts, etc.

**Comment by smaspe** [comment]
+1

**Comment by pathmanabhankv** [comment]
+1

**Comment by juancarlosfarah** [comment]
+1

**Comment by ilanapants** [comment]
+1

**Comment by tonyacunar** [comment]
+1

**Comment by stetsontuft** [comment]
+1

**Comment by talyablum** [comment]
+1

**Comment by HATEMOVICH** [comment]
+1

**Comment by parane** [comment]
+1

**Comment by carlysmith** [comment]
+1

**Comment by TheAliAbbasi** [comment]
+1

**Comment by nsoseka** [comment]
+1

**Comment by leovogel** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
