### ISSUE TITLE
Icon Request: icon-name

### ISSUE THREAD

**Issue by ekembs** [FortAwesome/Font-Awesome#2936]
![landscapepolygons](https://f.cloud.github.com/assets/6737078/2218137/ca35f724-9a28-11e3-9397-051f3d285a5f.png)

Good day

My name is iK, I am currently using Font Awesome for a project at the University of London.

I wanted to add the following Sprite sheets (PNG images) of Polygons and Shapes to my font awesome. How do I go about doing this??

Is there a way, you could send me an updates sprite sheet

Kind Regards
IK
![patternpolygons](https://f.cloud.github.com/assets/6737078/2218147/f7771f6a-9a28-11e3-9d65-901aa0ac4ae3.png)
![pointedpolygons](https://f.cloud.github.com/assets/6737078/2218153/00e9c282-9a29-11e3-962c-4ad7529e0b90.png)
![semiuniformpolygons](https://f.cloud.github.com/assets/6737078/2218156/076ce9d6-9a29-11e3-8a3c-452fe25fd9d2.png)
![starpolygons](https://f.cloud.github.com/assets/6737078/2218157/0b12015c-9a29-11e3-96c5-f8fc2951387a.png)

**Comment by tagliala** [comment]
Hi!

Just came into this old issue because I was searching for "polygon"

We have different shapes now, so I'm going to close here

#
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to close here because this request doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Feel free to start new, individual requests following our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
