### ISSUE TITLE
Embed font files as base-64

### ISSUE THREAD

**Issue by davegandy** [FortAwesome/Font-Awesome#294]
What do folks think about base-64 encoding all of the font files and including them directly in the LESS and CSS? There are apparently implementations that will also work in IE7.
http://venodesigns.net/2010/06/17/you-got-your-base64-in-my-css/
http://stackoverflow.com/questions/1124149/is-embedding-background-image-data-into-css-as-base64-good-or-bad-practice

Advantages:
- No messing with font path, everything could be implemented in a single css file.
- Should be no funky cross-domain font loading issues in Firefox and others. Font files will get served in their proper format.

Thoughts?

**Comment by antoniobrandao** [comment]
+1

**Comment by Spangenhelm** [comment]
+1 Sorry for commenting on a closed issue but having a base64 version is really useful within certains applications like for example [TiddlyWiki](https://github.com/Jermolene/TiddlyWiki5) (a single self-modifying html file that can be used on or offline. my interest for the base64 embedded fonts comes from the fact that i can store all my datas __and__ the app itself within one single html file !)

If it is not too much work for you then we would really appreciate it !
Thank you

**Comment by adamwintle** [comment]
<rant>In mainland China its a real pain because the Chinese government partially blocks some website's HTTP requests. It seems like they block certain files (PDFs, fonts, .ZIP), etc and not just the entire websites. This problem isn't even consistent to one region of China either; in Beijing we can't load web fonts (from what we think is the local ISPs blocking some western web fonts) and in Shenzhen all web fonts load without a problem.</rant>

So yeah, it would be great if a reliable base64 version was included in the official repo instead of using third-party tools. This way its one less HTTP request and its all bundled into a CSS file, which makes the content of the font harder to trace.

**Comment by stef-w** [comment]
+1

**Comment by nextgenthemes** [comment]
You can always write a script that pulls the current woff from this repo and generates a css with the base64 font in it.

Even If I not use FA any more but +1 from me for having this in the repo. Funny how much learned since 2012.

**Comment by wavded** [comment]
+ 1

**Comment by tobibeer** [comment]
I sure wish the base64 string for the woff was part of the distro, because figuring out a tool to do the conversion can be ...difficult.

**Comment by stefanct** [comment]
+1 because it would make creating self-contained html files (e.g. with asciidoctor) way easier. i can't remember reading that argument yet...

**Comment by morganfeeney** [comment]
Wouldn't this also be a good way to avoid issues with screen readers reading out the glyph character? This solution just means an icon is only that.

**Comment by tagliala** [comment]
@morganfeeney I may be wrong but this should have no effect on screen readers. Screen reader compatibility should be addressed in the docs here: http://fontawesome.io/accessibility/

**Comment by morganfeeney** [comment]
What I was getting at is that you wouldn't need to add the markup to hide characters from screen readers. A CSS only solution would just rule it out completely as you wouldn't assign an icon to a character. Would it not?

**Comment by tagliala** [comment]
I don't know if embedding fonts as base64 would prevent screen readers to read glyphs. We had a discussion on accessibility at #6133 and nobody mentioned this approach.

Moreover, I'm strongly against this because embedding all formats in the .css file will force the browser to download them all (.eot/.woff//.woff2/.svg), instead of picking the most appropriate one

**Comment by ranbuch** [comment]
+1
I need to convert an SVG with Font-Awesome text to image. To do that I (to my understanding) need to embed inline font into the SVG, otherwise the font-face wouldn't be supported.

**Comment by alexbruno** [comment]
I just published an alternative solution for this problem:

https://www.npmjs.com/package/font-awesome-base64

**Comment by svyatik** [comment]
There's one good solution for base64 fonts. You can download them async, separately from your main css file. Then you can save these base64 fonts to localStorage and apply from async JS to every page. This will give you a big boost of website loading.
