### ISSUE TITLE
Icon Request: icon-name

### ISSUE THREAD

**Issue by flappry** [FortAwesome/Font-Awesome#2957]
Hy everybody,

First of all, I would like to thank you for your great great job ! It's so easy to use !

Now, I need your help . I need 2 new icon for my web project, could you create them for me please ?
The first one is called "csao" and  the second one is called "elingue"

![csao](https://f.cloud.github.com/assets/6771178/2245483/f0301eb0-9d51-11e3-815f-062de55992f9.JPG)
![elingue cble 4 brins](https://f.cloud.github.com/assets/6771178/2245485/f0335f94-9d51-11e3-82ab-b3c34709e232.png)

Thanks a lot by advance.

Best regards

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
