### ISSUE TITLE
icon request - fa pipes

### ISSUE THREAD

**Issue by tonesg** [FortAwesome/Font-Awesome#2998]
I am building a plumbing construction site at the moment using your icons which are great but only a few are appropriate.  I would love a pipes/drains icon
![blockeddrainsicon](https://f.cloud.github.com/assets/6834850/2305949/954362fa-a274-11e3-92bc-a49eeebc4446.PNG)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/pipe-section?f=classic&s=solid)
