### ISSUE TITLE
Icon request: icon-asl-{letter}

### ISSUE THREAD

**Issue by respectyoda** [FortAwesome/Font-Awesome#3013]
I know American Sign Language (ASL) and it would be cool to have each letter of the manual alphabet as an Font Awesome icon.

For example, there's already a SVG file for the letter F signed in ASL.
http://commons.wikimedia.org/wiki/File:Sign_language_F.svg

You can easily find the SVG file for the other 25 letters by replacing the letter F in the link given above with any other letter.

**Comment by aethior** [comment]
@tagliala `accessibility (category)` label for this request?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
