### ISSUE TITLE
Icon request: icon-cds (compact discs)

### ISSUE THREAD

**Issue by XanderTenBoden** [FortAwesome/Font-Awesome#3046]
I would like to see two icons added to font-awesome. A CD and a collection of CD's.

Something like this:
http://logopond.com/logos/81c489366c0ff37baad5b7b91f76f329.png
http://osmoney.com/djx/wp-content/uploads/2013/02/268134_142858552455214_8310695_n.jpg

Thanks! :-)

**Comment by popisms** [comment]
+1

**Comment by Darrelk** [comment]
+1

**Comment by rubencausyn** [comment]
+1

**Comment by underlircs** [comment]
+1

**Comment by RobKaijen** [comment]
+1
Kinda surprised this isn't included in the font awesome set yet.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/album-collection?f=classic&s=solid)
