### ISSUE TITLE
Icon Request: double-click

### ISSUE THREAD

**Issue by JamesyBase** [FortAwesome/Font-Awesome#3058]
I need to indicate to the user an element needs a double-click. I have an idea of an arrow in arrow aka acorn computer style, but then I liked this concept:

![image](https://f.cloud.github.com/assets/1829964/2387499/6f714208-a937-11e3-9ea6-05276b4baece.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
