### ISSUE TITLE
Icon request: fa-check-empty (check outline)

### ISSUE THREAD

**Issue by CathyMacars** [FortAwesome/Font-Awesome#3059]
I would use this on a sort of "task list" in a larger app. It would be the "undone task" icon. On hover, it would change to the normal, filled "fa-check" icon that already exists and, once clicked, I just apply an opacity to it to indicate the "done task".
Here's an image representing it:
http://cl.ly/image/1n2N3n2m3w42
Thanks

**Comment by sorenriise** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
