### ISSUE TITLE
Icon Request: folder-check-in and folder-check-out icons

### ISSUE THREAD

**Issue by TheRealCuran** [FortAwesome/Font-Awesome#3097]
I'd imagine something like an open folder icon with a curved arrow coming out for the check-out icon and a curved arrow pointing into the opened folder for the check-in.

Basically a combination of fa-folder-open-o and fa-reply (for check-out) and fa-folder-open-o and fa-share, though the arrow should be flipped vertically and the point should be smaller than the end.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
