### ISSUE TITLE
Icons not showing in Android

### ISSUE THREAD

**Issue by maxcook** [FortAwesome/Font-Awesome#3137]
Using Phonegap, Angularjs, Bootstrap and Font-Awesome. Samsung Galaxy Note 10.1

```
.fa {
  text-rendering: auto !important;
}
```

```
test<i class="fa fa-plus"></i>test <span class="fa">(&#xf0f6;)</span>test
```

renders to 

```
test test ()test
```

So i dont event see those "squares". 

Everything works fine in Chrome + Ripple

**Comment by tagliala** [comment]
is this still an issue?

**Comment by knownasilya** [comment]
It is for me, using Galaxy Note 2 and only seeing some weird squiggles instead of the icons. Works on desktop though.

**Comment by kentr** [comment]
Same problem on iOS / Phonegap.

What solved the issue for me:

1. Download Font-Awesome to a directory under you phonegap `www` directory.  I used 

  ```
  phonegap-project/www/fontawesome
  ```
2. For the CSS link in `index.html`, use the local CSS file instead of the CDN file, such as

  ```
  <link rel="stylesheet" href="fontawesome/css/font-awesome.css">
  ```

@tagliala Could this be due to the relative paths for `fonts` folder in `font-awesome.css`?:

```
src: url('../fonts/fontawesome-webfont.eot?v=4.5.0');
```

**Comment by tagliala** [comment]
Closing here

Please open a new issue if this is still an issue
