### ISSUE TITLE
Icon Request: All icons can knockout

### ISSUE THREAD

**Issue by jerimiahmilton** [FortAwesome/Font-Awesome#3192]
I don't know if this is possible, I have been attempting to create it on my own, but my limited knowledge of SVG is really getting in the way.

It would be a nifty feature to have the ability to have the icons "knockout" any color from icons stacked below it.

Example: if you were to stack three icons like so on top of a button element and then play with their positions.
![image](https://cloud.githubusercontent.com/assets/164630/2618120/b53f0df0-bc1b-11e3-9b6e-bec6de9ca025.png)

Now there's this ugly white circle, I would really like to just knockout the white circle.

Example: 
![image](https://cloud.githubusercontent.com/assets/164630/2618197/08edf708-bc1d-11e3-9e36-e48301cd1112.png)

I have attempted to achieve this myself, but like I said, my limited knowledge of SVG is making it impossible. Here's a stackoverflow thread I started trying to achieve this.

http://stackoverflow.com/questions/21487790/css-or-svg-text-clip-mask

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
