### ISSUE TITLE
SVG Icons

### ISSUE THREAD

**Issue by miljan-aleksic** [FortAwesome/Font-Awesome#3203]
Hi!

I would like to propose for consideration moving the fonts to SVG. That would allow editing the icons in real time, adding very precise effects and so much more as you probably know.

I'm aware it's a big task, but wondering if there is any reason why this could be not such a good idea.

**Comment by iegik** [comment]
Here I create SVG Font Viewer: http://jsfiddle.net/iegik/r4ckgdc0/
Actually, Its get `d` attribute from `<glyph/>` tag and creates new SVG with `<path/>` tag.

There are few reasons to using SVG Font as main repository file:

* SVG files may be converted to web fonts using [grunt-webfont](https://github.com/sapegin/grunt-webfont)
* easy to maintain icons changes
* easy to maintain class-names with `glyph-name` attribute

**Comment by iegik** [comment]
```
<svg class="icon" width="32" height="32" viewBox="0 0 2304 2304">
    <use xlink:href="#fa-github-square" fill="currentColor">
</svg>
```
http://css-tricks.com/cascading-svg-fill-color/

**Comment by Rush** [comment]
@iegik Cool stuff! :) Especially the fill color. Does it work across the browsers?

**Comment by tagliala** [comment]
@iegik thanks for sharing

**Comment by edouard-lopez** [comment]
+1

And another article in favour of SVG icons: [Inline SVG vs Icon Fonts](https://css-tricks.com/icon-fonts-vs-svg/).

**Comment by Schweinepriester** [comment]
+1

**Comment by kieranmorrissey** [comment]
+1

**Comment by Frucht** [comment]
+1

**Comment by konfuzed** [comment]
As I commented at https://github.com/encharm/Font-Awesome-SVG-PNG/pull/11#issuecomment-195034397 changing to SVG symbols for the sprites and setting the viewBox on each symbol will alleviate the issues are run into above, where the viewBox is being set in the svg usage rather than as the default essentially. https://github.com/CodeCharmLtd/Font-Awesome-SVG-PNG defaults everything to 0 0 origin and the 1792 em units as per the font, and I'd guess it's something to be corrected using the SVGO settings while but haven't had time to dig through them.

But if not there, perhaps there's a step further back in the font production which could help with setting the viewBox easier for creating sprites.

**Comment by sanek4life** [comment]
+1

**Comment by mattboehm** [comment]
For what it's worth, here's a Microsoft blog post where they suggested disabling custom fonts: https://blogs.technet.microsoft.com/srd/2011/12/13/more-information-on-ms11-087/ . I think this is what's triggered multiple organizations to mandate that custom fonts are disabled.

I've run into this problem 3 times so far in my career and always fixed it with the fontawesome svg-png repo mentioned above. I've yet to find a pure css solution. For others looking to implement this workaround, here's a gist to get you started: https://gist.github.com/mattboehm/3525b5090c5568207daa09c35ae1e895

**Comment by leungwensen** [comment]
If you are ready to use SVG icons, you should check this out: http://leungwensen.github.io/svg-icon/#awesome not only Font-Awesome, there are **more than 10,000 SVG icons** out of the box.

**Comment by Tklaversma** [comment]
>If you are ready to use SVG icons, you should check this out: http://leungwensen.github.io/svg-icon/#awesome not only Font-Awesome, there are more than 10,000 SVG icons out of the box.

First of all, your amazing for creating this..props!!

I do got some improvements I would like to suggest:

1. In `<svg..>` use `overflow:hidden` instead of `opacity:0`.
2. In `<svg..>` add `version=1.1`.
3. Put the `<symbol>` elements in `<defs>` like described in the [SVG 1.1 spec](https://www.w3.org/TR/SVG/struct.html#Head).
4. Add `title` element in every `<symbol>` for accessibility stuff.
5. Add `class`-attribute on `<path>` element .

My current SVG:
```
<svg style="position: absolute; width: 0; height: 0; overflow: hidden;" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <defs>
        <symbol id="icon-glass" viewBox="0 0 32 32">
            <title>glass</title>
            <path class="path1" d="M30.339 3.321q0 0.625-0.768 1.393l-11.286 11.286v13.714h5.714q0.464 0 0.804 0.339t0.339 0.804-0.339 0.804-0.804 0.339h-16q-0.464 0-0.804-0.339t-0.339-0.804 0.339-0.804 0.804-0.339h5.714v-13.714l-11.286-11.286q-0.768-0.768-0.768-1.393 0-0.411 0.321-0.652t0.679-0.313 0.768-0.071h25.143q0.411 0 0.768 0.071t0.679 0.313 0.321 0.652z"></path>
        </symbol>
        ...
    </defs>
</svg>
```

Further more, it would be awesome if people could define their own settings.

For example:

1. Use `<title>` element or not..
2. Setting their own `id`-prefix. Instead of `si-awesome-500px` it could be `myprefix-500px`.
3. Whether or not to minify the SVG.
4. Use `class`-attribute on `<path>` element or not, making it possible to adjust paths with CSS.

I hope you find this helpfull. I do got one more suggestion though...I think people are craving for this and are willing to help a lot. Maybe an idea to openup a repo on github?

Cheers,
TK

**Comment by tagliala** [comment]
I think this has been addressed in Font Awesome 5 and I'm going to close here
