### ISSUE TITLE
Icon request: icon-diver-down-flag

### ISSUE THREAD

**Issue by drmuey** [FortAwesome/Font-Awesome#3227]
Its graphically simple, just a thick line diagonally from top left to bottom right corner.

It would be useful for business and personal dive sites, thanks!

**Comment by coquimoran** [comment]
+1

**Comment by Luuk3333** [comment]
+1

[![Diver down flag](https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/ICS_Diver.svg/2000px-ICS_Diver.svg.png)](https://en.wikipedia.org/wiki/Diver_down_flag#The_red_and_white_flag)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
