### ISSUE TITLE
Icon Request: fa-script (icon-script)

### ISSUE THREAD

**Issue by Agent156** [FortAwesome/Font-Awesome#3229]
Writing to request the inclusion of a Font Awesome icon called "-script". My thought is to use this as a UI element both navigationally and representationally for a section on an internal test harness where the end-user selects and manages which scripts to run for performance testing, but it could also be useful for programming tutorial and code repository sites as a UI element.  Old-school icon from way back, it looks like a scroll rolled opposite directions on each end.  See attached examples.  Thank you for considering my request.

![dev_apple_script](https://cloud.githubusercontent.com/assets/5750598/2674696/b1ed3a56-c106-11e3-8033-44a448daa9e6.gif)
![fastscripticon256](https://cloud.githubusercontent.com/assets/5750598/2674698/b5ffb614-c106-11e3-8fda-2c6870a24a94.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
