### ISSUE TITLE
Icon Request: Oil Production Industry Icons

### ISSUE THREAD

**Issue by szakwani** [FortAwesome/Font-Awesome#3256]
In the Oil Industry, three of these icons are mostly used. Would be nice to have something that can represent them

**Comment by tonineumann** [comment]
+1

**Comment by tagliala** [comment]
Things have changed since last year.

I have to close this request because it doesn't meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

For a gas pump, please +1 #1676 . If you need more icons, please open new individual requests

Please also consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Closing here, sorry

**Comment by zerochka** [comment]
+1

**Comment by tagliala** [comment]
🔒 https://github.com/FortAwesome/Font-Awesome/issues/3256#issuecomment-93020066
