### ISSUE TITLE
Remove query strings from static resources

### ISSUE THREAD

**Issue by delight** [FortAwesome/Font-Awesome#3286]
Resources with a "?" in the URL are not cached by some proxy caching servers. Remove the query string and encode the parameters into the URL

turn 
http://iplocator.herokuapp.com/fonts/fontawesome-webfont.woff?v=4.0.3

into
http://iplocator.herokuapp.com/fonts/fontawesome-webfont-4.0.3.woff

**Comment by ivanjuras** [comment]
+1 from me as well

**Comment by jordanrynard** [comment]
+1

**Comment by thielj** [comment]
+1

**Comment by tagliala** [comment]
Added to 5.0.0 milestone

**Comment by swbullis** [comment]
As a way to bypass this for Offline Cache you can added a custom style directly after loading the font awesome css library with them removed.
```html
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
     
<style>
/*Temporary Fix for Font Awesome ApplicatonManifest offline Cache */
@font-face {
     font-family: 'FontAwesome';
     src: url('../fonts/fontawesome-webfont.eot');
     src: url('../fonts/fontawesome-webfont.eot') format('embedded-opentype'),       url('../fonts/fontawesome-webfont.woff2') format('woff2'), url('../fonts/fontawesome-webfont.woff') format('woff'), url('../fonts/fontawesome-webfont.ttf') format('truetype'), url('../fonts/fontawesome-webfont.svg') format('svg');
       font-weight: normal;
       font-style: normal;
}
</style>
```

**Comment by vladimirmartsul** [comment]
+1

**Comment by johnnyshields** [comment]
+1

**Comment by scotty6435** [comment]
+1!

**Comment by andy-mehalick** [comment]
+1

**Comment by JackMorrissey** [comment]
+1

**Comment by virgofx** [comment]
+1

**Comment by virgofx** [comment]
@davegandy Any chance this could get included in 4.4.1?

**Comment by aadi27** [comment]
+1

**Comment by browndav** [comment]
+1

**Comment by CounsellingHub** [comment]
+1

**Comment by greggles** [comment]
This seems like a popular common problem and the solution has received a lot of "+1" comments.

Is this blocked on someone doing the work or is it blocked on the belief that this idea is not a good solution?

**Comment by ziahamza** [comment]
The query string makes it really hard to use font awesome in browser extension. Even a less flag to remove the query string from url would come a long way.

**Comment by andrenarchy** [comment]
+1 Currently, I have to rename the font files for inclusion in an extension.

**Comment by robert-claypool** [comment]
+1

I must enable [Forward Query Strings](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/QueryStringParameters.html) in CloudFront only to support Font Awesome.

**Comment by mriehema** [comment]
+1

**Comment by blindpet** [comment]
I am struggling to understand why nothing is being done abut this 1 year later.

Another +1

**Comment by ralphonz** [comment]
another +1.  been an issue for ages

**Comment by mattbucci** [comment]
+1

**Comment by cdobbyn** [comment]
+1

**Comment by psimoneau22** [comment]
+1

**Comment by plremis** [comment]
+1

**Comment by swherdman** [comment]
+1

**Comment by drzraf** [comment]
Could someone state why these query-string reached the build-process in the first place?
(I guess it's about mobile-cache, isn't?)
And were *common*/*regular*/*standard-compliant* cache configurations considered at that time?

Query-string versioning is here to workaround buggy proxies, but should proxies assumed to behave correctly?
People currently having the right reverse-proxy stack/configuration are the most annoyed ones.

**Comment by leecollings** [comment]
Why is this being left so long to appear in a major milestone, when it could be simply pushed out quickly? I'm just going to edit my CSS file where they're being referenced until the change comes out.

**Comment by drzraf** [comment]
- If static filenames are used like _fontawesome-webfont-4.0.3.woff_, it causes long-term issues. It's assumed to be a static file at this location. 3rd-party applications relying upon fontawesome have be aware of. CDN may remove these resources later, leaving dependant component with a HTTP 404. Not all webserver may use the same rewriting/storage setup.

- If query-string are used, it causes troubles for reverse proxies and intermediary proxies since it bypass caches in many situations and create duplicates entries. It also eases cache poisoning (just `GET "https://the-cdn.com/fontawesome-webfont.woff?v=<the-next-versions>"` to store an old version for the next X years in reverse/intermediary proxies you crossed)

- So please remove cache-busting completely (or at least disable it by default). So that people relying on far-future Expires HTTP header have to deal with the workarounds for the problem they created themselves... and people who configure properly their Expires/Last-Modified/ETags get a simple setup that just works.

If people set their CSS/JS/fonts to Expire in 10 years they should just be given what they expected.

**Comment by mkurz** [comment]
+1

**Comment by chris-purcell** [comment]
A work around has been posted. As well, if you place the fonts on the server (or in your CDN) you don't have to use the query string at all. You only need the query string when accessing the fonts from fontawesome's servers. No fix is needed on their end. This is an end user comprehension issue.

**Comment by andrenarchy** [comment]
@chris-purcell the query string is included [here](https://github.com/FortAwesome/Font-Awesome/blob/49e8997098917a5497275531edabcb388152dfc3/less/path.less) so we're all using it by default. The query string confuses caches and breaks browser extensions by default. Of course, we can overwrite `@font-face`. The purpose of this issue is to fix it upstream so everyone benefits from it.

**Comment by gerrywastaken** [comment]
> This is an end user comprehension issue.

@chris-purcell Wow, in my case you are correct. It seems I had googled for the problem I was having and ended up on a bug report on the wrong repo. My issue was actually with the usage of font-awesome in a popular Rails gem. Which it seems, was actually an issue that was fixed 27 days ago:
https://github.com/bokmann/font-awesome-rails/pull/175

**Comment by andrenarchy** [comment]
@gerrywastaken this is exactly what we're all doing now. It'd be great to have it fixed upstream.

**Comment by lt7** [comment]
+1

**Comment by juanpablof** [comment]
+1

**Comment by danger89** [comment]
Based on the reference from @rmm5t . FontAwesome needs to take this bugfix along, thus somebody needs to merge this change and so it will be fixed in CDN from Bootstrap.

**Comment by drzraf** [comment]
See also: https://github.com/w3c/preload/issues/68

**Comment by IndigoStarfish** [comment]
+1

**Comment by tagliala** [comment]
Done!

**Comment by drzraf** [comment]
commit ?

**Comment by tagliala** [comment]
@drzraf please follow #11908

**Comment by jocar6562** [comment]
src: url('../fonts/fontawesome-webfont.eot?v=4.6.3');
src: url('../fonts/fontawesome-webfont.eot') ;
took out the ?v=4.6.3 not sure what that was for but could see no difference after testing
This worked fine it was the last thing I needed to do now I have speeded up landing page to 625 mil sec johnc
