### ISSUE TITLE
Icon Request: Highlighted Thumb

### ISSUE THREAD

**Issue by Zakuska** [FortAwesome/Font-Awesome#3290]
Something like this.

![hightlight_thumb](https://cloud.githubusercontent.com/assets/7360220/2757896/d468bd90-c989-11e3-9c0f-43279f7f41d4.JPG)

Basically, the fa-th icon with the left upper 4 squares joined to form 1 large square.  and the other thumbs

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
