### ISSUE TITLE
Icon Request: icon-slidedeck

### ISSUE THREAD

**Issue by jacksonj04** [FortAwesome/Font-Awesome#3294]
Along with #1176 and #1688 I'd like an icon to represent "slide deck" in a more generic way, probably something as simple as two or three overlapping 'slides'.

**Comment by avand** [comment]
+1

**Comment by sven-mayer** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
