### ISSUE TITLE
icon request: workplace

### ISSUE THREAD

**Issue by tlu74** [FortAwesome/Font-Awesome#3333]
Hello,
i am working on a medical app, so i would need some new icons. 
- workplace (this could be a map-locator with a cogged wheel in it eg: http://www.flaticon.com/search/map-locator)

thanks in advance
thanks for the great work
tom

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
