### ISSUE TITLE
 fa-arrow-circle-right & fa-arrow-circle-o-right Arrow Consistency issue

### ISSUE THREAD

**Issue by Devolv** [FortAwesome/Font-Awesome#3342]
Is it me or shouldn't the arrow styles be the same here?  One is a rounded triangular point, the other is with square strokes to create the arrow point.  Should it not be the same here since the Class name with "o" suggest that it's an outline version of the same icon?

**Comment by tagliala** [comment]
Hi, I'm shutting down some old requests 😅 

This has definitely been fixed in FA5
- https://fontawesome.com/icons/arrow-alt-circle-up?style=solid
- https://fontawesome.com/icons/arrow-alt-circle-up?style=regular

FA 5 Pro also contains the other arrow style in outline
https://fontawesome.com/icons/arrow-circle-up?style=solid
https://fontawesome.com/icons/arrow-circle-up?style=regular
