### ISSUE TITLE
New icon: Public Domain Share icon

### ISSUE THREAD

**Issue by mocking** [FortAwesome/Font-Awesome#3370]
Please add the share icon:

![social_network_sharing_icon svg](https://cloud.githubusercontent.com/assets/1511818/2899753/24089a94-d5bc-11e3-86d3-0de606513252.png)

There is a public domain SVG file here:
http://expando.github.io/share/

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
