### ISSUE TITLE
Icon Request: fa-policeman (police)

### ISSUE THREAD

**Issue by edcoyne** [FortAwesome/Font-Awesome#3372]
Looking to use this for menu items and graphics on municipal websites. In fact, a whole set of municipal icons is probably a great idea (as long as someone else is doing the work to create them!). ;)

![users-police-icon](https://cloud.githubusercontent.com/assets/7119332/2901509/46e40f3e-d5d6-11e3-8d07-f4964bb46d58.png)

Thanks so much!

**Comment by AntonioMalatesta** [comment]
+

**Comment by matdave** [comment]
+

**Comment by frank0051** [comment]
+

**Comment by chrisfaustin** [comment]
+

**Comment by aethior** [comment]
+1

**Comment by MadTiago** [comment]
+1

**Comment by frank0051** [comment]
Yeah, come on, it's been a year in a half since this request was suggested. We love Font Awesome and want a police officer icon to be part of the fun!

**Comment by Balloonatic** [comment]
+1

**Comment by isfak** [comment]
+1

**Comment by tuxy** [comment]
+1 for **fa-police**

![fa-police](http://i.imgur.com/yLWV9ug.png)

**Comment by nairdo** [comment]
+1

**Comment by jbnv** [comment]
+1

**Comment by Christian-Schiffer** [comment]
+1

**Comment by jiri-novacek** [comment]
+1

**Comment by madcowke** [comment]
+1

**Comment by dpfem** [comment]
+1

**Comment by fastesol** [comment]
+1

**Comment by ronifabio** [comment]
+1

**Comment by Wineliva** [comment]
+1

**Comment by okcjosh** [comment]
+10

**Comment by okcjosh** [comment]
Dallas Police Department is requesting this

**Comment by jdblundell** [comment]
+1

**Comment by jdblundell** [comment]
We actually convert Font Awesome to SVG - so I don't know if this will help anyone else, but here's a police icon in SVG based on fa-user if it will help anyone else.

https://www.dcccd.edu/icons/dcccd-police-black.svg

**Comment by Crissov** [comment]
👮 U+1F46E in Unicode #222

**Comment by Expl01ting** [comment]
+1

**Comment by allor** [comment]
+1

**Comment by fabioravila** [comment]
+1

**Comment by Stealth22PD** [comment]
+1

**Comment by LionelMeroni** [comment]
+1

**Comment by paul-arg** [comment]
+1

**Comment by mtpultz** [comment]
Please just thumbs up the original post indicating you voting for or against.  The thumbs up is +1 without everyone receiving an email that you have an opinion, but no input.  If you're trying to subscribe don't +1 just us the subscribe button.

**Comment by AlessandroVecchi** [comment]
Something like this ?
![senza-titolo-1](https://user-images.githubusercontent.com/20642463/53101705-98cd4a00-352a-11e9-8989-1c91f01fdf71.png)

**Comment by allor** [comment]
That looks more suitable for passport control. Loose the passport and replace with

**Comment by Stealth22PD** [comment]
Yeah that's more of a Customs/Immigration/Passport Control officer icon. Any of the previously posted police officer icons would work.

Personally, I needed the icon for an Angular project, but I worked around the missing icon by using a custom SVG icon.

https://alligator.io/angular/custom-svg-icons-angular-material/

**Comment by ergec** [comment]
+1

**Comment by weijyewang** [comment]
+1

**Comment by simonterrasson** [comment]
+1

**Comment by weijyewang** [comment]
+1

**Comment by Stack-of-Pancakes** [comment]
+1.  Also

> @mtpultz commented on Jan 19, 2019 [🔗](https://github.com/FortAwesome/Font-Awesome/issues/3372#issuecomment-455822966)

> Please just thumbs up the original post indicating you're voting for or against. The thumbs up is +1 without everyone receiving an email that you have an opinion, but no input. If you're trying to subscribe don't +1 just us the subscribe button.

To anyone else checking this thread and comes across this comment by @mtpultz I just want to let you know his stance is incorrect.  The metric for determining an icon's place on the [leaderboard](https://fontawesome.com/community/leaderboard/new) is the sum of the comment and reaction count.  Also contributor and Fort Awesome member @tagliala had this to say in another thread:



>@tagliala commented on Jun 10, 2015 [🔗](https://github.com/FortAwesome/Font-Awesome/issues/1706#issuecomment-110751677)

>@dennym +1s help us to keep track of most requested icons: https://github.com/FortAwesome/Font-Awesome/issues?q=is%3Aopen+is%3Aissue+label%3A%22new+icon%22+sort%3Acomments-desc 
>
>Take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

I would however like to add my $0.02 to the discussion.  The only real implementation problem I can see with adding a police officer icon is that the imagery is not consistent across the globe.  The uniforms vary, sometimes to a large degree, between different localities/countries.  Since the benefit of using something like font awesome is the ability to use a universally recognized image in place of text, it should be universally recognized.  Or at least very recognizable to a majority of people.

I think @edcoyne's initially posted image is a good idea.  I threw the phrase "police officers around the world" into a search engine to find the most common uniform components.  The one thing I saw more than anything else was headgear (hat, helmet, beret, et al.) with a large badge placed prominently in the center.  The shape of the badge varied a bit, but the most common were shield or star shapes.

My recommendation would be of a person's bust, wearing headgear, and with a shield or star shaped badge located in the center of the headgear, and again on the person's left or right breast.  It can almost be cobbled together using existing icons.  Take the fa-user-nurse as a base.  Remove the "+" from the hat.  Replace it with either fa-shield or fa-badge-sheriff.  Add the same badge to the person's chest.  Would just need a different hat created.  Somewhere between the fa-user-secret hat and fa-hat-cowboy.

**Comment by davwheat** [comment]
+1

**Comment by mbomb007** [comment]
+1

**Comment by sensibleworld** [comment]
<img width="717" alt="Screen Shot 2021-03-30 at 12 13 21 PM" src="https://user-images.githubusercontent.com/529604/113021190-53d86080-9151-11eb-9f1f-72b2cfef113a.png">

This is now available in the latest alpha release of version 6: http://fontawesome.com/download
