### ISSUE TITLE
Icon Request: fa-migrate

### ISSUE THREAD

**Issue by nedyrb** [FortAwesome/Font-Awesome#3385]
An icon that depicts three migrating Canadian Geese. When they migrate, they always form a "V" so using three geese would be the smallest, most appropriate number of geese for this icon.

The icon would be used as a menu item icon for my website - one of the services I offer is migration of a website to Drupal.

Other uses could include migrating to any other platform, or as a multi-purpose wildlife icon. I'm thinking people who enjoy bird-watching/hobby sites could find use with it. Font-Awesome could also use it as a way to visually communicate to glyphicons users to migrate to Font-Awesome.

http://community.glwb.net/gallery/var/albums/grafton%20pictures/Indian%20Hollow%20Park%20Migrating%20Geese%202%20copy.jpg?m=1338313581

http://static6.depositphotos.com/1040662/642/v/950/depositphotos_6420198-Migrating-geese-in-the-spring-and-autumn.jpg

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
