### ISSUE TITLE
Icon Request: fa-dot-circle-half-o

### ISSUE THREAD

**Issue by oliverpitsch** [FortAwesome/Font-Awesome#3399]
I am right now developing an online reputation management tool displaying online reviews from various sources. To keep the look and feel with font-awesome I am right now searching for fa-dot-circle-half-o to display the rating of www.tripadvisor.com.

Thanks!

**Comment by jacobkossman** [comment]
+1

**Comment by markushausammann** [comment]
+1

**Comment by TosPortugal** [comment]
+1

**Comment by tagliala** [comment]
Just an heads-up

This icon could be achieved with the power transforms and masking features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/7hod8jy3/19/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/circle-half?f=classic&s=solid)

**Comment by tagliala** [comment]
@sensibleworld I think this is a request for a different icon
