### ISSUE TITLE
Icon request: notepad  (notepad with pencil)

### ISSUE THREAD

**Issue by kevinhikaruevans** [FortAwesome/Font-Awesome#3449]
Just something that looks similar to the Windows notepad icon would be perfect.

**Comment by TheChen5** [comment]
+1
https://upload.wikimedia.org/wikipedia/en/thumb/2/2a/Notepad.png/64px-Notepad.png

**Comment by JordanReiter** [comment]
+1

**Comment by phuyem** [comment]
+1 , anybody home ?

**Comment by apovn** [comment]
+1 I need this icon

**Comment by BuhtigithuB** [comment]
+1

Bunch of ideas : https://www.google.ca/search?q=note+pad+icon&espv=2&biw=1920&bih=995&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwiV6YbSubbLAhXBWj4KHYb-CzgQsAQIGg&dpr=1

**Comment by phuyem** [comment]
any news guys ?

**Comment by My1** [comment]
most of those dont work easily due to the black/transparent limitation of ANY font.

**Comment by phuyem** [comment]
I prefer a notepad with a pencil actually 
This one is close
http://fontawesome.io/icon/pencil-square-o/

**Comment by My1** [comment]
well maybe add some lines and it would look pretty nice.

**Comment by johnunclesam** [comment]
Why is it close?

**Comment by My1** [comment]
@johnunclesam this is not closed yet. tagliala just referenced an other issue that was clsoed for this one.

**Comment by dropspace-io** [comment]
+1

**Comment by doubledeej** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
