### ISSUE TITLE
Icon Request: icon-dinner-platter (serving dome, cloche)

### ISSUE THREAD

**Issue by agustinglez** [FortAwesome/Font-Awesome#3453]
Quisiera este icono para usarlo en un proyecto que estoy realizando. Podría también ser usado por otras personas para diversos proyectos.

Imagen: http://i1.minus.com/jbd4Avqv7QReZ9.jpg

**Comment by G-Driver** [comment]
+1

Some examples
<img src="https://cdn3.iconfinder.com/data/icons/food-drink/512/Guest-128.png">
<img src="https://cdn0.iconfinder.com/data/icons/transit-2/32/transit-35-512.png">

**Comment by tagliala** [comment]
what is the english name of

![](https://camo.githubusercontent.com/a7bdce708eab27e41341be8300b347d6c2d59a85/68747470733a2f2f63646e332e69636f6e66696e6465722e636f6d2f646174612f69636f6e732f666f6f642d6472696e6b2f3531322f47756573742d3132382e706e67) ?

**Comment by G-Driver** [comment]
A dinner platter or waiter platter

**Comment by oriadam** [comment]
+1

**Comment by TonyValenti** [comment]
+1

**Comment by tzeller** [comment]
i have created a dinner icon which can be used
[fa-dinner.pdf](https://github.com/FortAwesome/Font-Awesome/files/1364631/fa-dinner.pdf)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/plate-utensils?f=classic&s=solid)
