### ISSUE TITLE
Icon Request: profit-arrow

### ISSUE THREAD

**Issue by ThisMichelle** [FortAwesome/Font-Awesome#3458]
I love your icons!! Thank you so much! I couldn't find one to fit what I wanted, which was to give the idea of "rising profit" or "chartable profit." The closest I found was the "bar chart." 

![screen shot 2014-05-17 at 6 55 36 pm](https://cloud.githubusercontent.com/assets/7614068/3006227/7f7326f8-de16-11e3-94c4-5a8ff025d4a9.jpg)
(https://cdn2.iconfinder.com/data/icons/66-charts-graphs-and-diagrams/512/Icon_2-512.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
