### ISSUE TITLE
Icon request: group-by

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#3494]
Commonly utilized in data centric web applications, spreadsheets, or word processors.  Sometimes seen in conjunction with a filter icon.

**Icon:**  ![group-by.jpg](https://dl.dropboxusercontent.com/u/3040414/group-by-icon/groupby.png)
**PDF:**  [icon-groupby.pdf](https://dl.dropboxusercontent.com/u/3040414/group-by-icon/icon-groupby.pdf)
#### Example

![example.png](https://dl.dropboxusercontent.com/u/3040414/group-by-icon/example.png)

**Comment by netrevisanto** [comment]
+1

**Comment by abloodworth** [comment]
+1, but I cannot see what icons the OP attached. I was just looking for this icon and here's an idea I saw:
<img width="102" alt="Screen Shot 2021-07-16 at 3 29 54 PM" src="https://user-images.githubusercontent.com/7774652/126014386-aee7ee43-ad28-4bd5-9be7-cae3080bffc0.png">

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
