### ISSUE TITLE
Icon Request: multiple fa-child which can represent students

### ISSUE THREAD

**Issue by shadowstrike** [FortAwesome/Font-Awesome#3495]
![screen shot 2014-05-21 at 11 00 40 am](https://cloud.githubusercontent.com/assets/3520420/3036380/1ff1dfd6-e0a9-11e3-8fe7-5fe5aa56f08d.png)
Hi

First of all I would like to appreciate your hardwork.

Secondly i need an icon for multiple students in my application.I came across fa-child which is awesome but i need multiple child.Something like this

```
        fa-child
  fa-child   fa-child
```

It should be in a triangular shaped formation.

Thanks in advance and have  a great day

**Comment by radubr** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome! [Take a look at it here.](https://fontawesome.com/icons/children?f=classic&s=solid)
