### ISSUE TITLE
Icon Request: bullseye-square

### ISSUE THREAD

**Issue by kimaguess** [FortAwesome/Font-Awesome#3510]
I work for a company who collects data from sensors that are attached to vehicles and assets.   We would like to have an icon to represent sensors, so that we can use it in the menu and on the sensor entity page of our application.
Here is an example of what seems to be the most universal symbol for "sensor".
http://findicons.com/icon/557967/sensor

Concentric circles that become smaller as you go out from the center.
![sensor image](https://cloud.githubusercontent.com/assets/7669750/3054504/eb02e396-e1b7-11e3-9a01-4be01d7bcb81.png)

Would be much appreciated!  Thank you.  :)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
