### ISSUE TITLE
Icon request: fa-review-ok fa-review-remove

### ISSUE THREAD

**Issue by YipYipX4** [FortAwesome/Font-Awesome#3520]
Use case: A line-of-business application where users need to review documents and approve or reject.  Clicking this icon would open the document in review mode (as opposed to edit mode, which would use fa-edit).

Icon: Perhaps a combination of thumbs up and thumbs down (if it can be made to render clearly enough), or maybe just an alias for the check-mark icon.  I'm also open to suggestions if any existing icon could work for this purpose (distinct from fa-edit).

**Comment by jkarr** [comment]
+1

**Comment by phuyem** [comment]
+1: yes yes , I love to have fa-review  

<i class="fa fa-file-text" aria-hidden="true"></i>

**Comment by tagliala** [comment]
Refers to #1181 , you will find there a solution (but it requires effort on your side)

**Comment by dkniffin** [comment]
I'm thinking something like this would be good for a general `fa-review`:

![image](https://user-images.githubusercontent.com/1680080/28637468-a130cd1e-720f-11e7-969e-65654818d11e.png)

**Comment by fuzzygroup** [comment]
I can't say what this should look like but I'm firmly in the camp of it being needed.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
