### ISSUE TITLE
Icon request:fa-draw-point

### ISSUE THREAD

**Issue by jorgevinagre** [FortAwesome/Font-Awesome#3556]
To be included in a GIS set of icons.
In GIS we draw geometries of several types: points, lines, polygons and rectangles.

![i_draw_point](https://cloud.githubusercontent.com/assets/3876637/3094852/f27ac6ae-e5c0-11e3-9cc1-72096f933809.png)

**Comment by vtforester** [comment]
+1

**Comment by dbauszus** [comment]
not necessary imho, we already have a circle item. just need to change the size of the icon to make it a point.

**Comment by ubahnverleih** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
