### ISSUE TITLE
Icon request:fa-draw-rectangle

### ISSUE THREAD

**Issue by jorgevinagre** [FortAwesome/Font-Awesome#3559]
To be included in a GIS set of icons.
In GIS we draw geometries of several types: points, lines, polygons and rectangles.

![i_draw_rect](https://cloud.githubusercontent.com/assets/3876637/3094891/6116b802-e5c1-11e3-9b00-bee4b26bd399.png)

**Comment by vtforester** [comment]
+1

**Comment by geforcefan** [comment]
+1

**Comment by dbauszus** [comment]
there is already a rectangle item. same for point. just need the zigzag line item.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/draw-square?f=classic&s=solid)
