### ISSUE TITLE
Icon request: fa-rifle sniper

### ISSUE THREAD

**Issue by bilal1101-m** [FortAwesome/Font-Awesome#3560]
an icon for rifle weapon

**Comment by Blu-Angel** [comment]
Something like these
http://goo.gl/TQClx0
http://goo.gl/r5wovh

**Comment by mika76** [comment]
For anyone looking - I found this - http://govicons.io/ - font awesome style icons which include some weapons...

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome! [Take a look at it here.](https://fontawesome.com/icons/person-rifle?f=classic&s=solid)
