### ISSUE TITLE
Icon request: fa-sumo

### ISSUE THREAD

**Issue by sdomino** [FortAwesome/Font-Awesome#3563]
A sumo wrestler would be a great cultural addition to an already awesome set of fonts. I've provided an SVG to hopefully make things easier on you guys (along with a preview of what it icon might look like).

http://cl.ly/150t0g0E0o1O

![fa-sumo](https://cloud.githubusercontent.com/assets/28181/3098408/ab296bb8-e5eb-11e3-8d87-85916bf455e5.png)

**Comment by aethior** [comment]
@tagliala `sport (category)` label for this request?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
