### ISSUE TITLE
Icon Request: fa-paragraph-right

### ISSUE THREAD

**Issue by benbro** [FortAwesome/Font-Awesome#3666]
Text editors usually have an icon to control the text direction (in addition to alignment) Right-to-left and Left-to-Right
The icons can be  the fa-paragraph icon with an arrow below pointing to the left or right.

This is how it is used in gmail:
![text-direction-icon](https://cloud.githubusercontent.com/assets/75841/3217946/0ddfe248-efe5-11e3-993b-8dbd41751d6a.png)

Thanks

**Comment by aethior** [comment]
Hi @benbro,

✔️ `fa-paragraph-left` (rtl) (https://fontawesome.com/icons/paragraph-left) icon was added in v5.9.0.
❌ `fa-paragraph-right` (ltr) icon does not exist yet.

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
I do not know how this icon works on RTL languages, I guess that it is inverted and shows "Left to right" instead

I think that `fa-paragraph-right` is an addition that should have even if it has not been requested because of internationalization and inclusion of RTL languages

@sensibleworld any thoughts?

**Comment by aethior** [comment]
> I do not know how this icon works on RTL languages, I guess that it is inverted and shows "Left to right" instead
> 
> I think that `fa-paragraph-right` is an addition that should have even if it has not been requested because of internationalization and inclusion of RTL languages
> 
> @sensibleworld any thoughts?

I think this should not be forgotten.
Maybe it's a good idea to open a new related request?
