### ISSUE TITLE
 Icon request: icon-HopCone; icon-barley, icon-Mashing, icon-Tap (beer production)

### ISSUE THREAD

**Issue by bier-seminare** [FortAwesome/Font-Awesome#3678]
Would it be possible for the team to include some typical brewery Icons?

I'm a Brewer and i need some typical Icons for my Website (Hop Cone, Barley, Vessel for Mashing, Tap,...) like this one http://i.istockimg.com/file_thumbview_approve/6642066/2/stock-illustration-6642066-beer-process-and-equipment-black-white-icon-set.jpg ?

**Comment by iainwb** [comment]
+1 to brewing icons, perhaps a keg or beer barrel as well.

**Comment by feeh27** [comment]
+1 #12088

**Comment by feeh27** [comment]
+1

**Comment by dsmclaughlin** [comment]
+1

**Comment by emlynjones** [comment]
Yeah this would be great to have - any feedback on whether this will be implemented at all?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
