### ISSUE TITLE
Icon-request: fa-osh (open source hardware)

### ISSUE THREAD

**Issue by RileyStarlight** [FortAwesome/Font-Awesome#3708]
I think it would be nice to have an icon for open source hardware:
- To enhance the open source (also in hardware)
- By the tremendous growth of the technologies of hardware (electronics, 3D printers ...)
- Because all these new projects require creating documentation (and lot better with font-awesome
  )

Just as there is a petition to open source icon ( #1283 ), I think this is also required.

![osh](http://static1.ponoko.com/design_images/images/30510/b8c8f804-7d43-53b7-007e-8afaba6ef2f8/oshw_product_page.png?1309948458)

**Comment by kaelle** [comment]
+1

**Comment by larsi-org** [comment]
+1

**Comment by pietrushnic** [comment]
+1

**Comment by Epistrato** [comment]
+1

**Comment by extrapixel** [comment]
+1

**Comment by leowzukw** [comment]
:+1:

**Comment by victornesta** [comment]
+1 for OH icon

**Comment by aaronkondziela** [comment]
+1

**Comment by johnozbay** [comment]
+1

**Comment by ThorbJ** [comment]
+1

**Comment by cntlsn** [comment]
+1

**Comment by jbobrow** [comment]
+1

**Comment by mafe72** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
