### ISSUE TITLE
Icon Request: fa-littlstar

### ISSUE THREAD

**Issue by vkincaid** [FortAwesome/Font-Awesome#3768]
Hi, 

Putting in a new request for an star icon outline with brackets around it. 

Use Cases
- Icon representing curated collections
- Global Navigation Icons 
- Starring/Like icon on Content and Imagery

![littlstar_icon-blck](https://cloud.githubusercontent.com/assets/7970515/3366283/9145f808-fb42-11e3-91bf-591a6763d09a.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
