### ISSUE TITLE
Icon request: wishlist add

### ISSUE THREAD

**Issue by JannesHaagsman** [FortAwesome/Font-Awesome#3792]
I would love to see a 'wishlist' icon like the example below

![wishlist_add](https://cloud.githubusercontent.com/assets/4092994/3409267/865b7da0-fdd6-11e3-9b76-e7924864d6ab.png)

**Comment by markaharper** [comment]
While searching for a Font Awesome "Wishlist" icon I found this request.

Here are some suggestions:

![fontawesome_wishlist_ideas](https://cloud.githubusercontent.com/assets/54191/25555682/a597950e-2cf5-11e7-9f49-9811e10a12b7.png)

In the meantime I am "stacking" a heart icon on top of a file-o icon

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
