### ISSUE TITLE
Icon request: Presenter

### ISSUE THREAD

**Issue by Mer10506** [FortAwesome/Font-Awesome#3795]
Hello,
Would you please make a Presenter icon?  I need a glamorous woman, think hosting an awards show or film festival. An accent of bright pink if you do color would be great!

This is a current icon my client is using. 
![lorelei_shellist_fashion](https://cloud.githubusercontent.com/assets/8005992/3412598/1b5b2416-fe02-11e3-894e-86131c86c0c2.jpg)

This is the closest thing I've found, but way too professional for my needs:
http://www.flaticon.com/free-icon/businessman-presenter_46787

Thank you in advance! This is awesome!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
