### ISSUE TITLE
Icon Request: Brand Identity

### ISSUE THREAD

**Issue by tea2sugars** [FortAwesome/Font-Awesome#3833]
Hi guys!

I'm thinking of using icons for various projects, things like mobile sites, websites, apps, drupal sites, etc. These are simple but things like 'creative' or 'ideas' may be a little tougher but dooable within the current collection.

Brand Identity seems to be the big one for me, i've had a look on the Noun Project and they have some goodies http://thenounproject.com/search/?q=brand%20identity

But a 'brand identity' icon like the letterhead icon or even the business card one would be very cool.

Anyway, i love the project you're doing and am always encouraging clients to use your icons! Just so simple to use and they're great! Keep up the good work!

Rik Barwick

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
