### ISSUE TITLE
Icon Request: fax-settings

### ISSUE THREAD

**Issue by edrubite** [FortAwesome/Font-Awesome#3853]
Hi,

Just wanna ask if you can include a fax-settings (maybe a fax with gear) and SMS settings (mobile with gear), I am a designer and created some of it but not really sure if it works.
![fax_smssettings](https://cloud.githubusercontent.com/assets/8063873/3477720/6aba431e-0322-11e4-8fd1-a2fb72edf5ec.jpg)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
