### ISSUE TITLE
Icon request: icon-input-fieldset

### ISSUE THREAD

**Issue by Donaldini** [FortAwesome/Font-Awesome#3907]
Als we are trying to switch from images to font-awesome i'm looking for a replacement of our current icon for a "fieldset".

Currently we are using this one: ![](https://groepsadmin.scoutsengidsenvlaanderen.be/groepsadmin/img/icon_group.png)

But we want a clearer one like this one: ![ga-icon-fieldset2](https://cloud.githubusercontent.com/assets/2185680/3585582/fec9ab18-0c27-11e4-8a1b-7a233993794c.png)

**Comment by aethior** [comment]
Hi @Donaldini,

The current [**fa-input-text**](https://fontawesome.com/icons/input-text) icon solves this issue?

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
It's not the same thing, the request should represent a set of fields instead of an individual one with text type

Maybe https://fontawesome.com/icons/pen-field?s=solid

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
