### ISSUE TITLE
Icon Request: fa-bag

### ISSUE THREAD

**Issue by Klikini** [FortAwesome/Font-Awesome#3948]
I am on the Children of Ur development team, where we are re-making an MMORPG that closed down.

We need an icon for a bag, to be used for an inventory menu.

Here is what a bag looks like in the game:
![bag](https://cloud.githubusercontent.com/assets/1693960/3636385/912ae83a-0fbd-11e4-8164-fa3c0830db0a.png)
Currently, fa-suitcase is being used, however, it does not carry the same message.

**Comment by MVcodeartbr** [comment]
+1

**Comment by smithandre** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/sack?f=classic&s=solid)
