### ISSUE TITLE
Icon Request: fa-mirror or fa-reflect

### ISSUE THREAD

**Issue by meepster-nz** [FortAwesome/Font-Awesome#3955]
Hi. First of: FontAwesome -- AWESOME.

Would be great to have a mirror/reflect icon. Simple and clean like 
![mirror](https://cloud.githubusercontent.com/assets/8229423/3651836/188c3636-112f-11e4-9321-469edac1738d.png)

Would be used for video or any css3 transition button etc etc.
Thanks and great work.

**Comment by justinwp** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/reflect-horizontal?f=classic&s=solid)
