### ISSUE TITLE
Icon Request: take a snapshot of a Virtual machine

### ISSUE THREAD

**Issue by nehamundada** [FortAwesome/Font-Awesome#3979]
Hey,

This icon is relevant to the virtualization systems, where taking a snapshot of
![snapshot](https://cloud.githubusercontent.com/assets/2620781/3682048/832822b2-12c3-11e4-824f-60fd574e635b.jpeg)
 a VM to the image can be done. I would be grateful if you can provide a useful icon for this

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
