### ISSUE TITLE
Icon request: Country Silhouettes

### ISSUE THREAD

**Issue by aryanduntley** [FortAwesome/Font-Awesome#3992]
Pretty self explanatory, these guys did a good job of making them and I think it would be useful to include in the fontawesome library:

http://www.dafont.com/geobats.font

**Comment by tagliala** [comment]
Sorry I have to close this one because there are too many countries and those silhouettes have a lot of points which will noticeably increase the font size.

I should suggest you to consider an SVG solution

Also check out http://datamaps.github.io/

Please refer to this comment: #281 (comment) for further information

**Comment by jbnv** [comment]
There are too many countries to add icons for a few of them, but there are not too many obscure websites to add icons for those. Apply the same standard and give each country an individual vote.
