### ISSUE TITLE
Icon-Request: fa-finish-line

### ISSUE THREAD

**Issue by ygd** [FortAwesome/Font-Awesome#3994]
something like this …

![ziel](https://cloud.githubusercontent.com/assets/1052456/3701307/13896a50-13f0-11e4-9b1a-5e4e45f61756.png)

**Comment by MaklaCof** [comment]
I think this is legit request. Sometimes you want to display finish line and not finish flag.
![image](https://user-images.githubusercontent.com/1589573/57435165-f07f7580-723c-11e9-8ea9-f959f15bb779.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/flag-checkered?f=classic&s=solid)
