### ISSUE TITLE
Icon request: column-next-right/column-next-left

### ISSUE THREAD

**Issue by montelyno** [FortAwesome/Font-Awesome#4028]
Hello there,

as you answered, here the single requests with an image example, what was meant.

![image](https://cloud.githubusercontent.com/assets/7818858/3764091/76bc18dc-18ac-11e4-96f1-ca4847a0779e.png)
Angle left/right in both directions in single icons.

Thanks!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
