### ISSUE TITLE
Icon request: icon-table-check, icon-table-xmark

### ISSUE THREAD

**Issue by montelyno** [FortAwesome/Font-Awesome#4031]
And something to check/validate a table (or cell):

![image](https://cloud.githubusercontent.com/assets/7818858/3764173/9442ef88-18ad-11e4-968c-d6e427dd409b.png)

**Comment by Llorx** [comment]
+1

**Comment by tagliala** [comment]
**In a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/107/

Ref:

https://fontawesome.com/v6/docs/web/style/power-transform
https://fontawesome.com/docs/web/style/mask
https://fontawesome.com/docs/web/style/layer

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
