### ISSUE TITLE
Icon request: log-scale linear-scale

### ISSUE THREAD

**Issue by lobo-tuerto** [FortAwesome/Font-Awesome#4050]
These could be used in data visualization apps to alternate between a logarithmic and a linear scale when visualizing data on coordinated axis.

Examples:

Logarithmic grid (left), Linear grid (right).
![escalas](https://cloud.githubusercontent.com/assets/5730/3788584/182f0e24-1a6d-11e4-85db-6d850adebced.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
