### ISSUE TITLE
icon request - Shop recycle

### ISSUE THREAD

**Issue by rajeshsrinivas** [FortAwesome/Font-Awesome#4136]
Can I get a new icon for shop recycle? It should be like the shopping font and a recycle one within

something like this http://www.flaticon.com/free-icon/shopping-cart-cycle_25107

Thanks!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
