### ISSUE TITLE
Alisa fa-instagram-square to fa-instagram

### ISSUE THREAD

**Issue by nCrazed** [FortAwesome/Font-Awesome#4137]
I am currently generating media icons/links in a loop that looks something like this:

```python
supported = ['twitter', 'youtube', 'facebook']
for media in  supported:
    print('fa-' + media + '-square')
```
and due to absence of `fa-*-square` variant for instagram, I have to duplicate the icon generation outside of the loop. The `fa-instagram` icon seems to fit perfectly among the `fa-*-square` variants so there's no need to create a separate icon for this.

If you think that this is worth doing, I am happy to submit a PR once I get around to setting up the development environment for this.

**Comment by dlutger** [comment]
fa-instagram-square would be awesome.

**Comment by tagliala** [comment]
I'm going to close this one, because instagram does not match the aesthetics of square icons: border radius is different.

We had to implement another facebook icon because of the different border radius:
http://fontawesome.io/icon/facebook-square/
http://fontawesome.io/icon/facebook-official/

Please use a custom alias in your stylesheet
