### ISSUE TITLE
Icon Request: fa-language-es-ru

### ISSUE THREAD

**Issue by jlentijo** [FortAwesome/Font-Awesome#4177]
Hi, 

I would like ask you to make an icon which will be similar to the icon “fa-language” but with the different letters inside.

![fa-language-ru-es](https://cloud.githubusercontent.com/assets/1142572/3981304/b85325fe-286c-11e4-9344-5469215291c8.png)

 If it is possible could you change the Japanese symbol by Spanish letter “Ñ” and the letter “A” by Russian letter «Я».

I need this icon for my personal website.

Thank you.
Juanma.

**Comment by MRippy** [comment]
Spanish or Español
English

**Comment by jace** [comment]
Additional request: the existing icon for `language` is too wide and doesn't sit well alongside other icons in a menu. A rounder/squarer icon would be better. This may be achieved by changing the current horizontal A-क orientation to a diagonal orientation like <sup>A</sup>/<sub>क</sub> (here using the Devanagari 'ka' letter for the audience my product caters to).

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
