### ISSUE TITLE
please i need this icons below

### ISSUE THREAD

**Issue by bmkarim** [FortAwesome/Font-Awesome#4183]
http://image.shutterstock.com/display_pic_with_logo/902728/144413650/stock-vector-laundry-icons-144413650.jpg

and 

http://image.shutterstock.com/display_pic_with_logo/1523243/182280872/stock-vector-vector-laundry-icons-set-182280872.jpg

thanck you in advance

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm checking old issues and I get into this one

I'm going to close here because this request doesn't meet our contributing guidelines and there is not enough traction to justify effort in fixing it

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
