### ISSUE TITLE
Icon Request: fa-flasks

### ISSUE THREAD

**Issue by SebastianMucke** [FortAwesome/Font-Awesome#4228]
I currently use flask in context of market research projects. The flasks-icon i would use as icon for collections of such projects.

Design: Like fa-flask, but multiple behind one another.

**Comment by alessandroraffa** [comment]
+1

**Comment by sensibleworld** [comment]
Does this fit the bill: https://fontawesome.com/icons/flask-vial?f=classic&s=solid

Or does it need to be two (2) identical flasks?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/flask-vial?f=classic&s=solid)
