### ISSUE TITLE
Why fa-futbol instead of fa-football, or no alias fa-football in 4.2.0?

### ISSUE THREAD

**Issue by AlainD-** [FortAwesome/Font-Awesome#4232]
Hi, thanks for the new release 4.2.0.

I was wondering why there a fa-futbol and no fa-football in this new release? Is it a mistake ?

Thank you.

**Comment by kevbodavidson** [comment]
+1

**Comment by davegandy** [comment]
This is a great question, and I've been thinking a lot about this. Whatever we do, we'll need to be consistent. It gets really tough to name these if we're constantly changing the rules for how we pick the name. I was trying to be more internationally conscious with the naming here, but in the end I think it's backfired. It's just too hard to keep moving the target for how we pick the names.

In the future, we'll sadly need to name these from a single country perspective. Since we understand more of the cultural context for the US, we'll have to go from that point of view. So when we can get around to it, `fa-futbol` will be renamed `fa-soccer`. With 5.0.5, we've already added an `fa-football-ball`.
