### ISSUE TITLE
Icon Request: fa-square-arrow-[direction]

### ISSUE THREAD

**Issue by ptopenweb** [FortAwesome/Font-Awesome#4251]
The request is for a new background set with arrows for the main icon (an add on to fa-square).

Something like:
- fa fa-twitter fa-square-arrow-down
- fa fa-twitter fa-square-arrow-up
- fa fa-twitter fa-square-arrow-left
- fa fa-twitter fa-square-arrow-right
- fa fa-twitter fa-square-arrow-all

Example (for fa fa-twitter fa-square-arrow-down).
![example](https://cloud.githubusercontent.com/assets/7467959/4089435/4673e872-2f6c-11e4-87b2-b04eba93b3b9.png)

By the way, great work with Font Awesome!

Thanks

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
