### ISSUE TITLE
Icon Request: fa-double-line-chart

### ISSUE THREAD

**Issue by G-Driver** [FortAwesome/Font-Awesome#4270]
For example http://icons.iconarchive.com/icons/oxygen-icons.org/oxygen/128/Actions-office-chart-area-icon.png

<img src="http://icons.iconarchive.com/icons/oxygen-icons.org/oxygen/128/Actions-office-chart-area-icon.png">

**Comment by mjaragon** [comment]
+1 

Hello, I'd like to use a similar icon, to link to the SPC charts of our web-system.
This icon would be better if it could also include the data points, for example:

![image](https://user-images.githubusercontent.com/30312698/28408614-58192a26-6d38-11e7-8dd3-4fd0d3b5151f.png)

**Comment by rsiebeling** [comment]
+1

**Comment by aethior** [comment]
@tagliala `charts-diagrams (category)` label for this request?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/chart-line-up-down?f=classic&s=solid)
