### ISSUE TITLE
Icon Request: fa-oop-class

### ISSUE THREAD

**Issue by BryanHunt** [FortAwesome/Font-Awesome#4361]
Could we please get an icon that represents an object-oriented class.  Maybe something as simple as a "C" recessed in a solid box.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/square-c?f=classic&s=solid)
