### ISSUE TITLE
Icon request: fa-geocache-multi

### ISSUE THREAD

**Issue by brainscript** [FortAwesome/Font-Awesome#4387]
Dear developer,

I'd like to request a icon for the geocache type "Multi-Cache". This icon and icons of other cache types you can find [here](http://www.geocaching.com/about/cache_types.aspx).

![Multi-Cache](http://www.geocaching.com/images/WptTypes/multi_72.gif)

**Comment by Tugzrida** [comment]
+1

**Comment by Cigaras** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
