### ISSUE TITLE
Icon request: fa-search-active

### ISSUE THREAD

**Issue by notreadbyhumans** [FortAwesome/Font-Awesome#4398]
When OSX is indexing the Spotlight icon shows the same magnifying glass, but with a single point in the centre.

Something similar would be a useful addition to fa-search as a subtle way of showing search activity, such as background indexing, or when using a type-ahead search system where there is a delay between typing and the results being returned.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
