### ISSUE TITLE
Icon request: fa-orcid

### ISSUE THREAD

**Issue by drammock** [FortAwesome/Font-Awesome#4401]
**What can it be used for?**

- Member organizations would use this icon to identify points of integration with the ORCID system.
- Researchers who have ORCID IDs are encouraged to put links to their ORCID profile on their personal webpages, and could use the icon there.

**Example image**

![mini-icon](https://cloud.githubusercontent.com/assets/1810515/4228292/6b03dc88-3958-11e4-9094-d3c1771ccfea.png)

([source](https://github.com/ORCID/ORCID-Source/blob/master/orcid-web/src/main/webapp/static/img/mini-icon.png))

**Icon request checklist**

- [x] This is a single icon or matched pair (Ex: lock / unlock)
- [x] The title starts with "Icon request: " and is followed by the requested icon name
- [x] I have searched for existing issues and to the best of my knowledge this is not a duplicate (mentioned in comments to #541 )
- [x] I have included at least one example image
- [x] The request is for a concrete object

**Notes**
From the ORCID [about page](http://orcid.org/about/what-is-orcid):

> ORCID is an open, non-profit, community-driven effort to create and maintain a registry of unique researcher identifiers and a transparent method of linking research activities and outputs to these identifiers.

**Comment by ahagenbruch** [comment]
+1

**Comment by lpaglione** [comment]
+1

I'm the technical director for ORCID. Happy to provide the icon in whatever format needed, or some engineering resource if helpful. We've gotten a few requests for the same.  Best, Laura

**Comment by dudmanj** [comment]
+1

**Comment by teamrat** [comment]
+1

**Comment by drammock** [comment]
FYI, I just discovered that the ORCID logo has been implemented in [academicons](http://jpswalsh.github.io/academicons/), though I haven't yet tested compatibility between that and fontawesome (e.g., sizing, spacing, etc).  If the compatibility turns out to be good, I'm +1 for closing this issue; as long as it's available I don't much care whether it's part of fontawesome or some other similar resource.

**Comment by dudmanj** [comment]
agreed. thanks for directing me to academicons


























On Oct 7, 2015, at 3:18 PM, Daniel McCloy <notifications@github.com> wrote:


FYI, I just discovered that the ORCID logo has been implemented in 
academicons, though I haven't yet tested compatibility between that and fontawesome (e.g., sizing, spacing, etc). If the compatibility turns out to be good, I'm +1 for closing this issue; as long as it's available I don't much care whether it's part of
 fontawesome or some other similar resource.
—
Reply to this email directly or 
view it on GitHub.

**Comment by musoke** [comment]
+1

**Comment by GeorgLink** [comment]
+1

**Comment by dennisbauer** [comment]
+1

**Comment by aviggio** [comment]
+1

**Comment by robertpmansion** [comment]
+1

**Comment by pascalschulthess** [comment]
+1

**Comment by jonbra** [comment]
+1

**Comment by byrdnick** [comment]
👍 +1

**Comment by philipp-germann** [comment]
+1

**Comment by fsimkovic** [comment]
👍  +1

**Comment by felixlohmeier** [comment]
+1

**Comment by filipesaraiva** [comment]
+1 :)

**Comment by ratio91** [comment]
+1

**Comment by ambs** [comment]
ok no news for 2 years. Lets look to the academicons.

**Comment by jhonatan89** [comment]
+1

**Comment by MatthiasLohr** [comment]
+1

**Comment by rschmehl** [comment]
+1

**Comment by julsraemy** [comment]
+1

**Comment by LifeWorks** [comment]
+1

**Comment by rabernat** [comment]
+1

**Comment by alainna** [comment]
Writing from ORCID here. As @drammock notes, [Academicons](https://jpswalsh.github.io/academicons/) has an iD icon included, and we'd love to help you add it to Font Awesome. [Let me know](mailto:community@orcid.org) what we can provide to help make it a reality. 😸

**Comment by trilobiet** [comment]
+1

**Comment by rabernat** [comment]
I noticed that, since this issue was opened, font-awesome has introduced a an icon-request template. Perhaps @drammock could reformat the original issue to match the template, as follows:

### What can it be used for?

- Member organizations would use this icon to identify points of integration with the ORCID system.
- Researchers who have ORCID IDs are encouraged to put links to their ORCID profile on their personal webpages, and could use the icon there.

### Example image (optional)

![orcid-icon](https://cloud.githubusercontent.com/assets/1810515/4228292/6b03dc88-3958-11e4-9094-d3c1771ccfea.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

Since our request clearly satisfies all of the items on the checklist, hopefully this nearly four-year-old issue can be resolved soon!

**Comment by drammock** [comment]
@rabernat I've updated the original post as you suggested.

**Comment by MatthiasLohr** [comment]
Perfect, thank you all! :) So... who is now in charge?

**Comment by rabernat** [comment]
There are currently more than 4000 unresolved issues on this repo, the vast majority of them icon requests!

I'm not sure how we can make this a higher priority for the maintainers. This seems to be involved, but I can't figure out how it works:
https://fontawesome.com/community/leaderboard/released

**Comment by MatthiasLohr** [comment]
It seems that they count the number of comments here and the number of smileys/thumbs up/any reactions (thumbs definitively work) to the initial ticket. So... all of you: Please give more thumbs up for the first comment: https://github.com/FortAwesome/Font-Awesome/issues/4401#issue-42482209 :)

**Comment by drammock** [comment]
@rabernat the vote works by counting the :+1: icons on the original comment of the issue.  If everyone would use the "add reaction" to give a thumbs-up instead of typing "+1" comments in the comment thread, we would (in theory) climb that leaderboard.  However, there are a number of things on the leaderboard that have single-digit numbers of :+1: (and we currently have 48 here) so I agree that it's unclear how that leaderboard really works.

**Comment by GeorgLink** [comment]
The leaderboard appears to be adding number of comments and 👍 and rank by those. ... we could game the leaderboard by posting more comments and getting more 👍  (one of them is enough)

**Comment by baddesigner** [comment]
+1

**Comment by stephanmg** [comment]
+1

**Comment by jboockmann** [comment]
+1

**Comment by MoamenElmassry** [comment]
+1

**Comment by rsa4046** [comment]
+1 As others have requested, yes: fa-orcid please. Thanks and kind regards.

**Comment by stephanmg** [comment]
+1

**Comment by LeonardoPaccianiMori** [comment]
+1

**Comment by LeonardoPaccianiMori** [comment]
+1

**Comment by blalterman** [comment]
Any status on this?

**Comment by katyhuff** [comment]
+1

**Comment by lapofran** [comment]
+1

**Comment by Smartappli** [comment]
+1

**Comment by aaronpeikert** [comment]
+1

**Comment by williamrowell** [comment]
👍

**Comment by TomDemeranville** [comment]
Tom here from ORCID.  Is there anyway we can help make this a reality?  We're being asked for it our end as well!

**Comment by Bisaloo** [comment]
FYI, the counter increases each time a reaction is added to the first post, **even if the same user has already added another reaction**.

That's why the current leader is in its current position for example, even though they don't have much more :+1: reactions than this issue.

**Comment by homocomputeris** [comment]
Relevant: https://jpswalsh.github.io/academicons/

**Comment by floriandierickx** [comment]
+1

**Comment by soli** [comment]
+1

**Comment by maelle** [comment]
Excellent idea :100:

**Comment by statibk** [comment]
+1

**Comment by lcolladotor** [comment]
As as example of how prevalent ORCIDs are, they now also displayed in the Bioconductor landing pages. For example: http://bioconductor.org/packages/release/bioc/html/recount.html

**Comment by njtierney** [comment]
To build on @lcolladotor 's comment - ORCIDs are also on displayed CRAN now as well: https://cran.r-project.org/web/packages/visdat/

**Comment by hturner** [comment]
Another use case: speaker/tutor profiles on conference websites, e.g. http://www.user2019.fr/tutorials/

**Comment by fmichonneau** [comment]
[The Carpentries](https://carpentries.org/) uses an ORCID icon under the profile of each of our 1700+ instructors who have provided it: https://carpentries.org/instructors/

**Comment by sensibleworld** [comment]
This is now available in 5.11: https://fontawesome.com/icons/orcid?style=brands
