### ISSUE TITLE
Icon Request: fa-aed (Automated External Defibrillator)

### ISSUE THREAD

**Issue by G-Driver** [FortAwesome/Font-Awesome#4415]
An AED (Automated External Defibrillator)

<img src="http://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Automated_External_Defibrillator_%28symbol%29.svg/600px-Automated_External_Defibrillator_%28symbol%29.svg.png">

**Comment by kimberley-johnston** [comment]
+1

**Comment by HuwSy** [comment]
+1

**Comment by KingDumah** [comment]
+1

**Comment by Spixx90** [comment]
+1

**Comment by Evohwoo** [comment]
+1

**Comment by K3ll06s** [comment]
+1

**Comment by aethior** [comment]
This icon is interesting for signage and maps.
Building floor maps use this icon to help people to find defibrillators and save lives.
Many businesses also put it at the entrance to warn that it is a cardioprotected space.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome! [Take a look at it here.](https://fontawesome.com/icons/heart-circle-bolt?f=classic&s=solid)
