### ISSUE TITLE
Icon request: icon-irr

### ISSUE THREAD

**Issue by slashsbin** [FortAwesome/Font-Awesome#4423]
[Iranian Rial](http://en.wikipedia.org/wiki/Iranian_rial) Currency Icon

Symbols:
1. HTML Code: `&#65020;`
2. PNG:
![365px-rialsymbol svg](https://cloud.githubusercontent.com/assets/1018207/4260165/9bf4ce12-3b2c-11e4-953a-7080e96913a4.png)

**Comment by meshalbafian** [comment]
I also want to request for this (Iranian Rial)

**Comment by slashsBin** [comment]
:+1:

**Comment by aligholami99** [comment]
plz add this to fa icons

**Comment by thesoftwaresquad** [comment]
I also want to request for this

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
