### ISSUE TITLE
Icon Request: fa-bodyrepair

### ISSUE THREAD

**Issue by stevegoossens** [FortAwesome/Font-Awesome#4454]
Purpose: car body repair at garage
Notes: I understand that the example would be hard to reduce in size, so something similar conveying the same idea of external bodywork repair in a smaller form would be fine.  No square/outline required

![bodyrepairs](https://cloud.githubusercontent.com/assets/2405344/4289346/bef9c3f8-3db2-11e4-9a11-8eb9b3c7c629.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
