### ISSUE TITLE
Icon Request: fa-clutch

### ISSUE THREAD

**Issue by stevegoossens** [FortAwesome/Font-Awesome#4455]
Purpose: clutch service/replacement at garage
Notes: the circular part of the logo in the Clutch Sound example, but extended to a full circle
![clutch-sound-logo-v3-invert](https://cloud.githubusercontent.com/assets/2405344/4289457/e0e9cc78-3db3-11e4-87db-4d73945b65b8.gif)

**Comment by danieldanielecki** [comment]
+1, would be awesome!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
