### ISSUE TITLE
Icon request: fa-map-markers

### ISSUE THREAD

**Issue by DezrtRose** [FortAwesome/Font-Awesome#4510]
Please add this icon to you superb collection :)

**Comment by caycek** [comment]
Just out of curiosity if we are talking about same thing here I would say this is worth looking at

![image](https://cloud.githubusercontent.com/assets/9340125/7551990/58357adc-f66b-11e4-8e5f-dd72f122566c.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
