### ISSUE TITLE
Icon request: icon-cloud-sync

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#4518]
Cloud sync (or ftp)  for hosting / technology site

Example:

![2](https://cloud.githubusercontent.com/assets/8635771/4373243/2b2cb774-432b-11e4-9761-40fedd3bb301.PNG)

**Comment by Soullivaneuh** [comment]
:+1:

**Comment by MonkeyTrainer12** [comment]
I would prefer this style:
![icon cloud-sync](https://user-images.githubusercontent.com/14097948/61409712-6f7dd380-a8a8-11e9-85e3-1e00f6e40736.jpg)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
