### ISSUE TITLE
Icon request: icon-cluster

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#4523]
For hosting / technology

![network](https://cloud.githubusercontent.com/assets/8635771/4373377/206fb542-432c-11e4-9e3d-6231c2248e25.PNG)

**Comment by jodibean** [comment]
+1 for a better network icon

**Comment by jaykay2342** [comment]
+1 for something like the 2nd and 3rd from  CoDEmanX  comment

**Comment by danhalligan** [comment]
+1 for a better graph icon. I would agree with the preference order provided in the examples from CoDEmanX. In particular the first icon seems to be the clearest representation of a graph with multiple edges per node.

**Comment by tagliala** [comment]
renaming to icon cluster

**Comment by altitude** [comment]
+1 for this. Something like CoDEmanX comment's second icon would be awesome.

**Comment by tagliala** [comment]
Closely related to #1342

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/chart-network?f=classic&s=solid)
