### ISSUE TITLE
Icon Request: fa-size-x

### ISSUE THREAD

**Issue by Mistralys** [FortAwesome/Font-Awesome#4535]
A range of icons for representing different **element or object sizes**, for example:
- Products in an online shop with different sizes
- Thumbnail sizes in an image gallery
- Choices of text / widget sizes in a web application
- etc.

They could be named like this for example:

fa-size-mini
fa-size-small
fa-size-medium
fa-size-large

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
