### ISSUE TITLE
Icon request: icon-NLG (Guldencoin)

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#4548]
Hey there! First of all thanks for all the awesome icons i'm using every day!

I would really like to see an icon for the Guldencoin, an upcoming Dutch
cryptocoin. More and more webshops are using this coin as a valid payment
method and it would be nice if i can add the icon for our customers!

![image](https://cloud.githubusercontent.com/assets/8913992/4403608/a56eba2a-44a5-11e4-898a-df2c909d11fc.png)
This should do the trick!

Link: http://www.guldencoin.com

Thanks in advance!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
