### ISSUE TITLE
Icon request: icon-cup-winner-1st, icon-cup-winner-2nd, icon-cup-winner-3rd

### ISSUE THREAD

**Issue by max-favilli** [FortAwesome/Font-Awesome#4601]
An icon for a cup, a winner cup.

Like these: https://www.google.it/search?q=cup+icon&espv=2&biw=2304&bih=1191&tbm=isch&tbo=u&source=univ&sa=X&ei=bYwqVJeMHejNygP09oLQAg&ved=0CCAQsAQ#tbm=isch&q=winner%20cup%20icon&revid=1762042995&imgdii=_

Having something like...
1. icon-cupwinner-first 
2. icon-cupwinner-second
3. icon-cupwinner-third

...would be a big plus!

I often have **to compile list of best rated products** for my e-commerce websites and would be great to have such icons with which to graphically enhance the first results.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Comment by tagliala** [comment]
But we will have #12024, which may fit the use case
