### ISSUE TITLE
Icon request: fa-mx

### ISSUE THREAD

**Issue by KlintMX** [FortAwesome/Font-Awesome#4605]
I work a lot with motocross - both in real life and here on the web. I am sure that many will be happy for a MX-icon. I know it can not be handled as pictured here, but it is important that it radiates action
![mx](https://cloud.githubusercontent.com/assets/6128040/4459078/4c8b7f7c-48a8-11e4-81f9-e5c1fe3306c5.jpg)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome! [Take a look at it here.](https://fontawesome.com/icons/motorcycle?f=classic&s=solid)
