### ISSUE TITLE
Icon request: thumb-tack-left

### ISSUE THREAD

**Issue by GerardFR** [FortAwesome/Font-Awesome#4617]
It should be the fa-thumb-tack horizontal, pointing towards left. This is to use both icons to pin / unpin a toolbox.

Thanks

**Comment by lrparker81** [comment]
+1

**Comment by alixeb** [comment]
`To arbitrarily rotate and flip icons, use the fa-rotate-* and fa-flip-* classes.`

Would that not be sufficient for what you want to do?
See examples here: http://fortawesome.github.io/Font-Awesome/examples/#rotated-flipped

**Comment by AlexeyKosov** [comment]
@alixeb Do you see fa-rotate-45 class? I don't.

**Comment by QWp6t** [comment]
@AlexeyKosov This issue is asking for one that faces horizontal, which would be a 90-degree rotation.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
