### ISSUE TITLE
Icon Request: fa-floppy-slash

### ISSUE THREAD

**Issue by MrBenGriffin** [FortAwesome/Font-Awesome#4620]
I have no idea how these could look - maybe fa-save-slash ??

![example](https://cloud.githubusercontent.com/assets/1785064/4490048/f20b4be4-4a24-11e4-87ea-c372467f4872.png)

**Comment by tagliala** [comment]
Take a look at this project: https://github.com/nyon/fontawesome-actions

https://github.com/FortAwesome/Font-Awesome/issues/1181#issuecomment-87315812

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
