### ISSUE TITLE
Icon Request: fa-terrorist

### ISSUE THREAD

**Issue by danieljue** [FortAwesome/Font-Awesome#4650]
Hi, I'm currently using fa-bomb, but we currently have the need to disambiguate between bomb events and terrorist people/entities in news reports.  The icon would be similar to a person/user icon with a headscarf and one or two tips of RPGs showing from the back (description take from an actual icon I've seen elsewhere).  Alternatively, the person may have an outline of a circular crosshairs.

Also, anything using the attached (copyrighted) picture as inspiration would be helpful.

Thank you!  We love using Font Awesome for displaying things extracted from news reports!

![](http://image.shutterstock.com/display_pic_with_logo/1201634/185137616/stock-vector-vector-black-terrorism-icons-set-on-white-background-185137616.jpg)

**Comment by S-ed** [comment]
![bomb belt](https://cdn4.iconfinder.com/data/icons/terrorist-terrorism-suicide-bomber/237/terrorist-terrorism-war-gun-001-512.png)

But it may look bad when minimized.
@LegoStormtroopr Agree,

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
