### ISSUE TITLE
Icon request: icon-learn-driving

### ISSUE THREAD

**Issue by DesCenario** [FortAwesome/Font-Awesome#4677]
I want to request an icon which looks like an "L" for learning to drive a car. 

I'm designing a website for a driving instructor and therefore I would like to add such an icon to his site.

I guess - at least in Switzerland - many people who use Font-Awesome and have to create a website about car driving could need an icon like this.

The icon could look something like this:
![icon-learn-driving](https://cloud.githubusercontent.com/assets/9057475/4548872/aec58c7c-4e58-11e4-806f-ba0c13d2e937.gif)

**Comment by dpfem** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/square-l?f=classic&s=solid)
