### ISSUE TITLE
Icon request: icon-font-color

### ISSUE THREAD

**Issue by mirogrenda** [FortAwesome/Font-Awesome#4689]
I would like to request a icon-font-color icon which can be used for text editors to change the font color.

Here's an example/graphics:

![icon-font-color](https://cloud.githubusercontent.com/assets/234146/4556337/ec8402ae-4ec7-11e4-8237-04827c0c8da6.png)

**Comment by elenamg75** [comment]
+1

**Comment by acshi** [comment]
+1

**Comment by Killerbear** [comment]
i can just give the fa-font icon a border bottom to achive this

example
http://codepen.io/Killerbear_02/pen/vxeKgg

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
