### ISSUE TITLE
Icon Request: fa-paid

### ISSUE THREAD

**Issue by Geko82** [FortAwesome/Font-Awesome#4690]
Hi,
thank you for your hard work.
I think can be useful a paid icon, something like this:

http://www.canstockphoto.com/paid-stamp-15237156.html

web designer can use it in admin area to display invoice status: "paid | not paid"
can be used to create documents with watermarks (invoice, receipt with paid watermarks)

Thanks for your time!

**Comment by MODUS-IT** [comment]
+1

**Comment by dougrawson** [comment]
Paid Stamp Ideas...
![paid](https://cloud.githubusercontent.com/assets/13891494/9391828/fd48cce6-472d-11e5-8f2c-f271179390ce.jpg)
![due](https://cloud.githubusercontent.com/assets/13891494/9391835/04e02d96-472e-11e5-9165-afa358b9ee62.jpg)
![late](https://cloud.githubusercontent.com/assets/13891494/9391866/3eb17a5c-472e-11e5-839c-1710779b4b51.jpg)

**Comment by Dan-Brantze** [comment]
+1

**Comment by MODUS-IT** [comment]
You can do it using stack
https://fortawesome.github.io/Font-Awesome/examples/

<span class="fa-stack fa-lg">
  <i class="fa fa-square-o fa-stack-2x"></i>
  <i class="fa fa-stack-1x">PAID</i>
</span>

**Comment by Geko82** [comment]
It could be a solution, but it is different from the one proposed by dougrawson and me, ignoring the fact that your solution requires much more css (font-style, font-size, font-family, color .... )

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
