### ISSUE TITLE
Icon Request: fa-checkout and fa-wishlist

### ISSUE THREAD

**Issue by seovery** [FortAwesome/Font-Awesome#4697]
all shopping site need to use fa-checkout and fa-wishlist icons.

**Comment by ogregoire** [comment]
For the wishlist, I don't like the gift because the gift refer to a single item. Also, the gift absolutely refers to something physical. Wishlists don't always refer to physical stuff. I'd prefer to see something like a sheet of paper with 3 lines and a heart in top right corner. The heart partially covers the sheet but also expands oustide of it. An example is the following image: http://www.cscartrocks.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/w/i/wishlist-pro-icon.jpg

**Comment by tagliala** [comment]
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

https://fontawesome.com/icons/file-heart?s=solid

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
