### ISSUE TITLE
Icon Request: fa-expand-alt/fa-collapse-alt horizontal and vertical

### ISSUE THREAD

**Issue by jesseschoff** [FortAwesome/Font-Awesome#4708]
I'd like a set of icons to represent expand/collapse or open/close in an unambiguous manner. I've used fa-times and and fa-chevron, but they are too contextual and do not stand alone very well without text explaining their function.

I propose using symbols similar to the open/close buttons on elevators.
![open-close](https://cloud.githubusercontent.com/assets/2190426/4580649/52a94880-4fd8-11e4-97b8-baa0230f814f.png)

I've create an example on codepen of what I'm going for. I've combined the carat symbols to make new icons: http://codepen.io/jesseschoff/pen/vyrjI/

**Comment by thibaultdelor** [comment]
+1 I want to have icons that means "collapse/expand this tree structure" and this one would fit way better for my use case (I would just need to rotate)
I think this icons fits better when you want to represent something that collapses only horizontally or vertically

**Comment by MC-delta-T** [comment]
i need same icons vertical versions

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
