### ISSUE TITLE
Icon request: fa-dot-circle-thin

### ISSUE THREAD

**Issue by thecray** [FortAwesome/Font-Awesome#4712]
The current fa-circle-o and fa-dot-circle-o icons do not have the same thickness as the fa-square-o icons, however the fa-circle-thin icon DOES have the same thickness.
Unfortunately there is no corresponding fa-dot-circle-thin icon, so it cannot be used to display a radiobutton.
This is important because when you're printing a form with a bunch of radios and check boxes together, the radios look bold, whereas the check boxes do not.

**Comment by Emil-git** [comment]
+1 I also vote for a separate font weight

**Comment by stevebhcc** [comment]
Any news on this at all?

**Comment by lucasvall** [comment]
+1 fa-dot-circle-thin

**Comment by amandalynn-hs** [comment]
+1 please

**Comment by LeoWinterDE** [comment]
+1 would be very useful.

**Comment by tagliala** [comment]
Hi, I'm closing some old issues 😅 

I think this has been fixed in FA5

- `circle-thin` has been dropped in favour of `far fa-circle`
- [far fa-dot-circle](https://fontawesome.com/icons/dot-circle?style=regular), [far fa-circle](https://fontawesome.com/icons/circle?style=regular), and [far fa-square](https://fontawesome.com/icons/square?style=regular) have the same thickness
- we have a light style in FA Pro

Demo: https://jsfiddle.net/tagliala/c9rxutqe/29/

Closing here

PS: If this has not been fixed, feel free to open a new issue
