### ISSUE TITLE
Icon request: fa-baby-blocks

### ISSUE THREAD

**Issue by bmorse** [FortAwesome/Font-Awesome#4722]
I am developing a website for a public library system and would like to have some category classifications icons for programs.

4th column, 4th row

http://www.thinkstockphotos.co.uk/image/stock-illustration-baby-icons-set-vector-illustration/466734183

**Comment by aethior** [comment]
@tagliala `childhood (category)` label for this request?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
