### ISSUE TITLE
Icon request - box,google drive, asana, basecamp

### ISSUE THREAD

**Issue by dhruvparmar372** [FortAwesome/Font-Awesome#4724]

**Comment by DaAwesomeP** [comment]
:+1:

**Comment by DaSchTour** [comment]
+1

**Comment by levicole** [comment]
:+1: on Asana.

**Comment by emcnutt** [comment]
+1 Asana

**Comment by zeeshanyshaikh** [comment]
Need icon for Asana.

**Comment by danpezzin-social** [comment]
+1 asana

**Comment by steffengrahl** [comment]
+1 Asana

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by DaSchTour** [comment]
I like the new box icon 🤣
