### ISSUE TITLE
Icon Request: fa-flag-uk 🇬🇧

### ISSUE THREAD

**Issue by sandeep-multani** [FortAwesome/Font-Awesome#4735]
It would be great if font awesome contain a section of flags for example USA flag, Canada flag, UK flag, Europe flag, India flag, Australia flag, etc. It may require lots of efforts but it will be very useful.

Thanks

**Comment by tagliala** [comment]
Sorry, closing here at the moment for tracking purposes

**Comment by rbourque** [comment]
There is a flag-usa.   There should also be a flag-canada.   It's monochromatic so it shouldn't be difficult.

**Comment by tagliala** [comment]
Reopening here

**Comment by Ancinek** [comment]
Posting my thoughts here – I think that having a flag icon pack in color would be great. FontAwesome is the only icon pack I'm using to create apps and having flags included would be awesome!

But I get that you have over 5k open issues and plenty of requests!
Thanks for your awesome work!

**Comment by angerangel** [comment]
The UK is a must, it's needed by a lot of site for the link to english version and it would solve a lot of template issues.

**Comment by iogbole** [comment]
The UK flag is much needed, please.

**Comment by mapsmarketing** [comment]
Adding the US flag and not the UK one is just silly...

**Comment by lerouxm** [comment]
Please, the only icon missing in our FA kits is the UK one. Could it be included at some point ?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Comment by sensibleworld** [comment]
Just a quick note that we're moving all individual country-flag requests to a single open issue: https://github.com/FortAwesome/Font-Awesome/issues/20288
