### ISSUE TITLE
 Icon request: icon-couch-co-op

### ISSUE THREAD

**Issue by lofidevops** [FortAwesome/Font-Awesome#4748]
This is a request for an icon representing a gaming subtype known as "couch co-op" (two players playing co-operatively in front of the same screen). I recently missed the opportunity to use it in a small game website. The typical icon is two little users on a couch.

Example of icon in the wild: http://www.co-optimus.com/games.php?type=couch (lots of other icons too)

Random use case example, wouldn't this look better with some Font Awesome bullet points? https://www.ouya.tv/game/House-of-the-Lost/ (although I don't know what to suggest for icon-epic-boss-battles :)

Design/work effort could be combined with https://github.com/FortAwesome/Font-Awesome/issues/759 (aka https://github.com/FortAwesome/Font-Awesome/issues/4613)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
