### ISSUE TITLE
Icon Request: fa-poppy

### ISSUE THREAD

**Issue by n-smith** [FortAwesome/Font-Awesome#4803]
An new icon in the symbol or shape of a poppy to be used for rememberance day in the UK. Example Poppy image or PNG below:

http://sbsadmissions.files.wordpress.com/2013/11/royal_british_legions_paper_poppy_-_white_background.jpg

This is the traditional poppy known in the UK

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
