### ISSUE TITLE
Icon request: fa-fireengine

### ISSUE THREAD

**Issue by Drel** [FortAwesome/Font-Awesome#4812]
Part of a series of requests for fire service icons.  Please note that I am requesting a separate icon for a ladder truck.  The easiest distinguishing feature is that a ladder truck (aka fire truck) will typically be equipped with an aerial ladder.  See here -- https://www.portlandoregon.gov/fire/article/275933.

**Comment by AlexanderPilhar** [comment]
+1

**Comment by aethior** [comment]
*Related Unicode Emoji* #222
🚒 [U+1F692](https://emojipedia.org/emoji/%F0%9F%9A%92/) Fire Engine
Also known as `Fire Department` and `Fire Truck`.

Related:
`fireengine`: #4812
`laddertruck`: #4813

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/truck-fire?f=classic&s=solid)
