### ISSUE TITLE
Icon Request: fa-monospace

### ISSUE THREAD

**Issue by asgh** [FortAwesome/Font-Awesome#4824]
Can you make an icon that indicates a monospace font?

I'm using fa-font right now, but something more specific would be better. I think an A in the courier font would be good.

**Comment by nomadus** [comment]
+1, this indeed would be good to have

**Comment by mviens** [comment]
I completely agree with the need for this.  I have attached a simple example of what it could look like.
![monospace](https://user-images.githubusercontent.com/8459232/32058333-926362c2-ba1e-11e7-9ef3-4c03cd7b1f30.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
