### ISSUE TITLE
Icon Request: fa-burst-shot

### ISSUE THREAD

**Issue by thomas144** [FortAwesome/Font-Awesome#4835]
I would like a "burst-shot" or "multi-shot" icon as is typically available on digital cameras.  Three overlapping rectangles would be good enough, but searching for "burst shot icon" on the web I find things like this one:
http://www.tiengiangtv.org.vn/2014/04/burst-mode-camera.html

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
