### ISSUE TITLE
Icon Request: fa-polish-bottle

### ISSUE THREAD

**Issue by Emi1y** [FortAwesome/Font-Awesome#4844]
I would appreciate some type of nail polish bottle icon for beauty and fashion bloggers. I made the ones I prefer red (it has a more common/recognized nail polish bottle shape.) 

Use Cases: I have a nail polish blog, so I would use it fairly regularly. I think it would be used by anyone who has a nail polish blog, as well as beauty and fashion bloggers. It could also be used by other types of bloggers who write on topics related to nail polish, cosmetics, or the beauty industry.

Thank you in advance! =)

(Example attached.)
![stock-vector-nail-polish-vector-106322402](https://cloud.githubusercontent.com/assets/9398639/4781356/e2861186-5c99-11e4-9692-8f552da8c2fe.jpg)

**Comment by RyanDawkins** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
