### ISSUE TITLE
Icon request: icon-tomoe

### ISSUE THREAD

**Issue by BenHoffmanYes** [FortAwesome/Font-Awesome#4847]
Taiko Drumming is huge in Japan and a growing art form her in the US. For our Taiko group (fushudaiko.org), I could use some Tomoe icons to get started...

Thank you! I love this font set!!!

![tomoe1](https://cloud.githubusercontent.com/assets/4613656/4792047/39aab59e-5de3-11e4-83dd-779b11571563.gif)
![tomoe2](https://cloud.githubusercontent.com/assets/4613656/4792048/39ad291e-5de3-11e4-95c2-c1940c5c3e00.gif)

**Comment by benh222** [comment]
Hi, sorry, I don't know what the etiquette is here for asking for a status. It's all good, I just hope this one isn't forgotten.

Thanks,
Ben

**Comment by aethior** [comment]
>Tomoe (巴, also written 鞆絵),[a] commonly translated as "comma",[2][3] is a comma-like swirl symbol used in Japanese mon (roughly equivalent to a heraldic badge or charge in European heraldry). It closely resembles the usual form of a magatama.

@tagliala Are you sure this is a brand?

**Comment by BenHoffmanYes** [comment]
Sorry, I submitted a tomoe image years ago. Is this what this is about????

**Comment by tagliala** [comment]
Hi @BenHoffmanYes , apologies for the unexpected notification. We are sorting out old requests and this one was miscategorized at that time

Actually I can't find the proper category for this request

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
