### ISSUE TITLE
Icon request: icon-world-map

### ISSUE THREAD

**Issue by amir-rahnama** [FortAwesome/Font-Awesome#4848]
Since @tagliala asked me to, I created a new request for this:

I was thinking of a world map icon similar to the following to be included in font-awesome:

<a href="http://www.freeimagehosting.net/commercial-photography/"><img src="http://i.imgur.com/qCFON0C.png" alt="Commercial Photography"></a>

**Comment by michaelminter** [comment]
:+1: even something simpler

**Comment by ambodi** [comment]
thanks guys :smile:

**Comment by vlipman** [comment]
+1 yes tricky to fit in an icon, but would be nice..

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
