### ISSUE TITLE
Icon Request: fa-astrology-asteroids

### ISSUE THREAD

**Issue by solsystem** [FortAwesome/Font-Awesome#4863]
Request for Astrology Icon Set: Asteroids

Symbols of all the Asteroids: Chiron, Ceres, Pallas, Juno, and Vesta

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
