### ISSUE TITLE
Icon request: icon-sa, icon-uganda, icon-zambia, icon-zimbabwe, icon-rwanda, icon-mozambique

### ISSUE THREAD

**Issue by Sybrin** [FortAwesome/Font-Awesome#4895]
I desperately need flag icons for my website, specifically looking for ones in Africa.
So i'm putting forward the recommendation to create all country flags, since everyone may need them at some point or another.

Please see these examples:
http://www.shutterstock.com/pic-166107953/stock-vector-south-african-flag.html?src=FrZvtp88BiDSrG3OcUuRrg-1-11
http://www.shutterstock.com/pic-161687465/stock-vector-original-and-simple-uganda-flag-isolated-vector-in-official-colors-and-proportion-correctly.html?src=bzWUKFvtXlWQdTzG_NZtQw-1-0
http://www.shutterstock.com/pic-197142191/stock-vector-flag-of-zambia-vector-accurate-dimensions-element-proportions-and-colors.html?src=_yWIKP4HQNImcgYkjaZN-g-1-12
http://www.shutterstock.com/pic-160945127/stock-vector-original-and-simple-zimbabwe-flag-isolated-vector-in-official-colors-and-proportion-correctly.html?src=kTIG7aD7a3PgvirXKsE2Ng-1-1

**Comment by tagliala** [comment]
Sorry I have to close this one because there are too many countries and those silhouettes have a lot of points which will noticeably increase the font size.

I should suggest you to consider an SVG solution

Also check out http://datamaps.github.io/

Please refer to this comment: #281 (comment) for further information

**Comment by crwang** [comment]
This may also may be worth checking out:

http://lipis.github.io/flag-icon-css/
