### ISSUE TITLE
Icon Request: fa-

### ISSUE THREAD

**Issue by KingsCraft2013** [FortAwesome/Font-Awesome#4915]
![sexyimage](https://cloud.githubusercontent.com/assets/9611244/4955889/56899f64-6698-11e4-9a76-a2a509ea9522.png)

Icon request: icon-ng

**Comment by KingsCraft2013** [comment]
I need this for my homepage
Am 07.11.2014 17:27 schrieb "Geremia Taglialatela" <notifications@github.com

**Comment by tagliala** [comment]
is this a brand? what is the use case for other people using font awesome?

**Comment by KingsCraft2013** [comment]
Because i have a little server system and i need this for my homepage and
other people like the worker they need this to because whem they post
something i need this for the logo i thank you for the interes
Am 02.01.2015 19:11 schrieb "Geremia Taglialatela" <notifications@github.com

**Comment by tagliala** [comment]
@KingsCraft2013 sorry but if this not a service that is going mainstream like most of brands included in fontawesome there are very little chance to see this in the core.

I should suggest you to take a look at:
Take a look at:
https://fonticons.com/ (by Dave - adding custom icons is not possible in the free tier)
http://fontello.com/
http://icomoon.io/app/#/select
http://fontastic.me/

I will temporary close this issue because this doesn't meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

Please fix the title, specify if it is a brand, and if the brand is not globally known explain why it is important and I will reopen.

Here it is a good example of request: #1685
