### ISSUE TITLE
Icon Request: fa-power-on

### ISSUE THREAD

**Issue by Gyroscopic** [FortAwesome/Font-Awesome#4926]
Hi
Just wondered if you can do a version of the power icon that is 'on'

It would just mean the vertical line in the icon would be dropped down and sunken into the circle

Existing Off icon
![Image of off icon](http://i61.tinypic.com/9a3094.png)

New On icon
![Image of on icon](http://i62.tinypic.com/2s0bomv.png)

**Comment by zekageri** [comment]
Well, ping ping. I also in need of a power-on icon :D

**Comment by tagliala** [comment]
Can you please provide an example of a "power on" icon?

**Comment by zekageri** [comment]
Circle is fine but for some reason i get a full on circle instead of the regular one.

Here is an example.
![image](https://github.com/FortAwesome/Font-Awesome/assets/37899881/67b37e56-1ba3-4e02-bd29-539df72c7702)

Power off is what it is because the circuit is broken so no current can flow.
If the circle is closed, current can flow, so it is power on.

As i said the regula circle is ok. I'm using the latest font awesome but for some reason the solid circle and the regular circle looks the same.

![image](https://github.com/FortAwesome/Font-Awesome/assets/37899881/ecd4219f-cc6b-4958-b5ca-89f92442f885)

![image](https://github.com/FortAwesome/Font-Awesome/assets/37899881/382cef9a-60c8-404a-8a61-d89335ca79af)

**Comment by zekageri** [comment]
circle-notch is not suitable either because it is also broken

![image](https://github.com/FortAwesome/Font-Awesome/assets/37899881/17029ab6-e335-414f-95d3-6f3c94db5d98)

**Comment by zekageri** [comment]
It would also be sorter if we had a power-on icon for us who uses this syntax

Currently:

```js

`<button class="pin-force-button outputToggle">
    ${pin.state?'<i class="fa-solid fa-circle-notch"></i>':'<i class="fa-solid fa-power-off"></i>'}
</button>`
```

Would became this

```js
`<button class="pin-force-button outputToggle">
   <i class="fa-solid fa-power-${pin.state?'on':'off''}"></i>
</button>`
```

**Comment by tagliala** [comment]
> As i said the regula circle is ok. I'm using the latest font awesome but for some reason the solid circle and the regular circle looks the same.

Sorry, this is a different issue, maybe a third-party framework adding some css rules which conflicts with Font Awesome. Please inspect the dom and find the offending rule

Ref: https://jsfiddle.net/tagliala/8djt9nur/3/

So this is a request for a circle, or a small circle, or may be even circle-dot and we already have them:

- https://fontawesome.com/icons/circle?f=classic&s=solid
- https://fontawesome.com/icons/circle-dot?f=classic&s=solid
- https://fontawesome.com/icons/circle-small?f=classic&s=solid (FA Pro)

> It would also be sorter if we had a power-on icon for us who uses this syntax

Please add an alias in your CSS or import the icon with a different name if your application is using SVG+JS

Closing here
