### ISSUE TITLE
Icon Request: icon-macro

### ISSUE THREAD

**Issue by tdjoiner** [FortAwesome/Font-Awesome#4965]
I have come across several times to create a macro icon and would like to use the Font icon instead.  I use it as a way to create alternative alerts for my forms.  Microsoft Excel uses a macro icon that has like a document with a scroll on top.
![macro-icon](https://cloud.githubusercontent.com/assets/5429876/5017632/ff28af22-6a74-11e4-96fa-d3b9c2d72e17.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome! [Take a look at it here.](https://fontawesome.com/icons/scroll?f=classic&s=solid)
