### ISSUE TITLE
Icon Request: icon-ball-sack

### ISSUE THREAD

**Issue by mmoyles87** [FortAwesome/Font-Awesome#5014]
Can we get a nice ball sack icon? Like some truck nuts or something?

Use case:
We run a stock market trading group, and it would be nice to be able to tag someone when they make a ballsy bet in the market.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Comment by scrummitch** [comment]
We will need to get our ballsack icons elsewhere
