### ISSUE TITLE
Icon request: fa-file-xml-o

### ISSUE THREAD

**Issue by Christilut** [FortAwesome/Font-Awesome#5016]

**Comment by cuttingedgehobbies** [comment]
+1

**Comment by ytodorov** [comment]
+1. XML icon would be great. Please make one for us.

**Comment by diksha694** [comment]
+1

**Comment by nguyentuanbao** [comment]
You can stack the text (XML) and icon (fa-file-o) as explained in this link : [http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/]

**Comment by jpajuelo** [comment]
+1

**Comment by Berkmann18** [comment]
+1

**Comment by NickNiebling** [comment]
Just adding my thoughts to help people "work around" current limitation.

I also think it's difficult to add "xml" icon, since file-code is looking exactly as I would suggest file-xml to look.

You could argue that file-code both covers "code", "xml", "html", "xhtml", "xaml" and any other "xml based" file format. It would be difficult to implement all those in different ways either way (might be required for some - but difficult for sure).

Currently I've been able to use file-code when I needed "xml icon", since I never need "code" and "xml" icons side by side. However, others might find that to be a limitation they cannot overcome and therefore need explicit code and xml file icons that works side by side.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/file-xml?f=classic&s=solid
