### ISSUE TITLE
Icon Request: fa-moto fa-supermoto fa-chopper fa-cruiser fa-helmet fa-piston

### ISSUE THREAD

**Issue by ACE46** [FortAwesome/Font-Awesome#5018]
Hello!
Please add this simple set of moto icons.
I think there is no need to explain where and how to apply them as their field of application is huge.
The example files are named, respectively.
![chopper](https://cloud.githubusercontent.com/assets/9901894/5155152/6650add8-7283-11e4-93e4-e0df95589336.jpg)
![cruiser](https://cloud.githubusercontent.com/assets/9901894/5155148/660fb152-7283-11e4-9b2d-c21f8e12c0be.png)
![helmet](https://cloud.githubusercontent.com/assets/9901894/5155149/66254dfa-7283-11e4-8153-c704e490a674.jpg)
![moto](https://cloud.githubusercontent.com/assets/9901894/5155147/66011598-7283-11e4-97b6-a75b5b95b555.jpg)
![piston](https://cloud.githubusercontent.com/assets/9901894/5155151/6643f61a-7283-11e4-8034-405a8e4388e0.jpg)
![supermoto](https://cloud.githubusercontent.com/assets/9901894/5155150/663129a4-7283-11e4-88ec-3602c7ed2b3a.jpg)

**Comment by sebastiansipos90** [comment]
+1

**Comment by tagliala** [comment]
Sorry, I missed this request

I can't leave this open because it doesn't meet our contributing guidelines:

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

Even if you need all those icons for your use case, you should open individual request having care of searching for duplicates before
