### ISSUE TITLE
Icon Request: fa-char-<letter>

### ISSUE THREAD

**Issue by LCastr0** [FortAwesome/Font-Awesome#5019]
It would be very cool if there was 1 icon to each alphabet letter (A, B, C...) and number.

**Comment by erm3nda** [comment]
If i do undestand correctly, use a fortawesome icon can avoid me to get an image, use the tag, put with css then finally, show it. Why is not that good for numbers too?

I don't know how hard can be to add 10 (0-9) more icons wich are used for general purpose.
So, what about Roman numbers? There are less and got some ornamental design...

Even if i don't know what will be a good solution, i don't think is cool to avoid number icons on the icon pack.

**Comment by tagliala** [comment]
> Why is not that good for numbers too?

Because numbers are already present in almost all fonts and fontawesome is basically a font. With numbers (and standard unicode point), we will overload css with dozens of class definitions (icon-number-0..icon-number-9, icon-letter-A..icon-letter-Z, icon-letter-a..icon-letter-z, icon-letter-greek-a..icon-letter-greek-omega)

If you want to add numbers, you could use thie following approach: http://jsfiddle.net/tagliala/77re29ct/61/

You could also use the stack feature: http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/

Moreover, the suggested use case for numbers is often an abuse that goes beyond the "icon" meaning (e.g.: numbers from 1 to 100 inside a table. Votes (A-F). Why that? Use a number/letters so you can also sort the rows)

> So, what about Roman numbers? There are less and got some ornamental design...

I wouldn't say they are less romam numbers... If we only implement I,V,X,L,C,D and M, in order to write 4 we should use two icons: `icon-number-1-roman` `icon-number-5-roman` which is counterintuitive. Same for almost any other roman number.

Should Dave implement all roman numbers between 1 and ∞?

Said that, it would be useful to have numbers and letters in fontawesome which have the same aspect of other icons, but this is not the priority at the moment

**Comment by erm3nda** [comment]
Thank you, i used stacked from http://stackoverflow.com/a/24264565/2480481 but with a modify to use numbers: `<span class="fa-stack fa-lg"> <i class="fa fa-circle-thin fa-stack-2x"></i> <i class="fa fa-stack-1x">1</i> </span>` as example.

**Comment by erm3nda** [comment]
>I wouldn't say they are less romam numbers... If we only implement I,V,X,L,C,D and M, in order to write 4 we should use two icons: icon-number-1-roman icon-number-5-roman which is counterintuitive. Same for almost any other roman number.

Same as you wrote two words when writting IV with keyboard you must use 2 icons for put the number with icons. If that is counterintuitive for you i have no idea how can it be. Same goes for decimal numbers. To put twenty three you must write 23, and the same goes for the number of icons involved.

I say just develop 0-9 digits then use/combine. Also a special class for "join" numbers with a 75% widht can be cool.

Anyway stacked is cool enough for me ;)

Thank you again.

**Comment by tagliala** [comment]
ok got it. you would write roman numbers in this way `icon-letter-i` `icon-letter-v` rather than `icon-number-roman-1` `icon-number-roman-1`

So roman numbers are a subset of icon-letter-a..icon-letter-z

**Comment by erm3nda** [comment]
Yes, you got it. Decimal system can be done with a subset of numbers 0-9 and Roman too with a subset of letters IVXLCDM.

In both cases, using stacking you are done.

**Comment by erm3nda** [comment]
Funny note: Infinite ∞ is not a number and is not represented by one of them.
It's a term and it's represented by a simbol. You don't need to reach it, also i guess you need also ∞ RAM to do so :)

**Comment by tuxy** [comment]
+1, But it should be "fa-sign-<letter>"

**Comment by nostalgiaz** [comment]
+1

**Comment by Crolug** [comment]
+1, especially for Roman

**Comment by chillinski** [comment]
What about adding a modifier class (like fa-letter) that will style the text-content of the HTML-tag it is assigned to. So you do not need to create new CSS classes for each requested letter.

**Comment by samayo** [comment]
+1

**Comment by cykerway** [comment]
+1

**Comment by tagliala** [comment]
I'm going to close this one for the moment.

Please use custom css if you really need letters

**Comment by Buky77** [comment]
+1 

Too bad, if i need capital letter with good font i only can found `A` there `<i class="fa fa-font" aria-hidden="true"></i>` But i can find 11 differents of thermometer and 11 versions of battery...

Alphabet in capital letter have 26 letters, in other way thermometer + battery have 22 icons....

**Comment by tagliala** [comment]
Hi,

> thermometer + battery have 22 icons....

10 icons (5 + 5), the other ones are aliases

**Comment by Ujjwal-9** [comment]
```css
.fa-font:before {
        font-family: roboto;
        color: #429bf4;
        font-size: 1.2em;
        content: "k";   #any letter of your choice
}
```
Add above code to the style tag.
This gives same functionality as awesomefont and it can be used like this:

```html
<i class="fa fa-font"></i>
```

**Comment by My1** [comment]
I think numbers wouldnt be too bad, either or other chars, but one thing: I dont think this would need crazy CSS, because letters and numbers are precisely that. no need to put some `before` statements in, one could just do `<i class="fas">2</i>` and the font would do the rest.

**Comment by exodus4d** [comment]
You can even make the "char" icon dynamic:
```html
<i class="fas pf-char fa-fw" data-char-content="S"></i>
```
and SCSS:
```CSS
.pf-char:before{
    font-family: Arial; /* your font family here! */
    font-weight: bold;
    content: attr(data-char-content);
}
```

**Comment by gerardreches** [comment]
> please keep in mind that you are requesting at least 58 new icons that will also bloat the css file.

I think this shouldn't be a big issue since FontAwesome 5 and kits loading only the used icons.

I'm using the Elementor plugin in WordPress, which uses FontAwesome for its icons and has compatibility with FontAwesome Pro, and I find myself needing these icons. Unfortunately, in some situations, it's not easy or possible to use custom HTML/CSS, and these icons might be required.

**Comment by tagliala** [comment]
@sensibleworld will letters and numbers be available in FA6?

**Comment by sensibleworld** [comment]
Yup! They're already there :) Check out the latest Alpha release. (And they'll be included in v6 Free as well)

**Comment by tagliala** [comment]
>  (And they'll be included in v6 Free as well)

🚀

I'm going to fix some labels here and there

**Comment by Crolug** [comment]
Wow, we surely went a long way since "keep in mind that you are requesting at least 58 new icons that will also bloat the css file" initial answer 8)

**Comment by My1** [comment]
@Crolug well there's the pro subsetter and several other options for free subsets.

**Comment by tagliala** [comment]
> Wow, we surely went a long way since "keep in mind that you are requesting at least 58 new icons that will also bloat the css file" initial answer 8)

![image](https://user-images.githubusercontent.com/556268/113330919-90f24d80-931f-11eb-8d0d-a85c3b5cc6b3.png)


> @Crolug well there's the pro subsetter and several other options for free subsets.

I would explicitly mention [SVG + Tree Shaking](https://fontawesome.com/how-to-use/javascript-api/other/tree-shaking)
