### ISSUE TITLE
Icon request: icon-microphone-live

### ISSUE THREAD

**Issue by juergenlink** [FortAwesome/Font-Awesome#5030]
I am currently looking for icons for a band's equipment.
As I'm already Font Awesome it would be nice if these icons would be available.

What I need is a corded microphone (as used by vocalists live), not the podcast-like version
of a microphone that already exists in Font Awesome.

Something like this:
http://findicons.com/icon/496951/microphone?id=523150

**Comment by Darrelk** [comment]
+ 1

**Comment by Neraste** [comment]
+1

**Comment by aethior** [comment]
Hi @juergenlink,

Something like https://fontawesome.com/icons/microphone-stand?

Regards.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/microphone-stand?f=classic&s=solid)
