### ISSUE TITLE
Icon request: icon-catamaran

### ISSUE THREAD

**Issue by lburgalassi** [FortAwesome/Font-Awesome#5078]
this icon can be used on all website concerning sea sports and activities (sailing centers, resorts, regattas,...) 

I need to describe a sailing center services including catamaran class.

![catamaran](https://cloud.githubusercontent.com/assets/1389625/5215820/8e3f4632-762b-11e4-847c-b46e6057741c.jpg)

**Comment by aethior** [comment]
@tagliala `transportation (category)` and `maritime (category)` labels for this request?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
