### ISSUE TITLE
Icon request: icon-forsale

### ISSUE THREAD

**Issue by orbitalthread** [FortAwesome/Font-Awesome#5107]
Requesting an icon with the word "Sale" or "For Sale". 
Use case: display next to a price to indicate its for sale.
Example icons: 
1. http://goo.gl/67uOMV
2. http://goo.gl/gZJSae
3. http://goo.gl/gZJSae

**Comment by coffeelady** [comment]
+1

**Comment by dhaupin** [comment]
+1 "On Sale" style icons would be good indeed for ecom stores. Often i see people use the fa-tag for this, but its not clearly "sale" and since its used for other tags, may confuse folks who are used to it. I would suggest the name of this icon be fa-onsale though (vs fa-forsale).

**Comment by evan-terminus** [comment]
👍

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
