### ISSUE TITLE
Icon request: fa-refresh-top, fa-refresh-bottom

### ISSUE THREAD

**Issue by SBero** [FortAwesome/Font-Awesome#5143]
It'd be great if we could get the arrows for the refresh icon separated out as their own individual arrow icons.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.]()

**Comment by tagliala** [comment]
@sensibleworld the link is missing, I can't understand which one is the suggested replacement
