### ISSUE TITLE
Icon Request: fa-header-ban

### ISSUE THREAD

**Issue by CavemanCook** [FortAwesome/Font-Awesome#5169]
I love this service you guys provide!  

I am building a website and need icons to represent actions. On our website's programs page, you will see what I mean if desired. www.villagecreed.com.

Request #1 We need a fingerprint icon. We need to tell people to get a criminal background check. This will help us out tremendously. I'm really not picky on the style. You guys do great stuff.

Request #2 This may be too personal but.. We need an "H" inside the universal no symbol (circle with a line through it).  The "H" would represent "no service hours available" on our website.  I can code for this icon if it can be created.  

Thank you so so much for reviewing,

Kermit

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
