### ISSUE TITLE
icon request: fa-box-plot

### ISSUE THREAD

**Issue by minotogna** [FortAwesome/Font-Awesome#5177]
Hi,
would it be possible to have an icon for box plot? 
http://en.wikipedia.org/wiki/Box_plot
Please see this one as example: http://en.wikipedia.org/wiki/Box_plot#mediaviewer/File:Box-Plot_mit_Min-Max_Abstand.png

Thanks!
Mino

**Comment by msquatrito** [comment]
Hi,
Any chance to get this icon in the near feature?
Thanks
Massimo

**Comment by tagliala** [comment]
@msquatrito please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by msquatrito** [comment]
I would need it it for a web app developed in R shiny. At the moment only font awesome and glyph icons are supported. Thanks anyway.

**Comment by lickmydesign** [comment]
+1

**Comment by aethior** [comment]
@tagliala `charts-diagrams (category)` label for this request?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
