### ISSUE TITLE
Icon Request: Allergens

### ISSUE THREAD

**Issue by d-lamers** [FortAwesome/Font-Awesome#5228]
This would be very useful for any webshop that has food related items. This is actually required by law as of 13 Dec 2014 in the Netherlands.

There are actually 14 required and they can be seen here:
![allergenenwetgeving en etiketten](https://cloud.githubusercontent.com/assets/3164508/5452167/06a9deca-8518-11e4-91b3-75f992c1ee7e.jpg)

**Comment by tagliala** [comment]
Sorry but I have to close this request and I have also to update contributing guidelines to deal requests like this.

Font Awesome is more about icons that are broadly applicable to the web to folks developing web applications. Your request contains a lot of icons that are related to a very specific field.

Feel free to contact Dave privately if you need a custom solution

Closing here

**Comment by forclaz** [comment]
Hi,
Inform about allergens there are on any food NOW is mandatory from 13 December 2014,  for all shops,  restaurants, etc. on  in all countries of UE - (UE) nº 1169/2011 -  therefore this question NOW i think that is global ambit , please can you to reopen this question?.

Thank you in advance
Eduardo

**Comment by coreyb** [comment]
I feel like this is a valid use case. Especially for food industry specific websites (i.e. grocers, restuarants, cooking, health, etc.)

**Comment by stratigos** [comment]
@tagliala I find that to be a somewhat limited perspective. I work for many medical applications which make use of many font awesome icons. @forclaz and @coreyb make excellent cases about food and food production websites as well. I am right this moment designing my own css styles for "allergen" medications, since font awesome lacks many much needed related medical icons. 

Keep in mind many medical applications are used by millions of end users, though always entirely behind an authentication page. There is a large industry wanting these icons, used on pages not searchable with your favorite web search ;)

**Comment by tagliala** [comment]
> I am right this moment designing my own css styles for "allergen" medications, since font awesome lacks many much needed related medical icons.

Please share your work here

**Comment by forclaz** [comment]
I completely agree,


My best regards

________________________________
De: Todd <notifications@github.com>
Enviado: sábado, 1 de octubre de 2016 0:00
Para: FortAwesome/Font-Awesome
Cc: aneto2400; Mention
Asunto: Re: [FortAwesome/Font-Awesome] Icon Request: Allergens (#5228)


@tagliala<https://github.com/tagliala> I find that to be a somewhat limited perspective. I work for many medical applications which make use of many font awesome icons. @forclaz<https://github.com/forclaz> and @coreyb<https://github.com/coreyb> make excellent cases about food and food production websites as well. I am right this moment designing my own css styles for "allergen" medications, since font awesome lacks many much needed related medical icons.

Keep in mind many medical applications are used by millions of end users, though always entirely behind an authentication page. There is a large industry wanting these icons, used on pages not searchable with your favorite web search ;)

-

**Comment by davewoodhall** [comment]
Sorry to reopen this request, @tagliala , but I can hardly imagine how "bath" or "wheelchair-alt" are more, to quote you, "broadly applicable". Allergies are important for restaurants, groceries and other food-related businesses, as @coreyblaser pointed out. Then again, I guess [over 1 million restaurants generating over 750 Billion US Dollars, in America alone](http://www.restaurant.org/News-Research/Research/Facts-at-a-Glance) is too broad.

_Excuse my arrogance, just wondering on the choice of words._

**Comment by holtkamp** [comment]
Dear community! Maybe it is time to come up with a PR base on a allergen-specific customization based on https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome?

I got little experience in this field, but am willing to contribute. As a starter, someone already got access to (open source) vector files of the 14 allergen icons? [A Dutch foundation](https://allergenen.sho-horeca.nl/allergenen-iconen-set) offered some, but bitmap only:

[SHO-Allergenen.zip](https://github.com/FortAwesome/Font-Awesome/files/779886/SHO-Allergenen.zip)

**Comment by ronan-paul** [comment]
+1 : allergens is now mandatory in France also. 

Every person having meals is concerned (seems quite a lot, does'n-it ?!)

Please reopen and consider this request.

**Comment by livingos** [comment]
Just to let everybody know that we have actually just release our Erudus allergy icons as an icon font under MIT here: https://github.com/Erudus/erudus-icons

We are using these in our applications.

**Comment by madivad** [comment]
This was closed over three years ago. How does one ask for a review of closed issues? 

Font Awesome has grown a lot in that time and there are inclusions of things that a lot more specific than this now. Alergen, food contents, vegetarian and Vegan specific are hot items in the food industry, not just now but for some time. 

It would be awesome for FA to incorporate these as a generic set and not a mish-mash of different thought processes.

**Comment by brechtvhb** [comment]
I'd also like allergen icons. But with a cross on it. For example gluten free:
https://thenounproject.com/term/gluten-free/837080/

**Comment by ditiem** [comment]
Pity Allergen icons are not yet in.

Is there any estimated time to include them or it is out of question?

**Comment by dylanbromby** [comment]
2024 — almost a decade since this request was opened — and Font Awesome is still in need of icons for allergens. All of the use cases previously mentioned are only more significant today.
