### ISSUE TITLE
Icon Request: fa-skill-level-[1-5]

### ISSUE THREAD

**Issue by mpalere** [FortAwesome/Font-Awesome#5254]
Hi, I'd like to request some icons to represent skill levels.  Perhaps 1-5 to represent the Dreyfus Skill Model (I actually need expert, senior, intermediate, junior but modeling after a published definition may be better)

http://en.wikipedia.org/wiki/Dreyfus_model_of_skill_acquisition

As I have no artistic ability whatsoever, I borrowed this pic from another site.  Perhaps the 1-5 could be represented by the number of bars in each icon?

Thank you!
![skill-icon](https://cloud.githubusercontent.com/assets/10182093/5488405/466073a2-868b-11e4-82b3-7aceade1c2fb.png)

**Comment by rmm5t** [comment]
> I'd could leverage 1870 for my work but was there any resolution to it?

I was just suggesting that efforts should be focused and consolidated on #1870 instead of keeping this request open (because it's basically a duplicate).

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Comment by tagliala** [comment]
I think this is the same as signal 1-5

https://fontawesome.com/search?q=signal&o=r
