### ISSUE TITLE
Icon Request: icon- vector or digitizing pen

### ISSUE THREAD

**Issue by marieneig** [FortAwesome/Font-Awesome#5293]
It would be nice to have a vector icon to oppose to the paint brush icon. It could be a vector shape or the digit pencil. See exemples :

http://www.flaticon.com/free-icon/vector-sketch-with-pointer-arrow_29306

http://www.flaticon.com/free-icon/vector-diagonal-line-with-box-edges_33365

http://www.iconarchive.com/show/outline-icons-by-designcontest/Vector-icon.html

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome! [Take a look at it here.](https://fontawesome.com/icons/bezier-curve?f=classic&s=solid)
