### ISSUE TITLE
Icon Request: fa-slidegallery

### ISSUE THREAD

**Issue by michaelsboost** [FortAwesome/Font-Awesome#5330]
![slider-icon](https://cloud.githubusercontent.com/assets/2473707/5603913/cd85e416-9360-11e4-988c-16a2c0528e6e.png)

I'm working on a web design application for touch users. I love using Font-Awesome for my apps and I noticed when it comes to html element components there's only a few to choose from and some elements like buttons, select element, textbox's, textarea's are not available. I also plan on adding moduals so users can add their twitter feed, lightbox, slider/fotorama, email, etc:

In this case I've already designed the icon for a gallery-slider modual (.svg & .png). Because I enjoy using Font-Awesome I thought I'd come here and request it.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
