### ISSUE TITLE
Icon Change Request: fa-paperclip

### ISSUE THREAD

**Issue by KolyaKorruptis** [FortAwesome/Font-Awesome#5336]
My request is for a vertical fa-paperclip with its open side on the bottom.

The existing fa-paperclip is rotated by default. Its open side is top left, which means if you were to actually use a paperclip in that position, you could only attach it to a sheet from the bottom right. Of course that's not how paperclips are normally used. And this hurts immediate recognisability.
It's a small thing, but you wouldn't display an envelope upside down, even though you may find it lying around like that in your drawer. 

While the icon can be brought into a position that makes more sense via CSS transform: rotate(225deg); it moves completely out of line then. So you have to apply more CSS to bring it back in line, etc. It would be nice if it worked right away.

**Comment by tagliala** [comment]
![image](https://cloud.githubusercontent.com/assets/556268/5606148/ff611dbe-9420-11e4-8b91-8a24ccdb1bec.png)

In all three cases I see the closed side at bottom and I'm fine with that. Could you please post an example of a proper paperclip?

**Comment by KolyaKorruptis** [comment]
![Image of paperclip](https://i.imgur.com/zDULFQq.png)
.fa-paperclip { transform: rotate(135deg) scaleX(-1); vertical-align: bottom; } 

I assume that the paperclip is often rotated to use available pixel space efficiently. However the above version is clearer due to less diagonal pixel lines, and more easily recognisable imo.

**Comment by tagliala** [comment]
I have to agree that a "straight" paperclip could facilitate the browser rendering

**Comment by lenamtl** [comment]
+1

**Comment by networkimprov** [comment]
Yes, pls add a vertical paperclip as suggested by @KolyaKorruptis. This is commonly used to indicate "attachment". The diagonal ones in 5.0.12 are cartoonish.

Also the endpoints of the line that defines the clip should be closer to the top, and the inner loop should be closer to the bottom. As is, the figure has a stubby appearance.

Thanks for your consideration.

**Comment by nhardia1** [comment]
> .fa-paperclip { transform: rotate(135deg) scaleX(-1); vertical-align: bottom; }

+1

**Comment by sensibleworld** [comment]
<img width="771" alt="Screen Shot 2021-03-30 at 12 59 42 PM" src="https://user-images.githubusercontent.com/529604/113027185-cd734d00-9157-11eb-86de-1b643ebc5862.png">

This is now available in the latest alpha release of version 6: http://fontawesome.com/download

**Comment by KolyaKorruptis** [comment]
@sensibleworld  Have you even [looked at a paperclip](https://www.google.com/search?&tbm=isch&q=paperclip) or did you draw this from memory?

**Comment by sensibleworld** [comment]
@KolyaKorruptis If you have some constructive feedback, that'd be great. But responding with snark isn't appreciated.

**Comment by KolyaKorruptis** [comment]
@sensibleworld This doesn't look like a paperclip, it's hardly recognisable. It wouldn't work as a paperclip in real life due to the huge margins between the inner and outer wire. And the original request for an upright paperclip was to avoid unnecessary diagonals which get smudged at small resolutions. But this adds unnecessary curves that will look bad at low res again.

[This is what the most common type](https://i.imgur.com/XVUfYzW.jpg) of paperclips looks like. It hardly has any curves. Wires are close to grip the paper, because that's its sole purpose. Rotate this 180deg, make a vector that vaguely looks like it and you're done.

**Comment by sensibleworld** [comment]
Alrighty. Been working on some refinements to the version 6 paperclip icon(s).

For reference, here's the version 5 icon:

<img width="1297" alt="Screen Shot 2021-04-19 at 9 46 48 AM" src="https://user-images.githubusercontent.com/529604/115247392-c0ad9d80-a0f4-11eb-8be0-a71fd3797114.png">

And because we've heard from others that changing the icon orientation isn't ideal, we're going to keep the current angle. This has the benefit of showing a "longer" paperclip which is a bit more in line with the actual physical object. We've also added in the new `thin` style. Here's the working draft of the version 6 icon:

<img width="1296" alt="Screen Shot 2021-04-19 at 9 47 00 AM" src="https://user-images.githubusercontent.com/529604/115247577-e63aa700-a0f4-11eb-9616-0a3a4c4d0723.png">

But we'd also like to include an alternate version of the paperclip that's vertically oriented (as originally requested in this thread).

<img width="1298" alt="Screen Shot 2021-04-19 at 9 47 09 AM" src="https://user-images.githubusercontent.com/529604/115248220-7ed12700-a0f5-11eb-9a53-9dc7781ba908.png">

Because we're limited to a 16px height, this icon is admittedly a bit "stubbier" than would be ideal (at least in the `solid` style), but making it any less-wide would compromise it's legibility at smaller sizes/resolutions.

Here's the current pixel-level view:

<img width="1493" alt="Screen Shot 2021-04-19 at 9 49 52 AM" src="https://user-images.githubusercontent.com/529604/115249179-5bf34280-a0f6-11eb-8ace-f3cf3908b90b.png">

**Comment by sensibleworld** [comment]
There are still some refinements to make, especially to the diagonal icons and the length of the inner wires, but I wanted to share progress and get any feedback before we locked these in for the beta.

**Comment by KolyaKorruptis** [comment]
Thanks @sensibleworld, looking good. Especially the second to last in the pixel view. And I welcome the decision to include both versions. The pixel view is at 16px font-size?

**Comment by sensibleworld** [comment]
Yup. The pixel-views are at the 16px sizing and the second to last icon is our light style, which uses 1px stroke weights.

**Comment by sensibleworld** [comment]
These have been updated in version 6: https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=paperclip&s=thin
