### ISSUE TITLE
IE9 https issue. Black square outlines display in place of the icons

### ISSUE THREAD

**Issue by paulh1971** [FortAwesome/Font-Awesome#5343]
Hello, In IE9, if the url has ‘http://’ the icons display great, but if it is ‘https://’ then squares show up in place of the icons. I went to the Font Awesome website and changed it from ‘http://’ to ‘https://’ and the same issue happened there, so I am not sure if there is a fix for this. I have searched for many hours with no solution to the problem. Many people have reported the issue. Some have solutions and some don't. For the ones that do, either we already have that solution in place but it doesn't work, or we tried the solution they suggested and it still does not work.

Does anyone have an actual working solution to this issue? I would be greatly appreciative is someone could possibly help out with a solution.

Thanks so much,
Paul

**Comment by tagliala** [comment]
If i well remember this is a duplicate

**Comment by paulh1971** [comment]
Your response was not helpful at all. I explained to you that I have searched and found the duplicates, but they did not give an actual fix. I guess your response means that you do not know of a solution to the problem. You could have just said that.

Sent from my iPad

On Jan 6, 2015, at 3:46 AM, Geremia Taglialatela <notifications@github.com<mailto:notifications@github.com>> wrote:


If i well remember this is a duplicate

**Comment by tagliala** [comment]
I'm looking for existing issues related to IE9. I'm also trying to remember where I read of this issue but at the moment I can't remember, sorry

**Comment by marcoo** [comment]
+1

**Comment by cbebry** [comment]
We are also encountering this same issue. Occurs for all IE versions emulating from IE9 to Edge

**Comment by tagliala** [comment]
> In IE9, if the url has ‘http://’ the icons display great, but if it is ‘https://’ 

There are issues with IE and https when icons are served with `no-cache` option in Pragma header;

Ref: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#im-hosting-fonts-on-my-server-and-icons-dont-show-up

I'm going to assume that this issue is related to the aforementioned problem

Closing here

If this is still relevant, please open a new request by filling out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md) and provide as many information as you can, including a reproducible test case
