### ISSUE TITLE
Icon request: icon-tfl

### ISSUE THREAD

**Issue by dansimau** [FortAwesome/Font-Awesome#5351]
Hi there!

Slightly related to #14; this request is for a TfL (Transport for London) brand icon.

The use-case is that you are using a travel icon set and you are specifically targeting London, you  may want to use the TfL icon to represent a journey on that travel network.

Example:

![TfL logo](http://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Tfl_no-text.svg/500px-Tfl_no-text.svg.png)
http://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Tfl_no-text.svg/500px-Tfl_no-text.svg.png

Not 100% sure on whether this is relevant to enough people to be included, but I thought I would add it to be discussed.

Thanks!

**Comment by Jack95uk** [comment]
I would like to +1 this. It would be incredibly useful to me as there are sections on transport in London that I include in my websites, and each section used a png tile which we are replacing with html and FontAweseome characters. This logo will be instantly recognisable by the site's users and will help them navigate to the transport section.

Thanks,

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
