### ISSUE TITLE
not working on firefox 32.0.3

### ISSUE THREAD

**Issue by raxit2009** [FortAwesome/Font-Awesome#5352]
i am not able to get the font icon trying all about:config or add 

-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;  

or 

giving full path of css file doc type change but still i am not able to get the icon

so please help me to get resolve this issue.

![awsmfont](https://cloud.githubusercontent.com/assets/1736662/5645233/de505512-9692-11e4-8a99-2a2ea0c7afbf.png)

Thanks,
Rakshit Joshi

**Comment by tagliala** [comment]
Of course I can't confirm.

Please read our troubleshooting guidelines: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

Since this is a support request, please consider using stackoverflow

If you think there is an issue with fontawesome, please provide a fiddle or a public website showing the issue

closing here
