### ISSUE TITLE
Icon request: icon-hl-arrow

### ISSUE THREAD

**Issue by naidiaph** [FortAwesome/Font-Awesome#5353]
The usage cases for this icon would be:
- A more modern look in place of **fa-external-link**  and **fa-external-link-square**

A rough sketch (with arrow line weights exactly as in picture)
http://pasteboard.co/bBTnYpV.png

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
