### ISSUE TITLE
Icon Request: macbook, ipod, iphone, ipad, imac

### ISSUE THREAD

**Issue by hronik** [FortAwesome/Font-Awesome#5360]
Want these icons in next update.

**Comment by tagliala** [comment]
Sorry can't keep this open.

This request doesn't meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

Please split this request in multiple individual request and provide examples.

Examples are needed because I think that iphone/ipad, imac and macbook are already here:
http://fontawesome.io/icon/mobile/
http://fontawesome.io/icon/desktop/
http://fontawesome.io/icon/laptop/

Closing here
