### ISSUE TITLE
Icon Request: fa-pet-bottle

### ISSUE THREAD

**Issue by T4boOo** [FortAwesome/Font-Awesome#5365]
Hello everyone.
I am developing a website for recycling. (Www.reciclagemlunardi.com.br) And When trying to customize my icons for the main categories of recycling work (Metals, Stationery, Plastic and Electronics) was no option for a plastic icon (eg a bottle pet). Will you can help me with this problem?

**Comment by tagliala** [comment]
hi @T4boOo 

this request is fine and there are no duplicates. It means that you are the only one to request this icon but it doesn't mean that it will be never included in the fontawesome core, because popularity is not the only thing taken in account.

If you need this icon, my suggestion is to consider a custom build of fontawesome.

Take a look at:
https://fonticons.com/ (by Dave - adding custom icons is not possible in the free tier)
http://fontello.com/
http://icomoon.io/app/#/select
http://fontastic.me/

**Comment by aethior** [comment]
Hi @T4boOo,

`fa-bottle-water` icon has been added in v6.1.0.
Check https://fontawesome.com/icons/bottle-water

Regards.

cc/ @tagliala

**Comment by aethior** [comment]
@tagliala check here please.
