### ISSUE TITLE
Icon request: fa-briefcase-open

### ISSUE THREAD

**Issue by ph0rque** [FortAwesome/Font-Awesome#5366]
Hello,

I'd like to request an open version for the briefcase, perhaps something like this:

![briefcase-open](https://cloud.githubusercontent.com/assets/1257/5686906/4a9300a2-9815-11e4-96db-2cfd89cd7cab.png)

I am working on an application where I have collections of items, where I use the `fa-folder` icon  for all the collections, and the `fa-folder-open` icon to signify an active collection.  There are also projects containing zero or more of these items. I am using the `fa-briefcase` icon to represent a collection of projects. It would be great to have a `fa-briefcase-open` icon for an active project collection.

Thanks!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
