### ISSUE TITLE
Icon request: fa-scoreboard

### ISSUE THREAD

**Issue by AdamForst** [FortAwesome/Font-Awesome#5392]
An icon representing a scoreboard could be used by teams, leagues, or anyone else displaying a comparative table of rankings or scores on their website or application.  

I am not certain of what the best representation of this would be, below are some ideas

![icon-scoreboard](https://cloud.githubusercontent.com/assets/10541861/5752619/564be5d6-9c47-11e4-87d3-c1906d973a7d.png)

**Comment by AdamForst** [comment]
It could just be a minor modification of the calendar icon 

http://fortawesome.github.io/Font-Awesome/icon/calendar-o/

**Comment by mshovelt** [comment]
+1

**Comment by lordmilutin** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
