### ISSUE TITLE
Icon Request and suggestion for paid icons service addition

### ISSUE THREAD

**Issue by aagouda** [FortAwesome/Font-Awesome#5415]
First, I'd say thank you for your excellent work. Second I don not know if this is available or not, but I'd suggest you to have a single page/form to accept suggestions for commercial icons or paid service to add specific icons and also to have a vote on users suggested icons.

My suggestions for new icons:

in the Text editor you need
Increase font icons which is A+
decrease font icons which is A-

For web applications:

Blog icon
Classifieds icon
Auction icon
Banners or ads icon
Yellow pages icon
Real state icon
Business icon
Art icon
Antiques icon
Clothes icon
Dolls & Bears icon
Collectables icon
Gift cards icon
Gardens icon
Jewelry icon
Pets icon
Stamps icon
Tickets icon
Travel icon
Boats icon
Fashion icon
Sports icon
Swap/Trade icon
Events icon
Community icon
Portal icon
Charity icon
Automotive icon
Toys icon
Mountain icon
River icon
Desert icon
Satellite icon
School icon
Bridge icon
Canon icon
Gun icon

More to come...

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
