### ISSUE TITLE
Icon request: candle-light-on/candle-light-off 

### ISSUE THREAD

**Issue by samuelladapo** [FortAwesome/Font-Awesome#5484]
i want to use this icon as a like and dislike button on my social network's site and as its logo
![christmas218](https://cloud.githubusercontent.com/assets/10585798/5906575/f57df928-a598-11e4-9174-44a05ca2059f.png)

**Comment by samuelladapo** [comment]
when will i get reply?

**Comment by tagliala** [comment]
Hi @samuelladapo , please take a look at this wiki: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome#new-icons

Feel free to edit it if there are mistakes I'm not an English native speaker

**Comment by samuelladapo** [comment]
this is not so good

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/candle-holder?f=classic&s=solid)
