### ISSUE TITLE
Icon Request: icon-cube-square

### ISSUE THREAD

**Issue by sentanilesh** [FortAwesome/Font-Awesome#5494]
![cube_square](https://cloud.githubusercontent.com/assets/10580103/5918152/6b6951fc-a64b-11e4-8108-3235852ecea4.png)

It is Simply Box type / Folder Type for Categorized Directories.

**Comment by aethior** [comment]
Hi @sentanilesh,

This icon was added in v4.1.0.
Check https://fontawesome.com/icons/cube

Regards.

cc/ @tagliala

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome! [Take a look at it here.](https://fontawesome.com/icons/cube?f=classic&s=solid)
