### ISSUE TITLE
Icon Request: list-user

### ISSUE THREAD

**Issue by Zxurian** [FortAwesome/Font-Awesome#5514]
Use case would basically be lists that are specifically tailored to a/the user.

Example:
![example](https://i.imgur.com/X1eAaGo.png)
Instead of having a similar list icon to "All Titles", it would more clearly represent a list that is tailored to a user.

Example Icon:
![example](https://i.imgur.com/hrNDb8u.png)
(yes, my copypasta skills are not the greatest, but you get the idea)

**Comment by tagliala** [comment]
this will hardly fit the base size of 14px

**Comment by Zxurian** [comment]
As I said, that was just an example to get the idea, but since the idea isn't enough. Here's a photoshopped verison. Fits 15x14, copying directly from font-awesome's web page.
![img](http://puu.sh/f9T77/13c9756307.png)

**Comment by sensibleworld** [comment]
@Zxurian It looks like the images you referenced are no longer available. Would you mind adding them again?

**Comment by Zxurian** [comment]
been a while, but I added a new screen screenshot of the effect.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
