### ISSUE TITLE
Icon Request: fa-queue

### ISSUE THREAD

**Issue by followerz** [FortAwesome/Font-Awesome#5515]
There is no icon to represent queue. Icon of people staying in queue (like in supermarket or McDonalds) would be nice.

Use examples: displaying queue of server tasks, queue of messages to be sent etc.

**Comment by kwendenarmo** [comment]
+1

**Comment by redben** [comment]
How about using one of fa-ellipsis-v or fa-bars. they look like a queue / stack..etc ?

**Comment by Petercopter** [comment]
+1

**Comment by opensourceame** [comment]
+1

**Comment by edwinyzh** [comment]
+1

**Comment by andersjonsson** [comment]
👍

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/rectangle-history?f=classic&s=solid)
