### ISSUE TITLE
Icon Request: fa-Parkways

### ISSUE THREAD

**Issue by qopel** [FortAwesome/Font-Awesome#5516]
It would be cool to have parkway icons for directions

![640px-robert_moses_cswy_shield svg](https://cloud.githubusercontent.com/assets/8602426/5947138/041b82ae-a709-11e4-8294-3420dfce5a84.png)
![northern parkway](https://cloud.githubusercontent.com/assets/8602426/5947140/0525de6a-a709-11e4-8579-e236137d5bd3.jpg)
![loop parkway](https://cloud.githubusercontent.com/assets/8602426/5947146/07ceff3e-a709-11e4-84e5-c089432abe4a.jpg)
![heckscher parkway](https://cloud.githubusercontent.com/assets/8602426/5947147/0922fd36-a709-11e4-87b1-2dd64c0a0cfe.jpg)
![sagtikos](https://cloud.githubusercontent.com/assets/8602426/5947149/0a4a179e-a709-11e4-9b9c-d28699a03996.jpg)
![ocean pkway](https://cloud.githubusercontent.com/assets/8602426/5947158/0d95fe2c-a709-11e4-903b-66a20c047adf.jpg)
![wantagh parkway](https://cloud.githubusercontent.com/assets/8602426/5947161/0eb3142a-a709-11e4-98b6-87dc21291e8e.jpg)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
