### ISSUE TITLE
Icon Request: fa-resourcepack fa-resourceitem

### ISSUE THREAD

**Issue by MickeyElliott** [FortAwesome/Font-Awesome#5526]
I have an admin console that manages downloadable resources that people can queue into their carts. I would love to have 2 icons. One that represents a resource item (Generic product item). And another that represents a Generic resource package (Generic container that has product items in it).

A cart or shopping basket don't always represent the experience a user has on a website that is delivering resources of a specific type.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
