### ISSUE TITLE
Icon Request: fa-move-out-of-folder

### ISSUE THREAD

**Issue by shemani** [FortAwesome/Font-Awesome#5549]
Indicates a document is to be moved out of folder. Technically, what I would really like to see is document moved out of the shelf but I can't imagine how to create that. Attached the image for the former. 
![move](https://cloud.githubusercontent.com/assets/5160083/5990755/4b968d80-a98f-11e4-8ddf-309d12e418bf.png)

**Comment by renemaas** [comment]
Best thing in my opinion would be to combine file, file-o, folder, folder-o, folder-open and folder-open-o with the arrow of sign-out.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
