### ISSUE TITLE
Icon request: fa-shirtm, fa-shirtw

### ISSUE THREAD

**Issue by Haddicus** [FortAwesome/Font-Awesome#5563]
Great for apparel related links. Versions for men and women shirts
![shirt](https://cloud.githubusercontent.com/assets/1945494/6005393/cc7db90c-aabe-11e4-8b82-6f8f643668c0.PNG)

**Comment by LauritzT** [comment]
Maybe ```fa-shirt-m``` and ```fa-shirt-f``` would be better?

**Comment by tagliala** [comment]
related to #715

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue
