### ISSUE TITLE
Icon request: fa-text-foreground, fa-text-background

### ISSUE THREAD

**Issue by cnicodeme** [FortAwesome/Font-Awesome#5570]
Hi,

Thank for FA, it's awesome! :)

I'm building a text editor using Font Awesome, and I was unable to find the icons for settings foreground / background color.

Ideally, the "Foreground" color would be an "A" with an underline black line.
The "background" icon would be a white "A" with a black background.

Thank you :)

**Comment by elenamg75** [comment]
+1

**Comment by supertassu** [comment]
Yes. 
+1

**Comment by mbranicky** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
