### ISSUE TITLE
Icon request: GHS Hazard Pictograms

### ISSUE THREAD

**Issue by SverkerSbrg** [FortAwesome/Font-Awesome#5571]
Hello!

I'm working on a project involving hazard classification and the addition of the GHS Hazard Pictograms to FA would atleast for me be great. To enable two colors by using a separate glyph for the frame and the stacked class would make it even better!

https://www.osha.gov/dsg/hazcom/pictograms/

Cheers!

**Comment by tagliala** [comment]
Sorry @SverkerSbrg  but I have to close this request and I have also to update contributing guidelines to deal requests like this.

Font Awesome is more about icons that are broadly applicable to the web to folks developing web applications. Your request contains 9 icons that are related to a very specific field.

Feel free to contact Dave privately if you need a custom solution

Closing here

**Comment by dnagirl** [comment]
Actually, GHS symbols are used globally in workplace safety programs. For example, WHMIS (the Canadian workplace safety program) requires these symbols on every hazardous substance in a workplace. This means everything from photocopier toner to paint. It's not just about the chemical or scientific fields. It's **all** workplaces.

Right now I'm working on an inventory application for my company. Having the GHS symbols as part of FA would definitely make my life easier. 

Another use case would be for sellers or shippers of hazardous materials.

**Comment by myxptlyk** [comment]
I actually came here looking for GHS and other Safety Related type of icons.  GHS Icons are very standard globally and across industry, and are even driven by the United Nations for global applicability, and it is shame they are not being offered.  In my company we are developing web applications, and I've found a real lack of safety related icons in font awesome.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry but we do not accept requests for icon sets in the free repository because they are hard to manage.

If someone here is an FA Pro user, they could request a set in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
