### ISSUE TITLE
Icon Request: icon-France

### ISSUE THREAD

**Issue by HugoMnd** [FortAwesome/Font-Awesome#5576]
Hello,
I would like to know if you could create an icon with the shape of the France. It will be used to illustrate the "made in France" description. I just need a shape, and you can also create a version of the shape in a circle like your other icons, and other country shapes if you want. I join you an image of what it looks like.
Thank you for considering my request :)

![image](https://cloud.githubusercontent.com/assets/10837412/6029903/d6c059ca-abf3-11e4-9847-7a11250d9578.jpg)

**Comment by ryanknutson** [comment]
You could use an SVG of France, and scale it down as needed.

**Comment by tagliala** [comment]
Sorry I have to close this one because there are too many countries and those silhouettes have a lot of points which will noticeably increase the font size.

I should suggest you to consider an SVG solution

Also check out http://datamaps.github.io/

Please refer to this comment: #281 (comment) for further information
