### ISSUE TITLE
Icon Request: fa-cruise

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#5628]
Can u provide to create this logo?
Many thanks
Fabio

![valtorta_logo-07 1](https://cloud.githubusercontent.com/assets/2734866/6124934/d06f1d4a-b111-11e4-92c3-ee2305f6ccdf.png)

**Comment by lenamtl** [comment]
Hi, FYI there is a boat in the latest version.

**Comment by fabiosala85** [comment]
Yes but it is very similat to a yacht. 
The attach image is similar to a cruise.
It is important to male a difference for a marine company.
Can you make this difference? 
Please let me know
Fabio

**Comment by lenamtl** [comment]
I prefer your suggestion.
The one provided in the new package is not very clear, 
without ship wording I'm not sure I will recognize it as a shop or yacht...

**Comment by lenamtl** [comment]
+1

**Comment by yachtmakler** [comment]
+1 for yacht and/or sailing boat

**Comment by G-Driver** [comment]
+1

**Comment by xmuskrat** [comment]
+1

**Comment by xmuskrat** [comment]
Would prefer from side and not at perspective angle.

Examples:

![image](https://user-images.githubusercontent.com/59917/61471437-9cc59280-a937-11e9-8205-1e1083802e7b.png)

![image](https://user-images.githubusercontent.com/59917/61471478-a818be00-a937-11e9-879c-028ce25971d1.png)

**Comment by xmuskrat** [comment]
Would prefer side view instead of other perspective icons so it matches other vehicle icons.

Like:

![image](https://user-images.githubusercontent.com/59917/61471683-047bdd80-a938-11e9-9ccf-dbca440268b7.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
