### ISSUE TITLE
Icon request: icon-columns

### ISSUE THREAD

**Issue by erralb** [FortAwesome/Font-Awesome#5756]
Hi,

For responsive grid / backoffice purposes. it would be great to have some basic "proportion" icons, like this : 

![columns](https://cloud.githubusercontent.com/assets/790992/6324600/70083baa-bb3c-11e4-87c7-67e3cdab7d6d.png) (screenshot taken from the unyson framework pag builder)

Without the numbers of course... it could be something like fa-columns-1, fa-columns-1-2, fa-columns-1-3, etc

What do you think?

**Comment by jbethke** [comment]
+1

**Comment by ianchadwick** [comment]
+1

**Comment by gabrielmerovingi** [comment]
+1

**Comment by sfhaney** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/columns-3?f=classic&s=solid)
