### ISSUE TITLE
fa-mouse

### ISSUE THREAD

**Issue by WS-Theme** [FortAwesome/Font-Awesome#5763]
I have seen some people are also requesting this ... general Mouse Cursors would be great!!! This can be a whole new Set, with for example:

fa-mouse-right
fa-mouse-left
fa-mouse-move
fa-mouse-grab
...

Especially a "grab" and "grabbed" Cursor like Google Map it has would be great!
This can also be very useful if you use Font Awesome together with this Script:

https://jwarby.github.io/jquery-awesome-cursor/

Cheers, Oli

**Comment by JeffreyHyer** [comment]
:+1:

**Comment by zambotn** [comment]
+1

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
