### ISSUE TITLE
Icon Request: fa-switzerland

### ISSUE THREAD

**Issue by leonardstalder** [FortAwesome/Font-Awesome#5765]
an icon for Switzerland

**Comment by tagliala** [comment]
Are you asking for a flag or for the country silhouette?

**Comment by leonardstalder** [comment]
country silhouette

**Comment by leonardstalder** [comment]
country silhouette

2015-02-23 21:40 GMT+01:00 Geremia Taglialatela <notifications@github.com>:

> Are you asking for a flag or for the country silhouette?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FortAwesome/Font-Awesome/issues/5765#issuecomment-75627063>
> .
>



-- 
Meilleures salutations.

Léonard Stalder

_________________________________________________

Léonard Stalder
Pravidondaz
1991 Salins
079 / 386 00 04

**Comment by tagliala** [comment]
@leonardstalder

Sorry I have to close this one because there are too many countries and those silhouettes have a lot of points which will noticeably increase the font size.

I should suggest you to consider an SVG solution

Also check out http://datamaps.github.io/

Please refer to this comment: #281 (comment) for further information
