### ISSUE TITLE
Icon Request: fa-icon-meetingpoint

### ISSUE THREAD

**Issue by ianpottier** [FortAwesome/Font-Awesome#5770]
Hi,
I would need the meeting-point icon to add another type of "location" icon without using a map marker.
Especially, I would like to represent locations where people bring their waste, so meeting point and bringing point do some overlap here...
Example:
![image](https://cloud.githubusercontent.com/assets/11091038/6349059/a4abca12-bc26-11e4-9dbb-735198bccb58.png)

**Comment by bertoost** [comment]
+1

**Comment by paulvidal** [comment]
+1

**Comment by jcastrov** [comment]
More than 3 years with no answer :(

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/arrows-to-circle?f=classic&s=solid)
