### ISSUE TITLE
Icon request: icon-fist

### ISSUE THREAD

**Issue by dangnelson** [FortAwesome/Font-Awesome#5777]
Raised Resistance Fist to be used to represent activism.

![fist svg](https://cloud.githubusercontent.com/assets/8430446/6363787/a18704ba-bc6b-11e4-94b7-3686a7f30aab.png)

**Comment by akuataja** [comment]
This is done and can be closed https://fontawesome.com/icons/fist-raised.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/hand-fist?f=classic&s=solid)
