### ISSUE TITLE
Icon request: icon-elearning

### ISSUE THREAD

**Issue by sagarkachare** [FortAwesome/Font-Awesome#5778]
We have some E-learning projects which use this icon extensively, so I want this icon to be included into font awesome.

![elearning](https://cloud.githubusercontent.com/assets/5442943/6368133/d9768f1e-bcff-11e4-81a9-a01969621ed7.png)

**Comment by tagliala** [comment]
I don't like the title (quite abstract) and this icon is hard to fit in 14px size

leaving this open, but I should advise you to take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
