### ISSUE TITLE
Icon request: icon-cone, icon-uncone

### ISSUE THREAD

**Issue by veronikerr** [FortAwesome/Font-Awesome#5792]
Looking for an icon to represent a cone, both a "folded" and "unfolded" one like so:

![cone](https://cloud.githubusercontent.com/assets/11213838/6395118/63f5f6ee-bda4-11e4-9ade-2ef10584b1a6.jpg)

Our specific goal is to have an icon to represent an IES file, specific to the lighting industry. This way it could apply to multiple areas since it's a pair of simple shapes.

Thank you!
☺

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
