### ISSUE TITLE
Icon Request: fa-dutchbutton

### ISSUE THREAD

**Issue by macguyver76** [FortAwesome/Font-Awesome#5827]
I would like to see a fa-dutchbutton.
The dutchbutton is a regional symbol in the province of zeeland in the netherlands.
Originally it was a piece of jewelry (for the upperclass when made of gold)  back in the days.. now it has become an icon.
you can find dutchbutton images, jewelry and more in every corner around here.

I would like to use it as a button and clickon for my website to respresent the products i sell

Hope the material attched is enough.

Regards,

![dutchbutton](https://cloud.githubusercontent.com/assets/11271515/6441446/41605b46-c0e8-11e4-8a02-c2b4d74d1d10.jpg)
![proefprint](https://cloud.githubusercontent.com/assets/11271515/6441647/2f6c4f06-c0ea-11e4-83ae-16761d8b1ea4.jpg)

**Comment by tagliala** [comment]
hmmm it seems too complex, maybe an icon font is not the best choice for this icon.

I will keep this open, but you should consider an .svg based solution

**Comment by macguyver76** [comment]
@tagliala perhaps a simplified version is doable? (see attached)
any effort to see this fa added would be very appreciated.

![zeeuws](https://cloud.githubusercontent.com/assets/11271515/9521574/ee04bc16-4ccf-11e5-904e-72a9c0e0fd64.jpg)

Regards,

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
