### ISSUE TITLE
Icon Request: fa-pointer-circle

### ISSUE THREAD

**Issue by saqueib** [FortAwesome/Font-Awesome#5886]
Touch Mouse pointer with clicked pointer (ripple effect). It will be very helpful for Shop Online icon

**Comment by tagliala** [comment]
refers to #1095

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/bullseye-pointer?f=classic&s=solid)
