### ISSUE TITLE
Icon Request: icon-npr

### ISSUE THREAD

**Issue by acpmasquerade** [FortAwesome/Font-Awesome#5891]
Rupee is a currency in Nepal also, but the symbol of INR can't be used.

Rs (rupees)
Re (rupee)
रु (currently used symbol)

**Comment by SantoshSah** [comment]
Hello @acpmasquerade , did you get it to work? How can we use रु?

**Comment by techneeraz** [comment]
any updates on this ? when are we going to get Nepali Rupees icon ?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
