### ISSUE TITLE
Icon request: icon-job (job text with magnifying glass)

### ISSUE THREAD

**Issue by caplangues** [FortAwesome/Font-Awesome#5909]
Hi,
It would be great if we could find an icon for "recruitment".

Thanks

**Comment by tagliala** [comment]
could you please post an example?

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please and thank you if you include the following:
> Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

**Comment by caplangues** [comment]
Some examples :
http://www.leesbadminton.ca/images/job-icon.png (my favorite)
http://www.colourbox.com/preview/3647492-386922-job-icon-glass-blue-isolated-on-white-background.jpg
http://newmexicanvoice.com/wp-content/uploads/2011/04/Jobs-magnifying-glass-icon.jpg


De : Geremia Taglialatela [mailto:notifications@github.com]
Envoyé : mardi 10 mars 2015 12:56
À : FortAwesome/Font-Awesome
Cc : Samuel Desloges
Objet : Re: [Font-Awesome] Icon request: icon-jobs (#5909)


could you please post an example?

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

Please and thank you if you include the following:
Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
