### ISSUE TITLE
Icon Request: fa-angle-[direction]-thin

### ISSUE THREAD

**Issue by adamevosite** [FortAwesome/Font-Awesome#5912]
Hi,

I would love a thin version of your angle icons, a lot of our website designs look so much better with a thin arrow rather than a fat one and it would be great if there was one in your library.

![arrow-thin](https://cloud.githubusercontent.com/assets/8913973/6574204/81cc6174-c71a-11e4-9843-1f13fc3dbcf8.png)

Thanks
Adam

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.]()
