### ISSUE TITLE
Icon Request: fa-automatic

### ISSUE THREAD

**Issue by moussa-mokhtari** [FortAwesome/Font-Awesome#5924]

**Comment by tagliala** [comment]
Could you please provide an example?

**Comment by MMokhtari** [comment]
Like this one (automatic config ): 
![automation-128](https://cloud.githubusercontent.com/assets/9805952/6675893/313c528c-cc24-11e4-8dcb-b6a41e24d186.png)

**Comment by tagliala** [comment]
hmmm... This one http://fontawesome.io/icon/magic/ could be useful

**Comment by looeee** [comment]
I think something similar to this would be more standard for "automatic".

![auto](https://user-images.githubusercontent.com/5307958/65497988-523b3600-dee5-11e9-9db0-ebfab146d3ea.jpg)

 Currently I need this for an orientation toggle on a webapp. It will have three settings, landscape, portrait, and auto. I'm using the fa-mobile-alt icon for the first two settings (rotated 90 degrees for landscape). But I can't find a good icon for the auto setting, and the "magic" icon is definitely not suitable.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
