### ISSUE TITLE
Icon Request: icon-beetle, icon-beetle-convertible

### ISSUE THREAD

**Issue by Beetlix** [FortAwesome/Font-Awesome#5969]
Hello Everybody!
We use the Font-Awesome Iconfamiliy in our forum (WBB4.0) to identify new entries in the forum.
Its a Forum for classic Bugs, New Beetle and the actual Beetle.
The Idea: Take the New Beetle Logo (roof closed) for no news available and for new entries the open roof New Beetle.
![font-awesome-beetle](https://cloud.githubusercontent.com/assets/11489245/6656950/1e961ab2-cb3b-11e4-82b9-dc0c193a422a.jpg)
An for the Convertible, see my Avatar.

Greets
Andreas

Update 2015/03/16: I found a better draft version:
![nb_nbc](https://cloud.githubusercontent.com/assets/11489245/6671471/9c393380-cc05-11e4-9b11-1704aa22ffd7.jpg)

**Comment by G-Driver** [comment]
Cool idea +1

**Comment by dngunraj** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
