### ISSUE TITLE
Icon Request: fa-casting

### ISSUE THREAD

**Issue by JoeBoyle** [FortAwesome/Font-Awesome#6006]
![image](https://cloud.githubusercontent.com/assets/11560066/6736772/544ab0d2-ce3d-11e4-8c44-c8aef320272f.png)

Title your new issue Icon request: icon-name (e.g., Icon request: icon-casting).
Include a few use cases for your requested icon. How do you plan on using it? Moodle Courses Training
Attach a single color image or two that represent the idea you're going for. ![image](https://cloud.githubusercontent.com/assets/11560066/6736772/544ab0d2-ce3d-11e4-8c44-c8aef320272f.png)

Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ok

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
