### ISSUE TITLE
Icon Request: fa-machining

### ISSUE THREAD

**Issue by JoeBoyle** [FortAwesome/Font-Awesome#6007]
![image](https://cloud.githubusercontent.com/assets/11560066/6736885/1fec60c8-ce3e-11e4-91fc-0ea22ff21b32.png)

Icon-machining

Moodle course industrial training

**Comment by tagliala** [comment]
really complex to fit in 14px icon size

**Comment by JoeBoyle** [comment]
Thanks 
Perhaps this will work

![image](https://cloud.githubusercontent.com/assets/11560066/6770072/cc507982-d08a-11e4-9dbe-7a86bcb7696f.png)

I see a new category starting for industrial or manufacturing  icons

Joe

**Comment by JoeBoyle** [comment]
Can also leave off laser beam and burst of 
![image](https://cloud.githubusercontent.com/assets/11560066/6770989/aa799740-d0a7-11e4-9d6b-c4276ba7f59a.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
