### ISSUE TITLE
Icon Request: fa-fabrication

### ISSUE THREAD

**Issue by JoeBoyle** [FortAwesome/Font-Awesome#6008]
![image](https://cloud.githubusercontent.com/assets/11560066/6736989/e8504dae-ce3e-11e4-8b44-2c5819d5a999.png)

For use in Moodle course industrial training

**Comment by dngunraj** [comment]
+1

**Comment by JoeBoyle** [comment]
Nice, Thank you- are you up for a new category of manufacturing or industrial icons?

**Comment by dngunraj** [comment]
Yea, that would be awesome.

-----Original Message-----

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
