### ISSUE TITLE
Icon request: fa-extension

### ISSUE THREAD

**Issue by amcgregor** [FortAwesome/Font-Awesome#6049]
Desired look is a vector outline version of the "Extension" icon from classic Mac OS.  Additionally, a filled version.  Default orientation: horizontal.  (Looks like a square jigsaw piece with a tab extending from the right, and cutout inset in the left such that they would fit if overlapped, lightly rounded corners.)  Useful when combined with other icons overlaid, should be rotatable.

I.e.: ![mac-os-9-boot-screen-with-extensions](https://cloud.githubusercontent.com/assets/76750/6788145/f7e9aa44-d16d-11e4-92bd-ca2d07619152.jpg)

**Comment by seanfrasure** [comment]
It would look better as a flat icon.

**Comment by amcgregor** [comment]
@seanfrasure Indeed it would. :)  (That screenshot is from OS 9 during startup, i.e. the source material.)

**Comment by seanfrasure** [comment]
So you want a kind of puzzle thing, that can rotate, and combine with other icons. (Right?) I'll work on it and make a PR.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
