### ISSUE TITLE
Icon Request: fa-icon-bowling-ball-with-pins

### ISSUE THREAD

**Issue by monksee** [FortAwesome/Font-Awesome#6058]
![leisure_club_mob](https://cloud.githubusercontent.com/assets/9542969/6837484/a1f8f288-d344-11e4-9399-c01c8d4b2781.png)
I plan to use the bowling icon on a mobile website for a leisure club as you can see in the pic.
I plan to use the pool table/snooker icon on a mobile website for a leisure club as you can see in the pic.

thanks a lot 

Sarah

**Comment by tagliala** [comment]
Could you please split this request in two individual requests? You can use this one for bownling and open a new one for pool table

Since there aren't old and popular request for those icons, I should suggest you to consider a custom build of Font Awesome if you need them in a short while: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by monksee** [comment]
yes i will.. thank you.. I will try that custom build thanks :+1:

**Comment by mervinva** [comment]
+1

**Comment by tagliala** [comment]
We have individual icons for this request: https://fontawesome.com/icons/bowling-pins?style=solid
https://fontawesome.com/icons/bowling-ball?style=solid

**Comment by aethior** [comment]
Hi @monksee,

This icon has beed added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/bowling-ball-pin

Regards.

cc/ @tagliala
