### ISSUE TITLE
Icon Request: database-plus, database-times, database-check, database-*, etc.

### ISSUE THREAD

**Issue by AlainD-** [FortAwesome/Font-Awesome#6072]
Hi it would be nice to have also the declination of the plus, minus, remove, check, key, lock, etc... on the fa-database base icon.

Thank you.

**Comment by tagliala** [comment]
not so minimal -->  check, key, lock, **etc** <-- are out of scope

**Comment by tagliala** [comment]
Refers to #5883 #1181

**Comment by markhealey** [comment]
Probably can close this since #1181 covers it.

**Comment by tagliala** [comment]
@markhealey thanks for the heads-up

This is achievable with the layering and masking features of the SVG framework

Please take a look at the examples at https://jsfiddle.net/tagliala/u4h19ecy/11

I'm going to close here just because this request didn't gain much traction and it includes a comprehensive set of icons, which does not meet our contributing guidelines anymore.

Docs:
- https://fontawesome.com/how-to-use/on-the-web/styling/masking
- https://fontawesome.com/how-to-use/on-the-web/styling/layering
