### ISSUE TITLE
Icon request: rss-full-square

### ISSUE THREAD

**Issue by seanVonDrake** [FortAwesome/Font-Awesome#6074]
hello, you are doing a great work with this font set! I think you can improve it adding a perfect square rss icon, since the one with rounded corners looks ugly when used near square icons. I attach an image from my web site where you can see the issue and a preview of the icon I'd like you to add. I hope I can explain myself :-)
![ugly](https://cloud.githubusercontent.com/assets/11670332/6856072/a74645f6-d3fd-11e4-94a4-999b6afa73e7.jpg)
![path694-1](https://cloud.githubusercontent.com/assets/11670332/6856088/c8fffed0-d3fd-11e4-9f02-669a6c0cf598.png)

**Comment by tagliala** [comment]
Your request is legit, but you could consider using `fa-facebook-square` instead of `fa-facebook-official` or stack icons or a custom css solution

http://jsfiddle.net/tagliala/e9yfxsfj/9/

**Comment by seanVonDrake** [comment]
thank you for your answer, I can use it since it works
however, as you already have other full square icons in your set I think that adding the rss full square icon can still be a good idea :)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/square-rss?f=classic&s=solid)

**Comment by tagliala** [comment]
I think I've find an issue related to this request

https://fontawesome.com/icons/square-rss?f=sharp&s=solid is not sharp, I will track this separately
