### ISSUE TITLE
Icon Request: fa-graduation-open (just the outline)

### ISSUE THREAD

**Issue by lcavezza** [FortAwesome/Font-Awesome#6112]
Request for a version of the graduation cap (fa-graduation), with only the outline

**Comment by emmazimmerman** [comment]
+1

**Comment by ChristineZim** [comment]
+1

**Comment by nyon** [comment]
Somethin like this?

![selection_004](https://cloud.githubusercontent.com/assets/3247445/6907204/6e9fcb7a-d734-11e4-8756-4d0e13284484.png)

**Comment by ChristineZim** [comment]
Perfect! Thanks!

**Comment by nyon** [comment]
I plan to add this as an option (stroked icons) to my repository at nyon/fontawesome-actions tomorrow

**Comment by andrevanberlo** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/graduation-cap?f=classic&s=light)
