### ISSUE TITLE
Icon Request: icon-forum

### ISSUE THREAD

**Issue by bekircem** [FortAwesome/Font-Awesome#6126]
Hi. 

I guess it would be nice. I will use forum icon on the my header navigation. (http://forum.gameofthronestr.com)

**Comment by mrchief** [comment]
Perhaps you can use this: http://fortawesome.github.io/Font-Awesome/icon/comments-o/

**Comment by LogicalError** [comment]
+1

**Comment by shoulders** [comment]
there needs to be a generic icon for forum and if not its own icon then at least an alias.

peopel will search for the following:

https://fontawesome.com/icons?d=gallery&q=forum

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
