### ISSUE TITLE
Icon Request: icon-condom

### ISSUE THREAD

**Issue by LucasVandroux** [FortAwesome/Font-Awesome#6127]
Hi,

Currently designing a website for a pharmacy selling condoms 24h/7d. I just want to illustrate this service on the front page of their website with a nice icon.

Thanks for your amazing work,

![image](https://cloud.githubusercontent.com/assets/1956886/6934176/2a8a99b2-d863-11e4-91c0-19eb72f6cdb9.png)

![image](https://cloud.githubusercontent.com/assets/1956886/6934190/58901b70-d863-11e4-934d-fa7cdadba2d7.png)

**Comment by jbnv** [comment]
Is this an April Fool's joke?

**Comment by LucasVandroux** [comment]
Not at all. I know it can seems a bit weird but it is a serious request. I think it should be add to the medical icons category.

Here is another idea for the design:
![condom-penche-60px](https://cloud.githubusercontent.com/assets/1956886/6956077/f9518492-d91a-11e4-9b57-200c0760dcf8.png)

**Comment by kwendenarmo** [comment]
+1

**Comment by kwendenarmo** [comment]
@tagliala may have forgotten to label this as a new icon? I guess it will not be by taboo, being an element of health.

**Comment by tagliala** [comment]
@kwendenarmo just forgot labels, thanks

**Comment by kimberley-johnston** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
