### ISSUE TITLE
Icon request: fa-network-switch

### ISSUE THREAD

**Issue by MrZablah** [FortAwesome/Font-Awesome#6130]
Hi,

I would love if you can make a switch icon, I will use it in a IP monitored software but I think it will be very useful for normal server software.

Somthing like this maybe:
![images](https://cloud.githubusercontent.com/assets/6788941/6947582/81936f84-d865-11e4-80e7-42b8f90d169b.jpg)
![imgres](https://cloud.githubusercontent.com/assets/6788941/6947583/819c14fe-d865-11e4-976a-25e39ff4ae56.jpg)

Thank you for your excellent work and help! :)

**Comment by Grimdari** [comment]
I would love to see the icon at the bottom.  The symbols at the top are not quite as useful IMHO.  +1

**Comment by marksie1988** [comment]
+1 really need some networking icons. 

the Switch from the top image would be best

**Comment by FTreat** [comment]
The top right icon seems to be the common symbol for network switch. At least that's the symbol we're using (but flattened). Currently we have to use an image, which is messing up some of our format, and it would be really great if we could get it in font awesome.

**Comment by Raczaron** [comment]
Hello,
I also need this kind of network icons

**Comment by tagliala** [comment]
This is not labeled because I remember that there is a similar request. Meanwhile, labeling this too

**Comment by Korlawulki** [comment]
Cisco like network icons are very helpful, because commonly used everywhere in the network community.

**Comment by nemesis1117** [comment]
i also need this network icons too

**Comment by FTreat** [comment]
Any plans to add this icon? I've been waiting two years for this one ...

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
