### ISSUE TITLE
Icon Request: fa-switching

### ISSUE THREAD

**Issue by KermadecI** [FortAwesome/Font-Awesome#6166]
Hi,
I need the follow icon for a electronic site.
Thanks for the help.
Matteo Andreatta
![switching](https://cloud.githubusercontent.com/assets/11716776/7003106/627102ee-dc55-11e4-8ec6-bc3b072403e5.jpg)

**Comment by z38** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
