### ISSUE TITLE
Icon Request: icon-road-bike

### ISSUE THREAD

**Issue by mateo** [FortAwesome/Font-Awesome#6204]
Currently, there is a bike icon, but it is a beach cruiser.  I would really appreciate if there was a road bike as well, as a beach cruiser does not represent cycling as a sport.  The attached image may have too much detail for the vector theme of Font Awesome, but I trust that you guys can make something cool out of it

My Uses:
    Icon on my website
Other possible Uses:
    Any bike related webpage could use this as an icon

![road-racing-bike-silhouette-vector-423198](https://cloud.githubusercontent.com/assets/6895694/7104075/f8e389ca-e07b-11e4-86e6-621bb2fb12ef.jpg)

Disclaimer: I did not create this image, I downloaded it from the internet

**Comment by shunsukeaida** [comment]
I agree we'd benefit from having another. The current one indeed looks a bit weird, because it lacks the seat tube. I know we have to simplify things and omit the details people don't care to make a good icon, but still think the aforementioned missing tube matters so much (to me). 
![fa bicycle font awesome icons](https://cloud.githubusercontent.com/assets/5036100/14785838/7e2cb87c-0b37-11e6-9495-5488e8bfc3e4.png)
I'd even rather go with the top tube if I ever had to give up one of them...

**Comment by dpfem** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
