### ISSUE TITLE
Icon request: periodontics

### ISSUE THREAD

**Issue by garrywiley** [FortAwesome/Font-Awesome#6213]
Hi there,
I was wondering if you could help me. I'd like to request an icon please, it's for a periodontist site I'm in the middle of building.
All help appreciated, image attached. This is one of 4 requests if that's alright.
Thanks,
Garry

![periodontics](https://cloud.githubusercontent.com/assets/11925093/7116127/e9a4aa54-e1e6-11e4-97f8-fa659c490f93.jpg)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
