### ISSUE TITLE
Icon request: icon-tooth-search (oralsurgery)

### ISSUE THREAD

**Issue by garrywiley** [FortAwesome/Font-Awesome#6214]
Hi there,
I was wondering if you could help me. I'd like to request an icon please, it's for a periodontist site I'm in the middle of building.
All help appreciated, image attached. This is one of 4 requests if that's alright.
Thanks,
Garry

![oral_surgery](https://cloud.githubusercontent.com/assets/11925093/7116173/74b4e7da-e1e7-11e4-8e0c-b9fb3988eb1c.jpg)

**Comment by hdbarahona** [comment]
+1

**Comment by seysoosey** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
