### ISSUE TITLE
Icon request: waiting room

### ISSUE THREAD

**Issue by sbaramov** [FortAwesome/Font-Awesome#6218]
It would be nice if you guys can add an icon for a waiting room. One idea is show a guy sitting and a clock on the wall. Here is an example : http://www.decalsplanet.com/item-7228-waiting-room-sign.html

Thanks
Stefan

**Comment by viklele** [comment]
+1 This is a common requirement in application managing meeting with consultants (dentists, doctors, etc).

**Comment by tagliala** [comment]
hard to fit in 14px icon size

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
