### ISSUE TITLE
Icon Request: fa-nature

### ISSUE THREAD

**Issue by frague59** [FortAwesome/Font-Awesome#6230]
Hi, 

Could be nice to have a little bit mode nature-related icons, I've only found a pine tree...

May be a grass, flower, mushroom and wild animals : insect, mammals, fishes ?  

Thanks for your great job !

**Comment by DeBraid** [comment]
A tree, broken down into parts would be amazing.  

Roots + trunk + branches + canopy.

**Comment by tagliala** [comment]
Sorry, I need to close this request because it does not meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please search to see if your icon request already exists. If a request is found, please +1 that one.

(e.g.: fish: #2722)

> * Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
* Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
* Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺
