### ISSUE TITLE
 fa-square-o is smaller than fa-square

### ISSUE THREAD

**Issue by Simonn-** [FortAwesome/Font-Awesome#6238]
Should fa-square-o not be the same size as fa-square as they can be used to create a checkbox.

**Comment by tagliala** [comment]
hmmm... maybe because of the initial meaning of that square icon... 

Unchecked outlined: http://fontawesome.io/icon/square-o/
Checked outlined: http://fontawesome.io/icon/check-square-o/

Uncheked: http://fontawesome.io/icon/square/
Checked: http://fontawesome.io/icon/check-square/

But `circle-o` and `circle` have the same size. I don't know what to say.

Labeling this as enhancement and adding to 5.0.0 milestone, so dave will eventually take a look and take a decision

**Comment by bryanspears** [comment]
As @Simonn- said, this could be used for custom checkboxes, but as he said, they're different sizes. Even doing adjustments to font-size or other css properties I haven't been able to make it look right.

**Comment by tagliala** [comment]
Closing here in favour of #5156
