### ISSUE TITLE
Icon Request: fa-rating-g, fa-rating-pg, fa-rating-r, fa-rating-pg13

### ISSUE THREAD

**Issue by emadd** [FortAwesome/Font-Awesome#6239]
![46px-rated_r svg](https://cloud.githubusercontent.com/assets/240649/7186245/90a13ddc-e425-11e4-9783-73c837287aad.png)
![142px-rated_pg-13 svg](https://cloud.githubusercontent.com/assets/240649/7186246/90a1ac40-e425-11e4-9a2e-724286e500d2.png)
![images](https://cloud.githubusercontent.com/assets/240649/7186247/90a1e9d0-e425-11e4-96c6-e1d796cfe2ce.png)

**Comment by tvirelli** [comment]
@emadd here is a way you can do this now just by stacking icons with fonts:

http://jsfiddle.net/4rskv9me/1/

The PG-13 and NC-17 are not perfect, but a minute with CSS would fix that.

**Comment by maddox** [comment]
I know there's a lot of threads on these icons, and almost all of them have a comment suggesting to use stacking....but doing so does not match the actual official icons.

The MPAA ratings have a specific font. Just using the `R` and `PG-13` lettering doesn't give the brand people are looking for and that stick out in UIs.

**Comment by PDelahanty** [comment]
Yeah, stacking isn't a solution to get the specific style used in the ratings.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
