### ISSUE TITLE
Icon request: icon-ambulance-alt

### ISSUE THREAD

**Issue by redbullpeter** [FortAwesome/Font-Awesome#6270]
I know there is already an ambulance icon however it is represented by a cross which doesn't translate well in Asia and countries where Christianity is not the majority religion.

The more common symbol is the  caduceus (the staff and snake symbol) and in majority Muslim countries a crescent.

**Comment by tagliala** [comment]
thanks for pointing out this

**Comment by redbullpeter** [comment]
No problem

**Comment by Toron-Isil** [comment]
Only for your information: Caduceus is the wrong symbol for medicine - even if its common ... The American Air Force has mistaken the symbol with the Rod of Asclepius. 
The Caduceus is the staff of Hermes. Hermes is the god of thieves and merchants. 
I am not a proponent of spreading mistakes.
I like the symbol ... but not for medical / health category.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
