### ISSUE TITLE
Icon Request: icon-element-earth, icon-element-wind, icon-element-fire, icon-element-water

### ISSUE THREAD

**Issue by LanceLocke** [FortAwesome/Font-Awesome#6274]
I would like to see an icon or icons to represent various elements (i.e. earth, wind, fire, water)

More as variants to the styling of the one from Avatar the Last Airbender.

![image](https://cloud.githubusercontent.com/assets/10727745/7238195/7852d71c-e755-11e4-8cc9-dac4cfe03fa7.png)

**Comment by esatk** [comment]
+1

**Comment by jventers** [comment]
+1

**Comment by shachyjr** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
