### ISSUE TITLE
How to changes the icon`s size?

### ISSUE THREAD

**Issue by SimonWang2014** [FortAwesome/Font-Awesome#6286]
I used the icon like this:
```
<span><p class="icon icon-access-time"></p></span>
```
but how to change the size of the icon?

**Comment by tagliala** [comment]
Hi,

this is not FA's syntax are your sure are you using Font Awesome?

BTW please do not add icons like that, take a look at our docs: http://fontawesome.io/icon/bed/

`<i class="fa fa-bed"></i>` (feel free to replace `<i>` with `<span>`)

Since icon fonts act like text, you should simply change the font size to get larger icons. Please note that pixel perfection is not guaranteed at any icon size, so you should keep multiples of 14px, and there are helper classes for that (`fa-2x`, `fa-3x`, ...)

Hope it helps

Closing here but feel free to comment

**Comment by SimonWang2014** [comment]
Thanks :)
