### ISSUE TITLE
Icon Request: fa-grid (fa-th without rounded corners)

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#6299]
Basically a `fa-th` without the rounded corners, which would be a `fa-grid`, I presume.

**Comment by alcexhim** [comment]
I wasn't sure if I should add this as another request or not, since there's already this one, but because it's related... I think there should be outline versions of these icons as well (e.g. fa-grid-o, fa-th-o) and since there's an fa-th-large, a corresponding fa-grid-large and fa-grid-large-o should be included as well.

Just my 2 cents, since I came here looking for this exact icon and found th, which is okay, but an outline version would be even better :)

**Comment by sensibleworld** [comment]
We have a lot of grid icons now: https://fontawesome.com/search?q=grid&o=r
