### ISSUE TITLE
Icon request: icon-cloud-sun

### ISSUE THREAD

**Issue by tizata** [FortAwesome/Font-Awesome#6323]
![icon1_4](https://cloud.githubusercontent.com/assets/12114927/7334308/94289b10-eb98-11e4-8bc0-02418e3e4847.png)

That's my third , please help me with it :)

**Comment by tagliala** [comment]
This is a better duplicate of #155.

#155 does not meet our contributing guidelines, because it is a request of a comprehensive set of icons for a specific application

I'm going to close this one because in #155 there is a link to this icon font: https://github.com/erikflowers/weather-icons/ which could help you
