### ISSUE TITLE
Icon Request : icon-Cosmetics

### ISSUE THREAD

**Issue by eziolavolpe** [FortAwesome/Font-Awesome#6342]
I need for developing a website about selling cosmetics the following items
Lipstick
Mascara 
Perfume
Women Bags
Women shoes
necklace
and any related other icons to this field 
Thanks 
![lipstick](https://cloud.githubusercontent.com/assets/12144635/7360128/5ef1153e-ed47-11e4-8d4f-13ab17ed3671.jpg)
![mascara](https://cloud.githubusercontent.com/assets/12144635/7360131/611e084e-ed47-11e4-849e-fe629bc0c369.jpg)
![bag](https://cloud.githubusercontent.com/assets/12144635/7360134/688cd34e-ed47-11e4-8b8e-fe321bbf482f.jpg)
![shoes](https://cloud.githubusercontent.com/assets/12144635/7360135/69fa3154-ed47-11e4-920a-0eff7e6b81cd.jpg)
![perfume](https://cloud.githubusercontent.com/assets/12144635/7360154/97c72af6-ed47-11e4-9a20-adbfdfa9a21c.jpg)

**Comment by tagliala** [comment]
Hi,

I need to close this issue because it doesn't meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

Please +1 #5717 for perfume, #3473 for stiletto, #2582 for lipstick and open new individual requests for woman bag and mascara

Closing here
