### ISSUE TITLE
Icon Request: icon-sun-alt (asymmetric rays)

### ISSUE THREAD

**Issue by devagit** [FortAwesome/Font-Awesome#6347]
Hi

New icon request "fa-sunshine-o".

First image is static sunshine icon, and second image is the same icon with "fa-pulse" effect applied.

![fa-sunshine-o-1](https://cloud.githubusercontent.com/assets/11771088/7378347/10273824-eded-11e4-826a-ea39b586ca83.gif)

![fa-sunshine-o-animation-1](https://cloud.githubusercontent.com/assets/11771088/7378894/0fbfdca2-edf1-11e4-9065-0f063f71e757.gif)

I can see many use cases for such an icon on tourism oriented websites. My site is one of them and I would love to have it.

I have tried to apply "fa-pulse" effect to current "fa-sun-o" icon, but it is not nice.

Best, Dev

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
