### ISSUE TITLE
Crashes IE9

### ISSUE THREAD

**Issue by joeyre** [FortAwesome/Font-Awesome#6358]
Hi there, 

It's the first time I've ever experienced issues with Font Awesome and IE9, but one of my sites was crashing every time I loaded fontawesome.css. Took it out and the page loaded fine. Thought you might like to know.

**Comment by tagliala** [comment]
Does it also happen on fontawesome.io?

**Comment by joeyre** [comment]
No it doesn't. I'm wondering if there's some sort of compatibility issue with something else. I'm looking into it to see if I can solve the issue, will let you know if I find anything else out.

**Comment by tagliala** [comment]
could you please check your javascript?

**Comment by tazeverywhere** [comment]
Same here, can't find yet where the bug stands in font-awesome.
Used with @import in main.scss
Work in all browser except ie9 (seems that not all the css rules are loaded if font-awesome is present), so the entire design crash.
I have tried with scss and the css version.

Looking into it as well.

(used with foundation 5.5.3)

**Comment by tazeverywhere** [comment]
Myabe I found the problem.
If I load the cdn version (ex: //maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css) , everything is ok.

So I think it was the compression on the app.css  that corrupted the file...

Still strange because on other website, everything is ok with ie9.. even compressed.
