### ISSUE TITLE
Icon Request: Finance icons

### ISSUE THREAD

**Issue by ntfox** [FortAwesome/Font-Awesome#6367]
Hi,
Add finance icons, sample: ِDiscount, Promotion, ...

**Comment by tagliala** [comment]
Sorry, can't keep this open because it doesn't meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please search to see if your icon request already exists. If a request is found, please +1 that one.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
* Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
* Include a few use cases for your requested icon. How do you plan on using it?
* Attach a single color image or two that represent the idea you're going for.
* Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

Closing here
