### ISSUE TITLE
Icon request - Time of day

### ISSUE THREAD

**Issue by wilkmit** [FortAwesome/Font-Awesome#6380]
Some icons to indicate time of day would be nice. Either indicated by the sun and moon (missing fa-sunrise and fa-sunset) or indicated by time on a clock.

**Comment by tagliala** [comment]
sorry but I need to close this request because it doesn't meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please search to see if your icon request already exists. If a request is found, please +1 that one.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
* Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
* Attach a single color image or two that represent the idea you're going for.
* Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺
