### ISSUE TITLE
Icon request fa-bowl-of-hygieia

### ISSUE THREAD

**Issue by 4bdulll4** [FortAwesome/Font-Awesome#6410]
![image](https://cloud.githubusercontent.com/assets/10366571/7509346/3286e93a-f498-11e4-875f-455c4ba91c24.png)

**Comment by tagliala** [comment]
pharmacy could be considered a dup of #768

Since this is requesting a Bowl of Hygieia, let's change the name

**Comment by Hirbod** [comment]
+1 - as i like this symbol more then the others

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
