### ISSUE TITLE
Icon request: keyboard function key shortcuts

### ISSUE THREAD

**Issue by frumbert** [FortAwesome/Font-Awesome#6425]
MacOS has a bunch of effectively standard designs that represent the shift, control, option/alt, command/window/super key, escape, enter, backspace, and so on. These would be particularly handy for web apps who have menus/actions with keyboard shortcuts. Here's an example image of the standard shortcuts:

![Shortcuts](https://s-media-cache-ak0.pinimg.com/originals/ba/63/85/ba63854b2d8a9308c6b990849ffae06d.jpg)

**Comment by tagliala** [comment]
Hi,

sorry but I can't keep this request open because it doesn't meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
> Please search to see if your icon request already exists. If a request is found, please +1 that one.
> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
> Please and thank you if you include the following:
> Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).

backspace: #1980 
eject: http://fontawesome.io/icon/eject/
character: http://fontawesome.io/icon/font/
command: #1615

maybe there are more duplicates

closing here
