### ISSUE TITLE
Icon Request: fa-scuba (fa-diver, fa-diving)

### ISSUE THREAD

**Issue by paulvanderhoeven** [FortAwesome/Font-Awesome#6448]
The world is a better place with font-awesome!
Thanks for considering this.

**Comment by simonfranz** [comment]
see here: #2557
and you should really read https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md :)
helps a lot when requesting new icons

**Comment by tagliala** [comment]
@simonfranz 

thanks again!

closing here

**Comment by tagliala** [comment]
edit: this one is far better than #2557.

I'm going to leave this one open, #2557 doesn't meet our contributing guidelines

**Comment by ShamanFromSiberia** [comment]
+1

**Comment by M440** [comment]
+1

**Comment by nicolasThal** [comment]
:+1:

**Comment by callkeeper** [comment]
+1

**Comment by repat** [comment]
+1

**Comment by dannyverp** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/mask-snorkel?f=classic&s=solid)
