### ISSUE TITLE
Icon Request: fa-warthog

### ISSUE THREAD

**Issue by ToolA10github** [FortAwesome/Font-Awesome#6466]
The US Air Force and The US Congress are currently locked in an historic battle over the divestiture of the A-10 Thunderbolt II, or "Warthog"; the country's premier Close Air Support attack jet.  Many websites and blog posts have been dedicated on both sides to this debate.  A Font-Awesome icon labeled "fa-warthog" or perhaps "fa-attack".  You currently have icons for civil jets and even one for "fighter jets" generally, but there is no silhouette quite as distinctive the Warthog.
![a-10 topview](https://cloud.githubusercontent.com/assets/12436660/7623125/a6bb74ae-f98b-11e4-9e4e-07d8e1b7fbf8.png)

Thank you for your consideration,
Scott Hanes

**Comment by ToolA10github** [comment]
*A Font-Awesome icon labeled "fa-warthog" or perhaps "fa-attack" would benefit this online debate.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
