### ISSUE TITLE
Icon Request: fa-herb

### ISSUE THREAD

**Issue by msshin0313** [FortAwesome/Font-Awesome#6485]
It there is 
![s05-herb-icon03_0](https://cloud.githubusercontent.com/assets/12455362/7647162/deab06ce-fb0a-11e4-8506-2a83d254cbcb.png)
![plants-and-flowers-icons_156049388](https://cloud.githubusercontent.com/assets/12455362/7647163/e0eaac14-fb0a-11e4-8ee6-6c1f23a818be.jpg)

an icon that represents functional food or herbal medicine would be grate.

**Comment by tagliala** [comment]
maybe http://fontawesome.io/icon/leaf/ or an abuse of http://fontawesome.io/icon/pagelines/ could work

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
