### ISSUE TITLE
Icon Request: fa-open-sign & fa-closed-sign

### ISSUE THREAD

**Issue by FastEddie8888** [FortAwesome/Font-Awesome#6533]
For use like a store, open for business and closed for business.

Open:
![image](https://cloud.githubusercontent.com/assets/6530213/7761230/244c77b8-ffd8-11e4-970a-2677ca322fba.png)

Closed:
![image](https://cloud.githubusercontent.com/assets/6530213/7761226/19de42ca-ffd8-11e4-95a3-e0ac1702329a.png)

Thanks Font-Awesome Team!

**Comment by smaspe** [comment]
not localized. a lot of people in the world use languages that are not english

**Comment by jsieler** [comment]
But anyway everyone knows mean of it.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
