### ISSUE TITLE
Icon Request: fa-bank-check-number, fa-bank-routing-number, fa-bank-account-number

### ISSUE THREAD

**Issue by ksepehri** [FortAwesome/Font-Awesome#6534]
On checks bank routing numbers and accounts have certain symbols next to them. 
### Routing Number Icon

![Routing Number](http://pad1.whstatic.com/images/thumb/e/ed/Locate-a-Check-Routing-Number-Step-5.jpg/670px-Locate-a-Check-Routing-Number-Step-5.jpg)
### Account Number Icon

![Account Number](http://pad2.whstatic.com/images/thumb/2/27/Locate-a-Check-Routing-Number-Step-6.jpg/670px-Locate-a-Check-Routing-Number-Step-6.jpg)

More details here:
http://www.wikihow.com/Locate-a-Check-Routing-Number

**Comment by tagliala** [comment]
I didn't get this request. Or at least I didn't get the first part :)

Could you please clarify?

**Comment by VosAndHowden** [comment]
I'd like to second this request.
http://www.check-routing-number.com/

**Comment by tagliala** [comment]
@VosAndHowden could you please provide an example?

**Comment by VosAndHowden** [comment]
There are examples at the link I included in my comment. More specifically, however, these are the symbols I'm looking for:

![image](https://user-images.githubusercontent.com/1154394/68490938-c06e5a80-01fe-11ea-89f4-3ef029bd99c6.png)

I use them in an interface for setting up ACH payments like this:

![image](https://user-images.githubusercontent.com/1154394/68491089-09beaa00-01ff-11ea-9f5e-cd0e078bad92.png)

I'm currently stuck using images to represent these symbols. I'd much prefer to use Font Awesome.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
