### ISSUE TITLE
[Icon Request] oven icons

### ISSUE THREAD

**Issue by EinSteein** [FortAwesome/Font-Awesome#6542]
Hey guys

would be nice if you could add icons like these
https://www.ruislipappliances.com/images/Siemens/Icons/HB43NB520B.jpg
but mostly convection heat and bottom / top heat
to your collection.

**Comment by tagliala** [comment]
Sorry, I can't keep this open because it doesn't meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

You can of course request individual icons but you should consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Closing here
