### ISSUE TITLE
Icon Request: icon-hotel collection

### ISSUE THREAD

**Issue by blarnett** [FortAwesome/Font-Awesome#6545]
I am designing for a hotels and hostels and I would like to use your icons however there is a lack of representations for hotel/adventure services.

**smoking/non-smoking** = to indicate the different areas of the hotel
**wheelchair accessibility** = to indicate whether the location is wheelchair friendly
**breakfast included/not included(*bacon and sunny side up egg*)** = to indicate the morning food services
**room service** (*silver domed dishes on a cart*) = to indicate availability of room service
**tea kettle/coffee pot** = to indicate the free beverages available to all patrons
**stove/oven/microwave** = to indicate the extent of the kitchen that is available for guests
**cat/dog/pets(both)** = to indicate that its cat friendly, dog friendly or pet friendly in general
**mountains/river/beach/ocean/volcano** = to indicate the type of views that the rooms provide
**hand-washing(*detergent bottle and scrub brush*)/machine washing(*washer or dryer*)** = to indicate the type of laundry service at the location
**hot shower/cold shower** = to indicate whether hot water is available
**free towel service/ towels for rent** = to indicate that towel come included or not
**garden(*flower box*)/ orchard(*fruit tree*)** = to indicate the diversity of the grounds at the location
**exercise activities: gym(*weights*), yoga (*downward facing dog or yoga mat*), pool (*swimming*), hiking (*backpacker with hiking stick*), canoeing, jet skiing, snorkeling etc**. = to indicate the type of exercise or recreational equipment available.

I havent attached a photo for each of these but I can provide further explanation as needed.

**Comment by tagliala** [comment]
Hi, unfortunately I can't keep this open because it doesn't meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
> Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).

wheelchair: http://fontawesome.io/icon/wheelchair/
pet: http://fontawesome.io/icon/paw/

a request for Smoking/non smoking is here: #726 
request for shower: #708 

there should be other duplicate requests

You can also consider a custom build https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome or contact @davegandy privately to arrange a solution

Closing here
