### ISSUE TITLE
I did break you site with one /

### ISSUE THREAD

**Issue by DmitryOlkhovoi** [FortAwesome/Font-Awesome#6551]
http://fortawesome.github.io/Font-Awesome/icons//

**Comment by tagliala** [comment]
This is actually not an easy fix and may break a lot of links.

The `relative_path` variable should be needed for this stuff: https://help.github.com/articles/user-organization-and-project-pages/

I made another branch with the fix but I can't merge it.

This is not an issue for Font Awesome itself because we are using a custom domains, but forks could have troubles in building their docs without editing the .yml config file.

@davegandy can we ignore this issue?

**Comment by tagliala** [comment]
Can't reproduce anymore

If this is still an issue, feel free to fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)
