### ISSUE TITLE
Icon request: icon-cursor, icon-text-cursor etc.

### ISSUE THREAD

**Issue by cheics** [FortAwesome/Font-Awesome#6571]
It would be nice to have icons for various cursors - the pointer, grab hand, text cursor etc.

Since Balsamiqs uses Font Awesome as an icon set, it would be really useful for me to have the contextual cursors.

For a list of the cursors, see:
http://www.w3schools.com/cssref/playit.asp?filename=playcss_cursor&preval=alias

**Comment by tagliala** [comment]
Sorry but I need to close this one because it doesn't meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

It is fine to have multiple requests each containing strictly related icons but this one is too generic.

Pointer is here: #1095 
Grab hand: #3716
