### ISSUE TITLE
icon request

### ISSUE THREAD

**Issue by m3hul** [FortAwesome/Font-Awesome#6577]
please add new icons like jquery, web programming languages, databases and other web technology icons. thanks

**Comment by tagliala** [comment]
Hi, unfortunately I can't keep this open because it doesn't meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
> Please search to see if your icon request already exists. If a request is found, please +1 that one.
> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).

jquery is here: #1665 
there are also other duplicates #6052 #3654 

take also a look here: http://fizzed.com/oss/font-mfizz

Closing here
