### ISSUE TITLE
Icon request for add, edit and delete

### ISSUE THREAD

**Issue by SuperDJ** [FortAwesome/Font-Awesome#6606]
Down here is a list with a few example icons of which there can be icons for add (plus), edit (pencil), delete (minus, trashcan). All of these icons could work very nice with a CMS or admin area.
fa-file-archive-o;
fa-file-code-o;
fa-file-word-o (also powerpoint, pdf, excel etc);
fa-image (also video and music);
fa-language (for a multilanguage website);
fa-server;
fa-user;
fa-cart;

Could there also be an clipboard with pencil icon can be found on (at the bottom of the page): http://zurb.com/playground/foundation-icon-fonts-3 Could be used for taking notes or something like that.

**Comment by tagliala** [comment]
refers to #1181. Please take a look at the comments, you will find a solution

Sorry but I need to close this one because you are requesting 24+ icons: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

We can accept individual requests for add edit and delete
