### ISSUE TITLE
Icon Request: fa-templates

### ISSUE THREAD

**Issue by richterdennis** [FortAwesome/Font-Awesome#6613]
To choose a template or design fore something

**Comment by tagliala** [comment]
could you please provide an example?

**Comment by Denni007** [comment]
Something like that perhaps: https://www.iconfinder.com/icons/565330/layout_mail_template_page_template_templates_web_web_page_icon#size=128

**Comment by YoonHyungMin** [comment]
+1

**Comment by YoonHyungMin** [comment]
very expected about new fa-templates icon!!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
