### ISSUE TITLE
Icon Request: fa-report-workload

### ISSUE THREAD

**Issue by EddieFromFA** [FortAwesome/Font-Awesome#6635]
An icon to allow the users to bring up a report that shows the balance of workload. This report is to be used to show workflow task distribution among the users.

**Comment by tagliala** [comment]
could you please provide an example?

**Comment by EddieFromFA** [comment]
Sure, but do you mean an example of the icon I may be able to find elsewhere or an example of the use case?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
