### ISSUE TITLE
Icon request: fa-vihara

### ISSUE THREAD

**Issue by Appalab** [FortAwesome/Font-Awesome#6655]
I need an icon of fa-mosque, fa-church, fa-vihara and other religion. This perhaps is also needed by others.

**Comment by tagliala** [comment]
mosque is a dup of #5146, church is a dup of #2088 

Renaming this as fa-vinhara

About other religions, we need a separate request. But this is a sensitive topic. I don't know exactly what to do, perhaps we need all of them or none of them like genders :confused:

**Comment by GermanKiwi** [comment]
FYI, I believe it's spelled "vihara" (the name for a Buddhist monastery).

I don't think we need to treat this topic as an all-or-nothing affair though. I don't think it's the same as genders. Icons for houses of worship (church/mosque/temple/monestery etc) should be treated on a case-by-case basis, based on demand, just like any other icon request. I would view it similar to requests for sports, or famous product logos (Facebook/WhatsApp/Google etc) - eg. if lots of people request an icon for a tennis ball, you would consider adding it, but you wouldn't decide that you have to add every other sport on the planet at the same time, in fear of offending croquet players. :)

I honestly don't think that people will be offended if you add one icon for one house of worship, based on how popular it is, while leaving other ones until there is more demand for them or you have more time. Otherwise it's not very fair when there is massive demand for one particular icon, which many webmasters are desperately wanting to use for their client projects - they shouldn't have to wait until more demand is added for less common icons. It should be a simple case of supply and demand.

Worth noting that the fa-church icon request page #2088 currently has 32 "+1" comments on it, making it a very popular request, while the fa-mosque page #5146 has 4 "+1" comments. I can't find a request for synagogues or temples yet.

You could at least just create icons for a church and a mosque, as there is at least demand for those two, but I don't see the point in spending time to create icons for other things that (hardly) nobody needs.

**Comment by GermanKiwi** [comment]
And fwiw, this should have nothing to do with the religions themselves - popularity of an icon has nothing to do with the religion behind it - this should be viewed as purely a commercial exercise. If webmasters need a particular icon more than another one, then that's what should matter - inasmuch as having high demand for a soccer ball icon doesn't mean that we are saying that soccer is a better sport than rugby. :)

**Comment by GermanKiwi** [comment]
Incidentally, @tagliala what is the usual requirement for an icon request to get implemented? Does it need a certain number of +1 votes from other people? Or meet some other threshold? Just curious what the church icon request needs to get a milestone set for it! :)

**Comment by tagliala** [comment]
There are no thresholds... Dave will certainly take a look at the most requested icons

But **let's say** that 5.0.0 is a release focused on religions, then he would probably implement `fa-church` icon even if `fa-social-network` has 100 more +1s

**Comment by GermanKiwi** [comment]
Good to know, thanks!

**Comment by Guestrevu** [comment]
A set of all religions icons will be very useful, I work on a lot of school websites and religion is an important icon especially in a multi cultural society, governmental websites and census websites also use this a lot. In travel websites we sometimes need to indicate if the property have a Muslim prayer room, wedding venue or chapel, or if the food is halal :)

**Comment by GermanKiwi** [comment]
In my opinion a separate request should be created for religious icons (eg. cross, crescent star of David etc), in contrast to religious houses of worship which are being discussed here. This particular request page is for a Vihara icon (Buddhist temple).

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/vihara?style=solid
