### ISSUE TITLE
Icon Request : fa-desktop-with-bar-and-line-chart

### ISSUE THREAD

**Issue by KarthikDev81** [FortAwesome/Font-Awesome#6666]
Need ERP Solutions icon like zig zag graph inside computer / Laptop

**Comment by tagliala** [comment]
could you please provide an example?

**Comment by KarthikDev81** [comment]
https://www.iconfinder.com/icons/473802/business_chart_computer_data_finance_graph_statistics_icon#size=128

**Comment by tagliala** [comment]
is the chart needed to be inside a laptop/computer?

I'm asking because we need a better title

**Comment by KarthikDev81** [comment]
yes... i want like that... we call it as "finance chart" / "graphical stats" / "business chart"

**Comment by tagliala** [comment]
there is a line chart http://fontawesome.io/icon/line-chart/ that *might* work for your use case. 

Your request is legit, but if you need exactly that icon I should advise you to consider a custom build

**Comment by KarthikDev81** [comment]
please go ahead

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
