### ISSUE TITLE
Icon Request: Harvey Balls

### ISSUE THREAD

**Issue by designbyjim** [FortAwesome/Font-Awesome#6685]
http://en.wikipedia.org/wiki/Harvey_Balls

Basic set could alias the following:
http://fortawesome.github.io/Font-Awesome/icon/circle-o/
http://fortawesome.github.io/Font-Awesome/icon/adjust/
http://fortawesome.github.io/Font-Awesome/icon/circle/

plus 
"Circle with upper right quadrant black",
"Circle with all but upper left quadrant black"

**Comment by Shibumi-Gailyn** [comment]
+1 -- need these to indicate status/progress of a project.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/search?q=circle&o=r)
