### ISSUE TITLE
Icon request: icon-user-arrow-up and icon-user-arrow-down

### ISSUE THREAD

**Issue by legendarydrew** [FortAwesome/Font-Awesome#6711]
Basically the user icon with an up arrow or down arrow next to it, or perhaps a left right arrow and right arrow instead. This could be used to indicate the transfer of something from and to a user.

**Comment by tagliala** [comment]
refers to #1181 , you will find a solution in that thread

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
