### ISSUE TITLE
Icon Request: fa-meditation (or fa-meditate or fa-zen)

### ISSUE THREAD

**Issue by vomLeben** [FortAwesome/Font-Awesome#6770]
I would love to use an Icon like this for my german blog about better living (http://www.vomleben.de).

For example:
- category-icon (serenity)
- method-icon (meditate)
- chapter-icon in ebooks (how to reach serenity / how to meditate / ...)
- button-icon (leran how to meditate / ...)
- ...

![Uploading meditation.png…]()

**Comment by vomLeben** [comment]
Upload does not work. Link to image:

https://thenounproject.com/search/?q=meditate&i=51613

**Comment by ShamanFromSiberia** [comment]
+1

**Comment by tagliala** [comment]
Sorry, I can't keep this open because it does not meet our contributing guidelines

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
> Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).

You should consider a custom build, so you can merge a set specific to meditation icons with fontawesome: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
