### ISSUE TITLE
Icon Request: fa-map-marker-square

### ISSUE THREAD

**Issue by sinkfish** [FortAwesome/Font-Awesome#6779]
Hello FA designers, is it possible to make a map-marker in square version? :D

**Comment by manolodantonio** [comment]
+1. Great for maps and can double as speech bubble.

![marker](https://image.freepik.com/free-icon/speech-bubble-as-a-square_318-27278.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
