### ISSUE TITLE
Icon request:Building/Construction icons

### ISSUE THREAD

**Issue by JuliaShier** [FortAwesome/Font-Awesome#6785]
Hi there,
Can you please look into adding some icons to do with Building and construction such as perhaps a hard hat, tools (hammer, spanner etc) if possible a part built building. maybe a wee builder man, a plan - like blueprints. 
Thanks, Julia

**Comment by tagliala** [comment]
sorry but I can't keep this request open because it does not need our contributing guidelines: 

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
Please search to see if your icon request already exists. If a request is found, please +1 that one.
Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).

hammer is here: #1214 , you can +1 that request
hard hat: #5790 , you can +1 that request

there might be other duplicates.

If you need a comprehensive set of icons related to building/construction, you could also consider a custom build https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

closing here
