### ISSUE TITLE
Icon Request: fruit

### ISSUE THREAD

**Issue by Yannick86** [FortAwesome/Font-Awesome#6787]
I'd like to request icons which resemble all kinds of fruit. You could start with the simple ones; apple, banana, pear, citron, ...

What would I use this for?
There are many applications in the food and industry sector which could use icons such as this.

**Comment by DaTebe** [comment]
+1

**Comment by dfyx** [comment]
I have another use case for fruit icons:

I have a website where people can register for community meetups. During this process they can enter if they are vegetarians or not (because some of those meetups include dinner).

For the cooking team I have a table that lists every guest with their preference (no dinner, vegetarian, non-vegetarian). It would be really cool to show a piece of meat and maybe an apple or a carrot in those columns.

**Comment by tagliala** [comment]
@dfyx thanks for reporting related issues

Sorry, I need to close this one because fruit is generic and does not meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

Please +1 #1499 for a carrot or search for other fruits.

If you need a fruit that is not listed, feel free to open a new request.

Please also keep in mind that creating a comprehensive set of fruits is out of the scope of FontAwesome and you should consider a custom build, take a look at: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
