### ISSUE TITLE
Icon request: fa-print-square

### ISSUE THREAD

**Issue by jhuvi** [FortAwesome/Font-Awesome#6802]
It would be really cool to have a print icon like square social media icon to be used inline with other square icons.

So, basically combine these into one icon:
http://fortawesome.github.io/Font-Awesome/icon/print/
http://fortawesome.github.io/Font-Awesome/icon/square/

**Comment by capitantrueno** [comment]
Hello,

You can get what you need using *stacked icons* concept. I made this fiddle (http://jsfiddle.net/1rajan5q/) in order you can see it in action.

Best regards!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
