### ISSUE TITLE
Icon request: monuments, art icons

### ISSUE THREAD

**Issue by kwaaui** [FortAwesome/Font-Awesome#6815]
For example:
fa-colosseum, fa-eiffeltower, fa-libertystatue, etc.

Also general icons for art-related and/or museums like: fa-statue, fa-painting.

**Comment by tagliala** [comment]
Sorry, I can't leave this open because it does not meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

landmarks also contain a huge number of points, and this have impact on the final font size.

You should consider a custom build or a specif icon font dealing with landmarks, such as http://flaticons.net/category.php?c=Landmark

Refers to #2661
