### ISSUE TITLE
Icon Request: fa-play-plus

### ISSUE THREAD

**Issue by gabelerner** [FortAwesome/Font-Awesome#6827]
Basically an "add to play queue" icon as a combination of the play icon and a smaller plus icon as well as any circle, open, etc. varieties.

**Comment by ShamanFromSiberia** [comment]
+1

**Comment by tagliala** [comment]
refers to #1181

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
