### ISSUE TITLE
Icon Request: icon-databases

### ISSUE THREAD

**Issue by liptonbeer** [FortAwesome/Font-Awesome#6854]
Hi,
It would be great if you could make icon for copying data. We need to distinguish whether the uses copy the whole object or just some data of this object.
Here is the example of needed icon:
![data-copy](https://cloud.githubusercontent.com/assets/12607691/8449666/cfe2ef42-1fd3-11e5-8fc6-34d26cf771c8.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
