### ISSUE TITLE
Icons Dental

### ISSUE THREAD

**Issue by abhuanco** [FortAwesome/Font-Awesome#6856]
Hello,

In the part of medical icons is the basics.

Full increase would be good as dental icons.

example:
- An appointment icon, add, delete and edit
- Icon dental instruments
- Dental logos
- Dental Parts

Excellent would I use the cdn because it is easier to embed in my website
Thank you thank you ....

**Comment by daftarynimita14** [comment]
I need post which has clearly information about a dental implants India. This I  need because may go for the dental implant. Though dental implants are more preferred these days, the question about how long it shall last was on top of my mind. My sister recently lost her tooth in an accident. While looking for dental implant India I came across lot of information on the entire procedure. With more research, now i am confident enough to take my sister for the implant. The pictures shown here are very helpful from a non medical person like me.Now that i know all the procedure and the risk factors, i am sure to take better care of her.
<a href="http://www.dentzz.com/Dental-Implants.htm">dental implant india</a>

**Comment by jamiegiles** [comment]
+1

**Comment by aethior** [comment]
This request is very generic.
I think it's better to use separate requests.

- https://github.com/FortAwesome/Font-Awesome/issues/12876
- https://github.com/FortAwesome/Font-Awesome/issues/6216
- https://github.com/FortAwesome/Font-Awesome/issues/6215
- https://github.com/FortAwesome/Font-Awesome/issues/6214
- https://github.com/FortAwesome/Font-Awesome/issues/6213

cc/ @tagliala

**Comment by tagliala** [comment]
@aethior thanks

Yes, closing here in favor of individual requests (which meet our new contributing guidelines, probably at the time we didn't have restrictions)

Also

> An appointment icon, add, delete and edit

Those are unrelated to dental care, and in the meantime we implemented a lot of new calendar related icons, both in the Free and the Pro sets

https://fontawesome.com/search?q=calendar&s=solid%2Cbrands
