### ISSUE TITLE
Icon request: icon-self-timer

### ISSUE THREAD

**Issue by La8pv** [FortAwesome/Font-Awesome#6869]
http://www.google.no/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0CAcQjRw&url=http%3A%2F%2Fcpn.canon-europe.com%2Fcontent%2Feducation%2Finfobank%2Fcamera_settings%2Fself_timer_and_timed_exposures.do&ei=eLyWVbq5MIT6ygP05a4w&bvm=bv.96952980,d.bGQ&psig=AFQjCNGYRn-agauczQFUEBymDSXIdcSYZA&ust=1436028387261789

**Comment by tagliala** [comment]
Using this as `fa-self-timer`

Extra numbers could be add with the stacking feature or custom css

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
