### ISSUE TITLE
Icon Request: fa-scooter

### ISSUE THREAD

**Issue by jeroendhvv** [FortAwesome/Font-Awesome#6897]
There is a car, bus, truck, bike and motorcycle, but no scooter.

![fa-scooter](https://cloud.githubusercontent.com/assets/7705011/8566173/866f033a-255c-11e5-845e-20f061bb0fde.png)

**Comment by yabisko** [comment]
![scooter-02-256-8](https://cloud.githubusercontent.com/assets/15632696/10983863/fda2f658-841d-11e5-96bf-76d4edba2be4.png)

**Comment by zuck** [comment]
+1 but I think one of its more common use would be delivery service, so something like:

![Scooter1](https://cdn3.iconfinder.com/data/icons/e-commerce-8/91/moto-512.png)
![Scooter2](http://simpleicon.com/wp-content/uploads/scooter_1.png)
![Scooter3](http://thumb7.shutterstock.com/display_pic_with_logo/1537223/172311761/stock-vector-scooter-vector-icon-172311761.jpg)

**Comment by Crissov** [comment]
- 🛵 [U+1F6F5](http://emojipedia.org/motor-scooter/) Unicode emoji #222 
- 🛴 [U+1F6F4](http://emojipedia.org/scooter/)

**Comment by mikey186** [comment]
I really wish for a icon like this, but I prefer like this I found on Adobe Stock. https://stock.adobe.com/images/electric-kick-scooter-icon/210439746

**Comment by martindubenet** [comment]
As mention by @mikey186 there is confusion in English as the term « SCOOTER » is used for two different vehicules.

1. The *skateboard with a handlebar* used by kids
2. The *electrified skateboard with a handlebar* that since 2018 refers to products from LIME, BIRD, etc...
3. The *moped scooter* allowed on public roads as a motorcycle variant. Refering to Vespa products.

For that reason we'll need more then one single word to differ one icons to the others. So I propose:

1. `fa-scooter` = Foot-propelled kids toy.
2. `fa-scooter-electric` = Electrified city commuting skateboard with handlebar.
3. `fa-moped` or `fa-motor-scooter` = Motorcycle variant.

**Comment by Chukstart** [comment]
> As mention by @mikey186 there is confusion in English as the term « SCOOTER » is used for two different vehicules.
> 
> 1. The _skateboard with a handlebar_ used by kids
> 2. The _electrified skateboard with a handlebar_ that since 2018 refers to products from LIME, BIRD, etc...
> 3. The _moped scooter_ allowed on public roads as a motorcycle variant. Refering to Vespa products.
> 
> For that reason we'll need more then one single word to differ one icons to the others. So I propose:
> 
> 1. `fa-scooter` = Foot-propelled kids toy. I already proposed this one here #15447.
> 2. `fa-scooter-electric` = Electrified city commuting skateboard with handlebar.
> 3. `fa-moped` or `fa-motor-scooter` = Motorcycle variant.

Is this icon not there yet.....

**Comment by bertoost** [comment]
Really want this 👍

**Comment by FrancMunoz** [comment]
![istockphoto-1070585644-1024x1024](https://user-images.githubusercontent.com/8903413/83166212-dbf37100-a10e-11ea-9728-34a7432f3a32.jpg)

**Comment by sensibleworld** [comment]
Thanks for the request! We've just added this icon as part of version 6.

https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=moped&s=solid

<img width="1045" alt="Screen Shot 2021-05-27 at 1 54 57 PM" src="https://user-images.githubusercontent.com/529604/119873963-20b51200-bef3-11eb-89a2-37db768d40d7.png">
