### ISSUE TITLE
Icon Request: fa-users-plus

### ISSUE THREAD

**Issue by Eschwinm** [FortAwesome/Font-Awesome#6908]
![add](https://cloud.githubusercontent.com/assets/13255480/8595899/510d34a0-264c-11e5-8f28-75b14391f808.jpg)

I would like to use this icon for my own CRM. I have organisations in there and users. I like the new icon user-plus to add a new user. currently there's an organisation icon missing with the 'add' marker.

**Comment by tagliala** [comment]
refers to #1181 

Please take a look at that thread, you will find a solution

**Comment by Kidrive** [comment]
I don't think overlay is a good solution. Since user-times and user-plus exists, it could be nice and self-consistent to have userS-times and userS-plus.

**Comment by lzynihao** [comment]
I need the users + times which means delete user groups

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
