### ISSUE TITLE
Icon Request: fa-tv-y, fa-tv-y7, fa-tv-g, fa-tv-pg, fa-tv-14, fa-tv-ma (tv parental guidelines)

### ISSUE THREAD

**Issue by vbctv** [FortAwesome/Font-Awesome#6951]
edit by @tagliala

https://en.wikipedia.org/wiki/TV_Parental_Guidelines
## 

TV PG
TV 14
TV MA

All the TV ratings for use on TV Network websites.

**Comment by tvirelli** [comment]
@vbctv here is a way you can do this now just by stacking icons with fonts:

http://jsfiddle.net/pd5xv6sc/

**Comment by tvirelli** [comment]
This is close to [#6239](https://github.com/FortAwesome/Font-Awesome/issues/6239)

**Comment by tagliala** [comment]
Leaving this open, but please consider a custom build 

https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

> So, if you need a new icon in a short while, **or you need a comprehensive set of icons (e.g., a set of weather icons to build a forecast application)** our suggestion is to customize Font Awesome.

**Comment by MVcodeartbr** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
