### ISSUE TITLE
Icon Request : fa-dollar-slash

### ISSUE THREAD

**Issue by nabeelkondotty** [FortAwesome/Font-Awesome#6956]
Please add an icon for Free or Dollar slash which indicates free service or product for free.

Thanks

**Comment by Krevo** [comment]
May be you can stack fa-ban on fa-usd.

**Comment by tagliala** [comment]
the request is legit but I'm for the stack solution

otherwise Dave should also implement all fa-*currency*-slash variants

**Comment by Krevo** [comment]
Can also stack fa-slash (see #3691) on fa-usd

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
