### ISSUE TITLE
Site crashes in IE8

### ISSUE THREAD

**Issue by hmulay** [FortAwesome/Font-Awesome#6974]
Hi,

We are using the font-awesome in our web pages. Sometimes when we load our site in IE8, it crashes the browser. This happens very frequently. We are investigating other possible reasons however we observed that when we stripped off font awesome tags from the pages using fiddler, our site stopped crashing in IE8.

We also observed that if we opened font awesome site pages (http://fortawesome.github.io/Font-Awesome/ link) in IE8 and then IE8 crashes after we refresh the page.

Is this a known issue? Is there any way to resolve the issue?

Thanks.
Regards,
Hemant

I

**Comment by tagliala** [comment]
IE8 has some random issues, but I'm not aware of reboots. leaving this open

**Comment by GabGab** [comment]
Hello there, 

We are currently experiencing the same problem with IE8 (hard crash). We are using the latest font-awesome-rails rubygem (4.3.0.0), and were able to determine that the problem was coming from somewhere inside the included font-awesome css stylesheet. 

When we removed the stylesheet inclusion, the site would load and display properly (except for the FA icons of course). With the stylesheet included, the page does not load and a crash message error from IE8 shows up. Of course the site works properly in all IE browsers > 8, as well as Safari/Chrome/FireFox/Safari iOS/Android etc.

Do you know where this might come from ? 

Thanks for any help you can provide !
