### ISSUE TITLE
Icon request : fa-equilibrium (chemistry)

### ISSUE THREAD

**Issue by ankit-maverick** [FortAwesome/Font-Awesome#6983]
https://www.google.co.in/search?q=transfer&client=ubuntu&hs=Uv7&channel=fs&source=lnms&tbm=isch&sa=X&ved=0CAgQ_AUoAmoVChMIo_PsnvXmxgIVyo6OCh1wtw_I&biw=1366&bih=673#channel=fs&tbm=isch&q=equilibrium+symbol

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome! [Take a look at it here.](https://fontawesome.com/icons/right-left?f=classic&s=solid)
