### ISSUE TITLE
Icon Request: icon-bell-call-24h (service call 24h)

### ISSUE THREAD

**Issue by Arnau-ads** [FortAwesome/Font-Awesome#6989]
Need an icon for 24h reception availability in hotel

**Comment by tagliala** [comment]
any example?

**Comment by Arnau-ads** [comment]
Something like this: https://cloud.githubusercontent.com/assets/13414782/8772596/b9a4f5fa-2ecd-11e5-9cc2-c43fb37b81c9.png

**Comment by tuxy** [comment]
Here is many more examples > http://www.flaticon.com/search/24-hours

**Comment by tagliala** [comment]
Refers to #3919

**Comment by tuxy** [comment]
@tagliala, done. Thank You!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
