### ISSUE TITLE
Icon Request: fa-nonprofit (heart in hand)

### ISSUE THREAD

**Issue by EBonar** [FortAwesome/Font-Awesome#6991]
I would like to use it on an Industries Served page in a website, http://dev.colormixgraphics.com/industries-served/
![nonprofiticon_proof1](https://cloud.githubusercontent.com/assets/11934450/8777477/d44337ec-2ebd-11e5-804f-1f390fd3ebe6.png)

Thank you for your consideration.
Ebonar

**Comment by tuxy** [comment]
alternative fa-nonprofit icon:

![Alt NonProfit](http://i.imgur.com/Sl0MB0l.png)
Source: http://www.flaticon.com/free-icon/give-love_67410

**Comment by tagliala** [comment]
almost a duplicate of #2224

**Comment by tuxy** [comment]
@tagliala, No because #2224 is only fa-open-hand and does not include a heart. Which can be assosiated with non-profit organizations. It can also be a fa-heart-dove "bird in the heart" icon.

More examples; https://encrypted.google.com/search?q=non+profit+organization+symbol+hand+heart&source=lnms&tbm=isch

**Comment by EBonar** [comment]
@tuxy Thank you!

**Comment by tagliala** [comment]
@tuxy thanks for the clarification

**Comment by chtay1** [comment]
+1

**Comment by bennyp123** [comment]
+1

**Comment by alexdahlmandrm** [comment]
+1. Any work on this?

**Comment by sensibleworld** [comment]
Released in 5.0.9
