### ISSUE TITLE
Icon request: icon-call-split

### ISSUE THREAD

**Issue by 123blog** [FortAwesome/Font-Awesome#7001]
I want to a icon like that:
![icon-call-split](https://cloud.githubusercontent.com/assets/12905140/8793523/63c05c12-2fa2-11e5-9ce3-385ccd4bb0d9.png)

**Comment by tuxy** [comment]
Its better to call it fa-split-arrows. Also here is more examples;

![Split Arrows](http://i.imgur.com/92895KB.png)
Source: https://www.iconfinder.com/icons/326496/call_split_icon#size=128

**Comment by 123blog** [comment]
thank you !

**Comment by nielhardt** [comment]
+1

**Comment by PlassJ** [comment]
+1

**Comment by adexerivera** [comment]
+1

**Comment by orielsy** [comment]
It's 2020. Ver 5.0 has been out for some time.  

+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/split?f=classic&s=solid)
