### ISSUE TITLE
Icon Request: fa-hdtv

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#7010]
fa-hdtv icon:
![New TV](http://i.imgur.com/ZlaW9cQ.png)
Source: http://www.iconarchive.com/show/windows-8-icons-by-icons8/Household-Hdtv-icon.html

**Comment by tagliala** [comment]
tv: #368 , please +1 that request

leaving this open as hdtv

**Comment by tuxy** [comment]
@ tagliala, thank you!

**Comment by nielhardt** [comment]
+1

**Comment by Igcorreia** [comment]
+1

**Comment by Dan-Brantze** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/high-definition?f=classic&s=solid)
