### ISSUE TITLE
Icon Request: fa-user-question

### ISSUE THREAD

**Issue by niarkova** [FortAwesome/Font-Awesome#7026]
Hello! Loved the new user-plus and user-times icons. Could you please create a similar icon but with a question mark sign instead?
I would use it to represent 'anonymous' or 'unknown user'.

Thank you so much for your time!

**Comment by tagliala** [comment]
Refers to #1181

**Comment by heriniaina** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
