### ISSUE TITLE
Motor cycle accessories 

### ISSUE THREAD

**Issue by daplin2007** [FortAwesome/Font-Awesome#7041]
Hi

Requesting for new icons like motor accessories helmet, gloves, gear etc...

Thanks!

**Comment by tagliala** [comment]
Sorry, can't leave this open because it doesn't meet our contributing guidelines:

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

Even if you need all those icons for your use case, you should open individual request having care of searching for duplicates before
