### ISSUE TITLE
Icon Request: fa-ZAR icon-R

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#7045]
I would like a currency icon for South African Currency (R) Rand symbol please to be used on a wordpress project. 
![randsymbol](https://cloud.githubusercontent.com/assets/13505797/8893151/d7b17314-3384-11e5-8ef6-bb0191c38f15.png)

**Comment by nebuladesigns** [comment]
Please can someone assist with this icon issue.

**Comment by tagliala** [comment]
@ghost

if you need this icon in a short while, you could use the standard unicode point

```css
.fa-zar {
  content: 'R';
}
```

otherwise, you could go for a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome! [Take a look at it here.](https://fontawesome.com/icons/r?f=classic&s=solid)
