### ISSUE TITLE
Icon Request: Trajectory

### ISSUE THREAD

**Issue by aeryn21** [FortAwesome/Font-Awesome#7084]
Something from the base, up, and halfway down again.  Like with a fly ball, or a model rocket.

**Comment by tvirelli** [comment]
Can you give an example icon? I am not able to picture exactly what you are looking for. Thanks.

**Comment by aeryn21** [comment]
Oh crap, I never did that!  
![trajectory-icon](https://cloud.githubusercontent.com/assets/6741290/9093201/db62c266-3b67-11e5-90e5-908798b65d4c.png)

**Comment by tvirelli** [comment]
@aeryn21 thank you for providing an example.

**Comment by MVcodeartbr** [comment]
to much abstract for me

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
