### ISSUE TITLE
CodiePie logo

### ISSUE THREAD

**Issue by davegandy** [FortAwesome/Font-Awesome#7098]

**Comment by davegandy** [comment]
Added to 4.4.1-wip branch. Closing.

**Comment by floriansegginger** [comment]
Why are these types of brand icons added on every version, yet you wait to have 50+ requests for something basic like a computer chip in #1840 ?

**Comment by bramslob** [comment]
@floriansegginger probably because brand icons are unmistakable. There are only so many ways you can show for instance the Github logo. Yet something so subjective as 'a computer chip' is way more work to get right. 

Of course your example, the computer chip is almost 2 1/2 years old and it would help if there was an open/collaborative process to help design/form the icons.
But I just wanted to jump in to give some sort of explanation/defense.

**Comment by fredrkr** [comment]
@floriansegginger I completely agree. Codie Pie is a company that makes Wordpress themes (!) and I think bloating Font Awesome with brand icons like this is a mistake given the amount of requests for non-brand icons.
