### ISSUE TITLE
identical icons

### ISSUE THREAD

**Issue by beliyadm** [FortAwesome/Font-Awesome#7143]
http://fontawesome.io/icon/cog/ and http://fontawesome.io/icon/cog/
exactly the same icons

**Comment by tuxy** [comment]
@beliyadm Am I missing something, or you made typo ? You have exactly same name ``cog`` for both links.

**Comment by tagliala** [comment]
it is also the same link, I probably didn't get this request

Maybe you mean `fa-gear` and `fa-cog` are the same icon?

**Comment by beliyadm** [comment]
Yes, exactly this.
I meant that the list of icons http://fontawesome.io/icons/ icons GEAR and COG the same. The both links provide http://fontawesome.io/icon/cog/
Partly confusion, not you think?

**Comment by tuxy** [comment]
@beliyadm fa-cog is an alias for fa-gear.

**Comment by beliyadm** [comment]
only one question - why do need an alias? Only heavier script

**Comment by tuxy** [comment]
I agree, fa-cog is not as good as fa-gear anyway :-)

**Comment by tagliala** [comment]
> only one question - why do need an alias? Only heavier script

that was before we added filters on the documentation, people had troubles when looking for a gear.

A better example: `fa-close` is an alias for `fa-times`. The name is due to the html entity `&times;` ×

If you look for `Icon request: icon-close` you will find a lot of requests

Hope it helps, closing here

**Comment by tagliala** [comment]
I'm in favour of dropping aliases in 5.0.0 to reduce css footprint
