### ISSUE TITLE
Icon request: bobcat - equipment

### ISSUE THREAD

**Issue by awillness** [FortAwesome/Font-Awesome#7159]
Is there any equipment icons like this? How can I have one created?

![bobcat-equipment](https://cloud.githubusercontent.com/assets/13684572/9122890/409e1892-3c49-11e5-9d26-465a3b279e80.gif)

**Comment by aethior** [comment]
Duplicate or related of  #4084, #5305, #10032?

cc/ @tagliala

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

We do have a few more construction/transportation-related icons available now: https://fontawesome.com/search?q=construction&o=r&c=transportation&s=solid&f=classic
