### ISSUE TITLE
Icon Request: fa-note-[quarter/half/dotted-half/whole]

### ISSUE THREAD

**Issue by TheChen5** [FortAwesome/Font-Awesome#7186]
Icons for the music notes quarter, half, dotted half, whole
This was mentioned in #2134 but that wasn't an individual request
I put these requests in one issue as I think it would be dumb to make an issue for each one of these

quarter: http://exchangedownloads.smarttech.com/public/content/2a/2a7d05f0-c568-46ae-8351-882511f579b8/previews/medium/0001.png

half: http://www.polyvore.com/cgi/img-thing?.out=jpg&size=l&tid=65938669

dotted half: https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Dotted_half_note_with_upwards_stem.svg/2000px-Dotted_half_note_with_upwards_stem.svg.png

whole: http://images.all-free-download.com/images/graphiclarge/whole_note_144266.jpg

**Comment by peiche** [comment]
+1

**Comment by damusix** [comment]
+1

**Comment by Wingo5315** [comment]
+1 The half and quarter note could be the same icon, but the half note could be far fa-note and the quarter fas fa-note.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
