### ISSUE TITLE
Icon Request: fa-cricket-ball

### ISSUE THREAD

**Issue by Jeyanthinath** [FortAwesome/Font-Awesome#7200]
![ball](https://cloud.githubusercontent.com/assets/2253649/9196372/6825b160-4048-11e5-935b-3d03b159b1b3.jpg)

**Comment by mbdixon** [comment]
This would be great for my website too....

**Comment by Jeyanthinath** [comment]
any update on this ?

**Comment by ayoubkhan558** [comment]
any update on this ?

**Comment by sensibleworld** [comment]
We do not have a cricket-ball icon, but we do have this: https://fontawesome.com/icons/cricket-bat-ball?s=solid

**Comment by Jeyanthinath** [comment]
Can't we have a modular icons (bat seperately and ball seperately), so that we can use is whatever way we want.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
