### ISSUE TITLE
Icon Request: fa-admission and fa-discharge

### ISSUE THREAD

**Issue by dadoadk** [FortAwesome/Font-Awesome#7215]
Use cases: 
    - in health industry, patients are usually admitted and discharged to and from facilities, and their status needs to be marked.
 (i'm using this in my app next to date to show that's the date when patient is admitted or discharged)
    - in hotel industry patrons that are in status of visiting or leaving.

![admission_icon](https://cloud.githubusercontent.com/assets/11295452/9231997/3c10c9b4-40f9-11e5-8e29-68078d627f73.png)
![discharge_icon](https://cloud.githubusercontent.com/assets/11295452/9231998/3c11dcdc-40f9-11e5-88cb-775fcb1469e4.png)

**Comment by seysoosey** [comment]
+1

**Comment by kimberley-johnston** [comment]
+1

**Comment by palak6041** [comment]
+1

**Comment by tienti-b** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
