### ISSUE TITLE
Icon request: fa-image-xmark

### ISSUE THREAD

**Issue by eloyucu** [FortAwesome/Font-Awesome#7254]
A icon like picture-o but  with a x (similar as user-times).
Thank you.

**Comment by caduvieira** [comment]
Like this?
http://jsfiddle.net/nwbwtnpg/1/

**Comment by tagliala** [comment]
refers to #1181

**Comment by eloyucu** [comment]
ummm... and why does exist user-times having this method?? (maybe because it is a very common and used icon??)

Thanks

**Comment by tagliala** [comment]
> maybe because it is a very common and used icon??

Right :)

It was a popular request #902

**Comment by aethior** [comment]
Also known as `image-xmark` according with the current icons name.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
