### ISSUE TITLE
Icon Request: fa-arrow-v-opposite (fa-arrow-h-opposite)

### ISSUE THREAD

**Issue by eloyucu** [FortAwesome/Font-Awesome#7255]
Hello again.
A icon similar to fa-arrow-h, but opposite the pointers, something like -><- . It could be meaning that an element can be make smaller. For example I am using for make smaller an item the fa-exchange icon, and to make bigger the fa-arrow-h, only clicking once on each button.
The same happen with fa-arrow-v. On the same example, I use expand and compress to make higher or shorter.

Thank you.

**Comment by caduvieira** [comment]
Related #2545

**Comment by eloyucu** [comment]
thanks @caduvieira and thanks @tagliala

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/arrow-down-left-and-arrow-up-right-to-center?f=classic&s=solid)
