### ISSUE TITLE
Icon request: icon-horse along with a range of other animals

### ISSUE THREAD

**Issue by jswainosd** [FortAwesome/Font-Awesome#7259]
Hi,

Are there any plans to add a range of animals?

Icon request: icon-horse
Icon request: icon-pig
Icon request: icon-cow
Icon request: icon-chicken

etc. ?

**Comment by caduvieira** [comment]
Horse #2049
Cow #4166
Related #5927

**Comment by TheChen5** [comment]
+1 those
:mag:before:heavy_plus_sign:

**Comment by tagliala** [comment]
@caduvieira @TheChen5 thanks, really appreciate

@jswainosd as they said, please +1 proper requests, then take a look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

Since you are requesting a comprehensive set of icons, you should take into account a custom build of fontawesome: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

You can merge an icon font with a comprehensive set of animals with the icons you need from fontawesome

Closing here
