### ISSUE TITLE
Icon Request: fa-current-location

### ISSUE THREAD

**Issue by stantond** [FortAwesome/Font-Awesome#7340]
[`fa-map-marker`](http://fortawesome.github.io/Font-Awesome/icon/map-marker/) is perfect for showing any location on a map, but without additional context, and particularly in a button, it doesn't suggest current location.

[`fa-crosshairs`](http://fortawesome.github.io/Font-Awesome/icon/crosshairs/) is again useful for showing a location on a map, but, without the map for context, doesn't suggest current location.

[`fa-location-arrow`](http://fortawesome.github.io/Font-Awesome/icon/location-arrow/) suggests movement. I've seen it used in sat-navs.

I thought something similar to these examples would be ideal:

![Image of Current Location Icon Example 1](http://www.en.mspy.eu/images/icon_4.gif)

![Image of Current Location Icon Example 2](http://www.270towin.com/elected-officials/imgs/geolocate.png)

![Image of Current Location Icon Example 3](http://images.clipartpanda.com/google-location-icon-icon-location.png)

![Image of Current Location Icon Example 4](https://d13yacurqjgara.cloudfront.net/users/16463/screenshots/980623/location-icon_2x.jpeg)

**Comment by dekaikiwi** [comment]
+1

**Comment by smhk** [comment]
dude - SVG would be sweet

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
