### ISSUE TITLE
Icon Request: fa-user-bars , fa-user-menu 

### ISSUE THREAD

**Issue by pgroot91** [FortAwesome/Font-Awesome#7363]
Hallo,

I think this icon deserves it's spot in the font awesome kit. 

![user-bars_user-menu_font-awesome](https://cloud.githubusercontent.com/assets/6934501/9628542/0554b1d2-516c-11e5-9661-23db728a2262.jpg)

This icon specify's the user menu related things that opens off canvas panel with your, profile settings, messages, notifications, signout etc. etc. 

Kind Regards,
Patrick

**Comment by My1** [comment]
not a bad Idea.
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
