### ISSUE TITLE
Icon Request: fa-ellipsis-h-top

### ISSUE THREAD

**Issue by keon109** [FortAwesome/Font-Awesome#7378]
same icon as fa-ellipsis-h but location of the icon is at the same hight as the top line of fa-th.

In the same vision it can be easy to create also an fa-ellipsis-v-left.

greetings
Koen

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
