### ISSUE TITLE
Icon Request: fa-chip-pin

### ISSUE THREAD

**Issue by danielfeather** [FortAwesome/Font-Awesome#7403]
I would use this on my website to indicate that we accept chip and pin payments in-store at the bottom of my page next to the rest of the other icons such as the master-card, visa and american express icons, this would be an icon that would be used to indicate to customers that the store or company uses chip and pin

![chipandpin-outline](https://cloud.githubusercontent.com/assets/12731372/9705248/b3deca1a-54b6-11e5-9f4d-56b365673156.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
