### ISSUE TITLE
Including Font-Awesome makes website slow/unresponsive/laggy in Chrome

### ISSUE THREAD

**Issue by darsain** [FortAwesome/Font-Awesome#743]
As soon as I include this font on my website, it makes all hover effects laggy. Even those that don't contain any icons.

I'm running on Win 7, and this happens only in Chrome (from current stable: 24, to canary: 26).

Normally, I'd consider this to be a browser issue and just dealt with it, but fork of this font [Font-Awesome-More](http://gregoryloucas.github.com/Font-Awesome-More/) doesn't have this issue. Including that doesn't slow anything at all.

The demo is actually not needed as I observe the same thing on homepages of both fonts. Font-Awesome homepage is really laggy, while Font-Awesome-More is as fast as it gets.

**Comment by farhadniaz** [comment]
in current project that i work  on i used font-awesome . the font-awesome make all hover effects laggy and bad page loading . 
i used a lot of  star icon of the font-awesome to make rating elements . in the first i think it's because of the rendering a lot of font icon in the page . and i tried using image instead the font-awesome  and font awesome stay in page ,but it doesn't work . then i removed  the font-awesome , this time every thing worked okay.

now have i to remove the font-awesome for this issues if it haven't any improvement solution?if yes?what  other icon fonts do you recommend ?
