### ISSUE TITLE
Icon request: Four wheel drive

### ISSUE THREAD

**Issue by HarelM** [FortAwesome/Font-Awesome#7437]
I want to allow the user to select between routing options. one of the routing type is 4wd. my suggestion is something like a car and a '~' beneath it.

**Comment by dpfem** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/car-bump?f=classic&s=solid)

**Comment by tagliala** [comment]
@sensibleworld  `car-bump` may be used for a subset of this use case, but maybe it is not the requested icon: the `~` should symbolize the differential gear below the car.

Maybe this can be considered as "declined"
