### ISSUE TITLE
Icon Request: icon-svn

### ISSUE THREAD

**Issue by hackily** [FortAwesome/Font-Awesome#7488]
Seeing as an icon for git already exists, it would make sense to have the icons of other version control systems as well.
It is feasible that if someone were to be using the Git icon, they may also want to use other VCS icons. 

The icon could be placed in a section that would denote which VCS an application had native support for. Or if someone wanted to differentiate repositories in a list of repositories, these icons would make this very simple.

Here is an image for the SVN logo:
http://svn.apache.org/repos/asf/subversion/trunk/notes/logo/subversion_logo_notxt.png

**Comment by itapplication** [comment]
Please also create icon for SVN client TortoiseSVN https://tortoisesvn.net/ and Trac

**Comment by sampsonliu** [comment]
when the fa-svn is added to  Font-Awesome ?
I want to use the fa-svn icon in my program。

**Comment by sampsonliu** [comment]
![fa-svn fa-git](https://cloud.githubusercontent.com/assets/15682051/26230173/83356c82-3c79-11e7-9172-32ed273fbc2d.png)

**Comment by jovarweb** [comment]
Hello, I would also like to have the fa-svn icon available.
Is there any progress?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
