### ISSUE TITLE
Icon request: icon-csd-studio

### ISSUE THREAD

**Issue by CSD-studio** [FortAwesome/Font-Awesome#7507]
Hi ! If i have some ideas for a new icons, in what format better to send it? *.eps, *.svg ?

Icon request: icon-csd-studio
Use in my website and in websites what we make

![csd_logo_new](https://cloud.githubusercontent.com/assets/14673343/10008894/4ec7d864-60dd-11e5-8844-08b4aeed2a20.png)

**Comment by TheChen5** [comment]
I don't think that's really a problem.
Only a simple image is needed
Change the request name to "Icon request: icon-csd-studio"

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
