### ISSUE TITLE
Icon Request: fa-solarium

### ISSUE THREAD

**Issue by alex21** [FortAwesome/Font-Awesome#7510]
I need solarium icon. Can you add this?
Thanks

**Comment by tagliala** [comment]
any example?

**Comment by alex21** [comment]
Hmm I'm not sure. I can'f find something that, but I only found 
![tan](https://cloud.githubusercontent.com/assets/13554635/10021808/176ef682-614a-11e5-8316-56b9667b72dc.png) Maybe someone has an idea.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
