### ISSUE TITLE
Icon Request: fa-auroracoin

### ISSUE THREAD

**Issue by Skarfurinn** [FortAwesome/Font-Awesome#7597]
It would be awesome if the currency symbol for Auroracoin could be added. 

Auroracoin is a cryptocurrency that is based on Bitcoin. At launch it was distributed to the Icelandic public where over 10% of the nation claimed their coins. This was the first cryptocurrency that had a geological distribution so it raised a lot of interest throughout the world and has gotten wide usage. 

For this reason I think it would be very useful to get a Font Awesome payment Icon for Auroracoin as people need to use it as a payment symbol in basically all applications that either displays a value/price or requires a payment.

Auroracoin already has a symbol for payments which is the same symbol that is in the Auroracoin logo. That is the fé rune (also known as fe, fenu fehu). In current times the Icelandic word fé means money but it's also means sheep which was the currency of trade in the old days.

Here are some samples of the fé rune.

![fehu2](https://cloud.githubusercontent.com/assets/7969487/10256256/7b6a12fa-693f-11e5-83dd-7c03948c8b32.jpg)
![fehu](https://cloud.githubusercontent.com/assets/7969487/10256255/7b69cff2-693f-11e5-947c-3b76af1a2ac6.jpg)
![fehu3](https://cloud.githubusercontent.com/assets/7969487/10256257/7b6b2726-693f-11e5-8268-530fb358998c.png)

Here you can see how it's in the Auroracoin logo.

![auroralogo](https://cloud.githubusercontent.com/assets/7969487/10256283/a3d018a2-693f-11e5-8799-1d87e2be0327.png)

Thanks for Font Awesome, I appreciate your work on this and I hope you will consider this request. :)

**Comment by Stirling** [comment]
+1 great idea

**Comment by Dinobotta** [comment]
+1

**Comment by GULDEX** [comment]
+1 awesomeness!

**Comment by BioMike** [comment]
+1

**Comment by SkateFish** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Comment by SkateFish** [comment]
okay, well it is the the first letter of the Futhark rune set.  so if that was something you would consider placing in fontawesome, due to international interest in the runes, then perhaps that would be a valid case.  just suggesting 
something like this would be nice from our perspective. 
https://www.fontspace.com/futhark-aoe-font-f518

amazing to see the work that has happened with FontAwesome !    take care,  michael
