### ISSUE TITLE
Icon Request: fa-language-mn

### ISSUE THREAD

**Issue by batpurev** [FortAwesome/Font-Awesome#7599]
hi,

FA icons look great and we wish to have one of these icons for our language switcher icon. Most websites use flags for their language switcher some use language codes for example EN for English DE for Dutch etc.,

Our need is to have FA icons for EN and MN which will look like Facebook icon or Twitter icon. 
![icon request](https://cloud.githubusercontent.com/assets/3252495/10261658/1caae060-6957-11e5-91d5-dbfa8c7f7b52.png)

list of languages are available at: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
column titled 639-1 has two word language codes for all languages. My idea is to have FA icon for each of these languages. (Currently I need EN and MN though)

**Comment by tagliala** [comment]
I'm going to close this one because of this poin

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

You are requesting 185 (`$('.wikitable tbody tr').length`)new icons. You should consider a simpler solution, like stacking text on icons: http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/
