### ISSUE TITLE
Icon-request: cc-avenue

### ISSUE THREAD

**Issue by jbmorse** [FortAwesome/Font-Awesome#7649]
![ccavenue-icon](https://cloud.githubusercontent.com/assets/3848373/10399985/22d34c84-6e84-11e5-9aaa-27ca6b80cb2d.png)

An Icon such as this would work well with the other cc-[paymentType] icons. This is the only icon I have to use a special case for to generate an image.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
