### ISSUE TITLE
Icon request: icon-code-repository

### ISSUE THREAD

**Issue by JeroenSormani** [FortAwesome/Font-Awesome#7656]
My use case is for representing repositories as I'm listing/displaying them.

I can also imagine other people can use the icon as its basically a book.

![image](https://cloud.githubusercontent.com/assets/5774447/10415340/b77cb858-6ff5-11e5-8a38-b2d574825629.png)

I think this goes a bit hand in hand with https://github.com/FortAwesome/Font-Awesome/issues/2497

Thanks for the all the great work :smile:

**Comment by aethior** [comment]
@tagliala `coding (category)` label for this request?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/book-bookmark?f=classic&s=solid)
