### ISSUE TITLE
Icon Request: icon-blocker-priority, icon-critical-priority, icon-major-priority, icon-minor-priority, icon-optional-priority and icon-trivial-priority

### ISSUE THREAD

**Issue by ge0ffrey** [FortAwesome/Font-Awesome#7673]
I 'd like to request a set of icons to show the priority of an issue or task:

icon-blocker-priority
icon-critical-priority
icon-major-priority
icon-minor-priority
icon-optional-priority
icon-trivial-priority

This is handy for open source project's release notes and upgrade recipe's, but also for showing todo lists etc.

Here is a proprietary app that has such a set:
  https://answers.atlassian.com/upfiles/JIRA_question_95714_2.jpg

**Comment by dereuromark** [comment]
The link is dead
Is there a screenshot of it maybe?

**Comment by ge0ffrey** [comment]
https://i2.wp.com/reportsforjira.com/wp-content/uploads/2020/07/jira-priorities.png?fit=1598%2C458&ssl=1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
