### ISSUE TITLE
Icon request: icon-menu

### ISSUE THREAD

**Issue by eNerdDesigns** [FortAwesome/Font-Awesome#7767]
I'm looking for a way to make the fa-bars hamburger style menu icon more intuitive to use for those who do not understand the three lines means menu.

The reason i wish to modify this button is due to limited spacing in headers on responsive scale to fit both the icon and the word (menu) next to it so i'd like an icon that merges the two.

I have created a sample to demonstrate how this can work. 

![1446023245_menu-alt](https://cloud.githubusercontent.com/assets/15355279/10779659/fe7c5d86-7d87-11e5-9807-40bab45b1ce5.png)

**Comment by tagliala** [comment]
The request is legit, but this icon will harldy fit 14px icon size

**Comment by eNerdDesigns** [comment]
![menu-14px](https://cloud.githubusercontent.com/assets/15355279/10871780/bdd4f886-8144-11e5-9311-20ec47a203fe.png)

**Comment by tagliala** [comment]
I can barely read menu, it looks like fa-hamburger

I would consider a pure css solution. You will also take advantage of using the font of your application: http://jsfiddle.net/tagliala/15nmqqe1/

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
