### ISSUE TITLE
Icon request: Fullscreen/small window icons

### ISSUE THREAD

**Issue by vanderlee** [FortAwesome/Font-Awesome#7793]
Like those at top-right of the Microsoft Windows window titlebars:
- Fullscreen window: square with slightly thicker top border
- Two smaller shapes like the fullscreen one; one top-right, second bottom-left overlapping other.

Somewhat like this sketch:
![image](https://cloud.githubusercontent.com/assets/649240/10869577/ba9c4b1a-80b3-11e5-8ce9-bad738c9121b.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/search?q=window&o=r)
