### ISSUE TITLE
Icon request: icon-form

### ISSUE THREAD

**Issue by adriaandotcom** [FortAwesome/Font-Awesome#780]
I now use "icon-th-list", but I would be nice to have an icon for forms.

Maybe something like this:
![form_icon](https://f.cloud.github.com/assets/1079135/167574/409f7d72-79dc-11e2-99b6-f55fdecef3fa.jpg)

**Comment by christianklemp-imt** [comment]
👍 this icon would be super useful for a web application I'm working on right now.

**Comment by mariuszpala** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
