### ISSUE TITLE
Icon Request: fa-eyes-arrows

### ISSUE THREAD

**Issue by behnammodi** [FortAwesome/Font-Awesome#7848]
envirenment analysis

![envirenment-analysis](https://cloud.githubusercontent.com/assets/1549069/11019846/71839126-8604-11e5-977f-d740ec691496.jpg)

**Comment by tagliala** [comment]
I don't like this title, have you something better in mind?

**Comment by MrGrigri** [comment]
fa-awareness

**Comment by uxitten** [comment]
fa-awareness nice title

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
