### ISSUE TITLE
Icon Request: fa-tasks-refresh

### ISSUE THREAD

**Issue by behnammodi** [FortAwesome/Font-Awesome#7854]
replanning icon
![replanning](https://cloud.githubusercontent.com/assets/1549069/11020282/1db0d226-8612-11e5-91cf-22a5ecbd7b74.jpg)

**Comment by tagliala** [comment]
way too complciated for 14px icon size

I would go for the following approach: #1181 

renaming to `fa-task-refresh`

**Comment by nyon** [comment]
I added an icon to nyon/fontawesome-actions@d142fa3a38e07d0b95977e9ef5e86a495e3a5559 that could fit your purpose.

    fa-tasks-refresh

**Comment by mschadegg** [comment]
Would be nice with the same, but with a plus to add new tasks (maybee one with a minus too).
![image](https://cloud.githubusercontent.com/assets/11231039/14143745/294fbcdc-f68d-11e5-921c-74dd86748f09.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
