### ISSUE TITLE
Animation-Request: Shake

### ISSUE THREAD

**Issue by D4rkTiger** [FortAwesome/Font-Awesome#7882]
Hi,

Please find below a suggested animation to complete existing ones

.@{fa-css-prefix}-shake {
  -webkit-animation: fa-shake 2s 3 linear;
          animation: fa-shake 2s 3 linear;
}

@keyframes fa-shake {
    0%, 100% {
        -webkit-transform: rotate(0deg);
         transform: rotate(0deg);
    }
    10%, 30%, 50%, 70%, 90% {  
        -webkit-transform: rotate(10deg);
         transform: rotate(10deg);
    }
    20%, 40%, 60%, 80% {  
        -webkit-transform: rotate(-20deg);
         transform: rotate(-20deg);
    }
}

With my pleasure to contribute to this project ;-)

**Comment by HerrBertling** [comment]
Hey @D4rkTiger – could you explain why you want to use this? I could prepare a pull request for this, some background information would be great.

**Comment by D4rkTiger** [comment]
I use it simply to animate an icon, in my case, on the maintenance page or "coming soon" page.

I know that it is not the marvelous animation that all people wants but if they want, it is here ;-).

**Comment by HerrBertling** [comment]
Thanks for your answer! I'm not really involved in this project up to now, but it seems to me that the other animations are more "functional" in the sense that a loading spinner just needs to spin, since that's what the name already suggests. Hence, I'd only add definitely needed animations and leave the rest (like your animation) to the consumer (which would be you in this case ;) ).

That's most certainly to be discussed, so any input from other people on whether to add this or not would be helpful.

**Comment by tagliala** [comment]
If it would depend on me, I would also drop the spinning animation :)

#671 #3369 #3451 #7572 and maybe more

I would consider .svg for animations

**Comment by D4rkTiger** [comment]
I think you're right. New format SVG should be sufficient to do this stuff and for other format, assume consumer (like me :) ) can add this stuff into own styles
