### ISSUE TITLE
Icon Request: fa-card-plus

### ISSUE THREAD

**Issue by adammade** [FortAwesome/Font-Awesome#7892]
Could you look into adding an "Add card" icon or "Plus Card" icon - useful for e-commerce/ticketing situations in account areas and booking paths.

Something like the attached:
![plus-card](https://cloud.githubusercontent.com/assets/6839169/11181917/7c5f0ea8-8c5e-11e5-9cdf-22fe249cbe9b.png)

Cheers!

**Comment by tagliala** [comment]
Refers to #1181 , you will find a solution there

**Comment by tagliala** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
