### ISSUE TITLE
Icon Request: fa-czech-coin

### ISSUE THREAD

**Issue by dirart** [FortAwesome/Font-Awesome#7930]
Please add icon czech coin. Thanks :)
![czech-koruna-512 1](https://cloud.githubusercontent.com/assets/15933307/11286396/04e95748-8f15-11e5-9ebb-1d05d9c4e831.jpg)

**Comment by vsemecky** [comment]
+1

**Comment by dirart** [comment]
Please add icon czech coin. Thanks :)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
