### ISSUE TITLE
Icon Request: fa-invoice-send

### ISSUE THREAD

**Issue by gambetto** [FortAwesome/Font-Awesome#7945]
![image](https://cloud.githubusercontent.com/assets/7262110/11300793/2556a45e-8f92-11e5-873c-51542e3055bd.png)

**Comment by tagliala** [comment]
may refer to #1181

**Comment by tagliala** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
