### ISSUE TITLE
That's not what the <i> tag is for

### ISSUE THREAD

**Issue by arcwhite** [FortAwesome/Font-Awesome#799]
Love the library, but I feel it breaks the semantics of HTML. Specifically, the use of the <i> tag:

> "... the element has now been given the specific semantic purpose of representing text 
> “offset from its surrounding content without conveying any extra emphasis or importance, 
> and for which the conventional typographic presentation is italic text”."
> -- http://dev.w3.org/html5/markup/i.html

Now I realise the icons have all been done as part of a font, so it's probably churlish of me to suggest, but - wouldn't these be better served as images, in image tags, such that appropriate caching methods can be employed on them? Some mobile browsers can really choke on fonts.

**Comment by mmiszy** [comment]
Bootstrap now suggests to use `<span>` instead of `<i>` (finally!) http://getbootstrap.com/components/#glyphicons
This should be changed in font-awesome documentation as well. `<i>` element semantic is well defined and it's not meant for icons.

**Comment by tagliala** [comment]
> This should be changed in font-awesome documentation as well. <i> element semantic is well defined and it's not meant for icons.

I agree with this and I'm personally using span for my projects.

I agree that docs should have best practices, but Dave wants to keep the `<i>` tag.

This is also covered in the basic example

Ref #2451

![image](https://cloud.githubusercontent.com/assets/556268/15273268/48e90dda-1a93-11e6-83a1-8d79fb567ccf.png)

**Comment by jonkri** [comment]
`<i class="fas fa-bars"></i>` works for me, while `<span class="fas fa-bars"></span>` doesn't, using https://use.fontawesome.com/releases/v5.3.1/css/all.css. Has the support for `span` been removed? Thanks!

**Comment by tagliala** [comment]
@jonkri that is not the case, please check your css and html markup.

https://jsfiddle.net/tagliala/j3gakye6/2/

If you think there is an issue with font awesome, please open a new issue following our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md) and provide a reproducible test case

**Comment by jonkri** [comment]
Thanks, @tagliala!

I found that the problem occurred due to me combining Font Awesome with a certain Bulma component:

https://github.com/jgthms/bulma/issues/2099

**Comment by crislin2046** [comment]
HTML is a "language". Use it however you like. Just like people can use English words however they like. If they can't be understood because of their word choices, you can't force them to speak in a way you understand or like. It's their freedom to choose how they speak. Maybe they get some benefits from speaking that way, even if to you it seems like a detriment.

This is even more true with browsers because the browser has very loose restrictions on what tags can go where, relative to the suggested semantic constraints. So if people loosen up the semantics from the standard, that's actually a good thing because overall, the process of exploring the semantic terrain, and finding uses is one way these things evolve by actual usage. Spirit of the web, I think, is the tug of war between standards and explorers.

If you try to constrain others on their meanings or definitions because it's not "standard" or you personally dislike it, that's incorrect, because it misses the other aspect of the web beside standardization, which is exploration. Both are necessary for healthy growth of a dynamic system. 

This is true for language as well, which continuously evolves. 

The W3C/WHATWG even reminds authors / implementors of this with their terminology. There's a reason they call it a "living standard." Don't get too attached to the current snapshot at the expensive of exploration as well.
