### ISSUE TITLE
Icon request: Outline versions of carets

### ISSUE THREAD

**Issue by TheColorRed** [FortAwesome/Font-Awesome#8037]
For the Left/Right/Up/Down caret's, It would be nice to have a caret that is just the outline without the filler. Here is an example of a right caret (sorry for the size):

![caret](https://cloud.githubusercontent.com/assets/1571806/11460090/6fcd495a-96ab-11e5-90b8-7a993209deb2.png)

**Comment by jaydmiller** [comment]
+1

**Comment by MrZach** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/search?q=caret&o=r&s=regular)
