### ISSUE TITLE
Icon Request: fa-bars-o

### ISSUE THREAD

**Issue by pjlasl** [FortAwesome/Font-Awesome#8053]
It would be nice to have the inverse of this icon if you want to use it on background colors other than white.

**Comment by tagliala** [comment]
The request is fine but I think I didn't get your use case:

> It would be nice to have the inverse of this icon if you want to use it on background colors other than white.

http://jsfiddle.net/tagliala/m26owobt/

do you mean something else with background color?

**Comment by pjlasl** [comment]
I was going to use this icon on a dark blue background. Because the lines
are black, it is hard to see the icon on that dark background

**Comment by tagliala** [comment]
@pjlasl as you can see in my fiddle, you can change the color via css, icon fonts are like text

**Comment by pjlasl** [comment]
@tagliala sorry for the late reply. I looked at your example and thank you!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
