### ISSUE TITLE
Icon Request: fa-mouse-circle

### ISSUE THREAD

**Issue by duyson19802003** [FortAwesome/Font-Awesome#8114]
I want have icon about online different with others exist icons. Please see attach file for more detail:
![mouseonline](https://cloud.githubusercontent.com/assets/6958598/11650684/b4b05792-9dbd-11e5-93d8-e2c3e0ea2a72.png)

At here, I proposal 2 options: + mouse and the circle among can be change color.
                                               + mouse fix color but the circle among can be change color.

**Comment by tagliala** [comment]
How can a mouse in a circle represent "online"?

**Comment by duyson19802003** [comment]
It only need one circle among one mouse. Status active or deactive depent on color which decided by developer. No need special for status "online", it using for all status.

**Comment by ryankane** [comment]
@duyson19802003 Maybe a mouse can be added and stacked with a circle?

# fa-mouse

![mouse](https://cloud.githubusercontent.com/assets/1094151/11665558/0b97cc1e-9db6-11e5-9db4-3783cfc3563a.png)

**Comment by duyson19802003** [comment]
OK, I will try it. Thanks!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome! [Take a look at it here.](https://fontawesome.com/icons/computer-mouse?f=classic&s=solid)
