### ISSUE TITLE
Icon Request: fa-message-settings fa-invite-person

### ISSUE THREAD

**Issue by achtet** [FortAwesome/Font-Awesome#8183]
Hello
I would like to request new icon please and I have attached sample icon. If someone can add it in there that would be very grateful and appreciated. 
![invitation_icon_3](https://cloud.githubusercontent.com/assets/16364748/11914877/f914ff30-a684-11e5-9183-b52ee8a215b6.png)
![message_setting_icon](https://cloud.githubusercontent.com/assets/16364748/11914878/f9156394-a684-11e5-8e0e-4df6f0934485.png)

Thank you.

**Comment by caduvieira** [comment]
Refers to #1181

**Comment by tagliala** [comment]
This request should be split with proper titles. Each request refers to #1181

invite-person: user-email
message settings: message-cog

You can edit this one

**Comment by nyon** [comment]
I added the first icon to nyon/fontawesome-actions@d142fa3a38e07d0b95977e9ef5e86a495e3a5559

    fa-user-envelope

**Comment by tagliala** [comment]
@nyon thanks!

**Comment by achtet** [comment]
Thanks @nyon much appreciated.

**Comment by publicocean0** [comment]
for my option the icon above is not a invite , it seams a message to a user ... 
for a invite it is more simbolic give a hand before shaking hands

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
