### ISSUE TITLE
Wordpress Multisite - Subsites call older versions of Font Awesome from different sources 

### ISSUE THREAD

**Issue by rpetitto** [FortAwesome/Font-Awesome#8209]
Our main site (www.district96.org) calls correctly from the theme file.  Subsites (eg. www.district96.org/ames) calls from different sources (maxcdn, netdns, etc.).  Changing the header doesn't resolve.  See menus at top of each site to see missing icons.

**Comment by tagliala** [comment]
This issue is not related to Font Awesome, you should consider stackoverflow for support requests

Please also check your development console, there are issues in loading font
```
GET http://www.district96.org/wp-content/themes/alora/fonts/fonts/fontawesome-webfont.woff2?v=4.5.0 
(index):3946 GET http://www.district96.org/wp-content/themes/alora/fonts/fonts/fontawesome-webfont.woff?v=4.5.0 
(index):1 GET http://www.district96.org/wp-content/themes/alora/fonts/fonts/fontawesome-webfont.ttf?v=4.5.0 
```

please keep in mind that themes/plugins could load their own version of fontawesome: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting so you may need extra effort to avoid that
