### ISSUE TITLE
Icon Request: fa-pegion

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#8259]
please include pegion icon like i included in files. one pegion icon is like in this file and other one is by holding a message or later in his mouth. I will need that so i will be thankful for that  

![draw-pigeon-bird-15](https://cloud.githubusercontent.com/assets/6570062/12073920/22a12bec-b15e-11e5-85a2-bd5deb705ae6.jpg)

**Comment by codynguyen1116** [comment]
This should be renamed to "Icon request: fa-pigeon", but +1

**Comment by Tails** [comment]
+1 (for playful contact form icon)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
