### ISSUE TITLE
Icon Request: fa-ellipses-corner

### ISSUE THREAD

**Issue by jdu** [FortAwesome/Font-Awesome#8271]
Would be good to add a corner ellipses icon which would basically make it possible to use icons to build nested trees. I did a quick mock of what I'm talking about. I have to build a lot of nested and fairly complex trees in some of my apps which it's alright without the lines for a simple tree, but when you have multiple icons per line in the tree denoting things like status, type, etc... and your trees get large its nice to have the reference line like in the mock below. 

It might take a bit of effort figuring out the spacing, etc... though, I realise in my mock the sizes aren't realistic and there's the potential for there to be gap between the bottom of the corner icon and the item below it, but submitting anyway as someone more design savvy than I may have an idea how to overcome that.

![fa-ellipses-corner](https://cloud.githubusercontent.com/assets/120225/12115807/f5aa179c-b3ac-11e5-8f82-68c4482d7fca.png)

**Comment by wwilliams** [comment]
:+1:

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
