### ISSUE TITLE
Icon Request: icon-non-gmo for Non-GMO icon

### ISSUE THREAD

**Issue by webscot** [FortAwesome/Font-Awesome#8291]
Icon Request: icon-non-gmo for Non-GMO icon

Non-GMO Project Verified seal - Useful association icon for web use.

![non_gmo](https://cloud.githubusercontent.com/assets/16613531/12204737/46a824de-b5f3-11e5-8bf1-f4612ae42d24.png)

http://www.nongmoproject.org/learn-more/understanding-our-seal/

**Comment by tagliala** [comment]
the above example is too complex

**Comment by webscot** [comment]
![non-gmo-slash](https://cloud.githubusercontent.com/assets/16613531/12207050/cc1d096e-b601-11e5-86ae-4b285e5b2110.png)

**Comment by webscot** [comment]
@tagliala 

What about this since it's single color?

![non-gmo-single-color](https://cloud.githubusercontent.com/assets/16613531/12208187/7e7db85a-b608-11e5-9cdf-00646da8b50f.png)

**Comment by dotnetchris** [comment]
:-1:

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
