### ISSUE TITLE
Icon Request: fa-gear-clipboard

### ISSUE THREAD

**Issue by susisumesh** [FortAwesome/Font-Awesome#8318]
need an icon with gear & clipboard 

Case : 
"fa-gear" can be used for settings / tools
"fa-gears"  can be used for settings list / tools list
" fa-gear-copy' - new icon needed to show copy/clone settings

if i want to show copy tools or copy settings , a combined version of gear & clipboard will be useful.
something exactly like the clone icon. 

New icon with gear on background and clone page on front will symbolize copy settings to the end user.

**Comment by tagliala** [comment]
refers to #1181

**Comment by dnavarrojr** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
