### ISSUE TITLE
icon request: quote / quotation / offer

### ISSUE THREAD

**Issue by hpvd** [FortAwesome/Font-Awesome#8329]
Please add an icon for quote / quotation / offer

to complement icon-requests of
- invoice https://github.com/FortAwesome/Font-Awesome/issues/477
- delivery https://github.com/FortAwesome/Font-Awesome/issues/6041

(if needed please vote for them too)

**Comment by tagliala** [comment]
any example?

**Comment by hpvd** [comment]
not that easy...
maybe at least 3 ways are possible:
1. having a price tag as element
![2016-01-13_15h30_36](https://cloud.githubusercontent.com/assets/5681880/12296995/457ef508-ba0b-11e5-8651-348ce14de8b6.png)
2. having elements to document/select options
![2016-01-13_15h29_57](https://cloud.githubusercontent.com/assets/5681880/12297028/6ecc1756-ba0b-11e5-9a55-c26572f27c37.png)
![2016-01-13_15h29_12](https://cloud.githubusercontent.com/assets/5681880/12297031/71abf9f0-ba0b-11e5-933a-c0966ff0937a.png)
3. having elements for acceptance
![2016-01-13_15h28_55](https://cloud.githubusercontent.com/assets/5681880/12297099/c89bd460-ba0b-11e5-8032-20ec340dfbd1.png)
![2016-01-13_15h28_55](https://cloud.githubusercontent.com/assets/5681880/12297100/caca1314-ba0b-11e5-9808-92d48df6cfa3.png)

**Comment by miradnan** [comment]
+1

**Comment by cherrador** [comment]
What do you think something like this?
![quote](https://cloud.githubusercontent.com/assets/12229855/12542388/a1ad0188-c2f0-11e5-95a3-f742700b8c8e.png)
This one was created using icon stack.

**Comment by hpvd** [comment]
>What do you think something like this?
needs to fit to and differ from invoice icon see https://github.com/FortAwesome/Font-Awesome/issues/477

**Comment by cherrador** [comment]
Yeah that is the problem with icons. How to have a small picture describing an idea the best it can. I suggested that one, because is a document that quotes money. Invoice is a document asking money, maybe a document with a hand and dollar sign will fit better. Receipt is better universally understand as the cut roll paper icon like suggested on #477. However is you want and icon with a document with a checklist items then with stacks you could create this one:
![items](https://cloud.githubusercontent.com/assets/12229855/12687717/92dc7276-c69f-11e5-973f-9737fc0f65a1.png)

If you need reference how to create these icons (as I did) take as reference this:
https://jsfiddle.net/cherrador/jomgLb2h/

**Comment by sensibleworld** [comment]
We have a few options for this now: https://fontawesome.com/icons?d=gallery&q=invoice
