### ISSUE TITLE
Icon request: fa-circle-notch-alt (circle-notch with more gap)

### ISSUE THREAD

**Issue by cherrador** [FortAwesome/Font-Awesome#8403]
I have extended the CSS stacks at the point that I am able to create complex stacks. However some icons have align errors and some are inconsistent.

fa-circle-o-notch, the notch gap is too narrow to really insert something properly. fa-power-off somehow works but the line is misaligned to be useful. The gap should be as what the fa-power-off has (or base it on fa-power-off without the line). 

This jsfiddle shows the problem trying to create a solution for request #7389 that will require a better notch.

https://jsfiddle.net/cherrador/jomgLb2h/04/

With better notch icon will be very useful to create other nice quality stacks cases. Like #8121

**Comment by tagliala** [comment]
Adding this to 5.0.0 milestone, so Dave will eventually take a look

Ref: #9753

**Comment by cherrador** [comment]
Awesome, these are great news.

**Comment by tagliala** [comment]
The notch icon is not changed in FA5 and this makes more sense as a new request

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
