### ISSUE TITLE
Icon Request: fa-diff

### ISSUE THREAD

**Issue by psimonov** [FortAwesome/Font-Awesome#8408]
I want to use new icon (different, diff checker) in web development blog.

**Comment by tagliala** [comment]
could you please provide an example?

**Comment by psimonov** [comment]
For example, diff icon in PHPStrom:

![diff](https://cloud.githubusercontent.com/assets/14864408/12576857/b504704e-c427-11e5-8377-8bf0be533168.png)

**Comment by spoike** [comment]
Alternative for this would be the plus/minus icon #6885

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/plus-minus?f=classic&s=solid)
