### ISSUE TITLE
Icon Request: fa-e54B y fa-e54N

### ISSUE THREAD

**Issue by isc91** [FortAwesome/Font-Awesome#8417]
New icon!
![log negro](https://cloud.githubusercontent.com/assets/16740205/12567643/8b3f2ae2-c37d-11e5-9d3d-e42f620d814b.png)
![f](https://cloud.githubusercontent.com/assets/16740205/12567647/93866148-c37d-11e5-9aac-5de26c6d3eb4.png)

**Comment by tagliala** [comment]
could you please provide more info about this brand?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
