### ISSUE TITLE
Icon Request: icon-lock-question

### ISSUE THREAD

**Issue by Naimikan** [FortAwesome/Font-Awesome#8424]
Thanks for this awsome fonts!

It might be a good idea to have an icon to indicate forgotten passwords. Something like this:
![forgot_pass](https://cloud.githubusercontent.com/assets/6245958/12612301/054b8072-c4f2-11e5-9412-9c21e0c3d5c0.png)
![forgot_password1](https://cloud.githubusercontent.com/assets/6245958/12612302/0556d6ac-c4f2-11e5-9cd0-025eb0a47907.png)

Thanks!

**Comment by tagliala** [comment]
may refer to #1181

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
