### ISSUE TITLE
Icon Request: bars-v

### ISSUE THREAD

**Issue by juliabell** [FortAwesome/Font-Awesome#8529]
It would be great to have a version of bars that was rotated by 90 degrees. So 3 vertical lines.

Thanks!

**Comment by tagliala** [comment]
Your request is legit but please consider using `fa-rotate-90`

https://jsfiddle.net/tagliala/m26owobt/4/

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
