### ISSUE TITLE
Icon Request: fa-manipulated

### ISSUE THREAD

**Issue by sebilasse** [FortAwesome/Font-Awesome#8626]
Hey there,
I know – I could easily do a custom build for my own projects but this one is important to me and hopefully to you ;)

The `[M]` mark for manipulated content in a journalistic context:

Freelens e. V. –basically an european movement and union of freelanced photojournalists– proposed to mark manipulated images with an `[M]`. In germany many newspapers and magazines do so and it would look better as a FontAwesome icon...

**Comment by tagliala** [comment]
could you please add a single color example of this icon? I'm not able to find it

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
