### ISSUE TITLE
Icons to be added: fa-integer and fa-decimal

### ISSUE THREAD

**Issue by rbatllet** [FortAwesome/Font-Awesome#8627]
Please, add these icons, one for the integer representation and another for the decimal representation:

![screen shot 2016-02-22 at 16 09 11](https://cloud.githubusercontent.com/assets/3993987/13222113/b5878be8-d97e-11e5-8624-cebbac3a0eb7.png)

The file formats eot, svg, ttf, woff are in the zip:
[icon.zip](https://github.com/FortAwesome/Font-Awesome/files/140811/icon.zip)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
