### ISSUE TITLE
Icon request: fa-passport-photo

### ISSUE THREAD

**Issue by atul7398** [FortAwesome/Font-Awesome#8633]
![passport](https://cloud.githubusercontent.com/assets/16884805/13253210/f7829b90-da60-11e5-938c-801b77258a7a.png)

**Comment by tagliala** [comment]
Closely related to #3695

**Comment by gido** [comment]
What about including great work by @stuartpb https://github.com/stuartpb/passport-icon ?

Not sure if the LICENSE match.

**Comment by stuartpb** [comment]
I'd be happy to have my passport icon included as part of Font Awesome (and would more than willing to oblige if it would need to be relicensed accordingly), but with a few points:

- The hexagon and "eagle" is an Americocentric design, with the hexagon partially being present as a reference to Node.js (on which the Passport library this was originally drawn for ran). For use as a standalone "password" icon, I've been meaning to replace that part of the icon with a shield or crest, to be more generally applicable internationally (most country's passports feature crests on the cover), and to distinguish from the original Passport.js use of the image. I'd want to finish that first.
- That image is an icon for *passports in general*, and as such would be more applicable to #3695 than this issue. This issue is for an icon that I would describe, for applicability in broader contexts, as ["headshot"](https://en.wikipedia.org/wiki/Head_shot).
- While the icon is visually *distinct* at small resolutions, I'm not sure it's *recognizable* at the angle I drew it at, and it's certainly not as easily hintable to the pixel grid. If including it in an icon font like this, it might make more sense to rotate it (though, when originally drawing it, I ran into a lot of trouble trying to make it adequately fill a square character space when aligned straight - not sure if that's really a priority, though).

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/face-viewfinder?f=classic&s=solid)
