### ISSUE TITLE
Icon Request: icon-function-linear and icon-function-gaussian

### ISSUE THREAD

**Issue by SteveJordanKW** [FortAwesome/Font-Awesome#8641]
We've been using Font-Awesome for quite some time within our OpenSource scientific tools. While building web applications for scientific simulation and visualization (ParaViewWeb, ArcticViewer, HPCCloud...) we sometime run short in type of icons that could match our needs.

Hence today, we thought we should try to contribute those we commonly use within our application. 

These icons for 
![function-linear](https://cloud.githubusercontent.com/assets/1433903/13268719/1023b7ba-da52-11e5-8584-15643791785d.png)
scientific applications, different types of functions are used to describe data mapping (opacity, time dependent...)
![function-gaussian](https://cloud.githubusercontent.com/assets/1433903/13268729/2559f950-da52-11e5-87f2-6c1bc8c05200.png)

**Comment by RoumedG** [comment]
+1

**Comment by jourdain** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
