### ISSUE TITLE
Icon Request: icon-parallel-coordinates

### ISSUE THREAD

**Issue by SteveJordanKW** [FortAwesome/Font-Awesome#8642]
We've been using Font-Awesome for quite some time within our OpenSource scientific tools. While building web applications for scientific simulation and visualization (ParaViewWeb, ArcticViewer, HPCCloud...) we sometime run short in type of icons that could match our needs.

Hence today, we thought we should try to contribute those we commonly use within our application. 

This icon represents one of many visualization type we are doing
![parallel-coordinates](https://cloud.githubusercontent.com/assets/1433903/13268818/93438288-da52-11e5-83c1-851c05cff4c0.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
