### ISSUE TITLE
Icon request: fa-tree-tri-expanded & fa-tree-tri-collapsed

### ISSUE THREAD

**Issue by jezbo7** [FortAwesome/Font-Awesome#8657]
Many modern UIs use the triangle symbol to denote collapsed/expanded tree nodes, with collapsed pointing east and expanded pointing south-east (rather than the traditional +/- icons). To my surprise font-awesome didn't have these. Would be useful to have both filled and unfilled varieties.

**Comment by tagliala** [comment]
could you please post examples?

**Comment by jezbo7** [comment]
![tree](https://cloud.githubusercontent.com/assets/7715241/13350940/2c9dc388-dc7b-11e5-9ddf-1e7dc8acbd69.PNG)

**Comment by klambacher** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

(We do have this existing icon: https://fontawesome.com/icons/folder-tree?f=classic&s=solid)
