### ISSUE TITLE
Icon request: icon-money-empty

### ISSUE THREAD

**Issue by ewillebrands** [FortAwesome/Font-Awesome#8678]
So you can choose any character to put on any icon. This way you could create banknotes with different amounts or currencies (like requested in #4418), or coins /moneybags for different currencies ( #1414 ). This obviously requires also an empty banknote, coin and moneybag icon.
And much more combinations are possible.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
