### ISSUE TITLE
Icon Request: fa-star-one-third, fa-star-two-thirds

### ISSUE THREAD

**Issue by ckubs** [FortAwesome/Font-Awesome#8683]
Hello. I find Font Awesome to be pretty complete but I guess something is missing.
Right now the star rating options are: full star, half star, empty star, empty star half filled. 

The problem is though, if someone wants to use this icons for reviews, it has to display 3.8 as 3 stars and a half star, instead of 3 stars and 2 thirds of a star, for example.

One third of a star( empty star one third filled respectivelly) and 2 thirds of a star would be nice additions to Font Awesome Library.

**Comment by Crissov** [comment]
Since [`fa-star`](https://fortawesome.github.io/Font-Awesome/icon/star) etc. are five-pointed stars, why not use filled jags?

![Moon phase rating with five-jagged star](http://i.stack.imgur.com/KDBIb.jpg)

There’s also a point to be made for stars other than pentagram-based, some exist in Unicode: •▴✦★✶✷. And what about a snowflake-like star as seen on fridges and freezers?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
