### ISSUE TITLE
Icon Request: fa-long-range

### ISSUE THREAD

**Issue by Cenute** [FortAwesome/Font-Awesome#8713]
For inspiration:

![02-lr-pozitiv](https://cloud.githubusercontent.com/assets/10871569/13583097/ec27ae4e-e4af-11e5-835a-4f892c415d13.PNG)

**Comment by tagliala** [comment]
is this a brand?

Could you please clarify your request?

Please take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by Cenute** [comment]
It would have been icons for fan pages, regarding the sport of hunting and
shooting sports rifle.

2016-03-08 11:35 GMT+01:00 Geremia Taglialatela <notifications@github.com>:

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
