### ISSUE TITLE
Icon Request: fa-square2x2

### ISSUE THREAD

**Issue by dcbasso** [FortAwesome/Font-Awesome#8725]
If possible It will be cool if a tipo of 4 squares no separated (2x2) inside the squares in white and the line with black color. 
I have a sample here: [http://www.flaticon.com/free-icon/four-squares_16147#term=square&page=23&position=11](url)

If possible more squares, like 3x3, 4x4 will be nice too.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/border-all?f=classic&s=solid)
