### ISSUE TITLE
Icon request: icon-projectmanager

### ISSUE THREAD

**Issue by INWB** [FortAwesome/Font-Awesome#8768]
Hello

New here so apologies if I get anything wrong. I'm building a website to advertise my new business (just me not a mega corp) and I would be really grateful if someone would create an icon I can use on the website for "Project Management" 

I had this sort of thing in mind:

![icon_projectmanagement](https://cloud.githubusercontent.com/assets/17889700/13829904/6b51d678-ebc1-11e5-9c85-0db81efb326a.jpg)

Thanks very much in advance

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/clipboard-check?f=classic&s=solid)
