### ISSUE TITLE
<i class="fa fa-shopping-basket"></i> not working

### ISSUE THREAD

**Issue by rajnadan** [FortAwesome/Font-Awesome#8796]
shopping-basket has height=0 and width=0.
It's not displaying.
If I switch -basket to -cart, the cart is displayed

**Comment by tagliala** [comment]
maybe you are using an outdated version of FA. `shopping basket` was introduced in 4.5.0 so please make sure you are up to date

Check our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

**Comment by kn00tcn** [comment]
if anyone else runs into an unexpected failure & comes to this thread from google, here was my situation

at first i thought it was the linux OS that happened to have livestreamer package installed which included fontawesome... but the distro said it was on 4.7, no matter, i removed it in case the browser was loading the local file

i'm working on a WP site, eventually thought to view the page source... turns out a(n updated) plugin was enqueueing an old 4.4 version of fontawesome under the namespace 'font-awesome', which happened to be the same namespace i used in my theme... as soon as i renamed my enqueue name, the path to the css file was now mine instead of the plugin's... the weird thing is this plugin is only supposed to be for the admin area & renaming mine didnt result in a duplicate line in the page source

**Comment by tagliala** [comment]
@kn00tcn thanks for sharing this.

This case is covered in our troubleshooting guide https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up at point 5

**Comment by kn00tcn** [comment]
@tagliala yes, but i meant my case was really unexpected since all my code was correct & the plugin doesnt have anything to do with the public facing theme, nor does it load fontawesome, it only happened to override the name i gave it (specific to dynamically loading things in WP, wouldnt have happened if i manually wrote the url)
