### ISSUE TITLE
Icon Request: fa-ellipsis-h-circle-o

### ISSUE THREAD

**Issue by cjr--** [FortAwesome/Font-Awesome#8799]
This would give a little more visual weight to fa-ellipsis-h which i seem to be using a lot recently.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/ellipsis-stroke?f=classic&s=solid)
