### ISSUE TITLE
Icon Request: fa-boleto

### ISSUE THREAD

**Issue by recs182** [FortAwesome/Font-Awesome#8805]
Boleto is the most used method of payment in Brazil. I looked for a request but didn't find it.

check the icon bellow:
http://www.brandsoftheworld.com/logo/boleto-0

**Comment by thiagodesacosta** [comment]
You can try fa-barcode

**Comment by nofxx** [comment]
Yeah... barcode is nice.
Stacking is kinda difficult to accomplish with some cases, but you might give it a try:
That'll be `fa-barcode` over `fa-file-o`

**Comment by recs182** [comment]
Ok, thanks for the advice. We prefer to use icons instead of images, so we'll try it.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
