### ISSUE TITLE
Category of Fonts - Nature/Weather/Element Related

### ISSUE THREAD

**Issue by pljspahn** [FortAwesome/Font-Awesome#8862]
I'm not sure if I'm going about this the right way, but if this seems to be a good idea and is well-liked, I would take the time to add icon requests for each specific icon. As it is, there's a category of icons I would love to see relating to nature, the elements, weather, science, etc.

**I'm not sure if what I want is too narrow - is there generally interest in these?**

My site is for a retail/wholesale tree nursery/garden center. There are a lot of ideas that I would like to design as icon, but I feel like FA is just too limited. Some ideas would be:

Several generic weather icons - Snow, Rain, Hail, a few varying degrees of sun/clouds, tornado, hurricane, flood, wind, humid, dry, hot, cold.

Element / Environment type icons - Rocks, Swamp, Desert, Mountains, River, Canyon, Plains, several plant types (trees, evergreens, grasses, shrubs, vines) 

Science - microscope, goggles, DNA, a few common basic molecules/elements (salt, water, CO2, common metals, etc), 

**Again, is this simply too broad to bother considering? I imagine there are plenty of Agriculture businesses out there like ours that would be happy to get some icon love**

**Comment by tagliala** [comment]
Hi,

Font Awesome is supposed to work for a generic web application.

A comprehensive set of icons dealing with Nature/Weather/Element is a request that is hard to implement for Dave and to manage for me.

You can +1 individual requests like #1195 , #4109 , #1300...

We had to fix our contributing guidelines in order to deal with this:
https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

The best thing we can do in this case is to use fontawesome alongside another set specific to our needs

E.g.: I need to implement a forecast application, so I could opt for Font Awesome + Meteocons

Or I can customize fontawesome: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Hope it helps

Closing here
