### ISSUE TITLE
add new dataflow, workflow icons in font-awesome new version.

### ISSUE THREAD

**Issue by MUBUSHER** [FortAwesome/Font-Awesome#8863]
Hi Guys,

Thanks for doing wonderful job,

this is not just FontAwesome icons this is really awesome icons, i start using since 2 years, it helps me many places, and the good thing is they are improving day by day as per user experience. i feel its still need more icons as i was looking today but i couldn't find data flow, workflow icons.
please add some more workflow or data flow icons in font-awesome, i think its really required when you are building some workflow application, or drawing the software application model.

Thanks & Regards,
Muhammad Mubusher Aslam

**Comment by tagliala** [comment]
Could you please post an example (or examples) of the icons you need?

**Comment by dflock** [comment]
I also need icons in this space. These icons would a good start:

- Extract/Read
- Transform
- Load/Save
- Workflow/Flowchart

There's a more comprehensive list here: #9539:

- Source
- Sink
- Tap
- Tail
- Flow
- Filter
- Scrub
- Extract
- Transform
- Load
- Dump
- DirtyData
- Aggregate
- Split
- Scrape
- Crawl

#9539 was closed because it was requesting an icon pack, but I think this is allowed now?

**Comment by tagliala** [comment]
Hi,

as per [icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md), we do not accept requests with a set of icons because they are hard to manage

Closing here
