### ISSUE TITLE
Icons Request: fa-mobile-rotate-portrait, fa-mobile-rotate-landscape

### ISSUE THREAD

**Issue by renatodarrigo** [FortAwesome/Font-Awesome#8869]
Hello!

I would like an icon to illustrate when a user should rotate the device to portrait and landscape.

Something like this:

![to-landscape](https://cloud.githubusercontent.com/assets/2336153/14185350/cb34ea00-f74f-11e5-8991-9cec0dfcbb20.png)

![to-portrait](https://cloud.githubusercontent.com/assets/2336153/14185360/d1fa3d54-f74f-11e5-88c7-40b3ca35655f.png)

Thanks in advance!

**Comment by leecollings** [comment]
Couldn't you do something very similar yourself by using two instance of `fa fa-mobile` and one of the arrows?

**Comment by renatodarrigo** [comment]
That's exactly what I have done. ;)

Em Ter, 5 de abr de 2016 12:34, leecollings <notifications@github.com>
escreveu:

**Comment by maorkavod** [comment]
fa-rotate-180

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
