### ISSUE TITLE
Icon request: fa-year, fa-decade

### ISSUE THREAD

**Issue by jbnv** [FortAwesome/Font-Awesome#8880]
Supplemental request to #3609 for icons representing year and decade. For year, perhaps [fa-calendar-o](http://fortawesome.github.io/Font-Awesome/icon/calendar-o/) with a four-digit number in it. Decades would be harder to represent, but maybe also fa-calendar-o with "2010s."

**Comment by tagliala** [comment]
I'm going to close this one, please consider stacking text and icons for this purpose: http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/

**Comment by jbnv** [comment]
Not an acceptable workaround. Your stacking example requires using the larger size, which isn't practical for my application. Also, my idea of overlaying numbers was a proposal. I'm open to other proposals for how to represent these concepts.

Frankly, I'm getting the impression that you look for reasons to close and dismiss requests. Considering that you made icons for ridiculous things like paper-rock-scissors and Star Wars, while legitimate icon requests have gone unfulfilled for years, I don't give your reason any credibility.

**Comment by tagliala** [comment]
Hi,

>  I'm getting the impression that you look for reasons to close and dismiss requests.

this is far from being true.

Putting 4 or 5 digits in the calendar icon is hard: the available space is 9px wide.

Moreover, the original calendar contained `27` (ref: #303 https://dl.dropboxusercontent.com/u/87268031/calendar.png) and Dave removed it because it was confusing. In the same way, 2010, 2016, 201x or 2010s will be confusing too: you have an empty calendar if you need to put numbers in it.

If you have any other idea to represent a year feel free to provide an example and I will reopen it
