### ISSUE TITLE
Icon request: icon-hkey

### ISSUE THREAD

**Issue by VinodNIkam** [FortAwesome/Font-Awesome#8911]
![key_img](https://cloud.githubusercontent.com/assets/6291800/14343713/68dd632a-fcc0-11e5-8eba-9e839c9d2d2d.png)

please provide me font awesome  icon for this image

**Comment by tagliala** [comment]
Is this a brand? could you please provide more information?

**Comment by My1** [comment]
I think this isnt exactly a brand but just a "horizontal key", especially when searching for hkey the only thing that actually comes up is the Windows Registry.

**Comment by VinodNIkam** [comment]
No, it is not brand i want to use in my project

**Comment by diazona** [comment]
This is also similar to an icon [recommended by the ModernPGP working group](https://github.com/ModernPGP/icons) to represent PGP keys. I'm not sure how much weight that recommendation carries, but I suspect that among many people who use PGP, a horizontal key makes an association with "PGP key" that the diagonal key currently in Font Awesome doesn't, nor the gnupg lock icon suggested in #6168. So I think there's an argument to be made for including a horizontal key (if not necessarily the one suggested here) in the icon set.

It's also worth noting that [Key Bank](https://www.key.com) uses a stylized horizontal key as their brand logo. (Not that I'm suggesting adding their logo to FA)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
