### ISSUE TITLE
Icon Request: fa-child-plus

### ISSUE THREAD

**Issue by iici-vsimha** [FortAwesome/Font-Awesome#8929]
It would be great to have an add-chid icon. Will be used to indicate adding sub-items to an already existing item in a list and to differentiate from adding a sibling item to the list.

![screen shot 2016-04-09 at 10 06 35 am](https://cloud.githubusercontent.com/assets/7264229/14404117/0dcdf6a6-fe3d-11e5-91e6-4aaf10d75751.png)

**Comment by tagliala** [comment]
refers to #1181 , please take a look there

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
