### ISSUE TITLE
Icon request: icon-abbr

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#8972]
Hello Font-Awesome,

For the Text Editor Icons set, can you add an icon for abbr html tag ([abbrevation](https://developer.mozilla.org/fr/docs/Web/HTML/Element/abbr))

An example :
![abbr](https://cloud.githubusercontent.com/assets/5451956/14497183/391cf7ba-0196-11e6-89e1-d487d2842d05.png)

Thanks ^^

**Comment by PeterShaggyNoble** [comment]
http://fortawesome.github.io/Font-Awesome/icon/ellipsis-h/ might suit your needs, even if only as a stop-gap.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
