### ISSUE TITLE
Icon request: brush-slash

### ISSUE THREAD

**Issue by circleb** [FortAwesome/Font-Awesome#8985]
I'm using `brush` for a formatting button, but I need one with a slash through it for removing the formatting, like the others below.
![screen shot 2016-04-14 at 9 28 46 am](https://cloud.githubusercontent.com/assets/6741954/14531551/6bf8e396-0223-11e6-87c5-190c85717ab6.png)

**Comment by tagliala** [comment]
refers to #1181

**Comment by circleb** [comment]
There isn't a slash icon to use as an overlay, if that's how this request refers to what you just posted...
This is what I'm looking for: 
![screen shot 2016-04-14 at 9 30 38 am](https://cloud.githubusercontent.com/assets/6741954/14531719/120b1ef2-0224-11e6-8839-51bcf1b90b61.png)

**Comment by tagliala** [comment]
there is a request for slash in #3691 planned for 5.0.0 just to help out with #1181

Please notice that you cannot achieve the above example with a simple overlay. #1181 explains well

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
