### ISSUE TITLE
Icon request: fa-arrows-v-min, fa-arrows-v-max, fa-arrows-h-min, fa-arrows-h-max (4 icons)

### ISSUE THREAD

**Issue by jbnv** [FortAwesome/Font-Awesome#9005]
Icons to indicate maximum and minimum values. My proposal, with horizontal and vertical versions:

![](https://c2.staticflickr.com/2/1560/25884985254_1b088050db_m.jpg)

The range icons proposed by @larryosborn in #7322 may be sufficient.

**Comment by tagliala** [comment]
Please consider css tweaks to http://fontawesome.io/icon/arrows-h/ and http://fontawesome.io/icon/arrows-v/

https://jsfiddle.net/tagliala/72fd5vcr/1/

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
