### ISSUE TITLE
Icon request: plus-o

### ISSUE THREAD

**Issue by kurellajunior** [FortAwesome/Font-Awesome#9076]
More a matter of style having the nice plus icon (and the minus) also as outlined variant.
I like to toggle between this two, if I want to show, that already something is added/removed or not yet

**Comment by RoumedG** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
