### ISSUE TITLE
Icon Request: fa-glider or fa-sailplane

### ISSUE THREAD

**Issue by annaghi** [FortAwesome/Font-Awesome#9094]
I would love to use an icon like this one:
![glider](https://cloud.githubusercontent.com/assets/8246853/14941440/b790ee9a-0f9b-11e6-8f0d-af34e81e48b2.png)

**Comment by ipearx** [comment]
As a web developer creating software for gliding, I second this :)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
