### ISSUE TITLE
Icon Request: icon-list-plus, icon-list-minus

### ISSUE THREAD

**Issue by brimba** [FortAwesome/Font-Awesome#9104]
I'm missing a icon to add or remove someting to or from a list. 
For example a favorit item list for cusomers.
Attached some examples.
![add_remove_from_list](https://cloud.githubusercontent.com/assets/18737169/14981887/aa2ba540-1132-11e6-8a2e-868641117200.jpg)

**Comment by tagliala** [comment]
Can't you just use plus and minus in the context of a list?

Refers to #1181

**Comment by brimba** [comment]
The icon would be placed in the navigation and on the product list or product page, but not in the content of a list. It should symbolize to "add something to a list" for example a product to a wish-list or a task to a reminder list and also the list itself. Here is a example how it is used in a other ver nice shop:
https://www.dictum.com/en/

I would only need the plus symbol.

**Comment by Roumed** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
