### ISSUE TITLE
Icon Request: fa-history-dollar (billing history)

### ISSUE THREAD

**Issue by abigby** [FortAwesome/Font-Awesome#9107]
I think it would be nice to have an icon that represents billing history. 
I would like to use it inside a dashboard UI

**Comment by tagliala** [comment]
any example?

**Comment by abigby** [comment]
What formats can I upload my file in because I keep on getting an error "Something went really wrong, and we can’t process that file. "

**Comment by abigby** [comment]
[billing history.docx](https://github.com/FortAwesome/Font-Awesome/files/247143/billing.history.docx)

**Comment by tagliala** [comment]
could you please drag & drop a png or jpg in the github editor?

**Comment by abigby** [comment]
![fa-billing-history](https://cloud.githubusercontent.com/assets/2856119/14988467/f4c4abee-1121-11e6-8773-8aa9585fb7c7.png)

**Comment by abigby** [comment]
See image posted above, that is what I came up with.

**Comment by tagliala** [comment]
it should be named `fa-history-dollar`.

there is an history icon: http://fortawesome.github.io/Font-Awesome/icon/history/, it could help

I think there are very few chances of getting this icon in the core. Please take a look at #1181, you will find another project that might help you in creating the above icon . Then you might customize font awesome: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by abigby** [comment]
Ok thanks I will look into it.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
