### ISSUE TITLE
 Icon Request: fa-home-cog

### ISSUE THREAD

**Issue by lamisZ** [FortAwesome/Font-Awesome#9153]
Please add below icons as Home application. This icon would be used as home page for settings application

![icone_homeapp](https://cloud.githubusercontent.com/assets/19266435/15114945/ba157d0e-15fc-11e6-935c-12fa077f060c.png)

**Comment by tagliala** [comment]
slightly refers to #1181 .

Given the use case, I would consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
