### ISSUE TITLE
Icon Request: icon-free

### ISSUE THREAD

**Issue by mrinaljain** [FortAwesome/Font-Awesome#9221]
icon which can be used to show things which are free , like it can be used in pricing table or in a paragraph too.

![free-icon](https://cloud.githubusercontent.com/assets/7473761/15284236/ca680a20-1b6d-11e6-9ff1-2add5a8aee85.png)

**Comment by tagliala** [comment]
IIRC this is a duplicate, but I'm not able to find the original request so I'm leaving this open

**Comment by aethior** [comment]
Related to #7568.

One note: In my opinion the icons should be internationals, without words in any language. Why not use `fa-certificate` (http://fontawesome.io/icon/certificate/) with stacked text?

cc @tagliala, @davegandy

**Comment by tagliala** [comment]
I do agree.

I would avoid words, because they:
1. Are probably not international (Note: I'm not saying that numbers are international. Ref: #4418);
2. Don't fit the 14px icon size (https://jsfiddle.net/tagliala/4Lcpvhoo/4/);
3. Don't match webapp's main font.

As a cause of the above points, I would go for custom css

**Comment by JeanCollas** [comment]
For a "Free" icon, I would have put a $ or € crossed (large line)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
