### ISSUE TITLE
Icon Request: fa-icon-snow-groomer (dameuse)

### ISSUE THREAD

**Issue by mathieusayag** [FortAwesome/Font-Awesome#9259]
Hi,

I'd like a 2 new icons, a snow groomer and a snow mobile.

Here are 2 link :
http://www.cgx-mountain.com/GMAOWeb/images/dameuse.png
http://www.cgx-mountain.com/GMAOWeb/images/motoneige.png

Thank You for your help

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome! [Take a look at it here.](https://fontawesome.com/icons/snowplow?f=classic&s=solid)
