### ISSUE TITLE
Icon Request: fa-hodor

### ISSUE THREAD

**Issue by Jeowulf** [FortAwesome/Font-Awesome#9275]
Use cases:

A user wants to place a hold on the page that must be unheld before proceeding to the new page.
A provider wishes to put a block on a user action that must be intentionally unheld before a user may proceed.

A user wishes to say something through an icon (akin to 'like'-ing or favoriting) without committing to an emotion that differs from the mood of what is already in play.
![hodor](https://cloud.githubusercontent.com/assets/11777142/15555965/4be7d5a8-2299-11e6-8b30-f267b7c1942d.jpg)

**Comment by ryankane** [comment]
Here is a raster image of a rough vector I made.

![Hodor](http://i.imgur.com/hDBphWe.png)

**Comment by AdamHess** [comment]
I think it needs more of a "Hold the Door" look

**Comment by nickleach** [comment]
+ 1

**Comment by FHappy** [comment]
+1, in light of recent use cases this would have been crucial to my current project.

**Comment by svpanchal** [comment]
+1

**Comment by KristenLeach** [comment]
Hey; any updates on this? lmk ¯\_(ツ)_/¯

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
