### ISSUE TITLE
How can I submit a new icon to Font Awesome

### ISSUE THREAD

**Issue by SubhadipJot** [FortAwesome/Font-Awesome#9286]

**Comment by tagliala** [comment]
Hi,

unofortunately you cannot submit icons to font awesome because your PR will not be merged.

Ref: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#pull-requests

Please use a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Hope it helps, closing here
