### ISSUE TITLE
Icon request: clear-format

### ISSUE THREAD

**Issue by GabiAxel** [FortAwesome/Font-Awesome#9288]
For text editor. I know there is an "eraser" icon, but something like Tx may be more standard for this case.
![tx](https://cloud.githubusercontent.com/assets/968212/15621700/7248143c-246b-11e6-8bc4-c7e03c7acb93.png)

**Comment by refactorized** [comment]
I would like to see this too - and would happily make an attempt at a PR

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)

We also have this icon: https://fontawesome.com/icons/text-slash?f=classic&s=solid
