### ISSUE TITLE
Icon Request: Swooping Directional Arrows

### ISSUE THREAD

**Issue by zachkrall** [FortAwesome/Font-Awesome#9306]
Examples: ⤴⤵⤶⤷⤹

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/search?q=arrow-turn&o=r&s=solid&f=classic)
