### ISSUE TITLE
Errors in YAML file

### ISSUE THREAD

**Issue by aruben-c** [FortAwesome/Font-Awesome#9331]
Hi,
I notice some errors in the YAML file at:
https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/src/icons.yml

Instagram:
created since 3.2, not 4.6

Wheelchair:
accessible (not "accessibile")

Map Outline:
Outlined (not "Outline")

Paper Plane:
The filter tag is empty

area-chart / pie-chart / line-chart:
Ok, but categories are declared before filter

As of some icons are created in version 4.6.2 and 4.6.3, it's better to say:
created: 4.62
created: 4.63
instead of 4.6

Thanks for your iconic font FontAwesome,
ARuben

**Comment by tagliala** [comment]
> Instagram:
created since 3.2, not 4.6

The new instagram icon was implemented in 4.6.3, so Dave also bumped the version number in order to better reflect this change

> Wheelchair:
accessible (not "accessibile")

Removed both `accessibility` and `accessibile` filters (they are not present in other accessibility icons)

> Map Outline:
Outlined (not "Outline")

Fixed

> Paper Plane:
The filter tag is empty

Removed

> area-chart / pie-chart / line-chart:
Ok, but categories are declared before filter

Properties rearranged

> As of some icons are created in version 4.6.2 and 4.6.3, it's better to say:
created: 4.62
created: 4.63
instead of 4.6

I do agree. We are trying to use SemVer at the best we can. We are trying to not introduce new icons in patch level releases. We need that information to group new icons in the docs. Feel free to submit a PR to address this issue

**Comment by aruben-c** [comment]
Ok, thanks.
But why do you update the Instagram icon, while, for Pied Piper, you create another?
I think the best choice is to update the icon: thus, the most recent logo is always displayed without changing the class (and perhaps, also store in another Unicode the old logo).
ARuben
