### ISSUE TITLE
Icon Request: fa-liver

### ISSUE THREAD

**Issue by Bleene** [FortAwesome/Font-Awesome#9358]
![screen shot 2016-06-07 at 10 58 04 pm](https://cloud.githubusercontent.com/assets/19799274/15858334/522904fe-2d03-11e6-9849-3adbb1d2f89a.png)
Please!

**Comment by kimberley-johnston** [comment]
+1

**Comment by jamesroscoe** [comment]
+1

**Comment by rasimavci** [comment]
do we have this icon now ? I cent see

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
