### ISSUE TITLE
Icon Request: fa-syscoin

### ISSUE THREAD

**Issue by sidhujag** [FortAwesome/Font-Awesome#9365]
syscoin is an up-and-coming crypto currency which offers the world's first decentralized marketplace running on a blockchain. We need an icon for it to deploy to our web interface/wallet.

http://syscoin.org/

**Comment by sidhujag** [comment]
changed icon request

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
