### ISSUE TITLE
Icon Request - Buy and Sell

### ISSUE THREAD

**Issue by rpatil** [FortAwesome/Font-Awesome#9374]
Icon Request - Buy and Sell
![buy](https://cloud.githubusercontent.com/assets/757309/15913437/a4159e18-2df7-11e6-924e-aac13fd3d4df.png)
![sell_it_icon](https://cloud.githubusercontent.com/assets/757309/15913438/a41be944-2df7-11e6-8f18-8a90f29c5964.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/hand-holding-circle-dollar?f=classic&s=solid)
