### ISSUE TITLE
Icon Request: fa-cork

### ISSUE THREAD

**Issue by wegastudios** [FortAwesome/Font-Awesome#9422]
![cork](https://cloud.githubusercontent.com/assets/20037981/16185134/f7d9fe2c-36c1-11e6-9991-e2215e53a085.jpg)
Hi, this icon would be helpful in a enogastronomical communities to rate wine or champagne, it woud be useful also as uncork icon or maybe cork wood.
Can you please add it?

**Comment by tagliala** [comment]
Corkscrew: #5835

**Comment by tsulhc** [comment]
I need that icon as well

fa-glass is useful for cocktails, this one is perfect for wine.

Hope to see this one as soon as possible

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
