### ISSUE TITLE
Icon Request: fa-bank-dollar

### ISSUE THREAD

**Issue by douglasdeodato** [FortAwesome/Font-Awesome#9451]
This icon does not exist but people are using this existed one  :  http://fontawesome.io/icon/university/

and the ticket for: fa-bank was closed and someone asked there:
https://github.com/FortAwesome/Font-Awesome/issues/925

but maybe we could have something like that for bank?

![bank-512](https://cloud.githubusercontent.com/assets/993318/16269442/2e02df86-388a-11e6-96ff-a4e37a8640ee.png)

Thank you.

**Comment by tagliala** [comment]
The problem with icons like that is the dollar symbol, which is not international. Then we should have "bank-euro", "bank-ruble", and so on.

Refers to: #9221, #477 and many others

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
