### ISSUE TITLE
Icon Request: fa-potato

### ISSUE THREAD

**Issue by douglasdeodato** [FortAwesome/Font-Awesome#9453]
fa-potato

![thinline28-12-128](https://cloud.githubusercontent.com/assets/993318/16270365/f6b4628a-388d-11e6-9ce3-1f123510a6ee.png)

**Comment by PaluMacil** [comment]
I'm not sure if this would be a priority for Font Awesome, but perhaps consider submitting this to Vesper Icons since they are totally compatible with FA yet are restaurant focused: https://github.com/kkvesper/vesper-icons I am not affiliated but did make a contribution. I don't know if they need this in their collection or not.

**Comment by sensibleworld** [comment]
We now have some potato options! https://fontawesome.com/v6.0/icons?q=potato
