### ISSUE TITLE
Icon Request: fa-leprechaun

### ISSUE THREAD

**Issue by paisley2** [FortAwesome/Font-Awesome#9460]
Really appreciate what you guys do, makes life so much easier, thanks!
I would love a Leprechaun icon for use on St. Patrick's Day or Irish/American related sites.
Thanks. 
![leprechaun-22](https://cloud.githubusercontent.com/assets/20108208/16300456/f1a8d32a-3937-11e6-9698-96fd8b0473e5.png)
![liftarn-laughing-leprechaun](https://cloud.githubusercontent.com/assets/20108208/16300460/f5d97ada-3937-11e6-9365-9d54466eb3f4.png)
![ae5f8c649a13084f0fc10b7542dc1f22](https://cloud.githubusercontent.com/assets/20108208/16300462/f7f3fe08-3937-11e6-94f1-b538a6f17d95.gif)

**Comment by tagliala** [comment]
Please provide a single color, 14px suitable example

**Comment by paisley2** [comment]
Sorry, not sure what you mean by "14px suitable"?
![b w leprechaun](https://cloud.githubusercontent.com/assets/20108208/16300929/67a75798-393a-11e6-8d3f-5f3fccdb2f8b.png)

**Comment by tagliala** [comment]
single color = black with transparent backgruound, no greyscale images
sorry, suitable for 14px icon size, I'm not an English native speaker

eg: car
![image](https://cloud.githubusercontent.com/assets/556268/16302398/32a716f8-394b-11e6-9901-2ec75d3e98e2.png)

**Comment by paisley2** [comment]
Hi tagliala
When I reduce the image to 20px, it's too small and the detail is lost.
![b w leprechaun](https://cloud.githubusercontent.com/assets/20108208/16311683/6011c30e-3969-11e6-99a2-cc75da2a11dc.png)

**Comment by paisley2** [comment]
![20px lep](https://cloud.githubusercontent.com/assets/20108208/16312023/c0a1e13a-396a-11e6-916d-c6b99c8f1551.png)

**Comment by tagliala** [comment]
thanks

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
