### ISSUE TITLE
Icon request: flag-eu 🇪🇺

### ISSUE THREAD

**Issue by hudZEC** [FortAwesome/Font-Awesome#9520]
In our projects we would like to use flags European flags as icons.
flag-eu
~flag-uk
flag-de
flag-it
flag-hr~
...
I think a lot of people would like to have flags icon set. I hope it is doable.
Cheers!

**Comment by tagliala** [comment]
Sorry, flags are out of scope, ref: #1336

Closing here

PS

> In our projects we would like to use flags European flags as icons.
flag-eu
**flag-uk**

:grinning:

**Comment by forcequit** [comment]
> Sorry, flags are out of scope, ref: #1336
> 
> Closing here
> 
> PS
> 
> > In our projects we would like to use flags **European** flags as icons.
> > flag-eu
> > **flag-uk**
> 
> 😀

You have <i class="fas fa-flag-usa"></i>

**Comment by tagliala** [comment]
Reopening here as individual request for

# 🇪🇺 

PS: please note that 🇮🇹 and 🇫🇷 cannot be implemented in single color

**Comment by megagustav** [comment]
Also looking for an EU flag. There's a US flag, and imo it makes sense to have flags that work in a single color (Switzerland/medical, EU, Scotland, Japan, ...), EU-alt could just be the circle of stars

**Comment by tdapper** [comment]
We were just looking for just the circle with stars on its own would be super useful and perhaps reasonably simple. Flag would have worked just as well. 

Either one would be a great addition.

**Comment by keesjand** [comment]
my 5 cents: I want tio use it in footer like
- Made in EU
- EU GDPR approved

I think the latest is the most important because the EU is leading in the privacy debate and settign the norm!

**Comment by infuzz** [comment]
I would also recall that EU is not a country but an union of 27 member states (countries), with an estimated total population of about 447 million. They highly appreciate to be not ignored... So, it could be great to let Europe to have is own icon. As this is not a country, it should not fall into fa-flag discussion...  I suggest that icon name for europe should be as simple as : fa-europe

**Comment by sulleh** [comment]
I agree with keesjand - demonstrating GDPR accreditation is a super common requirement for many sites and applications, and there is no font awesome asset that can reliably represent this.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Comment by SensorPro** [comment]
If there's a US flag it seems reasonable there would be a EU flag.

**Comment by tdapper** [comment]
@sensibleworld I have to strongly disagree with a European flag or just the circle of start being "niche". That's just plain not backed by facts and feels like a canned response that has nothing to do with the merit of this request. The European Union is a trade area with way over 400 million inhabitants. If that is a niche, I don't know what isn't.

And especially in the web context there are so many things that are somewhat EU specific compliance aspects that this would be super useful for. It is a gaping hole in the otherwise very useful collection of icons FontAwesome provides. I would really not like to roll my own, but it feels like we have to. That is somewhat disheartening.

**Comment by sensibleworld** [comment]
Hey folks, thanks so much for the feedback. In terms of the wording of the above message, it was a boilerplate response... so please don't put too much weight on the word choice. (We're currently doing a long-overdue full review of ALL open icon requests.)

There are a number of reasons a request may be denied. In this particular case, the inclusion of flags in Font Awesome is tricky. Simply put, a LOT of flags won't display well in a single color... and for those that do, choosing which to include is fraught for a number of reasons. Do we include all countries? Only countries above a certain population, etc, etc.

Put another way... we WANT to include flag icons, but are working on the right way to do so. (And a way we can do so in full color). Stay tuned.

(P.S. If this is an icon someone absolutely needs, we do have a commission process available: https://fontawesome.com/#commissions)

**Comment by tdapper** [comment]
Thanks for the answer @sensibleworld and understood about the boilerplate. Also thanks for the more elaborate answer, but I think all your points (and more) have been addressed above.

1. This has been turned into a request that is specific to the European Union and not a country flag. So I think one could argue that the whole problem about flags in general (which I can see) does not really apply here. You do have a bunch of somewhat general flags, like a checkered flag, a generic flag, and don't get me started about the US flag. ;-)
2. For the specific EU request, the point about single color does not apply. It's a circle of stars, so that is really easy.
3. I believe it would also be fine for most people requesting this if it's not a flag, but just a standalone symbol with a circle of stars (I also don't think the exact star count would matter). You folks kind of took the same out for the pirate flag, where you don't include it as a flag, but just as a pirate symbol.

There have been additional points made by my fellow commenters above. Therefore, I think there is enough of a good reason here, it is distinct enough from regular flags (especially when you just pick the stars), and should be easy to do in single color.

Thanks for pointing out the commission process and that is certainly a possibility, but having just a single font source to get all the symbols on a site from would still be valuable, which I suppose is one of the reasons for FontAwesome's popularity in the first place.

I fully understand the need to weed out requests from time to time, but It would be "awesome" (pun intended), if this particular request could stay on.

**Comment by sensibleworld** [comment]
@tdapper I hear you. I'm going to re-open the issue. We can’t promise any firm timelines right now, but this will help us keep track of it.

As for the icon commission process, any icon created as part of it will be added into the full Font Awesome set, and is a great way to skip-the-line for icon creation. As it currently stands, there are only three (3) thumbs-up on the original post.

**Comment by tdapper** [comment]
Thank you so much for considering this, @sensibleworld!

Totally understandable about the timeline. Maybe we'll find a few folks to "crowd-fund" a commission. ;-)

**Comment by sensibleworld** [comment]
After a lot of discussion with the team, we've decided to move all open individual country-flag requests to a single open issue: https://github.com/FortAwesome/Font-Awesome/issues/20288

**Comment by forcequit** [comment]
There is an EU currency icon but no Flag?  WTF.
