### ISSUE TITLE
On IE8, font disapear when refresh

### ISSUE THREAD

**Issue by FabGre** [FortAwesome/Font-Awesome#954]
EDIT : Just see that there is an other bug about display on IE (#929) but I'm not sure it's the same 'cause the tweak seems to be on the source code..

Hello,

Sorry but I have to report a bug on IE 8 (argh). The users of my application are not experimented internet guys and could still use XP/IE 8 ..

So, I saw that when I simple refresh my app, fonts disapear randomly. I checked on fontAwesome website and it's the same, with a strange behaviour on hover. When I hard refresh (CRTL+R) or clear the cache, fonts come back. I let you see my different screenshots.

![FA-bug-ie8](https://f.cloud.github.com/assets/3983509/380425/ba247956-a5c2-11e2-9f39-9e2bc9c9c60b.png)

![FA-bug-ie8-2](https://f.cloud.github.com/assets/3983509/380426/bca67846-a5c2-11e2-8feb-c94ddf2504b0.png)

![FA-bug-ie8-3](https://f.cloud.github.com/assets/3983509/380427/be2018da-a5c2-11e2-98fd-8fa915ef266b.png)

![FA-bug-ie8-4](https://f.cloud.github.com/assets/3983509/380429/bfa4b03a-a5c2-11e2-9091-9a5c00812c3b.png)

**Comment by tagliala** [comment]
Refers to https://github.com/twbs/bootstrap/issues/13863

https://github.com/twbs/bootstrap/pull/13866/files#diff-b6ea1aa54468ea01aaf88a8b32d925d7R109

Closing here

**Comment by aallou** [comment]
This solution is ok for me :

Add font (glyphicons) in your css, although the bootstrap included : 

@font-face {
	font-family: 'Glyphicons Halflings';
	src: url('......./bootstrap-3/fonts/glyphicons-halflings-regular.eot');
	src: url('......../bootstrap-3/fonts/glyphicons-halflings-regular.eot?#iefix')
		format('embedded-opentype'),
		url('....../bootstrap-3/fonts/glyphicons-halflings-regular.woff') format('woff'),
		url('....../bootstrap-3/fonts/glyphicons-halflings-regular.ttf') format('truetype'),
		url('......../bootstrap-3/fonts/glyphicons-halflings-regular.svg#glyphicons-halflingsregular')
		format('svg');
}

**Comment by rjgotten** [comment]
> This solution is ok for me

Only reason that this *seems* to work for you, is that including the font-face definition in an earlier location in your CSS in **&raquo;this one specific occasion&laquo;** only, causes the font to finish loading before IE's first crack at rendering the page.

Thus you avoid the issue with IE not repainting pseudo-elements, because they're already completely rendered as they should be *on first paint*.

However, you have absolutely zero control over all the timing conditions involved and thus **zero** guarantee that this will work correctly everywhere on all connections for everyone.
