### ISSUE TITLE
Icon Request: Automotive/Motorsport Icons

### ISSUE THREAD

**Issue by bytecodedan** [FortAwesome/Font-Awesome#956]
I'm building an automotive web app and looking for suitable icons.  While FontAwesome is "awesome" (I use it all the time, wherever I can), it would be nice to have icons such as, engine, transmission, shock, wheel, brake rotor with caliper, shift knob, steering wheel, race helmet, checkered flag, oil can, half open garage door, etc.  Also, more "tool" icons such as, screw driver, hammer, tool box, just to name a few.

I've searched the web for such things.  While I have come across some icons, only some are usable, but still not enough.  And those that I've found don't fit the theme and style of FontAwesome, which I like.

**Comment by eduvoindo** [comment]
+1 for package

**Comment by baimeizhong** [comment]
+1 whole package

**Comment by DigitalBella** [comment]
+1

**Comment by MarkASmart** [comment]
+1 for package, but mainly crash helmet.

**Comment by tagliala** [comment]
Sorry, I missed this request

I can't keept his open because it doesn't meet our contributing guidelines

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

Even if you need all those icons for your use case, you should open individual request having care of searching for duplicates before, eg: tools: #736
