### ISSUE TITLE
Icon request: fa-audio-description-uk

### ISSUE THREAD

**Issue by PhillUpNorth** [FortAwesome/Font-Awesome#9561]
It is brilliant that the set has the Audio Description logo in it but the standard UK logo is different. Is there a chance to include this one too?

![image](https://cloud.githubusercontent.com/assets/8995982/16809281/9e4ad044-4917-11e6-89c8-e883652f8722.png)

(Without the explanatory text too!)

The above logo is from the UK television regulator OFCOM (http://consumers.ofcom.org.uk/news/broadcasters-to-run-audio-description-campaign/)

Here's an SVG I'm using at the moment: https://www.dropbox.com/s/v3krfj8r61aj86u/Audio%20Description%20%28hollow%29.svg?dl=0

**Comment by casman300** [comment]
+1!!!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome! [Take a look at it here.](https://fontawesome.com/icons/audio-description?f=classic&s=solid)
