### ISSUE TITLE
Icon Request: averge ø

### ISSUE THREAD

**Issue by Hexodus** [FortAwesome/Font-Awesome#9562]
Often usual font provide insufficient **ø** (averge) chars. Would be great to have an icon for this as well. It'll be used very often IMHO.

**Comment by tagliala** [comment]
This is the lower case version of #5852, right?

**Comment by Hexodus** [comment]
Yes, it exactly this ;)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/empty-set?f=classic&s=solid)
