### ISSUE TITLE
Icon request: exercise icons - biking, running, swimming, lifting weights, etc. 

### ISSUE THREAD

**Issue by srour** [FortAwesome/Font-Awesome#958]
Keep up the great work!

**Comment by jaysongo** [comment]
Hi all, this comment/question is a bit late, but I was looking for an icon that represents running: so fa-runner or fa-running.
Before creating an issue, I found a bunch of dupes pointing back to this issue, but this issue is closed requesting that the request be split up. I'm just curious, did anyone _ever_ split them up? Is the request for sports icons back to square one?

Thanks,
jgo
