### ISSUE TITLE
Icon Request: fa-dashed-circle

### ISSUE THREAD

**Issue by jayncoke** [FortAwesome/Font-Awesome#9592]
There really isn't any defacto official GIF icon, but we've been starting to use something like the dashed circle that Facebook uses overtop their posts that are animated GIFs. Pretty much like this: http://image.shutterstock.com/z/stock-vector-play-animation-icon-for-social-networks-circle-gif-sign-370296965.jpg

I'd like to request an icon like that, probably without the "GIF" word inside it and somehow start making the dashed circle icon represent GIFS. The dashed circle lends itself to rotation as well!

If there's a better icon to represent GIFs, I'd love to know!

**Comment by tagliala** [comment]
I would go for plain css, because:

* it needs 3 icons (semi-transparent background `fa-circle`, dashed circle, gif text)
* rotation has issues (ref: #671)
* dashed-circle + gif text will barely suite 14px icon size
* you will need custom css to position icons (`fa-circle` should be larger than the dashed circle)

https://jsfiddle.net/tagliala/6r61fyc7/

Given that, leaving this open as dashed-circle

**Comment by jayncoke** [comment]
Thanks for the response, @tagliala! Yeah, I'm totally ok for just dashed-circle. I agree that you can't make an icon exactly like the image I linked for all the points you made.

**Comment by aethior** [comment]
Hi @jayncoke,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/circle-dashed

Regards.

cc/ @tagliala
