### ISSUE TITLE
Icon Request: fa-assign or fa-user-arrow

### ISSUE THREAD

**Issue by ruimelodev** [FortAwesome/Font-Awesome#9628]
There is no icon to represent assigned stuff for a user or the action to assign stuff to a user for web applications.

I thought a user with an arrow pointing to it would be the best representation:
![icon-assigned-small](https://cloud.githubusercontent.com/assets/16306125/17087601/02411fda-5206-11e6-86a2-e90a52be1f6b.png)
![120x120xassign-task-icon png pagespeed ic phpcht7bau](https://cloud.githubusercontent.com/assets/16306125/17087607/096e0e8a-5206-11e6-9609-78decff7a2c2.jpg)

**Comment by tagliala** [comment]
Related to #1181

**Comment by rajtrivedi2001** [comment]
My Favour for @ruimelodev  for these new type of icons

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
