### ISSUE TITLE
Icon Request: fa-bdsm 

### ISSUE THREAD

**Issue by droidmunkey** [FortAwesome/Font-Awesome#9675]
It's a really simple symbol - explained here: 

https://dominationsubmission.wordpress.com/2012/12/05/the-bdsm-emblem-an-explanation-not-only-for-those-who-dont-know-but-also-for-many-who-might-have-forget-the-meaning-of-it/

"The BDSM emblem has no “obvious” symbolism because it was created to be enigmatic. To the vanilla (anyone out of the BDSM lifestyle) observer who would be put off by BDSM, it is merely an attractive piece of jewelry. Thus, we can wear it freely as a friendly salute, nod, and wink to other BDSMers we should happen to pass on the sidewalks and in the hallways of our daily lives.

To the insider, however, the Emblem is full of meaning.

The three divisions represent the various threesomes of BDSM. First of all, the three divisions of BDSM itself: B&D, D&S, and S&M. Secondly, the three-way creed of BDSM behavior: Safe, Sane, and Consensual. Thirdly, the three divisions of our community: Tops, Bottoms, and Switches.

The resemblance to a three-way variation on the Yin-Yang symbol is not accidental. As the curved outline of Yin and Yang represent the hazy border between where one ends and the other begins, so do the curved borders here represent the indistinct divisions between B&D, D&S, and S&M (Bondage and Discipline, Domination and submission, Sadism and Masochism or sadomasochism
"

**Comment by PandyLegend** [comment]
I vote for this too

**Comment by MaitreV** [comment]
Je suis d accord pour ça

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
