### ISSUE TITLE
get button id on click with fontawesome icons returns undefined

### ISSUE THREAD

**Issue by syednizamudeen** [FortAwesome/Font-Awesome#9775]
Please Check out this [SO Post](http://stackoverflow.com/q/39033237/4221894) for issue
[JSfiddle](http://jsfiddle.net/jvsxo8s0/2/) for demo

**Comment by tagliala** [comment]
Hi,

fontawesome is not involved in this

http://jsfiddle.net/jvsxo8s0/9/

Try clicking on the italic _send_ or _save_

The problem is that you are clicking on another element which has not the id attribute, but this is not the place for this kind of issues, it is a support request, please refer to your SO post
