### ISSUE TITLE
Icon request: icon-assisted wheelchair

### ISSUE THREAD

**Issue by WendyTEC** [FortAwesome/Font-Awesome#9829]
Hi,
Extending your great range of accessibility icons, I'd love to see and **assisted access** icon.  Like the icon we use here - [http://tec.tas.gov.au/LegislativeCouncilElections_2016/LCElection16PollingPlaceLists.html], so that I can use your icons rather than the current images!  would be much appreciated!  
We use this icon to demonstrate that the polling place is suitable for disabled access only with assistance.
thanks in advance!

**Comment by deandreamatias** [comment]
This link is broken

> Hi,
> Extending your great range of accessibility icons, I'd love to see and **assisted access** icon. Like the icon we use here - [http://tec.tas.gov.au/LegislativeCouncilElections_2016/LCElection16PollingPlaceLists.html], so that I can use your icons rather than the current images! would be much appreciated!
> We use this icon to demonstrate that the polling place is suitable for disabled access only with assistance.
> thanks in advance!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
