### ISSUE TITLE
Icon Request: fa-baptism

### ISSUE THREAD

**Issue by ijakic** [FortAwesome/Font-Awesome#9870]
Icon for baptism something like this http://images.clipartpanda.com/baptism-20clipart-diraeR6i9.gif

**Comment by tagliala** [comment]
is this a "brand"? Are there simpler versions of the logo suitable for 14px icon size?

Does #1612 fit the use case?

**Comment by ijakic** [comment]
Unfortunately no :-(
is too "harsh", is it possible to have something like this as it seems easier
http://images.clipartpanda.com/baptism-20clipart-Baptism_Dove-997x1024.jpg

**Comment by Krzysiu** [comment]
ijakic, I think you may have seen image which was posted as a joke. Indeed, that would be harsh. The requested icon is available here (from the first post): https://commons.wikimedia.org/wiki/File:Peace_dove_icon.svg
Could you reply if you uphold your position that's not suitable?

**Comment by sensibleworld** [comment]
Does our current "dove" icon cover this request? https://fontawesome.com/icons/dove?style=solid

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
