### ISSUE TITLE
Icon request: fa-unfold-more + fa-unfold-less

### ISSUE THREAD

**Issue by VeloAddict** [FortAwesome/Font-Awesome#9885]
<img width="364" alt="screen shot 2016-09-08 at 1 10 19 pm" src="https://cloud.githubusercontent.com/assets/36549/18345793/a46df3cc-75c5-11e6-898d-4202921c9389.png">

Use case: content that can be folded, like an accordion.

**Comment by tagliala** [comment]
We need a better tile for this one, it should be related to chevrons

> Use case: content that can be folded, like an accordion.

For this use case, there are widely used couple of icons, such as:
* plus / minus (used at [microsoft.com](https://products.office.com/en-US/try#accordion-#1))
* plus / cross (used at [apple.com](http://www.apple.com/shop/product/MMEF2AM/A/airpods#productInfoSection))
* plus-square-o / minus-square-o
* plus-square / minus-square
* arrow-right / arrow-down
* angle-right / angle-down
* caret-right / caret-down (used at [facebook.com](https://it-it.facebook.com/help/325807937506242))
* chevron-down / chevron-up (used at [facebook.com](https://www.facebook.com/help/325807937506242))
* chevron-right / chevron-down
* arrow-circle-right / arrow-circle-down
* angle-double-right / angle-double-down

You can also use one icon and a css transformation to rotate it by 90 degrees

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
