### ISSUE TITLE
ICON REQUEST: Requesting fa-ubereats 

### ISSUE THREAD

**Issue by BrianKTran** [FortAwesome/Font-Awesome#9931]
I want to announce on [my company website](http://hookipatech.com/) that my front facing product app will be utilizing Uber Eats API to delivery food from user to user. I request an icon to be converted from the [Uber Eats Logo  ](http://www.iclarified.com/images/news/53526/254732/254732-64.png)

I need the icon to be in html code like below: 

`fa-cutlery `
`<i class="fa fa-cutlery fa-stack-1x fa-inverse"></i>`

So code should be something like this : `fa-ubereats`

It was awesome if you can make this happen. 

Thank Font Awesome!!

**Comment by Krzysiu** [comment]
The decision is not up to me, but all I see so far is a lot cash spent on promotion in press and social websites, but user reply is rather low - most comments I see are about problems with application.  I don't think that FA should be overloaded with recent commercial brands which were requested to get more money, not because anybody would use it. The request "from the inside" doesn't look good. And sorry to doubt you, but for the corporation worth $1.5 billion I can't believe it's about helping others but about company gain. PS: I hope I won't be stalked and threatened for my opinion, if these are still your ways like in 2014.

**Comment by BrianKTran** [comment]
hey man thats cool. ill find another way. no ones gonna stalk you or sen your death threats. so do not worry. take it easy bro..
