### ISSUE TITLE
Icon Request: fa-print-plus / fa-print-times

### ISSUE THREAD

**Issue by gquipster** [FortAwesome/Font-Awesome#9943]
Hi

Is it possible to get icons to add/remove printers similar to add/remove users (fa-user-plus / fa-user-times)?

Basically using fa-print with a + or x overlaid as per fa-user-plus

Thanks

**Comment by tagliala** [comment]
Please take a look at #1181 , you will find a solution there

**Comment by gquipster** [comment]
I am for the interim but as we have the precedent of fa-user-plus/fa-user-times it would be nice to have this as a REAL icon rather than a hack

**Comment by tagliala** [comment]
this request is legit, and it is properly open and labeled.

Font Awesome Actions is an amazing project which provides real icons

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
