### ISSUE TITLE
Icon Request: fa-hand-clipboard

### ISSUE THREAD

**Issue by vegasoverdrive** [FortAwesome/Font-Awesome#9991]
hand clipboard icon 
![clipboard](https://cloud.githubusercontent.com/assets/539719/18966481/4cfa3296-864f-11e6-8592-4aca03edcf90.png)
to be used within a healthcare data app

**Comment by tagliala** [comment]
Maybe http://fontawesome.io/icon/clipboard/ does the job

**Comment by yesi79** [comment]
Looks too much like a document, was looking to invoke the idea of a doctor taking notes

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
